from lark_oapi.core.construct import init as init

class ChatCommonHeader:
    chat_id: str | None
    bot_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ChatCommonHeaderBuilder: ...

class ChatCommonHeaderBuilder:
    def __init__(self) -> None: ...
    def chat_id(self, chat_id: str) -> ChatCommonHeaderBuilder: ...
    def bot_id(self, bot_id: str) -> ChatCommonHeaderBuilder: ...
    def build(self) -> ChatCommonHeader: ...
