from .open_failed_user_app_feed_card_item import OpenFailedUserAppFeedCardItem as OpenFailedUserAppFeedCardItem
from lark_oapi.core.construct import init as init

class CreateAppFeedCardResponseBody:
    failed_cards: list[OpenFailedUserAppFeedCardItem] | None
    biz_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateAppFeedCardResponseBodyBuilder: ...

class CreateAppFeedCardResponseBodyBuilder:
    def __init__(self) -> None: ...
    def failed_cards(self, failed_cards: list[OpenFailedUserAppFeedCardItem]) -> CreateAppFeedCardResponseBodyBuilder: ...
    def biz_id(self, biz_id: str) -> CreateAppFeedCardResponseBodyBuilder: ...
    def build(self) -> CreateAppFeedCardResponseBody: ...
