from .create_biz_entity_tag_relation_request_body import CreateBizEntityTagRelationRequestBody as CreateBizEntityTagRelationRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateBizEntityTagRelationRequest(BaseRequest):
    request_body: CreateBizEntityTagRelationRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateBizEntityTagRelationRequestBuilder: ...

class CreateBizEntityTagRelationRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: CreateBizEntityTagRelationRequestBody) -> CreateBizEntityTagRelationRequestBuilder: ...
    def build(self) -> CreateBizEntityTagRelationRequest: ...
