from .feed_group_rules import FeedGroupRules as FeedGroupRules
from lark_oapi.core.construct import init as init

class FeedGroupUpdater:
    group_id: str | None
    name: str | None
    rules: FeedGroupRules | None
    update_fields: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FeedGroupUpdaterBuilder: ...

class FeedGroupUpdaterBuilder:
    def __init__(self) -> None: ...
    def group_id(self, group_id: str) -> FeedGroupUpdaterBuilder: ...
    def name(self, name: str) -> FeedGroupUpdaterBuilder: ...
    def rules(self, rules: FeedGroupRules) -> FeedGroupUpdaterBuilder: ...
    def update_fields(self, update_fields: list[str]) -> FeedGroupUpdaterBuilder: ...
    def build(self) -> FeedGroupUpdater: ...
