from .feed_group_rule import FeedGroupRule as FeedGroupRule
from lark_oapi.core.construct import init as init

class FeedGroupRules:
    rules: list[FeedGroupRule] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FeedGroupRulesBuilder: ...

class FeedGroupRulesBuilder:
    def __init__(self) -> None: ...
    def rules(self, rules: list[FeedGroupRule]) -> FeedGroupRulesBuilder: ...
    def build(self) -> FeedGroupRules: ...
