from lark_oapi.core.construct import init as init

class FeedCardSettingUpdater:
    feed_card_id: str | None
    read_timestamp: str | None
    mute_with_system_message: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FeedCardSettingUpdaterBuilder: ...

class FeedCardSettingUpdaterBuilder:
    def __init__(self) -> None: ...
    def feed_card_id(self, feed_card_id: str) -> FeedCardSettingUpdaterBuilder: ...
    def read_timestamp(self, read_timestamp: str) -> FeedCardSettingUpdaterBuilder: ...
    def mute_with_system_message(self, mute_with_system_message: bool) -> FeedCardSettingUpdaterBuilder: ...
    def build(self) -> FeedCardSettingUpdater: ...
