from lark_oapi.core.construct import init as init

class FeedCardDisplayRuleFailedItem:
    id: str | None
    error_code: int | None
    error_message: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FeedCardDisplayRuleFailedItemBuilder: ...

class FeedCardDisplayRuleFailedItemBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> FeedCardDisplayRuleFailedItemBuilder: ...
    def error_code(self, error_code: int) -> FeedCardDisplayRuleFailedItemBuilder: ...
    def error_message(self, error_message: str) -> FeedCardDisplayRuleFailedItemBuilder: ...
    def build(self) -> FeedCardDisplayRuleFailedItem: ...
