from .feed_group_rule_cond import FeedGroupRuleCond as FeedGroupRuleCond
from lark_oapi.core.construct import init as init

class FeedGroupRule:
    condition: FeedGroupRuleCond | None
    action: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FeedGroupRuleBuilder: ...

class FeedGroupRuleBuilder:
    def __init__(self) -> None: ...
    def condition(self, condition: FeedGroupRuleCond) -> FeedGroupRuleBuilder: ...
    def action(self, action: str) -> FeedGroupRuleBuilder: ...
    def build(self) -> FeedGroupRule: ...
