from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetBizEntityTagRelationRequest(BaseRequest):
    tag_biz_type: str | None
    biz_entity_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetBizEntityTagRelationRequestBuilder: ...

class GetBizEntityTagRelationRequestBuilder:
    def __init__(self) -> None: ...
    def tag_biz_type(self, tag_biz_type: str) -> GetBizEntityTagRelationRequestBuilder: ...
    def biz_entity_id(self, biz_entity_id: str) -> GetBizEntityTagRelationRequestBuilder: ...
    def build(self) -> GetBizEntityTagRelationRequest: ...
