from lark_oapi.core.construct import init as init

class GetBizEntityTagRelationRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetBizEntityTagRelationRequestBodyBuilder: ...

class GetBizEntityTagRelationRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetBizEntityTagRelationRequestBody: ...
