from .feed_group_item import FeedGroupItem as FeedGroupItem
from lark_oapi.core.construct import init as init

class GroupItemFailedReason:
    item: FeedGroupItem | None
    error_code: int | None
    error_message: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GroupItemFailedReasonBuilder: ...

class GroupItemFailedReasonBuilder:
    def __init__(self) -> None: ...
    def item(self, item: FeedGroupItem) -> GroupItemFailedReasonBuilder: ...
    def error_code(self, error_code: int) -> GroupItemFailedReasonBuilder: ...
    def error_message(self, error_message: str) -> GroupItemFailedReasonBuilder: ...
    def build(self) -> GroupItemFailedReason: ...
