from .open_app_feed_card_text import OpenAppFeedCardText as OpenAppFeedCardText
from .open_app_feed_card_url import OpenAppFeedCardUrl as OpenAppFeedCardUrl
from lark_oapi.core.construct import init as init

class OpenAppFeedCardButton:
    multi_url: OpenAppFeedCardUrl | None
    action_type: str | None
    text: OpenAppFeedCardText | None
    button_type: str | None
    action_map: dict[str, str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OpenAppFeedCardButtonBuilder: ...

class OpenAppFeedCardButtonBuilder:
    def __init__(self) -> None: ...
    def multi_url(self, multi_url: OpenAppFeedCardUrl) -> OpenAppFeedCardButtonBuilder: ...
    def action_type(self, action_type: str) -> OpenAppFeedCardButtonBuilder: ...
    def text(self, text: OpenAppFeedCardText) -> OpenAppFeedCardButtonBuilder: ...
    def button_type(self, button_type: str) -> OpenAppFeedCardButtonBuilder: ...
    def action_map(self, action_map: dict[str, str]) -> OpenAppFeedCardButtonBuilder: ...
    def build(self) -> OpenAppFeedCardButton: ...
