from lark_oapi.core.construct import init as init

class OpenFeedStatusLabel:
    text: str | None
    type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OpenFeedStatusLabelBuilder: ...

class OpenFeedStatusLabelBuilder:
    def __init__(self) -> None: ...
    def text(self, text: str) -> OpenFeedStatusLabelBuilder: ...
    def type(self, type: str) -> OpenFeedStatusLabelBuilder: ...
    def build(self) -> OpenFeedStatusLabel: ...
