from lark_oapi.core.construct import init as init

class OpenAppFeedLink:
    link: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OpenAppFeedLinkBuilder: ...

class OpenAppFeedLinkBuilder:
    def __init__(self) -> None: ...
    def link(self, link: str) -> OpenAppFeedLinkBuilder: ...
    def build(self) -> OpenAppFeedLink: ...
