from lark_oapi.core.construct import init as init

class OpenDisplayFeedRule:
    main_rule: str | None
    msg_types: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OpenDisplayFeedRuleBuilder: ...

class OpenDisplayFeedRuleBuilder:
    def __init__(self) -> None: ...
    def main_rule(self, main_rule: str) -> OpenDisplayFeedRuleBuilder: ...
    def msg_types(self, msg_types: list[str]) -> OpenDisplayFeedRuleBuilder: ...
    def build(self) -> OpenDisplayFeedRule: ...
