from .tag_i18n_name import TagI18nName as TagI18nName
from lark_oapi.core.construct import init as init

class TagInfo:
    id: str | None
    tenant_id: str | None
    tag_type: str | None
    name: str | None
    i18n_names: list[TagI18nName] | None
    creator_id: str | None
    create_time: str | None
    update_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TagInfoBuilder: ...

class TagInfoBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> TagInfoBuilder: ...
    def tenant_id(self, tenant_id: str) -> TagInfoBuilder: ...
    def tag_type(self, tag_type: str) -> TagInfoBuilder: ...
    def name(self, name: str) -> TagInfoBuilder: ...
    def i18n_names(self, i18n_names: list[TagI18nName]) -> TagInfoBuilder: ...
    def creator_id(self, creator_id: str) -> TagInfoBuilder: ...
    def create_time(self, create_time: str) -> TagInfoBuilder: ...
    def update_time(self, update_time: str) -> TagInfoBuilder: ...
    def build(self) -> TagInfo: ...
