from lark_oapi.core.construct import init as init

class UnReadUrgentMessage:
    id: str | None
    message_id: str | None
    chatter_id: str | None
    status: int | None
    confirm_time: str | None
    send_time: str | None
    type: int | None
    from_id: str | None
    chat_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UnReadUrgentMessageBuilder: ...

class UnReadUrgentMessageBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> UnReadUrgentMessageBuilder: ...
    def message_id(self, message_id: str) -> UnReadUrgentMessageBuilder: ...
    def chatter_id(self, chatter_id: str) -> UnReadUrgentMessageBuilder: ...
    def status(self, status: int) -> UnReadUrgentMessageBuilder: ...
    def confirm_time(self, confirm_time: str) -> UnReadUrgentMessageBuilder: ...
    def send_time(self, send_time: str) -> UnReadUrgentMessageBuilder: ...
    def type(self, type: int) -> UnReadUrgentMessageBuilder: ...
    def from_id(self, from_id: str) -> UnReadUrgentMessageBuilder: ...
    def chat_id(self, chat_id: str) -> UnReadUrgentMessageBuilder: ...
    def build(self) -> UnReadUrgentMessage: ...
