from lark_oapi.core.construct import init as init

class UpdateBizEntityTagRelationResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateBizEntityTagRelationResponseBodyBuilder: ...

class UpdateBizEntityTagRelationResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> UpdateBizEntityTagRelationResponseBody: ...
