from lark_oapi.core.construct import init as init

class UpdateBizEntityTagRelationRequestBody:
    tag_biz_type: str | None
    biz_entity_id: str | None
    tag_ids: list[str] | None
    bot_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateBizEntityTagRelationRequestBodyBuilder: ...

class UpdateBizEntityTagRelationRequestBodyBuilder:
    def __init__(self) -> None: ...
    def tag_biz_type(self, tag_biz_type: str) -> UpdateBizEntityTagRelationRequestBodyBuilder: ...
    def biz_entity_id(self, biz_entity_id: str) -> UpdateBizEntityTagRelationRequestBodyBuilder: ...
    def tag_ids(self, tag_ids: list[str]) -> UpdateBizEntityTagRelationRequestBodyBuilder: ...
    def bot_id(self, bot_id: str) -> UpdateBizEntityTagRelationRequestBodyBuilder: ...
    def build(self) -> UpdateBizEntityTagRelationRequestBody: ...
