from .open_app_feed_card_buttons import OpenAppFeedCardButtons as OpenAppFeedCardButtons
from lark_oapi.core.construct import init as init

class UpdateChatButtonRequestBody:
    user_ids: list[str] | None
    chat_id: str | None
    buttons: OpenAppFeedCardButtons | None
    bot_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateChatButtonRequestBodyBuilder: ...

class UpdateChatButtonRequestBodyBuilder:
    def __init__(self) -> None: ...
    def user_ids(self, user_ids: list[str]) -> UpdateChatButtonRequestBodyBuilder: ...
    def chat_id(self, chat_id: str) -> UpdateChatButtonRequestBodyBuilder: ...
    def buttons(self, buttons: OpenAppFeedCardButtons) -> UpdateChatButtonRequestBodyBuilder: ...
    def bot_id(self, bot_id: str) -> UpdateChatButtonRequestBodyBuilder: ...
    def build(self) -> UpdateChatButtonRequestBody: ...
