from lark_oapi.core.construct import init as init

class UserOpenAppFeedCardDeleter:
    biz_id: str | None
    user_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserOpenAppFeedCardDeleterBuilder: ...

class UserOpenAppFeedCardDeleterBuilder:
    def __init__(self) -> None: ...
    def biz_id(self, biz_id: str) -> UserOpenAppFeedCardDeleterBuilder: ...
    def user_id(self, user_id: str) -> UserOpenAppFeedCardDeleterBuilder: ...
    def build(self) -> UserOpenAppFeedCardDeleter: ...
