from lark_oapi.core.construct import init as init

class FileConfig:
    file_id: str | None
    format: str | None
    engine_type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FileConfigBuilder: ...

class FileConfigBuilder:
    def __init__(self) -> None: ...
    def file_id(self, file_id: str) -> FileConfigBuilder: ...
    def format(self, format: str) -> FileConfigBuilder: ...
    def engine_type(self, engine_type: str) -> FileConfigBuilder: ...
    def build(self) -> FileConfig: ...
