from lark_oapi.core.construct import init as init

class FileRecognizeSpeechResponseBody:
    recognition_text: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FileRecognizeSpeechResponseBodyBuilder: ...

class FileRecognizeSpeechResponseBodyBuilder:
    def __init__(self) -> None: ...
    def recognition_text(self, recognition_text: str) -> FileRecognizeSpeechResponseBodyBuilder: ...
    def build(self) -> FileRecognizeSpeechResponseBody: ...
