from lark_oapi.core.construct import init as init

class Speech:
    speech: str | None
    speech_key: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SpeechBuilder: ...

class SpeechBuilder:
    def __init__(self) -> None: ...
    def speech(self, speech: str) -> SpeechBuilder: ...
    def speech_key(self, speech_key: str) -> SpeechBuilder: ...
    def build(self) -> Speech: ...
