from lark_oapi.core.construct import init as init

class StreamRecognizeSpeechResponseBody:
    stream_id: str | None
    sequence_id: int | None
    recognition_text: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> StreamRecognizeSpeechResponseBodyBuilder: ...

class StreamRecognizeSpeechResponseBodyBuilder:
    def __init__(self) -> None: ...
    def stream_id(self, stream_id: str) -> StreamRecognizeSpeechResponseBodyBuilder: ...
    def sequence_id(self, sequence_id: int) -> StreamRecognizeSpeechResponseBodyBuilder: ...
    def recognition_text(self, recognition_text: str) -> StreamRecognizeSpeechResponseBodyBuilder: ...
    def build(self) -> StreamRecognizeSpeechResponseBody: ...
