from lark_oapi.core.construct import init as init

class AuthPermissionMemberResponseBody:
    auth_result: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AuthPermissionMemberResponseBodyBuilder: ...

class AuthPermissionMemberResponseBodyBuilder:
    def __init__(self) -> None: ...
    def auth_result(self, auth_result: bool) -> AuthPermissionMemberResponseBodyBuilder: ...
    def build(self) -> AuthPermissionMemberResponseBody: ...
