from lark_oapi.core.construct import init as init

class AuthPermissionMemberRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AuthPermissionMemberRequestBodyBuilder: ...

class AuthPermissionMemberRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> AuthPermissionMemberRequestBody: ...
