from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class AuthPermissionMemberRequest(BaseRequest):
    type: str | None
    action: str | None
    token: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> AuthPermissionMemberRequestBuilder: ...

class AuthPermissionMemberRequestBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> AuthPermissionMemberRequestBuilder: ...
    def action(self, action: str) -> AuthPermissionMemberRequestBuilder: ...
    def token(self, token: str) -> AuthPermissionMemberRequestBuilder: ...
    def build(self) -> AuthPermissionMemberRequest: ...
