from .batch_create_permission_member_request_body import BatchCreatePermissionMemberRequestBody as BatchCreatePermissionMemberRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchCreatePermissionMemberRequest(BaseRequest):
    type: str | None
    need_notification: bool | None
    token: str | None
    request_body: BatchCreatePermissionMemberRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchCreatePermissionMemberRequestBuilder: ...

class BatchCreatePermissionMemberRequestBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> BatchCreatePermissionMemberRequestBuilder: ...
    def need_notification(self, need_notification: bool) -> BatchCreatePermissionMemberRequestBuilder: ...
    def token(self, token: str) -> BatchCreatePermissionMemberRequestBuilder: ...
    def request_body(self, request_body: BatchCreatePermissionMemberRequestBody) -> BatchCreatePermissionMemberRequestBuilder: ...
    def build(self) -> BatchCreatePermissionMemberRequest: ...
