from .batch_query_file_comment_request_body import BatchQueryFileCommentRequestBody as BatchQueryFileCommentRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchQueryFileCommentRequest(BaseRequest):
    file_type: str | None
    user_id_type: str | None
    file_token: str | None
    request_body: BatchQueryFileCommentRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchQueryFileCommentRequestBuilder: ...

class BatchQueryFileCommentRequestBuilder:
    def __init__(self) -> None: ...
    def file_type(self, file_type: str) -> BatchQueryFileCommentRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> BatchQueryFileCommentRequestBuilder: ...
    def file_token(self, file_token: str) -> BatchQueryFileCommentRequestBuilder: ...
    def request_body(self, request_body: BatchQueryFileCommentRequestBody) -> BatchQueryFileCommentRequestBuilder: ...
    def build(self) -> BatchQueryFileCommentRequest: ...
