from .tmp_download_url import TmpDownloadUrl as TmpDownloadUrl
from lark_oapi.core.construct import init as init

class BatchGetTmpDownloadUrlMediaResponseBody:
    tmp_download_urls: list[TmpDownloadUrl] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchGetTmpDownloadUrlMediaResponseBodyBuilder: ...

class BatchGetTmpDownloadUrlMediaResponseBodyBuilder:
    def __init__(self) -> None: ...
    def tmp_download_urls(self, tmp_download_urls: list[TmpDownloadUrl]) -> BatchGetTmpDownloadUrlMediaResponseBodyBuilder: ...
    def build(self) -> BatchGetTmpDownloadUrlMediaResponseBody: ...
