from lark_oapi.core.construct import init as init

class BatchGetTmpDownloadUrlMediaRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchGetTmpDownloadUrlMediaRequestBodyBuilder: ...

class BatchGetTmpDownloadUrlMediaRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> BatchGetTmpDownloadUrlMediaRequestBody: ...
