from .bitable_table_record_action_field_identity import BitableTableRecordActionFieldIdentity as BitableTableRecordActionFieldIdentity
from lark_oapi.core.construct import init as init

class BitableTableRecordActionField:
    field_id: str | None
    field_value: str | None
    field_identity_value: BitableTableRecordActionFieldIdentity | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BitableTableRecordActionFieldBuilder: ...

class BitableTableRecordActionFieldBuilder:
    def __init__(self) -> None: ...
    def field_id(self, field_id: str) -> BitableTableRecordActionFieldBuilder: ...
    def field_value(self, field_value: str) -> BitableTableRecordActionFieldBuilder: ...
    def field_identity_value(self, field_identity_value: BitableTableRecordActionFieldIdentity) -> BitableTableRecordActionFieldBuilder: ...
    def build(self) -> BitableTableRecordActionField: ...
