from lark_oapi.core.construct import init as init

class BitableTableFieldActionValuePropertyAutoSerialOptions:
    type: str | None
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BitableTableFieldActionValuePropertyAutoSerialOptionsBuilder: ...

class BitableTableFieldActionValuePropertyAutoSerialOptionsBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> BitableTableFieldActionValuePropertyAutoSerialOptionsBuilder: ...
    def value(self, value: str) -> BitableTableFieldActionValuePropertyAutoSerialOptionsBuilder: ...
    def build(self) -> BitableTableFieldActionValuePropertyAutoSerialOptions: ...
