from .copy_file_request_body import CopyFileRequestBody as CopyFileRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CopyFileRequest(BaseRequest):
    user_id_type: str | None
    file_token: str | None
    request_body: CopyFileRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CopyFileRequestBuilder: ...

class CopyFileRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> CopyFileRequestBuilder: ...
    def file_token(self, file_token: str) -> CopyFileRequestBuilder: ...
    def request_body(self, request_body: CopyFileRequestBody) -> CopyFileRequestBuilder: ...
    def build(self) -> CopyFileRequest: ...
