from .create_shortcut_file_request_body import CreateShortcutFileRequestBody as CreateShortcutFileRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateShortcutFileRequest(BaseRequest):
    user_id_type: str | None
    request_body: CreateShortcutFileRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateShortcutFileRequestBuilder: ...

class CreateShortcutFileRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> CreateShortcutFileRequestBuilder: ...
    def request_body(self, request_body: CreateShortcutFileRequestBody) -> CreateShortcutFileRequestBuilder: ...
    def build(self) -> CreateShortcutFileRequest: ...
