from .base_member import BaseMember as BaseMember
from lark_oapi.core.construct import init as init

class CreatePermissionMemberResponseBody:
    member: BaseMember | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreatePermissionMemberResponseBodyBuilder: ...

class CreatePermissionMemberResponseBodyBuilder:
    def __init__(self) -> None: ...
    def member(self, member: BaseMember) -> CreatePermissionMemberResponseBodyBuilder: ...
    def build(self) -> CreatePermissionMemberResponseBody: ...
