from lark_oapi.core.construct import init as init

class CreateFileVersionResponseBody:
    name: str | None
    version: str | None
    parent_token: str | None
    owner_id: str | None
    creator_id: str | None
    create_time: int | None
    update_time: int | None
    status: int | None
    obj_type: str | None
    parent_type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateFileVersionResponseBodyBuilder: ...

class CreateFileVersionResponseBodyBuilder:
    def __init__(self) -> None: ...
    def name(self, name: str) -> CreateFileVersionResponseBodyBuilder: ...
    def version(self, version: str) -> CreateFileVersionResponseBodyBuilder: ...
    def parent_token(self, parent_token: str) -> CreateFileVersionResponseBodyBuilder: ...
    def owner_id(self, owner_id: str) -> CreateFileVersionResponseBodyBuilder: ...
    def creator_id(self, creator_id: str) -> CreateFileVersionResponseBodyBuilder: ...
    def create_time(self, create_time: int) -> CreateFileVersionResponseBodyBuilder: ...
    def update_time(self, update_time: int) -> CreateFileVersionResponseBodyBuilder: ...
    def status(self, status: int) -> CreateFileVersionResponseBodyBuilder: ...
    def obj_type(self, obj_type: str) -> CreateFileVersionResponseBodyBuilder: ...
    def parent_type(self, parent_type: str) -> CreateFileVersionResponseBodyBuilder: ...
    def build(self) -> CreateFileVersionResponseBody: ...
