from lark_oapi.core.construct import init as init

class CreateImportTaskResponseBody:
    ticket: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateImportTaskResponseBodyBuilder: ...

class CreateImportTaskResponseBodyBuilder:
    def __init__(self) -> None: ...
    def ticket(self, ticket: str) -> CreateImportTaskResponseBodyBuilder: ...
    def build(self) -> CreateImportTaskResponseBody: ...
