from .file_subscription import FileSubscription as FileSubscription
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateFileSubscriptionRequest(BaseRequest):
    file_token: str | None
    request_body: FileSubscription | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateFileSubscriptionRequestBuilder: ...

class CreateFileSubscriptionRequestBuilder:
    def __init__(self) -> None: ...
    def file_token(self, file_token: str) -> CreateFileSubscriptionRequestBuilder: ...
    def request_body(self, request_body: FileSubscription) -> CreateFileSubscriptionRequestBuilder: ...
    def build(self) -> CreateFileSubscriptionRequest: ...
