from lark_oapi.core.construct import init as init

class CreatePermissionPublicPasswordRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreatePermissionPublicPasswordRequestBodyBuilder: ...

class CreatePermissionPublicPasswordRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> CreatePermissionPublicPasswordRequestBody: ...
