from .delete_permission_member_request_body import DeletePermissionMemberRequestBody as DeletePermissionMemberRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeletePermissionMemberRequest(BaseRequest):
    type: str | None
    member_type: str | None
    token: str | None
    member_id: str | None
    request_body: DeletePermissionMemberRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeletePermissionMemberRequestBuilder: ...

class DeletePermissionMemberRequestBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> DeletePermissionMemberRequestBuilder: ...
    def member_type(self, member_type: str) -> DeletePermissionMemberRequestBuilder: ...
    def token(self, token: str) -> DeletePermissionMemberRequestBuilder: ...
    def member_id(self, member_id: str) -> DeletePermissionMemberRequestBuilder: ...
    def request_body(self, request_body: DeletePermissionMemberRequestBody) -> DeletePermissionMemberRequestBuilder: ...
    def build(self) -> DeletePermissionMemberRequest: ...
