from lark_oapi.core.construct import init as init

class DeleteSubscribeFileResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteSubscribeFileResponseBodyBuilder: ...

class DeleteSubscribeFileResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteSubscribeFileResponseBody: ...
