from lark_oapi.core.construct import init as init

class DeletePermissionPublicPasswordResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeletePermissionPublicPasswordResponseBodyBuilder: ...

class DeletePermissionPublicPasswordResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeletePermissionPublicPasswordResponseBody: ...
