from lark_oapi.core.construct import init as init

class DeleteFileCommentReplyRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteFileCommentReplyRequestBodyBuilder: ...

class DeleteFileCommentReplyRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteFileCommentReplyRequestBody: ...
