from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteFileCommentReplyRequest(BaseRequest):
    file_type: str | None
    file_token: str | None
    comment_id: int | None
    reply_id: int | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteFileCommentReplyRequestBuilder: ...

class DeleteFileCommentReplyRequestBuilder:
    def __init__(self) -> None: ...
    def file_type(self, file_type: str) -> DeleteFileCommentReplyRequestBuilder: ...
    def file_token(self, file_token: str) -> DeleteFileCommentReplyRequestBuilder: ...
    def comment_id(self, comment_id: int) -> DeleteFileCommentReplyRequestBuilder: ...
    def reply_id(self, reply_id: int) -> DeleteFileCommentReplyRequestBuilder: ...
    def build(self) -> DeleteFileCommentReplyRequest: ...
