from lark_oapi.core.construct import init as init

class DepartmentId:
    department_id: str | None
    open_department_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DepartmentIdBuilder: ...

class DepartmentIdBuilder:
    def __init__(self) -> None: ...
    def department_id(self, department_id: str) -> DepartmentIdBuilder: ...
    def open_department_id(self, open_department_id: str) -> DepartmentIdBuilder: ...
    def build(self) -> DepartmentId: ...
