from lark_oapi.core.construct import init as init

class DownloadExportTaskResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DownloadExportTaskResponseBodyBuilder: ...

class DownloadExportTaskResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DownloadExportTaskResponseBody: ...
