from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DownloadExportTaskRequest(BaseRequest):
    file_token: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DownloadExportTaskRequestBuilder: ...

class DownloadExportTaskRequestBuilder:
    def __init__(self) -> None: ...
    def file_token(self, file_token: str) -> DownloadExportTaskRequestBuilder: ...
    def build(self) -> DownloadExportTaskRequest: ...
