from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DownloadMediaRequest(BaseRequest):
    extra: str | None
    file_token: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DownloadMediaRequestBuilder: ...

class DownloadMediaRequestBuilder:
    def __init__(self) -> None: ...
    def extra(self, extra: str) -> DownloadMediaRequestBuilder: ...
    def file_token(self, file_token: str) -> DownloadMediaRequestBuilder: ...
    def build(self) -> DownloadMediaRequest: ...
