from lark_oapi.core.construct import init as init

class FileSearch:
    docs_token: str | None
    docs_type: str | None
    title: str | None
    owner_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FileSearchBuilder: ...

class FileSearchBuilder:
    def __init__(self) -> None: ...
    def docs_token(self, docs_token: str) -> FileSearchBuilder: ...
    def docs_type(self, docs_type: str) -> FileSearchBuilder: ...
    def title(self, title: str) -> FileSearchBuilder: ...
    def owner_id(self, owner_id: str) -> FileSearchBuilder: ...
    def build(self) -> FileSearch: ...
