from .shortcut_info import ShortcutInfo as ShortcutInfo
from lark_oapi.core.construct import init as init

class File:
    token: str | None
    name: str | None
    type: str | None
    parent_token: str | None
    url: str | None
    shortcut_info: ShortcutInfo | None
    created_time: int | None
    modified_time: int | None
    owner_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FileBuilder: ...

class FileBuilder:
    def __init__(self) -> None: ...
    def token(self, token: str) -> FileBuilder: ...
    def name(self, name: str) -> FileBuilder: ...
    def type(self, type: str) -> FileBuilder: ...
    def parent_token(self, parent_token: str) -> FileBuilder: ...
    def url(self, url: str) -> FileBuilder: ...
    def shortcut_info(self, shortcut_info: ShortcutInfo) -> FileBuilder: ...
    def created_time(self, created_time: int) -> FileBuilder: ...
    def modified_time(self, modified_time: int) -> FileBuilder: ...
    def owner_id(self, owner_id: str) -> FileBuilder: ...
    def build(self) -> File: ...
