from lark_oapi.core.construct import init as init

class FileUploadInfo:
    file_name: str | None
    parent_type: str | None
    parent_node: str | None
    size: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FileUploadInfoBuilder: ...

class FileUploadInfoBuilder:
    def __init__(self) -> None: ...
    def file_name(self, file_name: str) -> FileUploadInfoBuilder: ...
    def parent_type(self, parent_type: str) -> FileUploadInfoBuilder: ...
    def parent_node(self, parent_node: str) -> FileUploadInfoBuilder: ...
    def size(self, size: int) -> FileUploadInfoBuilder: ...
    def build(self) -> FileUploadInfo: ...
