from .file_block_change_info import FileBlockChangeInfo as FileBlockChangeInfo
from lark_oapi.core.construct import init as init

class FileChangeInfo:
    start_time: int | None
    changes: list[FileBlockChangeInfo] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FileChangeInfoBuilder: ...

class FileChangeInfoBuilder:
    def __init__(self) -> None: ...
    def start_time(self, start_time: int) -> FileChangeInfoBuilder: ...
    def changes(self, changes: list[FileBlockChangeInfo]) -> FileChangeInfoBuilder: ...
    def build(self) -> FileChangeInfo: ...
