from lark_oapi.core.construct import init as init

class FileStatistics:
    uv: int | None
    pv: int | None
    like_count: int | None
    timestamp: int | None
    uv_today: int | None
    pv_today: int | None
    like_count_today: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FileStatisticsBuilder: ...

class FileStatisticsBuilder:
    def __init__(self) -> None: ...
    def uv(self, uv: int) -> FileStatisticsBuilder: ...
    def pv(self, pv: int) -> FileStatisticsBuilder: ...
    def like_count(self, like_count: int) -> FileStatisticsBuilder: ...
    def timestamp(self, timestamp: int) -> FileStatisticsBuilder: ...
    def uv_today(self, uv_today: int) -> FileStatisticsBuilder: ...
    def pv_today(self, pv_today: int) -> FileStatisticsBuilder: ...
    def like_count_today(self, like_count_today: int) -> FileStatisticsBuilder: ...
    def build(self) -> FileStatistics: ...
