from lark_oapi.core.construct import init as init

class FileBlockChangeInfo:
    block_token: str | None
    block_token_type: str | None
    rev_ranges: list[int] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FileBlockChangeInfoBuilder: ...

class FileBlockChangeInfoBuilder:
    def __init__(self) -> None: ...
    def block_token(self, block_token: str) -> FileBlockChangeInfoBuilder: ...
    def block_token_type(self, block_token_type: str) -> FileBlockChangeInfoBuilder: ...
    def rev_ranges(self, rev_ranges: list[int]) -> FileBlockChangeInfoBuilder: ...
    def build(self) -> FileBlockChangeInfo: ...
