from lark_oapi.core.construct import init as init

class GetFileSubscriptionRequestBody:
    file_type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetFileSubscriptionRequestBodyBuilder: ...

class GetFileSubscriptionRequestBodyBuilder:
    def __init__(self) -> None: ...
    def file_type(self, file_type: str) -> GetFileSubscriptionRequestBodyBuilder: ...
    def build(self) -> GetFileSubscriptionRequestBody: ...
