from lark_oapi.core.construct import init as init

class GetFileStatisticsRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetFileStatisticsRequestBodyBuilder: ...

class GetFileStatisticsRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetFileStatisticsRequestBody: ...
