from lark_oapi.core.construct import init as init

class GetFileSubscriptionResponseBody:
    subscription_id: str | None
    subscription_type: str | None
    is_subcribe: bool | None
    file_type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetFileSubscriptionResponseBodyBuilder: ...

class GetFileSubscriptionResponseBodyBuilder:
    def __init__(self) -> None: ...
    def subscription_id(self, subscription_id: str) -> GetFileSubscriptionResponseBodyBuilder: ...
    def subscription_type(self, subscription_type: str) -> GetFileSubscriptionResponseBodyBuilder: ...
    def is_subcribe(self, is_subcribe: bool) -> GetFileSubscriptionResponseBodyBuilder: ...
    def file_type(self, file_type: str) -> GetFileSubscriptionResponseBodyBuilder: ...
    def build(self) -> GetFileSubscriptionResponseBody: ...
