from lark_oapi.core.construct import init as init

class GetFileVersionRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetFileVersionRequestBodyBuilder: ...

class GetFileVersionRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetFileVersionRequestBody: ...
