from lark_oapi.core.construct import init as init

class GetSubscribeFileRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetSubscribeFileRequestBodyBuilder: ...

class GetSubscribeFileRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetSubscribeFileRequestBody: ...
