from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetImportTaskRequest(BaseRequest):
    ticket: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetImportTaskRequestBuilder: ...

class GetImportTaskRequestBuilder:
    def __init__(self) -> None: ...
    def ticket(self, ticket: str) -> GetImportTaskRequestBuilder: ...
    def build(self) -> GetImportTaskRequest: ...
