from .permission_public import PermissionPublic as PermissionPublic
from lark_oapi.core.construct import init as init

class GetPermissionPublicResponseBody:
    permission_public: PermissionPublic | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetPermissionPublicResponseBodyBuilder: ...

class GetPermissionPublicResponseBodyBuilder:
    def __init__(self) -> None: ...
    def permission_public(self, permission_public: PermissionPublic) -> GetPermissionPublicResponseBodyBuilder: ...
    def build(self) -> GetPermissionPublicResponseBody: ...
