from lark_oapi.core.construct import init as init

class ListFileCommentReplyRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListFileCommentReplyRequestBodyBuilder: ...

class ListFileCommentReplyRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListFileCommentReplyRequestBody: ...
