from lark_oapi.core.construct import init as init

class ListFileViewRecordRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListFileViewRecordRequestBodyBuilder: ...

class ListFileViewRecordRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListFileViewRecordRequestBody: ...
