from .file_view_record import FileViewRecord as FileViewRecord
from lark_oapi.core.construct import init as init

class ListFileViewRecordResponseBody:
    items: list[FileViewRecord] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListFileViewRecordResponseBodyBuilder: ...

class ListFileViewRecordResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[FileViewRecord]) -> ListFileViewRecordResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListFileViewRecordResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListFileViewRecordResponseBodyBuilder: ...
    def build(self) -> ListFileViewRecordResponseBody: ...
