from .version import Version as Version
from lark_oapi.core.construct import init as init

class ListFileVersionResponseBody:
    items: list[Version] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListFileVersionResponseBodyBuilder: ...

class ListFileVersionResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[Version]) -> ListFileVersionResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListFileVersionResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListFileVersionResponseBodyBuilder: ...
    def build(self) -> ListFileVersionResponseBody: ...
