from .member import Member as Member
from lark_oapi.core.construct import init as init

class ListPermissionMemberResponseBody:
    items: list[Member] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListPermissionMemberResponseBodyBuilder: ...

class ListPermissionMemberResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[Member]) -> ListPermissionMemberResponseBodyBuilder: ...
    def build(self) -> ListPermissionMemberResponseBody: ...
