from .file_comment_reply import FileCommentReply as FileCommentReply
from lark_oapi.core.construct import init as init

class ListFileCommentReplyResponseBody:
    items: list[FileCommentReply] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListFileCommentReplyResponseBodyBuilder: ...

class ListFileCommentReplyResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[FileCommentReply]) -> ListFileCommentReplyResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListFileCommentReplyResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListFileCommentReplyResponseBodyBuilder: ...
    def build(self) -> ListFileCommentReplyResponseBody: ...
