from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListFileRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    folder_token: str | None
    order_by: str | None
    direction: str | None
    option: str | None
    user_id_type: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListFileRequestBuilder: ...

class ListFileRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> ListFileRequestBuilder: ...
    def page_token(self, page_token: str) -> ListFileRequestBuilder: ...
    def folder_token(self, folder_token: str) -> ListFileRequestBuilder: ...
    def order_by(self, order_by: str) -> ListFileRequestBuilder: ...
    def direction(self, direction: str) -> ListFileRequestBuilder: ...
    def option(self, option: str) -> ListFileRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> ListFileRequestBuilder: ...
    def build(self) -> ListFileRequest: ...
