from lark_oapi.core.construct import init as init

class ListPermissionMemberRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListPermissionMemberRequestBodyBuilder: ...

class ListPermissionMemberRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListPermissionMemberRequestBody: ...
