from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListFileViewRecordRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    file_type: str | None
    viewer_id_type: str | None
    file_token: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListFileViewRecordRequestBuilder: ...

class ListFileViewRecordRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> ListFileViewRecordRequestBuilder: ...
    def page_token(self, page_token: str) -> ListFileViewRecordRequestBuilder: ...
    def file_type(self, file_type: str) -> ListFileViewRecordRequestBuilder: ...
    def viewer_id_type(self, viewer_id_type: str) -> ListFileViewRecordRequestBuilder: ...
    def file_token(self, file_token: str) -> ListFileViewRecordRequestBuilder: ...
    def build(self) -> ListFileViewRecordRequest: ...
