from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListFileCommentReplyRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    file_type: str | None
    user_id_type: str | None
    file_token: str | None
    comment_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListFileCommentReplyRequestBuilder: ...

class ListFileCommentReplyRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> ListFileCommentReplyRequestBuilder: ...
    def page_token(self, page_token: str) -> ListFileCommentReplyRequestBuilder: ...
    def file_type(self, file_type: str) -> ListFileCommentReplyRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> ListFileCommentReplyRequestBuilder: ...
    def file_token(self, file_token: str) -> ListFileCommentReplyRequestBuilder: ...
    def comment_id(self, comment_id: str) -> ListFileCommentReplyRequestBuilder: ...
    def build(self) -> ListFileCommentReplyRequest: ...
