from lark_oapi.core.construct import init as init

class MediaUploadInfo:
    file_name: str | None
    parent_type: str | None
    size: int | None
    parent_node: str | None
    extra: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MediaUploadInfoBuilder: ...

class MediaUploadInfoBuilder:
    def __init__(self) -> None: ...
    def file_name(self, file_name: str) -> MediaUploadInfoBuilder: ...
    def parent_type(self, parent_type: str) -> MediaUploadInfoBuilder: ...
    def size(self, size: int) -> MediaUploadInfoBuilder: ...
    def parent_node(self, parent_node: str) -> MediaUploadInfoBuilder: ...
    def extra(self, extra: str) -> MediaUploadInfoBuilder: ...
    def build(self) -> MediaUploadInfo: ...
