from lark_oapi.core.construct import init as init

class Member:
    member_type: str | None
    member_id: str | None
    perm: str | None
    perm_type: str | None
    type: str | None
    name: str | None
    avatar: str | None
    external_label: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MemberBuilder: ...

class MemberBuilder:
    def __init__(self) -> None: ...
    def member_type(self, member_type: str) -> MemberBuilder: ...
    def member_id(self, member_id: str) -> MemberBuilder: ...
    def perm(self, perm: str) -> MemberBuilder: ...
    def perm_type(self, perm_type: str) -> MemberBuilder: ...
    def type(self, type: str) -> MemberBuilder: ...
    def name(self, name: str) -> MemberBuilder: ...
    def avatar(self, avatar: str) -> MemberBuilder: ...
    def external_label(self, external_label: bool) -> MemberBuilder: ...
    def build(self) -> Member: ...
