from lark_oapi.core.construct import init as init

class Meta:
    doc_token: str | None
    doc_type: str | None
    title: str | None
    owner_id: str | None
    create_time: int | None
    latest_modify_user: str | None
    latest_modify_time: int | None
    url: str | None
    sec_label_name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MetaBuilder: ...

class MetaBuilder:
    def __init__(self) -> None: ...
    def doc_token(self, doc_token: str) -> MetaBuilder: ...
    def doc_type(self, doc_type: str) -> MetaBuilder: ...
    def title(self, title: str) -> MetaBuilder: ...
    def owner_id(self, owner_id: str) -> MetaBuilder: ...
    def create_time(self, create_time: int) -> MetaBuilder: ...
    def latest_modify_user(self, latest_modify_user: str) -> MetaBuilder: ...
    def latest_modify_time(self, latest_modify_time: int) -> MetaBuilder: ...
    def url(self, url: str) -> MetaBuilder: ...
    def sec_label_name(self, sec_label_name: str) -> MetaBuilder: ...
    def build(self) -> Meta: ...
