from lark_oapi.core.construct import init as init

class MoveFileRequestBody:
    type: str | None
    folder_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MoveFileRequestBodyBuilder: ...

class MoveFileRequestBodyBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> MoveFileRequestBodyBuilder: ...
    def folder_token(self, folder_token: str) -> MoveFileRequestBodyBuilder: ...
    def build(self) -> MoveFileRequestBody: ...
