from .move_file_request_body import MoveFileRequestBody as MoveFileRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class MoveFileRequest(BaseRequest):
    file_token: str | None
    request_body: MoveFileRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> MoveFileRequestBuilder: ...

class MoveFileRequestBuilder:
    def __init__(self) -> None: ...
    def file_token(self, file_token: str) -> MoveFileRequestBuilder: ...
    def request_body(self, request_body: MoveFileRequestBody) -> MoveFileRequestBuilder: ...
    def build(self) -> MoveFileRequest: ...
