from lark_oapi.core.construct import init as init

class PatchFileSubscriptionResponseBody:
    subscription_id: str | None
    subscription_type: str | None
    is_subcribe: bool | None
    file_type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchFileSubscriptionResponseBodyBuilder: ...

class PatchFileSubscriptionResponseBodyBuilder:
    def __init__(self) -> None: ...
    def subscription_id(self, subscription_id: str) -> PatchFileSubscriptionResponseBodyBuilder: ...
    def subscription_type(self, subscription_type: str) -> PatchFileSubscriptionResponseBodyBuilder: ...
    def is_subcribe(self, is_subcribe: bool) -> PatchFileSubscriptionResponseBodyBuilder: ...
    def file_type(self, file_type: str) -> PatchFileSubscriptionResponseBodyBuilder: ...
    def build(self) -> PatchFileSubscriptionResponseBody: ...
