from .permission_public import PermissionPublic as PermissionPublic
from lark_oapi.core.construct import init as init

class PatchPermissionPublicResponseBody:
    permission_public: PermissionPublic | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchPermissionPublicResponseBodyBuilder: ...

class PatchPermissionPublicResponseBodyBuilder:
    def __init__(self) -> None: ...
    def permission_public(self, permission_public: PermissionPublic) -> PatchPermissionPublicResponseBodyBuilder: ...
    def build(self) -> PatchPermissionPublicResponseBody: ...
