from lark_oapi.core.construct import init as init

class PatchFileCommentRequestBody:
    is_solved: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchFileCommentRequestBodyBuilder: ...

class PatchFileCommentRequestBodyBuilder:
    def __init__(self) -> None: ...
    def is_solved(self, is_solved: bool) -> PatchFileCommentRequestBodyBuilder: ...
    def build(self) -> PatchFileCommentRequestBody: ...
