from lark_oapi.core.construct import init as init

class PermissionPublic:
    external_access: bool | None
    security_entity: str | None
    comment_entity: str | None
    share_entity: str | None
    link_share_entity: str | None
    invite_external: bool | None
    lock_switch: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PermissionPublicBuilder: ...

class PermissionPublicBuilder:
    def __init__(self) -> None: ...
    def external_access(self, external_access: bool) -> PermissionPublicBuilder: ...
    def security_entity(self, security_entity: str) -> PermissionPublicBuilder: ...
    def comment_entity(self, comment_entity: str) -> PermissionPublicBuilder: ...
    def share_entity(self, share_entity: str) -> PermissionPublicBuilder: ...
    def link_share_entity(self, link_share_entity: str) -> PermissionPublicBuilder: ...
    def invite_external(self, invite_external: bool) -> PermissionPublicBuilder: ...
    def lock_switch(self, lock_switch: bool) -> PermissionPublicBuilder: ...
    def build(self) -> PermissionPublic: ...
