from lark_oapi.core.construct import init as init

class PermissionPublicRequest:
    external_access: bool | None
    security_entity: str | None
    comment_entity: str | None
    share_entity: str | None
    link_share_entity: str | None
    invite_external: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PermissionPublicRequestBuilder: ...

class PermissionPublicRequestBuilder:
    def __init__(self) -> None: ...
    def external_access(self, external_access: bool) -> PermissionPublicRequestBuilder: ...
    def security_entity(self, security_entity: str) -> PermissionPublicRequestBuilder: ...
    def comment_entity(self, comment_entity: str) -> PermissionPublicRequestBuilder: ...
    def share_entity(self, share_entity: str) -> PermissionPublicRequestBuilder: ...
    def link_share_entity(self, link_share_entity: str) -> PermissionPublicRequestBuilder: ...
    def invite_external(self, invite_external: bool) -> PermissionPublicRequestBuilder: ...
    def build(self) -> PermissionPublicRequest: ...
