from lark_oapi.core.construct import init as init

class Property:
    key: str | None
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PropertyBuilder: ...

class PropertyBuilder:
    def __init__(self) -> None: ...
    def key(self, key: str) -> PropertyBuilder: ...
    def value(self, value: str) -> PropertyBuilder: ...
    def build(self) -> Property: ...
