from .file_comment_reply import FileCommentReply as FileCommentReply
from lark_oapi.core.construct import init as init

class ReplyList:
    replies: list[FileCommentReply] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReplyListBuilder: ...

class ReplyListBuilder:
    def __init__(self) -> None: ...
    def replies(self, replies: list[FileCommentReply]) -> ReplyListBuilder: ...
    def build(self) -> ReplyList: ...
