from lark_oapi.core.construct import init as init

class RequestDoc:
    doc_token: str | None
    doc_type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RequestDocBuilder: ...

class RequestDocBuilder:
    def __init__(self) -> None: ...
    def doc_token(self, doc_token: str) -> RequestDocBuilder: ...
    def doc_type(self, doc_type: str) -> RequestDocBuilder: ...
    def build(self) -> RequestDoc: ...
