from lark_oapi.core.construct import init as init

class TaskCheckFileRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TaskCheckFileRequestBodyBuilder: ...

class TaskCheckFileRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> TaskCheckFileRequestBody: ...
