from lark_oapi.core.construct import init as init

class TextRun:
    text: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TextRunBuilder: ...

class TextRunBuilder:
    def __init__(self) -> None: ...
    def text(self, text: str) -> TextRunBuilder: ...
    def build(self) -> TextRun: ...
