from lark_oapi.core.construct import init as init

class TransferOwnerPermissionMemberResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TransferOwnerPermissionMemberResponseBodyBuilder: ...

class TransferOwnerPermissionMemberResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> TransferOwnerPermissionMemberResponseBody: ...
