from lark_oapi.core.construct import init as init

class UploadFinishFileRequestBody:
    upload_id: str | None
    block_num: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UploadFinishFileRequestBodyBuilder: ...

class UploadFinishFileRequestBodyBuilder:
    def __init__(self) -> None: ...
    def upload_id(self, upload_id: str) -> UploadFinishFileRequestBodyBuilder: ...
    def block_num(self, block_num: int) -> UploadFinishFileRequestBodyBuilder: ...
    def build(self) -> UploadFinishFileRequestBody: ...
