from .media_upload_info import MediaUploadInfo as MediaUploadInfo
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UploadPrepareMediaRequest(BaseRequest):
    request_body: MediaUploadInfo | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UploadPrepareMediaRequestBuilder: ...

class UploadPrepareMediaRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: MediaUploadInfo) -> UploadPrepareMediaRequestBuilder: ...
    def build(self) -> UploadPrepareMediaRequest: ...
