from .upload_part_media_request_body import UploadPartMediaRequestBody as UploadPartMediaRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UploadPartMediaRequest(BaseRequest):
    request_body: UploadPartMediaRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UploadPartMediaRequestBuilder: ...

class UploadPartMediaRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: UploadPartMediaRequestBody) -> UploadPartMediaRequestBuilder: ...
    def build(self) -> UploadPartMediaRequest: ...
