from lark_oapi.core.construct import init as init

class UploadPartMediaResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UploadPartMediaResponseBodyBuilder: ...

class UploadPartMediaResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> UploadPartMediaResponseBody: ...
