from lark_oapi.core.construct import init as init
from typing import Any, IO

class UploadPartMediaRequestBody:
    upload_id: str | None
    seq: int | None
    size: int | None
    checksum: str | None
    file: IO[Any] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UploadPartMediaRequestBodyBuilder: ...

class UploadPartMediaRequestBodyBuilder:
    def __init__(self) -> None: ...
    def upload_id(self, upload_id: str) -> UploadPartMediaRequestBodyBuilder: ...
    def seq(self, seq: int) -> UploadPartMediaRequestBodyBuilder: ...
    def size(self, size: int) -> UploadPartMediaRequestBodyBuilder: ...
    def checksum(self, checksum: str) -> UploadPartMediaRequestBodyBuilder: ...
    def file(self, file: IO[Any]) -> UploadPartMediaRequestBodyBuilder: ...
    def build(self) -> UploadPartMediaRequestBody: ...
