from .upload_finish_media_request_body import UploadFinishMediaRequestBody as UploadFinishMediaRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UploadFinishMediaRequest(BaseRequest):
    request_body: UploadFinishMediaRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UploadFinishMediaRequestBuilder: ...

class UploadFinishMediaRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: UploadFinishMediaRequestBody) -> UploadFinishMediaRequestBuilder: ...
    def build(self) -> UploadFinishMediaRequest: ...
