from lark_oapi.core.construct import init as init

class UploadAllMediaResponseBody:
    file_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UploadAllMediaResponseBodyBuilder: ...

class UploadAllMediaResponseBodyBuilder:
    def __init__(self) -> None: ...
    def file_token(self, file_token: str) -> UploadAllMediaResponseBodyBuilder: ...
    def build(self) -> UploadAllMediaResponseBody: ...
