from lark_oapi.core.construct import init as init

class UploadPrepareMediaResponseBody:
    upload_id: str | None
    block_size: int | None
    block_num: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UploadPrepareMediaResponseBodyBuilder: ...

class UploadPrepareMediaResponseBodyBuilder:
    def __init__(self) -> None: ...
    def upload_id(self, upload_id: str) -> UploadPrepareMediaResponseBodyBuilder: ...
    def block_size(self, block_size: int) -> UploadPrepareMediaResponseBodyBuilder: ...
    def block_num(self, block_num: int) -> UploadPrepareMediaResponseBodyBuilder: ...
    def build(self) -> UploadPrepareMediaResponseBody: ...
