from lark_oapi.core.construct import init as init
from typing import Any, IO

class UploadPartFileRequestBody:
    upload_id: str | None
    seq: int | None
    size: int | None
    checksum: str | None
    file: IO[Any] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UploadPartFileRequestBodyBuilder: ...

class UploadPartFileRequestBodyBuilder:
    def __init__(self) -> None: ...
    def upload_id(self, upload_id: str) -> UploadPartFileRequestBodyBuilder: ...
    def seq(self, seq: int) -> UploadPartFileRequestBodyBuilder: ...
    def size(self, size: int) -> UploadPartFileRequestBodyBuilder: ...
    def checksum(self, checksum: str) -> UploadPartFileRequestBodyBuilder: ...
    def file(self, file: IO[Any]) -> UploadPartFileRequestBodyBuilder: ...
    def build(self) -> UploadPartFileRequestBody: ...
