from lark_oapi.core.construct import init as init

class UploadPartFileResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UploadPartFileResponseBodyBuilder: ...

class UploadPartFileResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> UploadPartFileResponseBody: ...
