from lark_oapi.core.construct import init as init

class UploadFinishFileResponseBody:
    file_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UploadFinishFileResponseBodyBuilder: ...

class UploadFinishFileResponseBodyBuilder:
    def __init__(self) -> None: ...
    def file_token(self, file_token: str) -> UploadFinishFileResponseBodyBuilder: ...
    def build(self) -> UploadFinishFileResponseBody: ...
