from .upload_part_file_request_body import UploadPartFileRequestBody as UploadPartFileRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UploadPartFileRequest(BaseRequest):
    request_body: UploadPartFileRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UploadPartFileRequestBuilder: ...

class UploadPartFileRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: UploadPartFileRequestBody) -> UploadPartFileRequestBuilder: ...
    def build(self) -> UploadPartFileRequest: ...
