from lark_oapi.core.construct import init as init

class AvatarInfo:
    avatar_72: str | None
    avatar_240: str | None
    avatar_640: str | None
    avatar_origin: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AvatarInfoBuilder: ...

class AvatarInfoBuilder:
    def __init__(self) -> None: ...
    def avatar_72(self, avatar_72: str) -> AvatarInfoBuilder: ...
    def avatar_240(self, avatar_240: str) -> AvatarInfoBuilder: ...
    def avatar_640(self, avatar_640: str) -> AvatarInfoBuilder: ...
    def avatar_origin(self, avatar_origin: str) -> AvatarInfoBuilder: ...
    def build(self) -> AvatarInfo: ...
