from lark_oapi.core.construct import init as init

class BatchCreateFunctionalRoleMemberRequestBody:
    members: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchCreateFunctionalRoleMemberRequestBodyBuilder: ...

class BatchCreateFunctionalRoleMemberRequestBodyBuilder:
    def __init__(self) -> None: ...
    def members(self, members: list[str]) -> BatchCreateFunctionalRoleMemberRequestBodyBuilder: ...
    def build(self) -> BatchCreateFunctionalRoleMemberRequestBody: ...
