from .batch_create_functional_role_member_request_body import BatchCreateFunctionalRoleMemberRequestBody as BatchCreateFunctionalRoleMemberRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchCreateFunctionalRoleMemberRequest(BaseRequest):
    user_id_type: str | None
    role_id: str | None
    request_body: BatchCreateFunctionalRoleMemberRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchCreateFunctionalRoleMemberRequestBuilder: ...

class BatchCreateFunctionalRoleMemberRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> BatchCreateFunctionalRoleMemberRequestBuilder: ...
    def role_id(self, role_id: str) -> BatchCreateFunctionalRoleMemberRequestBuilder: ...
    def request_body(self, request_body: BatchCreateFunctionalRoleMemberRequestBody) -> BatchCreateFunctionalRoleMemberRequestBuilder: ...
    def build(self) -> BatchCreateFunctionalRoleMemberRequest: ...
