from .batch_get_id_user_request_body import BatchGetIdUserRequestBody as BatchGetIdUserRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchGetIdUserRequest(BaseRequest):
    user_id_type: str | None
    request_body: BatchGetIdUserRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchGetIdUserRequestBuilder: ...

class BatchGetIdUserRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> BatchGetIdUserRequestBuilder: ...
    def request_body(self, request_body: BatchGetIdUserRequestBody) -> BatchGetIdUserRequestBuilder: ...
    def build(self) -> BatchGetIdUserRequest: ...
