from .bind_department_unit_request_body import BindDepartmentUnitRequestBody as BindDepartmentUnitRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BindDepartmentUnitRequest(BaseRequest):
    request_body: BindDepartmentUnitRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BindDepartmentUnitRequestBuilder: ...

class BindDepartmentUnitRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: BindDepartmentUnitRequestBody) -> BindDepartmentUnitRequestBuilder: ...
    def build(self) -> BindDepartmentUnitRequest: ...
