from lark_oapi.core.construct import init as init

class BindDepartmentUnitRequestBody:
    unit_id: str | None
    department_id: str | None
    department_id_type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BindDepartmentUnitRequestBodyBuilder: ...

class BindDepartmentUnitRequestBodyBuilder:
    def __init__(self) -> None: ...
    def unit_id(self, unit_id: str) -> BindDepartmentUnitRequestBodyBuilder: ...
    def department_id(self, department_id: str) -> BindDepartmentUnitRequestBodyBuilder: ...
    def department_id_type(self, department_id_type: str) -> BindDepartmentUnitRequestBodyBuilder: ...
    def build(self) -> BindDepartmentUnitRequestBody: ...
