from .department import Department as Department
from lark_oapi.core.construct import init as init

class ChildrenDepartmentResponseBody:
    has_more: bool | None
    page_token: str | None
    items: list[Department] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ChildrenDepartmentResponseBodyBuilder: ...

class ChildrenDepartmentResponseBodyBuilder:
    def __init__(self) -> None: ...
    def has_more(self, has_more: bool) -> ChildrenDepartmentResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ChildrenDepartmentResponseBodyBuilder: ...
    def items(self, items: list[Department]) -> ChildrenDepartmentResponseBodyBuilder: ...
    def build(self) -> ChildrenDepartmentResponseBody: ...
