from .group import Group as Group
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateGroupRequest(BaseRequest):
    user_id_type: str | None
    department_id_type: str | None
    request_body: Group | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateGroupRequestBuilder: ...

class CreateGroupRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> CreateGroupRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> CreateGroupRequestBuilder: ...
    def request_body(self, request_body: Group) -> CreateGroupRequestBuilder: ...
    def build(self) -> CreateGroupRequest: ...
