from .create_unit_request_body import CreateUnitRequestBody as CreateUnitRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateUnitRequest(BaseRequest):
    request_body: CreateUnitRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateUnitRequestBuilder: ...

class CreateUnitRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: CreateUnitRequestBody) -> CreateUnitRequestBuilder: ...
    def build(self) -> CreateUnitRequest: ...
