from .department import Department as Department
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateDepartmentRequest(BaseRequest):
    user_id_type: str | None
    department_id_type: str | None
    client_token: str | None
    request_body: Department | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateDepartmentRequestBuilder: ...

class CreateDepartmentRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> CreateDepartmentRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> CreateDepartmentRequestBuilder: ...
    def client_token(self, client_token: str) -> CreateDepartmentRequestBuilder: ...
    def request_body(self, request_body: Department) -> CreateDepartmentRequestBuilder: ...
    def build(self) -> CreateDepartmentRequest: ...
