from .custom_attr_option import CustomAttrOption as CustomAttrOption
from lark_oapi.core.construct import init as init

class CustomAttrOptions:
    default_option_id: str | None
    option_type: str | None
    options: list[CustomAttrOption] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CustomAttrOptionsBuilder: ...

class CustomAttrOptionsBuilder:
    def __init__(self) -> None: ...
    def default_option_id(self, default_option_id: str) -> CustomAttrOptionsBuilder: ...
    def option_type(self, option_type: str) -> CustomAttrOptionsBuilder: ...
    def options(self, options: list[CustomAttrOption]) -> CustomAttrOptionsBuilder: ...
    def build(self) -> CustomAttrOptions: ...
