from lark_oapi.core.construct import init as init

class CustomAttrEvent:
    contact_field_key: list[str] | None
    allow_open_query: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CustomAttrEventBuilder: ...

class CustomAttrEventBuilder:
    def __init__(self) -> None: ...
    def contact_field_key(self, contact_field_key: list[str]) -> CustomAttrEventBuilder: ...
    def allow_open_query(self, allow_open_query: bool) -> CustomAttrEventBuilder: ...
    def build(self) -> CustomAttrEvent: ...
