from .custom_attr_options import CustomAttrOptions as CustomAttrOptions
from .i18n_content import I18nContent as I18nContent
from lark_oapi.core.construct import init as init

class CustomAttr:
    id: str | None
    type: str | None
    options: CustomAttrOptions | None
    i18n_name: list[I18nContent] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CustomAttrBuilder: ...

class CustomAttrBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> CustomAttrBuilder: ...
    def type(self, type: str) -> CustomAttrBuilder: ...
    def options(self, options: CustomAttrOptions) -> CustomAttrBuilder: ...
    def i18n_name(self, i18n_name: list[I18nContent]) -> CustomAttrBuilder: ...
    def build(self) -> CustomAttr: ...
