from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteJobFamilyRequest(BaseRequest):
    job_family_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteJobFamilyRequestBuilder: ...

class DeleteJobFamilyRequestBuilder:
    def __init__(self) -> None: ...
    def job_family_id(self, job_family_id: str) -> DeleteJobFamilyRequestBuilder: ...
    def build(self) -> DeleteJobFamilyRequest: ...
