from .delete_user_request_body import DeleteUserRequestBody as DeleteUserRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteUserRequest(BaseRequest):
    user_id_type: str | None
    user_id: str | None
    request_body: DeleteUserRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteUserRequestBuilder: ...

class DeleteUserRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> DeleteUserRequestBuilder: ...
    def user_id(self, user_id: str) -> DeleteUserRequestBuilder: ...
    def request_body(self, request_body: DeleteUserRequestBody) -> DeleteUserRequestBuilder: ...
    def build(self) -> DeleteUserRequest: ...
