from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteFunctionalRoleRequest(BaseRequest):
    role_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteFunctionalRoleRequestBuilder: ...

class DeleteFunctionalRoleRequestBuilder:
    def __init__(self) -> None: ...
    def role_id(self, role_id: str) -> DeleteFunctionalRoleRequestBuilder: ...
    def build(self) -> DeleteFunctionalRoleRequest: ...
