from lark_oapi.core.construct import init as init

class DeleteJobFamilyResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteJobFamilyResponseBodyBuilder: ...

class DeleteJobFamilyResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteJobFamilyResponseBody: ...
