from lark_oapi.core.construct import init as init

class DeleteEmployeeTypeEnumResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteEmployeeTypeEnumResponseBodyBuilder: ...

class DeleteEmployeeTypeEnumResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteEmployeeTypeEnumResponseBody: ...
