from lark_oapi.core.construct import init as init

class DeleteJobLevelResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteJobLevelResponseBodyBuilder: ...

class DeleteJobLevelResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteJobLevelResponseBody: ...
