from lark_oapi.core.construct import init as init

class DeleteFunctionalRoleResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteFunctionalRoleResponseBodyBuilder: ...

class DeleteFunctionalRoleResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteFunctionalRoleResponseBody: ...
