from lark_oapi.core.construct import init as init

class DeleteEmployeeTypeEnumRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteEmployeeTypeEnumRequestBodyBuilder: ...

class DeleteEmployeeTypeEnumRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteEmployeeTypeEnumRequestBody: ...
