from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteUnitRequest(BaseRequest):
    unit_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteUnitRequestBuilder: ...

class DeleteUnitRequestBuilder:
    def __init__(self) -> None: ...
    def unit_id(self, unit_id: str) -> DeleteUnitRequestBuilder: ...
    def build(self) -> DeleteUnitRequest: ...
