from lark_oapi.core.construct import init as init

class DepartmentUnit:
    unit_id: str | None
    unit_type: str | None
    unit_name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DepartmentUnitBuilder: ...

class DepartmentUnitBuilder:
    def __init__(self) -> None: ...
    def unit_id(self, unit_id: str) -> DepartmentUnitBuilder: ...
    def unit_type(self, unit_type: str) -> DepartmentUnitBuilder: ...
    def unit_name(self, unit_name: str) -> DepartmentUnitBuilder: ...
    def build(self) -> DepartmentUnit: ...
