from .i18n_content import I18nContent as I18nContent
from lark_oapi.core.construct import init as init

class EmployeeTypeEnum:
    enum_id: str | None
    enum_value: int | None
    content: str | None
    enum_type: int | None
    enum_status: int | None
    i18n_content: list[I18nContent] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EmployeeTypeEnumBuilder: ...

class EmployeeTypeEnumBuilder:
    def __init__(self) -> None: ...
    def enum_id(self, enum_id: str) -> EmployeeTypeEnumBuilder: ...
    def enum_value(self, enum_value: int) -> EmployeeTypeEnumBuilder: ...
    def content(self, content: str) -> EmployeeTypeEnumBuilder: ...
    def enum_type(self, enum_type: int) -> EmployeeTypeEnumBuilder: ...
    def enum_status(self, enum_status: int) -> EmployeeTypeEnumBuilder: ...
    def i18n_content(self, i18n_content: list[I18nContent]) -> EmployeeTypeEnumBuilder: ...
    def build(self) -> EmployeeTypeEnum: ...
