from lark_oapi.core.construct import init as init

class FunctionalRoleMember:
    user_id: str | None
    scope_type: str | None
    department_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FunctionalRoleMemberBuilder: ...

class FunctionalRoleMemberBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: str) -> FunctionalRoleMemberBuilder: ...
    def scope_type(self, scope_type: str) -> FunctionalRoleMemberBuilder: ...
    def department_ids(self, department_ids: list[str]) -> FunctionalRoleMemberBuilder: ...
    def build(self) -> FunctionalRoleMember: ...
