from lark_oapi.core.construct import init as init

class GetGroupRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetGroupRequestBodyBuilder: ...

class GetGroupRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetGroupRequestBody: ...
