from lark_oapi.core.construct import init as init

class GetJobLevelRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetJobLevelRequestBodyBuilder: ...

class GetJobLevelRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetJobLevelRequestBody: ...
