from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetJobLevelRequest(BaseRequest):
    job_level_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetJobLevelRequestBuilder: ...

class GetJobLevelRequestBuilder:
    def __init__(self) -> None: ...
    def job_level_id(self, job_level_id: str) -> GetJobLevelRequestBuilder: ...
    def build(self) -> GetJobLevelRequest: ...
