from lark_oapi.core.construct import init as init

class GetUnitRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetUnitRequestBodyBuilder: ...

class GetUnitRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetUnitRequestBody: ...
