from .job_title import JobTitle as JobTitle
from lark_oapi.core.construct import init as init

class GetJobTitleResponseBody:
    job_title: JobTitle | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetJobTitleResponseBodyBuilder: ...

class GetJobTitleResponseBodyBuilder:
    def __init__(self) -> None: ...
    def job_title(self, job_title: JobTitle) -> GetJobTitleResponseBodyBuilder: ...
    def build(self) -> GetJobTitleResponseBody: ...
