from .group import Group as Group
from lark_oapi.core.construct import init as init

class GetGroupResponseBody:
    group: Group | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetGroupResponseBodyBuilder: ...

class GetGroupResponseBodyBuilder:
    def __init__(self) -> None: ...
    def group(self, group: Group) -> GetGroupResponseBodyBuilder: ...
    def build(self) -> GetGroupResponseBody: ...
