from .work_city import WorkCity as WorkCity
from lark_oapi.core.construct import init as init

class GetWorkCityResponseBody:
    work_city: WorkCity | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetWorkCityResponseBodyBuilder: ...

class GetWorkCityResponseBodyBuilder:
    def __init__(self) -> None: ...
    def work_city(self, work_city: WorkCity) -> GetWorkCityResponseBodyBuilder: ...
    def build(self) -> GetWorkCityResponseBody: ...
