from .job_family import JobFamily as JobFamily
from lark_oapi.core.construct import init as init

class GetJobFamilyResponseBody:
    job_family: JobFamily | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetJobFamilyResponseBodyBuilder: ...

class GetJobFamilyResponseBodyBuilder:
    def __init__(self) -> None: ...
    def job_family(self, job_family: JobFamily) -> GetJobFamilyResponseBodyBuilder: ...
    def build(self) -> GetJobFamilyResponseBody: ...
