from .i18n_content import I18nContent as I18nContent
from lark_oapi.core.construct import init as init

class JobTitle:
    job_title_id: str | None
    name: str | None
    i18n_name: list[I18nContent] | None
    status: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobTitleBuilder: ...

class JobTitleBuilder:
    def __init__(self) -> None: ...
    def job_title_id(self, job_title_id: str) -> JobTitleBuilder: ...
    def name(self, name: str) -> JobTitleBuilder: ...
    def i18n_name(self, i18n_name: list[I18nContent]) -> JobTitleBuilder: ...
    def status(self, status: bool) -> JobTitleBuilder: ...
    def build(self) -> JobTitle: ...
