from .i18n_content import I18nContent as I18nContent
from lark_oapi.core.construct import init as init

class JobFamily:
    name: str | None
    description: str | None
    parent_job_family_id: str | None
    status: bool | None
    i18n_name: list[I18nContent] | None
    i18n_description: list[I18nContent] | None
    job_family_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobFamilyBuilder: ...

class JobFamilyBuilder:
    def __init__(self) -> None: ...
    def name(self, name: str) -> JobFamilyBuilder: ...
    def description(self, description: str) -> JobFamilyBuilder: ...
    def parent_job_family_id(self, parent_job_family_id: str) -> JobFamilyBuilder: ...
    def status(self, status: bool) -> JobFamilyBuilder: ...
    def i18n_name(self, i18n_name: list[I18nContent]) -> JobFamilyBuilder: ...
    def i18n_description(self, i18n_description: list[I18nContent]) -> JobFamilyBuilder: ...
    def job_family_id(self, job_family_id: str) -> JobFamilyBuilder: ...
    def build(self) -> JobFamily: ...
