from .i18n_content import I18nContent as I18nContent
from lark_oapi.core.construct import init as init

class JobLevel:
    name: str | None
    description: str | None
    order: int | None
    status: bool | None
    job_level_id: str | None
    i18n_name: list[I18nContent] | None
    i18n_description: list[I18nContent] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobLevelBuilder: ...

class JobLevelBuilder:
    def __init__(self) -> None: ...
    def name(self, name: str) -> JobLevelBuilder: ...
    def description(self, description: str) -> JobLevelBuilder: ...
    def order(self, order: int) -> JobLevelBuilder: ...
    def status(self, status: bool) -> JobLevelBuilder: ...
    def job_level_id(self, job_level_id: str) -> JobLevelBuilder: ...
    def i18n_name(self, i18n_name: list[I18nContent]) -> JobLevelBuilder: ...
    def i18n_description(self, i18n_description: list[I18nContent]) -> JobLevelBuilder: ...
    def build(self) -> JobLevel: ...
