from .custom_attr import CustomAttr as CustomAttr
from lark_oapi.core.construct import init as init

class ListCustomAttrResponseBody:
    items: list[CustomAttr] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListCustomAttrResponseBodyBuilder: ...

class ListCustomAttrResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[CustomAttr]) -> ListCustomAttrResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListCustomAttrResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListCustomAttrResponseBodyBuilder: ...
    def build(self) -> ListCustomAttrResponseBody: ...
