from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListUserRequest(BaseRequest):
    user_id_type: str | None
    department_id_type: str | None
    department_id: str | None
    page_token: str | None
    page_size: int | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListUserRequestBuilder: ...

class ListUserRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> ListUserRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> ListUserRequestBuilder: ...
    def department_id(self, department_id: str) -> ListUserRequestBuilder: ...
    def page_token(self, page_token: str) -> ListUserRequestBuilder: ...
    def page_size(self, page_size: int) -> ListUserRequestBuilder: ...
    def build(self) -> ListUserRequest: ...
