from lark_oapi.core.construct import init as init

class ListUnitRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListUnitRequestBodyBuilder: ...

class ListUnitRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListUnitRequestBody: ...
