from lark_oapi.core.construct import init as init

class ListDepartmentUnitRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListDepartmentUnitRequestBodyBuilder: ...

class ListDepartmentUnitRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListDepartmentUnitRequestBody: ...
