from lark_oapi.core.construct import init as init

class ListJobLevelRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListJobLevelRequestBodyBuilder: ...

class ListJobLevelRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListJobLevelRequestBody: ...
