from .user import User as User
from lark_oapi.core.construct import init as init

class ListUserResponseBody:
    has_more: bool | None
    page_token: str | None
    items: list[User] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListUserResponseBodyBuilder: ...

class ListUserResponseBodyBuilder:
    def __init__(self) -> None: ...
    def has_more(self, has_more: bool) -> ListUserResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListUserResponseBodyBuilder: ...
    def items(self, items: list[User]) -> ListUserResponseBodyBuilder: ...
    def build(self) -> ListUserResponseBody: ...
