from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListFunctionalRoleMemberRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    user_id_type: str | None
    department_id_type: str | None
    role_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListFunctionalRoleMemberRequestBuilder: ...

class ListFunctionalRoleMemberRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> ListFunctionalRoleMemberRequestBuilder: ...
    def page_token(self, page_token: str) -> ListFunctionalRoleMemberRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> ListFunctionalRoleMemberRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> ListFunctionalRoleMemberRequestBuilder: ...
    def role_id(self, role_id: str) -> ListFunctionalRoleMemberRequestBuilder: ...
    def build(self) -> ListFunctionalRoleMemberRequest: ...
