from lark_oapi.core.construct import init as init

class ListJobTitleRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListJobTitleRequestBodyBuilder: ...

class ListJobTitleRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListJobTitleRequestBody: ...
