from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListEmployeeTypeEnumRequest(BaseRequest):
    page_token: str | None
    page_size: int | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListEmployeeTypeEnumRequestBuilder: ...

class ListEmployeeTypeEnumRequestBuilder:
    def __init__(self) -> None: ...
    def page_token(self, page_token: str) -> ListEmployeeTypeEnumRequestBuilder: ...
    def page_size(self, page_size: int) -> ListEmployeeTypeEnumRequestBuilder: ...
    def build(self) -> ListEmployeeTypeEnumRequest: ...
