from .unit_department import UnitDepartment as UnitDepartment
from lark_oapi.core.construct import init as init

class ListDepartmentUnitResponseBody:
    departmentlist: list[UnitDepartment] | None
    has_more: bool | None
    page_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListDepartmentUnitResponseBodyBuilder: ...

class ListDepartmentUnitResponseBodyBuilder:
    def __init__(self) -> None: ...
    def departmentlist(self, departmentlist: list[UnitDepartment]) -> ListDepartmentUnitResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListDepartmentUnitResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListDepartmentUnitResponseBodyBuilder: ...
    def build(self) -> ListDepartmentUnitResponseBody: ...
