from .functional_role_member import FunctionalRoleMember as FunctionalRoleMember
from lark_oapi.core.construct import init as init

class ListFunctionalRoleMemberResponseBody:
    members: list[FunctionalRoleMember] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListFunctionalRoleMemberResponseBodyBuilder: ...

class ListFunctionalRoleMemberResponseBodyBuilder:
    def __init__(self) -> None: ...
    def members(self, members: list[FunctionalRoleMember]) -> ListFunctionalRoleMemberResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListFunctionalRoleMemberResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListFunctionalRoleMemberResponseBodyBuilder: ...
    def build(self) -> ListFunctionalRoleMemberResponseBody: ...
