from lark_oapi.core.construct import init as init

class ListScopeResponseBody:
    department_ids: list[str] | None
    user_ids: list[str] | None
    group_ids: list[str] | None
    has_more: bool | None
    page_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListScopeResponseBodyBuilder: ...

class ListScopeResponseBodyBuilder:
    def __init__(self) -> None: ...
    def department_ids(self, department_ids: list[str]) -> ListScopeResponseBodyBuilder: ...
    def user_ids(self, user_ids: list[str]) -> ListScopeResponseBodyBuilder: ...
    def group_ids(self, group_ids: list[str]) -> ListScopeResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListScopeResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListScopeResponseBodyBuilder: ...
    def build(self) -> ListScopeResponseBody: ...
