from lark_oapi.core.construct import init as init

class MemberBelongGroupRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MemberBelongGroupRequestBodyBuilder: ...

class MemberBelongGroupRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> MemberBelongGroupRequestBody: ...
