from lark_oapi.core.construct import init as init

class Memberlist:
    member_id: str | None
    member_type: str | None
    member_id_type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MemberlistBuilder: ...

class MemberlistBuilder:
    def __init__(self) -> None: ...
    def member_id(self, member_id: str) -> MemberlistBuilder: ...
    def member_type(self, member_type: str) -> MemberlistBuilder: ...
    def member_id_type(self, member_id_type: str) -> MemberlistBuilder: ...
    def build(self) -> Memberlist: ...
