from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class MemberBelongGroupRequest(BaseRequest):
    member_id: str | None
    member_id_type: str | None
    group_type: int | None
    page_size: int | None
    page_token: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> MemberBelongGroupRequestBuilder: ...

class MemberBelongGroupRequestBuilder:
    def __init__(self) -> None: ...
    def member_id(self, member_id: str) -> MemberBelongGroupRequestBuilder: ...
    def member_id_type(self, member_id_type: str) -> MemberBelongGroupRequestBuilder: ...
    def group_type(self, group_type: int) -> MemberBelongGroupRequestBuilder: ...
    def page_size(self, page_size: int) -> MemberBelongGroupRequestBuilder: ...
    def page_token(self, page_token: str) -> MemberBelongGroupRequestBuilder: ...
    def build(self) -> MemberBelongGroupRequest: ...
