from lark_oapi.core.construct import init as init

class OldUserObject:
    department_ids: list[str] | None
    open_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OldUserObjectBuilder: ...

class OldUserObjectBuilder:
    def __init__(self) -> None: ...
    def department_ids(self, department_ids: list[str]) -> OldUserObjectBuilder: ...
    def open_id(self, open_id: str) -> OldUserObjectBuilder: ...
    def build(self) -> OldUserObject: ...
