from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ParentDepartmentRequest(BaseRequest):
    user_id_type: str | None
    department_id_type: str | None
    department_id: str | None
    page_token: str | None
    page_size: int | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ParentDepartmentRequestBuilder: ...

class ParentDepartmentRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> ParentDepartmentRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> ParentDepartmentRequestBuilder: ...
    def department_id(self, department_id: str) -> ParentDepartmentRequestBuilder: ...
    def page_token(self, page_token: str) -> ParentDepartmentRequestBuilder: ...
    def page_size(self, page_size: int) -> ParentDepartmentRequestBuilder: ...
    def build(self) -> ParentDepartmentRequest: ...
