from .user import User as User
from lark_oapi.core.construct import init as init

class PatchUserResponseBody:
    user: User | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchUserResponseBodyBuilder: ...

class PatchUserResponseBodyBuilder:
    def __init__(self) -> None: ...
    def user(self, user: User) -> PatchUserResponseBodyBuilder: ...
    def build(self) -> PatchUserResponseBody: ...
