from .group import Group as Group
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PatchGroupRequest(BaseRequest):
    user_id_type: str | None
    department_id_type: str | None
    group_id: str | None
    request_body: Group | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PatchGroupRequestBuilder: ...

class PatchGroupRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> PatchGroupRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> PatchGroupRequestBuilder: ...
    def group_id(self, group_id: str) -> PatchGroupRequestBuilder: ...
    def request_body(self, request_body: Group) -> PatchGroupRequestBuilder: ...
    def build(self) -> PatchGroupRequest: ...
