from .remove_group_member_request_body import RemoveGroupMemberRequestBody as RemoveGroupMemberRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class RemoveGroupMemberRequest(BaseRequest):
    group_id: str | None
    request_body: RemoveGroupMemberRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> RemoveGroupMemberRequestBuilder: ...

class RemoveGroupMemberRequestBuilder:
    def __init__(self) -> None: ...
    def group_id(self, group_id: str) -> RemoveGroupMemberRequestBuilder: ...
    def request_body(self, request_body: RemoveGroupMemberRequestBody) -> RemoveGroupMemberRequestBuilder: ...
    def build(self) -> RemoveGroupMemberRequest: ...
