from lark_oapi.core.construct import init as init

class RemoveGroupMemberResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RemoveGroupMemberResponseBodyBuilder: ...

class RemoveGroupMemberResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> RemoveGroupMemberResponseBody: ...
