from .resurrect_user_request_body import ResurrectUserRequestBody as ResurrectUserRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ResurrectUserRequest(BaseRequest):
    user_id_type: str | None
    department_id_type: str | None
    user_id: int | None
    request_body: ResurrectUserRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ResurrectUserRequestBuilder: ...

class ResurrectUserRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> ResurrectUserRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> ResurrectUserRequestBuilder: ...
    def user_id(self, user_id: int) -> ResurrectUserRequestBuilder: ...
    def request_body(self, request_body: ResurrectUserRequestBody) -> ResurrectUserRequestBuilder: ...
    def build(self) -> ResurrectUserRequest: ...
