from lark_oapi.core.construct import init as init

class ResurrectUserResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ResurrectUserResponseBodyBuilder: ...

class ResurrectUserResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ResurrectUserResponseBody: ...
