from .scopes_functional_role_member_request_body import ScopesFunctionalRoleMemberRequestBody as ScopesFunctionalRoleMemberRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ScopesFunctionalRoleMemberRequest(BaseRequest):
    user_id_type: str | None
    department_id_type: str | None
    role_id: str | None
    request_body: ScopesFunctionalRoleMemberRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ScopesFunctionalRoleMemberRequestBuilder: ...

class ScopesFunctionalRoleMemberRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> ScopesFunctionalRoleMemberRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> ScopesFunctionalRoleMemberRequestBuilder: ...
    def role_id(self, role_id: str) -> ScopesFunctionalRoleMemberRequestBuilder: ...
    def request_body(self, request_body: ScopesFunctionalRoleMemberRequestBody) -> ScopesFunctionalRoleMemberRequestBuilder: ...
    def build(self) -> ScopesFunctionalRoleMemberRequest: ...
