from lark_oapi.core.construct import init as init

class SearchDepartmentRequestBody:
    query: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SearchDepartmentRequestBodyBuilder: ...

class SearchDepartmentRequestBodyBuilder:
    def __init__(self) -> None: ...
    def query(self, query: str) -> SearchDepartmentRequestBodyBuilder: ...
    def build(self) -> SearchDepartmentRequestBody: ...
