from .memberlist import Memberlist as Memberlist
from lark_oapi.core.construct import init as init

class SimplelistGroupMemberResponseBody:
    memberlist: list[Memberlist] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SimplelistGroupMemberResponseBodyBuilder: ...

class SimplelistGroupMemberResponseBodyBuilder:
    def __init__(self) -> None: ...
    def memberlist(self, memberlist: list[Memberlist]) -> SimplelistGroupMemberResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> SimplelistGroupMemberResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> SimplelistGroupMemberResponseBodyBuilder: ...
    def build(self) -> SimplelistGroupMemberResponseBody: ...
