from .unbind_department_unit_request_body import UnbindDepartmentUnitRequestBody as UnbindDepartmentUnitRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UnbindDepartmentUnitRequest(BaseRequest):
    request_body: UnbindDepartmentUnitRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UnbindDepartmentUnitRequestBuilder: ...

class UnbindDepartmentUnitRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: UnbindDepartmentUnitRequestBody) -> UnbindDepartmentUnitRequestBuilder: ...
    def build(self) -> UnbindDepartmentUnitRequest: ...
