from lark_oapi.core.construct import init as init

class UnbindDepartmentChatDepartmentRequestBody:
    department_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UnbindDepartmentChatDepartmentRequestBodyBuilder: ...

class UnbindDepartmentChatDepartmentRequestBodyBuilder:
    def __init__(self) -> None: ...
    def department_id(self, department_id: str) -> UnbindDepartmentChatDepartmentRequestBodyBuilder: ...
    def build(self) -> UnbindDepartmentChatDepartmentRequestBody: ...
