from .employee_type_enum import EmployeeTypeEnum as EmployeeTypeEnum
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UpdateEmployeeTypeEnumRequest(BaseRequest):
    enum_id: str | None
    request_body: EmployeeTypeEnum | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UpdateEmployeeTypeEnumRequestBuilder: ...

class UpdateEmployeeTypeEnumRequestBuilder:
    def __init__(self) -> None: ...
    def enum_id(self, enum_id: str) -> UpdateEmployeeTypeEnumRequestBuilder: ...
    def request_body(self, request_body: EmployeeTypeEnum) -> UpdateEmployeeTypeEnumRequestBuilder: ...
    def build(self) -> UpdateEmployeeTypeEnumRequest: ...
