from .job_family import JobFamily as JobFamily
from lark_oapi.core.construct import init as init

class UpdateJobFamilyResponseBody:
    job_family: JobFamily | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateJobFamilyResponseBodyBuilder: ...

class UpdateJobFamilyResponseBodyBuilder:
    def __init__(self) -> None: ...
    def job_family(self, job_family: JobFamily) -> UpdateJobFamilyResponseBodyBuilder: ...
    def build(self) -> UpdateJobFamilyResponseBody: ...
