from lark_oapi.core.construct import init as init

class UpdateDepartmentIdDepartmentRequestBody:
    new_department_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateDepartmentIdDepartmentRequestBodyBuilder: ...

class UpdateDepartmentIdDepartmentRequestBodyBuilder:
    def __init__(self) -> None: ...
    def new_department_id(self, new_department_id: str) -> UpdateDepartmentIdDepartmentRequestBodyBuilder: ...
    def build(self) -> UpdateDepartmentIdDepartmentRequestBody: ...
