from lark_oapi.core.construct import init as init

class UserPosition:
    position_code: str | None
    position_name: str | None
    department_id: str | None
    leader_user_id: str | None
    leader_position_code: str | None
    is_major: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserPositionBuilder: ...

class UserPositionBuilder:
    def __init__(self) -> None: ...
    def position_code(self, position_code: str) -> UserPositionBuilder: ...
    def position_name(self, position_name: str) -> UserPositionBuilder: ...
    def department_id(self, department_id: str) -> UserPositionBuilder: ...
    def leader_user_id(self, leader_user_id: str) -> UserPositionBuilder: ...
    def leader_position_code(self, leader_position_code: str) -> UserPositionBuilder: ...
    def is_major(self, is_major: bool) -> UserPositionBuilder: ...
    def build(self) -> UserPosition: ...
