from lark_oapi.core.construct import init as init

class UserOrder:
    department_id: str | None
    user_order: int | None
    department_order: int | None
    is_primary_dept: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserOrderBuilder: ...

class UserOrderBuilder:
    def __init__(self) -> None: ...
    def department_id(self, department_id: str) -> UserOrderBuilder: ...
    def user_order(self, user_order: int) -> UserOrderBuilder: ...
    def department_order(self, department_order: int) -> UserOrderBuilder: ...
    def is_primary_dept(self, is_primary_dept: bool) -> UserOrderBuilder: ...
    def build(self) -> UserOrder: ...
