from lark_oapi.core.construct import init as init

class UserDepartmentInfo:
    department_id: int | None
    user_order: int | None
    department_order: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserDepartmentInfoBuilder: ...

class UserDepartmentInfoBuilder:
    def __init__(self) -> None: ...
    def department_id(self, department_id: int) -> UserDepartmentInfoBuilder: ...
    def user_order(self, user_order: int) -> UserDepartmentInfoBuilder: ...
    def department_order(self, department_order: int) -> UserDepartmentInfoBuilder: ...
    def build(self) -> UserDepartmentInfo: ...
