from .avatar_info import AvatarInfo as AvatarInfo
from .department_detail import DepartmentDetail as DepartmentDetail
from .notification_option import NotificationOption as NotificationOption
from .user_assign_info import UserAssignInfo as UserAssignInfo
from .user_custom_attr import UserCustomAttr as UserCustomAttr
from .user_order import UserOrder as UserOrder
from .user_position import UserPosition as UserPosition
from .user_status import UserStatus as UserStatus
from lark_oapi.core.construct import init as init

class User:
    union_id: str | None
    user_id: str | None
    open_id: str | None
    name: str | None
    en_name: str | None
    nickname: str | None
    email: str | None
    mobile: str | None
    mobile_visible: bool | None
    gender: int | None
    avatar_key: str | None
    avatar: AvatarInfo | None
    status: UserStatus | None
    department_ids: list[str] | None
    leader_user_id: str | None
    city: str | None
    country: str | None
    work_station: str | None
    join_time: int | None
    is_tenant_manager: bool | None
    employee_no: str | None
    employee_type: int | None
    positions: list[UserPosition] | None
    orders: list[UserOrder] | None
    custom_attrs: list[UserCustomAttr] | None
    enterprise_email: str | None
    idp_type: str | None
    time_zone: str | None
    description: str | None
    job_title: str | None
    need_send_notification: bool | None
    notification_option: NotificationOption | None
    is_frozen: bool | None
    geo: str | None
    job_level_id: str | None
    job_family_id: str | None
    subscription_ids: list[int] | None
    assign_info: list[UserAssignInfo] | None
    department_path: list[DepartmentDetail] | None
    dotted_line_leader_user_ids: list[int] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserBuilder: ...

class UserBuilder:
    def __init__(self) -> None: ...
    def union_id(self, union_id: str) -> UserBuilder: ...
    def user_id(self, user_id: str) -> UserBuilder: ...
    def open_id(self, open_id: str) -> UserBuilder: ...
    def name(self, name: str) -> UserBuilder: ...
    def en_name(self, en_name: str) -> UserBuilder: ...
    def nickname(self, nickname: str) -> UserBuilder: ...
    def email(self, email: str) -> UserBuilder: ...
    def mobile(self, mobile: str) -> UserBuilder: ...
    def mobile_visible(self, mobile_visible: bool) -> UserBuilder: ...
    def gender(self, gender: int) -> UserBuilder: ...
    def avatar_key(self, avatar_key: str) -> UserBuilder: ...
    def avatar(self, avatar: AvatarInfo) -> UserBuilder: ...
    def status(self, status: UserStatus) -> UserBuilder: ...
    def department_ids(self, department_ids: list[str]) -> UserBuilder: ...
    def leader_user_id(self, leader_user_id: str) -> UserBuilder: ...
    def city(self, city: str) -> UserBuilder: ...
    def country(self, country: str) -> UserBuilder: ...
    def work_station(self, work_station: str) -> UserBuilder: ...
    def join_time(self, join_time: int) -> UserBuilder: ...
    def is_tenant_manager(self, is_tenant_manager: bool) -> UserBuilder: ...
    def employee_no(self, employee_no: str) -> UserBuilder: ...
    def employee_type(self, employee_type: int) -> UserBuilder: ...
    def positions(self, positions: list[UserPosition]) -> UserBuilder: ...
    def orders(self, orders: list[UserOrder]) -> UserBuilder: ...
    def custom_attrs(self, custom_attrs: list[UserCustomAttr]) -> UserBuilder: ...
    def enterprise_email(self, enterprise_email: str) -> UserBuilder: ...
    def idp_type(self, idp_type: str) -> UserBuilder: ...
    def time_zone(self, time_zone: str) -> UserBuilder: ...
    def description(self, description: str) -> UserBuilder: ...
    def job_title(self, job_title: str) -> UserBuilder: ...
    def need_send_notification(self, need_send_notification: bool) -> UserBuilder: ...
    def notification_option(self, notification_option: NotificationOption) -> UserBuilder: ...
    def is_frozen(self, is_frozen: bool) -> UserBuilder: ...
    def geo(self, geo: str) -> UserBuilder: ...
    def job_level_id(self, job_level_id: str) -> UserBuilder: ...
    def job_family_id(self, job_family_id: str) -> UserBuilder: ...
    def subscription_ids(self, subscription_ids: list[int]) -> UserBuilder: ...
    def assign_info(self, assign_info: list[UserAssignInfo]) -> UserBuilder: ...
    def department_path(self, department_path: list[DepartmentDetail]) -> UserBuilder: ...
    def dotted_line_leader_user_ids(self, dotted_line_leader_user_ids: list[int]) -> UserBuilder: ...
    def build(self) -> User: ...
