from .user_status import UserStatus as UserStatus
from lark_oapi.core.construct import init as init

class UserContactInfo:
    user_id: str | None
    mobile: str | None
    email: str | None
    status: UserStatus | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserContactInfoBuilder: ...

class UserContactInfoBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: str) -> UserContactInfoBuilder: ...
    def mobile(self, mobile: str) -> UserContactInfoBuilder: ...
    def email(self, email: str) -> UserContactInfoBuilder: ...
    def status(self, status: UserStatus) -> UserContactInfoBuilder: ...
    def build(self) -> UserContactInfo: ...
