from .i18n_content import I18nContent as I18nContent
from lark_oapi.core.construct import init as init

class WorkCity:
    work_city_id: str | None
    name: str | None
    i18n_name: list[I18nContent] | None
    status: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WorkCityBuilder: ...

class WorkCityBuilder:
    def __init__(self) -> None: ...
    def work_city_id(self, work_city_id: str) -> WorkCityBuilder: ...
    def name(self, name: str) -> WorkCityBuilder: ...
    def i18n_name(self, i18n_name: list[I18nContent]) -> WorkCityBuilder: ...
    def status(self, status: bool) -> WorkCityBuilder: ...
    def build(self) -> WorkCity: ...
