from enum import Enum

class AppType(Enum):
    SELF = ...
    ISV = ...

class HttpMethod(Enum):
    GET = ...
    HEAD = ...
    POST = ...
    PUT = ...
    PATCH = ...
    DELETE = ...
    CONNECT = ...
    OPTIONS = ...
    TRACE = ...

class LogLevel(Enum):
    DEBUG = 10
    INFO = 20
    WARNING = 30
    ERROR = 40
    CRITICAL = 50

class AccessTokenType(Enum):
    TENANT = ...
    APP = ...
    USER = ...
