from ..model.create_app_data_asset_request import CreateAppDataAssetRequest as CreateAppDataAssetRequest
from ..model.create_app_data_asset_response import CreateAppDataAssetResponse as CreateAppDataAssetResponse
from ..model.delete_app_data_asset_request import DeleteAppDataAssetRequest as DeleteAppDataAssetRequest
from ..model.delete_app_data_asset_response import DeleteAppDataAssetResponse as DeleteAppDataAssetResponse
from ..model.get_app_data_asset_request import GetAppDataAssetRequest as GetAppDataAssetRequest
from ..model.get_app_data_asset_response import GetAppDataAssetResponse as GetAppDataAssetResponse
from ..model.list_app_data_asset_request import ListAppDataAssetRequest as ListAppDataAssetRequest
from ..model.list_app_data_asset_response import ListAppDataAssetResponse as ListAppDataAssetResponse
from ..model.upload_file_app_data_asset_request import UploadFileAppDataAssetRequest as UploadFileAppDataAssetRequest
from ..model.upload_file_app_data_asset_response import UploadFileAppDataAssetResponse as UploadFileAppDataAssetResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files

class AppDataAsset:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def create(self, request: CreateAppDataAssetRequest, option: RequestOption | None = None) -> CreateAppDataAssetResponse: ...
    async def acreate(self, request: CreateAppDataAssetRequest, option: RequestOption | None = None) -> CreateAppDataAssetResponse: ...
    def delete(self, request: DeleteAppDataAssetRequest, option: RequestOption | None = None) -> DeleteAppDataAssetResponse: ...
    async def adelete(self, request: DeleteAppDataAssetRequest, option: RequestOption | None = None) -> DeleteAppDataAssetResponse: ...
    def get(self, request: GetAppDataAssetRequest, option: RequestOption | None = None) -> GetAppDataAssetResponse: ...
    async def aget(self, request: GetAppDataAssetRequest, option: RequestOption | None = None) -> GetAppDataAssetResponse: ...
    def list(self, request: ListAppDataAssetRequest, option: RequestOption | None = None) -> ListAppDataAssetResponse: ...
    async def alist(self, request: ListAppDataAssetRequest, option: RequestOption | None = None) -> ListAppDataAssetResponse: ...
    def upload_file(self, request: UploadFileAppDataAssetRequest, option: RequestOption | None = None) -> UploadFileAppDataAssetResponse: ...
    async def aupload_file(self, request: UploadFileAppDataAssetRequest, option: RequestOption | None = None) -> UploadFileAppDataAssetResponse: ...
