from ..model.batch_create_app_role_member_request import BatchCreateAppRoleMemberRequest as BatchCreateAppRoleMemberRequest
from ..model.batch_create_app_role_member_response import BatchCreateAppRoleMemberResponse as BatchCreateAppRoleMemberResponse
from ..model.batch_delete_app_role_member_request import BatchDeleteAppRoleMemberRequest as BatchDeleteAppRoleMemberRequest
from ..model.batch_delete_app_role_member_response import BatchDeleteAppRoleMemberResponse as BatchDeleteAppRoleMemberResponse
from ..model.create_app_role_member_request import CreateAppRoleMemberRequest as CreateAppRoleMemberRequest
from ..model.create_app_role_member_response import CreateAppRoleMemberResponse as CreateAppRoleMemberResponse
from ..model.delete_app_role_member_request import DeleteAppRoleMemberRequest as DeleteAppRoleMemberRequest
from ..model.delete_app_role_member_response import DeleteAppRoleMemberResponse as DeleteAppRoleMemberResponse
from ..model.list_app_role_member_request import ListAppRoleMemberRequest as ListAppRoleMemberRequest
from ..model.list_app_role_member_response import ListAppRoleMemberResponse as ListAppRoleMemberResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class AppRoleMember:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def batch_create(self, request: BatchCreateAppRoleMemberRequest, option: RequestOption | None = None) -> BatchCreateAppRoleMemberResponse: ...
    async def abatch_create(self, request: BatchCreateAppRoleMemberRequest, option: RequestOption | None = None) -> BatchCreateAppRoleMemberResponse: ...
    def batch_delete(self, request: BatchDeleteAppRoleMemberRequest, option: RequestOption | None = None) -> BatchDeleteAppRoleMemberResponse: ...
    async def abatch_delete(self, request: BatchDeleteAppRoleMemberRequest, option: RequestOption | None = None) -> BatchDeleteAppRoleMemberResponse: ...
    def create(self, request: CreateAppRoleMemberRequest, option: RequestOption | None = None) -> CreateAppRoleMemberResponse: ...
    async def acreate(self, request: CreateAppRoleMemberRequest, option: RequestOption | None = None) -> CreateAppRoleMemberResponse: ...
    def delete(self, request: DeleteAppRoleMemberRequest, option: RequestOption | None = None) -> DeleteAppRoleMemberResponse: ...
    async def adelete(self, request: DeleteAppRoleMemberRequest, option: RequestOption | None = None) -> DeleteAppRoleMemberResponse: ...
    def list(self, request: ListAppRoleMemberRequest, option: RequestOption | None = None) -> ListAppRoleMemberResponse: ...
    async def alist(self, request: ListAppRoleMemberRequest, option: RequestOption | None = None) -> ListAppRoleMemberResponse: ...
