from ..model.create_cost_center_request import CreateCostCenterRequest as CreateCostCenterRequest
from ..model.create_cost_center_response import CreateCostCenterResponse as CreateCostCenterResponse
from ..model.delete_cost_center_request import DeleteCostCenterRequest as DeleteCostCenterRequest
from ..model.delete_cost_center_response import DeleteCostCenterResponse as DeleteCostCenterResponse
from ..model.patch_cost_center_request import PatchCostCenterRequest as PatchCostCenterRequest
from ..model.patch_cost_center_response import PatchCostCenterResponse as PatchCostCenterResponse
from ..model.query_recent_change_cost_center_request import QueryRecentChangeCostCenterRequest as QueryRecentChangeCostCenterRequest
from ..model.query_recent_change_cost_center_response import QueryRecentChangeCostCenterResponse as QueryRecentChangeCostCenterResponse
from ..model.search_cost_center_request import SearchCostCenterRequest as SearchCostCenterRequest
from ..model.search_cost_center_response import SearchCostCenterResponse as SearchCostCenterResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class CostCenter:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def create(self, request: CreateCostCenterRequest, option: RequestOption | None = None) -> CreateCostCenterResponse: ...
    async def acreate(self, request: CreateCostCenterRequest, option: RequestOption | None = None) -> CreateCostCenterResponse: ...
    def delete(self, request: DeleteCostCenterRequest, option: RequestOption | None = None) -> DeleteCostCenterResponse: ...
    async def adelete(self, request: DeleteCostCenterRequest, option: RequestOption | None = None) -> DeleteCostCenterResponse: ...
    def patch(self, request: PatchCostCenterRequest, option: RequestOption | None = None) -> PatchCostCenterResponse: ...
    async def apatch(self, request: PatchCostCenterRequest, option: RequestOption | None = None) -> PatchCostCenterResponse: ...
    def query_recent_change(self, request: QueryRecentChangeCostCenterRequest, option: RequestOption | None = None) -> QueryRecentChangeCostCenterResponse: ...
    async def aquery_recent_change(self, request: QueryRecentChangeCostCenterRequest, option: RequestOption | None = None) -> QueryRecentChangeCostCenterResponse: ...
    def search(self, request: SearchCostCenterRequest, option: RequestOption | None = None) -> SearchCostCenterResponse: ...
    async def asearch(self, request: SearchCostCenterRequest, option: RequestOption | None = None) -> SearchCostCenterResponse: ...
