from ..model.batch_query_cost_allocation_request import BatchQueryCostAllocationRequest as BatchQueryCostAllocationRequest
from ..model.batch_query_cost_allocation_response import BatchQueryCostAllocationResponse as BatchQueryCostAllocationResponse
from ..model.create_version_cost_allocation_request import CreateVersionCostAllocationRequest as CreateVersionCostAllocationRequest
from ..model.create_version_cost_allocation_response import CreateVersionCostAllocationResponse as CreateVersionCostAllocationResponse
from ..model.remove_version_cost_allocation_request import RemoveVersionCostAllocationRequest as RemoveVersionCostAllocationRequest
from ..model.remove_version_cost_allocation_response import RemoveVersionCostAllocationResponse as RemoveVersionCostAllocationResponse
from ..model.update_version_cost_allocation_request import UpdateVersionCostAllocationRequest as UpdateVersionCostAllocationRequest
from ..model.update_version_cost_allocation_response import UpdateVersionCostAllocationResponse as UpdateVersionCostAllocationResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class CostAllocation:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def batch_query(self, request: BatchQueryCostAllocationRequest, option: RequestOption | None = None) -> BatchQueryCostAllocationResponse: ...
    async def abatch_query(self, request: BatchQueryCostAllocationRequest, option: RequestOption | None = None) -> BatchQueryCostAllocationResponse: ...
    def create_version(self, request: CreateVersionCostAllocationRequest, option: RequestOption | None = None) -> CreateVersionCostAllocationResponse: ...
    async def acreate_version(self, request: CreateVersionCostAllocationRequest, option: RequestOption | None = None) -> CreateVersionCostAllocationResponse: ...
    def remove_version(self, request: RemoveVersionCostAllocationRequest, option: RequestOption | None = None) -> RemoveVersionCostAllocationResponse: ...
    async def aremove_version(self, request: RemoveVersionCostAllocationRequest, option: RequestOption | None = None) -> RemoveVersionCostAllocationResponse: ...
    def update_version(self, request: UpdateVersionCostAllocationRequest, option: RequestOption | None = None) -> UpdateVersionCostAllocationResponse: ...
    async def aupdate_version(self, request: UpdateVersionCostAllocationRequest, option: RequestOption | None = None) -> UpdateVersionCostAllocationResponse: ...
