from ..model.batch_get_department_request import BatchGetDepartmentRequest as BatchGetDepartmentRequest
from ..model.batch_get_department_response import BatchGetDepartmentResponse as BatchGetDepartmentResponse
from ..model.delete_department_request import DeleteDepartmentRequest as DeleteDepartmentRequest
from ..model.delete_department_response import DeleteDepartmentResponse as DeleteDepartmentResponse
from ..model.parents_department_request import ParentsDepartmentRequest as ParentsDepartmentRequest
from ..model.parents_department_response import ParentsDepartmentResponse as ParentsDepartmentResponse
from ..model.patch_department_request import PatchDepartmentRequest as PatchDepartmentRequest
from ..model.patch_department_response import PatchDepartmentResponse as PatchDepartmentResponse
from ..model.query_multi_timeline_department_request import QueryMultiTimelineDepartmentRequest as QueryMultiTimelineDepartmentRequest
from ..model.query_multi_timeline_department_response import QueryMultiTimelineDepartmentResponse as QueryMultiTimelineDepartmentResponse
from ..model.query_operation_logs_department_request import QueryOperationLogsDepartmentRequest as QueryOperationLogsDepartmentRequest
from ..model.query_operation_logs_department_response import QueryOperationLogsDepartmentResponse as QueryOperationLogsDepartmentResponse
from ..model.query_recent_change_department_request import QueryRecentChangeDepartmentRequest as QueryRecentChangeDepartmentRequest
from ..model.query_recent_change_department_response import QueryRecentChangeDepartmentResponse as QueryRecentChangeDepartmentResponse
from ..model.query_timeline_department_request import QueryTimelineDepartmentRequest as QueryTimelineDepartmentRequest
from ..model.query_timeline_department_response import QueryTimelineDepartmentResponse as QueryTimelineDepartmentResponse
from ..model.search_department_request import SearchDepartmentRequest as SearchDepartmentRequest
from ..model.search_department_response import SearchDepartmentResponse as SearchDepartmentResponse
from ..model.tree_department_request import TreeDepartmentRequest as TreeDepartmentRequest
from ..model.tree_department_response import TreeDepartmentResponse as TreeDepartmentResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class Department:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def batch_get(self, request: BatchGetDepartmentRequest, option: RequestOption | None = None) -> BatchGetDepartmentResponse: ...
    async def abatch_get(self, request: BatchGetDepartmentRequest, option: RequestOption | None = None) -> BatchGetDepartmentResponse: ...
    def delete(self, request: DeleteDepartmentRequest, option: RequestOption | None = None) -> DeleteDepartmentResponse: ...
    async def adelete(self, request: DeleteDepartmentRequest, option: RequestOption | None = None) -> DeleteDepartmentResponse: ...
    def parents(self, request: ParentsDepartmentRequest, option: RequestOption | None = None) -> ParentsDepartmentResponse: ...
    async def aparents(self, request: ParentsDepartmentRequest, option: RequestOption | None = None) -> ParentsDepartmentResponse: ...
    def patch(self, request: PatchDepartmentRequest, option: RequestOption | None = None) -> PatchDepartmentResponse: ...
    async def apatch(self, request: PatchDepartmentRequest, option: RequestOption | None = None) -> PatchDepartmentResponse: ...
    def query_multi_timeline(self, request: QueryMultiTimelineDepartmentRequest, option: RequestOption | None = None) -> QueryMultiTimelineDepartmentResponse: ...
    async def aquery_multi_timeline(self, request: QueryMultiTimelineDepartmentRequest, option: RequestOption | None = None) -> QueryMultiTimelineDepartmentResponse: ...
    def query_operation_logs(self, request: QueryOperationLogsDepartmentRequest, option: RequestOption | None = None) -> QueryOperationLogsDepartmentResponse: ...
    async def aquery_operation_logs(self, request: QueryOperationLogsDepartmentRequest, option: RequestOption | None = None) -> QueryOperationLogsDepartmentResponse: ...
    def query_recent_change(self, request: QueryRecentChangeDepartmentRequest, option: RequestOption | None = None) -> QueryRecentChangeDepartmentResponse: ...
    async def aquery_recent_change(self, request: QueryRecentChangeDepartmentRequest, option: RequestOption | None = None) -> QueryRecentChangeDepartmentResponse: ...
    def query_timeline(self, request: QueryTimelineDepartmentRequest, option: RequestOption | None = None) -> QueryTimelineDepartmentResponse: ...
    async def aquery_timeline(self, request: QueryTimelineDepartmentRequest, option: RequestOption | None = None) -> QueryTimelineDepartmentResponse: ...
    def search(self, request: SearchDepartmentRequest, option: RequestOption | None = None) -> SearchDepartmentResponse: ...
    async def asearch(self, request: SearchDepartmentRequest, option: RequestOption | None = None) -> SearchDepartmentResponse: ...
    def tree(self, request: TreeDepartmentRequest, option: RequestOption | None = None) -> TreeDepartmentResponse: ...
    async def atree(self, request: TreeDepartmentRequest, option: RequestOption | None = None) -> TreeDepartmentResponse: ...
