from ..model.complete_pre_hire_request import CompletePreHireRequest as CompletePreHireRequest
from ..model.complete_pre_hire_response import CompletePreHireResponse as CompletePreHireResponse
from ..model.create_pre_hire_request import CreatePreHireRequest as CreatePreHireRequest
from ..model.create_pre_hire_response import CreatePreHireResponse as CreatePreHireResponse
from ..model.delete_pre_hire_request import DeletePreHireRequest as DeletePreHireRequest
from ..model.delete_pre_hire_response import DeletePreHireResponse as DeletePreHireResponse
from ..model.patch_pre_hire_request import PatchPreHireRequest as PatchPreHireRequest
from ..model.patch_pre_hire_response import PatchPreHireResponse as PatchPreHireResponse
from ..model.query_pre_hire_request import QueryPreHireRequest as QueryPreHireRequest
from ..model.query_pre_hire_response import QueryPreHireResponse as QueryPreHireResponse
from ..model.restore_flow_instance_pre_hire_request import RestoreFlowInstancePreHireRequest as RestoreFlowInstancePreHireRequest
from ..model.restore_flow_instance_pre_hire_response import RestoreFlowInstancePreHireResponse as RestoreFlowInstancePreHireResponse
from ..model.search_pre_hire_request import SearchPreHireRequest as SearchPreHireRequest
from ..model.search_pre_hire_response import SearchPreHireResponse as SearchPreHireResponse
from ..model.transit_task_pre_hire_request import TransitTaskPreHireRequest as TransitTaskPreHireRequest
from ..model.transit_task_pre_hire_response import TransitTaskPreHireResponse as TransitTaskPreHireResponse
from ..model.withdraw_onboarding_pre_hire_request import WithdrawOnboardingPreHireRequest as WithdrawOnboardingPreHireRequest
from ..model.withdraw_onboarding_pre_hire_response import WithdrawOnboardingPreHireResponse as WithdrawOnboardingPreHireResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class PreHire:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def complete(self, request: CompletePreHireRequest, option: RequestOption | None = None) -> CompletePreHireResponse: ...
    async def acomplete(self, request: CompletePreHireRequest, option: RequestOption | None = None) -> CompletePreHireResponse: ...
    def create(self, request: CreatePreHireRequest, option: RequestOption | None = None) -> CreatePreHireResponse: ...
    async def acreate(self, request: CreatePreHireRequest, option: RequestOption | None = None) -> CreatePreHireResponse: ...
    def delete(self, request: DeletePreHireRequest, option: RequestOption | None = None) -> DeletePreHireResponse: ...
    async def adelete(self, request: DeletePreHireRequest, option: RequestOption | None = None) -> DeletePreHireResponse: ...
    def patch(self, request: PatchPreHireRequest, option: RequestOption | None = None) -> PatchPreHireResponse: ...
    async def apatch(self, request: PatchPreHireRequest, option: RequestOption | None = None) -> PatchPreHireResponse: ...
    def query(self, request: QueryPreHireRequest, option: RequestOption | None = None) -> QueryPreHireResponse: ...
    async def aquery(self, request: QueryPreHireRequest, option: RequestOption | None = None) -> QueryPreHireResponse: ...
    def restore_flow_instance(self, request: RestoreFlowInstancePreHireRequest, option: RequestOption | None = None) -> RestoreFlowInstancePreHireResponse: ...
    async def arestore_flow_instance(self, request: RestoreFlowInstancePreHireRequest, option: RequestOption | None = None) -> RestoreFlowInstancePreHireResponse: ...
    def search(self, request: SearchPreHireRequest, option: RequestOption | None = None) -> SearchPreHireResponse: ...
    async def asearch(self, request: SearchPreHireRequest, option: RequestOption | None = None) -> SearchPreHireResponse: ...
    def transit_task(self, request: TransitTaskPreHireRequest, option: RequestOption | None = None) -> TransitTaskPreHireResponse: ...
    async def atransit_task(self, request: TransitTaskPreHireRequest, option: RequestOption | None = None) -> TransitTaskPreHireResponse: ...
    def withdraw_onboarding(self, request: WithdrawOnboardingPreHireRequest, option: RequestOption | None = None) -> WithdrawOnboardingPreHireResponse: ...
    async def awithdraw_onboarding(self, request: WithdrawOnboardingPreHireRequest, option: RequestOption | None = None) -> WithdrawOnboardingPreHireResponse: ...
