from .text import Text as Text
from lark_oapi.core.construct import init as init

class ConnectorCaption:
    data: list[Text] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ConnectorCaptionBuilder: ...

class ConnectorCaptionBuilder:
    def __init__(self) -> None: ...
    def data(self, data: list[Text]) -> ConnectorCaptionBuilder: ...
    def build(self) -> ConnectorCaption: ...
