from .connector_attached_object import ConnectorAttachedObject as ConnectorAttachedObject
from .connector_caption import ConnectorCaption as ConnectorCaption
from lark_oapi.core.construct import init as init

class Connector:
    start_object: ConnectorAttachedObject | None
    end_object: ConnectorAttachedObject | None
    captions: ConnectorCaption | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ConnectorBuilder: ...

class ConnectorBuilder:
    def __init__(self) -> None: ...
    def start_object(self, start_object: ConnectorAttachedObject) -> ConnectorBuilder: ...
    def end_object(self, end_object: ConnectorAttachedObject) -> ConnectorBuilder: ...
    def captions(self, captions: ConnectorCaption) -> ConnectorBuilder: ...
    def build(self) -> Connector: ...
