from lark_oapi.core.construct import init as init

class DownloadAsImageWhiteboardResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DownloadAsImageWhiteboardResponseBodyBuilder: ...

class DownloadAsImageWhiteboardResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DownloadAsImageWhiteboardResponseBody: ...
