from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DownloadAsImageWhiteboardRequest(BaseRequest):
    whiteboard_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DownloadAsImageWhiteboardRequestBuilder: ...

class DownloadAsImageWhiteboardRequestBuilder:
    def __init__(self) -> None: ...
    def whiteboard_id(self, whiteboard_id: str) -> DownloadAsImageWhiteboardRequestBuilder: ...
    def build(self) -> DownloadAsImageWhiteboardRequest: ...
