from lark_oapi.core.construct import init as init

class Image:
    token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ImageBuilder: ...

class ImageBuilder:
    def __init__(self) -> None: ...
    def token(self, token: str) -> ImageBuilder: ...
    def build(self) -> Image: ...
