from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListWhiteboardNodeRequest(BaseRequest):
    whiteboard_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListWhiteboardNodeRequestBuilder: ...

class ListWhiteboardNodeRequestBuilder:
    def __init__(self) -> None: ...
    def whiteboard_id(self, whiteboard_id: str) -> ListWhiteboardNodeRequestBuilder: ...
    def build(self) -> ListWhiteboardNodeRequest: ...
