from lark_oapi.core.construct import init as init

class MindMap:
    parent_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MindMapBuilder: ...

class MindMapBuilder:
    def __init__(self) -> None: ...
    def parent_id(self, parent_id: str) -> MindMapBuilder: ...
    def build(self) -> MindMap: ...
