from lark_oapi.core.construct import init as init

class TableMeta:
    row_num: int | None
    col_num: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TableMetaBuilder: ...

class TableMetaBuilder:
    def __init__(self) -> None: ...
    def row_num(self, row_num: int) -> TableMetaBuilder: ...
    def col_num(self, col_num: int) -> TableMetaBuilder: ...
    def build(self) -> TableMeta: ...
