from .table_cell import TableCell as TableCell
from .table_meta import TableMeta as TableMeta
from lark_oapi.core.construct import init as init

class Table:
    meta: TableMeta | None
    title: str | None
    cells: list[TableCell] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TableBuilder: ...

class TableBuilder:
    def __init__(self) -> None: ...
    def meta(self, meta: TableMeta) -> TableBuilder: ...
    def title(self, title: str) -> TableBuilder: ...
    def cells(self, cells: list[TableCell]) -> TableBuilder: ...
    def build(self) -> Table: ...
