from lark_oapi.core.construct import init as init

class Text:
    text: str | None
    font_weight: str | None
    font_size: int | None
    horizontal_align: str | None
    vertical_align: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TextBuilder: ...

class TextBuilder:
    def __init__(self) -> None: ...
    def text(self, text: str) -> TextBuilder: ...
    def font_weight(self, font_weight: str) -> TextBuilder: ...
    def font_size(self, font_size: int) -> TextBuilder: ...
    def horizontal_align(self, horizontal_align: str) -> TextBuilder: ...
    def vertical_align(self, vertical_align: str) -> TextBuilder: ...
    def build(self) -> Text: ...
