from .event_uid import EventUid as EventUid
from lark_oapi.core.construct import init as init

class EventUids:
    event_uids: list[EventUid] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EventUidsBuilder: ...

class EventUidsBuilder:
    def __init__(self) -> None: ...
    def event_uids(self, event_uids: list[EventUid]) -> EventUidsBuilder: ...
    def build(self) -> EventUids: ...
