from lark_oapi.core.construct import init as init

class EventUid:
    uid: str | None
    original_time: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EventUidBuilder: ...

class EventUidBuilder:
    def __init__(self) -> None: ...
    def uid(self, uid: str) -> EventUidBuilder: ...
    def original_time(self, original_time: int) -> EventUidBuilder: ...
    def build(self) -> EventUid: ...
