from lark_oapi.core.construct import init as init

class UserInfo:
    open_id: str | None
    user_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserInfoBuilder: ...

class UserInfoBuilder:
    def __init__(self) -> None: ...
    def open_id(self, open_id: str) -> UserInfoBuilder: ...
    def user_id(self, user_id: str) -> UserInfoBuilder: ...
    def build(self) -> UserInfo: ...
