from lark_oapi.core.construct import init as init

class Vchat:
    meeting_url: str | None
    vc_type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> VchatBuilder: ...

class VchatBuilder:
    def __init__(self) -> None: ...
    def meeting_url(self, meeting_url: str) -> VchatBuilder: ...
    def vc_type(self, vc_type: str) -> VchatBuilder: ...
    def build(self) -> Vchat: ...
