from ..model.create_calendar_acl_request import CreateCalendarAclRequest as CreateCalendarAclRequest
from ..model.create_calendar_acl_response import CreateCalendarAclResponse as CreateCalendarAclResponse
from ..model.delete_calendar_acl_request import DeleteCalendarAclRequest as DeleteCalendarAclRequest
from ..model.delete_calendar_acl_response import DeleteCalendarAclResponse as DeleteCalendarAclResponse
from ..model.list_calendar_acl_request import ListCalendarAclRequest as ListCalendarAclRequest
from ..model.list_calendar_acl_response import ListCalendarAclResponse as ListCalendarAclResponse
from ..model.subscription_calendar_acl_request import SubscriptionCalendarAclRequest as SubscriptionCalendarAclRequest
from ..model.subscription_calendar_acl_response import SubscriptionCalendarAclResponse as SubscriptionCalendarAclResponse
from ..model.unsubscription_calendar_acl_request import UnsubscriptionCalendarAclRequest as UnsubscriptionCalendarAclRequest
from ..model.unsubscription_calendar_acl_response import UnsubscriptionCalendarAclResponse as UnsubscriptionCalendarAclResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class CalendarAcl:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def create(self, request: CreateCalendarAclRequest, option: RequestOption | None = None) -> CreateCalendarAclResponse: ...
    async def acreate(self, request: CreateCalendarAclRequest, option: RequestOption | None = None) -> CreateCalendarAclResponse: ...
    def delete(self, request: DeleteCalendarAclRequest, option: RequestOption | None = None) -> DeleteCalendarAclResponse: ...
    async def adelete(self, request: DeleteCalendarAclRequest, option: RequestOption | None = None) -> DeleteCalendarAclResponse: ...
    def list(self, request: ListCalendarAclRequest, option: RequestOption | None = None) -> ListCalendarAclResponse: ...
    async def alist(self, request: ListCalendarAclRequest, option: RequestOption | None = None) -> ListCalendarAclResponse: ...
    def subscription(self, request: SubscriptionCalendarAclRequest, option: RequestOption | None = None) -> SubscriptionCalendarAclResponse: ...
    async def asubscription(self, request: SubscriptionCalendarAclRequest, option: RequestOption | None = None) -> SubscriptionCalendarAclResponse: ...
    def unsubscription(self, request: UnsubscriptionCalendarAclRequest, option: RequestOption | None = None) -> UnsubscriptionCalendarAclResponse: ...
    async def aunsubscription(self, request: UnsubscriptionCalendarAclRequest, option: RequestOption | None = None) -> UnsubscriptionCalendarAclResponse: ...
