from ..model.create_calendar_event_request import CreateCalendarEventRequest as CreateCalendarEventRequest
from ..model.create_calendar_event_response import CreateCalendarEventResponse as CreateCalendarEventResponse
from ..model.delete_calendar_event_request import DeleteCalendarEventRequest as DeleteCalendarEventRequest
from ..model.delete_calendar_event_response import DeleteCalendarEventResponse as DeleteCalendarEventResponse
from ..model.get_calendar_event_request import GetCalendarEventRequest as GetCalendarEventRequest
from ..model.get_calendar_event_response import GetCalendarEventResponse as GetCalendarEventResponse
from ..model.instance_view_calendar_event_request import InstanceViewCalendarEventRequest as InstanceViewCalendarEventRequest
from ..model.instance_view_calendar_event_response import InstanceViewCalendarEventResponse as InstanceViewCalendarEventResponse
from ..model.instances_calendar_event_request import InstancesCalendarEventRequest as InstancesCalendarEventRequest
from ..model.instances_calendar_event_response import InstancesCalendarEventResponse as InstancesCalendarEventResponse
from ..model.list_calendar_event_request import ListCalendarEventRequest as ListCalendarEventRequest
from ..model.list_calendar_event_response import ListCalendarEventResponse as ListCalendarEventResponse
from ..model.patch_calendar_event_request import PatchCalendarEventRequest as PatchCalendarEventRequest
from ..model.patch_calendar_event_response import PatchCalendarEventResponse as PatchCalendarEventResponse
from ..model.reply_calendar_event_request import ReplyCalendarEventRequest as ReplyCalendarEventRequest
from ..model.reply_calendar_event_response import ReplyCalendarEventResponse as ReplyCalendarEventResponse
from ..model.search_calendar_event_request import SearchCalendarEventRequest as SearchCalendarEventRequest
from ..model.search_calendar_event_response import SearchCalendarEventResponse as SearchCalendarEventResponse
from ..model.subscription_calendar_event_request import SubscriptionCalendarEventRequest as SubscriptionCalendarEventRequest
from ..model.subscription_calendar_event_response import SubscriptionCalendarEventResponse as SubscriptionCalendarEventResponse
from ..model.unsubscription_calendar_event_request import UnsubscriptionCalendarEventRequest as UnsubscriptionCalendarEventRequest
from ..model.unsubscription_calendar_event_response import UnsubscriptionCalendarEventResponse as UnsubscriptionCalendarEventResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class CalendarEvent:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def create(self, request: CreateCalendarEventRequest, option: RequestOption | None = None) -> CreateCalendarEventResponse: ...
    async def acreate(self, request: CreateCalendarEventRequest, option: RequestOption | None = None) -> CreateCalendarEventResponse: ...
    def delete(self, request: DeleteCalendarEventRequest, option: RequestOption | None = None) -> DeleteCalendarEventResponse: ...
    async def adelete(self, request: DeleteCalendarEventRequest, option: RequestOption | None = None) -> DeleteCalendarEventResponse: ...
    def get(self, request: GetCalendarEventRequest, option: RequestOption | None = None) -> GetCalendarEventResponse: ...
    async def aget(self, request: GetCalendarEventRequest, option: RequestOption | None = None) -> GetCalendarEventResponse: ...
    def instance_view(self, request: InstanceViewCalendarEventRequest, option: RequestOption | None = None) -> InstanceViewCalendarEventResponse: ...
    async def ainstance_view(self, request: InstanceViewCalendarEventRequest, option: RequestOption | None = None) -> InstanceViewCalendarEventResponse: ...
    def instances(self, request: InstancesCalendarEventRequest, option: RequestOption | None = None) -> InstancesCalendarEventResponse: ...
    async def ainstances(self, request: InstancesCalendarEventRequest, option: RequestOption | None = None) -> InstancesCalendarEventResponse: ...
    def list(self, request: ListCalendarEventRequest, option: RequestOption | None = None) -> ListCalendarEventResponse: ...
    async def alist(self, request: ListCalendarEventRequest, option: RequestOption | None = None) -> ListCalendarEventResponse: ...
    def patch(self, request: PatchCalendarEventRequest, option: RequestOption | None = None) -> PatchCalendarEventResponse: ...
    async def apatch(self, request: PatchCalendarEventRequest, option: RequestOption | None = None) -> PatchCalendarEventResponse: ...
    def reply(self, request: ReplyCalendarEventRequest, option: RequestOption | None = None) -> ReplyCalendarEventResponse: ...
    async def areply(self, request: ReplyCalendarEventRequest, option: RequestOption | None = None) -> ReplyCalendarEventResponse: ...
    def search(self, request: SearchCalendarEventRequest, option: RequestOption | None = None) -> SearchCalendarEventResponse: ...
    async def asearch(self, request: SearchCalendarEventRequest, option: RequestOption | None = None) -> SearchCalendarEventResponse: ...
    def subscription(self, request: SubscriptionCalendarEventRequest, option: RequestOption | None = None) -> SubscriptionCalendarEventResponse: ...
    async def asubscription(self, request: SubscriptionCalendarEventRequest, option: RequestOption | None = None) -> SubscriptionCalendarEventResponse: ...
    def unsubscription(self, request: UnsubscriptionCalendarEventRequest, option: RequestOption | None = None) -> UnsubscriptionCalendarEventResponse: ...
    async def aunsubscription(self, request: UnsubscriptionCalendarEventRequest, option: RequestOption | None = None) -> UnsubscriptionCalendarEventResponse: ...
