from ..model.create_task_collaborator_request import CreateTaskCollaboratorRequest as CreateTaskCollaboratorRequest
from ..model.create_task_collaborator_response import CreateTaskCollaboratorResponse as CreateTaskCollaboratorResponse
from ..model.delete_task_collaborator_request import DeleteTaskCollaboratorRequest as DeleteTaskCollaboratorRequest
from ..model.delete_task_collaborator_response import DeleteTaskCollaboratorResponse as DeleteTaskCollaboratorResponse
from ..model.list_task_collaborator_request import ListTaskCollaboratorRequest as ListTaskCollaboratorRequest
from ..model.list_task_collaborator_response import ListTaskCollaboratorResponse as ListTaskCollaboratorResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class TaskCollaborator:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def create(self, request: CreateTaskCollaboratorRequest, option: RequestOption | None = None) -> CreateTaskCollaboratorResponse: ...
    async def acreate(self, request: CreateTaskCollaboratorRequest, option: RequestOption | None = None) -> CreateTaskCollaboratorResponse: ...
    def delete(self, request: DeleteTaskCollaboratorRequest, option: RequestOption | None = None) -> DeleteTaskCollaboratorResponse: ...
    async def adelete(self, request: DeleteTaskCollaboratorRequest, option: RequestOption | None = None) -> DeleteTaskCollaboratorResponse: ...
    def list(self, request: ListTaskCollaboratorRequest, option: RequestOption | None = None) -> ListTaskCollaboratorResponse: ...
    async def alist(self, request: ListTaskCollaboratorRequest, option: RequestOption | None = None) -> ListTaskCollaboratorResponse: ...
