from lark_oapi.core.construct import init as init

class Classification:
    id: str | None
    name: str | None
    father_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ClassificationBuilder: ...

class ClassificationBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> ClassificationBuilder: ...
    def name(self, name: str) -> ClassificationBuilder: ...
    def father_id(self, father_id: str) -> ClassificationBuilder: ...
    def build(self) -> Classification: ...
