from lark_oapi.core.construct import init as init

class CorrectPair:
    source_text: str | None
    target_text: str | None
    total: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CorrectPairBuilder: ...

class CorrectPairBuilder:
    def __init__(self) -> None: ...
    def source_text(self, source_text: str) -> CorrectPairBuilder: ...
    def target_text(self, target_text: str) -> CorrectPairBuilder: ...
    def total(self, total: int) -> CorrectPairBuilder: ...
    def build(self) -> CorrectPair: ...
