from .entity import Entity as Entity
from lark_oapi.core.construct import init as init

class Draft:
    draft_id: int | None
    entity: Entity | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DraftBuilder: ...

class DraftBuilder:
    def __init__(self) -> None: ...
    def draft_id(self, draft_id: int) -> DraftBuilder: ...
    def entity(self, entity: Entity) -> DraftBuilder: ...
    def build(self) -> Draft: ...
