from .entity_word import EntityWord as EntityWord
from lark_oapi.core.construct import init as init

class ExtractEntityResponseBody:
    entity_word: list[EntityWord] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ExtractEntityResponseBodyBuilder: ...

class ExtractEntityResponseBodyBuilder:
    def __init__(self) -> None: ...
    def entity_word(self, entity_word: list[EntityWord]) -> ExtractEntityResponseBodyBuilder: ...
    def build(self) -> ExtractEntityResponseBody: ...
