from .highlight_entity_request_body import HighlightEntityRequestBody as HighlightEntityRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class HighlightEntityRequest(BaseRequest):
    request_body: HighlightEntityRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> HighlightEntityRequestBuilder: ...

class HighlightEntityRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: HighlightEntityRequestBody) -> HighlightEntityRequestBuilder: ...
    def build(self) -> HighlightEntityRequest: ...
