from .phrase import Phrase as Phrase
from lark_oapi.core.construct import init as init

class HighlightEntityResponseBody:
    phrases: list[Phrase] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> HighlightEntityResponseBodyBuilder: ...

class HighlightEntityResponseBodyBuilder:
    def __init__(self) -> None: ...
    def phrases(self, phrases: list[Phrase]) -> HighlightEntityResponseBodyBuilder: ...
    def build(self) -> HighlightEntityResponseBody: ...
