from lark_oapi.core.construct import init as init

class OuterInfo:
    provider: str | None
    outer_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OuterInfoBuilder: ...

class OuterInfoBuilder:
    def __init__(self) -> None: ...
    def provider(self, provider: str) -> OuterInfoBuilder: ...
    def outer_id(self, outer_id: str) -> OuterInfoBuilder: ...
    def build(self) -> OuterInfo: ...
