from .entity import Entity as Entity
from lark_oapi.core.construct import init as init

class UpdateEntityResponseBody:
    entity: Entity | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateEntityResponseBodyBuilder: ...

class UpdateEntityResponseBodyBuilder:
    def __init__(self) -> None: ...
    def entity(self, entity: Entity) -> UpdateEntityResponseBodyBuilder: ...
    def build(self) -> UpdateEntityResponseBody: ...
