from .reserve_meeting_setting import ReserveMeetingSetting as ReserveMeetingSetting
from lark_oapi.core.construct import init as init

class ApplyReserveRequestBody:
    end_time: int | None
    owner_id: str | None
    meeting_settings: ReserveMeetingSetting | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApplyReserveRequestBodyBuilder: ...

class ApplyReserveRequestBodyBuilder:
    def __init__(self) -> None: ...
    def end_time(self, end_time: int) -> ApplyReserveRequestBodyBuilder: ...
    def owner_id(self, owner_id: str) -> ApplyReserveRequestBodyBuilder: ...
    def meeting_settings(self, meeting_settings: ReserveMeetingSetting) -> ApplyReserveRequestBodyBuilder: ...
    def build(self) -> ApplyReserveRequestBody: ...
