from .subscribe_user import SubscribeUser as SubscribeUser
from lark_oapi.core.construct import init as init

class ApprovalConfig:
    approval_switch: int | None
    approval_condition: int | None
    meeting_duration: float | None
    approvers: list[SubscribeUser] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApprovalConfigBuilder: ...

class ApprovalConfigBuilder:
    def __init__(self) -> None: ...
    def approval_switch(self, approval_switch: int) -> ApprovalConfigBuilder: ...
    def approval_condition(self, approval_condition: int) -> ApprovalConfigBuilder: ...
    def meeting_duration(self, meeting_duration: float) -> ApprovalConfigBuilder: ...
    def approvers(self, approvers: list[SubscribeUser]) -> ApprovalConfigBuilder: ...
    def build(self) -> ApprovalConfig: ...
