from .subscribe_user_event import SubscribeUserEvent as SubscribeUserEvent
from lark_oapi.core.construct import init as init

class ApprovalConfigEvent:
    approval_switch: int | None
    approval_condition: int | None
    meeting_duration: float | None
    approvers: list[SubscribeUserEvent] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApprovalConfigEventBuilder: ...

class ApprovalConfigEventBuilder:
    def __init__(self) -> None: ...
    def approval_switch(self, approval_switch: int) -> ApprovalConfigEventBuilder: ...
    def approval_condition(self, approval_condition: int) -> ApprovalConfigEventBuilder: ...
    def meeting_duration(self, meeting_duration: float) -> ApprovalConfigEventBuilder: ...
    def approvers(self, approvers: list[SubscribeUserEvent]) -> ApprovalConfigEventBuilder: ...
    def build(self) -> ApprovalConfigEvent: ...
