from lark_oapi.core.construct import init as init

class Conditions:
    custom_key: str | None
    option_keys: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ConditionsBuilder: ...

class ConditionsBuilder:
    def __init__(self) -> None: ...
    def custom_key(self, custom_key: str) -> ConditionsBuilder: ...
    def option_keys(self, option_keys: list[str]) -> ConditionsBuilder: ...
    def build(self) -> Conditions: ...
