from .scope_config import ScopeConfig as ScopeConfig
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateScopeConfigRequest(BaseRequest):
    user_id_type: str | None
    request_body: ScopeConfig | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateScopeConfigRequestBuilder: ...

class CreateScopeConfigRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> CreateScopeConfigRequestBuilder: ...
    def request_body(self, request_body: ScopeConfig) -> CreateScopeConfigRequestBuilder: ...
    def build(self) -> CreateScopeConfigRequest: ...
