from lark_oapi.core.construct import init as init

class DelRoomLevelResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DelRoomLevelResponseBodyBuilder: ...

class DelRoomLevelResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DelRoomLevelResponseBody: ...
