from .del_room_level_request_body import DelRoomLevelRequestBody as DelRoomLevelRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DelRoomLevelRequest(BaseRequest):
    request_body: DelRoomLevelRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DelRoomLevelRequestBuilder: ...

class DelRoomLevelRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: DelRoomLevelRequestBody) -> DelRoomLevelRequestBuilder: ...
    def build(self) -> DelRoomLevelRequest: ...
