from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteReserveRequest(BaseRequest):
    reserve_id: int | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteReserveRequestBuilder: ...

class DeleteReserveRequestBuilder:
    def __init__(self) -> None: ...
    def reserve_id(self, reserve_id: int) -> DeleteReserveRequestBuilder: ...
    def build(self) -> DeleteReserveRequest: ...
