from .meeting import Meeting as Meeting
from lark_oapi.core.construct import init as init

class GetMeetingResponseBody:
    meeting: Meeting | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetMeetingResponseBodyBuilder: ...

class GetMeetingResponseBodyBuilder:
    def __init__(self) -> None: ...
    def meeting(self, meeting: Meeting) -> GetMeetingResponseBodyBuilder: ...
    def build(self) -> GetMeetingResponseBody: ...
