from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetActiveMeetingReserveRequest(BaseRequest):
    with_participants: bool | None
    user_id_type: str | None
    reserve_id: int | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetActiveMeetingReserveRequestBuilder: ...

class GetActiveMeetingReserveRequestBuilder:
    def __init__(self) -> None: ...
    def with_participants(self, with_participants: bool) -> GetActiveMeetingReserveRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> GetActiveMeetingReserveRequestBuilder: ...
    def reserve_id(self, reserve_id: int) -> GetActiveMeetingReserveRequestBuilder: ...
    def build(self) -> GetActiveMeetingReserveRequest: ...
