from .reserve import Reserve as Reserve
from lark_oapi.core.construct import init as init

class GetReserveResponseBody:
    reserve: Reserve | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetReserveResponseBodyBuilder: ...

class GetReserveResponseBodyBuilder:
    def __init__(self) -> None: ...
    def reserve(self, reserve: Reserve) -> GetReserveResponseBodyBuilder: ...
    def build(self) -> GetReserveResponseBody: ...
