from .report_top_user import ReportTopUser as ReportTopUser
from lark_oapi.core.construct import init as init

class GetTopUserReportResponseBody:
    top_user_report: list[ReportTopUser] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetTopUserReportResponseBodyBuilder: ...

class GetTopUserReportResponseBodyBuilder:
    def __init__(self) -> None: ...
    def top_user_report(self, top_user_report: list[ReportTopUser]) -> GetTopUserReportResponseBodyBuilder: ...
    def build(self) -> GetTopUserReportResponseBody: ...
