from lark_oapi.core.construct import init as init

class GetReserveRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetReserveRequestBodyBuilder: ...

class GetReserveRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetReserveRequestBody: ...
