from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetReserveConfigDisableInformRequest(BaseRequest):
    scope_type: int | None
    user_id_type: str | None
    reserve_config_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetReserveConfigDisableInformRequestBuilder: ...

class GetReserveConfigDisableInformRequestBuilder:
    def __init__(self) -> None: ...
    def scope_type(self, scope_type: int) -> GetReserveConfigDisableInformRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> GetReserveConfigDisableInformRequestBuilder: ...
    def reserve_config_id(self, reserve_config_id: str) -> GetReserveConfigDisableInformRequestBuilder: ...
    def build(self) -> GetReserveConfigDisableInformRequest: ...
