from .reserve_admin_config import ReserveAdminConfig as ReserveAdminConfig
from lark_oapi.core.construct import init as init

class GetReserveConfigAdminResponseBody:
    reserve_admin_config: ReserveAdminConfig | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetReserveConfigAdminResponseBodyBuilder: ...

class GetReserveConfigAdminResponseBodyBuilder:
    def __init__(self) -> None: ...
    def reserve_admin_config(self, reserve_admin_config: ReserveAdminConfig) -> GetReserveConfigAdminResponseBodyBuilder: ...
    def build(self) -> GetReserveConfigAdminResponseBody: ...
