from .disable_inform_config import DisableInformConfig as DisableInformConfig
from lark_oapi.core.construct import init as init

class GetReserveConfigDisableInformResponseBody:
    disable_inform: DisableInformConfig | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetReserveConfigDisableInformResponseBodyBuilder: ...

class GetReserveConfigDisableInformResponseBodyBuilder:
    def __init__(self) -> None: ...
    def disable_inform(self, disable_inform: DisableInformConfig) -> GetReserveConfigDisableInformResponseBodyBuilder: ...
    def build(self) -> GetReserveConfigDisableInformResponseBody: ...
