from lark_oapi.core.construct import init as init

class GetExportRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetExportRequestBodyBuilder: ...

class GetExportRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetExportRequestBody: ...
