from lark_oapi.core.construct import init as init

class GetMeetingListRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetMeetingListRequestBodyBuilder: ...

class GetMeetingListRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetMeetingListRequestBody: ...
