from lark_oapi.core.construct import init as init

class GetRoomRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetRoomRequestBodyBuilder: ...

class GetRoomRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetRoomRequestBody: ...
