from lark_oapi.core.construct import init as init

class GetTopUserReportRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetTopUserReportRequestBodyBuilder: ...

class GetTopUserReportRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetTopUserReportRequestBody: ...
