from .room_level import RoomLevel as RoomLevel
from lark_oapi.core.construct import init as init

class GetRoomLevelResponseBody:
    room_level: RoomLevel | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetRoomLevelResponseBodyBuilder: ...

class GetRoomLevelResponseBodyBuilder:
    def __init__(self) -> None: ...
    def room_level(self, room_level: RoomLevel) -> GetRoomLevelResponseBodyBuilder: ...
    def build(self) -> GetRoomLevelResponseBody: ...
