from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetRoomRequest(BaseRequest):
    user_id_type: str | None
    room_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetRoomRequestBuilder: ...

class GetRoomRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> GetRoomRequestBuilder: ...
    def room_id(self, room_id: str) -> GetRoomRequestBuilder: ...
    def build(self) -> GetRoomRequest: ...
