from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetRoomLevelRequest(BaseRequest):
    room_level_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetRoomLevelRequestBuilder: ...

class GetRoomLevelRequestBuilder:
    def __init__(self) -> None: ...
    def room_level_id(self, room_level_id: str) -> GetRoomLevelRequestBuilder: ...
    def build(self) -> GetRoomLevelRequest: ...
