from .meeting_info import MeetingInfo as MeetingInfo
from lark_oapi.core.construct import init as init

class GetMeetingListResponseBody:
    meeting_list: list[MeetingInfo] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetMeetingListResponseBodyBuilder: ...

class GetMeetingListResponseBodyBuilder:
    def __init__(self) -> None: ...
    def meeting_list(self, meeting_list: list[MeetingInfo]) -> GetMeetingListResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> GetMeetingListResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> GetMeetingListResponseBodyBuilder: ...
    def build(self) -> GetMeetingListResponseBody: ...
