from lark_oapi.core.construct import init as init

class GetParticipantListRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetParticipantListRequestBodyBuilder: ...

class GetParticipantListRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetParticipantListRequestBody: ...
