from lark_oapi.core.construct import init as init

class GetReserveConfigAdminRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetReserveConfigAdminRequestBodyBuilder: ...

class GetReserveConfigAdminRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetReserveConfigAdminRequestBody: ...
