from lark_oapi.core.construct import init as init

class GetActiveMeetingReserveRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetActiveMeetingReserveRequestBodyBuilder: ...

class GetActiveMeetingReserveRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetActiveMeetingReserveRequestBody: ...
