from .invite_meeting_request_body import InviteMeetingRequestBody as InviteMeetingRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class InviteMeetingRequest(BaseRequest):
    user_id_type: str | None
    meeting_id: int | None
    request_body: InviteMeetingRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> InviteMeetingRequestBuilder: ...

class InviteMeetingRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> InviteMeetingRequestBuilder: ...
    def meeting_id(self, meeting_id: int) -> InviteMeetingRequestBuilder: ...
    def request_body(self, request_body: InviteMeetingRequestBody) -> InviteMeetingRequestBuilder: ...
    def build(self) -> InviteMeetingRequest: ...
