from lark_oapi.core.construct import init as init

class KeyPointMatchDetail:
    start_timestamp: str | None
    matched_text: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> KeyPointMatchDetailBuilder: ...

class KeyPointMatchDetailBuilder:
    def __init__(self) -> None: ...
    def start_timestamp(self, start_timestamp: str) -> KeyPointMatchDetailBuilder: ...
    def matched_text(self, matched_text: str) -> KeyPointMatchDetailBuilder: ...
    def build(self) -> KeyPointMatchDetail: ...
