from .room_level import RoomLevel as RoomLevel
from lark_oapi.core.construct import init as init

class ListRoomLevelResponseBody:
    items: list[RoomLevel] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListRoomLevelResponseBodyBuilder: ...

class ListRoomLevelResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[RoomLevel]) -> ListRoomLevelResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListRoomLevelResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListRoomLevelResponseBodyBuilder: ...
    def build(self) -> ListRoomLevelResponseBody: ...
