from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListRoomLevelRequest(BaseRequest):
    room_level_id: str | None
    page_size: int | None
    page_token: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListRoomLevelRequestBuilder: ...

class ListRoomLevelRequestBuilder:
    def __init__(self) -> None: ...
    def room_level_id(self, room_level_id: str) -> ListRoomLevelRequestBuilder: ...
    def page_size(self, page_size: int) -> ListRoomLevelRequestBuilder: ...
    def page_token(self, page_token: str) -> ListRoomLevelRequestBuilder: ...
    def build(self) -> ListRoomLevelRequest: ...
