from lark_oapi.core.construct import init as init

class MeetingRecording:
    id: int | None
    meeting_id: int | None
    url: str | None
    duration: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MeetingRecordingBuilder: ...

class MeetingRecordingBuilder:
    def __init__(self) -> None: ...
    def id(self, id: int) -> MeetingRecordingBuilder: ...
    def meeting_id(self, meeting_id: int) -> MeetingRecordingBuilder: ...
    def url(self, url: str) -> MeetingRecordingBuilder: ...
    def duration(self, duration: int) -> MeetingRecordingBuilder: ...
    def build(self) -> MeetingRecording: ...
