from .user_id import UserId as UserId
from lark_oapi.core.construct import init as init

class MeetingSecuritySetting:
    security_level: int | None
    group_ids: list[str] | None
    user_ids: list[UserId] | None
    room_ids: list[str] | None
    has_set_security_contacts_and_group: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MeetingSecuritySettingBuilder: ...

class MeetingSecuritySettingBuilder:
    def __init__(self) -> None: ...
    def security_level(self, security_level: int) -> MeetingSecuritySettingBuilder: ...
    def group_ids(self, group_ids: list[str]) -> MeetingSecuritySettingBuilder: ...
    def user_ids(self, user_ids: list[UserId]) -> MeetingSecuritySettingBuilder: ...
    def room_ids(self, room_ids: list[str]) -> MeetingSecuritySettingBuilder: ...
    def has_set_security_contacts_and_group(self, has_set_security_contacts_and_group: bool) -> MeetingSecuritySettingBuilder: ...
    def build(self) -> MeetingSecuritySetting: ...
