from lark_oapi.core.construct import init as init

class MeetingListExportRequestBody:
    start_time: int | None
    end_time: int | None
    meeting_status: int | None
    meeting_no: str | None
    user_id: str | None
    room_id: str | None
    meeting_type: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MeetingListExportRequestBodyBuilder: ...

class MeetingListExportRequestBodyBuilder:
    def __init__(self) -> None: ...
    def start_time(self, start_time: int) -> MeetingListExportRequestBodyBuilder: ...
    def end_time(self, end_time: int) -> MeetingListExportRequestBodyBuilder: ...
    def meeting_status(self, meeting_status: int) -> MeetingListExportRequestBodyBuilder: ...
    def meeting_no(self, meeting_no: str) -> MeetingListExportRequestBodyBuilder: ...
    def user_id(self, user_id: str) -> MeetingListExportRequestBodyBuilder: ...
    def room_id(self, room_id: str) -> MeetingListExportRequestBodyBuilder: ...
    def meeting_type(self, meeting_type: int) -> MeetingListExportRequestBodyBuilder: ...
    def build(self) -> MeetingListExportRequestBody: ...
