from .room_level import RoomLevel as RoomLevel
from lark_oapi.core.construct import init as init

class MgetRoomLevelResponseBody:
    items: list[RoomLevel] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MgetRoomLevelResponseBodyBuilder: ...

class MgetRoomLevelResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[RoomLevel]) -> MgetRoomLevelResponseBodyBuilder: ...
    def build(self) -> MgetRoomLevelResponseBody: ...
