from lark_oapi.core.construct import init as init

class MgetRoomLevelRequestBody:
    level_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MgetRoomLevelRequestBodyBuilder: ...

class MgetRoomLevelRequestBodyBuilder:
    def __init__(self) -> None: ...
    def level_ids(self, level_ids: list[str]) -> MgetRoomLevelRequestBodyBuilder: ...
    def build(self) -> MgetRoomLevelRequestBody: ...
