from .mget_room_level_request_body import MgetRoomLevelRequestBody as MgetRoomLevelRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class MgetRoomLevelRequest(BaseRequest):
    request_body: MgetRoomLevelRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> MgetRoomLevelRequestBuilder: ...

class MgetRoomLevelRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: MgetRoomLevelRequestBody) -> MgetRoomLevelRequestBuilder: ...
    def build(self) -> MgetRoomLevelRequest: ...
