from .my_ai_av_plugin_card_variables import MyAiAvPluginCardVariables as MyAiAvPluginCardVariables
from lark_oapi.core.construct import init as init

class MyAiAvPluginPresentInfo:
    type: str | None
    card_template_id: str | None
    body: str | None
    card_variables: MyAiAvPluginCardVariables | None
    callback_info: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MyAiAvPluginPresentInfoBuilder: ...

class MyAiAvPluginPresentInfoBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> MyAiAvPluginPresentInfoBuilder: ...
    def card_template_id(self, card_template_id: str) -> MyAiAvPluginPresentInfoBuilder: ...
    def body(self, body: str) -> MyAiAvPluginPresentInfoBuilder: ...
    def card_variables(self, card_variables: MyAiAvPluginCardVariables) -> MyAiAvPluginPresentInfoBuilder: ...
    def callback_info(self, callback_info: str) -> MyAiAvPluginPresentInfoBuilder: ...
    def build(self) -> MyAiAvPluginPresentInfo: ...
