from .my_ai_plugin_context import MyAiPluginContext as MyAiPluginContext
from .my_ai_vc_room_extra import MyAiVcRoomExtra as MyAiVcRoomExtra
from lark_oapi.core.construct import init as init

class MyAiVcRoomScenarioContext:
    plugins: list[MyAiPluginContext] | None
    extra: MyAiVcRoomExtra | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MyAiVcRoomScenarioContextBuilder: ...

class MyAiVcRoomScenarioContextBuilder:
    def __init__(self) -> None: ...
    def plugins(self, plugins: list[MyAiPluginContext]) -> MyAiVcRoomScenarioContextBuilder: ...
    def extra(self, extra: MyAiVcRoomExtra) -> MyAiVcRoomScenarioContextBuilder: ...
    def build(self) -> MyAiVcRoomScenarioContext: ...
