from lark_oapi.core.construct import init as init

class MyAiSipCardVariables:
    text: str | None
    image_key: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MyAiSipCardVariablesBuilder: ...

class MyAiSipCardVariablesBuilder:
    def __init__(self) -> None: ...
    def text(self, text: str) -> MyAiSipCardVariablesBuilder: ...
    def image_key(self, image_key: str) -> MyAiSipCardVariablesBuilder: ...
    def build(self) -> MyAiSipCardVariables: ...
