from lark_oapi.core.construct import init as init

class MyAiAvPluginCardVaribales:
    content: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MyAiAvPluginCardVaribalesBuilder: ...

class MyAiAvPluginCardVaribalesBuilder:
    def __init__(self) -> None: ...
    def content(self, content: str) -> MyAiAvPluginCardVaribalesBuilder: ...
    def build(self) -> MyAiAvPluginCardVaribales: ...
