from lark_oapi.core.construct import init as init

class MyAiPluginContext:
    key: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MyAiPluginContextBuilder: ...

class MyAiPluginContextBuilder:
    def __init__(self) -> None: ...
    def key(self, key: str) -> MyAiPluginContextBuilder: ...
    def build(self) -> MyAiPluginContext: ...
