from .my_ai_callback_action_value import MyAiCallbackActionValue as MyAiCallbackActionValue
from lark_oapi.core.construct import init as init

class MyAiCallbackAction:
    value: MyAiCallbackActionValue | None
    tag: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MyAiCallbackActionBuilder: ...

class MyAiCallbackActionBuilder:
    def __init__(self) -> None: ...
    def value(self, value: MyAiCallbackActionValue) -> MyAiCallbackActionBuilder: ...
    def tag(self, tag: str) -> MyAiCallbackActionBuilder: ...
    def build(self) -> MyAiCallbackAction: ...
