from lark_oapi.core.construct import init as init

class MyAiVcRoomExtra:
    calendar_info: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MyAiVcRoomExtraBuilder: ...

class MyAiVcRoomExtraBuilder:
    def __init__(self) -> None: ...
    def calendar_info(self, calendar_info: str) -> MyAiVcRoomExtraBuilder: ...
    def build(self) -> MyAiVcRoomExtra: ...
