from lark_oapi.core.construct import init as init

class MyAiCallbackActionValue:
    body: str | None
    handle: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MyAiCallbackActionValueBuilder: ...

class MyAiCallbackActionValueBuilder:
    def __init__(self) -> None: ...
    def body(self, body: str) -> MyAiCallbackActionValueBuilder: ...
    def handle(self, handle: str) -> MyAiCallbackActionValueBuilder: ...
    def build(self) -> MyAiCallbackActionValue: ...
