from .my_ai_av_plugin_context_system_info import MyAiAvPluginContextSystemInfo as MyAiAvPluginContextSystemInfo
from .my_ai_av_plugin_upload_object import MyAiAvPluginUploadObject as MyAiAvPluginUploadObject
from .my_ai_plugin_context import MyAiPluginContext as MyAiPluginContext
from lark_oapi.core.construct import init as init

class MyAiAvPluginScenarioContext:
    plugins: list[MyAiPluginContext] | None
    work_mode: int | None
    scenario: str | None
    session_id: str | None
    upload_objects: list[MyAiAvPluginUploadObject] | None
    system_info: MyAiAvPluginContextSystemInfo | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MyAiAvPluginScenarioContextBuilder: ...

class MyAiAvPluginScenarioContextBuilder:
    def __init__(self) -> None: ...
    def plugins(self, plugins: list[MyAiPluginContext]) -> MyAiAvPluginScenarioContextBuilder: ...
    def work_mode(self, work_mode: int) -> MyAiAvPluginScenarioContextBuilder: ...
    def scenario(self, scenario: str) -> MyAiAvPluginScenarioContextBuilder: ...
    def session_id(self, session_id: str) -> MyAiAvPluginScenarioContextBuilder: ...
    def upload_objects(self, upload_objects: list[MyAiAvPluginUploadObject]) -> MyAiAvPluginScenarioContextBuilder: ...
    def system_info(self, system_info: MyAiAvPluginContextSystemInfo) -> MyAiAvPluginScenarioContextBuilder: ...
    def build(self) -> MyAiAvPluginScenarioContext: ...
