from lark_oapi.core.construct import init as init

class Options:
    text: str | None
    key: str | None
    is_other: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OptionsBuilder: ...

class OptionsBuilder:
    def __init__(self) -> None: ...
    def text(self, text: str) -> OptionsBuilder: ...
    def key(self, key: str) -> OptionsBuilder: ...
    def is_other(self, is_other: bool) -> OptionsBuilder: ...
    def build(self) -> Options: ...
