from lark_oapi.core.construct import init as init

class ParticipantQualityListExportResponseBody:
    task_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ParticipantQualityListExportResponseBodyBuilder: ...

class ParticipantQualityListExportResponseBodyBuilder:
    def __init__(self) -> None: ...
    def task_id(self, task_id: str) -> ParticipantQualityListExportResponseBodyBuilder: ...
    def build(self) -> ParticipantQualityListExportResponseBody: ...
