from lark_oapi.core.construct import init as init

class ParticipantListExportRequestBody:
    meeting_start_time: int | None
    meeting_end_time: int | None
    meeting_status: int | None
    meeting_no: str | None
    user_id: str | None
    room_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ParticipantListExportRequestBodyBuilder: ...

class ParticipantListExportRequestBodyBuilder:
    def __init__(self) -> None: ...
    def meeting_start_time(self, meeting_start_time: int) -> ParticipantListExportRequestBodyBuilder: ...
    def meeting_end_time(self, meeting_end_time: int) -> ParticipantListExportRequestBodyBuilder: ...
    def meeting_status(self, meeting_status: int) -> ParticipantListExportRequestBodyBuilder: ...
    def meeting_no(self, meeting_no: str) -> ParticipantListExportRequestBodyBuilder: ...
    def user_id(self, user_id: str) -> ParticipantListExportRequestBodyBuilder: ...
    def room_id(self, room_id: str) -> ParticipantListExportRequestBodyBuilder: ...
    def build(self) -> ParticipantListExportRequestBody: ...
