from .patch_reserve_config_admin_request_body import PatchReserveConfigAdminRequestBody as PatchReserveConfigAdminRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PatchReserveConfigAdminRequest(BaseRequest):
    user_id_type: str | None
    reserve_config_id: str | None
    request_body: PatchReserveConfigAdminRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PatchReserveConfigAdminRequestBuilder: ...

class PatchReserveConfigAdminRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> PatchReserveConfigAdminRequestBuilder: ...
    def reserve_config_id(self, reserve_config_id: str) -> PatchReserveConfigAdminRequestBuilder: ...
    def request_body(self, request_body: PatchReserveConfigAdminRequestBody) -> PatchReserveConfigAdminRequestBuilder: ...
    def build(self) -> PatchReserveConfigAdminRequest: ...
