from lark_oapi.core.construct import init as init

class PatchRoomLevelResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchRoomLevelResponseBodyBuilder: ...

class PatchRoomLevelResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> PatchRoomLevelResponseBody: ...
