from .patch_reserve_config_disable_inform_request_body import PatchReserveConfigDisableInformRequestBody as PatchReserveConfigDisableInformRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PatchReserveConfigDisableInformRequest(BaseRequest):
    user_id_type: str | None
    reserve_config_id: str | None
    request_body: PatchReserveConfigDisableInformRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PatchReserveConfigDisableInformRequestBuilder: ...

class PatchReserveConfigDisableInformRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> PatchReserveConfigDisableInformRequestBuilder: ...
    def reserve_config_id(self, reserve_config_id: str) -> PatchReserveConfigDisableInformRequestBuilder: ...
    def request_body(self, request_body: PatchReserveConfigDisableInformRequestBody) -> PatchReserveConfigDisableInformRequestBuilder: ...
    def build(self) -> PatchReserveConfigDisableInformRequest: ...
