from .approval_config import ApprovalConfig as ApprovalConfig
from .reserve_scope_config import ReserveScopeConfig as ReserveScopeConfig
from .time_config import TimeConfig as TimeConfig
from lark_oapi.core.construct import init as init

class PatchReserveConfigRequestBody:
    scope_type: int | None
    approval_config: ApprovalConfig | None
    time_config: TimeConfig | None
    reserve_scope_config: ReserveScopeConfig | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchReserveConfigRequestBodyBuilder: ...

class PatchReserveConfigRequestBodyBuilder:
    def __init__(self) -> None: ...
    def scope_type(self, scope_type: int) -> PatchReserveConfigRequestBodyBuilder: ...
    def approval_config(self, approval_config: ApprovalConfig) -> PatchReserveConfigRequestBodyBuilder: ...
    def time_config(self, time_config: TimeConfig) -> PatchReserveConfigRequestBodyBuilder: ...
    def reserve_scope_config(self, reserve_scope_config: ReserveScopeConfig) -> PatchReserveConfigRequestBodyBuilder: ...
    def build(self) -> PatchReserveConfigRequestBody: ...
