from lark_oapi.core.construct import init as init

class QualityCpuUsage:
    time: str | None
    client_avg_cpu_usage: str | None
    client_max_cpu_usage: str | None
    system_avg_cpu_usage: str | None
    system_max_cpu_usage: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QualityCpuUsageBuilder: ...

class QualityCpuUsageBuilder:
    def __init__(self) -> None: ...
    def time(self, time: str) -> QualityCpuUsageBuilder: ...
    def client_avg_cpu_usage(self, client_avg_cpu_usage: str) -> QualityCpuUsageBuilder: ...
    def client_max_cpu_usage(self, client_max_cpu_usage: str) -> QualityCpuUsageBuilder: ...
    def system_avg_cpu_usage(self, system_avg_cpu_usage: str) -> QualityCpuUsageBuilder: ...
    def system_max_cpu_usage(self, system_max_cpu_usage: str) -> QualityCpuUsageBuilder: ...
    def build(self) -> QualityCpuUsage: ...
