from lark_oapi.core.construct import init as init

class RecordingPermissionObject:
    id: str | None
    type: int | None
    permission: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RecordingPermissionObjectBuilder: ...

class RecordingPermissionObjectBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> RecordingPermissionObjectBuilder: ...
    def type(self, type: int) -> RecordingPermissionObjectBuilder: ...
    def permission(self, permission: int) -> RecordingPermissionObjectBuilder: ...
    def build(self) -> RecordingPermissionObject: ...
