from lark_oapi.core.construct import init as init

class ReportMeetingDaily:
    date: int | None
    meeting_count: int | None
    meeting_duration: int | None
    participant_count: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReportMeetingDailyBuilder: ...

class ReportMeetingDailyBuilder:
    def __init__(self) -> None: ...
    def date(self, date: int) -> ReportMeetingDailyBuilder: ...
    def meeting_count(self, meeting_count: int) -> ReportMeetingDailyBuilder: ...
    def meeting_duration(self, meeting_duration: int) -> ReportMeetingDailyBuilder: ...
    def participant_count(self, participant_count: int) -> ReportMeetingDailyBuilder: ...
    def build(self) -> ReportMeetingDaily: ...
