from lark_oapi.core.construct import init as init

class ReportTopUser:
    id: int | None
    name: str | None
    user_type: int | None
    meeting_count: int | None
    meeting_duration: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReportTopUserBuilder: ...

class ReportTopUserBuilder:
    def __init__(self) -> None: ...
    def id(self, id: int) -> ReportTopUserBuilder: ...
    def name(self, name: str) -> ReportTopUserBuilder: ...
    def user_type(self, user_type: int) -> ReportTopUserBuilder: ...
    def meeting_count(self, meeting_count: int) -> ReportTopUserBuilder: ...
    def meeting_duration(self, meeting_duration: int) -> ReportTopUserBuilder: ...
    def build(self) -> ReportTopUser: ...
