from lark_oapi.core.construct import init as init

class ReserveAssignHost:
    user_type: int | None
    id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReserveAssignHostBuilder: ...

class ReserveAssignHostBuilder:
    def __init__(self) -> None: ...
    def user_type(self, user_type: int) -> ReserveAssignHostBuilder: ...
    def id(self, id: str) -> ReserveAssignHostBuilder: ...
    def build(self) -> ReserveAssignHost: ...
