from .approval_config import ApprovalConfig as ApprovalConfig
from .reserve_scope_config import ReserveScopeConfig as ReserveScopeConfig
from .time_config import TimeConfig as TimeConfig
from lark_oapi.core.construct import init as init

class ReserveScopeReserveConfigResponseBody:
    approve_config: ApprovalConfig | None
    time_config: TimeConfig | None
    reserve_scope_config: ReserveScopeConfig | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReserveScopeReserveConfigResponseBodyBuilder: ...

class ReserveScopeReserveConfigResponseBodyBuilder:
    def __init__(self) -> None: ...
    def approve_config(self, approve_config: ApprovalConfig) -> ReserveScopeReserveConfigResponseBodyBuilder: ...
    def time_config(self, time_config: TimeConfig) -> ReserveScopeReserveConfigResponseBodyBuilder: ...
    def reserve_scope_config(self, reserve_scope_config: ReserveScopeConfig) -> ReserveScopeReserveConfigResponseBodyBuilder: ...
    def build(self) -> ReserveScopeReserveConfigResponseBody: ...
