from .reserve_meeting_setting import ReserveMeetingSetting as ReserveMeetingSetting
from lark_oapi.core.construct import init as init

class Reserve:
    id: int | None
    meeting_no: str | None
    password: str | None
    url: str | None
    app_link: str | None
    live_link: str | None
    end_time: int | None
    expire_status: int | None
    reserve_user_id: str | None
    meeting_settings: ReserveMeetingSetting | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReserveBuilder: ...

class ReserveBuilder:
    def __init__(self) -> None: ...
    def id(self, id: int) -> ReserveBuilder: ...
    def meeting_no(self, meeting_no: str) -> ReserveBuilder: ...
    def password(self, password: str) -> ReserveBuilder: ...
    def url(self, url: str) -> ReserveBuilder: ...
    def app_link(self, app_link: str) -> ReserveBuilder: ...
    def live_link(self, live_link: str) -> ReserveBuilder: ...
    def end_time(self, end_time: int) -> ReserveBuilder: ...
    def expire_status(self, expire_status: int) -> ReserveBuilder: ...
    def reserve_user_id(self, reserve_user_id: str) -> ReserveBuilder: ...
    def meeting_settings(self, meeting_settings: ReserveMeetingSetting) -> ReserveBuilder: ...
    def build(self) -> Reserve: ...
