from .reserve_permission_checker import ReservePermissionChecker as ReservePermissionChecker
from lark_oapi.core.construct import init as init

class ReserveActionPermission:
    permission: int | None
    permission_checkers: list[ReservePermissionChecker] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReserveActionPermissionBuilder: ...

class ReserveActionPermissionBuilder:
    def __init__(self) -> None: ...
    def permission(self, permission: int) -> ReserveActionPermissionBuilder: ...
    def permission_checkers(self, permission_checkers: list[ReservePermissionChecker]) -> ReserveActionPermissionBuilder: ...
    def build(self) -> ReserveActionPermission: ...
