from .reserve_callee import ReserveCallee as ReserveCallee
from lark_oapi.core.construct import init as init

class ReserveCallSetting:
    callee: ReserveCallee | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReserveCallSettingBuilder: ...

class ReserveCallSettingBuilder:
    def __init__(self) -> None: ...
    def callee(self, callee: ReserveCallee) -> ReserveCallSettingBuilder: ...
    def build(self) -> ReserveCallSetting: ...
