from .custom_list import CustomList as CustomList
from .subscribe_user import SubscribeUser as SubscribeUser
from lark_oapi.core.construct import init as init

class ReserveFormConfig:
    if_cover_child_scope: bool | None
    reserve_form: bool | None
    notified_users: list[SubscribeUser] | None
    notified_time: int | None
    time_unit: int | None
    custom_list: list[CustomList] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReserveFormConfigBuilder: ...

class ReserveFormConfigBuilder:
    def __init__(self) -> None: ...
    def if_cover_child_scope(self, if_cover_child_scope: bool) -> ReserveFormConfigBuilder: ...
    def reserve_form(self, reserve_form: bool) -> ReserveFormConfigBuilder: ...
    def notified_users(self, notified_users: list[SubscribeUser]) -> ReserveFormConfigBuilder: ...
    def notified_time(self, notified_time: int) -> ReserveFormConfigBuilder: ...
    def time_unit(self, time_unit: int) -> ReserveFormConfigBuilder: ...
    def custom_list(self, custom_list: list[CustomList]) -> ReserveFormConfigBuilder: ...
    def build(self) -> ReserveFormConfig: ...
