from lark_oapi.core.construct import init as init

class ResourceReservationListExportRequestBody:
    room_level_id: str | None
    need_topic: bool | None
    start_time: int | None
    end_time: int | None
    room_ids: list[str] | None
    is_exclude: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ResourceReservationListExportRequestBodyBuilder: ...

class ResourceReservationListExportRequestBodyBuilder:
    def __init__(self) -> None: ...
    def room_level_id(self, room_level_id: str) -> ResourceReservationListExportRequestBodyBuilder: ...
    def need_topic(self, need_topic: bool) -> ResourceReservationListExportRequestBodyBuilder: ...
    def start_time(self, start_time: int) -> ResourceReservationListExportRequestBodyBuilder: ...
    def end_time(self, end_time: int) -> ResourceReservationListExportRequestBodyBuilder: ...
    def room_ids(self, room_ids: list[str]) -> ResourceReservationListExportRequestBodyBuilder: ...
    def is_exclude(self, is_exclude: bool) -> ResourceReservationListExportRequestBodyBuilder: ...
    def build(self) -> ResourceReservationListExportRequestBody: ...
