from lark_oapi.core.construct import init as init

class ResourceReservationListExportResponseBody:
    task_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ResourceReservationListExportResponseBodyBuilder: ...

class ResourceReservationListExportResponseBodyBuilder:
    def __init__(self) -> None: ...
    def task_id(self, task_id: str) -> ResourceReservationListExportResponseBodyBuilder: ...
    def build(self) -> ResourceReservationListExportResponseBody: ...
