from lark_oapi.core.construct import init as init

class RoomLevel:
    room_level_id: str | None
    name: str | None
    parent_id: str | None
    path: list[str] | None
    has_child: bool | None
    custom_group_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RoomLevelBuilder: ...

class RoomLevelBuilder:
    def __init__(self) -> None: ...
    def room_level_id(self, room_level_id: str) -> RoomLevelBuilder: ...
    def name(self, name: str) -> RoomLevelBuilder: ...
    def parent_id(self, parent_id: str) -> RoomLevelBuilder: ...
    def path(self, path: list[str]) -> RoomLevelBuilder: ...
    def has_child(self, has_child: bool) -> RoomLevelBuilder: ...
    def custom_group_id(self, custom_group_id: str) -> RoomLevelBuilder: ...
    def build(self) -> RoomLevel: ...
