from lark_oapi.core.construct import init as init

class RoomDigitalSignageMaterial:
    id: str | None
    name: str | None
    material_type: int | None
    url: str | None
    duration: int | None
    cover: str | None
    md5: str | None
    vid: str | None
    size: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RoomDigitalSignageMaterialBuilder: ...

class RoomDigitalSignageMaterialBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> RoomDigitalSignageMaterialBuilder: ...
    def name(self, name: str) -> RoomDigitalSignageMaterialBuilder: ...
    def material_type(self, material_type: int) -> RoomDigitalSignageMaterialBuilder: ...
    def url(self, url: str) -> RoomDigitalSignageMaterialBuilder: ...
    def duration(self, duration: int) -> RoomDigitalSignageMaterialBuilder: ...
    def cover(self, cover: str) -> RoomDigitalSignageMaterialBuilder: ...
    def md5(self, md5: str) -> RoomDigitalSignageMaterialBuilder: ...
    def vid(self, vid: str) -> RoomDigitalSignageMaterialBuilder: ...
    def size(self, size: str) -> RoomDigitalSignageMaterialBuilder: ...
    def build(self) -> RoomDigitalSignageMaterial: ...
