from .room_config import RoomConfig as RoomConfig
from lark_oapi.core.construct import init as init

class ScopeConfig:
    scope_type: int | None
    scope_id: str | None
    scope_config: RoomConfig | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ScopeConfigBuilder: ...

class ScopeConfigBuilder:
    def __init__(self) -> None: ...
    def scope_type(self, scope_type: int) -> ScopeConfigBuilder: ...
    def scope_id(self, scope_id: str) -> ScopeConfigBuilder: ...
    def scope_config(self, scope_config: RoomConfig) -> ScopeConfigBuilder: ...
    def build(self) -> ScopeConfig: ...
