from lark_oapi.core.construct import init as init

class SearchRoomLevelResponseBody:
    level_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SearchRoomLevelResponseBodyBuilder: ...

class SearchRoomLevelResponseBodyBuilder:
    def __init__(self) -> None: ...
    def level_ids(self, level_ids: list[str]) -> SearchRoomLevelResponseBodyBuilder: ...
    def build(self) -> SearchRoomLevelResponseBody: ...
