from .room_config import RoomConfig as RoomConfig
from lark_oapi.core.construct import init as init

class SetRoomConfigRequestBody:
    scope: int | None
    country_id: str | None
    district_id: str | None
    building_id: str | None
    floor_name: str | None
    room_id: str | None
    room_config: RoomConfig | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SetRoomConfigRequestBodyBuilder: ...

class SetRoomConfigRequestBodyBuilder:
    def __init__(self) -> None: ...
    def scope(self, scope: int) -> SetRoomConfigRequestBodyBuilder: ...
    def country_id(self, country_id: str) -> SetRoomConfigRequestBodyBuilder: ...
    def district_id(self, district_id: str) -> SetRoomConfigRequestBodyBuilder: ...
    def building_id(self, building_id: str) -> SetRoomConfigRequestBodyBuilder: ...
    def floor_name(self, floor_name: str) -> SetRoomConfigRequestBodyBuilder: ...
    def room_id(self, room_id: str) -> SetRoomConfigRequestBodyBuilder: ...
    def room_config(self, room_config: RoomConfig) -> SetRoomConfigRequestBodyBuilder: ...
    def build(self) -> SetRoomConfigRequestBody: ...
