from .meeting_user import MeetingUser as MeetingUser
from lark_oapi.core.construct import init as init

class SetHostMeetingRequestBody:
    host_user: MeetingUser | None
    old_host_user: MeetingUser | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SetHostMeetingRequestBodyBuilder: ...

class SetHostMeetingRequestBodyBuilder:
    def __init__(self) -> None: ...
    def host_user(self, host_user: MeetingUser) -> SetHostMeetingRequestBodyBuilder: ...
    def old_host_user(self, old_host_user: MeetingUser) -> SetHostMeetingRequestBodyBuilder: ...
    def build(self) -> SetHostMeetingRequestBody: ...
