from lark_oapi.core.construct import init as init

class SetRoomAccessCodeRoomConfigRequestBody:
    scope: int | None
    country_id: str | None
    district_id: str | None
    building_id: str | None
    floor_name: str | None
    room_id: str | None
    valid_day: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SetRoomAccessCodeRoomConfigRequestBodyBuilder: ...

class SetRoomAccessCodeRoomConfigRequestBodyBuilder:
    def __init__(self) -> None: ...
    def scope(self, scope: int) -> SetRoomAccessCodeRoomConfigRequestBodyBuilder: ...
    def country_id(self, country_id: str) -> SetRoomAccessCodeRoomConfigRequestBodyBuilder: ...
    def district_id(self, district_id: str) -> SetRoomAccessCodeRoomConfigRequestBodyBuilder: ...
    def building_id(self, building_id: str) -> SetRoomAccessCodeRoomConfigRequestBodyBuilder: ...
    def floor_name(self, floor_name: str) -> SetRoomAccessCodeRoomConfigRequestBodyBuilder: ...
    def room_id(self, room_id: str) -> SetRoomAccessCodeRoomConfigRequestBodyBuilder: ...
    def valid_day(self, valid_day: int) -> SetRoomAccessCodeRoomConfigRequestBodyBuilder: ...
    def build(self) -> SetRoomAccessCodeRoomConfigRequestBody: ...
