from lark_oapi.core.construct import init as init

class SetRoomAccessCodeRoomConfigResponseBody:
    access_code: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SetRoomAccessCodeRoomConfigResponseBodyBuilder: ...

class SetRoomAccessCodeRoomConfigResponseBodyBuilder:
    def __init__(self) -> None: ...
    def access_code(self, access_code: str) -> SetRoomAccessCodeRoomConfigResponseBodyBuilder: ...
    def build(self) -> SetRoomAccessCodeRoomConfigResponseBody: ...
