from lark_oapi.core.construct import init as init

class StopMeetingRecordingRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> StopMeetingRecordingRequestBodyBuilder: ...

class StopMeetingRecordingRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> StopMeetingRecordingRequestBody: ...
