from .key_point_match_details import KeyPointMatchDetails as KeyPointMatchDetails
from lark_oapi.core.construct import init as init

class SubjectiveCheckOutput:
    keypoints: list[str] | None
    key_point_match_details: list[KeyPointMatchDetails] | None
    user_prompt_outputs: list[str] | None
    status_code: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SubjectiveCheckOutputBuilder: ...

class SubjectiveCheckOutputBuilder:
    def __init__(self) -> None: ...
    def keypoints(self, keypoints: list[str]) -> SubjectiveCheckOutputBuilder: ...
    def key_point_match_details(self, key_point_match_details: list[KeyPointMatchDetails]) -> SubjectiveCheckOutputBuilder: ...
    def user_prompt_outputs(self, user_prompt_outputs: list[str]) -> SubjectiveCheckOutputBuilder: ...
    def status_code(self, status_code: int) -> SubjectiveCheckOutputBuilder: ...
    def build(self) -> SubjectiveCheckOutput: ...
