from .user_id import UserId as UserId
from lark_oapi.core.construct import init as init

class SubscribeUserEvent:
    user_id: UserId | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SubscribeUserEventBuilder: ...

class SubscribeUserEventBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: UserId) -> SubscribeUserEventBuilder: ...
    def build(self) -> SubscribeUserEvent: ...
