from .reserve import Reserve as Reserve
from .reserve_correction_check_info import ReserveCorrectionCheckInfo as ReserveCorrectionCheckInfo
from lark_oapi.core.construct import init as init

class UpdateReserveResponseBody:
    reserve: Reserve | None
    reserve_correction_check_info: ReserveCorrectionCheckInfo | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateReserveResponseBodyBuilder: ...

class UpdateReserveResponseBodyBuilder:
    def __init__(self) -> None: ...
    def reserve(self, reserve: Reserve) -> UpdateReserveResponseBodyBuilder: ...
    def reserve_correction_check_info(self, reserve_correction_check_info: ReserveCorrectionCheckInfo) -> UpdateReserveResponseBodyBuilder: ...
    def build(self) -> UpdateReserveResponseBody: ...
