from .reserve_meeting_setting import ReserveMeetingSetting as ReserveMeetingSetting
from lark_oapi.core.construct import init as init

class UpdateReserveRequestBody:
    end_time: int | None
    meeting_settings: ReserveMeetingSetting | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateReserveRequestBodyBuilder: ...

class UpdateReserveRequestBodyBuilder:
    def __init__(self) -> None: ...
    def end_time(self, end_time: int) -> UpdateReserveRequestBodyBuilder: ...
    def meeting_settings(self, meeting_settings: ReserveMeetingSetting) -> UpdateReserveRequestBodyBuilder: ...
    def build(self) -> UpdateReserveRequestBody: ...
