from ..model.create_group_request import CreateGroupRequest as CreateGroupRequest
from ..model.create_group_response import CreateGroupResponse as CreateGroupResponse
from ..model.delete_group_request import DeleteGroupRequest as DeleteGroupRequest
from ..model.delete_group_response import DeleteGroupResponse as DeleteGroupResponse
from ..model.get_group_request import GetGroupRequest as GetGroupRequest
from ..model.get_group_response import GetGroupResponse as GetGroupResponse
from ..model.list_group_request import ListGroupRequest as ListGroupRequest
from ..model.list_group_response import ListGroupResponse as ListGroupResponse
from ..model.list_user_group_request import ListUserGroupRequest as ListUserGroupRequest
from ..model.list_user_group_response import ListUserGroupResponse as ListUserGroupResponse
from ..model.search_group_request import SearchGroupRequest as SearchGroupRequest
from ..model.search_group_response import SearchGroupResponse as SearchGroupResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class Group:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def create(self, request: CreateGroupRequest, option: RequestOption | None = None) -> CreateGroupResponse: ...
    async def acreate(self, request: CreateGroupRequest, option: RequestOption | None = None) -> CreateGroupResponse: ...
    def delete(self, request: DeleteGroupRequest, option: RequestOption | None = None) -> DeleteGroupResponse: ...
    async def adelete(self, request: DeleteGroupRequest, option: RequestOption | None = None) -> DeleteGroupResponse: ...
    def get(self, request: GetGroupRequest, option: RequestOption | None = None) -> GetGroupResponse: ...
    async def aget(self, request: GetGroupRequest, option: RequestOption | None = None) -> GetGroupResponse: ...
    def list(self, request: ListGroupRequest, option: RequestOption | None = None) -> ListGroupResponse: ...
    async def alist(self, request: ListGroupRequest, option: RequestOption | None = None) -> ListGroupResponse: ...
    def list_user(self, request: ListUserGroupRequest, option: RequestOption | None = None) -> ListUserGroupResponse: ...
    async def alist_user(self, request: ListUserGroupRequest, option: RequestOption | None = None) -> ListUserGroupResponse: ...
    def search(self, request: SearchGroupRequest, option: RequestOption | None = None) -> SearchGroupResponse: ...
    async def asearch(self, request: SearchGroupRequest, option: RequestOption | None = None) -> SearchGroupResponse: ...
