from lark_oapi.core.construct import init as init

class AllowedEditModes:
    manual: bool | None
    scan: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AllowedEditModesBuilder: ...

class AllowedEditModesBuilder:
    def __init__(self) -> None: ...
    def manual(self, manual: bool) -> AllowedEditModesBuilder: ...
    def scan(self, scan: bool) -> AllowedEditModesBuilder: ...
    def build(self) -> AllowedEditModes: ...
