from lark_oapi.core.construct import init as init

class App:
    app_token: str | None
    name: str | None
    revision: int | None
    folder_token: str | None
    url: str | None
    default_table_id: str | None
    time_zone: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppBuilder: ...

class AppBuilder:
    def __init__(self) -> None: ...
    def app_token(self, app_token: str) -> AppBuilder: ...
    def name(self, name: str) -> AppBuilder: ...
    def revision(self, revision: int) -> AppBuilder: ...
    def folder_token(self, folder_token: str) -> AppBuilder: ...
    def url(self, url: str) -> AppBuilder: ...
    def default_table_id(self, default_table_id: str) -> AppBuilder: ...
    def time_zone(self, time_zone: str) -> AppBuilder: ...
    def build(self) -> App: ...
