from lark_oapi.core.construct import init as init

class AppRoleMemberId:
    type: str | None
    id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppRoleMemberIdBuilder: ...

class AppRoleMemberIdBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> AppRoleMemberIdBuilder: ...
    def id(self, id: str) -> AppRoleMemberIdBuilder: ...
    def build(self) -> AppRoleMemberId: ...
