from .app_table_view_property_filter_info_condition import AppTableViewPropertyFilterInfoCondition as AppTableViewPropertyFilterInfoCondition
from lark_oapi.core.construct import init as init

class AppTableViewPropertyFilterInfo:
    conjunction: str | None
    conditions: list[AppTableViewPropertyFilterInfoCondition] | None
    condition_omitted: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppTableViewPropertyFilterInfoBuilder: ...

class AppTableViewPropertyFilterInfoBuilder:
    def __init__(self) -> None: ...
    def conjunction(self, conjunction: str) -> AppTableViewPropertyFilterInfoBuilder: ...
    def conditions(self, conditions: list[AppTableViewPropertyFilterInfoCondition]) -> AppTableViewPropertyFilterInfoBuilder: ...
    def condition_omitted(self, condition_omitted: bool) -> AppTableViewPropertyFilterInfoBuilder: ...
    def build(self) -> AppTableViewPropertyFilterInfo: ...
