from .app_field_property_auto_serial_options import AppFieldPropertyAutoSerialOptions as AppFieldPropertyAutoSerialOptions
from lark_oapi.core.construct import init as init

class AppFieldPropertyAutoSerial:
    type: str | None
    options: list[AppFieldPropertyAutoSerialOptions] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppFieldPropertyAutoSerialBuilder: ...

class AppFieldPropertyAutoSerialBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> AppFieldPropertyAutoSerialBuilder: ...
    def options(self, options: list[AppFieldPropertyAutoSerialOptions]) -> AppFieldPropertyAutoSerialBuilder: ...
    def build(self) -> AppFieldPropertyAutoSerial: ...
