from lark_oapi.core.construct import init as init

class AppTableViewPropertyFilterInfoCondition:
    field_id: str | None
    operator: str | None
    value: str | None
    condition_id: str | None
    field_type: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppTableViewPropertyFilterInfoConditionBuilder: ...

class AppTableViewPropertyFilterInfoConditionBuilder:
    def __init__(self) -> None: ...
    def field_id(self, field_id: str) -> AppTableViewPropertyFilterInfoConditionBuilder: ...
    def operator(self, operator: str) -> AppTableViewPropertyFilterInfoConditionBuilder: ...
    def value(self, value: str) -> AppTableViewPropertyFilterInfoConditionBuilder: ...
    def condition_id(self, condition_id: str) -> AppTableViewPropertyFilterInfoConditionBuilder: ...
    def field_type(self, field_type: int) -> AppTableViewPropertyFilterInfoConditionBuilder: ...
    def build(self) -> AppTableViewPropertyFilterInfoCondition: ...
