from lark_oapi.core.construct import init as init

class AppConnector:
    token: str | None
    table_id: str | None
    src_table_path: str | None
    source_type: int | None
    sync_type: int | None
    field_sync_type: int | None
    sync_fields: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppConnectorBuilder: ...

class AppConnectorBuilder:
    def __init__(self) -> None: ...
    def token(self, token: str) -> AppConnectorBuilder: ...
    def table_id(self, table_id: str) -> AppConnectorBuilder: ...
    def src_table_path(self, src_table_path: str) -> AppConnectorBuilder: ...
    def source_type(self, source_type: int) -> AppConnectorBuilder: ...
    def sync_type(self, sync_type: int) -> AppConnectorBuilder: ...
    def field_sync_type(self, field_sync_type: int) -> AppConnectorBuilder: ...
    def sync_fields(self, sync_fields: list[str]) -> AppConnectorBuilder: ...
    def build(self) -> AppConnector: ...
