from lark_oapi.core.construct import init as init

class AppRoleTableRoleRecRuleCondition:
    field_name: str | None
    operator: str | None
    value: list[str] | None
    field_type: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppRoleTableRoleRecRuleConditionBuilder: ...

class AppRoleTableRoleRecRuleConditionBuilder:
    def __init__(self) -> None: ...
    def field_name(self, field_name: str) -> AppRoleTableRoleRecRuleConditionBuilder: ...
    def operator(self, operator: str) -> AppRoleTableRoleRecRuleConditionBuilder: ...
    def value(self, value: list[str]) -> AppRoleTableRoleRecRuleConditionBuilder: ...
    def field_type(self, field_type: int) -> AppRoleTableRoleRecRuleConditionBuilder: ...
    def build(self) -> AppRoleTableRoleRecRuleCondition: ...
