from lark_oapi.core.construct import init as init

class AppRoleBlockRole:
    block_id: str | None
    block_type: str | None
    block_perm: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppRoleBlockRoleBuilder: ...

class AppRoleBlockRoleBuilder:
    def __init__(self) -> None: ...
    def block_id(self, block_id: str) -> AppRoleBlockRoleBuilder: ...
    def block_type(self, block_type: str) -> AppRoleBlockRoleBuilder: ...
    def block_perm(self, block_perm: int) -> AppRoleBlockRoleBuilder: ...
    def build(self) -> AppRoleBlockRole: ...
