from lark_oapi.core.construct import init as init

class AppDashboard:
    block_id: str | None
    name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppDashboardBuilder: ...

class AppDashboardBuilder:
    def __init__(self) -> None: ...
    def block_id(self, block_id: str) -> AppDashboardBuilder: ...
    def name(self, name: str) -> AppDashboardBuilder: ...
    def build(self) -> AppDashboard: ...
