from .app_table_field_property_filter_info_condition import AppTableFieldPropertyFilterInfoCondition as AppTableFieldPropertyFilterInfoCondition
from lark_oapi.core.construct import init as init

class AppTableFieldPropertyFilterInfo:
    conjunction: str | None
    conditions: list[AppTableFieldPropertyFilterInfoCondition] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppTableFieldPropertyFilterInfoBuilder: ...

class AppTableFieldPropertyFilterInfoBuilder:
    def __init__(self) -> None: ...
    def conjunction(self, conjunction: str) -> AppTableFieldPropertyFilterInfoBuilder: ...
    def conditions(self, conditions: list[AppTableFieldPropertyFilterInfoCondition]) -> AppTableFieldPropertyFilterInfoBuilder: ...
    def build(self) -> AppTableFieldPropertyFilterInfo: ...
