from .person import Person as Person
from lark_oapi.core.construct import init as init
from typing import Any

class AppTableRecord:
    fields: dict[str, Any] | None
    record_id: str | None
    created_by: Person | None
    created_time: int | None
    last_modified_by: Person | None
    last_modified_time: int | None
    shared_url: str | None
    record_url: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppTableRecordBuilder: ...

class AppTableRecordBuilder:
    def __init__(self) -> None: ...
    def fields(self, fields: dict[str, Any]) -> AppTableRecordBuilder: ...
    def record_id(self, record_id: str) -> AppTableRecordBuilder: ...
    def created_by(self, created_by: Person) -> AppTableRecordBuilder: ...
    def created_time(self, created_time: int) -> AppTableRecordBuilder: ...
    def last_modified_by(self, last_modified_by: Person) -> AppTableRecordBuilder: ...
    def last_modified_time(self, last_modified_time: int) -> AppTableRecordBuilder: ...
    def shared_url(self, shared_url: str) -> AppTableRecordBuilder: ...
    def record_url(self, record_url: str) -> AppTableRecordBuilder: ...
    def build(self) -> AppTableRecord: ...
