from lark_oapi.core.construct import init as init

class AppFieldPropertyAutoSerialOptions:
    type: str | None
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppFieldPropertyAutoSerialOptionsBuilder: ...

class AppFieldPropertyAutoSerialOptionsBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> AppFieldPropertyAutoSerialOptionsBuilder: ...
    def value(self, value: str) -> AppFieldPropertyAutoSerialOptionsBuilder: ...
    def build(self) -> AppFieldPropertyAutoSerialOptions: ...
