from .app_table_field_property_type_ui_property import AppTableFieldPropertyTypeUiProperty as AppTableFieldPropertyTypeUiProperty
from lark_oapi.core.construct import init as init

class AppTableFieldPropertyType:
    data_type: int | None
    ui_property: AppTableFieldPropertyTypeUiProperty | None
    ui_type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppTableFieldPropertyTypeBuilder: ...

class AppTableFieldPropertyTypeBuilder:
    def __init__(self) -> None: ...
    def data_type(self, data_type: int) -> AppTableFieldPropertyTypeBuilder: ...
    def ui_property(self, ui_property: AppTableFieldPropertyTypeUiProperty) -> AppTableFieldPropertyTypeBuilder: ...
    def ui_type(self, ui_type: str) -> AppTableFieldPropertyTypeBuilder: ...
    def build(self) -> AppTableFieldPropertyType: ...
