from .app_table_field_property_filter_info import AppTableFieldPropertyFilterInfo as AppTableFieldPropertyFilterInfo
from lark_oapi.core.construct import init as init

class AppTableFieldPropertyLookupFilter:
    target_table: str | None
    filter_info: AppTableFieldPropertyFilterInfo | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppTableFieldPropertyLookupFilterBuilder: ...

class AppTableFieldPropertyLookupFilterBuilder:
    def __init__(self) -> None: ...
    def target_table(self, target_table: str) -> AppTableFieldPropertyLookupFilterBuilder: ...
    def filter_info(self, filter_info: AppTableFieldPropertyFilterInfo) -> AppTableFieldPropertyLookupFilterBuilder: ...
    def build(self) -> AppTableFieldPropertyLookupFilter: ...
