from lark_oapi.core.construct import init as init

class Attachment:
    file_token: str | None
    name: str | None
    type: str | None
    size: int | None
    url: str | None
    tmp_url: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AttachmentBuilder: ...

class AttachmentBuilder:
    def __init__(self) -> None: ...
    def file_token(self, file_token: str) -> AttachmentBuilder: ...
    def name(self, name: str) -> AttachmentBuilder: ...
    def type(self, type: str) -> AttachmentBuilder: ...
    def size(self, size: int) -> AttachmentBuilder: ...
    def url(self, url: str) -> AttachmentBuilder: ...
    def tmp_url(self, tmp_url: str) -> AttachmentBuilder: ...
    def build(self) -> Attachment: ...
