from lark_oapi.core.construct import init as init

class BatchCreateAppRoleMemberResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchCreateAppRoleMemberResponseBodyBuilder: ...

class BatchCreateAppRoleMemberResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> BatchCreateAppRoleMemberResponseBody: ...
