from .app_role_member_id import AppRoleMemberId as AppRoleMemberId
from lark_oapi.core.construct import init as init

class BatchDeleteAppRoleMemberRequestBody:
    member_list: list[AppRoleMemberId] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchDeleteAppRoleMemberRequestBodyBuilder: ...

class BatchDeleteAppRoleMemberRequestBodyBuilder:
    def __init__(self) -> None: ...
    def member_list(self, member_list: list[AppRoleMemberId]) -> BatchDeleteAppRoleMemberRequestBodyBuilder: ...
    def build(self) -> BatchDeleteAppRoleMemberRequestBody: ...
