from .delete_record import DeleteRecord as DeleteRecord
from lark_oapi.core.construct import init as init

class BatchDeleteAppTableRecordResponseBody:
    records: list[DeleteRecord] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchDeleteAppTableRecordResponseBodyBuilder: ...

class BatchDeleteAppTableRecordResponseBodyBuilder:
    def __init__(self) -> None: ...
    def records(self, records: list[DeleteRecord]) -> BatchDeleteAppTableRecordResponseBodyBuilder: ...
    def build(self) -> BatchDeleteAppTableRecordResponseBody: ...
