from .batch_get_app_table_record_request_body import BatchGetAppTableRecordRequestBody as BatchGetAppTableRecordRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchGetAppTableRecordRequest(BaseRequest):
    app_token: str | None
    table_id: str | None
    request_body: BatchGetAppTableRecordRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchGetAppTableRecordRequestBuilder: ...

class BatchGetAppTableRecordRequestBuilder:
    def __init__(self) -> None: ...
    def app_token(self, app_token: str) -> BatchGetAppTableRecordRequestBuilder: ...
    def table_id(self, table_id: str) -> BatchGetAppTableRecordRequestBuilder: ...
    def request_body(self, request_body: BatchGetAppTableRecordRequestBody) -> BatchGetAppTableRecordRequestBuilder: ...
    def build(self) -> BatchGetAppTableRecordRequest: ...
