from .batch_delete_app_table_record_request_body import BatchDeleteAppTableRecordRequestBody as BatchDeleteAppTableRecordRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchDeleteAppTableRecordRequest(BaseRequest):
    app_token: str | None
    table_id: str | None
    request_body: BatchDeleteAppTableRecordRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchDeleteAppTableRecordRequestBuilder: ...

class BatchDeleteAppTableRecordRequestBuilder:
    def __init__(self) -> None: ...
    def app_token(self, app_token: str) -> BatchDeleteAppTableRecordRequestBuilder: ...
    def table_id(self, table_id: str) -> BatchDeleteAppTableRecordRequestBuilder: ...
    def request_body(self, request_body: BatchDeleteAppTableRecordRequestBody) -> BatchDeleteAppTableRecordRequestBuilder: ...
    def build(self) -> BatchDeleteAppTableRecordRequest: ...
