from lark_oapi.core.construct import init as init

class BatchDeleteAppTableRecordRequestBody:
    records: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchDeleteAppTableRecordRequestBodyBuilder: ...

class BatchDeleteAppTableRecordRequestBodyBuilder:
    def __init__(self) -> None: ...
    def records(self, records: list[str]) -> BatchDeleteAppTableRecordRequestBodyBuilder: ...
    def build(self) -> BatchDeleteAppTableRecordRequestBody: ...
