from .app_table_record import AppTableRecord as AppTableRecord
from lark_oapi.core.construct import init as init

class BatchGetAppTableRecordResponseBody:
    records: list[AppTableRecord] | None
    forbidden_record_ids: list[str] | None
    absent_record_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchGetAppTableRecordResponseBodyBuilder: ...

class BatchGetAppTableRecordResponseBodyBuilder:
    def __init__(self) -> None: ...
    def records(self, records: list[AppTableRecord]) -> BatchGetAppTableRecordResponseBodyBuilder: ...
    def forbidden_record_ids(self, forbidden_record_ids: list[str]) -> BatchGetAppTableRecordResponseBodyBuilder: ...
    def absent_record_ids(self, absent_record_ids: list[str]) -> BatchGetAppTableRecordResponseBodyBuilder: ...
    def build(self) -> BatchGetAppTableRecordResponseBody: ...
