from .app import App as App
from lark_oapi.core.construct import init as init

class CopyAppResponseBody:
    app: App | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CopyAppResponseBodyBuilder: ...

class CopyAppResponseBodyBuilder:
    def __init__(self) -> None: ...
    def app(self, app: App) -> CopyAppResponseBodyBuilder: ...
    def build(self) -> CopyAppResponseBody: ...
