from .app_table_record import AppTableRecord as AppTableRecord
from lark_oapi.core.construct import init as init

class CreateAppTableRecordResponseBody:
    record: AppTableRecord | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateAppTableRecordResponseBodyBuilder: ...

class CreateAppTableRecordResponseBodyBuilder:
    def __init__(self) -> None: ...
    def record(self, record: AppTableRecord) -> CreateAppTableRecordResponseBodyBuilder: ...
    def build(self) -> CreateAppTableRecordResponseBody: ...
