from .req_view import ReqView as ReqView
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateAppTableViewRequest(BaseRequest):
    app_token: str | None
    table_id: str | None
    request_body: ReqView | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateAppTableViewRequestBuilder: ...

class CreateAppTableViewRequestBuilder:
    def __init__(self) -> None: ...
    def app_token(self, app_token: str) -> CreateAppTableViewRequestBuilder: ...
    def table_id(self, table_id: str) -> CreateAppTableViewRequestBuilder: ...
    def request_body(self, request_body: ReqView) -> CreateAppTableViewRequestBuilder: ...
    def build(self) -> CreateAppTableViewRequest: ...
