from lark_oapi.core.construct import init as init

class DeleteAppTableRecordRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteAppTableRecordRequestBodyBuilder: ...

class DeleteAppTableRecordRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteAppTableRecordRequestBody: ...
