from lark_oapi.core.construct import init as init

class DeleteAppRoleMemberRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteAppRoleMemberRequestBodyBuilder: ...

class DeleteAppRoleMemberRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteAppRoleMemberRequestBody: ...
