from lark_oapi.core.construct import init as init

class DeleteAppTableRecordResponseBody:
    deleted: bool | None
    record_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteAppTableRecordResponseBodyBuilder: ...

class DeleteAppTableRecordResponseBodyBuilder:
    def __init__(self) -> None: ...
    def deleted(self, deleted: bool) -> DeleteAppTableRecordResponseBodyBuilder: ...
    def record_id(self, record_id: str) -> DeleteAppTableRecordResponseBodyBuilder: ...
    def build(self) -> DeleteAppTableRecordResponseBody: ...
