from lark_oapi.core.construct import init as init

class DeleteAppRoleMemberResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteAppRoleMemberResponseBodyBuilder: ...

class DeleteAppRoleMemberResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteAppRoleMemberResponseBody: ...
