from lark_oapi.core.construct import init as init

class DeleteAppTableRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteAppTableRequestBodyBuilder: ...

class DeleteAppTableRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteAppTableRequestBody: ...
