from lark_oapi.core.construct import init as init

class DeleteRecord:
    deleted: bool | None
    record_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteRecordBuilder: ...

class DeleteRecordBuilder:
    def __init__(self) -> None: ...
    def deleted(self, deleted: bool) -> DeleteRecordBuilder: ...
    def record_id(self, record_id: str) -> DeleteRecordBuilder: ...
    def build(self) -> DeleteRecord: ...
