from lark_oapi.core.construct import init as init

class GetAppTableRecordRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetAppTableRecordRequestBodyBuilder: ...

class GetAppTableRecordRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetAppTableRecordRequestBody: ...
