from .display_app import DisplayApp as DisplayApp
from lark_oapi.core.construct import init as init

class GetAppResponseBody:
    app: DisplayApp | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetAppResponseBodyBuilder: ...

class GetAppResponseBodyBuilder:
    def __init__(self) -> None: ...
    def app(self, app: DisplayApp) -> GetAppResponseBodyBuilder: ...
    def build(self) -> GetAppResponseBody: ...
