from lark_oapi.core.construct import init as init

class Group:
    id: str | None
    name: str | None
    avatar_url: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GroupBuilder: ...

class GroupBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> GroupBuilder: ...
    def name(self, name: str) -> GroupBuilder: ...
    def avatar_url(self, avatar_url: str) -> GroupBuilder: ...
    def build(self) -> Group: ...
