from .app_role import AppRole as AppRole
from lark_oapi.core.construct import init as init

class ListAppRoleResponseBody:
    items: list[AppRole] | None
    page_token: str | None
    has_more: bool | None
    total: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListAppRoleResponseBodyBuilder: ...

class ListAppRoleResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[AppRole]) -> ListAppRoleResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListAppRoleResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListAppRoleResponseBodyBuilder: ...
    def total(self, total: int) -> ListAppRoleResponseBodyBuilder: ...
    def build(self) -> ListAppRoleResponseBody: ...
