from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListAppDashboardRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    app_token: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListAppDashboardRequestBuilder: ...

class ListAppDashboardRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> ListAppDashboardRequestBuilder: ...
    def page_token(self, page_token: str) -> ListAppDashboardRequestBuilder: ...
    def app_token(self, app_token: str) -> ListAppDashboardRequestBuilder: ...
    def build(self) -> ListAppDashboardRequest: ...
