from .app_role_member import AppRoleMember as AppRoleMember
from lark_oapi.core.construct import init as init

class ListAppRoleMemberResponseBody:
    items: list[AppRoleMember] | None
    has_more: bool | None
    page_token: str | None
    total: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListAppRoleMemberResponseBodyBuilder: ...

class ListAppRoleMemberResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[AppRoleMember]) -> ListAppRoleMemberResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListAppRoleMemberResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListAppRoleMemberResponseBodyBuilder: ...
    def total(self, total: int) -> ListAppRoleMemberResponseBodyBuilder: ...
    def build(self) -> ListAppRoleMemberResponseBody: ...
