from .app_table_field_for_list import AppTableFieldForList as AppTableFieldForList
from lark_oapi.core.construct import init as init

class ListAppTableFieldResponseBody:
    has_more: bool | None
    page_token: str | None
    total: int | None
    items: list[AppTableFieldForList] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListAppTableFieldResponseBodyBuilder: ...

class ListAppTableFieldResponseBodyBuilder:
    def __init__(self) -> None: ...
    def has_more(self, has_more: bool) -> ListAppTableFieldResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListAppTableFieldResponseBodyBuilder: ...
    def total(self, total: int) -> ListAppTableFieldResponseBodyBuilder: ...
    def items(self, items: list[AppTableFieldForList]) -> ListAppTableFieldResponseBodyBuilder: ...
    def build(self) -> ListAppTableFieldResponseBody: ...
