from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListAppWorkflowRequest(BaseRequest):
    page_token: str | None
    page_size: int | None
    app_token: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListAppWorkflowRequestBuilder: ...

class ListAppWorkflowRequestBuilder:
    def __init__(self) -> None: ...
    def page_token(self, page_token: str) -> ListAppWorkflowRequestBuilder: ...
    def page_size(self, page_size: int) -> ListAppWorkflowRequestBuilder: ...
    def app_token(self, app_token: str) -> ListAppWorkflowRequestBuilder: ...
    def build(self) -> ListAppWorkflowRequest: ...
