from .app_table_form_field import AppTableFormField as AppTableFormField
from lark_oapi.core.construct import init as init

class ListAppTableFormFieldResponseBody:
    items: list[AppTableFormField] | None
    page_token: str | None
    has_more: bool | None
    total: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListAppTableFormFieldResponseBodyBuilder: ...

class ListAppTableFormFieldResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[AppTableFormField]) -> ListAppTableFormFieldResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListAppTableFormFieldResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListAppTableFormFieldResponseBodyBuilder: ...
    def total(self, total: int) -> ListAppTableFormFieldResponseBodyBuilder: ...
    def build(self) -> ListAppTableFormFieldResponseBody: ...
