from lark_oapi.core.construct import init as init

class ListAppTableViewRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListAppTableViewRequestBodyBuilder: ...

class ListAppTableViewRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListAppTableViewRequestBody: ...
