from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListAppTableRecordRequest(BaseRequest):
    view_id: str | None
    filter: str | None
    sort: str | None
    field_names: str | None
    text_field_as_array: bool | None
    user_id_type: str | None
    display_formula_ref: bool | None
    automatic_fields: bool | None
    page_token: str | None
    page_size: int | None
    app_token: str | None
    table_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListAppTableRecordRequestBuilder: ...

class ListAppTableRecordRequestBuilder:
    def __init__(self) -> None: ...
    def view_id(self, view_id: str) -> ListAppTableRecordRequestBuilder: ...
    def filter(self, filter: str) -> ListAppTableRecordRequestBuilder: ...
    def sort(self, sort: str) -> ListAppTableRecordRequestBuilder: ...
    def field_names(self, field_names: str) -> ListAppTableRecordRequestBuilder: ...
    def text_field_as_array(self, text_field_as_array: bool) -> ListAppTableRecordRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> ListAppTableRecordRequestBuilder: ...
    def display_formula_ref(self, display_formula_ref: bool) -> ListAppTableRecordRequestBuilder: ...
    def automatic_fields(self, automatic_fields: bool) -> ListAppTableRecordRequestBuilder: ...
    def page_token(self, page_token: str) -> ListAppTableRecordRequestBuilder: ...
    def page_size(self, page_size: int) -> ListAppTableRecordRequestBuilder: ...
    def app_token(self, app_token: str) -> ListAppTableRecordRequestBuilder: ...
    def table_id(self, table_id: str) -> ListAppTableRecordRequestBuilder: ...
    def build(self) -> ListAppTableRecordRequest: ...
