from .app_table_view import AppTableView as AppTableView
from lark_oapi.core.construct import init as init

class ListAppTableViewResponseBody:
    items: list[AppTableView] | None
    page_token: str | None
    has_more: bool | None
    total: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListAppTableViewResponseBodyBuilder: ...

class ListAppTableViewResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[AppTableView]) -> ListAppTableViewResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListAppTableViewResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListAppTableViewResponseBodyBuilder: ...
    def total(self, total: int) -> ListAppTableViewResponseBodyBuilder: ...
    def build(self) -> ListAppTableViewResponseBody: ...
