from lark_oapi.core.construct import init as init

class ListAppTableRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListAppTableRequestBodyBuilder: ...

class ListAppTableRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListAppTableRequestBody: ...
