from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListAppTableFieldRequest(BaseRequest):
    view_id: str | None
    text_field_as_array: bool | None
    page_token: str | None
    page_size: int | None
    app_token: str | None
    table_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListAppTableFieldRequestBuilder: ...

class ListAppTableFieldRequestBuilder:
    def __init__(self) -> None: ...
    def view_id(self, view_id: str) -> ListAppTableFieldRequestBuilder: ...
    def text_field_as_array(self, text_field_as_array: bool) -> ListAppTableFieldRequestBuilder: ...
    def page_token(self, page_token: str) -> ListAppTableFieldRequestBuilder: ...
    def page_size(self, page_size: int) -> ListAppTableFieldRequestBuilder: ...
    def app_token(self, app_token: str) -> ListAppTableFieldRequestBuilder: ...
    def table_id(self, table_id: str) -> ListAppTableFieldRequestBuilder: ...
    def build(self) -> ListAppTableFieldRequest: ...
