from lark_oapi.core.construct import init as init

class Location:
    location: str | None
    pname: str | None
    cityname: str | None
    adname: str | None
    address: str | None
    name: str | None
    full_address: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LocationBuilder: ...

class LocationBuilder:
    def __init__(self) -> None: ...
    def location(self, location: str) -> LocationBuilder: ...
    def pname(self, pname: str) -> LocationBuilder: ...
    def cityname(self, cityname: str) -> LocationBuilder: ...
    def adname(self, adname: str) -> LocationBuilder: ...
    def address(self, address: str) -> LocationBuilder: ...
    def name(self, name: str) -> LocationBuilder: ...
    def full_address(self, full_address: str) -> LocationBuilder: ...
    def build(self) -> Location: ...
