from .app_table_form import AppTableForm as AppTableForm
from lark_oapi.core.construct import init as init

class PatchAppTableFormResponseBody:
    form: AppTableForm | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchAppTableFormResponseBodyBuilder: ...

class PatchAppTableFormResponseBodyBuilder:
    def __init__(self) -> None: ...
    def form(self, form: AppTableForm) -> PatchAppTableFormResponseBodyBuilder: ...
    def build(self) -> PatchAppTableFormResponseBody: ...
