from .app_table_view import AppTableView as AppTableView
from lark_oapi.core.construct import init as init

class PatchAppTableViewResponseBody:
    view: AppTableView | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchAppTableViewResponseBodyBuilder: ...

class PatchAppTableViewResponseBodyBuilder:
    def __init__(self) -> None: ...
    def view(self, view: AppTableView) -> PatchAppTableViewResponseBodyBuilder: ...
    def build(self) -> PatchAppTableViewResponseBody: ...
