from lark_oapi.core.construct import init as init

class Person:
    id: str | None
    name: str | None
    en_name: str | None
    email: str | None
    avatar_url: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PersonBuilder: ...

class PersonBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> PersonBuilder: ...
    def name(self, name: str) -> PersonBuilder: ...
    def en_name(self, en_name: str) -> PersonBuilder: ...
    def email(self, email: str) -> PersonBuilder: ...
    def avatar_url(self, avatar_url: str) -> PersonBuilder: ...
    def build(self) -> Person: ...
