from lark_oapi.core.construct import init as init

class ReqView:
    view_name: str | None
    view_type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReqViewBuilder: ...

class ReqViewBuilder:
    def __init__(self) -> None: ...
    def view_name(self, view_name: str) -> ReqViewBuilder: ...
    def view_type(self, view_type: str) -> ReqViewBuilder: ...
    def build(self) -> ReqView: ...
