from lark_oapi.core.construct import init as init

class ReqApp:
    name: str | None
    folder_token: str | None
    time_zone: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReqAppBuilder: ...

class ReqAppBuilder:
    def __init__(self) -> None: ...
    def name(self, name: str) -> ReqAppBuilder: ...
    def folder_token(self, folder_token: str) -> ReqAppBuilder: ...
    def time_zone(self, time_zone: str) -> ReqAppBuilder: ...
    def build(self) -> ReqApp: ...
