from .app_table_record import AppTableRecord as AppTableRecord
from lark_oapi.core.construct import init as init

class SearchAppTableRecordResponseBody:
    items: list[AppTableRecord] | None
    has_more: bool | None
    page_token: str | None
    total: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SearchAppTableRecordResponseBodyBuilder: ...

class SearchAppTableRecordResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[AppTableRecord]) -> SearchAppTableRecordResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> SearchAppTableRecordResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> SearchAppTableRecordResponseBodyBuilder: ...
    def total(self, total: int) -> SearchAppTableRecordResponseBodyBuilder: ...
    def build(self) -> SearchAppTableRecordResponseBody: ...
