from lark_oapi.core.construct import init as init

class UpdateAppRequestBody:
    name: str | None
    is_advanced: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateAppRequestBodyBuilder: ...

class UpdateAppRequestBodyBuilder:
    def __init__(self) -> None: ...
    def name(self, name: str) -> UpdateAppRequestBodyBuilder: ...
    def is_advanced(self, is_advanced: bool) -> UpdateAppRequestBodyBuilder: ...
    def build(self) -> UpdateAppRequestBody: ...
