from .display_app_v2 import DisplayAppV2 as DisplayAppV2
from lark_oapi.core.construct import init as init

class UpdateAppResponseBody:
    app: DisplayAppV2 | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateAppResponseBodyBuilder: ...

class UpdateAppResponseBodyBuilder:
    def __init__(self) -> None: ...
    def app(self, app: DisplayAppV2) -> UpdateAppResponseBodyBuilder: ...
    def build(self) -> UpdateAppResponseBody: ...
