from .app_table_field import AppTableField as AppTableField
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UpdateAppTableFieldRequest(BaseRequest):
    app_token: str | None
    table_id: str | None
    field_id: str | None
    request_body: AppTableField | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UpdateAppTableFieldRequestBuilder: ...

class UpdateAppTableFieldRequestBuilder:
    def __init__(self) -> None: ...
    def app_token(self, app_token: str) -> UpdateAppTableFieldRequestBuilder: ...
    def table_id(self, table_id: str) -> UpdateAppTableFieldRequestBuilder: ...
    def field_id(self, field_id: str) -> UpdateAppTableFieldRequestBuilder: ...
    def request_body(self, request_body: AppTableField) -> UpdateAppTableFieldRequestBuilder: ...
    def build(self) -> UpdateAppTableFieldRequest: ...
