from .app_table_field import AppTableField as AppTableField
from lark_oapi.core.construct import init as init

class UpdateAppTableFieldResponseBody:
    field: AppTableField | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateAppTableFieldResponseBodyBuilder: ...

class UpdateAppTableFieldResponseBodyBuilder:
    def __init__(self) -> None: ...
    def field(self, field: AppTableField) -> UpdateAppTableFieldResponseBodyBuilder: ...
    def build(self) -> UpdateAppTableFieldResponseBody: ...
