from .app_role import AppRole as AppRole
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UpdateAppRoleRequest(BaseRequest):
    app_token: str | None
    role_id: str | None
    request_body: AppRole | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UpdateAppRoleRequestBuilder: ...

class UpdateAppRoleRequestBuilder:
    def __init__(self) -> None: ...
    def app_token(self, app_token: str) -> UpdateAppRoleRequestBuilder: ...
    def role_id(self, role_id: str) -> UpdateAppRoleRequestBuilder: ...
    def request_body(self, request_body: AppRole) -> UpdateAppRoleRequestBuilder: ...
    def build(self) -> UpdateAppRoleRequest: ...
