from .model.p2_performance_review_data_changed_v2 import P2PerformanceReviewDataChangedV2 as P2PerformanceReviewDataChangedV2
from .model.p2_performance_stage_task_open_result_v2 import P2PerformanceStageTaskOpenResultV2 as P2PerformanceStageTaskOpenResultV2
from _typeshed import Incomplete
from lark_oapi.event.processor import IEventProcessor as IEventProcessor
from typing import Callable

class P2PerformanceReviewDataChangedV2Processor(IEventProcessor[P2PerformanceReviewDataChangedV2]):
    f: Incomplete
    def __init__(self, f: Callable[[P2PerformanceReviewDataChangedV2], None]) -> None: ...
    def type(self) -> type[P2PerformanceReviewDataChangedV2]: ...
    def do(self, data: P2PerformanceReviewDataChangedV2) -> None: ...

class P2PerformanceStageTaskOpenResultV2Processor(IEventProcessor[P2PerformanceStageTaskOpenResultV2]):
    f: Incomplete
    def __init__(self, f: Callable[[P2PerformanceStageTaskOpenResultV2], None]) -> None: ...
    def type(self) -> type[P2PerformanceStageTaskOpenResultV2]: ...
    def do(self, data: P2PerformanceStageTaskOpenResultV2) -> None: ...
