from lark_oapi.core.construct import init as init

class BasicRecognizeImageResponseBody:
    text_list: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BasicRecognizeImageResponseBodyBuilder: ...

class BasicRecognizeImageResponseBodyBuilder:
    def __init__(self) -> None: ...
    def text_list(self, text_list: list[str]) -> BasicRecognizeImageResponseBodyBuilder: ...
    def build(self) -> BasicRecognizeImageResponseBody: ...
