from lark_oapi.core.construct import init as init

class BasicRecognizeImageRequestBody:
    image: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BasicRecognizeImageRequestBodyBuilder: ...

class BasicRecognizeImageRequestBodyBuilder:
    def __init__(self) -> None: ...
    def image(self, image: str) -> BasicRecognizeImageRequestBodyBuilder: ...
    def build(self) -> BasicRecognizeImageRequestBody: ...
