from lark_oapi.core.construct import init as init

class AbnormalReasonElement:
    tag: str | None
    text: str | None
    href: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AbnormalReasonElementBuilder: ...

class AbnormalReasonElementBuilder:
    def __init__(self) -> None: ...
    def tag(self, tag: str) -> AbnormalReasonElementBuilder: ...
    def text(self, text: str) -> AbnormalReasonElementBuilder: ...
    def href(self, href: str) -> AbnormalReasonElementBuilder: ...
    def build(self) -> AbnormalReasonElement: ...
