from lark_oapi.core.construct import init as init

class ActiveLocationRequestBody:
    location_id: str | None
    effective_time: str | None
    active: bool | None
    operation_reason: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ActiveLocationRequestBodyBuilder: ...

class ActiveLocationRequestBodyBuilder:
    def __init__(self) -> None: ...
    def location_id(self, location_id: str) -> ActiveLocationRequestBodyBuilder: ...
    def effective_time(self, effective_time: str) -> ActiveLocationRequestBodyBuilder: ...
    def active(self, active: bool) -> ActiveLocationRequestBodyBuilder: ...
    def operation_reason(self, operation_reason: str) -> ActiveLocationRequestBodyBuilder: ...
    def build(self) -> ActiveLocationRequestBody: ...
