from lark_oapi.core.construct import init as init

class AddressForUpdate:
    address_id: str | None
    country_region_id: str | None
    region_id: str | None
    local_address_line1: str | None
    local_address_line2: str | None
    local_address_line3: str | None
    local_address_line4: str | None
    local_address_line5: str | None
    local_address_line6: str | None
    local_address_line7: str | None
    local_address_line8: str | None
    local_address_line9: str | None
    postal_code: str | None
    address_types: list[str] | None
    is_primary: bool | None
    is_public: bool | None
    city_id_v2: str | None
    district_id_v2: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AddressForUpdateBuilder: ...

class AddressForUpdateBuilder:
    def __init__(self) -> None: ...
    def address_id(self, address_id: str) -> AddressForUpdateBuilder: ...
    def country_region_id(self, country_region_id: str) -> AddressForUpdateBuilder: ...
    def region_id(self, region_id: str) -> AddressForUpdateBuilder: ...
    def local_address_line1(self, local_address_line1: str) -> AddressForUpdateBuilder: ...
    def local_address_line2(self, local_address_line2: str) -> AddressForUpdateBuilder: ...
    def local_address_line3(self, local_address_line3: str) -> AddressForUpdateBuilder: ...
    def local_address_line4(self, local_address_line4: str) -> AddressForUpdateBuilder: ...
    def local_address_line5(self, local_address_line5: str) -> AddressForUpdateBuilder: ...
    def local_address_line6(self, local_address_line6: str) -> AddressForUpdateBuilder: ...
    def local_address_line7(self, local_address_line7: str) -> AddressForUpdateBuilder: ...
    def local_address_line8(self, local_address_line8: str) -> AddressForUpdateBuilder: ...
    def local_address_line9(self, local_address_line9: str) -> AddressForUpdateBuilder: ...
    def postal_code(self, postal_code: str) -> AddressForUpdateBuilder: ...
    def address_types(self, address_types: list[str]) -> AddressForUpdateBuilder: ...
    def is_primary(self, is_primary: bool) -> AddressForUpdateBuilder: ...
    def is_public(self, is_public: bool) -> AddressForUpdateBuilder: ...
    def city_id_v2(self, city_id_v2: str) -> AddressForUpdateBuilder: ...
    def district_id_v2(self, district_id_v2: str) -> AddressForUpdateBuilder: ...
    def build(self) -> AddressForUpdate: ...
