from lark_oapi.core.construct import init as init

class ApproverInfo:
    approver_id: str | None
    process_id: str | None
    approver_status: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApproverInfoBuilder: ...

class ApproverInfoBuilder:
    def __init__(self) -> None: ...
    def approver_id(self, approver_id: str) -> ApproverInfoBuilder: ...
    def process_id(self, process_id: str) -> ApproverInfoBuilder: ...
    def approver_status(self, approver_status: int) -> ApproverInfoBuilder: ...
    def build(self) -> ApproverInfo: ...
