from lark_oapi.core.construct import init as init

class ApprovalGroup:
    approval_group_id: str | None
    process_id: str | None
    approval_group_status: str | None
    approval_group_status_v2: int | None
    topic: str | None
    adjust_reason: str | None
    effective_date: str | None
    created_by: str | None
    draft_id: str | None
    draft_status: str | None
    department_changes: list[str] | None
    job_changes: list[str] | None
    position_changes: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApprovalGroupBuilder: ...

class ApprovalGroupBuilder:
    def __init__(self) -> None: ...
    def approval_group_id(self, approval_group_id: str) -> ApprovalGroupBuilder: ...
    def process_id(self, process_id: str) -> ApprovalGroupBuilder: ...
    def approval_group_status(self, approval_group_status: str) -> ApprovalGroupBuilder: ...
    def approval_group_status_v2(self, approval_group_status_v2: int) -> ApprovalGroupBuilder: ...
    def topic(self, topic: str) -> ApprovalGroupBuilder: ...
    def adjust_reason(self, adjust_reason: str) -> ApprovalGroupBuilder: ...
    def effective_date(self, effective_date: str) -> ApprovalGroupBuilder: ...
    def created_by(self, created_by: str) -> ApprovalGroupBuilder: ...
    def draft_id(self, draft_id: str) -> ApprovalGroupBuilder: ...
    def draft_status(self, draft_status: str) -> ApprovalGroupBuilder: ...
    def department_changes(self, department_changes: list[str]) -> ApprovalGroupBuilder: ...
    def job_changes(self, job_changes: list[str]) -> ApprovalGroupBuilder: ...
    def position_changes(self, position_changes: list[str]) -> ApprovalGroupBuilder: ...
    def build(self) -> ApprovalGroup: ...
