from .object_field_data import ObjectFieldData as ObjectFieldData
from lark_oapi.core.construct import init as init

class BankAccountForUpdate:
    bank_name: str | None
    branch_name: str | None
    bank_account_number: str | None
    account_holder: str | None
    country_region_id: str | None
    bank_account_usages: list[str] | None
    bank_account_type: str | None
    custom_fields: list[ObjectFieldData] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BankAccountForUpdateBuilder: ...

class BankAccountForUpdateBuilder:
    def __init__(self) -> None: ...
    def bank_name(self, bank_name: str) -> BankAccountForUpdateBuilder: ...
    def branch_name(self, branch_name: str) -> BankAccountForUpdateBuilder: ...
    def bank_account_number(self, bank_account_number: str) -> BankAccountForUpdateBuilder: ...
    def account_holder(self, account_holder: str) -> BankAccountForUpdateBuilder: ...
    def country_region_id(self, country_region_id: str) -> BankAccountForUpdateBuilder: ...
    def bank_account_usages(self, bank_account_usages: list[str]) -> BankAccountForUpdateBuilder: ...
    def bank_account_type(self, bank_account_type: str) -> BankAccountForUpdateBuilder: ...
    def custom_fields(self, custom_fields: list[ObjectFieldData]) -> BankAccountForUpdateBuilder: ...
    def build(self) -> BankAccountForUpdate: ...
