from .basic_person_info import BasicPersonInfo as BasicPersonInfo
from lark_oapi.core.construct import init as init

class BasicEmployee:
    employment_id: str | None
    employment_id_v2: str | None
    employee_number: str | None
    email_address: str | None
    person_info: BasicPersonInfo | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BasicEmployeeBuilder: ...

class BasicEmployeeBuilder:
    def __init__(self) -> None: ...
    def employment_id(self, employment_id: str) -> BasicEmployeeBuilder: ...
    def employment_id_v2(self, employment_id_v2: str) -> BasicEmployeeBuilder: ...
    def employee_number(self, employee_number: str) -> BasicEmployeeBuilder: ...
    def email_address(self, email_address: str) -> BasicEmployeeBuilder: ...
    def person_info(self, person_info: BasicPersonInfo) -> BasicEmployeeBuilder: ...
    def build(self) -> BasicEmployee: ...
