from lark_oapi.core.construct import init as init

class BasicJobData:
    job_data_id: str | None
    employment_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BasicJobDataBuilder: ...

class BasicJobDataBuilder:
    def __init__(self) -> None: ...
    def job_data_id(self, job_data_id: str) -> BasicJobDataBuilder: ...
    def employment_id(self, employment_id: str) -> BasicJobDataBuilder: ...
    def build(self) -> BasicJobData: ...
