from .dimension_id_in_data import DimensionIdInData as DimensionIdInData
from lark_oapi.core.construct import init as init

class BatchV2WorkforcePlanDetailRequestBody:
    workforce_plan_id: str | None
    is_centralized_reporting_project: bool | None
    centralized_reporting_project_id: str | None
    dimension_id_in_datas: list[DimensionIdInData] | None
    include_missing_dimension_rows: bool | None
    filter_all_zero_value_rows: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchV2WorkforcePlanDetailRequestBodyBuilder: ...

class BatchV2WorkforcePlanDetailRequestBodyBuilder:
    def __init__(self) -> None: ...
    def workforce_plan_id(self, workforce_plan_id: str) -> BatchV2WorkforcePlanDetailRequestBodyBuilder: ...
    def is_centralized_reporting_project(self, is_centralized_reporting_project: bool) -> BatchV2WorkforcePlanDetailRequestBodyBuilder: ...
    def centralized_reporting_project_id(self, centralized_reporting_project_id: str) -> BatchV2WorkforcePlanDetailRequestBodyBuilder: ...
    def dimension_id_in_datas(self, dimension_id_in_datas: list[DimensionIdInData]) -> BatchV2WorkforcePlanDetailRequestBodyBuilder: ...
    def include_missing_dimension_rows(self, include_missing_dimension_rows: bool) -> BatchV2WorkforcePlanDetailRequestBodyBuilder: ...
    def filter_all_zero_value_rows(self, filter_all_zero_value_rows: bool) -> BatchV2WorkforcePlanDetailRequestBodyBuilder: ...
    def build(self) -> BatchV2WorkforcePlanDetailRequestBody: ...
