from lark_oapi.core.construct import init as init

class BatchSaveWorkforcePlanDetailRowResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchSaveWorkforcePlanDetailRowResponseBodyBuilder: ...

class BatchSaveWorkforcePlanDetailRowResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> BatchSaveWorkforcePlanDetailRowResponseBody: ...
