from lark_oapi.core.construct import init as init

class BatchGetLocationRequestBody:
    location_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchGetLocationRequestBodyBuilder: ...

class BatchGetLocationRequestBodyBuilder:
    def __init__(self) -> None: ...
    def location_ids(self, location_ids: list[str]) -> BatchGetLocationRequestBodyBuilder: ...
    def build(self) -> BatchGetLocationRequestBody: ...
