from .workforce_plan_detail_v2 import WorkforcePlanDetailV2 as WorkforcePlanDetailV2
from lark_oapi.core.construct import init as init

class BatchV2WorkforcePlanDetailResponseBody:
    workforce_plan_id: str | None
    centralized_reporting_project_id: str | None
    items: list[WorkforcePlanDetailV2] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchV2WorkforcePlanDetailResponseBodyBuilder: ...

class BatchV2WorkforcePlanDetailResponseBodyBuilder:
    def __init__(self) -> None: ...
    def workforce_plan_id(self, workforce_plan_id: str) -> BatchV2WorkforcePlanDetailResponseBodyBuilder: ...
    def centralized_reporting_project_id(self, centralized_reporting_project_id: str) -> BatchV2WorkforcePlanDetailResponseBodyBuilder: ...
    def items(self, items: list[WorkforcePlanDetailV2]) -> BatchV2WorkforcePlanDetailResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> BatchV2WorkforcePlanDetailResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> BatchV2WorkforcePlanDetailResponseBodyBuilder: ...
    def build(self) -> BatchV2WorkforcePlanDetailResponseBody: ...
