from .batch_get_location_request_body import BatchGetLocationRequestBody as BatchGetLocationRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchGetLocationRequest(BaseRequest):
    request_body: BatchGetLocationRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchGetLocationRequestBuilder: ...

class BatchGetLocationRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: BatchGetLocationRequestBody) -> BatchGetLocationRequestBuilder: ...
    def build(self) -> BatchGetLocationRequest: ...
