from .job_family import JobFamily as JobFamily
from lark_oapi.core.construct import init as init

class BatchGetJobFamilyResponseBody:
    items: list[JobFamily] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchGetJobFamilyResponseBodyBuilder: ...

class BatchGetJobFamilyResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[JobFamily]) -> BatchGetJobFamilyResponseBodyBuilder: ...
    def build(self) -> BatchGetJobFamilyResponseBody: ...
