from .batch_get_employee_request_body import BatchGetEmployeeRequestBody as BatchGetEmployeeRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchGetEmployeeRequest(BaseRequest):
    user_id_type: str | None
    department_id_type: str | None
    request_body: BatchGetEmployeeRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchGetEmployeeRequestBuilder: ...

class BatchGetEmployeeRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> BatchGetEmployeeRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> BatchGetEmployeeRequestBuilder: ...
    def request_body(self, request_body: BatchGetEmployeeRequestBody) -> BatchGetEmployeeRequestBuilder: ...
    def build(self) -> BatchGetEmployeeRequest: ...
