from .workforce_plan_detail import WorkforcePlanDetail as WorkforcePlanDetail
from lark_oapi.core.construct import init as init

class BatchWorkforcePlanDetailResponseBody:
    workforce_plan_id: str | None
    centralized_reporting_project_id: str | None
    items: list[WorkforcePlanDetail] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchWorkforcePlanDetailResponseBodyBuilder: ...

class BatchWorkforcePlanDetailResponseBodyBuilder:
    def __init__(self) -> None: ...
    def workforce_plan_id(self, workforce_plan_id: str) -> BatchWorkforcePlanDetailResponseBodyBuilder: ...
    def centralized_reporting_project_id(self, centralized_reporting_project_id: str) -> BatchWorkforcePlanDetailResponseBodyBuilder: ...
    def items(self, items: list[WorkforcePlanDetail]) -> BatchWorkforcePlanDetailResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> BatchWorkforcePlanDetailResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> BatchWorkforcePlanDetailResponseBodyBuilder: ...
    def build(self) -> BatchWorkforcePlanDetailResponseBody: ...
