from lark_oapi.core.construct import init as init

class BatchDeleteReportDetailRowResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchDeleteReportDetailRowResponseBodyBuilder: ...

class BatchDeleteReportDetailRowResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> BatchDeleteReportDetailRowResponseBody: ...
