from .batch_get_department_request_body import BatchGetDepartmentRequestBody as BatchGetDepartmentRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchGetDepartmentRequest(BaseRequest):
    user_id_type: str | None
    department_id_type: str | None
    request_body: BatchGetDepartmentRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchGetDepartmentRequestBuilder: ...

class BatchGetDepartmentRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> BatchGetDepartmentRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> BatchGetDepartmentRequestBuilder: ...
    def request_body(self, request_body: BatchGetDepartmentRequestBody) -> BatchGetDepartmentRequestBuilder: ...
    def build(self) -> BatchGetDepartmentRequest: ...
