from lark_oapi.core.construct import init as init

class BatchGetEmployeesBpRequestBody:
    employment_ids: list[str] | None
    get_all: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchGetEmployeesBpRequestBodyBuilder: ...

class BatchGetEmployeesBpRequestBodyBuilder:
    def __init__(self) -> None: ...
    def employment_ids(self, employment_ids: list[str]) -> BatchGetEmployeesBpRequestBodyBuilder: ...
    def get_all(self, get_all: bool) -> BatchGetEmployeesBpRequestBodyBuilder: ...
    def build(self) -> BatchGetEmployeesBpRequestBody: ...
