from lark_oapi.core.construct import init as init

class BatchDeleteWorkforcePlanDetailRowResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchDeleteWorkforcePlanDetailRowResponseBodyBuilder: ...

class BatchDeleteWorkforcePlanDetailRowResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> BatchDeleteWorkforcePlanDetailRowResponseBody: ...
