from .custom_field_data import CustomFieldData as CustomFieldData
from lark_oapi.core.construct import init as init

class ChangeFieldPair:
    origin_value: CustomFieldData | None
    target_value: CustomFieldData | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ChangeFieldPairBuilder: ...

class ChangeFieldPairBuilder:
    def __init__(self) -> None: ...
    def origin_value(self, origin_value: CustomFieldData) -> ChangeFieldPairBuilder: ...
    def target_value(self, target_value: CustomFieldData) -> ChangeFieldPairBuilder: ...
    def build(self) -> ChangeFieldPair: ...
