from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class CitizenshipStatus:
    id: str | None
    country_region_id: str | None
    active: bool | None
    name: list[I18n] | None
    citizenship_status: list[I18n] | None
    view_order: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CitizenshipStatusBuilder: ...

class CitizenshipStatusBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> CitizenshipStatusBuilder: ...
    def country_region_id(self, country_region_id: str) -> CitizenshipStatusBuilder: ...
    def active(self, active: bool) -> CitizenshipStatusBuilder: ...
    def name(self, name: list[I18n]) -> CitizenshipStatusBuilder: ...
    def citizenship_status(self, citizenship_status: list[I18n]) -> CitizenshipStatusBuilder: ...
    def view_order(self, view_order: int) -> CitizenshipStatusBuilder: ...
    def build(self) -> CitizenshipStatus: ...
