from lark_oapi.core.construct import init as init

class CompletePreHireRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CompletePreHireRequestBodyBuilder: ...

class CompletePreHireRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> CompletePreHireRequestBody: ...
