from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CompletePreHireRequest(BaseRequest):
    pre_hire_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CompletePreHireRequestBuilder: ...

class CompletePreHireRequestBuilder:
    def __init__(self) -> None: ...
    def pre_hire_id(self, pre_hire_id: str) -> CompletePreHireRequestBuilder: ...
    def build(self) -> CompletePreHireRequest: ...
