from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class CompanyIdAndName:
    company_id: str | None
    company_name: list[I18n] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CompanyIdAndNameBuilder: ...

class CompanyIdAndNameBuilder:
    def __init__(self) -> None: ...
    def company_id(self, company_id: str) -> CompanyIdAndNameBuilder: ...
    def company_name(self, company_name: list[I18n]) -> CompanyIdAndNameBuilder: ...
    def build(self) -> CompanyIdAndName: ...
