from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class CompanyVersionData:
    company_id: str | None
    company_version_id: str | None
    company_names: list[I18n] | None
    parent_company_id: str | None
    effective_date: str | None
    expiration_date: str | None
    active: bool | None
    descriptions: list[I18n] | None
    code: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CompanyVersionDataBuilder: ...

class CompanyVersionDataBuilder:
    def __init__(self) -> None: ...
    def company_id(self, company_id: str) -> CompanyVersionDataBuilder: ...
    def company_version_id(self, company_version_id: str) -> CompanyVersionDataBuilder: ...
    def company_names(self, company_names: list[I18n]) -> CompanyVersionDataBuilder: ...
    def parent_company_id(self, parent_company_id: str) -> CompanyVersionDataBuilder: ...
    def effective_date(self, effective_date: str) -> CompanyVersionDataBuilder: ...
    def expiration_date(self, expiration_date: str) -> CompanyVersionDataBuilder: ...
    def active(self, active: bool) -> CompanyVersionDataBuilder: ...
    def descriptions(self, descriptions: list[I18n]) -> CompanyVersionDataBuilder: ...
    def code(self, code: str) -> CompanyVersionDataBuilder: ...
    def build(self) -> CompanyVersionData: ...
