from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class CostCenter:
    cost_center_id: str | None
    cost_center_version_id: str | None
    name: list[I18n] | None
    code: str | None
    parent_cost_center_id: str | None
    managers: list[str] | None
    description: list[I18n] | None
    effective_time: str | None
    expiration_time: str | None
    active: bool | None
    operation_reason: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CostCenterBuilder: ...

class CostCenterBuilder:
    def __init__(self) -> None: ...
    def cost_center_id(self, cost_center_id: str) -> CostCenterBuilder: ...
    def cost_center_version_id(self, cost_center_version_id: str) -> CostCenterBuilder: ...
    def name(self, name: list[I18n]) -> CostCenterBuilder: ...
    def code(self, code: str) -> CostCenterBuilder: ...
    def parent_cost_center_id(self, parent_cost_center_id: str) -> CostCenterBuilder: ...
    def managers(self, managers: list[str]) -> CostCenterBuilder: ...
    def description(self, description: list[I18n]) -> CostCenterBuilder: ...
    def effective_time(self, effective_time: str) -> CostCenterBuilder: ...
    def expiration_time(self, expiration_time: str) -> CostCenterBuilder: ...
    def active(self, active: bool) -> CostCenterBuilder: ...
    def operation_reason(self, operation_reason: str) -> CostCenterBuilder: ...
    def build(self) -> CostCenter: ...
