from .create_version_default_cost_center_request_body import CreateVersionDefaultCostCenterRequestBody as CreateVersionDefaultCostCenterRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateVersionDefaultCostCenterRequest(BaseRequest):
    client_token: str | None
    user_id_type: str | None
    request_body: CreateVersionDefaultCostCenterRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateVersionDefaultCostCenterRequestBuilder: ...

class CreateVersionDefaultCostCenterRequestBuilder:
    def __init__(self) -> None: ...
    def client_token(self, client_token: str) -> CreateVersionDefaultCostCenterRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> CreateVersionDefaultCostCenterRequestBuilder: ...
    def request_body(self, request_body: CreateVersionDefaultCostCenterRequestBody) -> CreateVersionDefaultCostCenterRequestBuilder: ...
    def build(self) -> CreateVersionDefaultCostCenterRequest: ...
