from lark_oapi.core.construct import init as init

class CreateEmployeeResponseBody:
    employment_id: str | None
    contract_id: str | None
    job_data_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateEmployeeResponseBodyBuilder: ...

class CreateEmployeeResponseBodyBuilder:
    def __init__(self) -> None: ...
    def employment_id(self, employment_id: str) -> CreateEmployeeResponseBodyBuilder: ...
    def contract_id(self, contract_id: str) -> CreateEmployeeResponseBodyBuilder: ...
    def job_data_id(self, job_data_id: str) -> CreateEmployeeResponseBodyBuilder: ...
    def build(self) -> CreateEmployeeResponseBody: ...
