from .create_employee_request_body import CreateEmployeeRequestBody as CreateEmployeeRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateEmployeeRequest(BaseRequest):
    client_token: str | None
    rehire: bool | None
    rehire_employment_id: str | None
    force_submit: bool | None
    ignore_working_hours_type_rule: bool | None
    request_body: CreateEmployeeRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateEmployeeRequestBuilder: ...

class CreateEmployeeRequestBuilder:
    def __init__(self) -> None: ...
    def client_token(self, client_token: str) -> CreateEmployeeRequestBuilder: ...
    def rehire(self, rehire: bool) -> CreateEmployeeRequestBuilder: ...
    def rehire_employment_id(self, rehire_employment_id: str) -> CreateEmployeeRequestBuilder: ...
    def force_submit(self, force_submit: bool) -> CreateEmployeeRequestBuilder: ...
    def ignore_working_hours_type_rule(self, ignore_working_hours_type_rule: bool) -> CreateEmployeeRequestBuilder: ...
    def request_body(self, request_body: CreateEmployeeRequestBody) -> CreateEmployeeRequestBuilder: ...
    def build(self) -> CreateEmployeeRequest: ...
