from .assessment_for_create import AssessmentForCreate as AssessmentForCreate
from lark_oapi.core.construct import init as init

class CreateProbationAssessmentRequestBody:
    employment_id: str | None
    assessments: list[AssessmentForCreate] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateProbationAssessmentRequestBodyBuilder: ...

class CreateProbationAssessmentRequestBodyBuilder:
    def __init__(self) -> None: ...
    def employment_id(self, employment_id: str) -> CreateProbationAssessmentRequestBodyBuilder: ...
    def assessments(self, assessments: list[AssessmentForCreate]) -> CreateProbationAssessmentRequestBodyBuilder: ...
    def build(self) -> CreateProbationAssessmentRequestBody: ...
