from .cost_center_version import CostCenterVersion as CostCenterVersion
from lark_oapi.core.construct import init as init

class CreateCostCenterVersionResponseBody:
    version: CostCenterVersion | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateCostCenterVersionResponseBodyBuilder: ...

class CreateCostCenterVersionResponseBodyBuilder:
    def __init__(self) -> None: ...
    def version(self, version: CostCenterVersion) -> CreateCostCenterVersionResponseBodyBuilder: ...
    def build(self) -> CreateCostCenterVersionResponseBody: ...
