from lark_oapi.core.construct import init as init

class CreateEmpCustomOrg:
    id: str | None
    rate: float | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateEmpCustomOrgBuilder: ...

class CreateEmpCustomOrgBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> CreateEmpCustomOrgBuilder: ...
    def rate(self, rate: float) -> CreateEmpCustomOrgBuilder: ...
    def build(self) -> CreateEmpCustomOrg: ...
