from .custom_org_create import CustomOrgCreate as CustomOrgCreate
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateCustomOrgRequest(BaseRequest):
    client_token: str | None
    user_id_type: str | None
    request_body: CustomOrgCreate | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateCustomOrgRequestBuilder: ...

class CreateCustomOrgRequestBuilder:
    def __init__(self) -> None: ...
    def client_token(self, client_token: str) -> CreateCustomOrgRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> CreateCustomOrgRequestBuilder: ...
    def request_body(self, request_body: CustomOrgCreate) -> CreateCustomOrgRequestBuilder: ...
    def build(self) -> CreateCustomOrgRequest: ...
