from .employees_international_assignment_req import EmployeesInternationalAssignmentReq as EmployeesInternationalAssignmentReq
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateEmployeesInternationalAssignmentRequest(BaseRequest):
    client_token: str | None
    user_id_type: str | None
    department_id_type: str | None
    request_body: EmployeesInternationalAssignmentReq | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateEmployeesInternationalAssignmentRequestBuilder: ...

class CreateEmployeesInternationalAssignmentRequestBuilder:
    def __init__(self) -> None: ...
    def client_token(self, client_token: str) -> CreateEmployeesInternationalAssignmentRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> CreateEmployeesInternationalAssignmentRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> CreateEmployeesInternationalAssignmentRequestBuilder: ...
    def request_body(self, request_body: EmployeesInternationalAssignmentReq) -> CreateEmployeesInternationalAssignmentRequestBuilder: ...
    def build(self) -> CreateEmployeesInternationalAssignmentRequest: ...
