from .employment_cost_allocation import EmploymentCostAllocation as EmploymentCostAllocation
from lark_oapi.core.construct import init as init

class CreateVersionCostAllocationRequestBody:
    employment_id: str | None
    cost_allocation: EmploymentCostAllocation | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateVersionCostAllocationRequestBodyBuilder: ...

class CreateVersionCostAllocationRequestBodyBuilder:
    def __init__(self) -> None: ...
    def employment_id(self, employment_id: str) -> CreateVersionCostAllocationRequestBodyBuilder: ...
    def cost_allocation(self, cost_allocation: EmploymentCostAllocation) -> CreateVersionCostAllocationRequestBodyBuilder: ...
    def build(self) -> CreateVersionCostAllocationRequestBody: ...
