from .job_data_cost_center import JobDataCostCenter as JobDataCostCenter
from .tranfer_employment_info import TranferEmploymentInfo as TranferEmploymentInfo
from lark_oapi.core.construct import init as init

class CreateTransferInfo:
    remark: str | None
    offer_info: str | None
    target_dotted_manager_clean: bool | None
    probation_exist: bool | None
    target_department: str | None
    target_work_location: str | None
    target_direct_manager: str | None
    target_dotted_manager: str | None
    target_job: str | None
    target_job_family: str | None
    target_job_level: str | None
    target_workforce_type: str | None
    target_employee_subtype: str | None
    target_company: str | None
    target_contract_number: str | None
    target_contract_type: str | None
    target_duration_type: str | None
    target_signing_type: str | None
    target_contract_start_date: str | None
    target_contract_end_date: str | None
    target_working_hours_type: str | None
    target_working_calendar: str | None
    target_probation_end_date: str | None
    target_weekly_working_hours: str | None
    target_work_shift: str | None
    target_cost_center_rates: list[JobDataCostCenter] | None
    target_employment_change: TranferEmploymentInfo | None
    target_job_grade: str | None
    target_compensation_type: str | None
    target_service_company: str | None
    target_position: str | None
    target_social_security_city: str | None
    is_transfer_with_workforce: bool | None
    target_pathway: str | None
    target_allocation_effective_time: str | None
    target_allocation_expiration_time: str | None
    target_default_cost_center: str | None
    target_is_default_cost_center_inherited: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateTransferInfoBuilder: ...

class CreateTransferInfoBuilder:
    def __init__(self) -> None: ...
    def remark(self, remark: str) -> CreateTransferInfoBuilder: ...
    def offer_info(self, offer_info: str) -> CreateTransferInfoBuilder: ...
    def target_dotted_manager_clean(self, target_dotted_manager_clean: bool) -> CreateTransferInfoBuilder: ...
    def probation_exist(self, probation_exist: bool) -> CreateTransferInfoBuilder: ...
    def target_department(self, target_department: str) -> CreateTransferInfoBuilder: ...
    def target_work_location(self, target_work_location: str) -> CreateTransferInfoBuilder: ...
    def target_direct_manager(self, target_direct_manager: str) -> CreateTransferInfoBuilder: ...
    def target_dotted_manager(self, target_dotted_manager: str) -> CreateTransferInfoBuilder: ...
    def target_job(self, target_job: str) -> CreateTransferInfoBuilder: ...
    def target_job_family(self, target_job_family: str) -> CreateTransferInfoBuilder: ...
    def target_job_level(self, target_job_level: str) -> CreateTransferInfoBuilder: ...
    def target_workforce_type(self, target_workforce_type: str) -> CreateTransferInfoBuilder: ...
    def target_employee_subtype(self, target_employee_subtype: str) -> CreateTransferInfoBuilder: ...
    def target_company(self, target_company: str) -> CreateTransferInfoBuilder: ...
    def target_contract_number(self, target_contract_number: str) -> CreateTransferInfoBuilder: ...
    def target_contract_type(self, target_contract_type: str) -> CreateTransferInfoBuilder: ...
    def target_duration_type(self, target_duration_type: str) -> CreateTransferInfoBuilder: ...
    def target_signing_type(self, target_signing_type: str) -> CreateTransferInfoBuilder: ...
    def target_contract_start_date(self, target_contract_start_date: str) -> CreateTransferInfoBuilder: ...
    def target_contract_end_date(self, target_contract_end_date: str) -> CreateTransferInfoBuilder: ...
    def target_working_hours_type(self, target_working_hours_type: str) -> CreateTransferInfoBuilder: ...
    def target_working_calendar(self, target_working_calendar: str) -> CreateTransferInfoBuilder: ...
    def target_probation_end_date(self, target_probation_end_date: str) -> CreateTransferInfoBuilder: ...
    def target_weekly_working_hours(self, target_weekly_working_hours: str) -> CreateTransferInfoBuilder: ...
    def target_work_shift(self, target_work_shift: str) -> CreateTransferInfoBuilder: ...
    def target_cost_center_rates(self, target_cost_center_rates: list[JobDataCostCenter]) -> CreateTransferInfoBuilder: ...
    def target_employment_change(self, target_employment_change: TranferEmploymentInfo) -> CreateTransferInfoBuilder: ...
    def target_job_grade(self, target_job_grade: str) -> CreateTransferInfoBuilder: ...
    def target_compensation_type(self, target_compensation_type: str) -> CreateTransferInfoBuilder: ...
    def target_service_company(self, target_service_company: str) -> CreateTransferInfoBuilder: ...
    def target_position(self, target_position: str) -> CreateTransferInfoBuilder: ...
    def target_social_security_city(self, target_social_security_city: str) -> CreateTransferInfoBuilder: ...
    def is_transfer_with_workforce(self, is_transfer_with_workforce: bool) -> CreateTransferInfoBuilder: ...
    def target_pathway(self, target_pathway: str) -> CreateTransferInfoBuilder: ...
    def target_allocation_effective_time(self, target_allocation_effective_time: str) -> CreateTransferInfoBuilder: ...
    def target_allocation_expiration_time(self, target_allocation_expiration_time: str) -> CreateTransferInfoBuilder: ...
    def target_default_cost_center(self, target_default_cost_center: str) -> CreateTransferInfoBuilder: ...
    def target_is_default_cost_center_inherited(self, target_is_default_cost_center_inherited: bool) -> CreateTransferInfoBuilder: ...
    def build(self) -> CreateTransferInfo: ...
