from .prehire_create import PrehireCreate as PrehireCreate
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreatePreHireRequest(BaseRequest):
    request_body: PrehireCreate | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreatePreHireRequestBuilder: ...

class CreatePreHireRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: PrehireCreate) -> CreatePreHireRequestBuilder: ...
    def build(self) -> CreatePreHireRequest: ...
