from .employment_default_cost_center import EmploymentDefaultCostCenter as EmploymentDefaultCostCenter
from lark_oapi.core.construct import init as init

class CreateVersionDefaultCostCenterRequestBody:
    employment_id: str | None
    default_cost_center: EmploymentDefaultCostCenter | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateVersionDefaultCostCenterRequestBodyBuilder: ...

class CreateVersionDefaultCostCenterRequestBodyBuilder:
    def __init__(self) -> None: ...
    def employment_id(self, employment_id: str) -> CreateVersionDefaultCostCenterRequestBodyBuilder: ...
    def default_cost_center(self, default_cost_center: EmploymentDefaultCostCenter) -> CreateVersionDefaultCostCenterRequestBodyBuilder: ...
    def build(self) -> CreateVersionDefaultCostCenterRequestBody: ...
