from .create_probation_assessment_request_body import CreateProbationAssessmentRequestBody as CreateProbationAssessmentRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateProbationAssessmentRequest(BaseRequest):
    client_token: str | None
    user_id_type: str | None
    request_body: CreateProbationAssessmentRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateProbationAssessmentRequestBuilder: ...

class CreateProbationAssessmentRequestBuilder:
    def __init__(self) -> None: ...
    def client_token(self, client_token: str) -> CreateProbationAssessmentRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> CreateProbationAssessmentRequestBuilder: ...
    def request_body(self, request_body: CreateProbationAssessmentRequestBody) -> CreateProbationAssessmentRequestBuilder: ...
    def build(self) -> CreateProbationAssessmentRequest: ...
