from .custom_field_data import CustomFieldData as CustomFieldData
from .i18n import I18n as I18n
from .match_rules import MatchRules as MatchRules
from .org_role_update import OrgRoleUpdate as OrgRoleUpdate
from lark_oapi.core.construct import init as init

class CustomOrgCreate:
    object_api_name: str | None
    names: list[I18n] | None
    code: str | None
    parent_id: str | None
    manager_ids: list[str] | None
    description: list[I18n] | None
    effective_time: str | None
    org_roles: list[OrgRoleUpdate] | None
    match_rule_groups: list[MatchRules] | None
    custom_fields: list[CustomFieldData] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CustomOrgCreateBuilder: ...

class CustomOrgCreateBuilder:
    def __init__(self) -> None: ...
    def object_api_name(self, object_api_name: str) -> CustomOrgCreateBuilder: ...
    def names(self, names: list[I18n]) -> CustomOrgCreateBuilder: ...
    def code(self, code: str) -> CustomOrgCreateBuilder: ...
    def parent_id(self, parent_id: str) -> CustomOrgCreateBuilder: ...
    def manager_ids(self, manager_ids: list[str]) -> CustomOrgCreateBuilder: ...
    def description(self, description: list[I18n]) -> CustomOrgCreateBuilder: ...
    def effective_time(self, effective_time: str) -> CustomOrgCreateBuilder: ...
    def org_roles(self, org_roles: list[OrgRoleUpdate]) -> CustomOrgCreateBuilder: ...
    def match_rule_groups(self, match_rule_groups: list[MatchRules]) -> CustomOrgCreateBuilder: ...
    def custom_fields(self, custom_fields: list[CustomFieldData]) -> CustomOrgCreateBuilder: ...
    def build(self) -> CustomOrgCreate: ...
