from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteLocationAddressRequest(BaseRequest):
    location_id: str | None
    address_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteLocationAddressRequestBuilder: ...

class DeleteLocationAddressRequestBuilder:
    def __init__(self) -> None: ...
    def location_id(self, location_id: str) -> DeleteLocationAddressRequestBuilder: ...
    def address_id(self, address_id: str) -> DeleteLocationAddressRequestBuilder: ...
    def build(self) -> DeleteLocationAddressRequest: ...
