from lark_oapi.core.construct import init as init

class DeleteJobGradeRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteJobGradeRequestBodyBuilder: ...

class DeleteJobGradeRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteJobGradeRequestBody: ...
