from lark_oapi.core.construct import init as init

class DeleteEmployeesAdditionalJobResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteEmployeesAdditionalJobResponseBodyBuilder: ...

class DeleteEmployeesAdditionalJobResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteEmployeesAdditionalJobResponseBody: ...
