from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteEmployeesInternationalAssignmentRequest(BaseRequest):
    international_assignment_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteEmployeesInternationalAssignmentRequestBuilder: ...

class DeleteEmployeesInternationalAssignmentRequestBuilder:
    def __init__(self) -> None: ...
    def international_assignment_id(self, international_assignment_id: str) -> DeleteEmployeesInternationalAssignmentRequestBuilder: ...
    def build(self) -> DeleteEmployeesInternationalAssignmentRequest: ...
