from .delete_org_custom_org_request_body import DeleteOrgCustomOrgRequestBody as DeleteOrgCustomOrgRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteOrgCustomOrgRequest(BaseRequest):
    request_body: DeleteOrgCustomOrgRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteOrgCustomOrgRequestBuilder: ...

class DeleteOrgCustomOrgRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: DeleteOrgCustomOrgRequestBody) -> DeleteOrgCustomOrgRequestBuilder: ...
    def build(self) -> DeleteOrgCustomOrgRequest: ...
