from lark_oapi.core.construct import init as init

class DeleteCostCenterResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteCostCenterResponseBodyBuilder: ...

class DeleteCostCenterResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteCostCenterResponseBody: ...
