from lark_oapi.core.construct import init as init

class DeleteCostCenterVersionRequestBody:
    operation_reason: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteCostCenterVersionRequestBodyBuilder: ...

class DeleteCostCenterVersionRequestBodyBuilder:
    def __init__(self) -> None: ...
    def operation_reason(self, operation_reason: str) -> DeleteCostCenterVersionRequestBodyBuilder: ...
    def build(self) -> DeleteCostCenterVersionRequestBody: ...
