from lark_oapi.core.construct import init as init

class DeleteCostCenterRequestBody:
    operation_reason: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteCostCenterRequestBodyBuilder: ...

class DeleteCostCenterRequestBodyBuilder:
    def __init__(self) -> None: ...
    def operation_reason(self, operation_reason: str) -> DeleteCostCenterRequestBodyBuilder: ...
    def build(self) -> DeleteCostCenterRequestBody: ...
