from .delete_cost_center_version_request_body import DeleteCostCenterVersionRequestBody as DeleteCostCenterVersionRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteCostCenterVersionRequest(BaseRequest):
    cost_center_id: str | None
    version_id: str | None
    request_body: DeleteCostCenterVersionRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteCostCenterVersionRequestBuilder: ...

class DeleteCostCenterVersionRequestBuilder:
    def __init__(self) -> None: ...
    def cost_center_id(self, cost_center_id: str) -> DeleteCostCenterVersionRequestBuilder: ...
    def version_id(self, version_id: str) -> DeleteCostCenterVersionRequestBuilder: ...
    def request_body(self, request_body: DeleteCostCenterVersionRequestBody) -> DeleteCostCenterVersionRequestBuilder: ...
    def build(self) -> DeleteCostCenterVersionRequest: ...
