from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteProbationAssessmentRequest(BaseRequest):
    assessment_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteProbationAssessmentRequestBuilder: ...

class DeleteProbationAssessmentRequestBuilder:
    def __init__(self) -> None: ...
    def assessment_id(self, assessment_id: str) -> DeleteProbationAssessmentRequestBuilder: ...
    def build(self) -> DeleteProbationAssessmentRequest: ...
