from lark_oapi.core.construct import init as init

class DeleteCostCenterVersionResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteCostCenterVersionResponseBodyBuilder: ...

class DeleteCostCenterVersionResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteCostCenterVersionResponseBody: ...
