from lark_oapi.core.construct import init as init

class DeleteEmployeesAdditionalJobRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteEmployeesAdditionalJobRequestBodyBuilder: ...

class DeleteEmployeesAdditionalJobRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteEmployeesAdditionalJobRequestBody: ...
