from .reorganization_info import ReorganizationInfo as ReorganizationInfo
from lark_oapi.core.construct import init as init

class DepartmentAdjustRecord:
    record_id: str | None
    department_id: str | None
    draft_department_id: str | None
    department_change_type: str | None
    is_conflict: bool | None
    change_reasons: list[str] | None
    reorganization_info: ReorganizationInfo | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DepartmentAdjustRecordBuilder: ...

class DepartmentAdjustRecordBuilder:
    def __init__(self) -> None: ...
    def record_id(self, record_id: str) -> DepartmentAdjustRecordBuilder: ...
    def department_id(self, department_id: str) -> DepartmentAdjustRecordBuilder: ...
    def draft_department_id(self, draft_department_id: str) -> DepartmentAdjustRecordBuilder: ...
    def department_change_type(self, department_change_type: str) -> DepartmentAdjustRecordBuilder: ...
    def is_conflict(self, is_conflict: bool) -> DepartmentAdjustRecordBuilder: ...
    def change_reasons(self, change_reasons: list[str]) -> DepartmentAdjustRecordBuilder: ...
    def reorganization_info(self, reorganization_info: ReorganizationInfo) -> DepartmentAdjustRecordBuilder: ...
    def build(self) -> DepartmentAdjustRecord: ...
