from .enum import Enum as Enum
from .hiberarchy_common import HiberarchyCommon as HiberarchyCommon
from .object_field_data import ObjectFieldData as ObjectFieldData
from lark_oapi.core.construct import init as init

class DepartmentForPatch:
    id: str | None
    sub_type: Enum | None
    manager: str | None
    is_confidential: bool | None
    hiberarchy_common: HiberarchyCommon | None
    effective_time: str | None
    custom_fields: list[ObjectFieldData] | None
    cost_center_id: str | None
    staffing_model: Enum | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DepartmentForPatchBuilder: ...

class DepartmentForPatchBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> DepartmentForPatchBuilder: ...
    def sub_type(self, sub_type: Enum) -> DepartmentForPatchBuilder: ...
    def manager(self, manager: str) -> DepartmentForPatchBuilder: ...
    def is_confidential(self, is_confidential: bool) -> DepartmentForPatchBuilder: ...
    def hiberarchy_common(self, hiberarchy_common: HiberarchyCommon) -> DepartmentForPatchBuilder: ...
    def effective_time(self, effective_time: str) -> DepartmentForPatchBuilder: ...
    def custom_fields(self, custom_fields: list[ObjectFieldData]) -> DepartmentForPatchBuilder: ...
    def cost_center_id(self, cost_center_id: str) -> DepartmentForPatchBuilder: ...
    def staffing_model(self, staffing_model: Enum) -> DepartmentForPatchBuilder: ...
    def build(self) -> DepartmentForPatch: ...
