from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class District:
    district_id: str | None
    name: list[I18n] | None
    city_id: str | None
    subregion_code: str | None
    status: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DistrictBuilder: ...

class DistrictBuilder:
    def __init__(self) -> None: ...
    def district_id(self, district_id: str) -> DistrictBuilder: ...
    def name(self, name: list[I18n]) -> DistrictBuilder: ...
    def city_id(self, city_id: str) -> DistrictBuilder: ...
    def subregion_code(self, subregion_code: str) -> DistrictBuilder: ...
    def status(self, status: int) -> DistrictBuilder: ...
    def build(self) -> District: ...
