from .edit_offboarding_request_body import EditOffboardingRequestBody as EditOffboardingRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class EditOffboardingRequest(BaseRequest):
    user_id_type: str | None
    request_body: EditOffboardingRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> EditOffboardingRequestBuilder: ...

class EditOffboardingRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> EditOffboardingRequestBuilder: ...
    def request_body(self, request_body: EditOffboardingRequestBody) -> EditOffboardingRequestBuilder: ...
    def build(self) -> EditOffboardingRequest: ...
