from .object_field_data import ObjectFieldData as ObjectFieldData
from lark_oapi.core.construct import init as init

class EditOffboardingRequestBody:
    offboarding_id: str | None
    operator_id: str | None
    update_data: list[ObjectFieldData] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EditOffboardingRequestBodyBuilder: ...

class EditOffboardingRequestBodyBuilder:
    def __init__(self) -> None: ...
    def offboarding_id(self, offboarding_id: str) -> EditOffboardingRequestBodyBuilder: ...
    def operator_id(self, operator_id: str) -> EditOffboardingRequestBodyBuilder: ...
    def update_data(self, update_data: list[ObjectFieldData]) -> EditOffboardingRequestBodyBuilder: ...
    def build(self) -> EditOffboardingRequestBody: ...
