from .object_field_data import ObjectFieldData as ObjectFieldData
from lark_oapi.core.construct import init as init

class EducationInfo:
    school_name: str | None
    education: str | None
    start_time: str | None
    end_time: str | None
    field_of_study: str | None
    custom_fields: list[ObjectFieldData] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EducationInfoBuilder: ...

class EducationInfoBuilder:
    def __init__(self) -> None: ...
    def school_name(self, school_name: str) -> EducationInfoBuilder: ...
    def education(self, education: str) -> EducationInfoBuilder: ...
    def start_time(self, start_time: str) -> EducationInfoBuilder: ...
    def end_time(self, end_time: str) -> EducationInfoBuilder: ...
    def field_of_study(self, field_of_study: str) -> EducationInfoBuilder: ...
    def custom_fields(self, custom_fields: list[ObjectFieldData]) -> EducationInfoBuilder: ...
    def build(self) -> EducationInfo: ...
