from .address_for_update import AddressForUpdate as AddressForUpdate
from .email_for_update import EmailForUpdate as EmailForUpdate
from .object_field_data import ObjectFieldData as ObjectFieldData
from .phone_for_update import PhoneForUpdate as PhoneForUpdate
from lark_oapi.core.construct import init as init

class EmergencyContactForUpdate:
    legal_name: str | None
    relationship: str | None
    phones: list[PhoneForUpdate] | None
    address: AddressForUpdate | None
    email: EmailForUpdate | None
    is_primary: bool | None
    custom_fields: list[ObjectFieldData] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EmergencyContactForUpdateBuilder: ...

class EmergencyContactForUpdateBuilder:
    def __init__(self) -> None: ...
    def legal_name(self, legal_name: str) -> EmergencyContactForUpdateBuilder: ...
    def relationship(self, relationship: str) -> EmergencyContactForUpdateBuilder: ...
    def phones(self, phones: list[PhoneForUpdate]) -> EmergencyContactForUpdateBuilder: ...
    def address(self, address: AddressForUpdate) -> EmergencyContactForUpdateBuilder: ...
    def email(self, email: EmailForUpdate) -> EmergencyContactForUpdateBuilder: ...
    def is_primary(self, is_primary: bool) -> EmergencyContactForUpdateBuilder: ...
    def custom_fields(self, custom_fields: list[ObjectFieldData]) -> EmergencyContactForUpdateBuilder: ...
    def build(self) -> EmergencyContactForUpdate: ...
