from .international_assignment_v2 import InternationalAssignmentV2 as InternationalAssignmentV2
from lark_oapi.core.construct import init as init

class EmployeeInternationalAssignment:
    employment_id: str | None
    international_assignments: list[InternationalAssignmentV2] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EmployeeInternationalAssignmentBuilder: ...

class EmployeeInternationalAssignmentBuilder:
    def __init__(self) -> None: ...
    def employment_id(self, employment_id: str) -> EmployeeInternationalAssignmentBuilder: ...
    def international_assignments(self, international_assignments: list[InternationalAssignmentV2]) -> EmployeeInternationalAssignmentBuilder: ...
    def build(self) -> EmployeeInternationalAssignment: ...
