from lark_oapi.core.construct import init as init

class EmployeesAdditionalJobBatchReqDate:
    start: str | None
    end: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EmployeesAdditionalJobBatchReqDateBuilder: ...

class EmployeesAdditionalJobBatchReqDateBuilder:
    def __init__(self) -> None: ...
    def start(self, start: str) -> EmployeesAdditionalJobBatchReqDateBuilder: ...
    def end(self, end: str) -> EmployeesAdditionalJobBatchReqDateBuilder: ...
    def build(self) -> EmployeesAdditionalJobBatchReqDate: ...
