from .enum import Enum as Enum
from .object_field_data import ObjectFieldData as ObjectFieldData
from lark_oapi.core.construct import init as init

class EmployeesInternationalAssignment:
    work_location_id: str | None
    service_company: str | None
    work_shift: Enum | None
    working_hours_type_id: str | None
    employee_type_id: str | None
    weekly_working_hours_v2: float | None
    department_id: str | None
    job_id: str | None
    job_family_id: str | None
    job_level_id: str | None
    job_grade_id: str | None
    compensation_type: Enum | None
    direct_manager_id: str | None
    dotted_line_manager_id: str | None
    work_calendar_id: str | None
    position_id: str | None
    employment_id: str | None
    custom_fields: list[ObjectFieldData] | None
    international_assignment_reason: str | None
    description: str | None
    international_assignment_expected_end_date: str | None
    international_assignment_status: Enum | None
    international_assignment_type: Enum | None
    effective_time: str | None
    expiration_time: str | None
    id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EmployeesInternationalAssignmentBuilder: ...

class EmployeesInternationalAssignmentBuilder:
    def __init__(self) -> None: ...
    def work_location_id(self, work_location_id: str) -> EmployeesInternationalAssignmentBuilder: ...
    def service_company(self, service_company: str) -> EmployeesInternationalAssignmentBuilder: ...
    def work_shift(self, work_shift: Enum) -> EmployeesInternationalAssignmentBuilder: ...
    def working_hours_type_id(self, working_hours_type_id: str) -> EmployeesInternationalAssignmentBuilder: ...
    def employee_type_id(self, employee_type_id: str) -> EmployeesInternationalAssignmentBuilder: ...
    def weekly_working_hours_v2(self, weekly_working_hours_v2: float) -> EmployeesInternationalAssignmentBuilder: ...
    def department_id(self, department_id: str) -> EmployeesInternationalAssignmentBuilder: ...
    def job_id(self, job_id: str) -> EmployeesInternationalAssignmentBuilder: ...
    def job_family_id(self, job_family_id: str) -> EmployeesInternationalAssignmentBuilder: ...
    def job_level_id(self, job_level_id: str) -> EmployeesInternationalAssignmentBuilder: ...
    def job_grade_id(self, job_grade_id: str) -> EmployeesInternationalAssignmentBuilder: ...
    def compensation_type(self, compensation_type: Enum) -> EmployeesInternationalAssignmentBuilder: ...
    def direct_manager_id(self, direct_manager_id: str) -> EmployeesInternationalAssignmentBuilder: ...
    def dotted_line_manager_id(self, dotted_line_manager_id: str) -> EmployeesInternationalAssignmentBuilder: ...
    def work_calendar_id(self, work_calendar_id: str) -> EmployeesInternationalAssignmentBuilder: ...
    def position_id(self, position_id: str) -> EmployeesInternationalAssignmentBuilder: ...
    def employment_id(self, employment_id: str) -> EmployeesInternationalAssignmentBuilder: ...
    def custom_fields(self, custom_fields: list[ObjectFieldData]) -> EmployeesInternationalAssignmentBuilder: ...
    def international_assignment_reason(self, international_assignment_reason: str) -> EmployeesInternationalAssignmentBuilder: ...
    def description(self, description: str) -> EmployeesInternationalAssignmentBuilder: ...
    def international_assignment_expected_end_date(self, international_assignment_expected_end_date: str) -> EmployeesInternationalAssignmentBuilder: ...
    def international_assignment_status(self, international_assignment_status: Enum) -> EmployeesInternationalAssignmentBuilder: ...
    def international_assignment_type(self, international_assignment_type: Enum) -> EmployeesInternationalAssignmentBuilder: ...
    def effective_time(self, effective_time: str) -> EmployeesInternationalAssignmentBuilder: ...
    def expiration_time(self, expiration_time: str) -> EmployeesInternationalAssignmentBuilder: ...
    def id(self, id: str) -> EmployeesInternationalAssignmentBuilder: ...
    def build(self) -> EmployeesInternationalAssignment: ...
