from .custom_field_data import CustomFieldData as CustomFieldData
from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class EmployeeJobFamily:
    id: str | None
    name: list[I18n] | None
    active: bool | None
    parent_id: str | None
    effective_time: str | None
    expiration_time: str | None
    code: str | None
    custom_fields: list[CustomFieldData] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EmployeeJobFamilyBuilder: ...

class EmployeeJobFamilyBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> EmployeeJobFamilyBuilder: ...
    def name(self, name: list[I18n]) -> EmployeeJobFamilyBuilder: ...
    def active(self, active: bool) -> EmployeeJobFamilyBuilder: ...
    def parent_id(self, parent_id: str) -> EmployeeJobFamilyBuilder: ...
    def effective_time(self, effective_time: str) -> EmployeeJobFamilyBuilder: ...
    def expiration_time(self, expiration_time: str) -> EmployeeJobFamilyBuilder: ...
    def code(self, code: str) -> EmployeeJobFamilyBuilder: ...
    def custom_fields(self, custom_fields: list[CustomFieldData]) -> EmployeeJobFamilyBuilder: ...
    def build(self) -> EmployeeJobFamily: ...
