from .custom_field_data import CustomFieldData as CustomFieldData
from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class EmployeePathway:
    id: str | None
    code: str | None
    name: list[I18n] | None
    description: list[I18n] | None
    active: bool | None
    custom_fields: list[CustomFieldData] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EmployeePathwayBuilder: ...

class EmployeePathwayBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> EmployeePathwayBuilder: ...
    def code(self, code: str) -> EmployeePathwayBuilder: ...
    def name(self, name: list[I18n]) -> EmployeePathwayBuilder: ...
    def description(self, description: list[I18n]) -> EmployeePathwayBuilder: ...
    def active(self, active: bool) -> EmployeePathwayBuilder: ...
    def custom_fields(self, custom_fields: list[CustomFieldData]) -> EmployeePathwayBuilder: ...
    def build(self) -> EmployeePathway: ...
