from .job_data_cost_center import JobDataCostCenter as JobDataCostCenter
from .job_data_id import JobDataId as JobDataId
from lark_oapi.core.construct import init as init

class EmploymentCostAllocation:
    wk_id: str | None
    effective_time: str | None
    expiration_time: str | None
    job_data_cost_center_id: list[JobDataCostCenter] | None
    job_data_id: JobDataId | None
    reason: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EmploymentCostAllocationBuilder: ...

class EmploymentCostAllocationBuilder:
    def __init__(self) -> None: ...
    def wk_id(self, wk_id: str) -> EmploymentCostAllocationBuilder: ...
    def effective_time(self, effective_time: str) -> EmploymentCostAllocationBuilder: ...
    def expiration_time(self, expiration_time: str) -> EmploymentCostAllocationBuilder: ...
    def job_data_cost_center_id(self, job_data_cost_center_id: list[JobDataCostCenter]) -> EmploymentCostAllocationBuilder: ...
    def job_data_id(self, job_data_id: JobDataId) -> EmploymentCostAllocationBuilder: ...
    def reason(self, reason: str) -> EmploymentCostAllocationBuilder: ...
    def build(self) -> EmploymentCostAllocation: ...
