from .job_data import JobData as JobData
from lark_oapi.core.construct import init as init

class EmployeeJobData:
    employment_id: str | None
    job_datas: list[JobData] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EmployeeJobDataBuilder: ...

class EmployeeJobDataBuilder:
    def __init__(self) -> None: ...
    def employment_id(self, employment_id: str) -> EmployeeJobDataBuilder: ...
    def job_datas(self, job_datas: list[JobData]) -> EmployeeJobDataBuilder: ...
    def build(self) -> EmployeeJobData: ...
