from lark_oapi.core.construct import init as init

class EmployeeDomainEventData:
    id: str | None
    entity: str | None
    agg_entity: str | None
    agg_entity_id: str | None
    opt_type: int | None
    fields: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EmployeeDomainEventDataBuilder: ...

class EmployeeDomainEventDataBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> EmployeeDomainEventDataBuilder: ...
    def entity(self, entity: str) -> EmployeeDomainEventDataBuilder: ...
    def agg_entity(self, agg_entity: str) -> EmployeeDomainEventDataBuilder: ...
    def agg_entity_id(self, agg_entity_id: str) -> EmployeeDomainEventDataBuilder: ...
    def opt_type(self, opt_type: int) -> EmployeeDomainEventDataBuilder: ...
    def fields(self, fields: list[str]) -> EmployeeDomainEventDataBuilder: ...
    def build(self) -> EmployeeDomainEventData: ...
