from lark_oapi.core.construct import init as init

class EnableDisableAssessmentProbationResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EnableDisableAssessmentProbationResponseBodyBuilder: ...

class EnableDisableAssessmentProbationResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> EnableDisableAssessmentProbationResponseBody: ...
