from lark_oapi.core.construct import init as init

class EnableDisableAssessmentProbationRequestBody:
    active: bool | None
    app_url: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EnableDisableAssessmentProbationRequestBodyBuilder: ...

class EnableDisableAssessmentProbationRequestBodyBuilder:
    def __init__(self) -> None: ...
    def active(self, active: bool) -> EnableDisableAssessmentProbationRequestBodyBuilder: ...
    def app_url(self, app_url: str) -> EnableDisableAssessmentProbationRequestBodyBuilder: ...
    def build(self) -> EnableDisableAssessmentProbationRequestBody: ...
