from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class EnumField:
    api_name: str | None
    name: list[I18n] | None
    description: list[I18n] | None
    enum_api_name: str | None
    order: int | None
    status: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EnumFieldBuilder: ...

class EnumFieldBuilder:
    def __init__(self) -> None: ...
    def api_name(self, api_name: str) -> EnumFieldBuilder: ...
    def name(self, name: list[I18n]) -> EnumFieldBuilder: ...
    def description(self, description: list[I18n]) -> EnumFieldBuilder: ...
    def enum_api_name(self, enum_api_name: str) -> EnumFieldBuilder: ...
    def order(self, order: int) -> EnumFieldBuilder: ...
    def status(self, status: int) -> EnumFieldBuilder: ...
    def build(self) -> EnumField: ...
