from .enum_field import EnumField as EnumField
from lark_oapi.core.construct import init as init

class Enums:
    enum_apiname: str | None
    enum_items: list[EnumField] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EnumsBuilder: ...

class EnumsBuilder:
    def __init__(self) -> None: ...
    def enum_apiname(self, enum_apiname: str) -> EnumsBuilder: ...
    def enum_items(self, enum_items: list[EnumField]) -> EnumsBuilder: ...
    def build(self) -> Enums: ...
