from lark_oapi.core.construct import init as init

class FieldVariableValueToRecord:
    variable_api_name: str | None
    sub_value_key: str | None
    record_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FieldVariableValueToRecordBuilder: ...

class FieldVariableValueToRecordBuilder:
    def __init__(self) -> None: ...
    def variable_api_name(self, variable_api_name: str) -> FieldVariableValueToRecordBuilder: ...
    def sub_value_key(self, sub_value_key: str) -> FieldVariableValueToRecordBuilder: ...
    def record_id(self, record_id: str) -> FieldVariableValueToRecordBuilder: ...
    def build(self) -> FieldVariableValueToRecord: ...
