from lark_oapi.core.construct import init as init

class FieldVariableValueToFileForWrite:
    open_file_id: str | None
    file_name: str | None
    length: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FieldVariableValueToFileForWriteBuilder: ...

class FieldVariableValueToFileForWriteBuilder:
    def __init__(self) -> None: ...
    def open_file_id(self, open_file_id: str) -> FieldVariableValueToFileForWriteBuilder: ...
    def file_name(self, file_name: str) -> FieldVariableValueToFileForWriteBuilder: ...
    def length(self, length: int) -> FieldVariableValueToFileForWriteBuilder: ...
    def build(self) -> FieldVariableValueToFileForWrite: ...
