from lark_oapi.core.construct import init as init

class FieldVariableValueToFile:
    open_file_id: str | None
    file_name: str | None
    length: int | None
    mime_type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FieldVariableValueToFileBuilder: ...

class FieldVariableValueToFileBuilder:
    def __init__(self) -> None: ...
    def open_file_id(self, open_file_id: str) -> FieldVariableValueToFileBuilder: ...
    def file_name(self, file_name: str) -> FieldVariableValueToFileBuilder: ...
    def length(self, length: int) -> FieldVariableValueToFileBuilder: ...
    def mime_type(self, mime_type: str) -> FieldVariableValueToFileBuilder: ...
    def build(self) -> FieldVariableValueToFile: ...
