from lark_oapi.core.construct import init as init

class FieldVariableValueToObject:
    wk_id: str | None
    wk_api_name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FieldVariableValueToObjectBuilder: ...

class FieldVariableValueToObjectBuilder:
    def __init__(self) -> None: ...
    def wk_id(self, wk_id: str) -> FieldVariableValueToObjectBuilder: ...
    def wk_api_name(self, wk_api_name: str) -> FieldVariableValueToObjectBuilder: ...
    def build(self) -> FieldVariableValueToObject: ...
