from .field_variable_value_i18n import FieldVariableValueI18n as FieldVariableValueI18n
from lark_oapi.core.construct import init as init

class FieldVariableValueToEnum:
    value: str | None
    name: FieldVariableValueI18n | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FieldVariableValueToEnumBuilder: ...

class FieldVariableValueToEnumBuilder:
    def __init__(self) -> None: ...
    def value(self, value: str) -> FieldVariableValueToEnumBuilder: ...
    def name(self, name: FieldVariableValueI18n) -> FieldVariableValueToEnumBuilder: ...
    def build(self) -> FieldVariableValueToEnum: ...
