from .field_variable_sub_vlaue import FieldVariableSubVlaue as FieldVariableSubVlaue
from .field_variable_value_i18n import FieldVariableValueI18n as FieldVariableValueI18n
from .field_variable_value_to import FieldVariableValueTo as FieldVariableValueTo
from lark_oapi.core.construct import init as init

class FieldVariableValue:
    variable_api_name: str | None
    variable_name: FieldVariableValueI18n | None
    variable_value: FieldVariableValueTo | None
    sub_values: list[FieldVariableSubVlaue] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FieldVariableValueBuilder: ...

class FieldVariableValueBuilder:
    def __init__(self) -> None: ...
    def variable_api_name(self, variable_api_name: str) -> FieldVariableValueBuilder: ...
    def variable_name(self, variable_name: FieldVariableValueI18n) -> FieldVariableValueBuilder: ...
    def variable_value(self, variable_value: FieldVariableValueTo) -> FieldVariableValueBuilder: ...
    def sub_values(self, sub_values: list[FieldVariableSubVlaue]) -> FieldVariableValueBuilder: ...
    def build(self) -> FieldVariableValue: ...
