from .form_field_variable_bool_value import FormFieldVariableBoolValue as FormFieldVariableBoolValue
from .form_field_variable_i18n_value import FormFieldVariableI18nValue as FormFieldVariableI18nValue
from .form_field_variable_null_value import FormFieldVariableNullValue as FormFieldVariableNullValue
from .form_field_variable_number_value import FormFieldVariableNumberValue as FormFieldVariableNumberValue
from .form_field_variable_string_value import FormFieldVariableStringValue as FormFieldVariableStringValue
from lark_oapi.core.construct import init as init

class FormVariableValueInfo:
    text_value: FormFieldVariableStringValue | None
    number_value: FormFieldVariableStringValue | None
    date_value: FormFieldVariableNumberValue | None
    employment_value: FormFieldVariableStringValue | None
    date_time_value: FormFieldVariableNumberValue | None
    enum_value: FormFieldVariableStringValue | None
    null_value: FormFieldVariableNullValue | None
    bool_value: FormFieldVariableBoolValue | None
    department_value: FormFieldVariableStringValue | None
    i18n_value: FormFieldVariableI18nValue | None
    object_value: FormFieldVariableStringValue | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FormVariableValueInfoBuilder: ...

class FormVariableValueInfoBuilder:
    def __init__(self) -> None: ...
    def text_value(self, text_value: FormFieldVariableStringValue) -> FormVariableValueInfoBuilder: ...
    def number_value(self, number_value: FormFieldVariableStringValue) -> FormVariableValueInfoBuilder: ...
    def date_value(self, date_value: FormFieldVariableNumberValue) -> FormVariableValueInfoBuilder: ...
    def employment_value(self, employment_value: FormFieldVariableStringValue) -> FormVariableValueInfoBuilder: ...
    def date_time_value(self, date_time_value: FormFieldVariableNumberValue) -> FormVariableValueInfoBuilder: ...
    def enum_value(self, enum_value: FormFieldVariableStringValue) -> FormVariableValueInfoBuilder: ...
    def null_value(self, null_value: FormFieldVariableNullValue) -> FormVariableValueInfoBuilder: ...
    def bool_value(self, bool_value: FormFieldVariableBoolValue) -> FormVariableValueInfoBuilder: ...
    def department_value(self, department_value: FormFieldVariableStringValue) -> FormVariableValueInfoBuilder: ...
    def i18n_value(self, i18n_value: FormFieldVariableI18nValue) -> FormVariableValueInfoBuilder: ...
    def object_value(self, object_value: FormFieldVariableStringValue) -> FormVariableValueInfoBuilder: ...
    def build(self) -> FormVariableValueInfo: ...
