from .job import Job as Job
from lark_oapi.core.construct import init as init

class GetJobResponseBody:
    job: Job | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetJobResponseBodyBuilder: ...

class GetJobResponseBodyBuilder:
    def __init__(self) -> None: ...
    def job(self, job: Job) -> GetJobResponseBodyBuilder: ...
    def build(self) -> GetJobResponseBody: ...
