from .field_variable_value import FieldVariableValue as FieldVariableValue
from lark_oapi.core.construct import init as init

class GetProcessFormVariableDataResponseBody:
    field_variable_values: list[FieldVariableValue] | None
    process_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetProcessFormVariableDataResponseBodyBuilder: ...

class GetProcessFormVariableDataResponseBodyBuilder:
    def __init__(self) -> None: ...
    def field_variable_values(self, field_variable_values: list[FieldVariableValue]) -> GetProcessFormVariableDataResponseBodyBuilder: ...
    def process_id(self, process_id: str) -> GetProcessFormVariableDataResponseBodyBuilder: ...
    def build(self) -> GetProcessFormVariableDataResponseBody: ...
