from .department_hrbp import DepartmentHrbp as DepartmentHrbp
from lark_oapi.core.construct import init as init

class GetByDepartmentBpResponseBody:
    items: list[DepartmentHrbp] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetByDepartmentBpResponseBodyBuilder: ...

class GetByDepartmentBpResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[DepartmentHrbp]) -> GetByDepartmentBpResponseBodyBuilder: ...
    def build(self) -> GetByDepartmentBpResponseBody: ...
