from .get_by_department_bp_request_body import GetByDepartmentBpRequestBody as GetByDepartmentBpRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetByDepartmentBpRequest(BaseRequest):
    user_id_type: str | None
    department_id_type: str | None
    request_body: GetByDepartmentBpRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetByDepartmentBpRequestBuilder: ...

class GetByDepartmentBpRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> GetByDepartmentBpRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> GetByDepartmentBpRequestBuilder: ...
    def request_body(self, request_body: GetByDepartmentBpRequestBody) -> GetByDepartmentBpRequestBuilder: ...
    def build(self) -> GetByDepartmentBpRequest: ...
