from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetApprovalGroupsRequest(BaseRequest):
    user_id_type: str | None
    process_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetApprovalGroupsRequestBuilder: ...

class GetApprovalGroupsRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> GetApprovalGroupsRequestBuilder: ...
    def process_id(self, process_id: str) -> GetApprovalGroupsRequestBuilder: ...
    def build(self) -> GetApprovalGroupsRequest: ...
