from .approval_group import ApprovalGroup as ApprovalGroup
from lark_oapi.core.construct import init as init

class GetApprovalGroupsResponseBody:
    approval_group: ApprovalGroup | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetApprovalGroupsResponseBodyBuilder: ...

class GetApprovalGroupsResponseBodyBuilder:
    def __init__(self) -> None: ...
    def approval_group(self, approval_group: ApprovalGroup) -> GetApprovalGroupsResponseBodyBuilder: ...
    def build(self) -> GetApprovalGroupsResponseBody: ...
