from lark_oapi.core.construct import init as init

class GetApprovalGroupsRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetApprovalGroupsRequestBodyBuilder: ...

class GetApprovalGroupsRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetApprovalGroupsRequestBody: ...
