from lark_oapi.core.construct import init as init

class GetProcessRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetProcessRequestBodyBuilder: ...

class GetProcessRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetProcessRequestBody: ...
