from .enum import Enum as Enum
from .i18n import I18n as I18n
from .object_field_data import ObjectFieldData as ObjectFieldData
from lark_oapi.core.construct import init as init

class HiberarchyCommon:
    parent_id: str | None
    name: list[I18n] | None
    type: Enum | None
    active: bool | None
    effective_time: str | None
    expiration_time: str | None
    code: str | None
    description: list[I18n] | None
    tree_order: str | None
    list_order: str | None
    custom_fields: list[ObjectFieldData] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> HiberarchyCommonBuilder: ...

class HiberarchyCommonBuilder:
    def __init__(self) -> None: ...
    def parent_id(self, parent_id: str) -> HiberarchyCommonBuilder: ...
    def name(self, name: list[I18n]) -> HiberarchyCommonBuilder: ...
    def type(self, type: Enum) -> HiberarchyCommonBuilder: ...
    def active(self, active: bool) -> HiberarchyCommonBuilder: ...
    def effective_time(self, effective_time: str) -> HiberarchyCommonBuilder: ...
    def expiration_time(self, expiration_time: str) -> HiberarchyCommonBuilder: ...
    def code(self, code: str) -> HiberarchyCommonBuilder: ...
    def description(self, description: list[I18n]) -> HiberarchyCommonBuilder: ...
    def tree_order(self, tree_order: str) -> HiberarchyCommonBuilder: ...
    def list_order(self, list_order: str) -> HiberarchyCommonBuilder: ...
    def custom_fields(self, custom_fields: list[ObjectFieldData]) -> HiberarchyCommonBuilder: ...
    def build(self) -> HiberarchyCommon: ...
