from .enum import Enum as Enum
from lark_oapi.core.construct import init as init

class InternationalAssignmentV2ForPatch:
    effective_time: str | None
    international_assignment_expected_end_date: str | None
    expiration_time: str | None
    assignment_country: str | None
    assignment_city: str | None
    assignment_company: str | None
    international_assignment_status: Enum | None
    international_assignment_type: Enum | None
    international_assignment_allowance: bool | None
    accommodation: bool | None
    description: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InternationalAssignmentV2ForPatchBuilder: ...

class InternationalAssignmentV2ForPatchBuilder:
    def __init__(self) -> None: ...
    def effective_time(self, effective_time: str) -> InternationalAssignmentV2ForPatchBuilder: ...
    def international_assignment_expected_end_date(self, international_assignment_expected_end_date: str) -> InternationalAssignmentV2ForPatchBuilder: ...
    def expiration_time(self, expiration_time: str) -> InternationalAssignmentV2ForPatchBuilder: ...
    def assignment_country(self, assignment_country: str) -> InternationalAssignmentV2ForPatchBuilder: ...
    def assignment_city(self, assignment_city: str) -> InternationalAssignmentV2ForPatchBuilder: ...
    def assignment_company(self, assignment_company: str) -> InternationalAssignmentV2ForPatchBuilder: ...
    def international_assignment_status(self, international_assignment_status: Enum) -> InternationalAssignmentV2ForPatchBuilder: ...
    def international_assignment_type(self, international_assignment_type: Enum) -> InternationalAssignmentV2ForPatchBuilder: ...
    def international_assignment_allowance(self, international_assignment_allowance: bool) -> InternationalAssignmentV2ForPatchBuilder: ...
    def accommodation(self, accommodation: bool) -> InternationalAssignmentV2ForPatchBuilder: ...
    def description(self, description: str) -> InternationalAssignmentV2ForPatchBuilder: ...
    def build(self) -> InternationalAssignmentV2ForPatch: ...
