from .enum import Enum as Enum
from lark_oapi.core.construct import init as init

class InternationalAssignmentV2:
    id: str | None
    employment_id: str | None
    created_by: str | None
    created_at: str | None
    effective_time: str | None
    international_assignment_expected_end_date: str | None
    expiration_time: str | None
    deleted_at: str | None
    updated_at: str | None
    updated_by: str | None
    assignment_country: str | None
    assignment_city: str | None
    assignment_company: str | None
    international_assignment_status: Enum | None
    international_assignment_type: Enum | None
    international_assignment_allowance: bool | None
    accommodation: bool | None
    description: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InternationalAssignmentV2Builder: ...

class InternationalAssignmentV2Builder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> InternationalAssignmentV2Builder: ...
    def employment_id(self, employment_id: str) -> InternationalAssignmentV2Builder: ...
    def created_by(self, created_by: str) -> InternationalAssignmentV2Builder: ...
    def created_at(self, created_at: str) -> InternationalAssignmentV2Builder: ...
    def effective_time(self, effective_time: str) -> InternationalAssignmentV2Builder: ...
    def international_assignment_expected_end_date(self, international_assignment_expected_end_date: str) -> InternationalAssignmentV2Builder: ...
    def expiration_time(self, expiration_time: str) -> InternationalAssignmentV2Builder: ...
    def deleted_at(self, deleted_at: str) -> InternationalAssignmentV2Builder: ...
    def updated_at(self, updated_at: str) -> InternationalAssignmentV2Builder: ...
    def updated_by(self, updated_by: str) -> InternationalAssignmentV2Builder: ...
    def assignment_country(self, assignment_country: str) -> InternationalAssignmentV2Builder: ...
    def assignment_city(self, assignment_city: str) -> InternationalAssignmentV2Builder: ...
    def assignment_company(self, assignment_company: str) -> InternationalAssignmentV2Builder: ...
    def international_assignment_status(self, international_assignment_status: Enum) -> InternationalAssignmentV2Builder: ...
    def international_assignment_type(self, international_assignment_type: Enum) -> InternationalAssignmentV2Builder: ...
    def international_assignment_allowance(self, international_assignment_allowance: bool) -> InternationalAssignmentV2Builder: ...
    def accommodation(self, accommodation: bool) -> InternationalAssignmentV2Builder: ...
    def description(self, description: str) -> InternationalAssignmentV2Builder: ...
    def build(self) -> InternationalAssignmentV2: ...
