from .create_emp_custom_org import CreateEmpCustomOrg as CreateEmpCustomOrg
from lark_oapi.core.construct import init as init

class JobDataCustomOrg:
    effective_time: str | None
    start_reason: str | None
    custom_org_with_rates: list[CreateEmpCustomOrg] | None
    object_api_name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobDataCustomOrgBuilder: ...

class JobDataCustomOrgBuilder:
    def __init__(self) -> None: ...
    def effective_time(self, effective_time: str) -> JobDataCustomOrgBuilder: ...
    def start_reason(self, start_reason: str) -> JobDataCustomOrgBuilder: ...
    def custom_org_with_rates(self, custom_org_with_rates: list[CreateEmpCustomOrg]) -> JobDataCustomOrgBuilder: ...
    def object_api_name(self, object_api_name: str) -> JobDataCustomOrgBuilder: ...
    def build(self) -> JobDataCustomOrg: ...
