from lark_oapi.core.construct import init as init

class JobDataCostCenter:
    cost_center_id: str | None
    rate: int | None
    new_rate: float | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobDataCostCenterBuilder: ...

class JobDataCostCenterBuilder:
    def __init__(self) -> None: ...
    def cost_center_id(self, cost_center_id: str) -> JobDataCostCenterBuilder: ...
    def rate(self, rate: int) -> JobDataCostCenterBuilder: ...
    def new_rate(self, new_rate: float) -> JobDataCostCenterBuilder: ...
    def build(self) -> JobDataCostCenter: ...
