from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class JobGradeUpdate:
    grade_order: int | None
    code: str | None
    names: list[I18n] | None
    descriptions: list[I18n] | None
    active: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobGradeUpdateBuilder: ...

class JobGradeUpdateBuilder:
    def __init__(self) -> None: ...
    def grade_order(self, grade_order: int) -> JobGradeUpdateBuilder: ...
    def code(self, code: str) -> JobGradeUpdateBuilder: ...
    def names(self, names: list[I18n]) -> JobGradeUpdateBuilder: ...
    def descriptions(self, descriptions: list[I18n]) -> JobGradeUpdateBuilder: ...
    def active(self, active: bool) -> JobGradeUpdateBuilder: ...
    def build(self) -> JobGradeUpdate: ...
