from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class Language:
    language_id: str | None
    name: list[I18n] | None
    ietf_language_tag: str | None
    status: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LanguageBuilder: ...

class LanguageBuilder:
    def __init__(self) -> None: ...
    def language_id(self, language_id: str) -> LanguageBuilder: ...
    def name(self, name: list[I18n]) -> LanguageBuilder: ...
    def ietf_language_tag(self, ietf_language_tag: str) -> LanguageBuilder: ...
    def status(self, status: int) -> LanguageBuilder: ...
    def build(self) -> Language: ...
