from lark_oapi.core.construct import init as init

class LangText:
    lang: str | None
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LangTextBuilder: ...

class LangTextBuilder:
    def __init__(self) -> None: ...
    def lang(self, lang: str) -> LangTextBuilder: ...
    def value(self, value: str) -> LangTextBuilder: ...
    def build(self) -> LangText: ...
