from lark_oapi.core.construct import init as init

class LeaveProcessInfo:
    process_id: str | None
    process_status: str | None
    process_apply_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LeaveProcessInfoBuilder: ...

class LeaveProcessInfoBuilder:
    def __init__(self) -> None: ...
    def process_id(self, process_id: str) -> LeaveProcessInfoBuilder: ...
    def process_status(self, process_status: str) -> LeaveProcessInfoBuilder: ...
    def process_apply_time(self, process_apply_time: str) -> LeaveProcessInfoBuilder: ...
    def build(self) -> LeaveProcessInfo: ...
