from .lang_text import LangText as LangText
from lark_oapi.core.construct import init as init

class LeaveAccrualRecord:
    id: str | None
    employment_id: str | None
    leave_type_id: str | None
    granting_quantity: str | None
    granting_unit: int | None
    effective_date: str | None
    expiration_date: str | None
    granted_by: int | None
    reason: list[LangText] | None
    created_at: str | None
    created_by: str | None
    updated_at: str | None
    updated_by: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LeaveAccrualRecordBuilder: ...

class LeaveAccrualRecordBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> LeaveAccrualRecordBuilder: ...
    def employment_id(self, employment_id: str) -> LeaveAccrualRecordBuilder: ...
    def leave_type_id(self, leave_type_id: str) -> LeaveAccrualRecordBuilder: ...
    def granting_quantity(self, granting_quantity: str) -> LeaveAccrualRecordBuilder: ...
    def granting_unit(self, granting_unit: int) -> LeaveAccrualRecordBuilder: ...
    def effective_date(self, effective_date: str) -> LeaveAccrualRecordBuilder: ...
    def expiration_date(self, expiration_date: str) -> LeaveAccrualRecordBuilder: ...
    def granted_by(self, granted_by: int) -> LeaveAccrualRecordBuilder: ...
    def reason(self, reason: list[LangText]) -> LeaveAccrualRecordBuilder: ...
    def created_at(self, created_at: str) -> LeaveAccrualRecordBuilder: ...
    def created_by(self, created_by: str) -> LeaveAccrualRecordBuilder: ...
    def updated_at(self, updated_at: str) -> LeaveAccrualRecordBuilder: ...
    def updated_by(self, updated_by: str) -> LeaveAccrualRecordBuilder: ...
    def build(self) -> LeaveAccrualRecord: ...
