from .approver_info import ApproverInfo as ApproverInfo
from lark_oapi.core.construct import init as init

class ListProcessApproverResponseBody:
    page_token: str | None
    has_more: bool | None
    approvers: list[ApproverInfo] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListProcessApproverResponseBodyBuilder: ...

class ListProcessApproverResponseBodyBuilder:
    def __init__(self) -> None: ...
    def page_token(self, page_token: str) -> ListProcessApproverResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListProcessApproverResponseBodyBuilder: ...
    def approvers(self, approvers: list[ApproverInfo]) -> ListProcessApproverResponseBodyBuilder: ...
    def build(self) -> ListProcessApproverResponseBody: ...
