from .bp import Bp as Bp
from lark_oapi.core.construct import init as init

class ListBpResponseBody:
    items: list[Bp] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListBpResponseBodyBuilder: ...

class ListBpResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[Bp]) -> ListBpResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListBpResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListBpResponseBodyBuilder: ...
    def build(self) -> ListBpResponseBody: ...
