from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListWorkforcePlanRequest(BaseRequest):
    get_all_plan: bool | None
    active: bool | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListWorkforcePlanRequestBuilder: ...

class ListWorkforcePlanRequestBuilder:
    def __init__(self) -> None: ...
    def get_all_plan(self, get_all_plan: bool) -> ListWorkforcePlanRequestBuilder: ...
    def active(self, active: bool) -> ListWorkforcePlanRequestBuilder: ...
    def build(self) -> ListWorkforcePlanRequest: ...
