from lark_oapi.core.construct import init as init

class ListWorkforcePlanRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListWorkforcePlanRequestBodyBuilder: ...

class ListWorkforcePlanRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListWorkforcePlanRequestBody: ...
