from lark_oapi.core.construct import init as init

class ListJobRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListJobRequestBodyBuilder: ...

class ListJobRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListJobRequestBody: ...
