from lark_oapi.core.construct import init as init

class ListBpRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListBpRequestBodyBuilder: ...

class ListBpRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListBpRequestBody: ...
