from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListProcessApproverRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    user_id_type: str | None
    user_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListProcessApproverRequestBuilder: ...

class ListProcessApproverRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> ListProcessApproverRequestBuilder: ...
    def page_token(self, page_token: str) -> ListProcessApproverRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> ListProcessApproverRequestBuilder: ...
    def user_id(self, user_id: str) -> ListProcessApproverRequestBuilder: ...
    def build(self) -> ListProcessApproverRequest: ...
