from .address import Address as Address
from .location_version_data import LocationVersionData as LocationVersionData
from lark_oapi.core.construct import init as init

class LocationTimeline:
    location_version_data: list[LocationVersionData] | None
    address: list[Address] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LocationTimelineBuilder: ...

class LocationTimelineBuilder:
    def __init__(self) -> None: ...
    def location_version_data(self, location_version_data: list[LocationVersionData]) -> LocationTimelineBuilder: ...
    def address(self, address: list[Address]) -> LocationTimelineBuilder: ...
    def build(self) -> LocationTimeline: ...
