from .match_rule import MatchRule as MatchRule
from lark_oapi.core.construct import init as init

class MatchRules:
    match_rules: list[MatchRule] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MatchRulesBuilder: ...

class MatchRulesBuilder:
    def __init__(self) -> None: ...
    def match_rules(self, match_rules: list[MatchRule]) -> MatchRulesBuilder: ...
    def build(self) -> MatchRules: ...
