from lark_oapi.core.construct import init as init

class Name:
    full_name: str | None
    first_name: str | None
    middle_name: str | None
    name_primary: str | None
    local_first_name: str | None
    local_middle_name: str | None
    local_primary: str | None
    country_region_id: str | None
    custom_local_name: str | None
    custom_western_name: str | None
    additional_name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> NameBuilder: ...

class NameBuilder:
    def __init__(self) -> None: ...
    def full_name(self, full_name: str) -> NameBuilder: ...
    def first_name(self, first_name: str) -> NameBuilder: ...
    def middle_name(self, middle_name: str) -> NameBuilder: ...
    def name_primary(self, name_primary: str) -> NameBuilder: ...
    def local_first_name(self, local_first_name: str) -> NameBuilder: ...
    def local_middle_name(self, local_middle_name: str) -> NameBuilder: ...
    def local_primary(self, local_primary: str) -> NameBuilder: ...
    def country_region_id(self, country_region_id: str) -> NameBuilder: ...
    def custom_local_name(self, custom_local_name: str) -> NameBuilder: ...
    def custom_western_name(self, custom_western_name: str) -> NameBuilder: ...
    def additional_name(self, additional_name: str) -> NameBuilder: ...
    def build(self) -> Name: ...
