from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class Nationality:
    nationality_id: str | None
    name: list[I18n] | None
    alpha_2_code: str | None
    alpha_3_code: str | None
    numeric_code: int | None
    country_region_id: str | None
    status: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> NationalityBuilder: ...

class NationalityBuilder:
    def __init__(self) -> None: ...
    def nationality_id(self, nationality_id: str) -> NationalityBuilder: ...
    def name(self, name: list[I18n]) -> NationalityBuilder: ...
    def alpha_2_code(self, alpha_2_code: str) -> NationalityBuilder: ...
    def alpha_3_code(self, alpha_3_code: str) -> NationalityBuilder: ...
    def numeric_code(self, numeric_code: int) -> NationalityBuilder: ...
    def country_region_id(self, country_region_id: str) -> NationalityBuilder: ...
    def status(self, status: int) -> NationalityBuilder: ...
    def build(self) -> Nationality: ...
