from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class NoticePeriodDetail:
    wk_id: str | None
    value: int | None
    value_unit: str | None
    name: I18n | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> NoticePeriodDetailBuilder: ...

class NoticePeriodDetailBuilder:
    def __init__(self) -> None: ...
    def wk_id(self, wk_id: str) -> NoticePeriodDetailBuilder: ...
    def value(self, value: int) -> NoticePeriodDetailBuilder: ...
    def value_unit(self, value_unit: str) -> NoticePeriodDetailBuilder: ...
    def name(self, name: I18n) -> NoticePeriodDetailBuilder: ...
    def build(self) -> NoticePeriodDetail: ...
