from lark_oapi.core.construct import init as init

class OnboardingFlowChange:
    after_status: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OnboardingFlowChangeBuilder: ...

class OnboardingFlowChangeBuilder:
    def __init__(self) -> None: ...
    def after_status(self, after_status: str) -> OnboardingFlowChangeBuilder: ...
    def build(self) -> OnboardingFlowChange: ...
