from .qr_code_dimension_value import QrCodeDimensionValue as QrCodeDimensionValue
from lark_oapi.core.construct import init as init

class OnboardingQrCode:
    id: str | None
    pngs: list[str] | None
    url: str | None
    active: bool | None
    created_by: str | None
    updated_by: str | None
    created_at: int | None
    updated_at: int | None
    dimension_values: list[QrCodeDimensionValue] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OnboardingQrCodeBuilder: ...

class OnboardingQrCodeBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> OnboardingQrCodeBuilder: ...
    def pngs(self, pngs: list[str]) -> OnboardingQrCodeBuilder: ...
    def url(self, url: str) -> OnboardingQrCodeBuilder: ...
    def active(self, active: bool) -> OnboardingQrCodeBuilder: ...
    def created_by(self, created_by: str) -> OnboardingQrCodeBuilder: ...
    def updated_by(self, updated_by: str) -> OnboardingQrCodeBuilder: ...
    def created_at(self, created_at: int) -> OnboardingQrCodeBuilder: ...
    def updated_at(self, updated_at: int) -> OnboardingQrCodeBuilder: ...
    def dimension_values(self, dimension_values: list[QrCodeDimensionValue]) -> OnboardingQrCodeBuilder: ...
    def build(self) -> OnboardingQrCode: ...
