from lark_oapi.core.construct import init as init

class OnboardingTaskChange:
    after_status: str | None
    task_code: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OnboardingTaskChangeBuilder: ...

class OnboardingTaskChangeBuilder:
    def __init__(self) -> None: ...
    def after_status(self, after_status: str) -> OnboardingTaskChangeBuilder: ...
    def task_code(self, task_code: str) -> OnboardingTaskChangeBuilder: ...
    def build(self) -> OnboardingTaskChange: ...
