from lark_oapi.core.construct import init as init

class OnboardingTask:
    task_name: str | None
    task_status: str | None
    operator_id: str | None
    task_code: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OnboardingTaskBuilder: ...

class OnboardingTaskBuilder:
    def __init__(self) -> None: ...
    def task_name(self, task_name: str) -> OnboardingTaskBuilder: ...
    def task_status(self, task_status: str) -> OnboardingTaskBuilder: ...
    def operator_id(self, operator_id: str) -> OnboardingTaskBuilder: ...
    def task_code(self, task_code: str) -> OnboardingTaskBuilder: ...
    def build(self) -> OnboardingTask: ...
