from lark_oapi.core.construct import init as init

class OpenQueryJobChangeListByIdsApprovalGroupsRequestBody:
    job_change_ids: list[str] | None
    need_department_path: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OpenQueryJobChangeListByIdsApprovalGroupsRequestBodyBuilder: ...

class OpenQueryJobChangeListByIdsApprovalGroupsRequestBodyBuilder:
    def __init__(self) -> None: ...
    def job_change_ids(self, job_change_ids: list[str]) -> OpenQueryJobChangeListByIdsApprovalGroupsRequestBodyBuilder: ...
    def need_department_path(self, need_department_path: bool) -> OpenQueryJobChangeListByIdsApprovalGroupsRequestBodyBuilder: ...
    def build(self) -> OpenQueryJobChangeListByIdsApprovalGroupsRequestBody: ...
