from .department_change import DepartmentChange as DepartmentChange
from lark_oapi.core.construct import init as init

class OpenQueryDepartmentChangeListByIdsApprovalGroupsResponseBody:
    department_changes: list[DepartmentChange] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OpenQueryDepartmentChangeListByIdsApprovalGroupsResponseBodyBuilder: ...

class OpenQueryDepartmentChangeListByIdsApprovalGroupsResponseBodyBuilder:
    def __init__(self) -> None: ...
    def department_changes(self, department_changes: list[DepartmentChange]) -> OpenQueryDepartmentChangeListByIdsApprovalGroupsResponseBodyBuilder: ...
    def build(self) -> OpenQueryDepartmentChangeListByIdsApprovalGroupsResponseBody: ...
