from .open_query_department_change_list_by_ids_approval_groups_request_body import OpenQueryDepartmentChangeListByIdsApprovalGroupsRequestBody as OpenQueryDepartmentChangeListByIdsApprovalGroupsRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class OpenQueryDepartmentChangeListByIdsApprovalGroupsRequest(BaseRequest):
    process_id: str | None
    user_id_type: str | None
    department_id_type: str | None
    request_body: OpenQueryDepartmentChangeListByIdsApprovalGroupsRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> OpenQueryDepartmentChangeListByIdsApprovalGroupsRequestBuilder: ...

class OpenQueryDepartmentChangeListByIdsApprovalGroupsRequestBuilder:
    def __init__(self) -> None: ...
    def process_id(self, process_id: str) -> OpenQueryDepartmentChangeListByIdsApprovalGroupsRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> OpenQueryDepartmentChangeListByIdsApprovalGroupsRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> OpenQueryDepartmentChangeListByIdsApprovalGroupsRequestBuilder: ...
    def request_body(self, request_body: OpenQueryDepartmentChangeListByIdsApprovalGroupsRequestBody) -> OpenQueryDepartmentChangeListByIdsApprovalGroupsRequestBuilder: ...
    def build(self) -> OpenQueryDepartmentChangeListByIdsApprovalGroupsRequest: ...
