from .open_query_job_change_list_by_ids_approval_groups_request_body import OpenQueryJobChangeListByIdsApprovalGroupsRequestBody as OpenQueryJobChangeListByIdsApprovalGroupsRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class OpenQueryJobChangeListByIdsApprovalGroupsRequest(BaseRequest):
    process_id: str | None
    user_id_type: str | None
    department_id_type: str | None
    request_body: OpenQueryJobChangeListByIdsApprovalGroupsRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> OpenQueryJobChangeListByIdsApprovalGroupsRequestBuilder: ...

class OpenQueryJobChangeListByIdsApprovalGroupsRequestBuilder:
    def __init__(self) -> None: ...
    def process_id(self, process_id: str) -> OpenQueryJobChangeListByIdsApprovalGroupsRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> OpenQueryJobChangeListByIdsApprovalGroupsRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> OpenQueryJobChangeListByIdsApprovalGroupsRequestBuilder: ...
    def request_body(self, request_body: OpenQueryJobChangeListByIdsApprovalGroupsRequestBody) -> OpenQueryJobChangeListByIdsApprovalGroupsRequestBuilder: ...
    def build(self) -> OpenQueryJobChangeListByIdsApprovalGroupsRequest: ...
