from lark_oapi.core.construct import init as init

class OrganizationDomainEventData:
    id: str | None
    entity: str | None
    agg_entity: str | None
    agg_entity_id: str | None
    agg_entity_field: str | None
    opt_type: int | None
    field_changes: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OrganizationDomainEventDataBuilder: ...

class OrganizationDomainEventDataBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> OrganizationDomainEventDataBuilder: ...
    def entity(self, entity: str) -> OrganizationDomainEventDataBuilder: ...
    def agg_entity(self, agg_entity: str) -> OrganizationDomainEventDataBuilder: ...
    def agg_entity_id(self, agg_entity_id: str) -> OrganizationDomainEventDataBuilder: ...
    def agg_entity_field(self, agg_entity_field: str) -> OrganizationDomainEventDataBuilder: ...
    def opt_type(self, opt_type: int) -> OrganizationDomainEventDataBuilder: ...
    def field_changes(self, field_changes: list[str]) -> OrganizationDomainEventDataBuilder: ...
    def build(self) -> OrganizationDomainEventData: ...
