from lark_oapi.core.construct import init as init

class OrgdraftDepartmentId:
    department_id: str | None
    draft_department_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OrgdraftDepartmentIdBuilder: ...

class OrgdraftDepartmentIdBuilder:
    def __init__(self) -> None: ...
    def department_id(self, department_id: str) -> OrgdraftDepartmentIdBuilder: ...
    def draft_department_id(self, draft_department_id: str) -> OrgdraftDepartmentIdBuilder: ...
    def build(self) -> OrgdraftDepartmentId: ...
