from lark_oapi.core.construct import init as init

class ParentsDepartmentRequestBody:
    department_id_list: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ParentsDepartmentRequestBodyBuilder: ...

class ParentsDepartmentRequestBodyBuilder:
    def __init__(self) -> None: ...
    def department_id_list(self, department_id_list: list[str]) -> ParentsDepartmentRequestBodyBuilder: ...
    def build(self) -> ParentsDepartmentRequestBody: ...
