from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class PatchCostCenterVersionRequestBody:
    name: list[I18n] | None
    parent_cost_center_id: str | None
    managers: list[str] | None
    description: list[I18n] | None
    effective_time: str | None
    operation_reason: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchCostCenterVersionRequestBodyBuilder: ...

class PatchCostCenterVersionRequestBodyBuilder:
    def __init__(self) -> None: ...
    def name(self, name: list[I18n]) -> PatchCostCenterVersionRequestBodyBuilder: ...
    def parent_cost_center_id(self, parent_cost_center_id: str) -> PatchCostCenterVersionRequestBodyBuilder: ...
    def managers(self, managers: list[str]) -> PatchCostCenterVersionRequestBodyBuilder: ...
    def description(self, description: list[I18n]) -> PatchCostCenterVersionRequestBodyBuilder: ...
    def effective_time(self, effective_time: str) -> PatchCostCenterVersionRequestBodyBuilder: ...
    def operation_reason(self, operation_reason: str) -> PatchCostCenterVersionRequestBodyBuilder: ...
    def build(self) -> PatchCostCenterVersionRequestBody: ...
