from .employees_additional_job_write_resp import EmployeesAdditionalJobWriteResp as EmployeesAdditionalJobWriteResp
from lark_oapi.core.construct import init as init

class PatchEmployeesAdditionalJobResponseBody:
    additional_job: EmployeesAdditionalJobWriteResp | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchEmployeesAdditionalJobResponseBodyBuilder: ...

class PatchEmployeesAdditionalJobResponseBodyBuilder:
    def __init__(self) -> None: ...
    def additional_job(self, additional_job: EmployeesAdditionalJobWriteResp) -> PatchEmployeesAdditionalJobResponseBodyBuilder: ...
    def build(self) -> PatchEmployeesAdditionalJobResponseBody: ...
