from lark_oapi.core.construct import init as init

class PatchProbationAssessmentResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchProbationAssessmentResponseBodyBuilder: ...

class PatchProbationAssessmentResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> PatchProbationAssessmentResponseBody: ...
