from lark_oapi.core.construct import init as init

class PatchLocationAddressResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchLocationAddressResponseBodyBuilder: ...

class PatchLocationAddressResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> PatchLocationAddressResponseBody: ...
