from .assessment_for_create import AssessmentForCreate as AssessmentForCreate
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PatchProbationAssessmentRequest(BaseRequest):
    client_token: str | None
    assessment_id: str | None
    request_body: AssessmentForCreate | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PatchProbationAssessmentRequestBuilder: ...

class PatchProbationAssessmentRequestBuilder:
    def __init__(self) -> None: ...
    def client_token(self, client_token: str) -> PatchProbationAssessmentRequestBuilder: ...
    def assessment_id(self, assessment_id: str) -> PatchProbationAssessmentRequestBuilder: ...
    def request_body(self, request_body: AssessmentForCreate) -> PatchProbationAssessmentRequestBuilder: ...
    def build(self) -> PatchProbationAssessmentRequest: ...
