from .person_info import PersonInfo as PersonInfo
from lark_oapi.core.construct import init as init

class PatchPersonResponseBody:
    person: PersonInfo | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchPersonResponseBodyBuilder: ...

class PatchPersonResponseBodyBuilder:
    def __init__(self) -> None: ...
    def person(self, person: PersonInfo) -> PatchPersonResponseBodyBuilder: ...
    def build(self) -> PatchPersonResponseBody: ...
