from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class PathwayUpdate:
    code: str | None
    names: list[I18n] | None
    descriptions: list[I18n] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PathwayUpdateBuilder: ...

class PathwayUpdateBuilder:
    def __init__(self) -> None: ...
    def code(self, code: str) -> PathwayUpdateBuilder: ...
    def names(self, names: list[I18n]) -> PathwayUpdateBuilder: ...
    def descriptions(self, descriptions: list[I18n]) -> PathwayUpdateBuilder: ...
    def build(self) -> PathwayUpdate: ...
