from .enum import Enum as Enum
from lark_oapi.core.construct import init as init

class PersonInfoChn:
    native_region: str | None
    hukou_type: Enum | None
    hukou_location: str | None
    first_entry_time: str | None
    leave_time: str | None
    political_affiliations: list[Enum] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PersonInfoChnBuilder: ...

class PersonInfoChnBuilder:
    def __init__(self) -> None: ...
    def native_region(self, native_region: str) -> PersonInfoChnBuilder: ...
    def hukou_type(self, hukou_type: Enum) -> PersonInfoChnBuilder: ...
    def hukou_location(self, hukou_location: str) -> PersonInfoChnBuilder: ...
    def first_entry_time(self, first_entry_time: str) -> PersonInfoChnBuilder: ...
    def leave_time(self, leave_time: str) -> PersonInfoChnBuilder: ...
    def political_affiliations(self, political_affiliations: list[Enum]) -> PersonInfoChnBuilder: ...
    def build(self) -> PersonInfoChn: ...
