from lark_oapi.core.construct import init as init

class PhoneForUpdate:
    international_area_code: str | None
    phone_number: str | None
    device_type: str | None
    phone_usage: str | None
    is_primary: bool | None
    is_public: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PhoneForUpdateBuilder: ...

class PhoneForUpdateBuilder:
    def __init__(self) -> None: ...
    def international_area_code(self, international_area_code: str) -> PhoneForUpdateBuilder: ...
    def phone_number(self, phone_number: str) -> PhoneForUpdateBuilder: ...
    def device_type(self, device_type: str) -> PhoneForUpdateBuilder: ...
    def phone_usage(self, phone_usage: str) -> PhoneForUpdateBuilder: ...
    def is_primary(self, is_primary: bool) -> PhoneForUpdateBuilder: ...
    def is_public(self, is_public: bool) -> PhoneForUpdateBuilder: ...
    def build(self) -> PhoneForUpdate: ...
