from .position_adjustment_info import PositionAdjustmentInfo as PositionAdjustmentInfo
from lark_oapi.core.construct import init as init

class PositionChange:
    position_change_id: str | None
    position_id: str | None
    draft_position_id: str | None
    position_change_type: str | None
    position_adjustment_info: PositionAdjustmentInfo | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PositionChangeBuilder: ...

class PositionChangeBuilder:
    def __init__(self) -> None: ...
    def position_change_id(self, position_change_id: str) -> PositionChangeBuilder: ...
    def position_id(self, position_id: str) -> PositionChangeBuilder: ...
    def draft_position_id(self, draft_position_id: str) -> PositionChangeBuilder: ...
    def position_change_type(self, position_change_type: str) -> PositionChangeBuilder: ...
    def position_adjustment_info(self, position_adjustment_info: PositionAdjustmentInfo) -> PositionChangeBuilder: ...
    def build(self) -> PositionChange: ...
