from .custom_field_data import CustomFieldData as CustomFieldData
from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class Position:
    position_id: str | None
    code: str | None
    names: list[I18n] | None
    descriptions: list[I18n] | None
    active: bool | None
    job_family_id_list: list[str] | None
    cost_center_id: str | None
    job_id: str | None
    job_level_id_list: list[str] | None
    employee_type_id_list: list[str] | None
    job_grade_id_list: list[str] | None
    work_location_id_list: list[str] | None
    working_hours_type_id: str | None
    department_id: str | None
    direct_leader_id: str | None
    dotted_line_leader_id: str | None
    is_key_position: bool | None
    effective_time: str | None
    expiration_time: str | None
    custom_fields: list[CustomFieldData] | None
    created_by: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PositionBuilder: ...

class PositionBuilder:
    def __init__(self) -> None: ...
    def position_id(self, position_id: str) -> PositionBuilder: ...
    def code(self, code: str) -> PositionBuilder: ...
    def names(self, names: list[I18n]) -> PositionBuilder: ...
    def descriptions(self, descriptions: list[I18n]) -> PositionBuilder: ...
    def active(self, active: bool) -> PositionBuilder: ...
    def job_family_id_list(self, job_family_id_list: list[str]) -> PositionBuilder: ...
    def cost_center_id(self, cost_center_id: str) -> PositionBuilder: ...
    def job_id(self, job_id: str) -> PositionBuilder: ...
    def job_level_id_list(self, job_level_id_list: list[str]) -> PositionBuilder: ...
    def employee_type_id_list(self, employee_type_id_list: list[str]) -> PositionBuilder: ...
    def job_grade_id_list(self, job_grade_id_list: list[str]) -> PositionBuilder: ...
    def work_location_id_list(self, work_location_id_list: list[str]) -> PositionBuilder: ...
    def working_hours_type_id(self, working_hours_type_id: str) -> PositionBuilder: ...
    def department_id(self, department_id: str) -> PositionBuilder: ...
    def direct_leader_id(self, direct_leader_id: str) -> PositionBuilder: ...
    def dotted_line_leader_id(self, dotted_line_leader_id: str) -> PositionBuilder: ...
    def is_key_position(self, is_key_position: bool) -> PositionBuilder: ...
    def effective_time(self, effective_time: str) -> PositionBuilder: ...
    def expiration_time(self, expiration_time: str) -> PositionBuilder: ...
    def custom_fields(self, custom_fields: list[CustomFieldData]) -> PositionBuilder: ...
    def created_by(self, created_by: str) -> PositionBuilder: ...
    def build(self) -> Position: ...
