from lark_oapi.core.construct import init as init

class PreHireProbationInfo:
    probation_start_date: str | None
    probation_end_date: str | None
    probation_period: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PreHireProbationInfoBuilder: ...

class PreHireProbationInfoBuilder:
    def __init__(self) -> None: ...
    def probation_start_date(self, probation_start_date: str) -> PreHireProbationInfoBuilder: ...
    def probation_end_date(self, probation_end_date: str) -> PreHireProbationInfoBuilder: ...
    def probation_period(self, probation_period: int) -> PreHireProbationInfoBuilder: ...
    def build(self) -> PreHireProbationInfo: ...
