from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class PreHirePayGroupInfo:
    name: list[I18n] | None
    id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PreHirePayGroupInfoBuilder: ...

class PreHirePayGroupInfoBuilder:
    def __init__(self) -> None: ...
    def name(self, name: list[I18n]) -> PreHirePayGroupInfoBuilder: ...
    def id(self, id: str) -> PreHirePayGroupInfoBuilder: ...
    def build(self) -> PreHirePayGroupInfo: ...
