from .object_field_data import ObjectFieldData as ObjectFieldData
from lark_oapi.core.construct import init as init

class PrehireSeniorityAdjustInformationUpdate:
    seniority_adjustment: float | None
    seniority_adjustment_type: str | None
    reasons_for_seniority_adjustment: str | None
    start_date: str | None
    end_date: str | None
    custom_fields: list[ObjectFieldData] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PrehireSeniorityAdjustInformationUpdateBuilder: ...

class PrehireSeniorityAdjustInformationUpdateBuilder:
    def __init__(self) -> None: ...
    def seniority_adjustment(self, seniority_adjustment: float) -> PrehireSeniorityAdjustInformationUpdateBuilder: ...
    def seniority_adjustment_type(self, seniority_adjustment_type: str) -> PrehireSeniorityAdjustInformationUpdateBuilder: ...
    def reasons_for_seniority_adjustment(self, reasons_for_seniority_adjustment: str) -> PrehireSeniorityAdjustInformationUpdateBuilder: ...
    def start_date(self, start_date: str) -> PrehireSeniorityAdjustInformationUpdateBuilder: ...
    def end_date(self, end_date: str) -> PrehireSeniorityAdjustInformationUpdateBuilder: ...
    def custom_fields(self, custom_fields: list[ObjectFieldData]) -> PrehireSeniorityAdjustInformationUpdateBuilder: ...
    def build(self) -> PrehireSeniorityAdjustInformationUpdate: ...
