from .object_field_data import ObjectFieldData as ObjectFieldData
from lark_oapi.core.construct import init as init

class PrehireSeniorityAdjustInformation:
    seniority_adjustment: float | None
    seniority_adjustment_type: str | None
    reasons_for_seniority_adjustment: str | None
    start_date: str | None
    end_date: str | None
    custom_fields: list[ObjectFieldData] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PrehireSeniorityAdjustInformationBuilder: ...

class PrehireSeniorityAdjustInformationBuilder:
    def __init__(self) -> None: ...
    def seniority_adjustment(self, seniority_adjustment: float) -> PrehireSeniorityAdjustInformationBuilder: ...
    def seniority_adjustment_type(self, seniority_adjustment_type: str) -> PrehireSeniorityAdjustInformationBuilder: ...
    def reasons_for_seniority_adjustment(self, reasons_for_seniority_adjustment: str) -> PrehireSeniorityAdjustInformationBuilder: ...
    def start_date(self, start_date: str) -> PrehireSeniorityAdjustInformationBuilder: ...
    def end_date(self, end_date: str) -> PrehireSeniorityAdjustInformationBuilder: ...
    def custom_fields(self, custom_fields: list[ObjectFieldData]) -> PrehireSeniorityAdjustInformationBuilder: ...
    def build(self) -> PrehireSeniorityAdjustInformation: ...
