from lark_oapi.core.construct import init as init

class PrehireDefaultCostCenterUpdate:
    cost_center_id: str | None
    is_herit: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PrehireDefaultCostCenterUpdateBuilder: ...

class PrehireDefaultCostCenterUpdateBuilder:
    def __init__(self) -> None: ...
    def cost_center_id(self, cost_center_id: str) -> PrehireDefaultCostCenterUpdateBuilder: ...
    def is_herit(self, is_herit: bool) -> PrehireDefaultCostCenterUpdateBuilder: ...
    def build(self) -> PrehireDefaultCostCenterUpdate: ...
