from .dataengine_i18n import DataengineI18n as DataengineI18n
from .process_link import ProcessLink as ProcessLink
from lark_oapi.core.construct import init as init

class ProcessTodoItem:
    approver_id: str | None
    type: int | None
    links: ProcessLink | None
    operator_id: str | None
    operator_name: DataengineI18n | None
    node_name: DataengineI18n | None
    create_time: str | None
    node_definition_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ProcessTodoItemBuilder: ...

class ProcessTodoItemBuilder:
    def __init__(self) -> None: ...
    def approver_id(self, approver_id: str) -> ProcessTodoItemBuilder: ...
    def type(self, type: int) -> ProcessTodoItemBuilder: ...
    def links(self, links: ProcessLink) -> ProcessTodoItemBuilder: ...
    def operator_id(self, operator_id: str) -> ProcessTodoItemBuilder: ...
    def operator_name(self, operator_name: DataengineI18n) -> ProcessTodoItemBuilder: ...
    def node_name(self, node_name: DataengineI18n) -> ProcessTodoItemBuilder: ...
    def create_time(self, create_time: str) -> ProcessTodoItemBuilder: ...
    def node_definition_id(self, node_definition_id: str) -> ProcessTodoItemBuilder: ...
    def build(self) -> ProcessTodoItem: ...
