from .dataengine_i18n import DataengineI18n as DataengineI18n
from lark_oapi.core.construct import init as init

class ProcessCommentInfo:
    commentor_id: str | None
    commentor_name: DataengineI18n | None
    comment_time: str | None
    comment_msg: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ProcessCommentInfoBuilder: ...

class ProcessCommentInfoBuilder:
    def __init__(self) -> None: ...
    def commentor_id(self, commentor_id: str) -> ProcessCommentInfoBuilder: ...
    def commentor_name(self, commentor_name: DataengineI18n) -> ProcessCommentInfoBuilder: ...
    def comment_time(self, comment_time: str) -> ProcessCommentInfoBuilder: ...
    def comment_msg(self, comment_msg: str) -> ProcessCommentInfoBuilder: ...
    def build(self) -> ProcessCommentInfo: ...
