from .profile_setting_custom_group import ProfileSettingCustomGroup as ProfileSettingCustomGroup
from .profile_setting_emp_basic_info_for_update import ProfileSettingEmpBasicInfoForUpdate as ProfileSettingEmpBasicInfoForUpdate
from .profile_setting_probation_info import ProfileSettingProbationInfo as ProfileSettingProbationInfo
from .seniority_adjust_information_edit import SeniorityAdjustInformationEdit as SeniorityAdjustInformationEdit
from lark_oapi.core.construct import init as init

class ProfileSettingEmpInfoForUpdate:
    basic_info: ProfileSettingEmpBasicInfoForUpdate | None
    probation_info: ProfileSettingProbationInfo | None
    custom_groups: list[ProfileSettingCustomGroup] | None
    seniority_adjust_informations: list[SeniorityAdjustInformationEdit] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ProfileSettingEmpInfoForUpdateBuilder: ...

class ProfileSettingEmpInfoForUpdateBuilder:
    def __init__(self) -> None: ...
    def basic_info(self, basic_info: ProfileSettingEmpBasicInfoForUpdate) -> ProfileSettingEmpInfoForUpdateBuilder: ...
    def probation_info(self, probation_info: ProfileSettingProbationInfo) -> ProfileSettingEmpInfoForUpdateBuilder: ...
    def custom_groups(self, custom_groups: list[ProfileSettingCustomGroup]) -> ProfileSettingEmpInfoForUpdateBuilder: ...
    def seniority_adjust_informations(self, seniority_adjust_informations: list[SeniorityAdjustInformationEdit]) -> ProfileSettingEmpInfoForUpdateBuilder: ...
    def build(self) -> ProfileSettingEmpInfoForUpdate: ...
