from lark_oapi.core.construct import init as init

class ProfileSettingProbationInfo:
    probation_start_date: str | None
    probation_expected_end_date: str | None
    actual_probation_end_date: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ProfileSettingProbationInfoBuilder: ...

class ProfileSettingProbationInfoBuilder:
    def __init__(self) -> None: ...
    def probation_start_date(self, probation_start_date: str) -> ProfileSettingProbationInfoBuilder: ...
    def probation_expected_end_date(self, probation_expected_end_date: str) -> ProfileSettingProbationInfoBuilder: ...
    def actual_probation_end_date(self, actual_probation_end_date: str) -> ProfileSettingProbationInfoBuilder: ...
    def build(self) -> ProfileSettingProbationInfo: ...
