from lark_oapi.core.construct import init as init

class ProfileSettingAddress:
    address_type: str | None
    country_region: str | None
    region: str | None
    region_subdivision_1: str | None
    region_subdivision_2: str | None
    city_v2: str | None
    city_text: str | None
    local_city_text: str | None
    city_subdivision_1: str | None
    city_subdivision_2: str | None
    district_v2: str | None
    postal_code: str | None
    address_line_1: str | None
    local_address_line_1: str | None
    address_line_2: str | None
    local_address_line_2: str | None
    address_line_3: str | None
    local_address_line_3: str | None
    address_line_4: str | None
    local_address_line_5: str | None
    address_line_6: str | None
    local_address_line_6: str | None
    address_line_7: str | None
    local_address_line_7: str | None
    address_line_8: str | None
    local_address_line_8: str | None
    address_line_9: str | None
    local_address_line_9: str | None
    local_address_line_4: str | None
    address_line_5: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ProfileSettingAddressBuilder: ...

class ProfileSettingAddressBuilder:
    def __init__(self) -> None: ...
    def address_type(self, address_type: str) -> ProfileSettingAddressBuilder: ...
    def country_region(self, country_region: str) -> ProfileSettingAddressBuilder: ...
    def region(self, region: str) -> ProfileSettingAddressBuilder: ...
    def region_subdivision_1(self, region_subdivision_1: str) -> ProfileSettingAddressBuilder: ...
    def region_subdivision_2(self, region_subdivision_2: str) -> ProfileSettingAddressBuilder: ...
    def city_v2(self, city_v2: str) -> ProfileSettingAddressBuilder: ...
    def city_text(self, city_text: str) -> ProfileSettingAddressBuilder: ...
    def local_city_text(self, local_city_text: str) -> ProfileSettingAddressBuilder: ...
    def city_subdivision_1(self, city_subdivision_1: str) -> ProfileSettingAddressBuilder: ...
    def city_subdivision_2(self, city_subdivision_2: str) -> ProfileSettingAddressBuilder: ...
    def district_v2(self, district_v2: str) -> ProfileSettingAddressBuilder: ...
    def postal_code(self, postal_code: str) -> ProfileSettingAddressBuilder: ...
    def address_line_1(self, address_line_1: str) -> ProfileSettingAddressBuilder: ...
    def local_address_line_1(self, local_address_line_1: str) -> ProfileSettingAddressBuilder: ...
    def address_line_2(self, address_line_2: str) -> ProfileSettingAddressBuilder: ...
    def local_address_line_2(self, local_address_line_2: str) -> ProfileSettingAddressBuilder: ...
    def address_line_3(self, address_line_3: str) -> ProfileSettingAddressBuilder: ...
    def local_address_line_3(self, local_address_line_3: str) -> ProfileSettingAddressBuilder: ...
    def address_line_4(self, address_line_4: str) -> ProfileSettingAddressBuilder: ...
    def local_address_line_5(self, local_address_line_5: str) -> ProfileSettingAddressBuilder: ...
    def address_line_6(self, address_line_6: str) -> ProfileSettingAddressBuilder: ...
    def local_address_line_6(self, local_address_line_6: str) -> ProfileSettingAddressBuilder: ...
    def address_line_7(self, address_line_7: str) -> ProfileSettingAddressBuilder: ...
    def local_address_line_7(self, local_address_line_7: str) -> ProfileSettingAddressBuilder: ...
    def address_line_8(self, address_line_8: str) -> ProfileSettingAddressBuilder: ...
    def local_address_line_8(self, local_address_line_8: str) -> ProfileSettingAddressBuilder: ...
    def address_line_9(self, address_line_9: str) -> ProfileSettingAddressBuilder: ...
    def local_address_line_9(self, local_address_line_9: str) -> ProfileSettingAddressBuilder: ...
    def local_address_line_4(self, local_address_line_4: str) -> ProfileSettingAddressBuilder: ...
    def address_line_5(self, address_line_5: str) -> ProfileSettingAddressBuilder: ...
    def build(self) -> ProfileSettingAddress: ...
