from .profile_setting_address import ProfileSettingAddress as ProfileSettingAddress
from .profile_setting_custom_field import ProfileSettingCustomField as ProfileSettingCustomField
from .profile_setting_file import ProfileSettingFile as ProfileSettingFile
from .profile_setting_phone import ProfileSettingPhone as ProfileSettingPhone
from lark_oapi.core.construct import init as init

class ProfileSettingDependent:
    legal_name: str | None
    date_of_birth: str | None
    relationship_with_dependent: str | None
    gender: str | None
    phone: ProfileSettingPhone | None
    job: str | None
    child_birth_certificates: list[ProfileSettingFile] | None
    employer: str | None
    custom_fields: list[ProfileSettingCustomField] | None
    address: ProfileSettingAddress | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ProfileSettingDependentBuilder: ...

class ProfileSettingDependentBuilder:
    def __init__(self) -> None: ...
    def legal_name(self, legal_name: str) -> ProfileSettingDependentBuilder: ...
    def date_of_birth(self, date_of_birth: str) -> ProfileSettingDependentBuilder: ...
    def relationship_with_dependent(self, relationship_with_dependent: str) -> ProfileSettingDependentBuilder: ...
    def gender(self, gender: str) -> ProfileSettingDependentBuilder: ...
    def phone(self, phone: ProfileSettingPhone) -> ProfileSettingDependentBuilder: ...
    def job(self, job: str) -> ProfileSettingDependentBuilder: ...
    def child_birth_certificates(self, child_birth_certificates: list[ProfileSettingFile]) -> ProfileSettingDependentBuilder: ...
    def employer(self, employer: str) -> ProfileSettingDependentBuilder: ...
    def custom_fields(self, custom_fields: list[ProfileSettingCustomField]) -> ProfileSettingDependentBuilder: ...
    def address(self, address: ProfileSettingAddress) -> ProfileSettingDependentBuilder: ...
    def build(self) -> ProfileSettingDependent: ...
