from .profile_setting_custom_field import ProfileSettingCustomField as ProfileSettingCustomField
from lark_oapi.core.construct import init as init

class ProfileSettingCustomGroupItem:
    custom_fields: list[ProfileSettingCustomField] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ProfileSettingCustomGroupItemBuilder: ...

class ProfileSettingCustomGroupItemBuilder:
    def __init__(self) -> None: ...
    def custom_fields(self, custom_fields: list[ProfileSettingCustomField]) -> ProfileSettingCustomGroupItemBuilder: ...
    def build(self) -> ProfileSettingCustomGroupItem: ...
