from lark_oapi.core.construct import init as init

class ProfileSettingBankAccount:
    country_region: str | None
    bank_name: str | None
    branch_name: str | None
    account_holder: str | None
    bank_account_number: str | None
    bank_account_usages: list[str] | None
    bank_account_type: str | None
    bank_id: str | None
    branch_id: str | None
    payment_type: str | None
    payment_rate: str | None
    payment_amount: str | None
    priority: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ProfileSettingBankAccountBuilder: ...

class ProfileSettingBankAccountBuilder:
    def __init__(self) -> None: ...
    def country_region(self, country_region: str) -> ProfileSettingBankAccountBuilder: ...
    def bank_name(self, bank_name: str) -> ProfileSettingBankAccountBuilder: ...
    def branch_name(self, branch_name: str) -> ProfileSettingBankAccountBuilder: ...
    def account_holder(self, account_holder: str) -> ProfileSettingBankAccountBuilder: ...
    def bank_account_number(self, bank_account_number: str) -> ProfileSettingBankAccountBuilder: ...
    def bank_account_usages(self, bank_account_usages: list[str]) -> ProfileSettingBankAccountBuilder: ...
    def bank_account_type(self, bank_account_type: str) -> ProfileSettingBankAccountBuilder: ...
    def bank_id(self, bank_id: str) -> ProfileSettingBankAccountBuilder: ...
    def branch_id(self, branch_id: str) -> ProfileSettingBankAccountBuilder: ...
    def payment_type(self, payment_type: str) -> ProfileSettingBankAccountBuilder: ...
    def payment_rate(self, payment_rate: str) -> ProfileSettingBankAccountBuilder: ...
    def payment_amount(self, payment_amount: str) -> ProfileSettingBankAccountBuilder: ...
    def priority(self, priority: str) -> ProfileSettingBankAccountBuilder: ...
    def build(self) -> ProfileSettingBankAccount: ...
