from .profile_setting_custom_field import ProfileSettingCustomField as ProfileSettingCustomField
from lark_oapi.core.construct import init as init

class ProfileSettingResidentTax:
    year_resident_tax: str | None
    tax_country_region: str | None
    resident_status: str | None
    custom_fields: list[ProfileSettingCustomField] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ProfileSettingResidentTaxBuilder: ...

class ProfileSettingResidentTaxBuilder:
    def __init__(self) -> None: ...
    def year_resident_tax(self, year_resident_tax: str) -> ProfileSettingResidentTaxBuilder: ...
    def tax_country_region(self, tax_country_region: str) -> ProfileSettingResidentTaxBuilder: ...
    def resident_status(self, resident_status: str) -> ProfileSettingResidentTaxBuilder: ...
    def custom_fields(self, custom_fields: list[ProfileSettingCustomField]) -> ProfileSettingResidentTaxBuilder: ...
    def build(self) -> ProfileSettingResidentTax: ...
