from .profile_setting_custom_field import ProfileSettingCustomField as ProfileSettingCustomField
from lark_oapi.core.construct import init as init

class ProfileSettingEducation:
    school: str | None
    school_enum: str | None
    start_date: str | None
    end_date: str | None
    level_of_education: str | None
    field_of_study: str | None
    degree: str | None
    field_of_study_enum: str | None
    custom_fields: list[ProfileSettingCustomField] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ProfileSettingEducationBuilder: ...

class ProfileSettingEducationBuilder:
    def __init__(self) -> None: ...
    def school(self, school: str) -> ProfileSettingEducationBuilder: ...
    def school_enum(self, school_enum: str) -> ProfileSettingEducationBuilder: ...
    def start_date(self, start_date: str) -> ProfileSettingEducationBuilder: ...
    def end_date(self, end_date: str) -> ProfileSettingEducationBuilder: ...
    def level_of_education(self, level_of_education: str) -> ProfileSettingEducationBuilder: ...
    def field_of_study(self, field_of_study: str) -> ProfileSettingEducationBuilder: ...
    def degree(self, degree: str) -> ProfileSettingEducationBuilder: ...
    def field_of_study_enum(self, field_of_study_enum: str) -> ProfileSettingEducationBuilder: ...
    def custom_fields(self, custom_fields: list[ProfileSettingCustomField]) -> ProfileSettingEducationBuilder: ...
    def build(self) -> ProfileSettingEducation: ...
