from .profile_setting_custom_field import ProfileSettingCustomField as ProfileSettingCustomField
from .profile_setting_phone import ProfileSettingPhone as ProfileSettingPhone
from lark_oapi.core.construct import init as init

class ProfileSettingEmploymentBasicInfo:
    employee_number: str | None
    rehire: bool | None
    employment_info_before_rehire: str | None
    effective_time: str | None
    regular_employee_start_date: str | None
    seniority_date: str | None
    work_email: str | None
    phone: ProfileSettingPhone | None
    user_geo: str | None
    custom_fields: list[ProfileSettingCustomField] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ProfileSettingEmploymentBasicInfoBuilder: ...

class ProfileSettingEmploymentBasicInfoBuilder:
    def __init__(self) -> None: ...
    def employee_number(self, employee_number: str) -> ProfileSettingEmploymentBasicInfoBuilder: ...
    def rehire(self, rehire: bool) -> ProfileSettingEmploymentBasicInfoBuilder: ...
    def employment_info_before_rehire(self, employment_info_before_rehire: str) -> ProfileSettingEmploymentBasicInfoBuilder: ...
    def effective_time(self, effective_time: str) -> ProfileSettingEmploymentBasicInfoBuilder: ...
    def regular_employee_start_date(self, regular_employee_start_date: str) -> ProfileSettingEmploymentBasicInfoBuilder: ...
    def seniority_date(self, seniority_date: str) -> ProfileSettingEmploymentBasicInfoBuilder: ...
    def work_email(self, work_email: str) -> ProfileSettingEmploymentBasicInfoBuilder: ...
    def phone(self, phone: ProfileSettingPhone) -> ProfileSettingEmploymentBasicInfoBuilder: ...
    def user_geo(self, user_geo: str) -> ProfileSettingEmploymentBasicInfoBuilder: ...
    def custom_fields(self, custom_fields: list[ProfileSettingCustomField]) -> ProfileSettingEmploymentBasicInfoBuilder: ...
    def build(self) -> ProfileSettingEmploymentBasicInfo: ...
