from .profile_setting_custom_field import ProfileSettingCustomField as ProfileSettingCustomField
from .profile_setting_name import ProfileSettingName as ProfileSettingName
from .profile_setting_phone import ProfileSettingPhone as ProfileSettingPhone
from lark_oapi.core.construct import init as init

class ProfileSettingPersonalBasicInfo:
    legal_name: ProfileSettingName | None
    preferred_name: ProfileSettingName | None
    additional_name: str | None
    gender: str | None
    nationality_v2: str | None
    ethnicity_race: str | None
    phone: ProfileSettingPhone | None
    email: str | None
    date_of_birth: str | None
    marital_status: str | None
    is_disabled: bool | None
    disable_card_number: str | None
    is_martyr_family: bool | None
    martyr_card_number: str | None
    is_old_alone: bool | None
    born_country_region: str | None
    political_affiliation: str | None
    native_region: str | None
    date_entered_workforce: str | None
    first_entry_time: str | None
    leave_time: str | None
    custom_fields: list[ProfileSettingCustomField] | None
    additional_nationalities: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ProfileSettingPersonalBasicInfoBuilder: ...

class ProfileSettingPersonalBasicInfoBuilder:
    def __init__(self) -> None: ...
    def legal_name(self, legal_name: ProfileSettingName) -> ProfileSettingPersonalBasicInfoBuilder: ...
    def preferred_name(self, preferred_name: ProfileSettingName) -> ProfileSettingPersonalBasicInfoBuilder: ...
    def additional_name(self, additional_name: str) -> ProfileSettingPersonalBasicInfoBuilder: ...
    def gender(self, gender: str) -> ProfileSettingPersonalBasicInfoBuilder: ...
    def nationality_v2(self, nationality_v2: str) -> ProfileSettingPersonalBasicInfoBuilder: ...
    def ethnicity_race(self, ethnicity_race: str) -> ProfileSettingPersonalBasicInfoBuilder: ...
    def phone(self, phone: ProfileSettingPhone) -> ProfileSettingPersonalBasicInfoBuilder: ...
    def email(self, email: str) -> ProfileSettingPersonalBasicInfoBuilder: ...
    def date_of_birth(self, date_of_birth: str) -> ProfileSettingPersonalBasicInfoBuilder: ...
    def marital_status(self, marital_status: str) -> ProfileSettingPersonalBasicInfoBuilder: ...
    def is_disabled(self, is_disabled: bool) -> ProfileSettingPersonalBasicInfoBuilder: ...
    def disable_card_number(self, disable_card_number: str) -> ProfileSettingPersonalBasicInfoBuilder: ...
    def is_martyr_family(self, is_martyr_family: bool) -> ProfileSettingPersonalBasicInfoBuilder: ...
    def martyr_card_number(self, martyr_card_number: str) -> ProfileSettingPersonalBasicInfoBuilder: ...
    def is_old_alone(self, is_old_alone: bool) -> ProfileSettingPersonalBasicInfoBuilder: ...
    def born_country_region(self, born_country_region: str) -> ProfileSettingPersonalBasicInfoBuilder: ...
    def political_affiliation(self, political_affiliation: str) -> ProfileSettingPersonalBasicInfoBuilder: ...
    def native_region(self, native_region: str) -> ProfileSettingPersonalBasicInfoBuilder: ...
    def date_entered_workforce(self, date_entered_workforce: str) -> ProfileSettingPersonalBasicInfoBuilder: ...
    def first_entry_time(self, first_entry_time: str) -> ProfileSettingPersonalBasicInfoBuilder: ...
    def leave_time(self, leave_time: str) -> ProfileSettingPersonalBasicInfoBuilder: ...
    def custom_fields(self, custom_fields: list[ProfileSettingCustomField]) -> ProfileSettingPersonalBasicInfoBuilder: ...
    def additional_nationalities(self, additional_nationalities: list[str]) -> ProfileSettingPersonalBasicInfoBuilder: ...
    def build(self) -> ProfileSettingPersonalBasicInfo: ...
