from .profile_setting_custom_field import ProfileSettingCustomField as ProfileSettingCustomField
from lark_oapi.core.construct import init as init

class ProfileSettingNational:
    country_region: str | None
    national_id_type: str | None
    national_id_number: str | None
    issued_date: str | None
    issued_by: str | None
    expiration_date: str | None
    custom_fields: list[ProfileSettingCustomField] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ProfileSettingNationalBuilder: ...

class ProfileSettingNationalBuilder:
    def __init__(self) -> None: ...
    def country_region(self, country_region: str) -> ProfileSettingNationalBuilder: ...
    def national_id_type(self, national_id_type: str) -> ProfileSettingNationalBuilder: ...
    def national_id_number(self, national_id_number: str) -> ProfileSettingNationalBuilder: ...
    def issued_date(self, issued_date: str) -> ProfileSettingNationalBuilder: ...
    def issued_by(self, issued_by: str) -> ProfileSettingNationalBuilder: ...
    def expiration_date(self, expiration_date: str) -> ProfileSettingNationalBuilder: ...
    def custom_fields(self, custom_fields: list[ProfileSettingCustomField]) -> ProfileSettingNationalBuilder: ...
    def build(self) -> ProfileSettingNational: ...
