from lark_oapi.core.construct import init as init

class ProfileSettingCostCenter:
    id: str | None
    rate: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ProfileSettingCostCenterBuilder: ...

class ProfileSettingCostCenterBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> ProfileSettingCostCenterBuilder: ...
    def rate(self, rate: int) -> ProfileSettingCostCenterBuilder: ...
    def build(self) -> ProfileSettingCostCenter: ...
