from .profile_setting_custom_group import ProfileSettingCustomGroup as ProfileSettingCustomGroup
from .profile_setting_personal_record import ProfileSettingPersonalRecord as ProfileSettingPersonalRecord
from lark_oapi.core.construct import init as init

class ProfileSettingDataAttachment:
    personal_records: list[ProfileSettingPersonalRecord] | None
    custom_groups: list[ProfileSettingCustomGroup] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ProfileSettingDataAttachmentBuilder: ...

class ProfileSettingDataAttachmentBuilder:
    def __init__(self) -> None: ...
    def personal_records(self, personal_records: list[ProfileSettingPersonalRecord]) -> ProfileSettingDataAttachmentBuilder: ...
    def custom_groups(self, custom_groups: list[ProfileSettingCustomGroup]) -> ProfileSettingDataAttachmentBuilder: ...
    def build(self) -> ProfileSettingDataAttachment: ...
