from lark_oapi.core.construct import init as init

class ProfileSettingCitizenshipStatus:
    country_region: str | None
    citizenship_status: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ProfileSettingCitizenshipStatusBuilder: ...

class ProfileSettingCitizenshipStatusBuilder:
    def __init__(self) -> None: ...
    def country_region(self, country_region: str) -> ProfileSettingCitizenshipStatusBuilder: ...
    def citizenship_status(self, citizenship_status: str) -> ProfileSettingCitizenshipStatusBuilder: ...
    def build(self) -> ProfileSettingCitizenshipStatus: ...
