from .qr_code_dimension import QrCodeDimension as QrCodeDimension
from .qr_code_value import QrCodeValue as QrCodeValue
from lark_oapi.core.construct import init as init

class QrCodeDimensionValue:
    dimension: QrCodeDimension | None
    value: QrCodeValue | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QrCodeDimensionValueBuilder: ...

class QrCodeDimensionValueBuilder:
    def __init__(self) -> None: ...
    def dimension(self, dimension: QrCodeDimension) -> QrCodeDimensionValueBuilder: ...
    def value(self, value: QrCodeValue) -> QrCodeDimensionValueBuilder: ...
    def build(self) -> QrCodeDimensionValue: ...
