from .i18n_v2 import I18nV2 as I18nV2
from lark_oapi.core.construct import init as init

class QrCodeDimension:
    api_name: str | None
    display_name: I18nV2 | None
    type: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QrCodeDimensionBuilder: ...

class QrCodeDimensionBuilder:
    def __init__(self) -> None: ...
    def api_name(self, api_name: str) -> QrCodeDimensionBuilder: ...
    def display_name(self, display_name: I18nV2) -> QrCodeDimensionBuilder: ...
    def type(self, type: int) -> QrCodeDimensionBuilder: ...
    def build(self) -> QrCodeDimension: ...
