from lark_oapi.core.construct import init as init

class QueryRecentChangeDepartmentRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryRecentChangeDepartmentRequestBodyBuilder: ...

class QueryRecentChangeDepartmentRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> QueryRecentChangeDepartmentRequestBody: ...
