from .job_grade import JobGrade as JobGrade
from lark_oapi.core.construct import init as init

class QueryJobGradeResponseBody:
    items: list[JobGrade] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryJobGradeResponseBodyBuilder: ...

class QueryJobGradeResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[JobGrade]) -> QueryJobGradeResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> QueryJobGradeResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> QueryJobGradeResponseBodyBuilder: ...
    def build(self) -> QueryJobGradeResponseBody: ...
