from lark_oapi.core.construct import init as init

class QueryRecentChangeJobLevelRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryRecentChangeJobLevelRequestBodyBuilder: ...

class QueryRecentChangeJobLevelRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> QueryRecentChangeJobLevelRequestBody: ...
