from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class QueryRecentChangeJobFamilyRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    start_date: str | None
    end_date: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> QueryRecentChangeJobFamilyRequestBuilder: ...

class QueryRecentChangeJobFamilyRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> QueryRecentChangeJobFamilyRequestBuilder: ...
    def page_token(self, page_token: str) -> QueryRecentChangeJobFamilyRequestBuilder: ...
    def start_date(self, start_date: str) -> QueryRecentChangeJobFamilyRequestBuilder: ...
    def end_date(self, end_date: str) -> QueryRecentChangeJobFamilyRequestBuilder: ...
    def build(self) -> QueryRecentChangeJobFamilyRequest: ...
