from .query_job_grade_request_body import QueryJobGradeRequestBody as QueryJobGradeRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class QueryJobGradeRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    request_body: QueryJobGradeRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> QueryJobGradeRequestBuilder: ...

class QueryJobGradeRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> QueryJobGradeRequestBuilder: ...
    def page_token(self, page_token: str) -> QueryJobGradeRequestBuilder: ...
    def request_body(self, request_body: QueryJobGradeRequestBody) -> QueryJobGradeRequestBuilder: ...
    def build(self) -> QueryJobGradeRequest: ...
