from lark_oapi.core.construct import init as init

class QueryRecentChangeLocationRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryRecentChangeLocationRequestBodyBuilder: ...

class QueryRecentChangeLocationRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> QueryRecentChangeLocationRequestBody: ...
