from lark_oapi.core.construct import init as init

class QueryRecentChangeCustomOrgResponseBody:
    custom_org_ids: list[str] | None
    page_token: str | None
    has_more: bool | None
    deleted_custom_org_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryRecentChangeCustomOrgResponseBodyBuilder: ...

class QueryRecentChangeCustomOrgResponseBodyBuilder:
    def __init__(self) -> None: ...
    def custom_org_ids(self, custom_org_ids: list[str]) -> QueryRecentChangeCustomOrgResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> QueryRecentChangeCustomOrgResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> QueryRecentChangeCustomOrgResponseBodyBuilder: ...
    def deleted_custom_org_ids(self, deleted_custom_org_ids: list[str]) -> QueryRecentChangeCustomOrgResponseBodyBuilder: ...
    def build(self) -> QueryRecentChangeCustomOrgResponseBody: ...
