from .query_employees_job_data_request_body import QueryEmployeesJobDataRequestBody as QueryEmployeesJobDataRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class QueryEmployeesJobDataRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    user_id_type: str | None
    department_id_type: str | None
    request_body: QueryEmployeesJobDataRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> QueryEmployeesJobDataRequestBuilder: ...

class QueryEmployeesJobDataRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> QueryEmployeesJobDataRequestBuilder: ...
    def page_token(self, page_token: str) -> QueryEmployeesJobDataRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> QueryEmployeesJobDataRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> QueryEmployeesJobDataRequestBuilder: ...
    def request_body(self, request_body: QueryEmployeesJobDataRequestBody) -> QueryEmployeesJobDataRequestBuilder: ...
    def build(self) -> QueryEmployeesJobDataRequest: ...
