from lark_oapi.core.construct import init as init

class QueryPreHireRequestBody:
    pre_hire_ids: list[str] | None
    fields: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryPreHireRequestBodyBuilder: ...

class QueryPreHireRequestBodyBuilder:
    def __init__(self) -> None: ...
    def pre_hire_ids(self, pre_hire_ids: list[str]) -> QueryPreHireRequestBodyBuilder: ...
    def fields(self, fields: list[str]) -> QueryPreHireRequestBodyBuilder: ...
    def build(self) -> QueryPreHireRequestBody: ...
