from .query_operation_logs_department_request_body import QueryOperationLogsDepartmentRequestBody as QueryOperationLogsDepartmentRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class QueryOperationLogsDepartmentRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    department_id_type: str | None
    request_body: QueryOperationLogsDepartmentRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> QueryOperationLogsDepartmentRequestBuilder: ...

class QueryOperationLogsDepartmentRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> QueryOperationLogsDepartmentRequestBuilder: ...
    def page_token(self, page_token: str) -> QueryOperationLogsDepartmentRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> QueryOperationLogsDepartmentRequestBuilder: ...
    def request_body(self, request_body: QueryOperationLogsDepartmentRequestBody) -> QueryOperationLogsDepartmentRequestBuilder: ...
    def build(self) -> QueryOperationLogsDepartmentRequest: ...
