from lark_oapi.core.construct import init as init

class QueryRecentChangeDepartmentResponseBody:
    department_ids: list[str] | None
    deleted_department_ids: list[str] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryRecentChangeDepartmentResponseBodyBuilder: ...

class QueryRecentChangeDepartmentResponseBodyBuilder:
    def __init__(self) -> None: ...
    def department_ids(self, department_ids: list[str]) -> QueryRecentChangeDepartmentResponseBodyBuilder: ...
    def deleted_department_ids(self, deleted_department_ids: list[str]) -> QueryRecentChangeDepartmentResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> QueryRecentChangeDepartmentResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> QueryRecentChangeDepartmentResponseBodyBuilder: ...
    def build(self) -> QueryRecentChangeDepartmentResponseBody: ...
