from lark_oapi.core.construct import init as init

class QueryRecentChangeJobGradeResponseBody:
    job_grade_ids: list[str] | None
    page_token: str | None
    has_more: bool | None
    deleted_job_grade_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryRecentChangeJobGradeResponseBodyBuilder: ...

class QueryRecentChangeJobGradeResponseBodyBuilder:
    def __init__(self) -> None: ...
    def job_grade_ids(self, job_grade_ids: list[str]) -> QueryRecentChangeJobGradeResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> QueryRecentChangeJobGradeResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> QueryRecentChangeJobGradeResponseBodyBuilder: ...
    def deleted_job_grade_ids(self, deleted_job_grade_ids: list[str]) -> QueryRecentChangeJobGradeResponseBodyBuilder: ...
    def build(self) -> QueryRecentChangeJobGradeResponseBody: ...
