from .custom_org import CustomOrg as CustomOrg
from lark_oapi.core.construct import init as init

class QueryCustomOrgResponseBody:
    items: list[CustomOrg] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryCustomOrgResponseBodyBuilder: ...

class QueryCustomOrgResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[CustomOrg]) -> QueryCustomOrgResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> QueryCustomOrgResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> QueryCustomOrgResponseBodyBuilder: ...
    def build(self) -> QueryCustomOrgResponseBody: ...
