from lark_oapi.core.construct import init as init

class QueryRecentChangeJobFamilyRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryRecentChangeJobFamilyRequestBodyBuilder: ...

class QueryRecentChangeJobFamilyRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> QueryRecentChangeJobFamilyRequestBody: ...
