from .remove_version_default_cost_center_request_body import RemoveVersionDefaultCostCenterRequestBody as RemoveVersionDefaultCostCenterRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class RemoveVersionDefaultCostCenterRequest(BaseRequest):
    client_token: str | None
    user_id_type: str | None
    request_body: RemoveVersionDefaultCostCenterRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> RemoveVersionDefaultCostCenterRequestBuilder: ...

class RemoveVersionDefaultCostCenterRequestBuilder:
    def __init__(self) -> None: ...
    def client_token(self, client_token: str) -> RemoveVersionDefaultCostCenterRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> RemoveVersionDefaultCostCenterRequestBuilder: ...
    def request_body(self, request_body: RemoveVersionDefaultCostCenterRequestBody) -> RemoveVersionDefaultCostCenterRequestBuilder: ...
    def build(self) -> RemoveVersionDefaultCostCenterRequest: ...
