from lark_oapi.core.construct import init as init

class RestoreFlowInstancePreHireResponseBody:
    success: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RestoreFlowInstancePreHireResponseBodyBuilder: ...

class RestoreFlowInstancePreHireResponseBodyBuilder:
    def __init__(self) -> None: ...
    def success(self, success: bool) -> RestoreFlowInstancePreHireResponseBodyBuilder: ...
    def build(self) -> RestoreFlowInstancePreHireResponseBody: ...
