from .revoke_job_change_request_body import RevokeJobChangeRequestBody as RevokeJobChangeRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class RevokeJobChangeRequest(BaseRequest):
    user_id_type: str | None
    job_change_id: str | None
    request_body: RevokeJobChangeRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> RevokeJobChangeRequestBuilder: ...

class RevokeJobChangeRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> RevokeJobChangeRequestBuilder: ...
    def job_change_id(self, job_change_id: str) -> RevokeJobChangeRequestBuilder: ...
    def request_body(self, request_body: RevokeJobChangeRequestBody) -> RevokeJobChangeRequestBuilder: ...
    def build(self) -> RevokeJobChangeRequest: ...
