from .revoke_offboarding_request_body import RevokeOffboardingRequestBody as RevokeOffboardingRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class RevokeOffboardingRequest(BaseRequest):
    user_id_type: str | None
    request_body: RevokeOffboardingRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> RevokeOffboardingRequestBuilder: ...

class RevokeOffboardingRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> RevokeOffboardingRequestBuilder: ...
    def request_body(self, request_body: RevokeOffboardingRequestBody) -> RevokeOffboardingRequestBuilder: ...
    def build(self) -> RevokeOffboardingRequest: ...
