from lark_oapi.core.construct import init as init

class RevokeOffboardingRequestBody:
    offboarding_id: str | None
    operator_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RevokeOffboardingRequestBodyBuilder: ...

class RevokeOffboardingRequestBodyBuilder:
    def __init__(self) -> None: ...
    def offboarding_id(self, offboarding_id: str) -> RevokeOffboardingRequestBodyBuilder: ...
    def operator_id(self, operator_id: str) -> RevokeOffboardingRequestBodyBuilder: ...
    def build(self) -> RevokeOffboardingRequestBody: ...
