from .country_region import CountryRegion as CountryRegion
from lark_oapi.core.construct import init as init

class SearchBasicInfoCountryRegionResponseBody:
    items: list[CountryRegion] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SearchBasicInfoCountryRegionResponseBodyBuilder: ...

class SearchBasicInfoCountryRegionResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[CountryRegion]) -> SearchBasicInfoCountryRegionResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> SearchBasicInfoCountryRegionResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> SearchBasicInfoCountryRegionResponseBodyBuilder: ...
    def build(self) -> SearchBasicInfoCountryRegionResponseBody: ...
