from lark_oapi.core.construct import init as init

class SearchBasicInfoCountryRegionRequestBody:
    country_region_id_list: list[str] | None
    status_list: list[int] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SearchBasicInfoCountryRegionRequestBodyBuilder: ...

class SearchBasicInfoCountryRegionRequestBodyBuilder:
    def __init__(self) -> None: ...
    def country_region_id_list(self, country_region_id_list: list[str]) -> SearchBasicInfoCountryRegionRequestBodyBuilder: ...
    def status_list(self, status_list: list[int]) -> SearchBasicInfoCountryRegionRequestBodyBuilder: ...
    def build(self) -> SearchBasicInfoCountryRegionRequestBody: ...
