from .bank import Bank as Bank
from lark_oapi.core.construct import init as init

class SearchBasicInfoBankResponseBody:
    items: list[Bank] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SearchBasicInfoBankResponseBodyBuilder: ...

class SearchBasicInfoBankResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[Bank]) -> SearchBasicInfoBankResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> SearchBasicInfoBankResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> SearchBasicInfoBankResponseBodyBuilder: ...
    def build(self) -> SearchBasicInfoBankResponseBody: ...
