from .search_basic_info_currency_request_body import SearchBasicInfoCurrencyRequestBody as SearchBasicInfoCurrencyRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class SearchBasicInfoCurrencyRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    request_body: SearchBasicInfoCurrencyRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> SearchBasicInfoCurrencyRequestBuilder: ...

class SearchBasicInfoCurrencyRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> SearchBasicInfoCurrencyRequestBuilder: ...
    def page_token(self, page_token: str) -> SearchBasicInfoCurrencyRequestBuilder: ...
    def request_body(self, request_body: SearchBasicInfoCurrencyRequestBody) -> SearchBasicInfoCurrencyRequestBuilder: ...
    def build(self) -> SearchBasicInfoCurrencyRequest: ...
