from .search_basic_info_nationality_request_body import SearchBasicInfoNationalityRequestBody as SearchBasicInfoNationalityRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class SearchBasicInfoNationalityRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    request_body: SearchBasicInfoNationalityRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> SearchBasicInfoNationalityRequestBuilder: ...

class SearchBasicInfoNationalityRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> SearchBasicInfoNationalityRequestBuilder: ...
    def page_token(self, page_token: str) -> SearchBasicInfoNationalityRequestBuilder: ...
    def request_body(self, request_body: SearchBasicInfoNationalityRequestBody) -> SearchBasicInfoNationalityRequestBuilder: ...
    def build(self) -> SearchBasicInfoNationalityRequest: ...
