from lark_oapi.core.construct import init as init

class SearchBasicInfoNationalityRequestBody:
    nationality_id_list: list[str] | None
    country_region_id_list: list[str] | None
    status_list: list[int] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SearchBasicInfoNationalityRequestBodyBuilder: ...

class SearchBasicInfoNationalityRequestBodyBuilder:
    def __init__(self) -> None: ...
    def nationality_id_list(self, nationality_id_list: list[str]) -> SearchBasicInfoNationalityRequestBodyBuilder: ...
    def country_region_id_list(self, country_region_id_list: list[str]) -> SearchBasicInfoNationalityRequestBodyBuilder: ...
    def status_list(self, status_list: list[int]) -> SearchBasicInfoNationalityRequestBodyBuilder: ...
    def build(self) -> SearchBasicInfoNationalityRequestBody: ...
