from .search_basic_info_country_region_subdivision_request_body import SearchBasicInfoCountryRegionSubdivisionRequestBody as SearchBasicInfoCountryRegionSubdivisionRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class SearchBasicInfoCountryRegionSubdivisionRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    request_body: SearchBasicInfoCountryRegionSubdivisionRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> SearchBasicInfoCountryRegionSubdivisionRequestBuilder: ...

class SearchBasicInfoCountryRegionSubdivisionRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> SearchBasicInfoCountryRegionSubdivisionRequestBuilder: ...
    def page_token(self, page_token: str) -> SearchBasicInfoCountryRegionSubdivisionRequestBuilder: ...
    def request_body(self, request_body: SearchBasicInfoCountryRegionSubdivisionRequestBody) -> SearchBasicInfoCountryRegionSubdivisionRequestBuilder: ...
    def build(self) -> SearchBasicInfoCountryRegionSubdivisionRequest: ...
