from .search_probation_request_body import SearchProbationRequestBody as SearchProbationRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class SearchProbationRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    user_id_type: str | None
    department_id_type: str | None
    request_body: SearchProbationRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> SearchProbationRequestBuilder: ...

class SearchProbationRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> SearchProbationRequestBuilder: ...
    def page_token(self, page_token: str) -> SearchProbationRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> SearchProbationRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> SearchProbationRequestBuilder: ...
    def request_body(self, request_body: SearchProbationRequestBody) -> SearchProbationRequestBuilder: ...
    def build(self) -> SearchProbationRequest: ...
