from lark_oapi.core.construct import init as init

class SearchBasicInfoCityRequestBody:
    country_region_subdivision_id_list: list[str] | None
    city_id_list: list[str] | None
    status_list: list[int] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SearchBasicInfoCityRequestBodyBuilder: ...

class SearchBasicInfoCityRequestBodyBuilder:
    def __init__(self) -> None: ...
    def country_region_subdivision_id_list(self, country_region_subdivision_id_list: list[str]) -> SearchBasicInfoCityRequestBodyBuilder: ...
    def city_id_list(self, city_id_list: list[str]) -> SearchBasicInfoCityRequestBodyBuilder: ...
    def status_list(self, status_list: list[int]) -> SearchBasicInfoCityRequestBodyBuilder: ...
    def build(self) -> SearchBasicInfoCityRequestBody: ...
