from .search_basic_info_district_request_body import SearchBasicInfoDistrictRequestBody as SearchBasicInfoDistrictRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class SearchBasicInfoDistrictRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    request_body: SearchBasicInfoDistrictRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> SearchBasicInfoDistrictRequestBuilder: ...

class SearchBasicInfoDistrictRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> SearchBasicInfoDistrictRequestBuilder: ...
    def page_token(self, page_token: str) -> SearchBasicInfoDistrictRequestBuilder: ...
    def request_body(self, request_body: SearchBasicInfoDistrictRequestBody) -> SearchBasicInfoDistrictRequestBuilder: ...
    def build(self) -> SearchBasicInfoDistrictRequest: ...
