from .search_employee_request_body import SearchEmployeeRequestBody as SearchEmployeeRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class SearchEmployeeRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    user_id_type: str | None
    department_id_type: str | None
    request_body: SearchEmployeeRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> SearchEmployeeRequestBuilder: ...

class SearchEmployeeRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> SearchEmployeeRequestBuilder: ...
    def page_token(self, page_token: str) -> SearchEmployeeRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> SearchEmployeeRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> SearchEmployeeRequestBuilder: ...
    def request_body(self, request_body: SearchEmployeeRequestBody) -> SearchEmployeeRequestBuilder: ...
    def build(self) -> SearchEmployeeRequest: ...
