from lark_oapi.core.construct import init as init

class SearchJobChangeRequestBody:
    employment_ids: list[str] | None
    job_change_ids: list[str] | None
    statuses: list[str] | None
    effective_date_start: str | None
    effective_date_end: str | None
    updated_time_start: str | None
    updated_time_end: str | None
    target_department_ids: list[str] | None
    transfer_type_unique_identifier: list[str] | None
    transfer_reason_unique_identifier: list[str] | None
    exception_statuses: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SearchJobChangeRequestBodyBuilder: ...

class SearchJobChangeRequestBodyBuilder:
    def __init__(self) -> None: ...
    def employment_ids(self, employment_ids: list[str]) -> SearchJobChangeRequestBodyBuilder: ...
    def job_change_ids(self, job_change_ids: list[str]) -> SearchJobChangeRequestBodyBuilder: ...
    def statuses(self, statuses: list[str]) -> SearchJobChangeRequestBodyBuilder: ...
    def effective_date_start(self, effective_date_start: str) -> SearchJobChangeRequestBodyBuilder: ...
    def effective_date_end(self, effective_date_end: str) -> SearchJobChangeRequestBodyBuilder: ...
    def updated_time_start(self, updated_time_start: str) -> SearchJobChangeRequestBodyBuilder: ...
    def updated_time_end(self, updated_time_end: str) -> SearchJobChangeRequestBodyBuilder: ...
    def target_department_ids(self, target_department_ids: list[str]) -> SearchJobChangeRequestBodyBuilder: ...
    def transfer_type_unique_identifier(self, transfer_type_unique_identifier: list[str]) -> SearchJobChangeRequestBodyBuilder: ...
    def transfer_reason_unique_identifier(self, transfer_reason_unique_identifier: list[str]) -> SearchJobChangeRequestBodyBuilder: ...
    def exception_statuses(self, exception_statuses: list[str]) -> SearchJobChangeRequestBodyBuilder: ...
    def build(self) -> SearchJobChangeRequestBody: ...
