from .language import Language as Language
from lark_oapi.core.construct import init as init

class SearchBasicInfoLanguageResponseBody:
    items: list[Language] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SearchBasicInfoLanguageResponseBodyBuilder: ...

class SearchBasicInfoLanguageResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[Language]) -> SearchBasicInfoLanguageResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> SearchBasicInfoLanguageResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> SearchBasicInfoLanguageResponseBodyBuilder: ...
    def build(self) -> SearchBasicInfoLanguageResponseBody: ...
