from .search_basic_info_bank_branch_request_body import SearchBasicInfoBankBranchRequestBody as SearchBasicInfoBankBranchRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class SearchBasicInfoBankBranchRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    request_body: SearchBasicInfoBankBranchRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> SearchBasicInfoBankBranchRequestBuilder: ...

class SearchBasicInfoBankBranchRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> SearchBasicInfoBankBranchRequestBuilder: ...
    def page_token(self, page_token: str) -> SearchBasicInfoBankBranchRequestBuilder: ...
    def request_body(self, request_body: SearchBasicInfoBankBranchRequestBody) -> SearchBasicInfoBankBranchRequestBuilder: ...
    def build(self) -> SearchBasicInfoBankBranchRequest: ...
