from .profile_setting_custom_field import ProfileSettingCustomField as ProfileSettingCustomField
from lark_oapi.core.construct import init as init

class SeniorityAdjustInformationEdit:
    seniority_adjustment_type: str | None
    start_date: str | None
    end_date: str | None
    reasons_for_seniority_adjustment: str | None
    seniority_adjustment: float | None
    custom_fields: list[ProfileSettingCustomField] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SeniorityAdjustInformationEditBuilder: ...

class SeniorityAdjustInformationEditBuilder:
    def __init__(self) -> None: ...
    def seniority_adjustment_type(self, seniority_adjustment_type: str) -> SeniorityAdjustInformationEditBuilder: ...
    def start_date(self, start_date: str) -> SeniorityAdjustInformationEditBuilder: ...
    def end_date(self, end_date: str) -> SeniorityAdjustInformationEditBuilder: ...
    def reasons_for_seniority_adjustment(self, reasons_for_seniority_adjustment: str) -> SeniorityAdjustInformationEditBuilder: ...
    def seniority_adjustment(self, seniority_adjustment: float) -> SeniorityAdjustInformationEditBuilder: ...
    def custom_fields(self, custom_fields: list[ProfileSettingCustomField]) -> SeniorityAdjustInformationEditBuilder: ...
    def build(self) -> SeniorityAdjustInformationEdit: ...
