from .signature_enum_info_label import SignatureEnumInfoLabel as SignatureEnumInfoLabel
from lark_oapi.core.construct import init as init

class SignatureEnumInfo:
    label: SignatureEnumInfoLabel | None
    apiname: str | None
    active: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SignatureEnumInfoBuilder: ...

class SignatureEnumInfoBuilder:
    def __init__(self) -> None: ...
    def label(self, label: SignatureEnumInfoLabel) -> SignatureEnumInfoBuilder: ...
    def apiname(self, apiname: str) -> SignatureEnumInfoBuilder: ...
    def active(self, active: bool) -> SignatureEnumInfoBuilder: ...
    def build(self) -> SignatureEnumInfo: ...
