from .signature_template_brief_info import SignatureTemplateBriefInfo as SignatureTemplateBriefInfo
from .signature_template_content_info import SignatureTemplateContentInfo as SignatureTemplateContentInfo
from lark_oapi.core.construct import init as init

class SignatureTemplateInfo:
    id: str | None
    brief_info: SignatureTemplateBriefInfo | None
    content_info: SignatureTemplateContentInfo | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SignatureTemplateInfoBuilder: ...

class SignatureTemplateInfoBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> SignatureTemplateInfoBuilder: ...
    def brief_info(self, brief_info: SignatureTemplateBriefInfo) -> SignatureTemplateInfoBuilder: ...
    def content_info(self, content_info: SignatureTemplateContentInfo) -> SignatureTemplateInfoBuilder: ...
    def build(self) -> SignatureTemplateInfo: ...
