from .enum import Enum as Enum
from lark_oapi.core.construct import init as init

class SignatureTemplateCombinationFieldInfoV2:
    total_apiname: str | None
    apiname: str | None
    source: Enum | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SignatureTemplateCombinationFieldInfoV2Builder: ...

class SignatureTemplateCombinationFieldInfoV2Builder:
    def __init__(self) -> None: ...
    def total_apiname(self, total_apiname: str) -> SignatureTemplateCombinationFieldInfoV2Builder: ...
    def apiname(self, apiname: str) -> SignatureTemplateCombinationFieldInfoV2Builder: ...
    def source(self, source: Enum) -> SignatureTemplateCombinationFieldInfoV2Builder: ...
    def build(self) -> SignatureTemplateCombinationFieldInfoV2: ...
