from .enum import Enum as Enum
from .i18n import I18n as I18n
from .signature_template_common_field_info import SignatureTemplateCommonFieldInfo as SignatureTemplateCommonFieldInfo
from lark_oapi.core.construct import init as init

class SignatureTemplateCustomField:
    label: list[I18n] | None
    apiname: str | None
    custom_field_type: Enum | None
    used: bool | None
    is_required: bool | None
    custom_desc: str | None
    common_info: SignatureTemplateCommonFieldInfo | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SignatureTemplateCustomFieldBuilder: ...

class SignatureTemplateCustomFieldBuilder:
    def __init__(self) -> None: ...
    def label(self, label: list[I18n]) -> SignatureTemplateCustomFieldBuilder: ...
    def apiname(self, apiname: str) -> SignatureTemplateCustomFieldBuilder: ...
    def custom_field_type(self, custom_field_type: Enum) -> SignatureTemplateCustomFieldBuilder: ...
    def used(self, used: bool) -> SignatureTemplateCustomFieldBuilder: ...
    def is_required(self, is_required: bool) -> SignatureTemplateCustomFieldBuilder: ...
    def custom_desc(self, custom_desc: str) -> SignatureTemplateCustomFieldBuilder: ...
    def common_info(self, common_info: SignatureTemplateCommonFieldInfo) -> SignatureTemplateCustomFieldBuilder: ...
    def build(self) -> SignatureTemplateCustomField: ...
