from lark_oapi.core.construct import init as init

class SignatureUserInfo:
    id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SignatureUserInfoBuilder: ...

class SignatureUserInfoBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> SignatureUserInfoBuilder: ...
    def build(self) -> SignatureUserInfo: ...
