from .signature_custom_field_value import SignatureCustomFieldValue as SignatureCustomFieldValue
from lark_oapi.core.construct import init as init

class SignatureCustomFieldV2:
    key: str | None
    value: SignatureCustomFieldValue | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SignatureCustomFieldV2Builder: ...

class SignatureCustomFieldV2Builder:
    def __init__(self) -> None: ...
    def key(self, key: str) -> SignatureCustomFieldV2Builder: ...
    def value(self, value: SignatureCustomFieldValue) -> SignatureCustomFieldV2Builder: ...
    def build(self) -> SignatureCustomFieldV2: ...
