from .enum import Enum as Enum
from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class SignatureFile:
    signature_file_id: str | None
    names: list[I18n] | None
    create_time: str | None
    update_time: str | None
    employment_id: str | None
    pre_hire_id: str | None
    signature_file_state: Enum | None
    contract_code: str | None
    effective_date: str | None
    template_id: str | None
    sign_url: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SignatureFileBuilder: ...

class SignatureFileBuilder:
    def __init__(self) -> None: ...
    def signature_file_id(self, signature_file_id: str) -> SignatureFileBuilder: ...
    def names(self, names: list[I18n]) -> SignatureFileBuilder: ...
    def create_time(self, create_time: str) -> SignatureFileBuilder: ...
    def update_time(self, update_time: str) -> SignatureFileBuilder: ...
    def employment_id(self, employment_id: str) -> SignatureFileBuilder: ...
    def pre_hire_id(self, pre_hire_id: str) -> SignatureFileBuilder: ...
    def signature_file_state(self, signature_file_state: Enum) -> SignatureFileBuilder: ...
    def contract_code(self, contract_code: str) -> SignatureFileBuilder: ...
    def effective_date(self, effective_date: str) -> SignatureFileBuilder: ...
    def template_id(self, template_id: str) -> SignatureFileBuilder: ...
    def sign_url(self, sign_url: str) -> SignatureFileBuilder: ...
    def build(self) -> SignatureFile: ...
