from lark_oapi.core.construct import init as init

class SignatureTemplateAttachmentInfo:
    id: str | None
    name: str | None
    size: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SignatureTemplateAttachmentInfoBuilder: ...

class SignatureTemplateAttachmentInfoBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> SignatureTemplateAttachmentInfoBuilder: ...
    def name(self, name: str) -> SignatureTemplateAttachmentInfoBuilder: ...
    def size(self, size: int) -> SignatureTemplateAttachmentInfoBuilder: ...
    def build(self) -> SignatureTemplateAttachmentInfo: ...
