from lark_oapi.core.construct import init as init

class SignatureCustomFieldValueMultilingualValue:
    zh: str | None
    en: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SignatureCustomFieldValueMultilingualValueBuilder: ...

class SignatureCustomFieldValueMultilingualValueBuilder:
    def __init__(self) -> None: ...
    def zh(self, zh: str) -> SignatureCustomFieldValueMultilingualValueBuilder: ...
    def en(self, en: str) -> SignatureCustomFieldValueMultilingualValueBuilder: ...
    def build(self) -> SignatureCustomFieldValueMultilingualValue: ...
