from lark_oapi.core.construct import init as init

class SignatureTemplateSetting:
    page_seal_types: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SignatureTemplateSettingBuilder: ...

class SignatureTemplateSettingBuilder:
    def __init__(self) -> None: ...
    def page_seal_types(self, page_seal_types: list[str]) -> SignatureTemplateSettingBuilder: ...
    def build(self) -> SignatureTemplateSetting: ...
