from .signature_template_common_field_info import SignatureTemplateCommonFieldInfo as SignatureTemplateCommonFieldInfo
from .signature_template_content_item import SignatureTemplateContentItem as SignatureTemplateContentItem
from .signature_template_custom_field import SignatureTemplateCustomField as SignatureTemplateCustomField
from .signature_template_field import SignatureTemplateField as SignatureTemplateField
from .signature_template_filter import SignatureTemplateFilter as SignatureTemplateFilter
from lark_oapi.core.construct import init as init

class SignatureTemplateContentInfo:
    contents: list[SignatureTemplateContentItem] | None
    custom_fields: list[SignatureTemplateCustomField] | None
    filter_fields: list[SignatureTemplateFilter] | None
    using_fields: list[SignatureTemplateCommonFieldInfo] | None
    system_setting_fields: list[SignatureTemplateField] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SignatureTemplateContentInfoBuilder: ...

class SignatureTemplateContentInfoBuilder:
    def __init__(self) -> None: ...
    def contents(self, contents: list[SignatureTemplateContentItem]) -> SignatureTemplateContentInfoBuilder: ...
    def custom_fields(self, custom_fields: list[SignatureTemplateCustomField]) -> SignatureTemplateContentInfoBuilder: ...
    def filter_fields(self, filter_fields: list[SignatureTemplateFilter]) -> SignatureTemplateContentInfoBuilder: ...
    def using_fields(self, using_fields: list[SignatureTemplateCommonFieldInfo]) -> SignatureTemplateContentInfoBuilder: ...
    def system_setting_fields(self, system_setting_fields: list[SignatureTemplateField]) -> SignatureTemplateContentInfoBuilder: ...
    def build(self) -> SignatureTemplateContentInfo: ...
