from .enum import Enum as Enum
from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class SignatureSignatoryLabel:
    template_signatory_type: Enum | None
    label: list[I18n] | None
    apiname: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SignatureSignatoryLabelBuilder: ...

class SignatureSignatoryLabelBuilder:
    def __init__(self) -> None: ...
    def template_signatory_type(self, template_signatory_type: Enum) -> SignatureSignatoryLabelBuilder: ...
    def label(self, label: list[I18n]) -> SignatureSignatoryLabelBuilder: ...
    def apiname(self, apiname: str) -> SignatureSignatoryLabelBuilder: ...
    def build(self) -> SignatureSignatoryLabel: ...
