from .enum import Enum as Enum
from lark_oapi.core.construct import init as init

class SignatureHumanInfo:
    employee_id: str | None
    pre_hire_id: str | None
    user_id_type: str | None
    human_type: Enum | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SignatureHumanInfoBuilder: ...

class SignatureHumanInfoBuilder:
    def __init__(self) -> None: ...
    def employee_id(self, employee_id: str) -> SignatureHumanInfoBuilder: ...
    def pre_hire_id(self, pre_hire_id: str) -> SignatureHumanInfoBuilder: ...
    def user_id_type(self, user_id_type: str) -> SignatureHumanInfoBuilder: ...
    def human_type(self, human_type: Enum) -> SignatureHumanInfoBuilder: ...
    def build(self) -> SignatureHumanInfo: ...
