from .object_field_data import ObjectFieldData as ObjectFieldData
from lark_oapi.core.construct import init as init

class SubmitV2OffboardingRequestBody:
    offboarding_mode: int | None
    employment_id: str | None
    offboarding_date: str | None
    offboarding_reason_unique_identifier: str | None
    offboarding_reason_explanation: str | None
    initiator_id: str | None
    add_block_list: bool | None
    block_reason: str | None
    block_reason_explanation: str | None
    custom_fields: list[ObjectFieldData] | None
    retain_account: bool | None
    is_transfer_with_workforce: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SubmitV2OffboardingRequestBodyBuilder: ...

class SubmitV2OffboardingRequestBodyBuilder:
    def __init__(self) -> None: ...
    def offboarding_mode(self, offboarding_mode: int) -> SubmitV2OffboardingRequestBodyBuilder: ...
    def employment_id(self, employment_id: str) -> SubmitV2OffboardingRequestBodyBuilder: ...
    def offboarding_date(self, offboarding_date: str) -> SubmitV2OffboardingRequestBodyBuilder: ...
    def offboarding_reason_unique_identifier(self, offboarding_reason_unique_identifier: str) -> SubmitV2OffboardingRequestBodyBuilder: ...
    def offboarding_reason_explanation(self, offboarding_reason_explanation: str) -> SubmitV2OffboardingRequestBodyBuilder: ...
    def initiator_id(self, initiator_id: str) -> SubmitV2OffboardingRequestBodyBuilder: ...
    def add_block_list(self, add_block_list: bool) -> SubmitV2OffboardingRequestBodyBuilder: ...
    def block_reason(self, block_reason: str) -> SubmitV2OffboardingRequestBodyBuilder: ...
    def block_reason_explanation(self, block_reason_explanation: str) -> SubmitV2OffboardingRequestBodyBuilder: ...
    def custom_fields(self, custom_fields: list[ObjectFieldData]) -> SubmitV2OffboardingRequestBodyBuilder: ...
    def retain_account(self, retain_account: bool) -> SubmitV2OffboardingRequestBodyBuilder: ...
    def is_transfer_with_workforce(self, is_transfer_with_workforce: bool) -> SubmitV2OffboardingRequestBodyBuilder: ...
    def build(self) -> SubmitV2OffboardingRequestBody: ...
