from .custom_field_data import CustomFieldData as CustomFieldData
from lark_oapi.core.construct import init as init

class SubmitProbationRequestBody:
    employment_id: str | None
    conversion_mode: int | None
    actual_probation_end_date: str | None
    submission_type: str | None
    initiator_id: str | None
    notes: str | None
    self_review: str | None
    custom_fields: list[CustomFieldData] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SubmitProbationRequestBodyBuilder: ...

class SubmitProbationRequestBodyBuilder:
    def __init__(self) -> None: ...
    def employment_id(self, employment_id: str) -> SubmitProbationRequestBodyBuilder: ...
    def conversion_mode(self, conversion_mode: int) -> SubmitProbationRequestBodyBuilder: ...
    def actual_probation_end_date(self, actual_probation_end_date: str) -> SubmitProbationRequestBodyBuilder: ...
    def submission_type(self, submission_type: str) -> SubmitProbationRequestBodyBuilder: ...
    def initiator_id(self, initiator_id: str) -> SubmitProbationRequestBodyBuilder: ...
    def notes(self, notes: str) -> SubmitProbationRequestBodyBuilder: ...
    def self_review(self, self_review: str) -> SubmitProbationRequestBodyBuilder: ...
    def custom_fields(self, custom_fields: list[CustomFieldData]) -> SubmitProbationRequestBodyBuilder: ...
    def build(self) -> SubmitProbationRequestBody: ...
