from .submit_v2_offboarding_request_body import SubmitV2OffboardingRequestBody as SubmitV2OffboardingRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class SubmitV2OffboardingRequest(BaseRequest):
    user_id_type: str | None
    request_body: SubmitV2OffboardingRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> SubmitV2OffboardingRequestBuilder: ...

class SubmitV2OffboardingRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> SubmitV2OffboardingRequestBuilder: ...
    def request_body(self, request_body: SubmitV2OffboardingRequestBody) -> SubmitV2OffboardingRequestBuilder: ...
    def build(self) -> SubmitV2OffboardingRequest: ...
