from lark_oapi.core.construct import init as init

class SubmitV2OffboardingResponseBody:
    offboarding_id: str | None
    employment_id: str | None
    offboarding_reason_unique_identifier: str | None
    offboarding_date: str | None
    offboarding_reason_explanation: str | None
    add_block_list: bool | None
    block_reason: str | None
    block_reason_explanation: str | None
    created_time: str | None
    retain_account: bool | None
    is_transfer_with_workforce: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SubmitV2OffboardingResponseBodyBuilder: ...

class SubmitV2OffboardingResponseBodyBuilder:
    def __init__(self) -> None: ...
    def offboarding_id(self, offboarding_id: str) -> SubmitV2OffboardingResponseBodyBuilder: ...
    def employment_id(self, employment_id: str) -> SubmitV2OffboardingResponseBodyBuilder: ...
    def offboarding_reason_unique_identifier(self, offboarding_reason_unique_identifier: str) -> SubmitV2OffboardingResponseBodyBuilder: ...
    def offboarding_date(self, offboarding_date: str) -> SubmitV2OffboardingResponseBodyBuilder: ...
    def offboarding_reason_explanation(self, offboarding_reason_explanation: str) -> SubmitV2OffboardingResponseBodyBuilder: ...
    def add_block_list(self, add_block_list: bool) -> SubmitV2OffboardingResponseBodyBuilder: ...
    def block_reason(self, block_reason: str) -> SubmitV2OffboardingResponseBodyBuilder: ...
    def block_reason_explanation(self, block_reason_explanation: str) -> SubmitV2OffboardingResponseBodyBuilder: ...
    def created_time(self, created_time: str) -> SubmitV2OffboardingResponseBodyBuilder: ...
    def retain_account(self, retain_account: bool) -> SubmitV2OffboardingResponseBodyBuilder: ...
    def is_transfer_with_workforce(self, is_transfer_with_workforce: bool) -> SubmitV2OffboardingResponseBodyBuilder: ...
    def build(self) -> SubmitV2OffboardingResponseBody: ...
