from .submit_probation_request_body import SubmitProbationRequestBody as SubmitProbationRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class SubmitProbationRequest(BaseRequest):
    client_token: str | None
    user_id_type: str | None
    request_body: SubmitProbationRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> SubmitProbationRequestBuilder: ...

class SubmitProbationRequestBuilder:
    def __init__(self) -> None: ...
    def client_token(self, client_token: str) -> SubmitProbationRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> SubmitProbationRequestBuilder: ...
    def request_body(self, request_body: SubmitProbationRequestBody) -> SubmitProbationRequestBuilder: ...
    def build(self) -> SubmitProbationRequest: ...
