from lark_oapi.core.construct import init as init

class TerminateSignatureFailIdAndReason:
    signature_file_id: str | None
    fail_reason: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TerminateSignatureFailIdAndReasonBuilder: ...

class TerminateSignatureFailIdAndReasonBuilder:
    def __init__(self) -> None: ...
    def signature_file_id(self, signature_file_id: str) -> TerminateSignatureFailIdAndReasonBuilder: ...
    def fail_reason(self, fail_reason: str) -> TerminateSignatureFailIdAndReasonBuilder: ...
    def build(self) -> TerminateSignatureFailIdAndReason: ...
