from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class TimeZone:
    time_zone_id: str | None
    name: list[I18n] | None
    time_zone_code: str | None
    utc_offset: str | None
    status: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TimeZoneBuilder: ...

class TimeZoneBuilder:
    def __init__(self) -> None: ...
    def time_zone_id(self, time_zone_id: str) -> TimeZoneBuilder: ...
    def name(self, name: list[I18n]) -> TimeZoneBuilder: ...
    def time_zone_code(self, time_zone_code: str) -> TimeZoneBuilder: ...
    def utc_offset(self, utc_offset: str) -> TimeZoneBuilder: ...
    def status(self, status: int) -> TimeZoneBuilder: ...
    def build(self) -> TimeZone: ...
