from lark_oapi.core.construct import init as init

class TransitTaskPreHireResponseBody:
    success: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TransitTaskPreHireResponseBodyBuilder: ...

class TransitTaskPreHireResponseBodyBuilder:
    def __init__(self) -> None: ...
    def success(self, success: bool) -> TransitTaskPreHireResponseBodyBuilder: ...
    def build(self) -> TransitTaskPreHireResponseBody: ...
