from .transit_task_pre_hire_request_body import TransitTaskPreHireRequestBody as TransitTaskPreHireRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class TransitTaskPreHireRequest(BaseRequest):
    pre_hire_id: str | None
    request_body: TransitTaskPreHireRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> TransitTaskPreHireRequestBuilder: ...

class TransitTaskPreHireRequestBuilder:
    def __init__(self) -> None: ...
    def pre_hire_id(self, pre_hire_id: str) -> TransitTaskPreHireRequestBuilder: ...
    def request_body(self, request_body: TransitTaskPreHireRequestBody) -> TransitTaskPreHireRequestBuilder: ...
    def build(self) -> TransitTaskPreHireRequest: ...
