from lark_oapi.core.construct import init as init

class UpdateProcessApproverResponseBody:
    code: int | None
    msg: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateProcessApproverResponseBodyBuilder: ...

class UpdateProcessApproverResponseBodyBuilder:
    def __init__(self) -> None: ...
    def code(self, code: int) -> UpdateProcessApproverResponseBodyBuilder: ...
    def msg(self, msg: str) -> UpdateProcessApproverResponseBodyBuilder: ...
    def build(self) -> UpdateProcessApproverResponseBody: ...
