from .match_rules import MatchRules as MatchRules
from lark_oapi.core.construct import init as init

class UpdateRuleCustomOrgRequestBody:
    object_api_name: str | None
    org_id: str | None
    match_rule_groups: list[MatchRules] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateRuleCustomOrgRequestBodyBuilder: ...

class UpdateRuleCustomOrgRequestBodyBuilder:
    def __init__(self) -> None: ...
    def object_api_name(self, object_api_name: str) -> UpdateRuleCustomOrgRequestBodyBuilder: ...
    def org_id(self, org_id: str) -> UpdateRuleCustomOrgRequestBodyBuilder: ...
    def match_rule_groups(self, match_rule_groups: list[MatchRules]) -> UpdateRuleCustomOrgRequestBodyBuilder: ...
    def build(self) -> UpdateRuleCustomOrgRequestBody: ...
