from lark_oapi.core.construct import init as init

class UpdateProcessRevokeResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateProcessRevokeResponseBodyBuilder: ...

class UpdateProcessRevokeResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> UpdateProcessRevokeResponseBody: ...
