from .employment_default_cost_center import EmploymentDefaultCostCenter as EmploymentDefaultCostCenter
from lark_oapi.core.construct import init as init

class UpdateVersionDefaultCostCenterRequestBody:
    employment_id: str | None
    default_cost_center: EmploymentDefaultCostCenter | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateVersionDefaultCostCenterRequestBodyBuilder: ...

class UpdateVersionDefaultCostCenterRequestBodyBuilder:
    def __init__(self) -> None: ...
    def employment_id(self, employment_id: str) -> UpdateVersionDefaultCostCenterRequestBodyBuilder: ...
    def default_cost_center(self, default_cost_center: EmploymentDefaultCostCenter) -> UpdateVersionDefaultCostCenterRequestBodyBuilder: ...
    def build(self) -> UpdateVersionDefaultCostCenterRequestBody: ...
