from lark_oapi.core.construct import init as init

class UserContact:
    user_ids: list[str] | None
    mobile: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserContactBuilder: ...

class UserContactBuilder:
    def __init__(self) -> None: ...
    def user_ids(self, user_ids: list[str]) -> UserContactBuilder: ...
    def mobile(self, mobile: str) -> UserContactBuilder: ...
    def build(self) -> UserContact: ...
