from lark_oapi.core.construct import init as init

class UserInfo:
    user_id: str | None
    name: str | None
    zh_name: str | None
    en_name: str | None
    mobile: str | None
    employee_no: str | None
    email: str | None
    is_resigned: bool | None
    resign_time: int | None
    resign_date: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserInfoBuilder: ...

class UserInfoBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: str) -> UserInfoBuilder: ...
    def name(self, name: str) -> UserInfoBuilder: ...
    def zh_name(self, zh_name: str) -> UserInfoBuilder: ...
    def en_name(self, en_name: str) -> UserInfoBuilder: ...
    def mobile(self, mobile: str) -> UserInfoBuilder: ...
    def employee_no(self, employee_no: str) -> UserInfoBuilder: ...
    def email(self, email: str) -> UserInfoBuilder: ...
    def is_resigned(self, is_resigned: bool) -> UserInfoBuilder: ...
    def resign_time(self, resign_time: int) -> UserInfoBuilder: ...
    def resign_date(self, resign_date: str) -> UserInfoBuilder: ...
    def build(self) -> UserInfo: ...
