from lark_oapi.core.construct import init as init

class WithdrawOnboardingPreHireRequestBody:
    pre_hire_id: str | None
    withdraw_reason: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WithdrawOnboardingPreHireRequestBodyBuilder: ...

class WithdrawOnboardingPreHireRequestBodyBuilder:
    def __init__(self) -> None: ...
    def pre_hire_id(self, pre_hire_id: str) -> WithdrawOnboardingPreHireRequestBodyBuilder: ...
    def withdraw_reason(self, withdraw_reason: str) -> WithdrawOnboardingPreHireRequestBodyBuilder: ...
    def build(self) -> WithdrawOnboardingPreHireRequestBody: ...
