from lark_oapi.core.construct import init as init

class WithdrawOnboardingPreHireResponseBody:
    success: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WithdrawOnboardingPreHireResponseBodyBuilder: ...

class WithdrawOnboardingPreHireResponseBodyBuilder:
    def __init__(self) -> None: ...
    def success(self, success: bool) -> WithdrawOnboardingPreHireResponseBodyBuilder: ...
    def build(self) -> WithdrawOnboardingPreHireResponseBody: ...
