from .custom_field_data import CustomFieldData as CustomFieldData
from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class WorkExperienceInfo:
    company_organization: list[I18n] | None
    department: list[I18n] | None
    job: list[I18n] | None
    description: list[I18n] | None
    start_date: str | None
    end_date: str | None
    custom_fields: list[CustomFieldData] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WorkExperienceInfoBuilder: ...

class WorkExperienceInfoBuilder:
    def __init__(self) -> None: ...
    def company_organization(self, company_organization: list[I18n]) -> WorkExperienceInfoBuilder: ...
    def department(self, department: list[I18n]) -> WorkExperienceInfoBuilder: ...
    def job(self, job: list[I18n]) -> WorkExperienceInfoBuilder: ...
    def description(self, description: list[I18n]) -> WorkExperienceInfoBuilder: ...
    def start_date(self, start_date: str) -> WorkExperienceInfoBuilder: ...
    def end_date(self, end_date: str) -> WorkExperienceInfoBuilder: ...
    def custom_fields(self, custom_fields: list[CustomFieldData]) -> WorkExperienceInfoBuilder: ...
    def build(self) -> WorkExperienceInfo: ...
