from lark_oapi.core.construct import init as init

class WorkforcePlanMultiPeriodValue:
    period_date: str | None
    workforce_plan: str | None
    individuals_to_be_added: str | None
    individuals_to_be_removed: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WorkforcePlanMultiPeriodValueBuilder: ...

class WorkforcePlanMultiPeriodValueBuilder:
    def __init__(self) -> None: ...
    def period_date(self, period_date: str) -> WorkforcePlanMultiPeriodValueBuilder: ...
    def workforce_plan(self, workforce_plan: str) -> WorkforcePlanMultiPeriodValueBuilder: ...
    def individuals_to_be_added(self, individuals_to_be_added: str) -> WorkforcePlanMultiPeriodValueBuilder: ...
    def individuals_to_be_removed(self, individuals_to_be_removed: str) -> WorkforcePlanMultiPeriodValueBuilder: ...
    def build(self) -> WorkforcePlanMultiPeriodValue: ...
