from .object_field_data import ObjectFieldData as ObjectFieldData
from lark_oapi.core.construct import init as init

class WorkExperienceForUpdate:
    company_name: str | None
    start_time: str | None
    end_time: str | None
    job_title: str | None
    description: str | None
    department: str | None
    custom_fields: list[ObjectFieldData] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WorkExperienceForUpdateBuilder: ...

class WorkExperienceForUpdateBuilder:
    def __init__(self) -> None: ...
    def company_name(self, company_name: str) -> WorkExperienceForUpdateBuilder: ...
    def start_time(self, start_time: str) -> WorkExperienceForUpdateBuilder: ...
    def end_time(self, end_time: str) -> WorkExperienceForUpdateBuilder: ...
    def job_title(self, job_title: str) -> WorkExperienceForUpdateBuilder: ...
    def description(self, description: str) -> WorkExperienceForUpdateBuilder: ...
    def department(self, department: str) -> WorkExperienceForUpdateBuilder: ...
    def custom_fields(self, custom_fields: list[ObjectFieldData]) -> WorkExperienceForUpdateBuilder: ...
    def build(self) -> WorkExperienceForUpdate: ...
