from lark_oapi.core.construct import init as init

class WorkforcePlanEaiDetail:
    date: str | None
    estimated_active_individuals: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WorkforcePlanEaiDetailBuilder: ...

class WorkforcePlanEaiDetailBuilder:
    def __init__(self) -> None: ...
    def date(self, date: str) -> WorkforcePlanEaiDetailBuilder: ...
    def estimated_active_individuals(self, estimated_active_individuals: str) -> WorkforcePlanEaiDetailBuilder: ...
    def build(self) -> WorkforcePlanEaiDetail: ...
