from lark_oapi.core.construct import init as init

class BatchCloseSystemStatusRequestBody:
    user_list: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchCloseSystemStatusRequestBodyBuilder: ...

class BatchCloseSystemStatusRequestBodyBuilder:
    def __init__(self) -> None: ...
    def user_list(self, user_list: list[str]) -> BatchCloseSystemStatusRequestBodyBuilder: ...
    def build(self) -> BatchCloseSystemStatusRequestBody: ...
