from .system_status_user_open_param import SystemStatusUserOpenParam as SystemStatusUserOpenParam
from lark_oapi.core.construct import init as init

class BatchOpenSystemStatusRequestBody:
    user_list: list[SystemStatusUserOpenParam] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchOpenSystemStatusRequestBodyBuilder: ...

class BatchOpenSystemStatusRequestBodyBuilder:
    def __init__(self) -> None: ...
    def user_list(self, user_list: list[SystemStatusUserOpenParam]) -> BatchOpenSystemStatusRequestBodyBuilder: ...
    def build(self) -> BatchOpenSystemStatusRequestBody: ...
