from .system_status import SystemStatus as SystemStatus
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateSystemStatusRequest(BaseRequest):
    request_body: SystemStatus | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateSystemStatusRequestBuilder: ...

class CreateSystemStatusRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: SystemStatus) -> CreateSystemStatusRequestBuilder: ...
    def build(self) -> CreateSystemStatusRequest: ...
