from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteSystemStatusRequest(BaseRequest):
    system_status_id: int | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteSystemStatusRequestBuilder: ...

class DeleteSystemStatusRequestBuilder:
    def __init__(self) -> None: ...
    def system_status_id(self, system_status_id: int) -> DeleteSystemStatusRequestBuilder: ...
    def build(self) -> DeleteSystemStatusRequest: ...
