from lark_oapi.core.construct import init as init

class ListSystemStatusRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListSystemStatusRequestBodyBuilder: ...

class ListSystemStatusRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListSystemStatusRequestBody: ...
