from .system_status import SystemStatus as SystemStatus
from lark_oapi.core.construct import init as init

class ListSystemStatusResponseBody:
    items: list[SystemStatus] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListSystemStatusResponseBodyBuilder: ...

class ListSystemStatusResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[SystemStatus]) -> ListSystemStatusResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListSystemStatusResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListSystemStatusResponseBodyBuilder: ...
    def build(self) -> ListSystemStatusResponseBody: ...
