from .patch_system_status_request_body import PatchSystemStatusRequestBody as PatchSystemStatusRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PatchSystemStatusRequest(BaseRequest):
    system_status_id: int | None
    request_body: PatchSystemStatusRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PatchSystemStatusRequestBuilder: ...

class PatchSystemStatusRequestBuilder:
    def __init__(self) -> None: ...
    def system_status_id(self, system_status_id: int) -> PatchSystemStatusRequestBuilder: ...
    def request_body(self, request_body: PatchSystemStatusRequestBody) -> PatchSystemStatusRequestBuilder: ...
    def build(self) -> PatchSystemStatusRequest: ...
