from .system_status import SystemStatus as SystemStatus
from lark_oapi.core.construct import init as init

class PatchSystemStatusResponseBody:
    system_status: SystemStatus | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchSystemStatusResponseBodyBuilder: ...

class PatchSystemStatusResponseBodyBuilder:
    def __init__(self) -> None: ...
    def system_status(self, system_status: SystemStatus) -> PatchSystemStatusResponseBodyBuilder: ...
    def build(self) -> PatchSystemStatusResponseBody: ...
