from lark_oapi.core.construct import init as init

class SystemStatusUserOpenParam:
    user_id: str | None
    end_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SystemStatusUserOpenParamBuilder: ...

class SystemStatusUserOpenParamBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: str) -> SystemStatusUserOpenParamBuilder: ...
    def end_time(self, end_time: str) -> SystemStatusUserOpenParamBuilder: ...
    def build(self) -> SystemStatusUserOpenParam: ...
