from .system_status_sync_i18n_explain import SystemStatusSyncI18nExplain as SystemStatusSyncI18nExplain
from .system_status_sync_i18n_name import SystemStatusSyncI18nName as SystemStatusSyncI18nName
from lark_oapi.core.construct import init as init

class SystemStatusSyncSetting:
    is_open_by_default: bool | None
    title: str | None
    i18n_title: SystemStatusSyncI18nName | None
    explain: str | None
    i18n_explain: SystemStatusSyncI18nExplain | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SystemStatusSyncSettingBuilder: ...

class SystemStatusSyncSettingBuilder:
    def __init__(self) -> None: ...
    def is_open_by_default(self, is_open_by_default: bool) -> SystemStatusSyncSettingBuilder: ...
    def title(self, title: str) -> SystemStatusSyncSettingBuilder: ...
    def i18n_title(self, i18n_title: SystemStatusSyncI18nName) -> SystemStatusSyncSettingBuilder: ...
    def explain(self, explain: str) -> SystemStatusSyncSettingBuilder: ...
    def i18n_explain(self, i18n_explain: SystemStatusSyncI18nExplain) -> SystemStatusSyncSettingBuilder: ...
    def build(self) -> SystemStatusSyncSetting: ...
