from ..model.create_employee_type_enum_request import CreateEmployeeTypeEnumRequest as CreateEmployeeTypeEnumRequest
from ..model.create_employee_type_enum_response import CreateEmployeeTypeEnumResponse as CreateEmployeeTypeEnumResponse
from ..model.delete_employee_type_enum_request import DeleteEmployeeTypeEnumRequest as DeleteEmployeeTypeEnumRequest
from ..model.delete_employee_type_enum_response import DeleteEmployeeTypeEnumResponse as DeleteEmployeeTypeEnumResponse
from ..model.list_employee_type_enum_request import ListEmployeeTypeEnumRequest as ListEmployeeTypeEnumRequest
from ..model.list_employee_type_enum_response import ListEmployeeTypeEnumResponse as ListEmployeeTypeEnumResponse
from ..model.update_employee_type_enum_request import UpdateEmployeeTypeEnumRequest as UpdateEmployeeTypeEnumRequest
from ..model.update_employee_type_enum_response import UpdateEmployeeTypeEnumResponse as UpdateEmployeeTypeEnumResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class EmployeeTypeEnum:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def create(self, request: CreateEmployeeTypeEnumRequest, option: RequestOption | None = None) -> CreateEmployeeTypeEnumResponse: ...
    async def acreate(self, request: CreateEmployeeTypeEnumRequest, option: RequestOption | None = None) -> CreateEmployeeTypeEnumResponse: ...
    def delete(self, request: DeleteEmployeeTypeEnumRequest, option: RequestOption | None = None) -> DeleteEmployeeTypeEnumResponse: ...
    async def adelete(self, request: DeleteEmployeeTypeEnumRequest, option: RequestOption | None = None) -> DeleteEmployeeTypeEnumResponse: ...
    def list(self, request: ListEmployeeTypeEnumRequest, option: RequestOption | None = None) -> ListEmployeeTypeEnumResponse: ...
    async def alist(self, request: ListEmployeeTypeEnumRequest, option: RequestOption | None = None) -> ListEmployeeTypeEnumResponse: ...
    def update(self, request: UpdateEmployeeTypeEnumRequest, option: RequestOption | None = None) -> UpdateEmployeeTypeEnumResponse: ...
    async def aupdate(self, request: UpdateEmployeeTypeEnumRequest, option: RequestOption | None = None) -> UpdateEmployeeTypeEnumResponse: ...
