from ..model.add_group_member_request import AddGroupMemberRequest as AddGroupMemberRequest
from ..model.add_group_member_response import AddGroupMemberResponse as AddGroupMemberResponse
from ..model.batch_add_group_member_request import BatchAddGroupMemberRequest as BatchAddGroupMemberRequest
from ..model.batch_add_group_member_response import BatchAddGroupMemberResponse as BatchAddGroupMemberResponse
from ..model.batch_remove_group_member_request import BatchRemoveGroupMemberRequest as BatchRemoveGroupMemberRequest
from ..model.batch_remove_group_member_response import BatchRemoveGroupMemberResponse as BatchRemoveGroupMemberResponse
from ..model.remove_group_member_request import RemoveGroupMemberRequest as RemoveGroupMemberRequest
from ..model.remove_group_member_response import RemoveGroupMemberResponse as RemoveGroupMemberResponse
from ..model.simplelist_group_member_request import SimplelistGroupMemberRequest as SimplelistGroupMemberRequest
from ..model.simplelist_group_member_response import SimplelistGroupMemberResponse as SimplelistGroupMemberResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class GroupMember:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def add(self, request: AddGroupMemberRequest, option: RequestOption | None = None) -> AddGroupMemberResponse: ...
    async def aadd(self, request: AddGroupMemberRequest, option: RequestOption | None = None) -> AddGroupMemberResponse: ...
    def batch_add(self, request: BatchAddGroupMemberRequest, option: RequestOption | None = None) -> BatchAddGroupMemberResponse: ...
    async def abatch_add(self, request: BatchAddGroupMemberRequest, option: RequestOption | None = None) -> BatchAddGroupMemberResponse: ...
    def batch_remove(self, request: BatchRemoveGroupMemberRequest, option: RequestOption | None = None) -> BatchRemoveGroupMemberResponse: ...
    async def abatch_remove(self, request: BatchRemoveGroupMemberRequest, option: RequestOption | None = None) -> BatchRemoveGroupMemberResponse: ...
    def remove(self, request: RemoveGroupMemberRequest, option: RequestOption | None = None) -> RemoveGroupMemberResponse: ...
    async def aremove(self, request: RemoveGroupMemberRequest, option: RequestOption | None = None) -> RemoveGroupMemberResponse: ...
    def simplelist(self, request: SimplelistGroupMemberRequest, option: RequestOption | None = None) -> SimplelistGroupMemberResponse: ...
    async def asimplelist(self, request: SimplelistGroupMemberRequest, option: RequestOption | None = None) -> SimplelistGroupMemberResponse: ...
