from ..model.create_chat_tab_request import CreateChatTabRequest as CreateChatTabRequest
from ..model.create_chat_tab_response import CreateChatTabResponse as CreateChatTabResponse
from ..model.delete_tabs_chat_tab_request import DeleteTabsChatTabRequest as DeleteTabsChatTabRequest
from ..model.delete_tabs_chat_tab_response import DeleteTabsChatTabResponse as DeleteTabsChatTabResponse
from ..model.list_tabs_chat_tab_request import ListTabsChatTabRequest as ListTabsChatTabRequest
from ..model.list_tabs_chat_tab_response import ListTabsChatTabResponse as ListTabsChatTabResponse
from ..model.sort_tabs_chat_tab_request import SortTabsChatTabRequest as SortTabsChatTabRequest
from ..model.sort_tabs_chat_tab_response import SortTabsChatTabResponse as SortTabsChatTabResponse
from ..model.update_tabs_chat_tab_request import UpdateTabsChatTabRequest as UpdateTabsChatTabRequest
from ..model.update_tabs_chat_tab_response import UpdateTabsChatTabResponse as UpdateTabsChatTabResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class ChatTab:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def create(self, request: CreateChatTabRequest, option: RequestOption | None = None) -> CreateChatTabResponse: ...
    async def acreate(self, request: CreateChatTabRequest, option: RequestOption | None = None) -> CreateChatTabResponse: ...
    def delete_tabs(self, request: DeleteTabsChatTabRequest, option: RequestOption | None = None) -> DeleteTabsChatTabResponse: ...
    async def adelete_tabs(self, request: DeleteTabsChatTabRequest, option: RequestOption | None = None) -> DeleteTabsChatTabResponse: ...
    def list_tabs(self, request: ListTabsChatTabRequest, option: RequestOption | None = None) -> ListTabsChatTabResponse: ...
    async def alist_tabs(self, request: ListTabsChatTabRequest, option: RequestOption | None = None) -> ListTabsChatTabResponse: ...
    def sort_tabs(self, request: SortTabsChatTabRequest, option: RequestOption | None = None) -> SortTabsChatTabResponse: ...
    async def asort_tabs(self, request: SortTabsChatTabRequest, option: RequestOption | None = None) -> SortTabsChatTabResponse: ...
    def update_tabs(self, request: UpdateTabsChatTabRequest, option: RequestOption | None = None) -> UpdateTabsChatTabResponse: ...
    async def aupdate_tabs(self, request: UpdateTabsChatTabRequest, option: RequestOption | None = None) -> UpdateTabsChatTabResponse: ...
