from ..model.create_chat_menu_tree_request import CreateChatMenuTreeRequest as CreateChatMenuTreeRequest
from ..model.create_chat_menu_tree_response import CreateChatMenuTreeResponse as CreateChatMenuTreeResponse
from ..model.delete_chat_menu_tree_request import DeleteChatMenuTreeRequest as DeleteChatMenuTreeRequest
from ..model.delete_chat_menu_tree_response import DeleteChatMenuTreeResponse as DeleteChatMenuTreeResponse
from ..model.get_chat_menu_tree_request import GetChatMenuTreeRequest as GetChatMenuTreeRequest
from ..model.get_chat_menu_tree_response import GetChatMenuTreeResponse as GetChatMenuTreeResponse
from ..model.sort_chat_menu_tree_request import SortChatMenuTreeRequest as SortChatMenuTreeRequest
from ..model.sort_chat_menu_tree_response import SortChatMenuTreeResponse as SortChatMenuTreeResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class ChatMenuTree:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def create(self, request: CreateChatMenuTreeRequest, option: RequestOption | None = None) -> CreateChatMenuTreeResponse: ...
    async def acreate(self, request: CreateChatMenuTreeRequest, option: RequestOption | None = None) -> CreateChatMenuTreeResponse: ...
    def delete(self, request: DeleteChatMenuTreeRequest, option: RequestOption | None = None) -> DeleteChatMenuTreeResponse: ...
    async def adelete(self, request: DeleteChatMenuTreeRequest, option: RequestOption | None = None) -> DeleteChatMenuTreeResponse: ...
    def get(self, request: GetChatMenuTreeRequest, option: RequestOption | None = None) -> GetChatMenuTreeResponse: ...
    async def aget(self, request: GetChatMenuTreeRequest, option: RequestOption | None = None) -> GetChatMenuTreeResponse: ...
    def sort(self, request: SortChatMenuTreeRequest, option: RequestOption | None = None) -> SortChatMenuTreeResponse: ...
    async def asort(self, request: SortChatMenuTreeRequest, option: RequestOption | None = None) -> SortChatMenuTreeResponse: ...
