from lark_oapi.core.construct import init as init

class AigcConfig:
    need_review: bool | None
    repo_id: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AigcConfigBuilder: ...

class AigcConfigBuilder:
    def __init__(self) -> None: ...
    def need_review(self, need_review: bool) -> AigcConfigBuilder: ...
    def repo_id(self, repo_id: int) -> AigcConfigBuilder: ...
    def build(self) -> AigcConfig: ...
