from .i18n_cls_name import I18nClsName as I18nClsName
from lark_oapi.core.construct import init as init

class Classification:
    id: str | None
    name: str | None
    father_id: str | None
    i18n_names: list[I18nClsName] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ClassificationBuilder: ...

class ClassificationBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> ClassificationBuilder: ...
    def name(self, name: str) -> ClassificationBuilder: ...
    def father_id(self, father_id: str) -> ClassificationBuilder: ...
    def i18n_names(self, i18n_names: list[I18nClsName]) -> ClassificationBuilder: ...
    def build(self) -> Classification: ...
