from lark_oapi.core.construct import init as init

class DeleteEntityRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteEntityRequestBodyBuilder: ...

class DeleteEntityRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteEntityRequestBody: ...
