from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteEntityRequest(BaseRequest):
    provider: str | None
    outer_id: str | None
    entity_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteEntityRequestBuilder: ...

class DeleteEntityRequestBuilder:
    def __init__(self) -> None: ...
    def provider(self, provider: str) -> DeleteEntityRequestBuilder: ...
    def outer_id(self, outer_id: str) -> DeleteEntityRequestBuilder: ...
    def entity_id(self, entity_id: str) -> DeleteEntityRequestBuilder: ...
    def build(self) -> DeleteEntityRequest: ...
