from lark_oapi.core.construct import init as init

class DocBullet:
    text: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DocBulletBuilder: ...

class DocBulletBuilder:
    def __init__(self) -> None: ...
    def text(self, text: str) -> DocBulletBuilder: ...
    def build(self) -> DocBullet: ...
