from lark_oapi.core.construct import init as init

class DocHeading:
    text: str | None
    heading_level: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DocHeadingBuilder: ...

class DocHeadingBuilder:
    def __init__(self) -> None: ...
    def text(self, text: str) -> DocHeadingBuilder: ...
    def heading_level(self, heading_level: int) -> DocHeadingBuilder: ...
    def build(self) -> DocHeading: ...
