from lark_oapi.core.construct import init as init

class DocCode:
    text: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DocCodeBuilder: ...

class DocCodeBuilder:
    def __init__(self) -> None: ...
    def text(self, text: str) -> DocCodeBuilder: ...
    def build(self) -> DocCode: ...
