from lark_oapi.core.construct import init as init

class DocRodered:
    text: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DocRoderedBuilder: ...

class DocRoderedBuilder:
    def __init__(self) -> None: ...
    def text(self, text: str) -> DocRoderedBuilder: ...
    def build(self) -> DocRodered: ...
