from lark_oapi.core.construct import init as init

class DownloadFileRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DownloadFileRequestBodyBuilder: ...

class DownloadFileRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DownloadFileRequestBody: ...
