from lark_oapi.core.construct import init as init

class GetEntityRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetEntityRequestBodyBuilder: ...

class GetEntityRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetEntityRequestBody: ...
