from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetEntityRequest(BaseRequest):
    provider: str | None
    outer_id: str | None
    user_id_type: str | None
    entity_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetEntityRequestBuilder: ...

class GetEntityRequestBuilder:
    def __init__(self) -> None: ...
    def provider(self, provider: str) -> GetEntityRequestBuilder: ...
    def outer_id(self, outer_id: str) -> GetEntityRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> GetEntityRequestBuilder: ...
    def entity_id(self, entity_id: str) -> GetEntityRequestBuilder: ...
    def build(self) -> GetEntityRequest: ...
