from lark_oapi.core.construct import init as init

class ListClassificationRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListClassificationRequestBodyBuilder: ...

class ListClassificationRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListClassificationRequestBody: ...
