from lark_oapi.core.construct import init as init

class MatchInfo:
    entity_id: str | None
    type: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MatchInfoBuilder: ...

class MatchInfoBuilder:
    def __init__(self) -> None: ...
    def entity_id(self, entity_id: str) -> MatchInfoBuilder: ...
    def type(self, type: int) -> MatchInfoBuilder: ...
    def build(self) -> MatchInfo: ...
