from lark_oapi.core.construct import init as init

class Repo:
    id: int | None
    name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RepoBuilder: ...

class RepoBuilder:
    def __init__(self) -> None: ...
    def id(self, id: int) -> RepoBuilder: ...
    def name(self, name: str) -> RepoBuilder: ...
    def build(self) -> Repo: ...
