from .correct_info import CorrectInfo as CorrectInfo
from .word_info import WordInfo as WordInfo
from lark_oapi.core.construct import init as init

class StatisticalReport:
    date_interval: int | None
    word_info: WordInfo | None
    correct_info: CorrectInfo | None
    update_date: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> StatisticalReportBuilder: ...

class StatisticalReportBuilder:
    def __init__(self) -> None: ...
    def date_interval(self, date_interval: int) -> StatisticalReportBuilder: ...
    def word_info(self, word_info: WordInfo) -> StatisticalReportBuilder: ...
    def correct_info(self, correct_info: CorrectInfo) -> StatisticalReportBuilder: ...
    def update_date(self, update_date: int) -> StatisticalReportBuilder: ...
    def build(self) -> StatisticalReport: ...
