from .draft import Draft as Draft
from lark_oapi.core.construct import init as init

class UpdateDraftResponseBody:
    draft: Draft | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateDraftResponseBodyBuilder: ...

class UpdateDraftResponseBodyBuilder:
    def __init__(self) -> None: ...
    def draft(self, draft: Draft) -> UpdateDraftResponseBodyBuilder: ...
    def build(self) -> UpdateDraftResponseBody: ...
