from .entity import Entity as Entity
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UpdateEntityRequest(BaseRequest):
    user_id_type: str | None
    entity_id: str | None
    request_body: Entity | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UpdateEntityRequestBuilder: ...

class UpdateEntityRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> UpdateEntityRequestBuilder: ...
    def entity_id(self, entity_id: str) -> UpdateEntityRequestBuilder: ...
    def request_body(self, request_body: Entity) -> UpdateEntityRequestBuilder: ...
    def build(self) -> UpdateEntityRequest: ...
