from .model.p2_vc_meeting_all_meeting_ended_v1 import P2VcMeetingAllMeetingEndedV1 as P2VcMeetingAllMeetingEndedV1
from .model.p2_vc_meeting_all_meeting_started_v1 import P2VcMeetingAllMeetingStartedV1 as P2VcMeetingAllMeetingStartedV1
from .model.p2_vc_meeting_join_meeting_v1 import P2VcMeetingJoinMeetingV1 as P2VcMeetingJoinMeetingV1
from .model.p2_vc_meeting_leave_meeting_v1 import P2VcMeetingLeaveMeetingV1 as P2VcMeetingLeaveMeetingV1
from .model.p2_vc_meeting_meeting_ended_v1 import P2VcMeetingMeetingEndedV1 as P2VcMeetingMeetingEndedV1
from .model.p2_vc_meeting_meeting_started_v1 import P2VcMeetingMeetingStartedV1 as P2VcMeetingMeetingStartedV1
from .model.p2_vc_meeting_recording_ended_v1 import P2VcMeetingRecordingEndedV1 as P2VcMeetingRecordingEndedV1
from .model.p2_vc_meeting_recording_ready_v1 import P2VcMeetingRecordingReadyV1 as P2VcMeetingRecordingReadyV1
from .model.p2_vc_meeting_recording_started_v1 import P2VcMeetingRecordingStartedV1 as P2VcMeetingRecordingStartedV1
from .model.p2_vc_meeting_share_ended_v1 import P2VcMeetingShareEndedV1 as P2VcMeetingShareEndedV1
from .model.p2_vc_meeting_share_started_v1 import P2VcMeetingShareStartedV1 as P2VcMeetingShareStartedV1
from .model.p2_vc_reserve_config_updated_v1 import P2VcReserveConfigUpdatedV1 as P2VcReserveConfigUpdatedV1
from .model.p2_vc_room_created_v1 import P2VcRoomCreatedV1 as P2VcRoomCreatedV1
from .model.p2_vc_room_deleted_v1 import P2VcRoomDeletedV1 as P2VcRoomDeletedV1
from .model.p2_vc_room_level_created_v1 import P2VcRoomLevelCreatedV1 as P2VcRoomLevelCreatedV1
from .model.p2_vc_room_level_deleted_v1 import P2VcRoomLevelDeletedV1 as P2VcRoomLevelDeletedV1
from .model.p2_vc_room_level_updated_v1 import P2VcRoomLevelUpdatedV1 as P2VcRoomLevelUpdatedV1
from .model.p2_vc_room_updated_v1 import P2VcRoomUpdatedV1 as P2VcRoomUpdatedV1
from _typeshed import Incomplete
from lark_oapi.event.processor import IEventProcessor as IEventProcessor
from typing import Callable

class P2VcMeetingAllMeetingEndedV1Processor(IEventProcessor[P2VcMeetingAllMeetingEndedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2VcMeetingAllMeetingEndedV1], None]) -> None: ...
    def type(self) -> type[P2VcMeetingAllMeetingEndedV1]: ...
    def do(self, data: P2VcMeetingAllMeetingEndedV1) -> None: ...

class P2VcMeetingAllMeetingStartedV1Processor(IEventProcessor[P2VcMeetingAllMeetingStartedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2VcMeetingAllMeetingStartedV1], None]) -> None: ...
    def type(self) -> type[P2VcMeetingAllMeetingStartedV1]: ...
    def do(self, data: P2VcMeetingAllMeetingStartedV1) -> None: ...

class P2VcMeetingJoinMeetingV1Processor(IEventProcessor[P2VcMeetingJoinMeetingV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2VcMeetingJoinMeetingV1], None]) -> None: ...
    def type(self) -> type[P2VcMeetingJoinMeetingV1]: ...
    def do(self, data: P2VcMeetingJoinMeetingV1) -> None: ...

class P2VcMeetingLeaveMeetingV1Processor(IEventProcessor[P2VcMeetingLeaveMeetingV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2VcMeetingLeaveMeetingV1], None]) -> None: ...
    def type(self) -> type[P2VcMeetingLeaveMeetingV1]: ...
    def do(self, data: P2VcMeetingLeaveMeetingV1) -> None: ...

class P2VcMeetingMeetingEndedV1Processor(IEventProcessor[P2VcMeetingMeetingEndedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2VcMeetingMeetingEndedV1], None]) -> None: ...
    def type(self) -> type[P2VcMeetingMeetingEndedV1]: ...
    def do(self, data: P2VcMeetingMeetingEndedV1) -> None: ...

class P2VcMeetingMeetingStartedV1Processor(IEventProcessor[P2VcMeetingMeetingStartedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2VcMeetingMeetingStartedV1], None]) -> None: ...
    def type(self) -> type[P2VcMeetingMeetingStartedV1]: ...
    def do(self, data: P2VcMeetingMeetingStartedV1) -> None: ...

class P2VcMeetingRecordingEndedV1Processor(IEventProcessor[P2VcMeetingRecordingEndedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2VcMeetingRecordingEndedV1], None]) -> None: ...
    def type(self) -> type[P2VcMeetingRecordingEndedV1]: ...
    def do(self, data: P2VcMeetingRecordingEndedV1) -> None: ...

class P2VcMeetingRecordingReadyV1Processor(IEventProcessor[P2VcMeetingRecordingReadyV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2VcMeetingRecordingReadyV1], None]) -> None: ...
    def type(self) -> type[P2VcMeetingRecordingReadyV1]: ...
    def do(self, data: P2VcMeetingRecordingReadyV1) -> None: ...

class P2VcMeetingRecordingStartedV1Processor(IEventProcessor[P2VcMeetingRecordingStartedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2VcMeetingRecordingStartedV1], None]) -> None: ...
    def type(self) -> type[P2VcMeetingRecordingStartedV1]: ...
    def do(self, data: P2VcMeetingRecordingStartedV1) -> None: ...

class P2VcMeetingShareEndedV1Processor(IEventProcessor[P2VcMeetingShareEndedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2VcMeetingShareEndedV1], None]) -> None: ...
    def type(self) -> type[P2VcMeetingShareEndedV1]: ...
    def do(self, data: P2VcMeetingShareEndedV1) -> None: ...

class P2VcMeetingShareStartedV1Processor(IEventProcessor[P2VcMeetingShareStartedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2VcMeetingShareStartedV1], None]) -> None: ...
    def type(self) -> type[P2VcMeetingShareStartedV1]: ...
    def do(self, data: P2VcMeetingShareStartedV1) -> None: ...

class P2VcReserveConfigUpdatedV1Processor(IEventProcessor[P2VcReserveConfigUpdatedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2VcReserveConfigUpdatedV1], None]) -> None: ...
    def type(self) -> type[P2VcReserveConfigUpdatedV1]: ...
    def do(self, data: P2VcReserveConfigUpdatedV1) -> None: ...

class P2VcRoomCreatedV1Processor(IEventProcessor[P2VcRoomCreatedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2VcRoomCreatedV1], None]) -> None: ...
    def type(self) -> type[P2VcRoomCreatedV1]: ...
    def do(self, data: P2VcRoomCreatedV1) -> None: ...

class P2VcRoomDeletedV1Processor(IEventProcessor[P2VcRoomDeletedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2VcRoomDeletedV1], None]) -> None: ...
    def type(self) -> type[P2VcRoomDeletedV1]: ...
    def do(self, data: P2VcRoomDeletedV1) -> None: ...

class P2VcRoomUpdatedV1Processor(IEventProcessor[P2VcRoomUpdatedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2VcRoomUpdatedV1], None]) -> None: ...
    def type(self) -> type[P2VcRoomUpdatedV1]: ...
    def do(self, data: P2VcRoomUpdatedV1) -> None: ...

class P2VcRoomLevelCreatedV1Processor(IEventProcessor[P2VcRoomLevelCreatedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2VcRoomLevelCreatedV1], None]) -> None: ...
    def type(self) -> type[P2VcRoomLevelCreatedV1]: ...
    def do(self, data: P2VcRoomLevelCreatedV1) -> None: ...

class P2VcRoomLevelDeletedV1Processor(IEventProcessor[P2VcRoomLevelDeletedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2VcRoomLevelDeletedV1], None]) -> None: ...
    def type(self) -> type[P2VcRoomLevelDeletedV1]: ...
    def do(self, data: P2VcRoomLevelDeletedV1) -> None: ...

class P2VcRoomLevelUpdatedV1Processor(IEventProcessor[P2VcRoomLevelUpdatedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2VcRoomLevelUpdatedV1], None]) -> None: ...
    def type(self) -> type[P2VcRoomLevelUpdatedV1]: ...
    def do(self, data: P2VcRoomLevelUpdatedV1) -> None: ...
