from lark_oapi.core.construct import init as init

class AppendDimension:
    major_dimension: str | None
    length: int | None
    inherit_from_before: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppendDimensionBuilder: ...

class AppendDimensionBuilder:
    def __init__(self) -> None: ...
    def major_dimension(self, major_dimension: str) -> AppendDimensionBuilder: ...
    def length(self, length: int) -> AppendDimensionBuilder: ...
    def inherit_from_before(self, inherit_from_before: bool) -> AppendDimensionBuilder: ...
    def build(self) -> AppendDimension: ...
