from lark_oapi.core.construct import init as init

class BitableProperties:
    bitable_token: str | None
    table_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BitablePropertiesBuilder: ...

class BitablePropertiesBuilder:
    def __init__(self) -> None: ...
    def bitable_token(self, bitable_token: str) -> BitablePropertiesBuilder: ...
    def table_id(self, table_id: str) -> BitablePropertiesBuilder: ...
    def build(self) -> BitableProperties: ...
