from lark_oapi.core.construct import init as init

class BoolRuleValue:
    type: str | None
    number: str | None
    text: str | None
    time_period: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BoolRuleValueBuilder: ...

class BoolRuleValueBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> BoolRuleValueBuilder: ...
    def number(self, number: str) -> BoolRuleValueBuilder: ...
    def text(self, text: str) -> BoolRuleValueBuilder: ...
    def time_period(self, time_period: str) -> BoolRuleValueBuilder: ...
    def build(self) -> BoolRuleValue: ...
