from .bool_rule_value import BoolRuleValue as BoolRuleValue
from lark_oapi.core.construct import init as init

class BooleanRuleCondition:
    type: str | None
    boolean_conditional_values: list[BoolRuleValue] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BooleanRuleConditionBuilder: ...

class BooleanRuleConditionBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> BooleanRuleConditionBuilder: ...
    def boolean_conditional_values(self, boolean_conditional_values: list[BoolRuleValue]) -> BooleanRuleConditionBuilder: ...
    def build(self) -> BooleanRuleCondition: ...
