from lark_oapi.core.construct import init as init

class BottomBorderStyle:
    style: str | None
    color: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BottomBorderStyleBuilder: ...

class BottomBorderStyleBuilder:
    def __init__(self) -> None: ...
    def style(self, style: str) -> BottomBorderStyleBuilder: ...
    def color(self, color: str) -> BottomBorderStyleBuilder: ...
    def build(self) -> BottomBorderStyle: ...
