from lark_oapi.core.construct import init as init

class CellFontStyle:
    bold: bool | None
    italic: bool | None
    strikethrough: bool | None
    underline: bool | None
    foreground_color: str | None
    background_color: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CellFontStyleBuilder: ...

class CellFontStyleBuilder:
    def __init__(self) -> None: ...
    def bold(self, bold: bool) -> CellFontStyleBuilder: ...
    def italic(self, italic: bool) -> CellFontStyleBuilder: ...
    def strikethrough(self, strikethrough: bool) -> CellFontStyleBuilder: ...
    def underline(self, underline: bool) -> CellFontStyleBuilder: ...
    def foreground_color(self, foreground_color: str) -> CellFontStyleBuilder: ...
    def background_color(self, background_color: str) -> CellFontStyleBuilder: ...
    def build(self) -> CellFontStyle: ...
