from .alignment_style import AlignmentStyle as AlignmentStyle
from .border_style import BorderStyle as BorderStyle
from .cell_font_style import CellFontStyle as CellFontStyle
from lark_oapi.core.construct import init as init

class CellStyle:
    font_style: CellFontStyle | None
    border_style: BorderStyle | None
    alignment_style: AlignmentStyle | None
    wrap_strategy: str | None
    format: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CellStyleBuilder: ...

class CellStyleBuilder:
    def __init__(self) -> None: ...
    def font_style(self, font_style: CellFontStyle) -> CellStyleBuilder: ...
    def border_style(self, border_style: BorderStyle) -> CellStyleBuilder: ...
    def alignment_style(self, alignment_style: AlignmentStyle) -> CellStyleBuilder: ...
    def wrap_strategy(self, wrap_strategy: str) -> CellStyleBuilder: ...
    def format(self, format: str) -> CellStyleBuilder: ...
    def build(self) -> CellStyle: ...
