from lark_oapi.core.construct import init as init

class ClearStyleMultiRange:
    ranges: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ClearStyleMultiRangeBuilder: ...

class ClearStyleMultiRangeBuilder:
    def __init__(self) -> None: ...
    def ranges(self, ranges: list[str]) -> ClearStyleMultiRangeBuilder: ...
    def build(self) -> ClearStyleMultiRange: ...
