from .boolean_rule_condition import BooleanRuleCondition as BooleanRuleCondition
from lark_oapi.core.construct import init as init

class ConditionalFormatRule:
    boolean_rule: BooleanRuleCondition | None
    type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ConditionalFormatRuleBuilder: ...

class ConditionalFormatRuleBuilder:
    def __init__(self) -> None: ...
    def boolean_rule(self, boolean_rule: BooleanRuleCondition) -> ConditionalFormatRuleBuilder: ...
    def type(self, type: str) -> ConditionalFormatRuleBuilder: ...
    def build(self) -> ConditionalFormatRule: ...
