from .filter_view_condition import FilterViewCondition as FilterViewCondition
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateSpreadsheetSheetFilterViewConditionRequest(BaseRequest):
    spreadsheet_token: str | None
    sheet_id: str | None
    filter_view_id: str | None
    request_body: FilterViewCondition | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateSpreadsheetSheetFilterViewConditionRequestBuilder: ...

class CreateSpreadsheetSheetFilterViewConditionRequestBuilder:
    def __init__(self) -> None: ...
    def spreadsheet_token(self, spreadsheet_token: str) -> CreateSpreadsheetSheetFilterViewConditionRequestBuilder: ...
    def sheet_id(self, sheet_id: str) -> CreateSpreadsheetSheetFilterViewConditionRequestBuilder: ...
    def filter_view_id(self, filter_view_id: str) -> CreateSpreadsheetSheetFilterViewConditionRequestBuilder: ...
    def request_body(self, request_body: FilterViewCondition) -> CreateSpreadsheetSheetFilterViewConditionRequestBuilder: ...
    def build(self) -> CreateSpreadsheetSheetFilterViewConditionRequest: ...
