from .condition import Condition as Condition
from lark_oapi.core.construct import init as init

class CreateSheetFilter:
    range: str | None
    col: str | None
    condition: Condition | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateSheetFilterBuilder: ...

class CreateSheetFilterBuilder:
    def __init__(self) -> None: ...
    def range(self, range: str) -> CreateSheetFilterBuilder: ...
    def col(self, col: str) -> CreateSheetFilterBuilder: ...
    def condition(self, condition: Condition) -> CreateSheetFilterBuilder: ...
    def build(self) -> CreateSheetFilter: ...
