from .filter_view_condition import FilterViewCondition as FilterViewCondition
from lark_oapi.core.construct import init as init

class CreateSpreadsheetSheetFilterViewConditionResponseBody:
    condition: FilterViewCondition | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateSpreadsheetSheetFilterViewConditionResponseBodyBuilder: ...

class CreateSpreadsheetSheetFilterViewConditionResponseBodyBuilder:
    def __init__(self) -> None: ...
    def condition(self, condition: FilterViewCondition) -> CreateSpreadsheetSheetFilterViewConditionResponseBodyBuilder: ...
    def build(self) -> CreateSpreadsheetSheetFilterViewConditionResponseBody: ...
