from .data_validation import DataValidation as DataValidation
from lark_oapi.core.construct import init as init

class CreateDataValidation:
    range: str | None
    rule: DataValidation | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateDataValidationBuilder: ...

class CreateDataValidationBuilder:
    def __init__(self) -> None: ...
    def range(self, range: str) -> CreateDataValidationBuilder: ...
    def rule(self, rule: DataValidation) -> CreateDataValidationBuilder: ...
    def build(self) -> CreateDataValidation: ...
