from .filter_view import FilterView as FilterView
from lark_oapi.core.construct import init as init

class CreateSpreadsheetSheetFilterViewResponseBody:
    filter_view: FilterView | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateSpreadsheetSheetFilterViewResponseBodyBuilder: ...

class CreateSpreadsheetSheetFilterViewResponseBodyBuilder:
    def __init__(self) -> None: ...
    def filter_view(self, filter_view: FilterView) -> CreateSpreadsheetSheetFilterViewResponseBodyBuilder: ...
    def build(self) -> CreateSpreadsheetSheetFilterViewResponseBody: ...
