from lark_oapi.core.construct import init as init

class DataValidationValue:
    option_value: str | None
    option_color: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DataValidationValueBuilder: ...

class DataValidationValueBuilder:
    def __init__(self) -> None: ...
    def option_value(self, option_value: str) -> DataValidationValueBuilder: ...
    def option_color(self, option_color: str) -> DataValidationValueBuilder: ...
    def build(self) -> DataValidationValue: ...
