from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteSpreadsheetSheetFilterViewConditionRequest(BaseRequest):
    spreadsheet_token: str | None
    sheet_id: str | None
    filter_view_id: str | None
    condition_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteSpreadsheetSheetFilterViewConditionRequestBuilder: ...

class DeleteSpreadsheetSheetFilterViewConditionRequestBuilder:
    def __init__(self) -> None: ...
    def spreadsheet_token(self, spreadsheet_token: str) -> DeleteSpreadsheetSheetFilterViewConditionRequestBuilder: ...
    def sheet_id(self, sheet_id: str) -> DeleteSpreadsheetSheetFilterViewConditionRequestBuilder: ...
    def filter_view_id(self, filter_view_id: str) -> DeleteSpreadsheetSheetFilterViewConditionRequestBuilder: ...
    def condition_id(self, condition_id: str) -> DeleteSpreadsheetSheetFilterViewConditionRequestBuilder: ...
    def build(self) -> DeleteSpreadsheetSheetFilterViewConditionRequest: ...
