from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteSpreadsheetSheetFloatImageRequest(BaseRequest):
    spreadsheet_token: str | None
    sheet_id: str | None
    float_image_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteSpreadsheetSheetFloatImageRequestBuilder: ...

class DeleteSpreadsheetSheetFloatImageRequestBuilder:
    def __init__(self) -> None: ...
    def spreadsheet_token(self, spreadsheet_token: str) -> DeleteSpreadsheetSheetFloatImageRequestBuilder: ...
    def sheet_id(self, sheet_id: str) -> DeleteSpreadsheetSheetFloatImageRequestBuilder: ...
    def float_image_id(self, float_image_id: str) -> DeleteSpreadsheetSheetFloatImageRequestBuilder: ...
    def build(self) -> DeleteSpreadsheetSheetFloatImageRequest: ...
