from lark_oapi.core.construct import init as init

class DeleteSpreadsheetSheetFloatImageRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteSpreadsheetSheetFloatImageRequestBodyBuilder: ...

class DeleteSpreadsheetSheetFloatImageRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteSpreadsheetSheetFloatImageRequestBody: ...
