from lark_oapi.core.construct import init as init

class DeleteSpreadsheetSheetFilterViewRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteSpreadsheetSheetFilterViewRequestBodyBuilder: ...

class DeleteSpreadsheetSheetFilterViewRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteSpreadsheetSheetFilterViewRequestBody: ...
