from lark_oapi.core.construct import init as init

class DeleteSpreadsheetSheetFilterViewConditionRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteSpreadsheetSheetFilterViewConditionRequestBodyBuilder: ...

class DeleteSpreadsheetSheetFilterViewConditionRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteSpreadsheetSheetFilterViewConditionRequestBody: ...
