from lark_oapi.core.construct import init as init

class Dimension:
    major_dimension: str | None
    start_index: int | None
    end_index: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DimensionBuilder: ...

class DimensionBuilder:
    def __init__(self) -> None: ...
    def major_dimension(self, major_dimension: str) -> DimensionBuilder: ...
    def start_index(self, start_index: int) -> DimensionBuilder: ...
    def end_index(self, end_index: int) -> DimensionBuilder: ...
    def build(self) -> Dimension: ...
