from lark_oapi.core.construct import init as init

class DimensionProperties:
    hidden: bool | None
    pixel_size: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DimensionPropertiesBuilder: ...

class DimensionPropertiesBuilder:
    def __init__(self) -> None: ...
    def hidden(self, hidden: bool) -> DimensionPropertiesBuilder: ...
    def pixel_size(self, pixel_size: int) -> DimensionPropertiesBuilder: ...
    def build(self) -> DimensionProperties: ...
