from lark_oapi.core.construct import init as init

class FilterView:
    filter_view_id: str | None
    filter_view_name: str | None
    range: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FilterViewBuilder: ...

class FilterViewBuilder:
    def __init__(self) -> None: ...
    def filter_view_id(self, filter_view_id: str) -> FilterViewBuilder: ...
    def filter_view_name(self, filter_view_name: str) -> FilterViewBuilder: ...
    def range(self, range: str) -> FilterViewBuilder: ...
    def build(self) -> FilterView: ...
