from .find_replace_result import FindReplaceResult as FindReplaceResult
from lark_oapi.core.construct import init as init

class FindSpreadsheetSheetResponseBody:
    find_result: FindReplaceResult | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FindSpreadsheetSheetResponseBodyBuilder: ...

class FindSpreadsheetSheetResponseBodyBuilder:
    def __init__(self) -> None: ...
    def find_result(self, find_result: FindReplaceResult) -> FindSpreadsheetSheetResponseBodyBuilder: ...
    def build(self) -> FindSpreadsheetSheetResponseBody: ...
