from lark_oapi.core.construct import init as init

class GetSpreadsheet:
    title: str | None
    owner_id: str | None
    token: str | None
    url: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetSpreadsheetBuilder: ...

class GetSpreadsheetBuilder:
    def __init__(self) -> None: ...
    def title(self, title: str) -> GetSpreadsheetBuilder: ...
    def owner_id(self, owner_id: str) -> GetSpreadsheetBuilder: ...
    def token(self, token: str) -> GetSpreadsheetBuilder: ...
    def url(self, url: str) -> GetSpreadsheetBuilder: ...
    def build(self) -> GetSpreadsheet: ...
