from lark_oapi.core.construct import init as init

class GetSpreadsheetSheetFilterRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetSpreadsheetSheetFilterRequestBodyBuilder: ...

class GetSpreadsheetSheetFilterRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetSpreadsheetSheetFilterRequestBody: ...
