from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetSpreadsheetSheetFilterRequest(BaseRequest):
    spreadsheet_token: str | None
    sheet_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetSpreadsheetSheetFilterRequestBuilder: ...

class GetSpreadsheetSheetFilterRequestBuilder:
    def __init__(self) -> None: ...
    def spreadsheet_token(self, spreadsheet_token: str) -> GetSpreadsheetSheetFilterRequestBuilder: ...
    def sheet_id(self, sheet_id: str) -> GetSpreadsheetSheetFilterRequestBuilder: ...
    def build(self) -> GetSpreadsheetSheetFilterRequest: ...
