from lark_oapi.core.construct import init as init

class GetSpreadsheetSheetFilterViewConditionRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetSpreadsheetSheetFilterViewConditionRequestBodyBuilder: ...

class GetSpreadsheetSheetFilterViewConditionRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetSpreadsheetSheetFilterViewConditionRequestBody: ...
