from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetSpreadsheetSheetRequest(BaseRequest):
    spreadsheet_token: str | None
    sheet_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetSpreadsheetSheetRequestBuilder: ...

class GetSpreadsheetSheetRequestBuilder:
    def __init__(self) -> None: ...
    def spreadsheet_token(self, spreadsheet_token: str) -> GetSpreadsheetSheetRequestBuilder: ...
    def sheet_id(self, sheet_id: str) -> GetSpreadsheetSheetRequestBuilder: ...
    def build(self) -> GetSpreadsheetSheetRequest: ...
