from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetSpreadsheetRequest(BaseRequest):
    user_id_type: str | None
    spreadsheet_token: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetSpreadsheetRequestBuilder: ...

class GetSpreadsheetRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> GetSpreadsheetRequestBuilder: ...
    def spreadsheet_token(self, spreadsheet_token: str) -> GetSpreadsheetRequestBuilder: ...
    def build(self) -> GetSpreadsheetRequest: ...
