from lark_oapi.core.construct import init as init

class GridProperties:
    frozen_row_count: int | None
    frozen_column_count: int | None
    row_count: int | None
    column_count: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GridPropertiesBuilder: ...

class GridPropertiesBuilder:
    def __init__(self) -> None: ...
    def frozen_row_count(self, frozen_row_count: int) -> GridPropertiesBuilder: ...
    def frozen_column_count(self, frozen_column_count: int) -> GridPropertiesBuilder: ...
    def row_count(self, row_count: int) -> GridPropertiesBuilder: ...
    def column_count(self, column_count: int) -> GridPropertiesBuilder: ...
    def build(self) -> GridProperties: ...
