from .segment_style import SegmentStyle as SegmentStyle
from lark_oapi.core.construct import init as init

class Link:
    text: str | None
    link: str | None
    segment_styles: list[SegmentStyle] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LinkBuilder: ...

class LinkBuilder:
    def __init__(self) -> None: ...
    def text(self, text: str) -> LinkBuilder: ...
    def link(self, link: str) -> LinkBuilder: ...
    def segment_styles(self, segment_styles: list[SegmentStyle]) -> LinkBuilder: ...
    def build(self) -> Link: ...
