from .merge_range import MergeRange as MergeRange
from lark_oapi.core.construct import init as init

class MergeCell:
    range: MergeRange | None
    merge_type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MergeCellBuilder: ...

class MergeCellBuilder:
    def __init__(self) -> None: ...
    def range(self, range: MergeRange) -> MergeCellBuilder: ...
    def merge_type(self, merge_type: str) -> MergeCellBuilder: ...
    def build(self) -> MergeCell: ...
