from .dimension import Dimension as Dimension
from lark_oapi.core.construct import init as init

class MoveDimension:
    source: Dimension | None
    destination_index: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MoveDimensionBuilder: ...

class MoveDimensionBuilder:
    def __init__(self) -> None: ...
    def source(self, source: Dimension) -> MoveDimensionBuilder: ...
    def destination_index(self, destination_index: int) -> MoveDimensionBuilder: ...
    def build(self) -> MoveDimension: ...
