from .filter_view import FilterView as FilterView
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PatchSpreadsheetSheetFilterViewRequest(BaseRequest):
    spreadsheet_token: str | None
    sheet_id: str | None
    filter_view_id: str | None
    request_body: FilterView | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PatchSpreadsheetSheetFilterViewRequestBuilder: ...

class PatchSpreadsheetSheetFilterViewRequestBuilder:
    def __init__(self) -> None: ...
    def spreadsheet_token(self, spreadsheet_token: str) -> PatchSpreadsheetSheetFilterViewRequestBuilder: ...
    def sheet_id(self, sheet_id: str) -> PatchSpreadsheetSheetFilterViewRequestBuilder: ...
    def filter_view_id(self, filter_view_id: str) -> PatchSpreadsheetSheetFilterViewRequestBuilder: ...
    def request_body(self, request_body: FilterView) -> PatchSpreadsheetSheetFilterViewRequestBuilder: ...
    def build(self) -> PatchSpreadsheetSheetFilterViewRequest: ...
