from .float_image import FloatImage as FloatImage
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PatchSpreadsheetSheetFloatImageRequest(BaseRequest):
    spreadsheet_token: str | None
    sheet_id: str | None
    float_image_id: str | None
    request_body: FloatImage | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PatchSpreadsheetSheetFloatImageRequestBuilder: ...

class PatchSpreadsheetSheetFloatImageRequestBuilder:
    def __init__(self) -> None: ...
    def spreadsheet_token(self, spreadsheet_token: str) -> PatchSpreadsheetSheetFloatImageRequestBuilder: ...
    def sheet_id(self, sheet_id: str) -> PatchSpreadsheetSheetFloatImageRequestBuilder: ...
    def float_image_id(self, float_image_id: str) -> PatchSpreadsheetSheetFloatImageRequestBuilder: ...
    def request_body(self, request_body: FloatImage) -> PatchSpreadsheetSheetFloatImageRequestBuilder: ...
    def build(self) -> PatchSpreadsheetSheetFloatImageRequest: ...
