from lark_oapi.core.construct import init as init

class PlainTextValueRange:
    range: str | None
    values: list[list] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PlainTextValueRangeBuilder: ...

class PlainTextValueRangeBuilder:
    def __init__(self) -> None: ...
    def range(self, range: str) -> PlainTextValueRangeBuilder: ...
    def values(self, values: list[list]) -> PlainTextValueRangeBuilder: ...
    def build(self) -> PlainTextValueRange: ...
