from lark_oapi.core.construct import init as init

class ProtectedColumns:
    sheet_id: str | None
    start_index: int | None
    end_index: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ProtectedColumnsBuilder: ...

class ProtectedColumnsBuilder:
    def __init__(self) -> None: ...
    def sheet_id(self, sheet_id: str) -> ProtectedColumnsBuilder: ...
    def start_index(self, start_index: int) -> ProtectedColumnsBuilder: ...
    def end_index(self, end_index: int) -> ProtectedColumnsBuilder: ...
    def build(self) -> ProtectedColumns: ...
