from .sheet import Sheet as Sheet
from lark_oapi.core.construct import init as init

class QuerySpreadsheetSheetResponseBody:
    sheets: list[Sheet] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QuerySpreadsheetSheetResponseBodyBuilder: ...

class QuerySpreadsheetSheetResponseBodyBuilder:
    def __init__(self) -> None: ...
    def sheets(self, sheets: list[Sheet]) -> QuerySpreadsheetSheetResponseBodyBuilder: ...
    def build(self) -> QuerySpreadsheetSheetResponseBody: ...
