from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class QuerySpreadsheetSheetFilterViewConditionRequest(BaseRequest):
    spreadsheet_token: str | None
    sheet_id: str | None
    filter_view_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> QuerySpreadsheetSheetFilterViewConditionRequestBuilder: ...

class QuerySpreadsheetSheetFilterViewConditionRequestBuilder:
    def __init__(self) -> None: ...
    def spreadsheet_token(self, spreadsheet_token: str) -> QuerySpreadsheetSheetFilterViewConditionRequestBuilder: ...
    def sheet_id(self, sheet_id: str) -> QuerySpreadsheetSheetFilterViewConditionRequestBuilder: ...
    def filter_view_id(self, filter_view_id: str) -> QuerySpreadsheetSheetFilterViewConditionRequestBuilder: ...
    def build(self) -> QuerySpreadsheetSheetFilterViewConditionRequest: ...
