from lark_oapi.core.construct import init as init

class QuerySpreadsheetSheetRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QuerySpreadsheetSheetRequestBodyBuilder: ...

class QuerySpreadsheetSheetRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> QuerySpreadsheetSheetRequestBody: ...
