from lark_oapi.core.construct import init as init

class QuerySpreadsheetSheetFilterViewConditionRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QuerySpreadsheetSheetFilterViewConditionRequestBodyBuilder: ...

class QuerySpreadsheetSheetFilterViewConditionRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> QuerySpreadsheetSheetFilterViewConditionRequestBody: ...
