from lark_oapi.core.construct import init as init

class QuerySpreadsheetSheetFilterViewRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QuerySpreadsheetSheetFilterViewRequestBodyBuilder: ...

class QuerySpreadsheetSheetFilterViewRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> QuerySpreadsheetSheetFilterViewRequestBody: ...
