from .filter_view_condition import FilterViewCondition as FilterViewCondition
from lark_oapi.core.construct import init as init

class QuerySpreadsheetSheetFilterViewConditionResponseBody:
    items: list[FilterViewCondition] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QuerySpreadsheetSheetFilterViewConditionResponseBodyBuilder: ...

class QuerySpreadsheetSheetFilterViewConditionResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[FilterViewCondition]) -> QuerySpreadsheetSheetFilterViewConditionResponseBodyBuilder: ...
    def build(self) -> QuerySpreadsheetSheetFilterViewConditionResponseBody: ...
