from .replace import Replace as Replace
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ReplaceSpreadsheetSheetRequest(BaseRequest):
    spreadsheet_token: str | None
    sheet_id: str | None
    request_body: Replace | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ReplaceSpreadsheetSheetRequestBuilder: ...

class ReplaceSpreadsheetSheetRequestBuilder:
    def __init__(self) -> None: ...
    def spreadsheet_token(self, spreadsheet_token: str) -> ReplaceSpreadsheetSheetRequestBuilder: ...
    def sheet_id(self, sheet_id: str) -> ReplaceSpreadsheetSheetRequestBuilder: ...
    def request_body(self, request_body: Replace) -> ReplaceSpreadsheetSheetRequestBuilder: ...
    def build(self) -> ReplaceSpreadsheetSheetRequest: ...
