from .find_replace_result import FindReplaceResult as FindReplaceResult
from lark_oapi.core.construct import init as init

class ReplaceSpreadsheetSheetResponseBody:
    replace_result: FindReplaceResult | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReplaceSpreadsheetSheetResponseBodyBuilder: ...

class ReplaceSpreadsheetSheetResponseBodyBuilder:
    def __init__(self) -> None: ...
    def replace_result(self, replace_result: FindReplaceResult) -> ReplaceSpreadsheetSheetResponseBodyBuilder: ...
    def build(self) -> ReplaceSpreadsheetSheetResponseBody: ...
