from lark_oapi.core.construct import init as init

class RightBorderStyle:
    style: str | None
    color: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RightBorderStyleBuilder: ...

class RightBorderStyleBuilder:
    def __init__(self) -> None: ...
    def style(self, style: str) -> RightBorderStyleBuilder: ...
    def color(self, color: str) -> RightBorderStyleBuilder: ...
    def build(self) -> RightBorderStyle: ...
