from .grid_properties import GridProperties as GridProperties
from .merge_range import MergeRange as MergeRange
from lark_oapi.core.construct import init as init

class Sheet:
    sheet_id: str | None
    title: str | None
    index: int | None
    hidden: bool | None
    grid_properties: GridProperties | None
    resource_type: str | None
    merges: list[MergeRange] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SheetBuilder: ...

class SheetBuilder:
    def __init__(self) -> None: ...
    def sheet_id(self, sheet_id: str) -> SheetBuilder: ...
    def title(self, title: str) -> SheetBuilder: ...
    def index(self, index: int) -> SheetBuilder: ...
    def hidden(self, hidden: bool) -> SheetBuilder: ...
    def grid_properties(self, grid_properties: GridProperties) -> SheetBuilder: ...
    def resource_type(self, resource_type: str) -> SheetBuilder: ...
    def merges(self, merges: list[MergeRange]) -> SheetBuilder: ...
    def build(self) -> Sheet: ...
