from lark_oapi.core.construct import init as init

class SheetProperties:
    row_count: int | None
    column_count: int | None
    frozen_row_count: int | None
    frozen_column_count: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SheetPropertiesBuilder: ...

class SheetPropertiesBuilder:
    def __init__(self) -> None: ...
    def row_count(self, row_count: int) -> SheetPropertiesBuilder: ...
    def column_count(self, column_count: int) -> SheetPropertiesBuilder: ...
    def frozen_row_count(self, frozen_row_count: int) -> SheetPropertiesBuilder: ...
    def frozen_column_count(self, frozen_column_count: int) -> SheetPropertiesBuilder: ...
    def build(self) -> SheetProperties: ...
