from .segment_style import SegmentStyle as SegmentStyle
from lark_oapi.core.construct import init as init

class Text:
    text: str | None
    segment_style: SegmentStyle | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TextBuilder: ...

class TextBuilder:
    def __init__(self) -> None: ...
    def text(self, text: str) -> TextBuilder: ...
    def segment_style(self, segment_style: SegmentStyle) -> TextBuilder: ...
    def build(self) -> Text: ...
