from lark_oapi.core.construct import init as init

class ValueElementSingleOption:
    data_validation_id: int | None
    data_validiton_value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ValueElementSingleOptionBuilder: ...

class ValueElementSingleOptionBuilder:
    def __init__(self) -> None: ...
    def data_validation_id(self, data_validation_id: int) -> ValueElementSingleOptionBuilder: ...
    def data_validiton_value(self, data_validiton_value: str) -> ValueElementSingleOptionBuilder: ...
    def build(self) -> ValueElementSingleOption: ...
