from lark_oapi.core.construct import init as init

class ValueElement:
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ValueElementBuilder: ...

class ValueElementBuilder:
    def __init__(self) -> None: ...
    def value(self, value: str) -> ValueElementBuilder: ...
    def build(self) -> ValueElement: ...
