from .cell_value import CellValue as CellValue
from lark_oapi.core.construct import init as init

class Value:
    range: str | None
    values: list[list] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ValueBuilder: ...

class ValueBuilder:
    def __init__(self) -> None: ...
    def range(self, range: str) -> ValueBuilder: ...
    def values(self, values: list[list]) -> ValueBuilder: ...
    def build(self) -> Value: ...
