from lark_oapi.core.construct import init as init

class Avatar:
    avatar_origin: str | None
    avatar_72: str | None
    avatar_240: str | None
    avatar_640: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AvatarBuilder: ...

class AvatarBuilder:
    def __init__(self) -> None: ...
    def avatar_origin(self, avatar_origin: str) -> AvatarBuilder: ...
    def avatar_72(self, avatar_72: str) -> AvatarBuilder: ...
    def avatar_240(self, avatar_240: str) -> AvatarBuilder: ...
    def avatar_640(self, avatar_640: str) -> AvatarBuilder: ...
    def build(self) -> Avatar: ...
