from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class QueryTenantProductAssignInfoRequest(BaseRequest):
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> QueryTenantProductAssignInfoRequestBuilder: ...

class QueryTenantProductAssignInfoRequestBuilder:
    def __init__(self) -> None: ...
    def build(self) -> QueryTenantProductAssignInfoRequest: ...
