from lark_oapi.core.construct import init as init

class QueryTenantRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryTenantRequestBodyBuilder: ...

class QueryTenantRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> QueryTenantRequestBody: ...
