from .tenant_assign_info import TenantAssignInfo as TenantAssignInfo
from lark_oapi.core.construct import init as init

class QueryTenantProductAssignInfoResponseBody:
    assign_info_list: list[TenantAssignInfo] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryTenantProductAssignInfoResponseBodyBuilder: ...

class QueryTenantProductAssignInfoResponseBodyBuilder:
    def __init__(self) -> None: ...
    def assign_info_list(self, assign_info_list: list[TenantAssignInfo]) -> QueryTenantProductAssignInfoResponseBodyBuilder: ...
    def build(self) -> QueryTenantProductAssignInfoResponseBody: ...
