from .product_i18n_name import ProductI18nName as ProductI18nName
from lark_oapi.core.construct import init as init

class TenantAssignInfo:
    subscription_id: int | None
    license_plan_key: str | None
    product_name: str | None
    i18n_name: ProductI18nName | None
    total_seats: int | None
    assigned_seats: int | None
    start_time: int | None
    end_time: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TenantAssignInfoBuilder: ...

class TenantAssignInfoBuilder:
    def __init__(self) -> None: ...
    def subscription_id(self, subscription_id: int) -> TenantAssignInfoBuilder: ...
    def license_plan_key(self, license_plan_key: str) -> TenantAssignInfoBuilder: ...
    def product_name(self, product_name: str) -> TenantAssignInfoBuilder: ...
    def i18n_name(self, i18n_name: ProductI18nName) -> TenantAssignInfoBuilder: ...
    def total_seats(self, total_seats: int) -> TenantAssignInfoBuilder: ...
    def assigned_seats(self, assigned_seats: int) -> TenantAssignInfoBuilder: ...
    def start_time(self, start_time: int) -> TenantAssignInfoBuilder: ...
    def end_time(self, end_time: int) -> TenantAssignInfoBuilder: ...
    def build(self) -> TenantAssignInfo: ...
