from .avatar import Avatar as Avatar
from lark_oapi.core.construct import init as init

class Tenant:
    name: str | None
    display_id: str | None
    tenant_tag: int | None
    tenant_key: str | None
    avatar: Avatar | None
    domain: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TenantBuilder: ...

class TenantBuilder:
    def __init__(self) -> None: ...
    def name(self, name: str) -> TenantBuilder: ...
    def display_id(self, display_id: str) -> TenantBuilder: ...
    def tenant_tag(self, tenant_tag: int) -> TenantBuilder: ...
    def tenant_key(self, tenant_key: str) -> TenantBuilder: ...
    def avatar(self, avatar: Avatar) -> TenantBuilder: ...
    def domain(self, domain: str) -> TenantBuilder: ...
    def build(self) -> Tenant: ...
