from ..model.batch_close_system_status_request import BatchCloseSystemStatusRequest as BatchCloseSystemStatusRequest
from ..model.batch_close_system_status_response import BatchCloseSystemStatusResponse as BatchCloseSystemStatusResponse
from ..model.batch_open_system_status_request import BatchOpenSystemStatusRequest as BatchOpenSystemStatusRequest
from ..model.batch_open_system_status_response import BatchOpenSystemStatusResponse as BatchOpenSystemStatusResponse
from ..model.create_system_status_request import CreateSystemStatusRequest as CreateSystemStatusRequest
from ..model.create_system_status_response import CreateSystemStatusResponse as CreateSystemStatusResponse
from ..model.delete_system_status_request import DeleteSystemStatusRequest as DeleteSystemStatusRequest
from ..model.delete_system_status_response import DeleteSystemStatusResponse as DeleteSystemStatusResponse
from ..model.list_system_status_request import ListSystemStatusRequest as ListSystemStatusRequest
from ..model.list_system_status_response import ListSystemStatusResponse as ListSystemStatusResponse
from ..model.patch_system_status_request import PatchSystemStatusRequest as PatchSystemStatusRequest
from ..model.patch_system_status_response import PatchSystemStatusResponse as PatchSystemStatusResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class SystemStatus:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def batch_close(self, request: BatchCloseSystemStatusRequest, option: RequestOption | None = None) -> BatchCloseSystemStatusResponse: ...
    async def abatch_close(self, request: BatchCloseSystemStatusRequest, option: RequestOption | None = None) -> BatchCloseSystemStatusResponse: ...
    def batch_open(self, request: BatchOpenSystemStatusRequest, option: RequestOption | None = None) -> BatchOpenSystemStatusResponse: ...
    async def abatch_open(self, request: BatchOpenSystemStatusRequest, option: RequestOption | None = None) -> BatchOpenSystemStatusResponse: ...
    def create(self, request: CreateSystemStatusRequest, option: RequestOption | None = None) -> CreateSystemStatusResponse: ...
    async def acreate(self, request: CreateSystemStatusRequest, option: RequestOption | None = None) -> CreateSystemStatusResponse: ...
    def delete(self, request: DeleteSystemStatusRequest, option: RequestOption | None = None) -> DeleteSystemStatusResponse: ...
    async def adelete(self, request: DeleteSystemStatusRequest, option: RequestOption | None = None) -> DeleteSystemStatusResponse: ...
    def list(self, request: ListSystemStatusRequest, option: RequestOption | None = None) -> ListSystemStatusResponse: ...
    async def alist(self, request: ListSystemStatusRequest, option: RequestOption | None = None) -> ListSystemStatusResponse: ...
    def patch(self, request: PatchSystemStatusRequest, option: RequestOption | None = None) -> PatchSystemStatusResponse: ...
    async def apatch(self, request: PatchSystemStatusRequest, option: RequestOption | None = None) -> PatchSystemStatusResponse: ...
