from lark_oapi.core.construct import init as init

class BatchUpdateCardRequestBody:
    uuid: str | None
    sequence: int | None
    actions: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchUpdateCardRequestBodyBuilder: ...

class BatchUpdateCardRequestBodyBuilder:
    def __init__(self) -> None: ...
    def uuid(self, uuid: str) -> BatchUpdateCardRequestBodyBuilder: ...
    def sequence(self, sequence: int) -> BatchUpdateCardRequestBodyBuilder: ...
    def actions(self, actions: str) -> BatchUpdateCardRequestBodyBuilder: ...
    def build(self) -> BatchUpdateCardRequestBody: ...
