from lark_oapi.core.construct import init as init

class CallbackActionContext:
    open_message_id: str | None
    open_chat_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CallbackActionContextBuilder: ...

class CallbackActionContextBuilder:
    def __init__(self) -> None: ...
    def open_message_id(self, open_message_id: str) -> CallbackActionContextBuilder: ...
    def open_chat_id(self, open_chat_id: str) -> CallbackActionContextBuilder: ...
    def build(self) -> CallbackActionContext: ...
