from lark_oapi.core.construct import init as init

class CardTemplate:
    template_id: str | None
    template_name: str | None
    template_owner: str | None
    template_version_name: str | None
    schema_version: str | None
    status: str | None
    create_time: str | None
    update_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CardTemplateBuilder: ...

class CardTemplateBuilder:
    def __init__(self) -> None: ...
    def template_id(self, template_id: str) -> CardTemplateBuilder: ...
    def template_name(self, template_name: str) -> CardTemplateBuilder: ...
    def template_owner(self, template_owner: str) -> CardTemplateBuilder: ...
    def template_version_name(self, template_version_name: str) -> CardTemplateBuilder: ...
    def schema_version(self, schema_version: str) -> CardTemplateBuilder: ...
    def status(self, status: str) -> CardTemplateBuilder: ...
    def create_time(self, create_time: str) -> CardTemplateBuilder: ...
    def update_time(self, update_time: str) -> CardTemplateBuilder: ...
    def build(self) -> CardTemplate: ...
