from .summary import Summary as Summary
from lark_oapi.core.construct import init as init

class Config:
    enable_forward: bool | None
    streaming_mode: bool | None
    summary: Summary | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ConfigBuilder: ...

class ConfigBuilder:
    def __init__(self) -> None: ...
    def enable_forward(self, enable_forward: bool) -> ConfigBuilder: ...
    def streaming_mode(self, streaming_mode: bool) -> ConfigBuilder: ...
    def summary(self, summary: Summary) -> ConfigBuilder: ...
    def build(self) -> Config: ...
