from lark_oapi.core.construct import init as init

class ContentCardElementRequestBody:
    uuid: str | None
    content: str | None
    sequence: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ContentCardElementRequestBodyBuilder: ...

class ContentCardElementRequestBodyBuilder:
    def __init__(self) -> None: ...
    def uuid(self, uuid: str) -> ContentCardElementRequestBodyBuilder: ...
    def content(self, content: str) -> ContentCardElementRequestBodyBuilder: ...
    def sequence(self, sequence: int) -> ContentCardElementRequestBodyBuilder: ...
    def build(self) -> ContentCardElementRequestBody: ...
