from .card_link import CardLink as CardLink
from .element import Element as Element
from .header import Header as Header
from lark_oapi.core.construct import init as init

class Data:
    schema: str | None
    body: Element | None
    header: Header | None
    card_link: CardLink | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DataBuilder: ...

class DataBuilder:
    def __init__(self) -> None: ...
    def schema(self, schema: str) -> DataBuilder: ...
    def body(self, body: Element) -> DataBuilder: ...
    def header(self, header: Header) -> DataBuilder: ...
    def card_link(self, card_link: CardLink) -> DataBuilder: ...
    def build(self) -> Data: ...
