from .delete_card_element_request_body import DeleteCardElementRequestBody as DeleteCardElementRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteCardElementRequest(BaseRequest):
    card_id: str | None
    element_id: str | None
    request_body: DeleteCardElementRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteCardElementRequestBuilder: ...

class DeleteCardElementRequestBuilder:
    def __init__(self) -> None: ...
    def card_id(self, card_id: str) -> DeleteCardElementRequestBuilder: ...
    def element_id(self, element_id: str) -> DeleteCardElementRequestBuilder: ...
    def request_body(self, request_body: DeleteCardElementRequestBody) -> DeleteCardElementRequestBuilder: ...
    def build(self) -> DeleteCardElementRequest: ...
