from lark_oapi.core.construct import init as init

class DeleteCardElementResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteCardElementResponseBodyBuilder: ...

class DeleteCardElementResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteCardElementResponseBody: ...
