from lark_oapi.core.construct import init as init

class Header:
    title: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> HeaderBuilder: ...

class HeaderBuilder:
    def __init__(self) -> None: ...
    def title(self, title: str) -> HeaderBuilder: ...
    def build(self) -> Header: ...
