from lark_oapi.core.construct import init as init

class KaCardTemplateVariable:
    variable_type: str | None
    name: str | None
    description: str | None
    config: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> KaCardTemplateVariableBuilder: ...

class KaCardTemplateVariableBuilder:
    def __init__(self) -> None: ...
    def variable_type(self, variable_type: str) -> KaCardTemplateVariableBuilder: ...
    def name(self, name: str) -> KaCardTemplateVariableBuilder: ...
    def description(self, description: str) -> KaCardTemplateVariableBuilder: ...
    def config(self, config: str) -> KaCardTemplateVariableBuilder: ...
    def build(self) -> KaCardTemplateVariable: ...
