from .ka_card_template_variable import KaCardTemplateVariable as KaCardTemplateVariable
from lark_oapi.core.construct import init as init

class KaCardTemplateOld:
    template_id: str | None
    name: str | None
    biz_ext: str | None
    lock_status: int | None
    status: int | None
    mock_data: str | None
    content: str | None
    draft_content: str | None
    create_time: str | None
    update_time: str | None
    creator_id: str | None
    variables: list[KaCardTemplateVariable] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> KaCardTemplateOldBuilder: ...

class KaCardTemplateOldBuilder:
    def __init__(self) -> None: ...
    def template_id(self, template_id: str) -> KaCardTemplateOldBuilder: ...
    def name(self, name: str) -> KaCardTemplateOldBuilder: ...
    def biz_ext(self, biz_ext: str) -> KaCardTemplateOldBuilder: ...
    def lock_status(self, lock_status: int) -> KaCardTemplateOldBuilder: ...
    def status(self, status: int) -> KaCardTemplateOldBuilder: ...
    def mock_data(self, mock_data: str) -> KaCardTemplateOldBuilder: ...
    def content(self, content: str) -> KaCardTemplateOldBuilder: ...
    def draft_content(self, draft_content: str) -> KaCardTemplateOldBuilder: ...
    def create_time(self, create_time: str) -> KaCardTemplateOldBuilder: ...
    def update_time(self, update_time: str) -> KaCardTemplateOldBuilder: ...
    def creator_id(self, creator_id: str) -> KaCardTemplateOldBuilder: ...
    def variables(self, variables: list[KaCardTemplateVariable]) -> KaCardTemplateOldBuilder: ...
    def build(self) -> KaCardTemplateOld: ...
