from lark_oapi.core.construct import init as init

class Params:
    type: str | None
    target_element_id: str | None
    elements: list[str] | None
    element_ids: list[str] | None
    element_id: str | None
    partial_element: str | None
    element: str | None
    settings: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ParamsBuilder: ...

class ParamsBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> ParamsBuilder: ...
    def target_element_id(self, target_element_id: str) -> ParamsBuilder: ...
    def elements(self, elements: list[str]) -> ParamsBuilder: ...
    def element_ids(self, element_ids: list[str]) -> ParamsBuilder: ...
    def element_id(self, element_id: str) -> ParamsBuilder: ...
    def partial_element(self, partial_element: str) -> ParamsBuilder: ...
    def element(self, element: str) -> ParamsBuilder: ...
    def settings(self, settings: str) -> ParamsBuilder: ...
    def build(self) -> Params: ...
