from lark_oapi.core.construct import init as init

class PatchCardElementRequestBody:
    partial_element: str | None
    uuid: str | None
    sequence: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchCardElementRequestBodyBuilder: ...

class PatchCardElementRequestBodyBuilder:
    def __init__(self) -> None: ...
    def partial_element(self, partial_element: str) -> PatchCardElementRequestBodyBuilder: ...
    def uuid(self, uuid: str) -> PatchCardElementRequestBodyBuilder: ...
    def sequence(self, sequence: int) -> PatchCardElementRequestBodyBuilder: ...
    def build(self) -> PatchCardElementRequestBody: ...
