from .card import Card as Card
from lark_oapi.core.construct import init as init

class UpdateCardRequestBody:
    card: Card | None
    uuid: str | None
    sequence: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateCardRequestBodyBuilder: ...

class UpdateCardRequestBodyBuilder:
    def __init__(self) -> None: ...
    def card(self, card: Card) -> UpdateCardRequestBodyBuilder: ...
    def uuid(self, uuid: str) -> UpdateCardRequestBodyBuilder: ...
    def sequence(self, sequence: int) -> UpdateCardRequestBodyBuilder: ...
    def build(self) -> UpdateCardRequestBody: ...
