from lark_oapi.core.construct import init as init

class UpdateCardResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateCardResponseBodyBuilder: ...

class UpdateCardResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> UpdateCardResponseBody: ...
