from lark_oapi.core.construct import init as init

class CreateEntityRequestBody:
    title: str | None
    block_type_id: str | None
    source_data: str | None
    source_meta: str | None
    version: int | None
    source_link: str | None
    owner: str | None
    extra: str | None
    i18n_summary: str | None
    i18n_preview: str | None
    summary: str | None
    preview: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateEntityRequestBodyBuilder: ...

class CreateEntityRequestBodyBuilder:
    def __init__(self) -> None: ...
    def title(self, title: str) -> CreateEntityRequestBodyBuilder: ...
    def block_type_id(self, block_type_id: str) -> CreateEntityRequestBodyBuilder: ...
    def source_data(self, source_data: str) -> CreateEntityRequestBodyBuilder: ...
    def source_meta(self, source_meta: str) -> CreateEntityRequestBodyBuilder: ...
    def version(self, version: int) -> CreateEntityRequestBodyBuilder: ...
    def source_link(self, source_link: str) -> CreateEntityRequestBodyBuilder: ...
    def owner(self, owner: str) -> CreateEntityRequestBodyBuilder: ...
    def extra(self, extra: str) -> CreateEntityRequestBodyBuilder: ...
    def i18n_summary(self, i18n_summary: str) -> CreateEntityRequestBodyBuilder: ...
    def i18n_preview(self, i18n_preview: str) -> CreateEntityRequestBodyBuilder: ...
    def summary(self, summary: str) -> CreateEntityRequestBodyBuilder: ...
    def preview(self, preview: str) -> CreateEntityRequestBodyBuilder: ...
    def build(self) -> CreateEntityRequestBody: ...
