from .create_entity_request_body import CreateEntityRequestBody as CreateEntityRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateEntityRequest(BaseRequest):
    request_body: CreateEntityRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateEntityRequestBuilder: ...

class CreateEntityRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: CreateEntityRequestBody) -> CreateEntityRequestBuilder: ...
    def build(self) -> CreateEntityRequest: ...
