from .entity import Entity as Entity
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UpdateEntityRequest(BaseRequest):
    block_id: str | None
    request_body: Entity | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UpdateEntityRequestBuilder: ...

class UpdateEntityRequestBuilder:
    def __init__(self) -> None: ...
    def block_id(self, block_id: str) -> UpdateEntityRequestBuilder: ...
    def request_body(self, request_body: Entity) -> UpdateEntityRequestBuilder: ...
    def build(self) -> UpdateEntityRequest: ...
