from lark_oapi.core.construct import init as init

class UpdateEntityResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateEntityResponseBodyBuilder: ...

class UpdateEntityResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> UpdateEntityResponseBody: ...
