from .verification import Verification as Verification
from lark_oapi.core.construct import init as init

class GetVerificationResponseBody:
    verification: Verification | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetVerificationResponseBodyBuilder: ...

class GetVerificationResponseBodyBuilder:
    def __init__(self) -> None: ...
    def verification(self, verification: Verification) -> GetVerificationResponseBodyBuilder: ...
    def build(self) -> GetVerificationResponseBody: ...
