from lark_oapi.core.construct import init as init

class GetVerificationRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetVerificationRequestBodyBuilder: ...

class GetVerificationRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetVerificationRequestBody: ...
