from ..model.create_mailgroup_request import CreateMailgroupRequest as CreateMailgroupRequest
from ..model.create_mailgroup_response import CreateMailgroupResponse as CreateMailgroupResponse
from ..model.delete_mailgroup_request import DeleteMailgroupRequest as DeleteMailgroupRequest
from ..model.delete_mailgroup_response import DeleteMailgroupResponse as DeleteMailgroupResponse
from ..model.get_mailgroup_request import GetMailgroupRequest as GetMailgroupRequest
from ..model.get_mailgroup_response import GetMailgroupResponse as GetMailgroupResponse
from ..model.list_mailgroup_request import ListMailgroupRequest as ListMailgroupRequest
from ..model.list_mailgroup_response import ListMailgroupResponse as ListMailgroupResponse
from ..model.patch_mailgroup_request import PatchMailgroupRequest as PatchMailgroupRequest
from ..model.patch_mailgroup_response import PatchMailgroupResponse as PatchMailgroupResponse
from ..model.update_mailgroup_request import UpdateMailgroupRequest as UpdateMailgroupRequest
from ..model.update_mailgroup_response import UpdateMailgroupResponse as UpdateMailgroupResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class Mailgroup:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def create(self, request: CreateMailgroupRequest, option: RequestOption | None = None) -> CreateMailgroupResponse: ...
    async def acreate(self, request: CreateMailgroupRequest, option: RequestOption | None = None) -> CreateMailgroupResponse: ...
    def delete(self, request: DeleteMailgroupRequest, option: RequestOption | None = None) -> DeleteMailgroupResponse: ...
    async def adelete(self, request: DeleteMailgroupRequest, option: RequestOption | None = None) -> DeleteMailgroupResponse: ...
    def get(self, request: GetMailgroupRequest, option: RequestOption | None = None) -> GetMailgroupResponse: ...
    async def aget(self, request: GetMailgroupRequest, option: RequestOption | None = None) -> GetMailgroupResponse: ...
    def list(self, request: ListMailgroupRequest, option: RequestOption | None = None) -> ListMailgroupResponse: ...
    async def alist(self, request: ListMailgroupRequest, option: RequestOption | None = None) -> ListMailgroupResponse: ...
    def patch(self, request: PatchMailgroupRequest, option: RequestOption | None = None) -> PatchMailgroupResponse: ...
    async def apatch(self, request: PatchMailgroupRequest, option: RequestOption | None = None) -> PatchMailgroupResponse: ...
    def update(self, request: UpdateMailgroupRequest, option: RequestOption | None = None) -> UpdateMailgroupResponse: ...
    async def aupdate(self, request: UpdateMailgroupRequest, option: RequestOption | None = None) -> UpdateMailgroupResponse: ...
