from ..model.batch_create_mailgroup_manager_request import BatchCreateMailgroupManagerRequest as BatchCreateMailgroupManagerRequest
from ..model.batch_create_mailgroup_manager_response import BatchCreateMailgroupManagerResponse as BatchCreateMailgroupManagerResponse
from ..model.batch_delete_mailgroup_manager_request import BatchDeleteMailgroupManagerRequest as BatchDeleteMailgroupManagerRequest
from ..model.batch_delete_mailgroup_manager_response import BatchDeleteMailgroupManagerResponse as BatchDeleteMailgroupManagerResponse
from ..model.list_mailgroup_manager_request import ListMailgroupManagerRequest as ListMailgroupManagerRequest
from ..model.list_mailgroup_manager_response import ListMailgroupManagerResponse as ListMailgroupManagerResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class MailgroupManager:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def batch_create(self, request: BatchCreateMailgroupManagerRequest, option: RequestOption | None = None) -> BatchCreateMailgroupManagerResponse: ...
    async def abatch_create(self, request: BatchCreateMailgroupManagerRequest, option: RequestOption | None = None) -> BatchCreateMailgroupManagerResponse: ...
    def batch_delete(self, request: BatchDeleteMailgroupManagerRequest, option: RequestOption | None = None) -> BatchDeleteMailgroupManagerResponse: ...
    async def abatch_delete(self, request: BatchDeleteMailgroupManagerRequest, option: RequestOption | None = None) -> BatchDeleteMailgroupManagerResponse: ...
    def list(self, request: ListMailgroupManagerRequest, option: RequestOption | None = None) -> ListMailgroupManagerResponse: ...
    async def alist(self, request: ListMailgroupManagerRequest, option: RequestOption | None = None) -> ListMailgroupManagerResponse: ...
