from ..model.create_public_mailbox_request import CreatePublicMailboxRequest as CreatePublicMailboxRequest
from ..model.create_public_mailbox_response import CreatePublicMailboxResponse as CreatePublicMailboxResponse
from ..model.delete_public_mailbox_request import DeletePublicMailboxRequest as DeletePublicMailboxRequest
from ..model.delete_public_mailbox_response import DeletePublicMailboxResponse as DeletePublicMailboxResponse
from ..model.get_public_mailbox_request import GetPublicMailboxRequest as GetPublicMailboxRequest
from ..model.get_public_mailbox_response import GetPublicMailboxResponse as GetPublicMailboxResponse
from ..model.list_public_mailbox_request import ListPublicMailboxRequest as ListPublicMailboxRequest
from ..model.list_public_mailbox_response import ListPublicMailboxResponse as ListPublicMailboxResponse
from ..model.patch_public_mailbox_request import PatchPublicMailboxRequest as PatchPublicMailboxRequest
from ..model.patch_public_mailbox_response import PatchPublicMailboxResponse as PatchPublicMailboxResponse
from ..model.remove_to_recycle_bin_public_mailbox_request import RemoveToRecycleBinPublicMailboxRequest as RemoveToRecycleBinPublicMailboxRequest
from ..model.remove_to_recycle_bin_public_mailbox_response import RemoveToRecycleBinPublicMailboxResponse as RemoveToRecycleBinPublicMailboxResponse
from ..model.update_public_mailbox_request import UpdatePublicMailboxRequest as UpdatePublicMailboxRequest
from ..model.update_public_mailbox_response import UpdatePublicMailboxResponse as UpdatePublicMailboxResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class PublicMailbox:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def create(self, request: CreatePublicMailboxRequest, option: RequestOption | None = None) -> CreatePublicMailboxResponse: ...
    async def acreate(self, request: CreatePublicMailboxRequest, option: RequestOption | None = None) -> CreatePublicMailboxResponse: ...
    def delete(self, request: DeletePublicMailboxRequest, option: RequestOption | None = None) -> DeletePublicMailboxResponse: ...
    async def adelete(self, request: DeletePublicMailboxRequest, option: RequestOption | None = None) -> DeletePublicMailboxResponse: ...
    def get(self, request: GetPublicMailboxRequest, option: RequestOption | None = None) -> GetPublicMailboxResponse: ...
    async def aget(self, request: GetPublicMailboxRequest, option: RequestOption | None = None) -> GetPublicMailboxResponse: ...
    def list(self, request: ListPublicMailboxRequest, option: RequestOption | None = None) -> ListPublicMailboxResponse: ...
    async def alist(self, request: ListPublicMailboxRequest, option: RequestOption | None = None) -> ListPublicMailboxResponse: ...
    def patch(self, request: PatchPublicMailboxRequest, option: RequestOption | None = None) -> PatchPublicMailboxResponse: ...
    async def apatch(self, request: PatchPublicMailboxRequest, option: RequestOption | None = None) -> PatchPublicMailboxResponse: ...
    def remove_to_recycle_bin(self, request: RemoveToRecycleBinPublicMailboxRequest, option: RequestOption | None = None) -> RemoveToRecycleBinPublicMailboxResponse: ...
    async def aremove_to_recycle_bin(self, request: RemoveToRecycleBinPublicMailboxRequest, option: RequestOption | None = None) -> RemoveToRecycleBinPublicMailboxResponse: ...
    def update(self, request: UpdatePublicMailboxRequest, option: RequestOption | None = None) -> UpdatePublicMailboxResponse: ...
    async def aupdate(self, request: UpdatePublicMailboxRequest, option: RequestOption | None = None) -> UpdatePublicMailboxResponse: ...
