from ..model.create_user_mailbox_folder_request import CreateUserMailboxFolderRequest as CreateUserMailboxFolderRequest
from ..model.create_user_mailbox_folder_response import CreateUserMailboxFolderResponse as CreateUserMailboxFolderResponse
from ..model.delete_user_mailbox_folder_request import DeleteUserMailboxFolderRequest as DeleteUserMailboxFolderRequest
from ..model.delete_user_mailbox_folder_response import DeleteUserMailboxFolderResponse as DeleteUserMailboxFolderResponse
from ..model.list_user_mailbox_folder_request import ListUserMailboxFolderRequest as ListUserMailboxFolderRequest
from ..model.list_user_mailbox_folder_response import ListUserMailboxFolderResponse as ListUserMailboxFolderResponse
from ..model.patch_user_mailbox_folder_request import PatchUserMailboxFolderRequest as PatchUserMailboxFolderRequest
from ..model.patch_user_mailbox_folder_response import PatchUserMailboxFolderResponse as PatchUserMailboxFolderResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class UserMailboxFolder:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def create(self, request: CreateUserMailboxFolderRequest, option: RequestOption | None = None) -> CreateUserMailboxFolderResponse: ...
    async def acreate(self, request: CreateUserMailboxFolderRequest, option: RequestOption | None = None) -> CreateUserMailboxFolderResponse: ...
    def delete(self, request: DeleteUserMailboxFolderRequest, option: RequestOption | None = None) -> DeleteUserMailboxFolderResponse: ...
    async def adelete(self, request: DeleteUserMailboxFolderRequest, option: RequestOption | None = None) -> DeleteUserMailboxFolderResponse: ...
    def list(self, request: ListUserMailboxFolderRequest, option: RequestOption | None = None) -> ListUserMailboxFolderResponse: ...
    async def alist(self, request: ListUserMailboxFolderRequest, option: RequestOption | None = None) -> ListUserMailboxFolderResponse: ...
    def patch(self, request: PatchUserMailboxFolderRequest, option: RequestOption | None = None) -> PatchUserMailboxFolderResponse: ...
    async def apatch(self, request: PatchUserMailboxFolderRequest, option: RequestOption | None = None) -> PatchUserMailboxFolderResponse: ...
