from ..model.create_user_mailbox_rule_request import CreateUserMailboxRuleRequest as CreateUserMailboxRuleRequest
from ..model.create_user_mailbox_rule_response import CreateUserMailboxRuleResponse as CreateUserMailboxRuleResponse
from ..model.delete_user_mailbox_rule_request import DeleteUserMailboxRuleRequest as DeleteUserMailboxRuleRequest
from ..model.delete_user_mailbox_rule_response import DeleteUserMailboxRuleResponse as DeleteUserMailboxRuleResponse
from ..model.list_user_mailbox_rule_request import ListUserMailboxRuleRequest as ListUserMailboxRuleRequest
from ..model.list_user_mailbox_rule_response import ListUserMailboxRuleResponse as ListUserMailboxRuleResponse
from ..model.reorder_user_mailbox_rule_request import ReorderUserMailboxRuleRequest as ReorderUserMailboxRuleRequest
from ..model.reorder_user_mailbox_rule_response import ReorderUserMailboxRuleResponse as ReorderUserMailboxRuleResponse
from ..model.update_user_mailbox_rule_request import UpdateUserMailboxRuleRequest as UpdateUserMailboxRuleRequest
from ..model.update_user_mailbox_rule_response import UpdateUserMailboxRuleResponse as UpdateUserMailboxRuleResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class UserMailboxRule:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def create(self, request: CreateUserMailboxRuleRequest, option: RequestOption | None = None) -> CreateUserMailboxRuleResponse: ...
    async def acreate(self, request: CreateUserMailboxRuleRequest, option: RequestOption | None = None) -> CreateUserMailboxRuleResponse: ...
    def delete(self, request: DeleteUserMailboxRuleRequest, option: RequestOption | None = None) -> DeleteUserMailboxRuleResponse: ...
    async def adelete(self, request: DeleteUserMailboxRuleRequest, option: RequestOption | None = None) -> DeleteUserMailboxRuleResponse: ...
    def list(self, request: ListUserMailboxRuleRequest, option: RequestOption | None = None) -> ListUserMailboxRuleResponse: ...
    async def alist(self, request: ListUserMailboxRuleRequest, option: RequestOption | None = None) -> ListUserMailboxRuleResponse: ...
    def reorder(self, request: ReorderUserMailboxRuleRequest, option: RequestOption | None = None) -> ReorderUserMailboxRuleResponse: ...
    async def areorder(self, request: ReorderUserMailboxRuleRequest, option: RequestOption | None = None) -> ReorderUserMailboxRuleResponse: ...
    def update(self, request: UpdateUserMailboxRuleRequest, option: RequestOption | None = None) -> UpdateUserMailboxRuleResponse: ...
    async def aupdate(self, request: UpdateUserMailboxRuleRequest, option: RequestOption | None = None) -> UpdateUserMailboxRuleResponse: ...
