from lark_oapi.core.construct import init as init

class GetContentResponseBody:
    content: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetContentResponseBodyBuilder: ...

class GetContentResponseBodyBuilder:
    def __init__(self) -> None: ...
    def content(self, content: str) -> GetContentResponseBodyBuilder: ...
    def build(self) -> GetContentResponseBody: ...
