from lark_oapi.core.construct import init as init

class AttendeeChatMember:
    rsvp_status: str | None
    is_optional: bool | None
    display_name: str | None
    is_organizer: bool | None
    is_external: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AttendeeChatMemberBuilder: ...

class AttendeeChatMemberBuilder:
    def __init__(self) -> None: ...
    def rsvp_status(self, rsvp_status: str) -> AttendeeChatMemberBuilder: ...
    def is_optional(self, is_optional: bool) -> AttendeeChatMemberBuilder: ...
    def display_name(self, display_name: str) -> AttendeeChatMemberBuilder: ...
    def is_organizer(self, is_organizer: bool) -> AttendeeChatMemberBuilder: ...
    def is_external(self, is_external: bool) -> AttendeeChatMemberBuilder: ...
    def build(self) -> AttendeeChatMember: ...
