from .batch_delete_calendar_event_attendee_request_body import BatchDeleteCalendarEventAttendeeRequestBody as BatchDeleteCalendarEventAttendeeRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchDeleteCalendarEventAttendeeRequest(BaseRequest):
    user_id_type: str | None
    calendar_id: str | None
    event_id: str | None
    request_body: BatchDeleteCalendarEventAttendeeRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchDeleteCalendarEventAttendeeRequestBuilder: ...

class BatchDeleteCalendarEventAttendeeRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> BatchDeleteCalendarEventAttendeeRequestBuilder: ...
    def calendar_id(self, calendar_id: str) -> BatchDeleteCalendarEventAttendeeRequestBuilder: ...
    def event_id(self, event_id: str) -> BatchDeleteCalendarEventAttendeeRequestBuilder: ...
    def request_body(self, request_body: BatchDeleteCalendarEventAttendeeRequestBody) -> BatchDeleteCalendarEventAttendeeRequestBuilder: ...
    def build(self) -> BatchDeleteCalendarEventAttendeeRequest: ...
