from .room_meta import RoomMeta as RoomMeta
from lark_oapi.core.construct import init as init

class BookMeetingRoomData:
    meeting_room_id: str | None
    hint: str | None
    rooms: list[RoomMeta] | None
    recurrence_rule: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BookMeetingRoomDataBuilder: ...

class BookMeetingRoomDataBuilder:
    def __init__(self) -> None: ...
    def meeting_room_id(self, meeting_room_id: str) -> BookMeetingRoomDataBuilder: ...
    def hint(self, hint: str) -> BookMeetingRoomDataBuilder: ...
    def rooms(self, rooms: list[RoomMeta]) -> BookMeetingRoomDataBuilder: ...
    def recurrence_rule(self, recurrence_rule: str) -> BookMeetingRoomDataBuilder: ...
    def build(self) -> BookMeetingRoomData: ...
