from .calendar_understand_extra import CalendarUnderstandExtra as CalendarUnderstandExtra
from .system_info import SystemInfo as SystemInfo
from lark_oapi.core.construct import init as init

class CalendarUnderstandScenarioContext:
    scenario: str | None
    work_mode: int | None
    extra: CalendarUnderstandExtra | None
    system_info: SystemInfo | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CalendarUnderstandScenarioContextBuilder: ...

class CalendarUnderstandScenarioContextBuilder:
    def __init__(self) -> None: ...
    def scenario(self, scenario: str) -> CalendarUnderstandScenarioContextBuilder: ...
    def work_mode(self, work_mode: int) -> CalendarUnderstandScenarioContextBuilder: ...
    def extra(self, extra: CalendarUnderstandExtra) -> CalendarUnderstandScenarioContextBuilder: ...
    def system_info(self, system_info: SystemInfo) -> CalendarUnderstandScenarioContextBuilder: ...
    def build(self) -> CalendarUnderstandScenarioContext: ...
