from .event_location import EventLocation as EventLocation
from .reminder import Reminder as Reminder
from .schema import Schema as Schema
from .time_info import TimeInfo as TimeInfo
from .vchat import Vchat as Vchat
from lark_oapi.core.construct import init as init

class CalendarEventResp:
    event_id: str | None
    organizer_calendar_id: str | None
    summary: str | None
    description: str | None
    need_notification: bool | None
    start_time: TimeInfo | None
    end_time: TimeInfo | None
    vchat: Vchat | None
    visibility: str | None
    attendee_ability: str | None
    free_busy_status: str | None
    location: EventLocation | None
    color: int | None
    reminders: list[Reminder] | None
    recurrence: str | None
    status: str | None
    is_exception: bool | None
    recurring_event_id: str | None
    create_time: str | None
    schemas: list[Schema] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CalendarEventRespBuilder: ...

class CalendarEventRespBuilder:
    def __init__(self) -> None: ...
    def event_id(self, event_id: str) -> CalendarEventRespBuilder: ...
    def organizer_calendar_id(self, organizer_calendar_id: str) -> CalendarEventRespBuilder: ...
    def summary(self, summary: str) -> CalendarEventRespBuilder: ...
    def description(self, description: str) -> CalendarEventRespBuilder: ...
    def need_notification(self, need_notification: bool) -> CalendarEventRespBuilder: ...
    def start_time(self, start_time: TimeInfo) -> CalendarEventRespBuilder: ...
    def end_time(self, end_time: TimeInfo) -> CalendarEventRespBuilder: ...
    def vchat(self, vchat: Vchat) -> CalendarEventRespBuilder: ...
    def visibility(self, visibility: str) -> CalendarEventRespBuilder: ...
    def attendee_ability(self, attendee_ability: str) -> CalendarEventRespBuilder: ...
    def free_busy_status(self, free_busy_status: str) -> CalendarEventRespBuilder: ...
    def location(self, location: EventLocation) -> CalendarEventRespBuilder: ...
    def color(self, color: int) -> CalendarEventRespBuilder: ...
    def reminders(self, reminders: list[Reminder]) -> CalendarEventRespBuilder: ...
    def recurrence(self, recurrence: str) -> CalendarEventRespBuilder: ...
    def status(self, status: str) -> CalendarEventRespBuilder: ...
    def is_exception(self, is_exception: bool) -> CalendarEventRespBuilder: ...
    def recurring_event_id(self, recurring_event_id: str) -> CalendarEventRespBuilder: ...
    def create_time(self, create_time: str) -> CalendarEventRespBuilder: ...
    def schemas(self, schemas: list[Schema]) -> CalendarEventRespBuilder: ...
    def build(self) -> CalendarEventResp: ...
