from .customization_option import CustomizationOption as CustomizationOption
from lark_oapi.core.construct import init as init

class CalendarAttendeeResourceCustomization:
    index_key: str | None
    input_content: str | None
    options: list[CustomizationOption] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CalendarAttendeeResourceCustomizationBuilder: ...

class CalendarAttendeeResourceCustomizationBuilder:
    def __init__(self) -> None: ...
    def index_key(self, index_key: str) -> CalendarAttendeeResourceCustomizationBuilder: ...
    def input_content(self, input_content: str) -> CalendarAttendeeResourceCustomizationBuilder: ...
    def options(self, options: list[CustomizationOption]) -> CalendarAttendeeResourceCustomizationBuilder: ...
    def build(self) -> CalendarAttendeeResourceCustomization: ...
