from lark_oapi.core.construct import init as init

class CalendarEventAttendeeChatMember:
    rsvp_status: str | None
    is_optional: bool | None
    display_name: str | None
    open_id: str | None
    is_organizer: bool | None
    is_external: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CalendarEventAttendeeChatMemberBuilder: ...

class CalendarEventAttendeeChatMemberBuilder:
    def __init__(self) -> None: ...
    def rsvp_status(self, rsvp_status: str) -> CalendarEventAttendeeChatMemberBuilder: ...
    def is_optional(self, is_optional: bool) -> CalendarEventAttendeeChatMemberBuilder: ...
    def display_name(self, display_name: str) -> CalendarEventAttendeeChatMemberBuilder: ...
    def open_id(self, open_id: str) -> CalendarEventAttendeeChatMemberBuilder: ...
    def is_organizer(self, is_organizer: bool) -> CalendarEventAttendeeChatMemberBuilder: ...
    def is_external(self, is_external: bool) -> CalendarEventAttendeeChatMemberBuilder: ...
    def build(self) -> CalendarEventAttendeeChatMember: ...
