from .myai_card_status import MyaiCardStatus as MyaiCardStatus
from lark_oapi.core.construct import init as init

class CardCallback:
    message_id: int | None
    status: MyaiCardStatus | None
    callback_info: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CardCallbackBuilder: ...

class CardCallbackBuilder:
    def __init__(self) -> None: ...
    def message_id(self, message_id: int) -> CardCallbackBuilder: ...
    def status(self, status: MyaiCardStatus) -> CardCallbackBuilder: ...
    def callback_info(self, callback_info: str) -> CardCallbackBuilder: ...
    def build(self) -> CardCallback: ...
