from lark_oapi.core.construct import init as init

class CheckInTime:
    time_type: str | None
    duration: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CheckInTimeBuilder: ...

class CheckInTimeBuilder:
    def __init__(self) -> None: ...
    def time_type(self, time_type: str) -> CheckInTimeBuilder: ...
    def duration(self, duration: int) -> CheckInTimeBuilder: ...
    def build(self) -> CheckInTime: ...
