from lark_oapi.core.construct import init as init

class CreateCalendarEventMeetingChatRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateCalendarEventMeetingChatRequestBodyBuilder: ...

class CreateCalendarEventMeetingChatRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> CreateCalendarEventMeetingChatRequestBody: ...
