from .create_calendar_event_attendee_request_body import CreateCalendarEventAttendeeRequestBody as CreateCalendarEventAttendeeRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateCalendarEventAttendeeRequest(BaseRequest):
    user_id_type: str | None
    calendar_id: str | None
    event_id: str | None
    request_body: CreateCalendarEventAttendeeRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateCalendarEventAttendeeRequestBuilder: ...

class CreateCalendarEventAttendeeRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> CreateCalendarEventAttendeeRequestBuilder: ...
    def calendar_id(self, calendar_id: str) -> CreateCalendarEventAttendeeRequestBuilder: ...
    def event_id(self, event_id: str) -> CreateCalendarEventAttendeeRequestBuilder: ...
    def request_body(self, request_body: CreateCalendarEventAttendeeRequestBody) -> CreateCalendarEventAttendeeRequestBuilder: ...
    def build(self) -> CreateCalendarEventAttendeeRequest: ...
