from .calendar import Calendar as Calendar
from lark_oapi.core.construct import init as init

class CreateCalendarResponseBody:
    calendar: Calendar | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateCalendarResponseBodyBuilder: ...

class CreateCalendarResponseBodyBuilder:
    def __init__(self) -> None: ...
    def calendar(self, calendar: Calendar) -> CreateCalendarResponseBodyBuilder: ...
    def build(self) -> CreateCalendarResponseBody: ...
