from lark_oapi.core.construct import init as init

class CreateTimeoffEventResponseBody:
    timeoff_event_id: str | None
    user_id: str | None
    timezone: str | None
    start_time: str | None
    end_time: str | None
    title: str | None
    description: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateTimeoffEventResponseBodyBuilder: ...

class CreateTimeoffEventResponseBodyBuilder:
    def __init__(self) -> None: ...
    def timeoff_event_id(self, timeoff_event_id: str) -> CreateTimeoffEventResponseBodyBuilder: ...
    def user_id(self, user_id: str) -> CreateTimeoffEventResponseBodyBuilder: ...
    def timezone(self, timezone: str) -> CreateTimeoffEventResponseBodyBuilder: ...
    def start_time(self, start_time: str) -> CreateTimeoffEventResponseBodyBuilder: ...
    def end_time(self, end_time: str) -> CreateTimeoffEventResponseBodyBuilder: ...
    def title(self, title: str) -> CreateTimeoffEventResponseBodyBuilder: ...
    def description(self, description: str) -> CreateTimeoffEventResponseBodyBuilder: ...
    def build(self) -> CreateTimeoffEventResponseBody: ...
