from .calendar_event_attendee import CalendarEventAttendee as CalendarEventAttendee
from lark_oapi.core.construct import init as init

class CreateCalendarEventAttendeeResponseBody:
    attendees: list[CalendarEventAttendee] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateCalendarEventAttendeeResponseBodyBuilder: ...

class CreateCalendarEventAttendeeResponseBodyBuilder:
    def __init__(self) -> None: ...
    def attendees(self, attendees: list[CalendarEventAttendee]) -> CreateCalendarEventAttendeeResponseBodyBuilder: ...
    def build(self) -> CreateCalendarEventAttendeeResponseBody: ...
