from lark_oapi.core.construct import init as init

class CreateCalendarEventMeetingMinuteRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateCalendarEventMeetingMinuteRequestBodyBuilder: ...

class CreateCalendarEventMeetingMinuteRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> CreateCalendarEventMeetingMinuteRequestBody: ...
