from lark_oapi.core.construct import init as init

class DeleteCalendarEventMeetingChatRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteCalendarEventMeetingChatRequestBodyBuilder: ...

class DeleteCalendarEventMeetingChatRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteCalendarEventMeetingChatRequestBody: ...
