from lark_oapi.core.construct import init as init

class DeleteCalendarEventMeetingChatResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteCalendarEventMeetingChatResponseBodyBuilder: ...

class DeleteCalendarEventMeetingChatResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteCalendarEventMeetingChatResponseBody: ...
