from lark_oapi.core.construct import init as init

class DeleteCalendarResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteCalendarResponseBodyBuilder: ...

class DeleteCalendarResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteCalendarResponseBody: ...
