from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteCalendarEventMeetingChatRequest(BaseRequest):
    meeting_chat_id: str | None
    calendar_id: str | None
    event_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteCalendarEventMeetingChatRequestBuilder: ...

class DeleteCalendarEventMeetingChatRequestBuilder:
    def __init__(self) -> None: ...
    def meeting_chat_id(self, meeting_chat_id: str) -> DeleteCalendarEventMeetingChatRequestBuilder: ...
    def calendar_id(self, calendar_id: str) -> DeleteCalendarEventMeetingChatRequestBuilder: ...
    def event_id(self, event_id: str) -> DeleteCalendarEventMeetingChatRequestBuilder: ...
    def build(self) -> DeleteCalendarEventMeetingChatRequest: ...
