from lark_oapi.core.construct import init as init

class DeleteExchangeBindingResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteExchangeBindingResponseBodyBuilder: ...

class DeleteExchangeBindingResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteExchangeBindingResponseBody: ...
