from lark_oapi.core.construct import init as init

class EventLocation:
    name: str | None
    address: str | None
    latitude: float | None
    longitude: float | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EventLocationBuilder: ...

class EventLocationBuilder:
    def __init__(self) -> None: ...
    def name(self, name: str) -> EventLocationBuilder: ...
    def address(self, address: str) -> EventLocationBuilder: ...
    def latitude(self, latitude: float) -> EventLocationBuilder: ...
    def longitude(self, longitude: float) -> EventLocationBuilder: ...
    def build(self) -> EventLocation: ...
