from lark_oapi.core.construct import init as init

class EventOrganizer:
    user_id: str | None
    display_name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EventOrganizerBuilder: ...

class EventOrganizerBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: str) -> EventOrganizerBuilder: ...
    def display_name(self, display_name: str) -> EventOrganizerBuilder: ...
    def build(self) -> EventOrganizer: ...
