from lark_oapi.core.construct import init as init

class Freebusy:
    start_time: str | None
    end_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FreebusyBuilder: ...

class FreebusyBuilder:
    def __init__(self) -> None: ...
    def start_time(self, start_time: str) -> FreebusyBuilder: ...
    def end_time(self, end_time: str) -> FreebusyBuilder: ...
    def build(self) -> Freebusy: ...
