from lark_oapi.core.construct import init as init

class FreeTimeAi:
    free_time_list: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FreeTimeAiBuilder: ...

class FreeTimeAiBuilder:
    def __init__(self) -> None: ...
    def free_time_list(self, free_time_list: str) -> FreeTimeAiBuilder: ...
    def build(self) -> FreeTimeAi: ...
