from lark_oapi.core.construct import init as init

class FreeTime:
    free_time_start: str | None
    free_time_end: str | None
    free_time_list: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FreeTimeBuilder: ...

class FreeTimeBuilder:
    def __init__(self) -> None: ...
    def free_time_start(self, free_time_start: str) -> FreeTimeBuilder: ...
    def free_time_end(self, free_time_end: str) -> FreeTimeBuilder: ...
    def free_time_list(self, free_time_list: str) -> FreeTimeBuilder: ...
    def build(self) -> FreeTime: ...
