from lark_oapi.core.construct import init as init

class GenerateCaldavConfSettingResponseBody:
    password: str | None
    user_name: str | None
    server_address: str | None
    device_name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GenerateCaldavConfSettingResponseBodyBuilder: ...

class GenerateCaldavConfSettingResponseBodyBuilder:
    def __init__(self) -> None: ...
    def password(self, password: str) -> GenerateCaldavConfSettingResponseBodyBuilder: ...
    def user_name(self, user_name: str) -> GenerateCaldavConfSettingResponseBodyBuilder: ...
    def server_address(self, server_address: str) -> GenerateCaldavConfSettingResponseBodyBuilder: ...
    def device_name(self, device_name: str) -> GenerateCaldavConfSettingResponseBodyBuilder: ...
    def build(self) -> GenerateCaldavConfSettingResponseBody: ...
