from .generate_caldav_conf_setting_request_body import GenerateCaldavConfSettingRequestBody as GenerateCaldavConfSettingRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GenerateCaldavConfSettingRequest(BaseRequest):
    request_body: GenerateCaldavConfSettingRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GenerateCaldavConfSettingRequestBuilder: ...

class GenerateCaldavConfSettingRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: GenerateCaldavConfSettingRequestBody) -> GenerateCaldavConfSettingRequestBuilder: ...
    def build(self) -> GenerateCaldavConfSettingRequest: ...
