from lark_oapi.core.construct import init as init

class GenerateCaldavConfSettingRequestBody:
    device_name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GenerateCaldavConfSettingRequestBodyBuilder: ...

class GenerateCaldavConfSettingRequestBodyBuilder:
    def __init__(self) -> None: ...
    def device_name(self, device_name: str) -> GenerateCaldavConfSettingRequestBodyBuilder: ...
    def build(self) -> GenerateCaldavConfSettingRequestBody: ...
