from lark_oapi.core.construct import init as init

class GetCalendarRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetCalendarRequestBodyBuilder: ...

class GetCalendarRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetCalendarRequestBody: ...
