from lark_oapi.core.construct import init as init

class GetExchangeBindingRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetExchangeBindingRequestBodyBuilder: ...

class GetExchangeBindingRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetExchangeBindingRequestBody: ...
