from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetCalendarRequest(BaseRequest):
    calendar_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetCalendarRequestBuilder: ...

class GetCalendarRequestBuilder:
    def __init__(self) -> None: ...
    def calendar_id(self, calendar_id: str) -> GetCalendarRequestBuilder: ...
    def build(self) -> GetCalendarRequest: ...
