from .instance import Instance as Instance
from lark_oapi.core.construct import init as init

class InstanceViewCalendarEventResponseBody:
    items: list[Instance] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InstanceViewCalendarEventResponseBodyBuilder: ...

class InstanceViewCalendarEventResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[Instance]) -> InstanceViewCalendarEventResponseBodyBuilder: ...
    def build(self) -> InstanceViewCalendarEventResponseBody: ...
