from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class InstancesCalendarEventRequest(BaseRequest):
    start_time: str | None
    end_time: str | None
    page_size: int | None
    page_token: str | None
    calendar_id: str | None
    event_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> InstancesCalendarEventRequestBuilder: ...

class InstancesCalendarEventRequestBuilder:
    def __init__(self) -> None: ...
    def start_time(self, start_time: str) -> InstancesCalendarEventRequestBuilder: ...
    def end_time(self, end_time: str) -> InstancesCalendarEventRequestBuilder: ...
    def page_size(self, page_size: int) -> InstancesCalendarEventRequestBuilder: ...
    def page_token(self, page_token: str) -> InstancesCalendarEventRequestBuilder: ...
    def calendar_id(self, calendar_id: str) -> InstancesCalendarEventRequestBuilder: ...
    def event_id(self, event_id: str) -> InstancesCalendarEventRequestBuilder: ...
    def build(self) -> InstancesCalendarEventRequest: ...
