from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class InstanceViewCalendarEventRequest(BaseRequest):
    start_time: str | None
    end_time: str | None
    user_id_type: str | None
    calendar_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> InstanceViewCalendarEventRequestBuilder: ...

class InstanceViewCalendarEventRequestBuilder:
    def __init__(self) -> None: ...
    def start_time(self, start_time: str) -> InstanceViewCalendarEventRequestBuilder: ...
    def end_time(self, end_time: str) -> InstanceViewCalendarEventRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> InstanceViewCalendarEventRequestBuilder: ...
    def calendar_id(self, calendar_id: str) -> InstanceViewCalendarEventRequestBuilder: ...
    def build(self) -> InstanceViewCalendarEventRequest: ...
