from lark_oapi.core.construct import init as init

class InstancesCalendarEventRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InstancesCalendarEventRequestBodyBuilder: ...

class InstancesCalendarEventRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> InstancesCalendarEventRequestBody: ...
