from .list_freebusy_request_body import ListFreebusyRequestBody as ListFreebusyRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListFreebusyRequest(BaseRequest):
    user_id_type: str | None
    request_body: ListFreebusyRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListFreebusyRequestBuilder: ...

class ListFreebusyRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> ListFreebusyRequestBuilder: ...
    def request_body(self, request_body: ListFreebusyRequestBody) -> ListFreebusyRequestBuilder: ...
    def build(self) -> ListFreebusyRequest: ...
