from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListCalendarRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    sync_token: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListCalendarRequestBuilder: ...

class ListCalendarRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> ListCalendarRequestBuilder: ...
    def page_token(self, page_token: str) -> ListCalendarRequestBuilder: ...
    def sync_token(self, sync_token: str) -> ListCalendarRequestBuilder: ...
    def build(self) -> ListCalendarRequest: ...
