from .freebusy import Freebusy as Freebusy
from lark_oapi.core.construct import init as init

class ListFreebusyResponseBody:
    freebusy_list: list[Freebusy] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListFreebusyResponseBodyBuilder: ...

class ListFreebusyResponseBodyBuilder:
    def __init__(self) -> None: ...
    def freebusy_list(self, freebusy_list: list[Freebusy]) -> ListFreebusyResponseBodyBuilder: ...
    def build(self) -> ListFreebusyResponseBody: ...
