from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListCalendarEventAttendeeChatMemberRequest(BaseRequest):
    page_token: str | None
    page_size: int | None
    user_id_type: str | None
    calendar_id: str | None
    event_id: str | None
    attendee_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListCalendarEventAttendeeChatMemberRequestBuilder: ...

class ListCalendarEventAttendeeChatMemberRequestBuilder:
    def __init__(self) -> None: ...
    def page_token(self, page_token: str) -> ListCalendarEventAttendeeChatMemberRequestBuilder: ...
    def page_size(self, page_size: int) -> ListCalendarEventAttendeeChatMemberRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> ListCalendarEventAttendeeChatMemberRequestBuilder: ...
    def calendar_id(self, calendar_id: str) -> ListCalendarEventAttendeeChatMemberRequestBuilder: ...
    def event_id(self, event_id: str) -> ListCalendarEventAttendeeChatMemberRequestBuilder: ...
    def attendee_id(self, attendee_id: str) -> ListCalendarEventAttendeeChatMemberRequestBuilder: ...
    def build(self) -> ListCalendarEventAttendeeChatMemberRequest: ...
