from lark_oapi.core.construct import init as init

class ListCalendarAclRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListCalendarAclRequestBodyBuilder: ...

class ListCalendarAclRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListCalendarAclRequestBody: ...
