from lark_oapi.core.construct import init as init

class ListCalendarEventRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListCalendarEventRequestBodyBuilder: ...

class ListCalendarEventRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListCalendarEventRequestBody: ...
