from lark_oapi.core.construct import init as init

class ListFreebusyRequestBody:
    time_min: str | None
    time_max: str | None
    user_id: str | None
    room_id: str | None
    include_external_calendar: bool | None
    only_busy: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListFreebusyRequestBodyBuilder: ...

class ListFreebusyRequestBodyBuilder:
    def __init__(self) -> None: ...
    def time_min(self, time_min: str) -> ListFreebusyRequestBodyBuilder: ...
    def time_max(self, time_max: str) -> ListFreebusyRequestBodyBuilder: ...
    def user_id(self, user_id: str) -> ListFreebusyRequestBodyBuilder: ...
    def room_id(self, room_id: str) -> ListFreebusyRequestBodyBuilder: ...
    def include_external_calendar(self, include_external_calendar: bool) -> ListFreebusyRequestBodyBuilder: ...
    def only_busy(self, only_busy: bool) -> ListFreebusyRequestBodyBuilder: ...
    def build(self) -> ListFreebusyRequestBody: ...
