from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListCalendarAclRequest(BaseRequest):
    user_id_type: str | None
    page_token: str | None
    page_size: int | None
    calendar_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListCalendarAclRequestBuilder: ...

class ListCalendarAclRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> ListCalendarAclRequestBuilder: ...
    def page_token(self, page_token: str) -> ListCalendarAclRequestBuilder: ...
    def page_size(self, page_size: int) -> ListCalendarAclRequestBuilder: ...
    def calendar_id(self, calendar_id: str) -> ListCalendarAclRequestBuilder: ...
    def build(self) -> ListCalendarAclRequest: ...
