from lark_oapi.core.construct import init as init

class ListCalendarRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListCalendarRequestBodyBuilder: ...

class ListCalendarRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListCalendarRequestBody: ...
