from lark_oapi.core.construct import init as init

class MeetingMinute:
    doc_token: str | None
    doc_url: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MeetingMinuteBuilder: ...

class MeetingMinuteBuilder:
    def __init__(self) -> None: ...
    def doc_token(self, doc_token: str) -> MeetingMinuteBuilder: ...
    def doc_url(self, doc_url: str) -> MeetingMinuteBuilder: ...
    def build(self) -> MeetingMinute: ...
