from lark_oapi.core.construct import init as init

class MyaiDocDetail:
    title: str | None
    url: str | None
    token: str | None
    doc_type: str | None
    extra: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MyaiDocDetailBuilder: ...

class MyaiDocDetailBuilder:
    def __init__(self) -> None: ...
    def title(self, title: str) -> MyaiDocDetailBuilder: ...
    def url(self, url: str) -> MyaiDocDetailBuilder: ...
    def token(self, token: str) -> MyaiDocDetailBuilder: ...
    def doc_type(self, doc_type: str) -> MyaiDocDetailBuilder: ...
    def extra(self, extra: str) -> MyaiDocDetailBuilder: ...
    def build(self) -> MyaiDocDetail: ...
