from lark_oapi.core.construct import init as init

class OperateCardData:
    meeting_url: str | None
    meeting_no: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OperateCardDataBuilder: ...

class OperateCardDataBuilder:
    def __init__(self) -> None: ...
    def meeting_url(self, meeting_url: str) -> OperateCardDataBuilder: ...
    def meeting_no(self, meeting_no: str) -> OperateCardDataBuilder: ...
    def build(self) -> OperateCardData: ...
