from .calendar_event import CalendarEvent as CalendarEvent
from lark_oapi.core.construct import init as init

class PatchCalendarEventResponseBody:
    event: CalendarEvent | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchCalendarEventResponseBodyBuilder: ...

class PatchCalendarEventResponseBodyBuilder:
    def __init__(self) -> None: ...
    def event(self, event: CalendarEvent) -> PatchCalendarEventResponseBodyBuilder: ...
    def build(self) -> PatchCalendarEventResponseBody: ...
