from .calendar_event import CalendarEvent as CalendarEvent
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PatchCalendarEventRequest(BaseRequest):
    user_id_type: str | None
    calendar_id: str | None
    event_id: str | None
    request_body: CalendarEvent | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PatchCalendarEventRequestBuilder: ...

class PatchCalendarEventRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> PatchCalendarEventRequestBuilder: ...
    def calendar_id(self, calendar_id: str) -> PatchCalendarEventRequestBuilder: ...
    def event_id(self, event_id: str) -> PatchCalendarEventRequestBuilder: ...
    def request_body(self, request_body: CalendarEvent) -> PatchCalendarEventRequestBuilder: ...
    def build(self) -> PatchCalendarEventRequest: ...
