from lark_oapi.core.construct import init as init

class Reminder:
    minutes: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReminderBuilder: ...

class ReminderBuilder:
    def __init__(self) -> None: ...
    def minutes(self, minutes: int) -> ReminderBuilder: ...
    def build(self) -> Reminder: ...
