from lark_oapi.core.construct import init as init

class ReplyCalendarEventRequestBody:
    rsvp_status: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReplyCalendarEventRequestBodyBuilder: ...

class ReplyCalendarEventRequestBodyBuilder:
    def __init__(self) -> None: ...
    def rsvp_status(self, rsvp_status: str) -> ReplyCalendarEventRequestBodyBuilder: ...
    def build(self) -> ReplyCalendarEventRequestBody: ...
