from lark_oapi.core.construct import init as init

class RoomMeta:
    name: str | None
    room_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RoomMetaBuilder: ...

class RoomMetaBuilder:
    def __init__(self) -> None: ...
    def name(self, name: str) -> RoomMetaBuilder: ...
    def room_id(self, room_id: str) -> RoomMetaBuilder: ...
    def build(self) -> RoomMeta: ...
