from lark_oapi.core.construct import init as init

class Schema:
    ui_name: str | None
    ui_status: str | None
    app_link: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SchemaBuilder: ...

class SchemaBuilder:
    def __init__(self) -> None: ...
    def ui_name(self, ui_name: str) -> SchemaBuilder: ...
    def ui_status(self, ui_status: str) -> SchemaBuilder: ...
    def app_link(self, app_link: str) -> SchemaBuilder: ...
    def build(self) -> Schema: ...
