from lark_oapi.core.construct import init as init

class SearchCalendarRequestBody:
    query: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SearchCalendarRequestBodyBuilder: ...

class SearchCalendarRequestBodyBuilder:
    def __init__(self) -> None: ...
    def query(self, query: str) -> SearchCalendarRequestBodyBuilder: ...
    def build(self) -> SearchCalendarRequestBody: ...
