from .search_calendar_request_body import SearchCalendarRequestBody as SearchCalendarRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class SearchCalendarRequest(BaseRequest):
    page_token: str | None
    page_size: int | None
    request_body: SearchCalendarRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> SearchCalendarRequestBuilder: ...

class SearchCalendarRequestBuilder:
    def __init__(self) -> None: ...
    def page_token(self, page_token: str) -> SearchCalendarRequestBuilder: ...
    def page_size(self, page_size: int) -> SearchCalendarRequestBuilder: ...
    def request_body(self, request_body: SearchCalendarRequestBody) -> SearchCalendarRequestBuilder: ...
    def build(self) -> SearchCalendarRequest: ...
