from .calendar_event import CalendarEvent as CalendarEvent
from lark_oapi.core.construct import init as init

class SearchCalendarEventResponseBody:
    items: list[CalendarEvent] | None
    page_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SearchCalendarEventResponseBodyBuilder: ...

class SearchCalendarEventResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[CalendarEvent]) -> SearchCalendarEventResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> SearchCalendarEventResponseBodyBuilder: ...
    def build(self) -> SearchCalendarEventResponseBody: ...
