from .event_search_filter import EventSearchFilter as EventSearchFilter
from lark_oapi.core.construct import init as init

class SearchCalendarEventRequestBody:
    query: str | None
    filter: EventSearchFilter | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SearchCalendarEventRequestBodyBuilder: ...

class SearchCalendarEventRequestBodyBuilder:
    def __init__(self) -> None: ...
    def query(self, query: str) -> SearchCalendarEventRequestBodyBuilder: ...
    def filter(self, filter: EventSearchFilter) -> SearchCalendarEventRequestBodyBuilder: ...
    def build(self) -> SearchCalendarEventRequestBody: ...
