from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class SubscribeCalendarRequest(BaseRequest):
    calendar_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> SubscribeCalendarRequestBuilder: ...

class SubscribeCalendarRequestBuilder:
    def __init__(self) -> None: ...
    def calendar_id(self, calendar_id: str) -> SubscribeCalendarRequestBuilder: ...
    def build(self) -> SubscribeCalendarRequest: ...
