from lark_oapi.core.construct import init as init

class SubscriptionCalendarEventResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SubscriptionCalendarEventResponseBodyBuilder: ...

class SubscriptionCalendarEventResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> SubscriptionCalendarEventResponseBody: ...
