from lark_oapi.core.construct import init as init

class SubscriptionCalendarRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SubscriptionCalendarRequestBodyBuilder: ...

class SubscriptionCalendarRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> SubscriptionCalendarRequestBody: ...
