from lark_oapi.core.construct import init as init

class TimeSpan:
    start_time: str | None
    end_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TimeSpanBuilder: ...

class TimeSpanBuilder:
    def __init__(self) -> None: ...
    def start_time(self, start_time: str) -> TimeSpanBuilder: ...
    def end_time(self, end_time: str) -> TimeSpanBuilder: ...
    def build(self) -> TimeSpan: ...
