from lark_oapi.core.construct import init as init

class TimeInfo:
    date: str | None
    timestamp: str | None
    timezone: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TimeInfoBuilder: ...

class TimeInfoBuilder:
    def __init__(self) -> None: ...
    def date(self, date: str) -> TimeInfoBuilder: ...
    def timestamp(self, timestamp: str) -> TimeInfoBuilder: ...
    def timezone(self, timezone: str) -> TimeInfoBuilder: ...
    def build(self) -> TimeInfo: ...
