from lark_oapi.core.construct import init as init

class UnsubscribeCalendarResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UnsubscribeCalendarResponseBodyBuilder: ...

class UnsubscribeCalendarResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> UnsubscribeCalendarResponseBody: ...
