from .calendar import Calendar as Calendar
from lark_oapi.core.construct import init as init

class UserCalendar:
    calendar: Calendar | None
    user_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserCalendarBuilder: ...

class UserCalendarBuilder:
    def __init__(self) -> None: ...
    def calendar(self, calendar: Calendar) -> UserCalendarBuilder: ...
    def user_id(self, user_id: str) -> UserCalendarBuilder: ...
    def build(self) -> UserCalendar: ...
