from .freebusy import Freebusy as Freebusy
from lark_oapi.core.construct import init as init

class UserFreebusy:
    freebusy_items: list[Freebusy] | None
    user_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserFreebusyBuilder: ...

class UserFreebusyBuilder:
    def __init__(self) -> None: ...
    def freebusy_items(self, freebusy_items: list[Freebusy]) -> UserFreebusyBuilder: ...
    def user_id(self, user_id: str) -> UserFreebusyBuilder: ...
    def build(self) -> UserFreebusy: ...
