from lark_oapi.core.construct import init as init

class VcInfo:
    unique_id: int | None
    meeting_no: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> VcInfoBuilder: ...

class VcInfoBuilder:
    def __init__(self) -> None: ...
    def unique_id(self, unique_id: int) -> VcInfoBuilder: ...
    def meeting_no(self, meeting_no: int) -> VcInfoBuilder: ...
    def build(self) -> VcInfo: ...
