from .workhour import Workhour as Workhour
from lark_oapi.core.construct import init as init

class WorkhourSetting:
    timezone: str | None
    workhours: list[Workhour] | None
    enable_work_hour: bool | None
    user_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WorkhourSettingBuilder: ...

class WorkhourSettingBuilder:
    def __init__(self) -> None: ...
    def timezone(self, timezone: str) -> WorkhourSettingBuilder: ...
    def workhours(self, workhours: list[Workhour]) -> WorkhourSettingBuilder: ...
    def enable_work_hour(self, enable_work_hour: bool) -> WorkhourSettingBuilder: ...
    def user_id(self, user_id: str) -> WorkhourSettingBuilder: ...
    def build(self) -> WorkhourSetting: ...
