from lark_oapi.core.construct import init as init

class Workhour:
    day_of_week: int | None
    start_time: int | None
    end_time: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WorkhourBuilder: ...

class WorkhourBuilder:
    def __init__(self) -> None: ...
    def day_of_week(self, day_of_week: int) -> WorkhourBuilder: ...
    def start_time(self, start_time: int) -> WorkhourBuilder: ...
    def end_time(self, end_time: int) -> WorkhourBuilder: ...
    def build(self) -> Workhour: ...
