from lark_oapi.core.construct import init as init

class AdditionalInformation:
    item_id: int | None
    external_id: str | None
    reviewee_user_id: str | None
    item: str | None
    time: str | None
    detailed_description: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AdditionalInformationBuilder: ...

class AdditionalInformationBuilder:
    def __init__(self) -> None: ...
    def item_id(self, item_id: int) -> AdditionalInformationBuilder: ...
    def external_id(self, external_id: str) -> AdditionalInformationBuilder: ...
    def reviewee_user_id(self, reviewee_user_id: str) -> AdditionalInformationBuilder: ...
    def item(self, item: str) -> AdditionalInformationBuilder: ...
    def time(self, time: str) -> AdditionalInformationBuilder: ...
    def detailed_description(self, detailed_description: str) -> AdditionalInformationBuilder: ...
    def build(self) -> AdditionalInformation: ...
