from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class CooperationUserRole:
    role_id: str | None
    name: I18n | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CooperationUserRoleBuilder: ...

class CooperationUserRoleBuilder:
    def __init__(self) -> None: ...
    def role_id(self, role_id: str) -> CooperationUserRoleBuilder: ...
    def name(self, name: I18n) -> CooperationUserRoleBuilder: ...
    def build(self) -> CooperationUserRole: ...
