from .cooperation_role import CooperationRole as CooperationRole
from .cooperation_user_role import CooperationUserRole as CooperationUserRole
from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class CooperationProject:
    id: str | None
    name: I18n | None
    roles: list[CooperationRole] | None
    user_roles: list[CooperationUserRole] | None
    underling_roles: list[CooperationUserRole] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CooperationProjectBuilder: ...

class CooperationProjectBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> CooperationProjectBuilder: ...
    def name(self, name: I18n) -> CooperationProjectBuilder: ...
    def roles(self, roles: list[CooperationRole]) -> CooperationProjectBuilder: ...
    def user_roles(self, user_roles: list[CooperationUserRole]) -> CooperationProjectBuilder: ...
    def underling_roles(self, underling_roles: list[CooperationUserRole]) -> CooperationProjectBuilder: ...
    def build(self) -> CooperationProject: ...
