from .delete_additional_informations_batch_request_body import DeleteAdditionalInformationsBatchRequestBody as DeleteAdditionalInformationsBatchRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteAdditionalInformationsBatchRequest(BaseRequest):
    user_id_type: str | None
    request_body: DeleteAdditionalInformationsBatchRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteAdditionalInformationsBatchRequestBuilder: ...

class DeleteAdditionalInformationsBatchRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> DeleteAdditionalInformationsBatchRequestBuilder: ...
    def request_body(self, request_body: DeleteAdditionalInformationsBatchRequestBody) -> DeleteAdditionalInformationsBatchRequestBuilder: ...
    def build(self) -> DeleteAdditionalInformationsBatchRequest: ...
