from lark_oapi.core.construct import init as init

class DeleteAdditionalInformationsBatchResponseBody:
    additional_informations: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteAdditionalInformationsBatchResponseBodyBuilder: ...

class DeleteAdditionalInformationsBatchResponseBodyBuilder:
    def __init__(self) -> None: ...
    def additional_informations(self, additional_informations: list[str]) -> DeleteAdditionalInformationsBatchResponseBodyBuilder: ...
    def build(self) -> DeleteAdditionalInformationsBatchResponseBody: ...
