from .import_metric_detail_request_body import ImportMetricDetailRequestBody as ImportMetricDetailRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ImportMetricDetailRequest(BaseRequest):
    client_token: str | None
    user_id_type: str | None
    request_body: ImportMetricDetailRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ImportMetricDetailRequestBuilder: ...

class ImportMetricDetailRequestBuilder:
    def __init__(self) -> None: ...
    def client_token(self, client_token: str) -> ImportMetricDetailRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> ImportMetricDetailRequestBuilder: ...
    def request_body(self, request_body: ImportMetricDetailRequestBody) -> ImportMetricDetailRequestBuilder: ...
    def build(self) -> ImportMetricDetailRequest: ...
