from .import_additional_information_request_body import ImportAdditionalInformationRequestBody as ImportAdditionalInformationRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ImportAdditionalInformationRequest(BaseRequest):
    client_token: str | None
    user_id_type: str | None
    request_body: ImportAdditionalInformationRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ImportAdditionalInformationRequestBuilder: ...

class ImportAdditionalInformationRequestBuilder:
    def __init__(self) -> None: ...
    def client_token(self, client_token: str) -> ImportAdditionalInformationRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> ImportAdditionalInformationRequestBuilder: ...
    def request_body(self, request_body: ImportAdditionalInformationRequestBody) -> ImportAdditionalInformationRequestBuilder: ...
    def build(self) -> ImportAdditionalInformationRequest: ...
