from .i18n import I18n as I18n
from .indicator_option import IndicatorOption as IndicatorOption
from lark_oapi.core.construct import init as init

class Indicator:
    id: str | None
    name: I18n | None
    type: str | None
    options: list[IndicatorOption] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> IndicatorBuilder: ...

class IndicatorBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> IndicatorBuilder: ...
    def name(self, name: I18n) -> IndicatorBuilder: ...
    def type(self, type: str) -> IndicatorBuilder: ...
    def options(self, options: list[IndicatorOption]) -> IndicatorBuilder: ...
    def build(self) -> Indicator: ...
