from .user import User as User
from lark_oapi.core.construct import init as init

class InvitedReviewRecordInfo:
    reviewer_id: User | None
    is_rejected: bool | None
    rejected_reason: str | None
    distribute_type: int | None
    avg_diff: str | None
    relationship_with_reviewee: str | None
    invitedby: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InvitedReviewRecordInfoBuilder: ...

class InvitedReviewRecordInfoBuilder:
    def __init__(self) -> None: ...
    def reviewer_id(self, reviewer_id: User) -> InvitedReviewRecordInfoBuilder: ...
    def is_rejected(self, is_rejected: bool) -> InvitedReviewRecordInfoBuilder: ...
    def rejected_reason(self, rejected_reason: str) -> InvitedReviewRecordInfoBuilder: ...
    def distribute_type(self, distribute_type: int) -> InvitedReviewRecordInfoBuilder: ...
    def avg_diff(self, avg_diff: str) -> InvitedReviewRecordInfoBuilder: ...
    def relationship_with_reviewee(self, relationship_with_reviewee: str) -> InvitedReviewRecordInfoBuilder: ...
    def invitedby(self, invitedby: str) -> InvitedReviewRecordInfoBuilder: ...
    def build(self) -> InvitedReviewRecordInfo: ...
