from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class JobLevel:
    id: str | None
    name: I18n | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobLevelBuilder: ...

class JobLevelBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> JobLevelBuilder: ...
    def name(self, name: I18n) -> JobLevelBuilder: ...
    def build(self) -> JobLevel: ...
