from .metric_tag import MetricTag as MetricTag
from lark_oapi.core.construct import init as init

class ListMetricTagResponseBody:
    items: list[MetricTag] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListMetricTagResponseBodyBuilder: ...

class ListMetricTagResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[MetricTag]) -> ListMetricTagResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListMetricTagResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListMetricTagResponseBodyBuilder: ...
    def build(self) -> ListMetricTagResponseBody: ...
