from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class MetricTag:
    tag_id: int | None
    tag_name: I18n | None
    index: int | None
    create_time: str | None
    update_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MetricTagBuilder: ...

class MetricTagBuilder:
    def __init__(self) -> None: ...
    def tag_id(self, tag_id: int) -> MetricTagBuilder: ...
    def tag_name(self, tag_name: I18n) -> MetricTagBuilder: ...
    def index(self, index: int) -> MetricTagBuilder: ...
    def create_time(self, create_time: str) -> MetricTagBuilder: ...
    def update_time(self, update_time: str) -> MetricTagBuilder: ...
    def build(self) -> MetricTag: ...
