from lark_oapi.core.construct import init as init

class MetricData:
    id: str | None
    score: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MetricDataBuilder: ...

class MetricDataBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> MetricDataBuilder: ...
    def score(self, score: str) -> MetricDataBuilder: ...
    def build(self) -> MetricData: ...
