from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class MetricField:
    field_id: int | None
    name: I18n | None
    type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MetricFieldBuilder: ...

class MetricFieldBuilder:
    def __init__(self) -> None: ...
    def field_id(self, field_id: int) -> MetricFieldBuilder: ...
    def name(self, name: I18n) -> MetricFieldBuilder: ...
    def type(self, type: str) -> MetricFieldBuilder: ...
    def build(self) -> MetricField: ...
