from .user import User as User
from lark_oapi.core.construct import init as init

class MetricFieldInTemplate:
    id: int | None
    input_setting: str | None
    filed_value: str | None
    field_value_person: User | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MetricFieldInTemplateBuilder: ...

class MetricFieldInTemplateBuilder:
    def __init__(self) -> None: ...
    def id(self, id: int) -> MetricFieldInTemplateBuilder: ...
    def input_setting(self, input_setting: str) -> MetricFieldInTemplateBuilder: ...
    def filed_value(self, filed_value: str) -> MetricFieldInTemplateBuilder: ...
    def field_value_person(self, field_value_person: User) -> MetricFieldInTemplateBuilder: ...
    def build(self) -> MetricFieldInTemplate: ...
