from .i18n import I18n as I18n
from .okr_objective import OkrObjective as OkrObjective
from lark_oapi.core.construct import init as init

class Okr:
    id: str | None
    period_id: str | None
    create_date: str | None
    name: I18n | None
    objectives: list[OkrObjective] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OkrBuilder: ...

class OkrBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> OkrBuilder: ...
    def period_id(self, period_id: str) -> OkrBuilder: ...
    def create_date(self, create_date: str) -> OkrBuilder: ...
    def name(self, name: I18n) -> OkrBuilder: ...
    def objectives(self, objectives: list[OkrObjective]) -> OkrBuilder: ...
    def build(self) -> Okr: ...
