from .okr_objective_kr import OkrObjectiveKr as OkrObjectiveKr
from .okr_progress_rate import OkrProgressRate as OkrProgressRate
from lark_oapi.core.construct import init as init

class OkrObjective:
    id: str | None
    content: str | None
    score: int | None
    weight: float | None
    progress_rate: OkrProgressRate | None
    key_results: list[OkrObjectiveKr] | None
    category_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OkrObjectiveBuilder: ...

class OkrObjectiveBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> OkrObjectiveBuilder: ...
    def content(self, content: str) -> OkrObjectiveBuilder: ...
    def score(self, score: int) -> OkrObjectiveBuilder: ...
    def weight(self, weight: float) -> OkrObjectiveBuilder: ...
    def progress_rate(self, progress_rate: OkrProgressRate) -> OkrObjectiveBuilder: ...
    def key_results(self, key_results: list[OkrObjectiveKr]) -> OkrObjectiveBuilder: ...
    def category_id(self, category_id: str) -> OkrObjectiveBuilder: ...
    def build(self) -> OkrObjective: ...
