from lark_oapi.core.construct import init as init

class QueryIndicatorRequestBody:
    indicator_ids: list[int] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryIndicatorRequestBodyBuilder: ...

class QueryIndicatorRequestBodyBuilder:
    def __init__(self) -> None: ...
    def indicator_ids(self, indicator_ids: list[int]) -> QueryIndicatorRequestBodyBuilder: ...
    def build(self) -> QueryIndicatorRequestBody: ...
