from .query_review_data_request_body import QueryReviewDataRequestBody as QueryReviewDataRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class QueryReviewDataRequest(BaseRequest):
    user_id_type: str | None
    request_body: QueryReviewDataRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> QueryReviewDataRequestBuilder: ...

class QueryReviewDataRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> QueryReviewDataRequestBuilder: ...
    def request_body(self, request_body: QueryReviewDataRequestBody) -> QueryReviewDataRequestBuilder: ...
    def build(self) -> QueryReviewDataRequest: ...
