from .query_reviewee_request_body import QueryRevieweeRequestBody as QueryRevieweeRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class QueryRevieweeRequest(BaseRequest):
    user_id_type: str | None
    page_token: str | None
    page_size: int | None
    request_body: QueryRevieweeRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> QueryRevieweeRequestBuilder: ...

class QueryRevieweeRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> QueryRevieweeRequestBuilder: ...
    def page_token(self, page_token: str) -> QueryRevieweeRequestBuilder: ...
    def page_size(self, page_size: int) -> QueryRevieweeRequestBuilder: ...
    def request_body(self, request_body: QueryRevieweeRequestBody) -> QueryRevieweeRequestBuilder: ...
    def build(self) -> QueryRevieweeRequest: ...
