from .review_template import ReviewTemplate as ReviewTemplate
from lark_oapi.core.construct import init as init

class QueryReviewTemplateResponseBody:
    review_templates: list[ReviewTemplate] | None
    has_more: bool | None
    page_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryReviewTemplateResponseBodyBuilder: ...

class QueryReviewTemplateResponseBodyBuilder:
    def __init__(self) -> None: ...
    def review_templates(self, review_templates: list[ReviewTemplate]) -> QueryReviewTemplateResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> QueryReviewTemplateResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> QueryReviewTemplateResponseBodyBuilder: ...
    def build(self) -> QueryReviewTemplateResponseBody: ...
