from .review_profile import ReviewProfile as ReviewProfile
from lark_oapi.core.construct import init as init

class QueryReviewDataResponseBody:
    datas: list[ReviewProfile] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryReviewDataResponseBodyBuilder: ...

class QueryReviewDataResponseBodyBuilder:
    def __init__(self) -> None: ...
    def datas(self, datas: list[ReviewProfile]) -> QueryReviewDataResponseBodyBuilder: ...
    def build(self) -> QueryReviewDataResponseBody: ...
