from .query_metric_detail_request_body import QueryMetricDetailRequestBody as QueryMetricDetailRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class QueryMetricDetailRequest(BaseRequest):
    user_id_type: str | None
    request_body: QueryMetricDetailRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> QueryMetricDetailRequestBuilder: ...

class QueryMetricDetailRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> QueryMetricDetailRequestBuilder: ...
    def request_body(self, request_body: QueryMetricDetailRequestBody) -> QueryMetricDetailRequestBuilder: ...
    def build(self) -> QueryMetricDetailRequest: ...
