from lark_oapi.core.construct import init as init

class QueryMetricFieldRequestBody:
    field_ids: list[int] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryMetricFieldRequestBodyBuilder: ...

class QueryMetricFieldRequestBodyBuilder:
    def __init__(self) -> None: ...
    def field_ids(self, field_ids: list[int]) -> QueryMetricFieldRequestBodyBuilder: ...
    def build(self) -> QueryMetricFieldRequestBody: ...
