from .reviewee import Reviewee as Reviewee
from lark_oapi.core.construct import init as init

class QueryRevieweeResponseBody:
    semester_id: str | None
    reviewees: list[Reviewee] | None
    has_more: bool | None
    page_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryRevieweeResponseBodyBuilder: ...

class QueryRevieweeResponseBodyBuilder:
    def __init__(self) -> None: ...
    def semester_id(self, semester_id: str) -> QueryRevieweeResponseBodyBuilder: ...
    def reviewees(self, reviewees: list[Reviewee]) -> QueryRevieweeResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> QueryRevieweeResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> QueryRevieweeResponseBodyBuilder: ...
    def build(self) -> QueryRevieweeResponseBody: ...
