from lark_oapi.core.construct import init as init

class QueryMetricLibRequestBody:
    is_active: bool | None
    tag_ids: list[int] | None
    type_ids: list[int] | None
    range_of_availability: str | None
    scoring_setting_type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryMetricLibRequestBodyBuilder: ...

class QueryMetricLibRequestBodyBuilder:
    def __init__(self) -> None: ...
    def is_active(self, is_active: bool) -> QueryMetricLibRequestBodyBuilder: ...
    def tag_ids(self, tag_ids: list[int]) -> QueryMetricLibRequestBodyBuilder: ...
    def type_ids(self, type_ids: list[int]) -> QueryMetricLibRequestBodyBuilder: ...
    def range_of_availability(self, range_of_availability: str) -> QueryMetricLibRequestBodyBuilder: ...
    def scoring_setting_type(self, scoring_setting_type: str) -> QueryMetricLibRequestBodyBuilder: ...
    def build(self) -> QueryMetricLibRequestBody: ...
