from lark_oapi.core.construct import init as init

class QueryMetricDetailRequestBody:
    semester_id: int | None
    reviewee_user_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryMetricDetailRequestBodyBuilder: ...

class QueryMetricDetailRequestBodyBuilder:
    def __init__(self) -> None: ...
    def semester_id(self, semester_id: int) -> QueryMetricDetailRequestBodyBuilder: ...
    def reviewee_user_ids(self, reviewee_user_ids: list[str]) -> QueryMetricDetailRequestBodyBuilder: ...
    def build(self) -> QueryMetricDetailRequestBody: ...
