from .metric_field import MetricField as MetricField
from lark_oapi.core.construct import init as init

class QueryMetricFieldResponseBody:
    items: list[MetricField] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryMetricFieldResponseBodyBuilder: ...

class QueryMetricFieldResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[MetricField]) -> QueryMetricFieldResponseBodyBuilder: ...
    def build(self) -> QueryMetricFieldResponseBody: ...
