from .activity import Activity as Activity
from lark_oapi.core.construct import init as init

class QueryActivityResponseBody:
    activities: list[Activity] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryActivityResponseBodyBuilder: ...

class QueryActivityResponseBodyBuilder:
    def __init__(self) -> None: ...
    def activities(self, activities: list[Activity]) -> QueryActivityResponseBodyBuilder: ...
    def build(self) -> QueryActivityResponseBody: ...
