from lark_oapi.core.construct import init as init

class QueryQuestionRequestBody:
    tag_based_question_ids: list[int] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryQuestionRequestBodyBuilder: ...

class QueryQuestionRequestBodyBuilder:
    def __init__(self) -> None: ...
    def tag_based_question_ids(self, tag_based_question_ids: list[int]) -> QueryQuestionRequestBodyBuilder: ...
    def build(self) -> QueryQuestionRequestBody: ...
