from .i18n import I18n as I18n
from .tag_item import TagItem as TagItem
from lark_oapi.core.construct import init as init

class Question:
    question_id: str | None
    name: I18n | None
    tag_items: list[TagItem] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QuestionBuilder: ...

class QuestionBuilder:
    def __init__(self) -> None: ...
    def question_id(self, question_id: str) -> QuestionBuilder: ...
    def name(self, name: I18n) -> QuestionBuilder: ...
    def tag_items(self, tag_items: list[TagItem]) -> QuestionBuilder: ...
    def build(self) -> Question: ...
