from .stage_change import StageChange as StageChange
from .user_id import UserId as UserId
from lark_oapi.core.construct import init as init

class ReviewDataChange:
    user_id: UserId | None
    semester_id: str | None
    activity_id: str | None
    stage_changes: list[StageChange] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReviewDataChangeBuilder: ...

class ReviewDataChangeBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: UserId) -> ReviewDataChangeBuilder: ...
    def semester_id(self, semester_id: str) -> ReviewDataChangeBuilder: ...
    def activity_id(self, activity_id: str) -> ReviewDataChangeBuilder: ...
    def stage_changes(self, stage_changes: list[StageChange]) -> ReviewDataChangeBuilder: ...
    def build(self) -> ReviewDataChange: ...
