from .review_record import ReviewRecord as ReviewRecord
from lark_oapi.core.construct import init as init

class ReviewStage:
    stage_id: str | None
    stage_type: str | None
    review_stage_roles: list[str] | None
    template_id: str | None
    records: list[ReviewRecord] | None
    review_stage_role: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReviewStageBuilder: ...

class ReviewStageBuilder:
    def __init__(self) -> None: ...
    def stage_id(self, stage_id: str) -> ReviewStageBuilder: ...
    def stage_type(self, stage_type: str) -> ReviewStageBuilder: ...
    def review_stage_roles(self, review_stage_roles: list[str]) -> ReviewStageBuilder: ...
    def template_id(self, template_id: str) -> ReviewStageBuilder: ...
    def records(self, records: list[ReviewRecord]) -> ReviewStageBuilder: ...
    def review_stage_role(self, review_stage_role: str) -> ReviewStageBuilder: ...
    def build(self) -> ReviewStage: ...
