from .i18n import I18n as I18n
from .template import Template as Template
from .unit import Unit as Unit
from lark_oapi.core.construct import init as init

class ReviewTemplate:
    templates: list[Template] | None
    units: list[Unit] | None
    review_template_id: str | None
    name: I18n | None
    description: I18n | None
    status: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReviewTemplateBuilder: ...

class ReviewTemplateBuilder:
    def __init__(self) -> None: ...
    def templates(self, templates: list[Template]) -> ReviewTemplateBuilder: ...
    def units(self, units: list[Unit]) -> ReviewTemplateBuilder: ...
    def review_template_id(self, review_template_id: str) -> ReviewTemplateBuilder: ...
    def name(self, name: I18n) -> ReviewTemplateBuilder: ...
    def description(self, description: I18n) -> ReviewTemplateBuilder: ...
    def status(self, status: str) -> ReviewTemplateBuilder: ...
    def build(self) -> ReviewTemplate: ...
