from .review_data_permission_unit import ReviewDataPermissionUnit as ReviewDataPermissionUnit
from lark_oapi.core.construct import init as init

class ReviewDataPermissionStage:
    stage_id: str | None
    stage_type: str | None
    units: list[ReviewDataPermissionUnit] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReviewDataPermissionStageBuilder: ...

class ReviewDataPermissionStageBuilder:
    def __init__(self) -> None: ...
    def stage_id(self, stage_id: str) -> ReviewDataPermissionStageBuilder: ...
    def stage_type(self, stage_type: str) -> ReviewDataPermissionStageBuilder: ...
    def units(self, units: list[ReviewDataPermissionUnit]) -> ReviewDataPermissionStageBuilder: ...
    def build(self) -> ReviewDataPermissionStage: ...
