from .review_data_permission_stage import ReviewDataPermissionStage as ReviewDataPermissionStage
from .user import User as User
from lark_oapi.core.construct import init as init

class ReviewDataPermission:
    user_id: User | None
    semester_id: str | None
    activity_id: str | None
    review_template_id: str | None
    stages: list[ReviewDataPermissionStage] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReviewDataPermissionBuilder: ...

class ReviewDataPermissionBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: User) -> ReviewDataPermissionBuilder: ...
    def semester_id(self, semester_id: str) -> ReviewDataPermissionBuilder: ...
    def activity_id(self, activity_id: str) -> ReviewDataPermissionBuilder: ...
    def review_template_id(self, review_template_id: str) -> ReviewDataPermissionBuilder: ...
    def stages(self, stages: list[ReviewDataPermissionStage]) -> ReviewDataPermissionBuilder: ...
    def build(self) -> ReviewDataPermission: ...
