from .review_stage import ReviewStage as ReviewStage
from .user import User as User
from lark_oapi.core.construct import init as init

class ReviewProfile:
    user_id: User | None
    semester_id: str | None
    activity_id: str | None
    review_template_id: str | None
    stages: list[ReviewStage] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReviewProfileBuilder: ...

class ReviewProfileBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: User) -> ReviewProfileBuilder: ...
    def semester_id(self, semester_id: str) -> ReviewProfileBuilder: ...
    def activity_id(self, activity_id: str) -> ReviewProfileBuilder: ...
    def review_template_id(self, review_template_id: str) -> ReviewProfileBuilder: ...
    def stages(self, stages: list[ReviewStage]) -> ReviewProfileBuilder: ...
    def build(self) -> ReviewProfile: ...
