from lark_oapi.core.construct import init as init

class ReviewDataPermissionField:
    field_id: str | None
    indicator_id: str | None
    action: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReviewDataPermissionFieldBuilder: ...

class ReviewDataPermissionFieldBuilder:
    def __init__(self) -> None: ...
    def field_id(self, field_id: str) -> ReviewDataPermissionFieldBuilder: ...
    def indicator_id(self, indicator_id: str) -> ReviewDataPermissionFieldBuilder: ...
    def action(self, action: list[str]) -> ReviewDataPermissionFieldBuilder: ...
    def build(self) -> ReviewDataPermissionField: ...
