from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class ReviewerInfo:
    invite_distribute_type: int | None
    invite_avg_diff: str | None
    invite_relationship_with_reviewee: str | None
    invite_invitedby: str | None
    cooperation_project: str | None
    cooperation_project_name: I18n | None
    direct_project_leader_role_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReviewerInfoBuilder: ...

class ReviewerInfoBuilder:
    def __init__(self) -> None: ...
    def invite_distribute_type(self, invite_distribute_type: int) -> ReviewerInfoBuilder: ...
    def invite_avg_diff(self, invite_avg_diff: str) -> ReviewerInfoBuilder: ...
    def invite_relationship_with_reviewee(self, invite_relationship_with_reviewee: str) -> ReviewerInfoBuilder: ...
    def invite_invitedby(self, invite_invitedby: str) -> ReviewerInfoBuilder: ...
    def cooperation_project(self, cooperation_project: str) -> ReviewerInfoBuilder: ...
    def cooperation_project_name(self, cooperation_project_name: I18n) -> ReviewerInfoBuilder: ...
    def direct_project_leader_role_id(self, direct_project_leader_role_id: str) -> ReviewerInfoBuilder: ...
    def build(self) -> ReviewerInfo: ...
