from .i18n import I18n as I18n
from .template_stage import TemplateStage as TemplateStage
from lark_oapi.core.construct import init as init

class SemesterStage:
    id: str | None
    name: I18n | None
    stages: list[TemplateStage] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SemesterStageBuilder: ...

class SemesterStageBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> SemesterStageBuilder: ...
    def name(self, name: I18n) -> SemesterStageBuilder: ...
    def stages(self, stages: list[TemplateStage]) -> SemesterStageBuilder: ...
    def build(self) -> SemesterStage: ...
