from lark_oapi.core.construct import init as init

class StageChange:
    stage_id: str | None
    stage_type: str | None
    review_stage_role: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> StageChangeBuilder: ...

class StageChangeBuilder:
    def __init__(self) -> None: ...
    def stage_id(self, stage_id: str) -> StageChangeBuilder: ...
    def stage_type(self, stage_type: str) -> StageChangeBuilder: ...
    def review_stage_role(self, review_stage_role: str) -> StageChangeBuilder: ...
    def build(self) -> StageChange: ...
