from lark_oapi.core.construct import init as init

class SubIndicator:
    field_id: str | None
    indicator_id: str | None
    option_id: str | None
    score: str | None
    text: str | None
    richtext: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SubIndicatorBuilder: ...

class SubIndicatorBuilder:
    def __init__(self) -> None: ...
    def field_id(self, field_id: str) -> SubIndicatorBuilder: ...
    def indicator_id(self, indicator_id: str) -> SubIndicatorBuilder: ...
    def option_id(self, option_id: str) -> SubIndicatorBuilder: ...
    def score(self, score: str) -> SubIndicatorBuilder: ...
    def text(self, text: str) -> SubIndicatorBuilder: ...
    def richtext(self, richtext: str) -> SubIndicatorBuilder: ...
    def build(self) -> SubIndicator: ...
