from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class TemplateStage:
    id: str | None
    name: I18n | None
    template_group_id: str | None
    stage_type: str | None
    perform_role: str | None
    as_final_result: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TemplateStageBuilder: ...

class TemplateStageBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> TemplateStageBuilder: ...
    def name(self, name: I18n) -> TemplateStageBuilder: ...
    def template_group_id(self, template_group_id: str) -> TemplateStageBuilder: ...
    def stage_type(self, stage_type: str) -> TemplateStageBuilder: ...
    def perform_role(self, perform_role: str) -> TemplateStageBuilder: ...
    def as_final_result(self, as_final_result: bool) -> TemplateStageBuilder: ...
    def build(self) -> TemplateStage: ...
