from .okr import Okr as Okr
from .user import User as User
from lark_oapi.core.construct import init as init

class UserOkr:
    reviewee_user_id: User | None
    okrs: list[Okr] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserOkrBuilder: ...

class UserOkrBuilder:
    def __init__(self) -> None: ...
    def reviewee_user_id(self, reviewee_user_id: User) -> UserOkrBuilder: ...
    def okrs(self, okrs: list[Okr]) -> UserOkrBuilder: ...
    def build(self) -> UserOkr: ...
