from lark_oapi.core.construct import init as init

class WriteUserGroupScopeFailUserData:
    user_id: str | None
    fail_code: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WriteUserGroupScopeFailUserDataBuilder: ...

class WriteUserGroupScopeFailUserDataBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: str) -> WriteUserGroupScopeFailUserDataBuilder: ...
    def fail_code(self, fail_code: int) -> WriteUserGroupScopeFailUserDataBuilder: ...
    def build(self) -> WriteUserGroupScopeFailUserData: ...
