from lark_oapi.core.construct import init as init

class WriteUserGroupUserRelRequestBody:
    group_id: str | None
    scope_visible_setting: int | None
    user_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WriteUserGroupUserRelRequestBodyBuilder: ...

class WriteUserGroupUserRelRequestBodyBuilder:
    def __init__(self) -> None: ...
    def group_id(self, group_id: str) -> WriteUserGroupUserRelRequestBodyBuilder: ...
    def scope_visible_setting(self, scope_visible_setting: int) -> WriteUserGroupUserRelRequestBodyBuilder: ...
    def user_ids(self, user_ids: list[str]) -> WriteUserGroupUserRelRequestBodyBuilder: ...
    def build(self) -> WriteUserGroupUserRelRequestBody: ...
