from .write_user_group_scope_fail_user_data import WriteUserGroupScopeFailUserData as WriteUserGroupScopeFailUserData
from lark_oapi.core.construct import init as init

class WriteUserGroupScopeData:
    success_user_ids: list[str] | None
    fail_user_datas: list[WriteUserGroupScopeFailUserData] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WriteUserGroupScopeDataBuilder: ...

class WriteUserGroupScopeDataBuilder:
    def __init__(self) -> None: ...
    def success_user_ids(self, success_user_ids: list[str]) -> WriteUserGroupScopeDataBuilder: ...
    def fail_user_datas(self, fail_user_datas: list[WriteUserGroupScopeFailUserData]) -> WriteUserGroupScopeDataBuilder: ...
    def build(self) -> WriteUserGroupScopeData: ...
