from lark_oapi.core.construct import init as init

class AdminUserStat:
    date: str | None
    user_id: str | None
    user_name: str | None
    department_name: str | None
    department_path: str | None
    create_time: str | None
    user_active_flag: int | None
    register_time: str | None
    suite_active_flag: int | None
    last_active_time: str | None
    im_active_flag: int | None
    send_messenger_num: int | None
    docs_active_flag: int | None
    create_docs_num: int | None
    cal_active_flag: int | None
    create_cal_num: int | None
    vc_active_flag: int | None
    vc_duration: int | None
    active_os: str | None
    create_task_num: int | None
    vc_num: int | None
    app_package_type: str | None
    os_name: str | None
    email_send_count: int | None
    email_receive_count: int | None
    email_send_ext_count: int | None
    email_receive_ext_count: int | None
    email_send_in_count: int | None
    email_receive_in_count: int | None
    search_active_flag: int | None
    total_search_count: int | None
    quick_search_count: int | None
    tab_search_count: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AdminUserStatBuilder: ...

class AdminUserStatBuilder:
    def __init__(self) -> None: ...
    def date(self, date: str) -> AdminUserStatBuilder: ...
    def user_id(self, user_id: str) -> AdminUserStatBuilder: ...
    def user_name(self, user_name: str) -> AdminUserStatBuilder: ...
    def department_name(self, department_name: str) -> AdminUserStatBuilder: ...
    def department_path(self, department_path: str) -> AdminUserStatBuilder: ...
    def create_time(self, create_time: str) -> AdminUserStatBuilder: ...
    def user_active_flag(self, user_active_flag: int) -> AdminUserStatBuilder: ...
    def register_time(self, register_time: str) -> AdminUserStatBuilder: ...
    def suite_active_flag(self, suite_active_flag: int) -> AdminUserStatBuilder: ...
    def last_active_time(self, last_active_time: str) -> AdminUserStatBuilder: ...
    def im_active_flag(self, im_active_flag: int) -> AdminUserStatBuilder: ...
    def send_messenger_num(self, send_messenger_num: int) -> AdminUserStatBuilder: ...
    def docs_active_flag(self, docs_active_flag: int) -> AdminUserStatBuilder: ...
    def create_docs_num(self, create_docs_num: int) -> AdminUserStatBuilder: ...
    def cal_active_flag(self, cal_active_flag: int) -> AdminUserStatBuilder: ...
    def create_cal_num(self, create_cal_num: int) -> AdminUserStatBuilder: ...
    def vc_active_flag(self, vc_active_flag: int) -> AdminUserStatBuilder: ...
    def vc_duration(self, vc_duration: int) -> AdminUserStatBuilder: ...
    def active_os(self, active_os: str) -> AdminUserStatBuilder: ...
    def create_task_num(self, create_task_num: int) -> AdminUserStatBuilder: ...
    def vc_num(self, vc_num: int) -> AdminUserStatBuilder: ...
    def app_package_type(self, app_package_type: str) -> AdminUserStatBuilder: ...
    def os_name(self, os_name: str) -> AdminUserStatBuilder: ...
    def email_send_count(self, email_send_count: int) -> AdminUserStatBuilder: ...
    def email_receive_count(self, email_receive_count: int) -> AdminUserStatBuilder: ...
    def email_send_ext_count(self, email_send_ext_count: int) -> AdminUserStatBuilder: ...
    def email_receive_ext_count(self, email_receive_ext_count: int) -> AdminUserStatBuilder: ...
    def email_send_in_count(self, email_send_in_count: int) -> AdminUserStatBuilder: ...
    def email_receive_in_count(self, email_receive_in_count: int) -> AdminUserStatBuilder: ...
    def search_active_flag(self, search_active_flag: int) -> AdminUserStatBuilder: ...
    def total_search_count(self, total_search_count: int) -> AdminUserStatBuilder: ...
    def quick_search_count(self, quick_search_count: int) -> AdminUserStatBuilder: ...
    def tab_search_count(self, tab_search_count: int) -> AdminUserStatBuilder: ...
    def build(self) -> AdminUserStat: ...
