from lark_oapi.core.construct import init as init

class AdminUserExtContactStat:
    date: str | None
    user_id: str | None
    user_name: str | None
    department_name: str | None
    ref_contact_ucnt: str | None
    ref_contact_tcnt: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AdminUserExtContactStatBuilder: ...

class AdminUserExtContactStatBuilder:
    def __init__(self) -> None: ...
    def date(self, date: str) -> AdminUserExtContactStatBuilder: ...
    def user_id(self, user_id: str) -> AdminUserExtContactStatBuilder: ...
    def user_name(self, user_name: str) -> AdminUserExtContactStatBuilder: ...
    def department_name(self, department_name: str) -> AdminUserExtContactStatBuilder: ...
    def ref_contact_ucnt(self, ref_contact_ucnt: str) -> AdminUserExtContactStatBuilder: ...
    def ref_contact_tcnt(self, ref_contact_tcnt: str) -> AdminUserExtContactStatBuilder: ...
    def build(self) -> AdminUserExtContactStat: ...
