from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class Badge:
    id: str | None
    name: str | None
    explanation: str | None
    detail_image: str | None
    show_image: str | None
    i18n_name: I18n | None
    i18n_explanation: I18n | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BadgeBuilder: ...

class BadgeBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> BadgeBuilder: ...
    def name(self, name: str) -> BadgeBuilder: ...
    def explanation(self, explanation: str) -> BadgeBuilder: ...
    def detail_image(self, detail_image: str) -> BadgeBuilder: ...
    def show_image(self, show_image: str) -> BadgeBuilder: ...
    def i18n_name(self, i18n_name: I18n) -> BadgeBuilder: ...
    def i18n_explanation(self, i18n_explanation: I18n) -> BadgeBuilder: ...
    def build(self) -> Badge: ...
