from lark_oapi.core.construct import init as init

class CreateBadgeImageResponseBody:
    image_key: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateBadgeImageResponseBodyBuilder: ...

class CreateBadgeImageResponseBodyBuilder:
    def __init__(self) -> None: ...
    def image_key(self, image_key: str) -> CreateBadgeImageResponseBodyBuilder: ...
    def build(self) -> CreateBadgeImageResponseBody: ...
