from .create_badge_image_request_body import CreateBadgeImageRequestBody as CreateBadgeImageRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateBadgeImageRequest(BaseRequest):
    request_body: CreateBadgeImageRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateBadgeImageRequestBuilder: ...

class CreateBadgeImageRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: CreateBadgeImageRequestBody) -> CreateBadgeImageRequestBuilder: ...
    def build(self) -> CreateBadgeImageRequest: ...
