from lark_oapi.core.construct import init as init

class DeleteBadgeGrantResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteBadgeGrantResponseBodyBuilder: ...

class DeleteBadgeGrantResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteBadgeGrantResponseBody: ...
