from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetBadgeGrantRequest(BaseRequest):
    user_id_type: str | None
    department_id_type: str | None
    badge_id: str | None
    grant_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetBadgeGrantRequestBuilder: ...

class GetBadgeGrantRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> GetBadgeGrantRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> GetBadgeGrantRequestBuilder: ...
    def badge_id(self, badge_id: str) -> GetBadgeGrantRequestBuilder: ...
    def grant_id(self, grant_id: str) -> GetBadgeGrantRequestBuilder: ...
    def build(self) -> GetBadgeGrantRequest: ...
