from .rule_detail import RuleDetail as RuleDetail
from lark_oapi.core.construct import init as init

class Grant:
    id: str | None
    badge_id: str | None
    name: str | None
    grant_type: int | None
    time_zone: str | None
    rule_detail: RuleDetail | None
    is_grant_all: bool | None
    user_ids: list[str] | None
    department_ids: list[str] | None
    group_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GrantBuilder: ...

class GrantBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> GrantBuilder: ...
    def badge_id(self, badge_id: str) -> GrantBuilder: ...
    def name(self, name: str) -> GrantBuilder: ...
    def grant_type(self, grant_type: int) -> GrantBuilder: ...
    def time_zone(self, time_zone: str) -> GrantBuilder: ...
    def rule_detail(self, rule_detail: RuleDetail) -> GrantBuilder: ...
    def is_grant_all(self, is_grant_all: bool) -> GrantBuilder: ...
    def user_ids(self, user_ids: list[str]) -> GrantBuilder: ...
    def department_ids(self, department_ids: list[str]) -> GrantBuilder: ...
    def group_ids(self, group_ids: list[str]) -> GrantBuilder: ...
    def build(self) -> Grant: ...
