from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListAuditInfoRequest(BaseRequest):
    user_id_type: str | None
    latest: int | None
    oldest: int | None
    event_name: str | None
    operator_type: str | None
    operator_value: str | None
    event_module: int | None
    page_token: str | None
    page_size: int | None
    user_type: int | None
    object_type: int | None
    object_value: str | None
    ext_filter_object_by_ccm_token: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListAuditInfoRequestBuilder: ...

class ListAuditInfoRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> ListAuditInfoRequestBuilder: ...
    def latest(self, latest: int) -> ListAuditInfoRequestBuilder: ...
    def oldest(self, oldest: int) -> ListAuditInfoRequestBuilder: ...
    def event_name(self, event_name: str) -> ListAuditInfoRequestBuilder: ...
    def operator_type(self, operator_type: str) -> ListAuditInfoRequestBuilder: ...
    def operator_value(self, operator_value: str) -> ListAuditInfoRequestBuilder: ...
    def event_module(self, event_module: int) -> ListAuditInfoRequestBuilder: ...
    def page_token(self, page_token: str) -> ListAuditInfoRequestBuilder: ...
    def page_size(self, page_size: int) -> ListAuditInfoRequestBuilder: ...
    def user_type(self, user_type: int) -> ListAuditInfoRequestBuilder: ...
    def object_type(self, object_type: int) -> ListAuditInfoRequestBuilder: ...
    def object_value(self, object_value: str) -> ListAuditInfoRequestBuilder: ...
    def ext_filter_object_by_ccm_token(self, ext_filter_object_by_ccm_token: str) -> ListAuditInfoRequestBuilder: ...
    def build(self) -> ListAuditInfoRequest: ...
