from lark_oapi.core.construct import init as init

class ListBadgeRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListBadgeRequestBodyBuilder: ...

class ListBadgeRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListBadgeRequestBody: ...
