from .audit_info import AuditInfo as AuditInfo
from lark_oapi.core.construct import init as init

class ListAuditInfoResponseBody:
    has_more: bool | None
    page_token: str | None
    items: list[AuditInfo] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListAuditInfoResponseBodyBuilder: ...

class ListAuditInfoResponseBodyBuilder:
    def __init__(self) -> None: ...
    def has_more(self, has_more: bool) -> ListAuditInfoResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListAuditInfoResponseBodyBuilder: ...
    def items(self, items: list[AuditInfo]) -> ListAuditInfoResponseBodyBuilder: ...
    def build(self) -> ListAuditInfoResponseBody: ...
