from lark_oapi.core.construct import init as init

class ListAuditInfoRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListAuditInfoRequestBodyBuilder: ...

class ListAuditInfoRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListAuditInfoRequestBody: ...
