from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class OperatorName:
    default_name: str | None
    i18n_value: I18n | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OperatorNameBuilder: ...

class OperatorNameBuilder:
    def __init__(self) -> None: ...
    def default_name(self, default_name: str) -> OperatorNameBuilder: ...
    def i18n_value(self, i18n_value: I18n) -> OperatorNameBuilder: ...
    def build(self) -> OperatorName: ...
