from .password import Password as Password
from lark_oapi.core.construct import init as init

class ResetPasswordRequestBody:
    password: Password | None
    user_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ResetPasswordRequestBodyBuilder: ...

class ResetPasswordRequestBodyBuilder:
    def __init__(self) -> None: ...
    def password(self, password: Password) -> ResetPasswordRequestBodyBuilder: ...
    def user_id(self, user_id: str) -> ResetPasswordRequestBodyBuilder: ...
    def build(self) -> ResetPasswordRequestBody: ...
