from lark_oapi.core.construct import init as init

class SplashPageStat:
    date: str | None
    splash_id: str | None
    impression_count: int | None
    click_count: int | None
    skip_count: int | None
    impression_count_accumulate: int | None
    click_count_accumulate: int | None
    skip_count_accumulate: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SplashPageStatBuilder: ...

class SplashPageStatBuilder:
    def __init__(self) -> None: ...
    def date(self, date: str) -> SplashPageStatBuilder: ...
    def splash_id(self, splash_id: str) -> SplashPageStatBuilder: ...
    def impression_count(self, impression_count: int) -> SplashPageStatBuilder: ...
    def click_count(self, click_count: int) -> SplashPageStatBuilder: ...
    def skip_count(self, skip_count: int) -> SplashPageStatBuilder: ...
    def impression_count_accumulate(self, impression_count_accumulate: int) -> SplashPageStatBuilder: ...
    def click_count_accumulate(self, click_count_accumulate: int) -> SplashPageStatBuilder: ...
    def skip_count_accumulate(self, skip_count_accumulate: int) -> SplashPageStatBuilder: ...
    def build(self) -> SplashPageStat: ...
