from .file import File as File
from lark_oapi.core.construct import init as init

class Task:
    original_user_id: str | None
    target_owner_id: str | None
    file_list: list[File] | None
    task_id: str | None
    status: int | None
    original_user_email: str | None
    target_owner_email: str | None
    type: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TaskBuilder: ...

class TaskBuilder:
    def __init__(self) -> None: ...
    def original_user_id(self, original_user_id: str) -> TaskBuilder: ...
    def target_owner_id(self, target_owner_id: str) -> TaskBuilder: ...
    def file_list(self, file_list: list[File]) -> TaskBuilder: ...
    def task_id(self, task_id: str) -> TaskBuilder: ...
    def status(self, status: int) -> TaskBuilder: ...
    def original_user_email(self, original_user_email: str) -> TaskBuilder: ...
    def target_owner_email(self, target_owner_email: str) -> TaskBuilder: ...
    def type(self, type: int) -> TaskBuilder: ...
    def build(self) -> Task: ...
