from .grant import Grant as Grant
from lark_oapi.core.construct import init as init

class UpdateBadgeGrantResponseBody:
    grant: Grant | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateBadgeGrantResponseBodyBuilder: ...

class UpdateBadgeGrantResponseBodyBuilder:
    def __init__(self) -> None: ...
    def grant(self, grant: Grant) -> UpdateBadgeGrantResponseBodyBuilder: ...
    def build(self) -> UpdateBadgeGrantResponseBody: ...
