from .badge import Badge as Badge
from lark_oapi.core.construct import init as init

class UpdateBadgeResponseBody:
    badge: Badge | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateBadgeResponseBodyBuilder: ...

class UpdateBadgeResponseBodyBuilder:
    def __init__(self) -> None: ...
    def badge(self, badge: Badge) -> UpdateBadgeResponseBodyBuilder: ...
    def build(self) -> UpdateBadgeResponseBody: ...
