from lark_oapi.core.construct import init as init

class UserReport2021:
    active_day_count: int | None
    busy_week: str | None
    p2p_chat_count: str | None
    talked_chat_count: str | None
    favorite_emoji: str | None
    reaction_count: str | None
    conference_create_count: str | None
    total_parti_count: str | None
    minutes_object_count: str | None
    minutes_duration: float | None
    create_edit_file_count: str | None
    create_file_count: str | None
    cooperate_edit_file_count: str | None
    like_record_count: str | None
    okr_cum_o_count: str | None
    okr_cum_kr_count: str | None
    okr_aligned_user_rankfirst: str | None
    approval_start_count: str | None
    approval_execute_count: str | None
    approval_relation_user_rankfirst: str | None
    user_id: str | None
    busy_week_sum_duration: str | None
    busy_week_mdate: str | None
    busy_week_act_days: int | None
    create_read_user_count: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserReport2021Builder: ...

class UserReport2021Builder:
    def __init__(self) -> None: ...
    def active_day_count(self, active_day_count: int) -> UserReport2021Builder: ...
    def busy_week(self, busy_week: str) -> UserReport2021Builder: ...
    def p2p_chat_count(self, p2p_chat_count: str) -> UserReport2021Builder: ...
    def talked_chat_count(self, talked_chat_count: str) -> UserReport2021Builder: ...
    def favorite_emoji(self, favorite_emoji: str) -> UserReport2021Builder: ...
    def reaction_count(self, reaction_count: str) -> UserReport2021Builder: ...
    def conference_create_count(self, conference_create_count: str) -> UserReport2021Builder: ...
    def total_parti_count(self, total_parti_count: str) -> UserReport2021Builder: ...
    def minutes_object_count(self, minutes_object_count: str) -> UserReport2021Builder: ...
    def minutes_duration(self, minutes_duration: float) -> UserReport2021Builder: ...
    def create_edit_file_count(self, create_edit_file_count: str) -> UserReport2021Builder: ...
    def create_file_count(self, create_file_count: str) -> UserReport2021Builder: ...
    def cooperate_edit_file_count(self, cooperate_edit_file_count: str) -> UserReport2021Builder: ...
    def like_record_count(self, like_record_count: str) -> UserReport2021Builder: ...
    def okr_cum_o_count(self, okr_cum_o_count: str) -> UserReport2021Builder: ...
    def okr_cum_kr_count(self, okr_cum_kr_count: str) -> UserReport2021Builder: ...
    def okr_aligned_user_rankfirst(self, okr_aligned_user_rankfirst: str) -> UserReport2021Builder: ...
    def approval_start_count(self, approval_start_count: str) -> UserReport2021Builder: ...
    def approval_execute_count(self, approval_execute_count: str) -> UserReport2021Builder: ...
    def approval_relation_user_rankfirst(self, approval_relation_user_rankfirst: str) -> UserReport2021Builder: ...
    def user_id(self, user_id: str) -> UserReport2021Builder: ...
    def busy_week_sum_duration(self, busy_week_sum_duration: str) -> UserReport2021Builder: ...
    def busy_week_mdate(self, busy_week_mdate: str) -> UserReport2021Builder: ...
    def busy_week_act_days(self, busy_week_act_days: int) -> UserReport2021Builder: ...
    def create_read_user_count(self, create_read_user_count: str) -> UserReport2021Builder: ...
    def build(self) -> UserReport2021: ...
