from .annual_report_map_float import AnnualReportMapFloat as AnnualReportMapFloat
from .annual_report_map_int import AnnualReportMapInt as AnnualReportMapInt
from lark_oapi.core.construct import init as init

class UserReport2024:
    user_id: str | None
    tenant_all_cnt: int | None
    user_register_date: str | None
    feishu_day_cnt: int | None
    duration_cnt_2: list[AnnualReportMapFloat] | None
    im_send_msg_cnt_2: list[AnnualReportMapInt] | None
    avg_im_send_msg_cnt_2: list[AnnualReportMapFloat] | None
    im_talked_chat_cnt: int | None
    im_private_chat_cnt: int | None
    im_emoji_top1: str | None
    im_emoji_top1_cnt_2: list[AnnualReportMapInt] | None
    im_emoji_top2: str | None
    im_emoji_top2_cnt_2: list[AnnualReportMapInt] | None
    im_emoji_top3: str | None
    im_emoji_top3_cnt_2: list[AnnualReportMapInt] | None
    im_positive_reaction_cnt_2: list[AnnualReportMapInt] | None
    im_positive_reaction_cnt_rank: int | None
    im_positive_reaction_cnt_denominator: int | None
    busy_day: str | None
    busy_day_send_msg_cnt: int | None
    ccm_create_cnt_2: list[AnnualReportMapInt] | None
    ccm_create_viewed_ucnt: int | None
    ccm_create_liked_cnt: int | None
    ccm_create_liked_max_cnt: int | None
    vc_join_meeting_cnt: int | None
    vc_all_meeting_duration_2: list[AnnualReportMapFloat] | None
    vc_join_meeting_all_user_cnt: int | None
    vc_last_meeting_time: str | None
    base_create_fcnt_2: list[AnnualReportMapInt] | None
    base_view_fcnt: int | None
    base_create_dashboard_cnt: int | None
    base_create_dashboard_rank: int | None
    base_create_dashboard_rank_ucnt: int | None
    base_create_chat_cnt: int | None
    base_workflow_ins_cnt: int | None
    base_workflow_ins_rank: int | None
    base_workflow_ins_rank_ucnt: int | None
    vc_all_read_notes_cnt: int | None
    meego_role_wi_cnt_v2: list[AnnualReportMapInt] | None
    meego_common_wi_ucnt: int | None
    meego_workflow_wi_cnt: int | None
    people_interview_num_2: list[AnnualReportMapInt] | None
    people_interview_num_rank: int | None
    people_interview_num_rank_ucnt: int | None
    people_interview_offer_num_2: list[AnnualReportMapInt] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserReport2024Builder: ...

class UserReport2024Builder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: str) -> UserReport2024Builder: ...
    def tenant_all_cnt(self, tenant_all_cnt: int) -> UserReport2024Builder: ...
    def user_register_date(self, user_register_date: str) -> UserReport2024Builder: ...
    def feishu_day_cnt(self, feishu_day_cnt: int) -> UserReport2024Builder: ...
    def duration_cnt_2(self, duration_cnt_2: list[AnnualReportMapFloat]) -> UserReport2024Builder: ...
    def im_send_msg_cnt_2(self, im_send_msg_cnt_2: list[AnnualReportMapInt]) -> UserReport2024Builder: ...
    def avg_im_send_msg_cnt_2(self, avg_im_send_msg_cnt_2: list[AnnualReportMapFloat]) -> UserReport2024Builder: ...
    def im_talked_chat_cnt(self, im_talked_chat_cnt: int) -> UserReport2024Builder: ...
    def im_private_chat_cnt(self, im_private_chat_cnt: int) -> UserReport2024Builder: ...
    def im_emoji_top1(self, im_emoji_top1: str) -> UserReport2024Builder: ...
    def im_emoji_top1_cnt_2(self, im_emoji_top1_cnt_2: list[AnnualReportMapInt]) -> UserReport2024Builder: ...
    def im_emoji_top2(self, im_emoji_top2: str) -> UserReport2024Builder: ...
    def im_emoji_top2_cnt_2(self, im_emoji_top2_cnt_2: list[AnnualReportMapInt]) -> UserReport2024Builder: ...
    def im_emoji_top3(self, im_emoji_top3: str) -> UserReport2024Builder: ...
    def im_emoji_top3_cnt_2(self, im_emoji_top3_cnt_2: list[AnnualReportMapInt]) -> UserReport2024Builder: ...
    def im_positive_reaction_cnt_2(self, im_positive_reaction_cnt_2: list[AnnualReportMapInt]) -> UserReport2024Builder: ...
    def im_positive_reaction_cnt_rank(self, im_positive_reaction_cnt_rank: int) -> UserReport2024Builder: ...
    def im_positive_reaction_cnt_denominator(self, im_positive_reaction_cnt_denominator: int) -> UserReport2024Builder: ...
    def busy_day(self, busy_day: str) -> UserReport2024Builder: ...
    def busy_day_send_msg_cnt(self, busy_day_send_msg_cnt: int) -> UserReport2024Builder: ...
    def ccm_create_cnt_2(self, ccm_create_cnt_2: list[AnnualReportMapInt]) -> UserReport2024Builder: ...
    def ccm_create_viewed_ucnt(self, ccm_create_viewed_ucnt: int) -> UserReport2024Builder: ...
    def ccm_create_liked_cnt(self, ccm_create_liked_cnt: int) -> UserReport2024Builder: ...
    def ccm_create_liked_max_cnt(self, ccm_create_liked_max_cnt: int) -> UserReport2024Builder: ...
    def vc_join_meeting_cnt(self, vc_join_meeting_cnt: int) -> UserReport2024Builder: ...
    def vc_all_meeting_duration_2(self, vc_all_meeting_duration_2: list[AnnualReportMapFloat]) -> UserReport2024Builder: ...
    def vc_join_meeting_all_user_cnt(self, vc_join_meeting_all_user_cnt: int) -> UserReport2024Builder: ...
    def vc_last_meeting_time(self, vc_last_meeting_time: str) -> UserReport2024Builder: ...
    def base_create_fcnt_2(self, base_create_fcnt_2: list[AnnualReportMapInt]) -> UserReport2024Builder: ...
    def base_view_fcnt(self, base_view_fcnt: int) -> UserReport2024Builder: ...
    def base_create_dashboard_cnt(self, base_create_dashboard_cnt: int) -> UserReport2024Builder: ...
    def base_create_dashboard_rank(self, base_create_dashboard_rank: int) -> UserReport2024Builder: ...
    def base_create_dashboard_rank_ucnt(self, base_create_dashboard_rank_ucnt: int) -> UserReport2024Builder: ...
    def base_create_chat_cnt(self, base_create_chat_cnt: int) -> UserReport2024Builder: ...
    def base_workflow_ins_cnt(self, base_workflow_ins_cnt: int) -> UserReport2024Builder: ...
    def base_workflow_ins_rank(self, base_workflow_ins_rank: int) -> UserReport2024Builder: ...
    def base_workflow_ins_rank_ucnt(self, base_workflow_ins_rank_ucnt: int) -> UserReport2024Builder: ...
    def vc_all_read_notes_cnt(self, vc_all_read_notes_cnt: int) -> UserReport2024Builder: ...
    def meego_role_wi_cnt_v2(self, meego_role_wi_cnt_v2: list[AnnualReportMapInt]) -> UserReport2024Builder: ...
    def meego_common_wi_ucnt(self, meego_common_wi_ucnt: int) -> UserReport2024Builder: ...
    def meego_workflow_wi_cnt(self, meego_workflow_wi_cnt: int) -> UserReport2024Builder: ...
    def people_interview_num_2(self, people_interview_num_2: list[AnnualReportMapInt]) -> UserReport2024Builder: ...
    def people_interview_num_rank(self, people_interview_num_rank: int) -> UserReport2024Builder: ...
    def people_interview_num_rank_ucnt(self, people_interview_num_rank_ucnt: int) -> UserReport2024Builder: ...
    def people_interview_offer_num_2(self, people_interview_offer_num_2: list[AnnualReportMapInt]) -> UserReport2024Builder: ...
    def build(self) -> UserReport2024: ...
