from .user_auth_data_relation import UserAuthDataRelation as UserAuthDataRelation
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BindUserAuthDataRelationRequest(BaseRequest):
    user_id_type: str | None
    request_body: UserAuthDataRelation | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BindUserAuthDataRelationRequestBuilder: ...

class BindUserAuthDataRelationRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> BindUserAuthDataRelationRequestBuilder: ...
    def request_body(self, request_body: UserAuthDataRelation) -> BindUserAuthDataRelationRequestBuilder: ...
    def build(self) -> BindUserAuthDataRelationRequest: ...
