from lark_oapi.core.construct import init as init

class DepartmentCostCenterRelationship:
    department_cost_center_relationship_uid: str | None
    company_code: str | None
    open_department_id: str | None
    cost_center_code: str | None
    department_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DepartmentCostCenterRelationshipBuilder: ...

class DepartmentCostCenterRelationshipBuilder:
    def __init__(self) -> None: ...
    def department_cost_center_relationship_uid(self, department_cost_center_relationship_uid: str) -> DepartmentCostCenterRelationshipBuilder: ...
    def company_code(self, company_code: str) -> DepartmentCostCenterRelationshipBuilder: ...
    def open_department_id(self, open_department_id: str) -> DepartmentCostCenterRelationshipBuilder: ...
    def cost_center_code(self, cost_center_code: str) -> DepartmentCostCenterRelationshipBuilder: ...
    def department_id(self, department_id: str) -> DepartmentCostCenterRelationshipBuilder: ...
    def build(self) -> DepartmentCostCenterRelationship: ...
