from .i18n_struct import I18nStruct as I18nStruct
from lark_oapi.core.construct import init as init

class GlAccount:
    gl_account_uid: str | None
    gl_account: str | None
    gl_account_name: str | None
    i18n_gl_account_name: list[I18nStruct] | None
    type: str | None
    valid_to: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GlAccountBuilder: ...

class GlAccountBuilder:
    def __init__(self) -> None: ...
    def gl_account_uid(self, gl_account_uid: str) -> GlAccountBuilder: ...
    def gl_account(self, gl_account: str) -> GlAccountBuilder: ...
    def gl_account_name(self, gl_account_name: str) -> GlAccountBuilder: ...
    def i18n_gl_account_name(self, i18n_gl_account_name: list[I18nStruct]) -> GlAccountBuilder: ...
    def type(self, type: str) -> GlAccountBuilder: ...
    def valid_to(self, valid_to: str) -> GlAccountBuilder: ...
    def build(self) -> GlAccount: ...
