from lark_oapi.core.construct import init as init

class GlAccountCompanyRelationship:
    gl_account_code: str | None
    company_code: str | None
    gl_account_company_relationship_uid: str | None
    valid_to: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GlAccountCompanyRelationshipBuilder: ...

class GlAccountCompanyRelationshipBuilder:
    def __init__(self) -> None: ...
    def gl_account_code(self, gl_account_code: str) -> GlAccountCompanyRelationshipBuilder: ...
    def company_code(self, company_code: str) -> GlAccountCompanyRelationshipBuilder: ...
    def gl_account_company_relationship_uid(self, gl_account_company_relationship_uid: str) -> GlAccountCompanyRelationshipBuilder: ...
    def valid_to(self, valid_to: str) -> GlAccountCompanyRelationshipBuilder: ...
    def build(self) -> GlAccountCompanyRelationship: ...
