from .user_auth_data_relation import UserAuthDataRelation as UserAuthDataRelation
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UnbindUserAuthDataRelationRequest(BaseRequest):
    user_id_type: str | None
    request_body: UserAuthDataRelation | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UnbindUserAuthDataRelationRequestBuilder: ...

class UnbindUserAuthDataRelationRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> UnbindUserAuthDataRelationRequestBuilder: ...
    def request_body(self, request_body: UserAuthDataRelation) -> UnbindUserAuthDataRelationRequestBuilder: ...
    def build(self) -> UnbindUserAuthDataRelationRequest: ...
