from lark_oapi.core.construct import init as init

class UserAuthDataRelation:
    root_dimension_type: str | None
    sub_dimension_types: list[str] | None
    authorized_user_ids: list[str] | None
    uams_app_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserAuthDataRelationBuilder: ...

class UserAuthDataRelationBuilder:
    def __init__(self) -> None: ...
    def root_dimension_type(self, root_dimension_type: str) -> UserAuthDataRelationBuilder: ...
    def sub_dimension_types(self, sub_dimension_types: list[str]) -> UserAuthDataRelationBuilder: ...
    def authorized_user_ids(self, authorized_user_ids: list[str]) -> UserAuthDataRelationBuilder: ...
    def uams_app_id(self, uams_app_id: str) -> UserAuthDataRelationBuilder: ...
    def build(self) -> UserAuthDataRelation: ...
