from .extend_field import ExtendField as ExtendField
from lark_oapi.core.construct import init as init

class VendorCompanyView:
    id: int | None
    company_code: str | None
    gl_account: str | None
    vendor_site_code: str | None
    payment_term: str | None
    down_payment_term: str | None
    extend_info: list[ExtendField] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> VendorCompanyViewBuilder: ...

class VendorCompanyViewBuilder:
    def __init__(self) -> None: ...
    def id(self, id: int) -> VendorCompanyViewBuilder: ...
    def company_code(self, company_code: str) -> VendorCompanyViewBuilder: ...
    def gl_account(self, gl_account: str) -> VendorCompanyViewBuilder: ...
    def vendor_site_code(self, vendor_site_code: str) -> VendorCompanyViewBuilder: ...
    def payment_term(self, payment_term: str) -> VendorCompanyViewBuilder: ...
    def down_payment_term(self, down_payment_term: str) -> VendorCompanyViewBuilder: ...
    def extend_info(self, extend_info: list[ExtendField]) -> VendorCompanyViewBuilder: ...
    def build(self) -> VendorCompanyView: ...
