from lark_oapi.core.construct import init as init

class AddSignInstanceResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AddSignInstanceResponseBodyBuilder: ...

class AddSignInstanceResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> AddSignInstanceResponseBody: ...
