from .add_sign_instance_request_body import AddSignInstanceRequestBody as AddSignInstanceRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class AddSignInstanceRequest(BaseRequest):
    request_body: AddSignInstanceRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> AddSignInstanceRequestBuilder: ...

class AddSignInstanceRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: AddSignInstanceRequestBody) -> AddSignInstanceRequestBuilder: ...
    def build(self) -> AddSignInstanceRequest: ...
