from lark_oapi.core.construct import init as init

class ApprovalConfig:
    can_update_viewer: bool | None
    can_update_form: bool | None
    can_update_process: bool | None
    can_update_revert: bool | None
    help_url: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApprovalConfigBuilder: ...

class ApprovalConfigBuilder:
    def __init__(self) -> None: ...
    def can_update_viewer(self, can_update_viewer: bool) -> ApprovalConfigBuilder: ...
    def can_update_form(self, can_update_form: bool) -> ApprovalConfigBuilder: ...
    def can_update_process(self, can_update_process: bool) -> ApprovalConfigBuilder: ...
    def can_update_revert(self, can_update_revert: bool) -> ApprovalConfigBuilder: ...
    def help_url(self, help_url: str) -> ApprovalConfigBuilder: ...
    def build(self) -> ApprovalConfig: ...
