from lark_oapi.core.construct import init as init

class ApprovalCreateViewers:
    viewer_type: str | None
    viewer_user_id: str | None
    viewer_department_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApprovalCreateViewersBuilder: ...

class ApprovalCreateViewersBuilder:
    def __init__(self) -> None: ...
    def viewer_type(self, viewer_type: str) -> ApprovalCreateViewersBuilder: ...
    def viewer_user_id(self, viewer_user_id: str) -> ApprovalCreateViewersBuilder: ...
    def viewer_department_id(self, viewer_department_id: str) -> ApprovalCreateViewersBuilder: ...
    def build(self) -> ApprovalCreateViewers: ...
