from lark_oapi.core.construct import init as init

class ApprovalSetting:
    revert_interval: int | None
    revert_option: int | None
    reject_option: int | None
    quick_approval_option: int | None
    overtime_disable: bool | None
    overtime_notice_time: int | None
    overtime_close_time: int | None
    overtime_recover_time: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApprovalSettingBuilder: ...

class ApprovalSettingBuilder:
    def __init__(self) -> None: ...
    def revert_interval(self, revert_interval: int) -> ApprovalSettingBuilder: ...
    def revert_option(self, revert_option: int) -> ApprovalSettingBuilder: ...
    def reject_option(self, reject_option: int) -> ApprovalSettingBuilder: ...
    def quick_approval_option(self, quick_approval_option: int) -> ApprovalSettingBuilder: ...
    def overtime_disable(self, overtime_disable: bool) -> ApprovalSettingBuilder: ...
    def overtime_notice_time(self, overtime_notice_time: int) -> ApprovalSettingBuilder: ...
    def overtime_close_time(self, overtime_close_time: int) -> ApprovalSettingBuilder: ...
    def overtime_recover_time(self, overtime_recover_time: int) -> ApprovalSettingBuilder: ...
    def build(self) -> ApprovalSetting: ...
