from lark_oapi.core.construct import init as init

class ApprovalCreateExternal:
    biz_name: str | None
    biz_type: str | None
    create_link_mobile: str | None
    create_link_pc: str | None
    support_pc: bool | None
    support_mobile: bool | None
    support_batch_read: bool | None
    enable_mark_readed: bool | None
    enable_quick_operate: bool | None
    action_callback_url: str | None
    action_callback_token: str | None
    action_callback_key: str | None
    allow_batch_operate: bool | None
    exclude_efficiency_statistics: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApprovalCreateExternalBuilder: ...

class ApprovalCreateExternalBuilder:
    def __init__(self) -> None: ...
    def biz_name(self, biz_name: str) -> ApprovalCreateExternalBuilder: ...
    def biz_type(self, biz_type: str) -> ApprovalCreateExternalBuilder: ...
    def create_link_mobile(self, create_link_mobile: str) -> ApprovalCreateExternalBuilder: ...
    def create_link_pc(self, create_link_pc: str) -> ApprovalCreateExternalBuilder: ...
    def support_pc(self, support_pc: bool) -> ApprovalCreateExternalBuilder: ...
    def support_mobile(self, support_mobile: bool) -> ApprovalCreateExternalBuilder: ...
    def support_batch_read(self, support_batch_read: bool) -> ApprovalCreateExternalBuilder: ...
    def enable_mark_readed(self, enable_mark_readed: bool) -> ApprovalCreateExternalBuilder: ...
    def enable_quick_operate(self, enable_quick_operate: bool) -> ApprovalCreateExternalBuilder: ...
    def action_callback_url(self, action_callback_url: str) -> ApprovalCreateExternalBuilder: ...
    def action_callback_token(self, action_callback_token: str) -> ApprovalCreateExternalBuilder: ...
    def action_callback_key(self, action_callback_key: str) -> ApprovalCreateExternalBuilder: ...
    def allow_batch_operate(self, allow_batch_operate: bool) -> ApprovalCreateExternalBuilder: ...
    def exclude_efficiency_statistics(self, exclude_efficiency_statistics: bool) -> ApprovalCreateExternalBuilder: ...
    def build(self) -> ApprovalCreateExternal: ...
