from lark_oapi.core.construct import init as init

class ApproveTaskResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApproveTaskResponseBodyBuilder: ...

class ApproveTaskResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ApproveTaskResponseBody: ...
