from lark_oapi.core.construct import init as init

class ApprovalViewer:
    type: str | None
    open_id: str | None
    user_id: str | None
    union_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApprovalViewerBuilder: ...

class ApprovalViewerBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> ApprovalViewerBuilder: ...
    def open_id(self, open_id: str) -> ApprovalViewerBuilder: ...
    def user_id(self, user_id: str) -> ApprovalViewerBuilder: ...
    def union_id(self, union_id: str) -> ApprovalViewerBuilder: ...
    def build(self) -> ApprovalViewer: ...
