from .cc_search_node import CcSearchNode as CcSearchNode
from .instance_search_approval import InstanceSearchApproval as InstanceSearchApproval
from .instance_search_group import InstanceSearchGroup as InstanceSearchGroup
from .instance_search_node import InstanceSearchNode as InstanceSearchNode
from lark_oapi.core.construct import init as init

class CcSearchItem:
    approval: InstanceSearchApproval | None
    group: InstanceSearchGroup | None
    instance: InstanceSearchNode | None
    cc: CcSearchNode | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CcSearchItemBuilder: ...

class CcSearchItemBuilder:
    def __init__(self) -> None: ...
    def approval(self, approval: InstanceSearchApproval) -> CcSearchItemBuilder: ...
    def group(self, group: InstanceSearchGroup) -> CcSearchItemBuilder: ...
    def instance(self, instance: InstanceSearchNode) -> CcSearchItemBuilder: ...
    def cc(self, cc: CcSearchNode) -> CcSearchItemBuilder: ...
    def build(self) -> CcSearchItem: ...
