from lark_oapi.core.construct import init as init

class CcSearch:
    user_id: str | None
    approval_code: str | None
    instance_code: str | None
    instance_external_id: str | None
    group_external_id: str | None
    cc_title: str | None
    read_status: str | None
    cc_create_time_from: int | None
    cc_create_time_to: int | None
    locale: str | None
    with_revoked_instance: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CcSearchBuilder: ...

class CcSearchBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: str) -> CcSearchBuilder: ...
    def approval_code(self, approval_code: str) -> CcSearchBuilder: ...
    def instance_code(self, instance_code: str) -> CcSearchBuilder: ...
    def instance_external_id(self, instance_external_id: str) -> CcSearchBuilder: ...
    def group_external_id(self, group_external_id: str) -> CcSearchBuilder: ...
    def cc_title(self, cc_title: str) -> CcSearchBuilder: ...
    def read_status(self, read_status: str) -> CcSearchBuilder: ...
    def cc_create_time_from(self, cc_create_time_from: int) -> CcSearchBuilder: ...
    def cc_create_time_to(self, cc_create_time_to: int) -> CcSearchBuilder: ...
    def locale(self, locale: str) -> CcSearchBuilder: ...
    def with_revoked_instance(self, with_revoked_instance: bool) -> CcSearchBuilder: ...
    def build(self) -> CcSearch: ...
