from .exteranl_instance_check import ExteranlInstanceCheck as ExteranlInstanceCheck
from lark_oapi.core.construct import init as init

class CheckExternalInstanceRequestBody:
    instances: list[ExteranlInstanceCheck] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CheckExternalInstanceRequestBodyBuilder: ...

class CheckExternalInstanceRequestBodyBuilder:
    def __init__(self) -> None: ...
    def instances(self, instances: list[ExteranlInstanceCheck]) -> CheckExternalInstanceRequestBodyBuilder: ...
    def build(self) -> CheckExternalInstanceRequestBody: ...
