from .exteranl_instance_check_response import ExteranlInstanceCheckResponse as ExteranlInstanceCheckResponse
from lark_oapi.core.construct import init as init

class CheckExternalInstanceResponseBody:
    diff_instances: list[ExteranlInstanceCheckResponse] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CheckExternalInstanceResponseBodyBuilder: ...

class CheckExternalInstanceResponseBodyBuilder:
    def __init__(self) -> None: ...
    def diff_instances(self, diff_instances: list[ExteranlInstanceCheckResponse]) -> CheckExternalInstanceResponseBodyBuilder: ...
    def build(self) -> CheckExternalInstanceResponseBody: ...
