from .connector_log_data import ConnectorLogData as ConnectorLogData
from lark_oapi.core.construct import init as init

class ConnectorLog:
    log_data: list[ConnectorLogData] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ConnectorLogBuilder: ...

class ConnectorLogBuilder:
    def __init__(self) -> None: ...
    def log_data(self, log_data: list[ConnectorLogData]) -> ConnectorLogBuilder: ...
    def build(self) -> ConnectorLog: ...
