from lark_oapi.core.construct import init as init

class Count:
    total: int | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CountBuilder: ...

class CountBuilder:
    def __init__(self) -> None: ...
    def total(self, total: int) -> CountBuilder: ...
    def has_more(self, has_more: bool) -> CountBuilder: ...
    def build(self) -> Count: ...
