from .external_instance import ExternalInstance as ExternalInstance
from lark_oapi.core.construct import init as init

class CreateExternalInstanceResponseBody:
    data: ExternalInstance | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateExternalInstanceResponseBodyBuilder: ...

class CreateExternalInstanceResponseBodyBuilder:
    def __init__(self) -> None: ...
    def data(self, data: ExternalInstance) -> CreateExternalInstanceResponseBodyBuilder: ...
    def build(self) -> CreateExternalInstanceResponseBody: ...
