from lark_oapi.core.construct import init as init

class CreateInstanceCommentResponseBody:
    comment_id: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateInstanceCommentResponseBodyBuilder: ...

class CreateInstanceCommentResponseBodyBuilder:
    def __init__(self) -> None: ...
    def comment_id(self, comment_id: int) -> CreateInstanceCommentResponseBodyBuilder: ...
    def build(self) -> CreateInstanceCommentResponseBody: ...
