from lark_oapi.core.construct import init as init

class CreateExternalApprovalResponseBody:
    approval_code: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateExternalApprovalResponseBodyBuilder: ...

class CreateExternalApprovalResponseBodyBuilder:
    def __init__(self) -> None: ...
    def approval_code(self, approval_code: str) -> CreateExternalApprovalResponseBodyBuilder: ...
    def build(self) -> CreateExternalApprovalResponseBody: ...
