from lark_oapi.core.construct import init as init

class Definition:
    approval_code: str | None
    approval_name: str | None
    group_name: str | None
    description: str | None
    icon_url: str | None
    group_code: str | None
    is_external: bool | None
    create_link_pc: str | None
    create_link_mobile: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DefinitionBuilder: ...

class DefinitionBuilder:
    def __init__(self) -> None: ...
    def approval_code(self, approval_code: str) -> DefinitionBuilder: ...
    def approval_name(self, approval_name: str) -> DefinitionBuilder: ...
    def group_name(self, group_name: str) -> DefinitionBuilder: ...
    def description(self, description: str) -> DefinitionBuilder: ...
    def icon_url(self, icon_url: str) -> DefinitionBuilder: ...
    def group_code(self, group_code: str) -> DefinitionBuilder: ...
    def is_external(self, is_external: bool) -> DefinitionBuilder: ...
    def create_link_pc(self, create_link_pc: str) -> DefinitionBuilder: ...
    def create_link_mobile(self, create_link_mobile: str) -> DefinitionBuilder: ...
    def build(self) -> Definition: ...
