from lark_oapi.core.construct import init as init

class DeleteInstanceCommentResponseBody:
    comment_id: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteInstanceCommentResponseBodyBuilder: ...

class DeleteInstanceCommentResponseBodyBuilder:
    def __init__(self) -> None: ...
    def comment_id(self, comment_id: int) -> DeleteInstanceCommentResponseBodyBuilder: ...
    def build(self) -> DeleteInstanceCommentResponseBody: ...
