from lark_oapi.core.construct import init as init

class ExternalInstanceTask:
    task_id: str | None
    update_time: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ExternalInstanceTaskBuilder: ...

class ExternalInstanceTaskBuilder:
    def __init__(self) -> None: ...
    def task_id(self, task_id: str) -> ExternalInstanceTaskBuilder: ...
    def update_time(self, update_time: int) -> ExternalInstanceTaskBuilder: ...
    def build(self) -> ExternalInstanceTask: ...
