from lark_oapi.core.construct import init as init

class ExternalTaskItem:
    id: str | None
    status: str | None
    update_time: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ExternalTaskItemBuilder: ...

class ExternalTaskItemBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> ExternalTaskItemBuilder: ...
    def status(self, status: str) -> ExternalTaskItemBuilder: ...
    def update_time(self, update_time: int) -> ExternalTaskItemBuilder: ...
    def build(self) -> ExternalTaskItem: ...
