from .external_instance_task import ExternalInstanceTask as ExternalInstanceTask
from lark_oapi.core.construct import init as init

class ExteranlInstanceCheckResponse:
    instance_id: str | None
    update_time: int | None
    tasks: list[ExternalInstanceTask] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ExteranlInstanceCheckResponseBuilder: ...

class ExteranlInstanceCheckResponseBuilder:
    def __init__(self) -> None: ...
    def instance_id(self, instance_id: str) -> ExteranlInstanceCheckResponseBuilder: ...
    def update_time(self, update_time: int) -> ExteranlInstanceCheckResponseBuilder: ...
    def tasks(self, tasks: list[ExternalInstanceTask]) -> ExteranlInstanceCheckResponseBuilder: ...
    def build(self) -> ExteranlInstanceCheckResponse: ...
