from lark_oapi.core.construct import init as init

class FieldGroup:
    writable: list[str] | None
    readable: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FieldGroupBuilder: ...

class FieldGroupBuilder:
    def __init__(self) -> None: ...
    def writable(self, writable: list[str]) -> FieldGroupBuilder: ...
    def readable(self, readable: list[str]) -> FieldGroupBuilder: ...
    def build(self) -> FieldGroup: ...
