from lark_oapi.core.construct import init as init

class FileUrl:
    name: str | None
    url: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FileUrlBuilder: ...

class FileUrlBuilder:
    def __init__(self) -> None: ...
    def name(self, name: str) -> FileUrlBuilder: ...
    def url(self, url: str) -> FileUrlBuilder: ...
    def build(self) -> FileUrl: ...
