from lark_oapi.core.construct import init as init

class GetApprovalRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetApprovalRequestBodyBuilder: ...

class GetApprovalRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetApprovalRequestBody: ...
