from .instance_comment import InstanceComment as InstanceComment
from .instance_task import InstanceTask as InstanceTask
from .instance_timeline import InstanceTimeline as InstanceTimeline
from lark_oapi.core.construct import init as init

class GetInstanceResponseBody:
    approval_name: str | None
    start_time: int | None
    end_time: int | None
    user_id: str | None
    open_id: str | None
    serial_number: str | None
    department_id: str | None
    status: str | None
    uuid: str | None
    form: str | None
    task_list: list[InstanceTask] | None
    comment_list: list[InstanceComment] | None
    timeline: list[InstanceTimeline] | None
    modified_instance_code: str | None
    reverted_instance_code: str | None
    approval_code: str | None
    reverted: bool | None
    instance_code: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetInstanceResponseBodyBuilder: ...

class GetInstanceResponseBodyBuilder:
    def __init__(self) -> None: ...
    def approval_name(self, approval_name: str) -> GetInstanceResponseBodyBuilder: ...
    def start_time(self, start_time: int) -> GetInstanceResponseBodyBuilder: ...
    def end_time(self, end_time: int) -> GetInstanceResponseBodyBuilder: ...
    def user_id(self, user_id: str) -> GetInstanceResponseBodyBuilder: ...
    def open_id(self, open_id: str) -> GetInstanceResponseBodyBuilder: ...
    def serial_number(self, serial_number: str) -> GetInstanceResponseBodyBuilder: ...
    def department_id(self, department_id: str) -> GetInstanceResponseBodyBuilder: ...
    def status(self, status: str) -> GetInstanceResponseBodyBuilder: ...
    def uuid(self, uuid: str) -> GetInstanceResponseBodyBuilder: ...
    def form(self, form: str) -> GetInstanceResponseBodyBuilder: ...
    def task_list(self, task_list: list[InstanceTask]) -> GetInstanceResponseBodyBuilder: ...
    def comment_list(self, comment_list: list[InstanceComment]) -> GetInstanceResponseBodyBuilder: ...
    def timeline(self, timeline: list[InstanceTimeline]) -> GetInstanceResponseBodyBuilder: ...
    def modified_instance_code(self, modified_instance_code: str) -> GetInstanceResponseBodyBuilder: ...
    def reverted_instance_code(self, reverted_instance_code: str) -> GetInstanceResponseBodyBuilder: ...
    def approval_code(self, approval_code: str) -> GetInstanceResponseBodyBuilder: ...
    def reverted(self, reverted: bool) -> GetInstanceResponseBodyBuilder: ...
    def instance_code(self, instance_code: str) -> GetInstanceResponseBodyBuilder: ...
    def build(self) -> GetInstanceResponseBody: ...
