from .i18n_resource import I18nResource as I18nResource
from .node_approver import NodeApprover as NodeApprover
from .node_auto_approval import NodeAutoApproval as NodeAutoApproval
from .node_cc import NodeCc as NodeCc
from lark_oapi.core.construct import init as init

class InstanceCreate:
    approval_code: str | None
    user_id: str | None
    open_id: str | None
    department_id: str | None
    form: str | None
    node_approver_user_id_list: list[NodeApprover] | None
    node_approver_open_id_list: list[NodeApprover] | None
    node_cc_user_id_list: list[NodeCc] | None
    node_cc_open_id_list: list[NodeCc] | None
    uuid: str | None
    allow_resubmit: bool | None
    allow_submit_again: bool | None
    cancel_bot_notification: int | None
    forbid_revoke: bool | None
    i18n_resources: list[I18nResource] | None
    title: str | None
    title_display_method: int | None
    node_auto_approval_list: list[NodeAutoApproval] | None
    byte_extra: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InstanceCreateBuilder: ...

class InstanceCreateBuilder:
    def __init__(self) -> None: ...
    def approval_code(self, approval_code: str) -> InstanceCreateBuilder: ...
    def user_id(self, user_id: str) -> InstanceCreateBuilder: ...
    def open_id(self, open_id: str) -> InstanceCreateBuilder: ...
    def department_id(self, department_id: str) -> InstanceCreateBuilder: ...
    def form(self, form: str) -> InstanceCreateBuilder: ...
    def node_approver_user_id_list(self, node_approver_user_id_list: list[NodeApprover]) -> InstanceCreateBuilder: ...
    def node_approver_open_id_list(self, node_approver_open_id_list: list[NodeApprover]) -> InstanceCreateBuilder: ...
    def node_cc_user_id_list(self, node_cc_user_id_list: list[NodeCc]) -> InstanceCreateBuilder: ...
    def node_cc_open_id_list(self, node_cc_open_id_list: list[NodeCc]) -> InstanceCreateBuilder: ...
    def uuid(self, uuid: str) -> InstanceCreateBuilder: ...
    def allow_resubmit(self, allow_resubmit: bool) -> InstanceCreateBuilder: ...
    def allow_submit_again(self, allow_submit_again: bool) -> InstanceCreateBuilder: ...
    def cancel_bot_notification(self, cancel_bot_notification: int) -> InstanceCreateBuilder: ...
    def forbid_revoke(self, forbid_revoke: bool) -> InstanceCreateBuilder: ...
    def i18n_resources(self, i18n_resources: list[I18nResource]) -> InstanceCreateBuilder: ...
    def title(self, title: str) -> InstanceCreateBuilder: ...
    def title_display_method(self, title_display_method: int) -> InstanceCreateBuilder: ...
    def node_auto_approval_list(self, node_auto_approval_list: list[NodeAutoApproval]) -> InstanceCreateBuilder: ...
    def byte_extra(self, byte_extra: str) -> InstanceCreateBuilder: ...
    def build(self) -> InstanceCreate: ...
