from lark_oapi.core.construct import init as init

class InstanceSearchApprovalExternal:
    batch_cc_read: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InstanceSearchApprovalExternalBuilder: ...

class InstanceSearchApprovalExternalBuilder:
    def __init__(self) -> None: ...
    def batch_cc_read(self, batch_cc_read: bool) -> InstanceSearchApprovalExternalBuilder: ...
    def build(self) -> InstanceSearchApprovalExternal: ...
