from .instance_search_approval_external import InstanceSearchApprovalExternal as InstanceSearchApprovalExternal
from lark_oapi.core.construct import init as init

class InstanceSearchApproval:
    code: str | None
    name: str | None
    is_external: bool | None
    external: InstanceSearchApprovalExternal | None
    approval_id: int | None
    icon: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InstanceSearchApprovalBuilder: ...

class InstanceSearchApprovalBuilder:
    def __init__(self) -> None: ...
    def code(self, code: str) -> InstanceSearchApprovalBuilder: ...
    def name(self, name: str) -> InstanceSearchApprovalBuilder: ...
    def is_external(self, is_external: bool) -> InstanceSearchApprovalBuilder: ...
    def external(self, external: InstanceSearchApprovalExternal) -> InstanceSearchApprovalBuilder: ...
    def approval_id(self, approval_id: int) -> InstanceSearchApprovalBuilder: ...
    def icon(self, icon: str) -> InstanceSearchApprovalBuilder: ...
    def build(self) -> InstanceSearchApproval: ...
