from lark_oapi.core.construct import init as init

class InstanceSearchGroup:
    external_id: str | None
    name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InstanceSearchGroupBuilder: ...

class InstanceSearchGroupBuilder:
    def __init__(self) -> None: ...
    def external_id(self, external_id: str) -> InstanceSearchGroupBuilder: ...
    def name(self, name: str) -> InstanceSearchGroupBuilder: ...
    def build(self) -> InstanceSearchGroup: ...
