from lark_oapi.core.construct import init as init

class InstanceCc:
    approval_code: str | None
    instance_code: str | None
    user_id: str | None
    cc_user_ids: list[str] | None
    comment: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InstanceCcBuilder: ...

class InstanceCcBuilder:
    def __init__(self) -> None: ...
    def approval_code(self, approval_code: str) -> InstanceCcBuilder: ...
    def instance_code(self, instance_code: str) -> InstanceCcBuilder: ...
    def user_id(self, user_id: str) -> InstanceCcBuilder: ...
    def cc_user_ids(self, cc_user_ids: list[str]) -> InstanceCcBuilder: ...
    def comment(self, comment: str) -> InstanceCcBuilder: ...
    def build(self) -> InstanceCc: ...
