from lark_oapi.core.construct import init as init

class InstanceCcUser:
    user_id: str | None
    cc_id: str | None
    open_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InstanceCcUserBuilder: ...

class InstanceCcUserBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: str) -> InstanceCcUserBuilder: ...
    def cc_id(self, cc_id: str) -> InstanceCcUserBuilder: ...
    def open_id(self, open_id: str) -> InstanceCcUserBuilder: ...
    def build(self) -> InstanceCcUser: ...
