from .my_ai_instance_detail_extra import MyAiInstanceDetailExtra as MyAiInstanceDetailExtra
from .object_context import ObjectContext as ObjectContext
from lark_oapi.core.construct import init as init

class InstanceDetailScenarioContext:
    object: ObjectContext | None
    extra: MyAiInstanceDetailExtra | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InstanceDetailScenarioContextBuilder: ...

class InstanceDetailScenarioContextBuilder:
    def __init__(self) -> None: ...
    def object(self, object: ObjectContext) -> InstanceDetailScenarioContextBuilder: ...
    def extra(self, extra: MyAiInstanceDetailExtra) -> InstanceDetailScenarioContextBuilder: ...
    def build(self) -> InstanceDetailScenarioContext: ...
