from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListInstanceCommentRequest(BaseRequest):
    user_id_type: str | None
    user_id: int | None
    page_token: str | None
    page_size: int | None
    instance_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListInstanceCommentRequestBuilder: ...

class ListInstanceCommentRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> ListInstanceCommentRequestBuilder: ...
    def user_id(self, user_id: int) -> ListInstanceCommentRequestBuilder: ...
    def page_token(self, page_token: str) -> ListInstanceCommentRequestBuilder: ...
    def page_size(self, page_size: int) -> ListInstanceCommentRequestBuilder: ...
    def instance_id(self, instance_id: str) -> ListInstanceCommentRequestBuilder: ...
    def build(self) -> ListInstanceCommentRequest: ...
