from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListInstanceRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    approval_code: str | None
    start_time: int | None
    end_time: int | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListInstanceRequestBuilder: ...

class ListInstanceRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> ListInstanceRequestBuilder: ...
    def page_token(self, page_token: str) -> ListInstanceRequestBuilder: ...
    def approval_code(self, approval_code: str) -> ListInstanceRequestBuilder: ...
    def start_time(self, start_time: int) -> ListInstanceRequestBuilder: ...
    def end_time(self, end_time: int) -> ListInstanceRequestBuilder: ...
    def build(self) -> ListInstanceRequest: ...
