from lark_oapi.core.construct import init as init

class ManageableDefinition:
    approval_code: str | None
    approval_name: str | None
    approval_status: str | None
    approval_admin_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ManageableDefinitionBuilder: ...

class ManageableDefinitionBuilder:
    def __init__(self) -> None: ...
    def approval_code(self, approval_code: str) -> ManageableDefinitionBuilder: ...
    def approval_name(self, approval_name: str) -> ManageableDefinitionBuilder: ...
    def approval_status(self, approval_status: str) -> ManageableDefinitionBuilder: ...
    def approval_admin_ids(self, approval_admin_ids: list[str]) -> ManageableDefinitionBuilder: ...
    def build(self) -> ManageableDefinition: ...
