from lark_oapi.core.construct import init as init

class MyAiTask:
    user_name: str | None
    type: str | None
    node_name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MyAiTaskBuilder: ...

class MyAiTaskBuilder:
    def __init__(self) -> None: ...
    def user_name(self, user_name: str) -> MyAiTaskBuilder: ...
    def type(self, type: str) -> MyAiTaskBuilder: ...
    def node_name(self, node_name: str) -> MyAiTaskBuilder: ...
    def build(self) -> MyAiTask: ...
