from .my_ai_card_value import MyAiCardValue as MyAiCardValue
from lark_oapi.core.construct import init as init

class MyAiCardAction:
    tag: str | None
    value: MyAiCardValue | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MyAiCardActionBuilder: ...

class MyAiCardActionBuilder:
    def __init__(self) -> None: ...
    def tag(self, tag: str) -> MyAiCardActionBuilder: ...
    def value(self, value: MyAiCardValue) -> MyAiCardActionBuilder: ...
    def build(self) -> MyAiCardAction: ...
