from lark_oapi.core.construct import init as init

class MyAiPresentCardVariables:
    prologue: str | None
    quick_actions: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MyAiPresentCardVariablesBuilder: ...

class MyAiPresentCardVariablesBuilder:
    def __init__(self) -> None: ...
    def prologue(self, prologue: str) -> MyAiPresentCardVariablesBuilder: ...
    def quick_actions(self, quick_actions: str) -> MyAiPresentCardVariablesBuilder: ...
    def build(self) -> MyAiPresentCardVariables: ...
