from lark_oapi.core.construct import init as init

class MyAiComment:
    user_name: str | None
    comment: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MyAiCommentBuilder: ...

class MyAiCommentBuilder:
    def __init__(self) -> None: ...
    def user_name(self, user_name: str) -> MyAiCommentBuilder: ...
    def comment(self, comment: str) -> MyAiCommentBuilder: ...
    def build(self) -> MyAiComment: ...
