from lark_oapi.core.construct import init as init

class MyAiMessageCallbackRequest:
    message_id: str | None
    callback_info: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MyAiMessageCallbackRequestBuilder: ...

class MyAiMessageCallbackRequestBuilder:
    def __init__(self) -> None: ...
    def message_id(self, message_id: str) -> MyAiMessageCallbackRequestBuilder: ...
    def callback_info(self, callback_info: str) -> MyAiMessageCallbackRequestBuilder: ...
    def build(self) -> MyAiMessageCallbackRequest: ...
