from lark_oapi.core.construct import init as init

class PreviewNode:
    node_id: str | None
    node_name: str | None
    node_type: str | None
    comments: list[str] | None
    custom_node_id: str | None
    user_id_list: list[str] | None
    end_cc_id_list: list[str] | None
    is_empty_logic: bool | None
    is_approver_type_free: bool | None
    has_cc_type_free: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PreviewNodeBuilder: ...

class PreviewNodeBuilder:
    def __init__(self) -> None: ...
    def node_id(self, node_id: str) -> PreviewNodeBuilder: ...
    def node_name(self, node_name: str) -> PreviewNodeBuilder: ...
    def node_type(self, node_type: str) -> PreviewNodeBuilder: ...
    def comments(self, comments: list[str]) -> PreviewNodeBuilder: ...
    def custom_node_id(self, custom_node_id: str) -> PreviewNodeBuilder: ...
    def user_id_list(self, user_id_list: list[str]) -> PreviewNodeBuilder: ...
    def end_cc_id_list(self, end_cc_id_list: list[str]) -> PreviewNodeBuilder: ...
    def is_empty_logic(self, is_empty_logic: bool) -> PreviewNodeBuilder: ...
    def is_approver_type_free(self, is_approver_type_free: bool) -> PreviewNodeBuilder: ...
    def has_cc_type_free(self, has_cc_type_free: bool) -> PreviewNodeBuilder: ...
    def build(self) -> PreviewNode: ...
