from .count import Count as Count
from .task import Task as Task
from lark_oapi.core.construct import init as init

class QueryTaskResponseBody:
    tasks: list[Task] | None
    page_token: str | None
    has_more: bool | None
    count: Count | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryTaskResponseBodyBuilder: ...

class QueryTaskResponseBodyBuilder:
    def __init__(self) -> None: ...
    def tasks(self, tasks: list[Task]) -> QueryTaskResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> QueryTaskResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> QueryTaskResponseBodyBuilder: ...
    def count(self, count: Count) -> QueryTaskResponseBodyBuilder: ...
    def build(self) -> QueryTaskResponseBody: ...
