from .instance_search_item import InstanceSearchItem as InstanceSearchItem
from lark_oapi.core.construct import init as init

class QueryInstanceResponseBody:
    count: int | None
    instance_list: list[InstanceSearchItem] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryInstanceResponseBodyBuilder: ...

class QueryInstanceResponseBodyBuilder:
    def __init__(self) -> None: ...
    def count(self, count: int) -> QueryInstanceResponseBodyBuilder: ...
    def instance_list(self, instance_list: list[InstanceSearchItem]) -> QueryInstanceResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> QueryInstanceResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> QueryInstanceResponseBodyBuilder: ...
    def build(self) -> QueryInstanceResponseBody: ...
