from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class QueryTaskRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    user_id: str | None
    topic: int | None
    user_id_type: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> QueryTaskRequestBuilder: ...

class QueryTaskRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> QueryTaskRequestBuilder: ...
    def page_token(self, page_token: str) -> QueryTaskRequestBuilder: ...
    def user_id(self, user_id: str) -> QueryTaskRequestBuilder: ...
    def topic(self, topic: int) -> QueryTaskRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> QueryTaskRequestBuilder: ...
    def build(self) -> QueryTaskRequest: ...
