from lark_oapi.core.construct import init as init

class RejectTaskResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RejectTaskResponseBodyBuilder: ...

class RejectTaskResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> RejectTaskResponseBody: ...
