from lark_oapi.core.construct import init as init

class RemoveInstanceCommentRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RemoveInstanceCommentRequestBodyBuilder: ...

class RemoveInstanceCommentRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> RemoveInstanceCommentRequestBody: ...
