from lark_oapi.core.construct import init as init

class ResubmitTaskResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ResubmitTaskResponseBodyBuilder: ...

class ResubmitTaskResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ResubmitTaskResponseBody: ...
