from .task_search_item import TaskSearchItem as TaskSearchItem
from lark_oapi.core.construct import init as init

class SearchTaskResponseBody:
    count: int | None
    task_list: list[TaskSearchItem] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SearchTaskResponseBodyBuilder: ...

class SearchTaskResponseBodyBuilder:
    def __init__(self) -> None: ...
    def count(self, count: int) -> SearchTaskResponseBodyBuilder: ...
    def task_list(self, task_list: list[TaskSearchItem]) -> SearchTaskResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> SearchTaskResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> SearchTaskResponseBodyBuilder: ...
    def build(self) -> SearchTaskResponseBody: ...
