from .swap_shift_detail import SwapShiftDetail as SwapShiftDetail
from lark_oapi.core.construct import init as init

class ShiftGroup:
    type: str | None
    instance_code: str | None
    user_id: str | None
    swap_shift_user_id: str | None
    start_time: int | None
    end_time: int | None
    shift_reason: str | None
    swap_shift_details: list[SwapShiftDetail] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ShiftGroupBuilder: ...

class ShiftGroupBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> ShiftGroupBuilder: ...
    def instance_code(self, instance_code: str) -> ShiftGroupBuilder: ...
    def user_id(self, user_id: str) -> ShiftGroupBuilder: ...
    def swap_shift_user_id(self, swap_shift_user_id: str) -> ShiftGroupBuilder: ...
    def start_time(self, start_time: int) -> ShiftGroupBuilder: ...
    def end_time(self, end_time: int) -> ShiftGroupBuilder: ...
    def shift_reason(self, shift_reason: str) -> ShiftGroupBuilder: ...
    def swap_shift_details(self, swap_shift_details: list[SwapShiftDetail]) -> ShiftGroupBuilder: ...
    def build(self) -> ShiftGroup: ...
