from lark_oapi.core.construct import init as init

class SpecifiedRollbackInstanceResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SpecifiedRollbackInstanceResponseBodyBuilder: ...

class SpecifiedRollbackInstanceResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> SpecifiedRollbackInstanceResponseBody: ...
