from lark_oapi.core.construct import init as init

class SpecifiedRollback:
    user_id: str | None
    task_id: int | None
    reason: str | None
    extra: str | None
    task_def_key_list: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SpecifiedRollbackBuilder: ...

class SpecifiedRollbackBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: str) -> SpecifiedRollbackBuilder: ...
    def task_id(self, task_id: int) -> SpecifiedRollbackBuilder: ...
    def reason(self, reason: str) -> SpecifiedRollbackBuilder: ...
    def extra(self, extra: str) -> SpecifiedRollbackBuilder: ...
    def task_def_key_list(self, task_def_key_list: list[str]) -> SpecifiedRollbackBuilder: ...
    def build(self) -> SpecifiedRollback: ...
