from lark_oapi.core.construct import init as init

class SubscribeApprovalRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SubscribeApprovalRequestBodyBuilder: ...

class SubscribeApprovalRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> SubscribeApprovalRequestBody: ...
