from lark_oapi.core.construct import init as init

class SwapShiftDetail:
    date: str | None
    return_date: str | None
    shfit_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SwapShiftDetailBuilder: ...

class SwapShiftDetailBuilder:
    def __init__(self) -> None: ...
    def date(self, date: str) -> SwapShiftDetailBuilder: ...
    def return_date(self, return_date: str) -> SwapShiftDetailBuilder: ...
    def shfit_id(self, shfit_id: str) -> SwapShiftDetailBuilder: ...
    def build(self) -> SwapShiftDetail: ...
