from lark_oapi.core.construct import init as init

class TaskApprove:
    approval_code: str | None
    instance_code: str | None
    user_id: str | None
    comment: str | None
    task_id: str | None
    form: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TaskApproveBuilder: ...

class TaskApproveBuilder:
    def __init__(self) -> None: ...
    def approval_code(self, approval_code: str) -> TaskApproveBuilder: ...
    def instance_code(self, instance_code: str) -> TaskApproveBuilder: ...
    def user_id(self, user_id: str) -> TaskApproveBuilder: ...
    def comment(self, comment: str) -> TaskApproveBuilder: ...
    def task_id(self, task_id: str) -> TaskApproveBuilder: ...
    def form(self, form: str) -> TaskApproveBuilder: ...
    def build(self) -> TaskApprove: ...
