from lark_oapi.core.construct import init as init

class TaskUrls:
    helpdesk: str | None
    mobile: str | None
    pc: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TaskUrlsBuilder: ...

class TaskUrlsBuilder:
    def __init__(self) -> None: ...
    def helpdesk(self, helpdesk: str) -> TaskUrlsBuilder: ...
    def mobile(self, mobile: str) -> TaskUrlsBuilder: ...
    def pc(self, pc: str) -> TaskUrlsBuilder: ...
    def build(self) -> TaskUrls: ...
