from lark_oapi.core.construct import init as init

class TaskSearch:
    user_id: str | None
    approval_code: str | None
    instance_code: str | None
    instance_external_id: str | None
    group_external_id: str | None
    task_title: str | None
    task_status: str | None
    task_start_time_from: int | None
    task_start_time_to: int | None
    locale: str | None
    task_status_list: list[str] | None
    order: int | None
    with_revoked_instance: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TaskSearchBuilder: ...

class TaskSearchBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: str) -> TaskSearchBuilder: ...
    def approval_code(self, approval_code: str) -> TaskSearchBuilder: ...
    def instance_code(self, instance_code: str) -> TaskSearchBuilder: ...
    def instance_external_id(self, instance_external_id: str) -> TaskSearchBuilder: ...
    def group_external_id(self, group_external_id: str) -> TaskSearchBuilder: ...
    def task_title(self, task_title: str) -> TaskSearchBuilder: ...
    def task_status(self, task_status: str) -> TaskSearchBuilder: ...
    def task_start_time_from(self, task_start_time_from: int) -> TaskSearchBuilder: ...
    def task_start_time_to(self, task_start_time_to: int) -> TaskSearchBuilder: ...
    def locale(self, locale: str) -> TaskSearchBuilder: ...
    def task_status_list(self, task_status_list: list[str]) -> TaskSearchBuilder: ...
    def order(self, order: int) -> TaskSearchBuilder: ...
    def with_revoked_instance(self, with_revoked_instance: bool) -> TaskSearchBuilder: ...
    def build(self) -> TaskSearch: ...
