from lark_oapi.core.construct import init as init

class TaskResubmit:
    approval_code: str | None
    instance_code: str | None
    user_id: str | None
    comment: str | None
    task_id: str | None
    form: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TaskResubmitBuilder: ...

class TaskResubmitBuilder:
    def __init__(self) -> None: ...
    def approval_code(self, approval_code: str) -> TaskResubmitBuilder: ...
    def instance_code(self, instance_code: str) -> TaskResubmitBuilder: ...
    def user_id(self, user_id: str) -> TaskResubmitBuilder: ...
    def comment(self, comment: str) -> TaskResubmitBuilder: ...
    def task_id(self, task_id: str) -> TaskResubmitBuilder: ...
    def form(self, form: str) -> TaskResubmitBuilder: ...
    def build(self) -> TaskResubmit: ...
