from .instance_search_link import InstanceSearchLink as InstanceSearchLink
from lark_oapi.core.construct import init as init

class TaskSearchNode:
    user_id: str | None
    start_time: int | None
    end_time: int | None
    status: str | None
    title: str | None
    extra: str | None
    link: InstanceSearchLink | None
    task_id: str | None
    update_time: int | None
    task_external_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TaskSearchNodeBuilder: ...

class TaskSearchNodeBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: str) -> TaskSearchNodeBuilder: ...
    def start_time(self, start_time: int) -> TaskSearchNodeBuilder: ...
    def end_time(self, end_time: int) -> TaskSearchNodeBuilder: ...
    def status(self, status: str) -> TaskSearchNodeBuilder: ...
    def title(self, title: str) -> TaskSearchNodeBuilder: ...
    def extra(self, extra: str) -> TaskSearchNodeBuilder: ...
    def link(self, link: InstanceSearchLink) -> TaskSearchNodeBuilder: ...
    def task_id(self, task_id: str) -> TaskSearchNodeBuilder: ...
    def update_time(self, update_time: int) -> TaskSearchNodeBuilder: ...
    def task_external_id(self, task_external_id: str) -> TaskSearchNodeBuilder: ...
    def build(self) -> TaskSearchNode: ...
