from lark_oapi.core.construct import init as init

class TransferTaskResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TransferTaskResponseBodyBuilder: ...

class TransferTaskResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> TransferTaskResponseBody: ...
