from .task_transfer import TaskTransfer as TaskTransfer
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class TransferTaskRequest(BaseRequest):
    user_id_type: str | None
    request_body: TaskTransfer | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> TransferTaskRequestBuilder: ...

class TransferTaskRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> TransferTaskRequestBuilder: ...
    def request_body(self, request_body: TaskTransfer) -> TransferTaskRequestBuilder: ...
    def build(self) -> TransferTaskRequest: ...
