from .trip_group_schedule import TripGroupSchedule as TripGroupSchedule
from .user import User as User
from lark_oapi.core.construct import init as init

class TripGroup:
    type: str | None
    instance_code: str | None
    start_user: User | None
    start_time: str | None
    end_time: str | None
    trip_interval: str | None
    trip_reason: str | None
    schedules: list[TripGroupSchedule] | None
    trip_peers: list[User] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TripGroupBuilder: ...

class TripGroupBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> TripGroupBuilder: ...
    def instance_code(self, instance_code: str) -> TripGroupBuilder: ...
    def start_user(self, start_user: User) -> TripGroupBuilder: ...
    def start_time(self, start_time: str) -> TripGroupBuilder: ...
    def end_time(self, end_time: str) -> TripGroupBuilder: ...
    def trip_interval(self, trip_interval: str) -> TripGroupBuilder: ...
    def trip_reason(self, trip_reason: str) -> TripGroupBuilder: ...
    def schedules(self, schedules: list[TripGroupSchedule]) -> TripGroupBuilder: ...
    def trip_peers(self, trip_peers: list[User]) -> TripGroupBuilder: ...
    def build(self) -> TripGroup: ...
