from lark_oapi.core.construct import init as init

class TrusteeshipUrls:
    form_detail_url: str | None
    action_definition_url: str | None
    approval_node_url: str | None
    action_callback_url: str | None
    pull_business_data_url: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TrusteeshipUrlsBuilder: ...

class TrusteeshipUrlsBuilder:
    def __init__(self) -> None: ...
    def form_detail_url(self, form_detail_url: str) -> TrusteeshipUrlsBuilder: ...
    def action_definition_url(self, action_definition_url: str) -> TrusteeshipUrlsBuilder: ...
    def approval_node_url(self, approval_node_url: str) -> TrusteeshipUrlsBuilder: ...
    def action_callback_url(self, action_callback_url: str) -> TrusteeshipUrlsBuilder: ...
    def pull_business_data_url(self, pull_business_data_url: str) -> TrusteeshipUrlsBuilder: ...
    def build(self) -> TrusteeshipUrls: ...
