from lark_oapi.core.construct import init as init

class UnsubscribeApprovalResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UnsubscribeApprovalResponseBodyBuilder: ...

class UnsubscribeApprovalResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> UnsubscribeApprovalResponseBody: ...
