from lark_oapi.core.construct import init as init

class UnsubscribeApprovalRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UnsubscribeApprovalRequestBodyBuilder: ...

class UnsubscribeApprovalRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> UnsubscribeApprovalRequestBody: ...
