from lark_oapi.core.construct import init as init

class AuditAndroidContext:
    udid: str | None
    did: str | None
    app_ver: str | None
    ver: str | None
    region: str | None
    id_i: str | None
    id_r: str | None
    hw_brand: str | None
    hw_manuf: str | None
    wifip: str | None
    route_iip: str | None
    route_gip: str | None
    env_su: str | None
    env_tz: str | None
    env_ml: str | None
    location: str | None
    active_ip: str | None
    active_ip_detail: str | None
    cell_base_station: str | None
    i_p: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AuditAndroidContextBuilder: ...

class AuditAndroidContextBuilder:
    def __init__(self) -> None: ...
    def udid(self, udid: str) -> AuditAndroidContextBuilder: ...
    def did(self, did: str) -> AuditAndroidContextBuilder: ...
    def app_ver(self, app_ver: str) -> AuditAndroidContextBuilder: ...
    def ver(self, ver: str) -> AuditAndroidContextBuilder: ...
    def region(self, region: str) -> AuditAndroidContextBuilder: ...
    def id_i(self, id_i: str) -> AuditAndroidContextBuilder: ...
    def id_r(self, id_r: str) -> AuditAndroidContextBuilder: ...
    def hw_brand(self, hw_brand: str) -> AuditAndroidContextBuilder: ...
    def hw_manuf(self, hw_manuf: str) -> AuditAndroidContextBuilder: ...
    def wifip(self, wifip: str) -> AuditAndroidContextBuilder: ...
    def route_iip(self, route_iip: str) -> AuditAndroidContextBuilder: ...
    def route_gip(self, route_gip: str) -> AuditAndroidContextBuilder: ...
    def env_su(self, env_su: str) -> AuditAndroidContextBuilder: ...
    def env_tz(self, env_tz: str) -> AuditAndroidContextBuilder: ...
    def env_ml(self, env_ml: str) -> AuditAndroidContextBuilder: ...
    def location(self, location: str) -> AuditAndroidContextBuilder: ...
    def active_ip(self, active_ip: str) -> AuditAndroidContextBuilder: ...
    def active_ip_detail(self, active_ip_detail: str) -> AuditAndroidContextBuilder: ...
    def cell_base_station(self, cell_base_station: str) -> AuditAndroidContextBuilder: ...
    def i_p(self, i_p: str) -> AuditAndroidContextBuilder: ...
    def build(self) -> AuditAndroidContext: ...
