from lark_oapi.core.construct import init as init

class AuditRecipientDetail:
    permission_action_type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AuditRecipientDetailBuilder: ...

class AuditRecipientDetailBuilder:
    def __init__(self) -> None: ...
    def permission_action_type(self, permission_action_type: str) -> AuditRecipientDetailBuilder: ...
    def build(self) -> AuditRecipientDetail: ...
