from lark_oapi.core.construct import init as init

class AuditObjectDetail:
    clone_source: str | None
    text_detail: str | None
    file_name: str | None
    third_party_app_i_d: str | None
    contain_file_num: int | None
    permission_setting_type: str | None
    permission_external_access__type: bool | None
    permission_share_type: str | None
    file_service_source: str | None
    okr_download_content: str | None
    container_type: str | None
    container_id: str | None
    current_page: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AuditObjectDetailBuilder: ...

class AuditObjectDetailBuilder:
    def __init__(self) -> None: ...
    def clone_source(self, clone_source: str) -> AuditObjectDetailBuilder: ...
    def text_detail(self, text_detail: str) -> AuditObjectDetailBuilder: ...
    def file_name(self, file_name: str) -> AuditObjectDetailBuilder: ...
    def third_party_app_i_d(self, third_party_app_i_d: str) -> AuditObjectDetailBuilder: ...
    def contain_file_num(self, contain_file_num: int) -> AuditObjectDetailBuilder: ...
    def permission_setting_type(self, permission_setting_type: str) -> AuditObjectDetailBuilder: ...
    def permission_external_access__type(self, permission_external_access__type: bool) -> AuditObjectDetailBuilder: ...
    def permission_share_type(self, permission_share_type: str) -> AuditObjectDetailBuilder: ...
    def file_service_source(self, file_service_source: str) -> AuditObjectDetailBuilder: ...
    def okr_download_content(self, okr_download_content: str) -> AuditObjectDetailBuilder: ...
    def container_type(self, container_type: str) -> AuditObjectDetailBuilder: ...
    def container_id(self, container_id: str) -> AuditObjectDetailBuilder: ...
    def current_page(self, current_page: str) -> AuditObjectDetailBuilder: ...
    def build(self) -> AuditObjectDetail: ...
