from lark_oapi.core.construct import init as init

class AuditDetail:
    mc: str | None
    device_model: str | None
    os: str | None
    city: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AuditDetailBuilder: ...

class AuditDetailBuilder:
    def __init__(self) -> None: ...
    def mc(self, mc: str) -> AuditDetailBuilder: ...
    def device_model(self, device_model: str) -> AuditDetailBuilder: ...
    def os(self, os: str) -> AuditDetailBuilder: ...
    def city(self, city: str) -> AuditDetailBuilder: ...
    def build(self) -> AuditDetail: ...
