from lark_oapi.core.construct import init as init

class DataArchivingMessage:
    seq_id: int | None
    limit: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DataArchivingMessageBuilder: ...

class DataArchivingMessageBuilder:
    def __init__(self) -> None: ...
    def seq_id(self, seq_id: int) -> DataArchivingMessageBuilder: ...
    def limit(self, limit: int) -> DataArchivingMessageBuilder: ...
    def build(self) -> DataArchivingMessage: ...
