from lark_oapi.core.construct import init as init

class DataArchivingUserStruct:
    type: str | None
    id: str | None
    name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DataArchivingUserStructBuilder: ...

class DataArchivingUserStructBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> DataArchivingUserStructBuilder: ...
    def id(self, id: str) -> DataArchivingUserStructBuilder: ...
    def name(self, name: str) -> DataArchivingUserStructBuilder: ...
    def build(self) -> DataArchivingUserStruct: ...
