from .data_archiving_user_struct import DataArchivingUserStruct as DataArchivingUserStruct
from lark_oapi.core.construct import init as init

class DataArchivingMessageStruct:
    message_id: str | None
    message_type: int | None
    sender_info: DataArchivingUserStruct | None
    receiver_ids: list[str] | None
    action_type: str | None
    chat_id: int | None
    action_time: int | None
    is_super_chat: bool | None
    is_cross_tenant_chat: bool | None
    chat_name: str | None
    content: str | None
    chat_mode: str | None
    reaction_type: str | None
    parent_msg_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DataArchivingMessageStructBuilder: ...

class DataArchivingMessageStructBuilder:
    def __init__(self) -> None: ...
    def message_id(self, message_id: str) -> DataArchivingMessageStructBuilder: ...
    def message_type(self, message_type: int) -> DataArchivingMessageStructBuilder: ...
    def sender_info(self, sender_info: DataArchivingUserStruct) -> DataArchivingMessageStructBuilder: ...
    def receiver_ids(self, receiver_ids: list[str]) -> DataArchivingMessageStructBuilder: ...
    def action_type(self, action_type: str) -> DataArchivingMessageStructBuilder: ...
    def chat_id(self, chat_id: int) -> DataArchivingMessageStructBuilder: ...
    def action_time(self, action_time: int) -> DataArchivingMessageStructBuilder: ...
    def is_super_chat(self, is_super_chat: bool) -> DataArchivingMessageStructBuilder: ...
    def is_cross_tenant_chat(self, is_cross_tenant_chat: bool) -> DataArchivingMessageStructBuilder: ...
    def chat_name(self, chat_name: str) -> DataArchivingMessageStructBuilder: ...
    def content(self, content: str) -> DataArchivingMessageStructBuilder: ...
    def chat_mode(self, chat_mode: str) -> DataArchivingMessageStructBuilder: ...
    def reaction_type(self, reaction_type: str) -> DataArchivingMessageStructBuilder: ...
    def parent_msg_id(self, parent_msg_id: str) -> DataArchivingMessageStructBuilder: ...
    def build(self) -> DataArchivingMessageStruct: ...
