from lark_oapi.core.construct import init as init

class DlpExecuteEvidence:
    keyword_hits: list[str] | None
    regular_hits: list[str] | None
    sensitive_hits: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DlpExecuteEvidenceBuilder: ...

class DlpExecuteEvidenceBuilder:
    def __init__(self) -> None: ...
    def keyword_hits(self, keyword_hits: list[str]) -> DlpExecuteEvidenceBuilder: ...
    def regular_hits(self, regular_hits: list[str]) -> DlpExecuteEvidenceBuilder: ...
    def sensitive_hits(self, sensitive_hits: list[str]) -> DlpExecuteEvidenceBuilder: ...
    def build(self) -> DlpExecuteEvidence: ...
