from lark_oapi.core.construct import init as init

class GwResponse:
    status_code: int | None
    header: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GwResponseBuilder: ...

class GwResponseBuilder:
    def __init__(self) -> None: ...
    def status_code(self, status_code: int) -> GwResponseBuilder: ...
    def header(self, header: str) -> GwResponseBuilder: ...
    def build(self) -> GwResponse: ...
