from lark_oapi.core.construct import init as init

class MigrationEntity:
    id: str | None
    location: str | None
    type: str | None
    creator_id: str | None
    creator_type: str | None
    create_time: str | None
    mail_address: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MigrationEntityBuilder: ...

class MigrationEntityBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> MigrationEntityBuilder: ...
    def location(self, location: str) -> MigrationEntityBuilder: ...
    def type(self, type: str) -> MigrationEntityBuilder: ...
    def creator_id(self, creator_id: str) -> MigrationEntityBuilder: ...
    def creator_type(self, creator_type: str) -> MigrationEntityBuilder: ...
    def create_time(self, create_time: str) -> MigrationEntityBuilder: ...
    def mail_address(self, mail_address: str) -> MigrationEntityBuilder: ...
    def build(self) -> MigrationEntity: ...
