from lark_oapi.core.construct import init as init

class Notification:
    idempotent_key: str | None
    content: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> NotificationBuilder: ...

class NotificationBuilder:
    def __init__(self) -> None: ...
    def idempotent_key(self, idempotent_key: str) -> NotificationBuilder: ...
    def content(self, content: str) -> NotificationBuilder: ...
    def build(self) -> Notification: ...
