from lark_oapi.core.construct import init as init

class Param:
    key: str | None
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ParamBuilder: ...

class ParamBuilder:
    def __init__(self) -> None: ...
    def key(self, key: str) -> ParamBuilder: ...
    def value(self, value: str) -> ParamBuilder: ...
    def build(self) -> Param: ...
