from lark_oapi.core.construct import init as init

class TenantThirdPartyEncryptionApp:
    vendor_name: str | None
    status: int | None
    service_start_time: int | None
    service_end_time: int | None
    config: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TenantThirdPartyEncryptionAppBuilder: ...

class TenantThirdPartyEncryptionAppBuilder:
    def __init__(self) -> None: ...
    def vendor_name(self, vendor_name: str) -> TenantThirdPartyEncryptionAppBuilder: ...
    def status(self, status: int) -> TenantThirdPartyEncryptionAppBuilder: ...
    def service_start_time(self, service_start_time: int) -> TenantThirdPartyEncryptionAppBuilder: ...
    def service_end_time(self, service_end_time: int) -> TenantThirdPartyEncryptionAppBuilder: ...
    def config(self, config: str) -> TenantThirdPartyEncryptionAppBuilder: ...
    def build(self) -> TenantThirdPartyEncryptionApp: ...
