from .model.p2_acs_access_record_created_v1 import P2AcsAccessRecordCreatedV1 as P2AcsAccessRecordCreatedV1
from .model.p2_acs_user_updated_v1 import P2AcsUserUpdatedV1 as P2AcsUserUpdatedV1
from _typeshed import Incomplete
from lark_oapi.event.processor import IEventProcessor as IEventProcessor
from typing import Callable

class P2AcsAccessRecordCreatedV1Processor(IEventProcessor[P2AcsAccessRecordCreatedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2AcsAccessRecordCreatedV1], None]) -> None: ...
    def type(self) -> type[P2AcsAccessRecordCreatedV1]: ...
    def do(self, data: P2AcsAccessRecordCreatedV1) -> None: ...

class P2AcsUserUpdatedV1Processor(IEventProcessor[P2AcsUserUpdatedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2AcsUserUpdatedV1], None]) -> None: ...
    def type(self) -> type[P2AcsUserUpdatedV1]: ...
    def do(self, data: P2AcsUserUpdatedV1) -> None: ...
