from lark_oapi.core.construct import init as init

class AddOns:
    component_id: str | None
    component_type_id: str | None
    record: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AddOnsBuilder: ...

class AddOnsBuilder:
    def __init__(self) -> None: ...
    def component_id(self, component_id: str) -> AddOnsBuilder: ...
    def component_type_id(self, component_type_id: str) -> AddOnsBuilder: ...
    def record(self, record: str) -> AddOnsBuilder: ...
    def build(self) -> AddOns: ...
