from lark_oapi.core.construct import init as init

class BatchDeleteDocumentBlockChildrenResponseBody:
    document_revision_id: int | None
    client_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchDeleteDocumentBlockChildrenResponseBodyBuilder: ...

class BatchDeleteDocumentBlockChildrenResponseBodyBuilder:
    def __init__(self) -> None: ...
    def document_revision_id(self, document_revision_id: int) -> BatchDeleteDocumentBlockChildrenResponseBodyBuilder: ...
    def client_token(self, client_token: str) -> BatchDeleteDocumentBlockChildrenResponseBodyBuilder: ...
    def build(self) -> BatchDeleteDocumentBlockChildrenResponseBody: ...
