from lark_oapi.core.construct import init as init

class BatchDeleteChatAnnouncementBlockChildrenResponseBody:
    revision_id: int | None
    client_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchDeleteChatAnnouncementBlockChildrenResponseBodyBuilder: ...

class BatchDeleteChatAnnouncementBlockChildrenResponseBodyBuilder:
    def __init__(self) -> None: ...
    def revision_id(self, revision_id: int) -> BatchDeleteChatAnnouncementBlockChildrenResponseBodyBuilder: ...
    def client_token(self, client_token: str) -> BatchDeleteChatAnnouncementBlockChildrenResponseBodyBuilder: ...
    def build(self) -> BatchDeleteChatAnnouncementBlockChildrenResponseBody: ...
