from lark_oapi.core.construct import init as init

class BatchDeleteChatAnnouncementBlockChildrenRequestBody:
    start_index: int | None
    end_index: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchDeleteChatAnnouncementBlockChildrenRequestBodyBuilder: ...

class BatchDeleteChatAnnouncementBlockChildrenRequestBodyBuilder:
    def __init__(self) -> None: ...
    def start_index(self, start_index: int) -> BatchDeleteChatAnnouncementBlockChildrenRequestBodyBuilder: ...
    def end_index(self, end_index: int) -> BatchDeleteChatAnnouncementBlockChildrenRequestBodyBuilder: ...
    def build(self) -> BatchDeleteChatAnnouncementBlockChildrenRequestBody: ...
