from .block import Block as Block
from lark_oapi.core.construct import init as init

class BatchUpdateChatAnnouncementBlockResponseBody:
    blocks: list[Block] | None
    revision_id: int | None
    client_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchUpdateChatAnnouncementBlockResponseBodyBuilder: ...

class BatchUpdateChatAnnouncementBlockResponseBodyBuilder:
    def __init__(self) -> None: ...
    def blocks(self, blocks: list[Block]) -> BatchUpdateChatAnnouncementBlockResponseBodyBuilder: ...
    def revision_id(self, revision_id: int) -> BatchUpdateChatAnnouncementBlockResponseBodyBuilder: ...
    def client_token(self, client_token: str) -> BatchUpdateChatAnnouncementBlockResponseBodyBuilder: ...
    def build(self) -> BatchUpdateChatAnnouncementBlockResponseBody: ...
