from .batch_delete_chat_announcement_block_children_request_body import BatchDeleteChatAnnouncementBlockChildrenRequestBody as BatchDeleteChatAnnouncementBlockChildrenRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchDeleteChatAnnouncementBlockChildrenRequest(BaseRequest):
    revision_id: int | None
    client_token: str | None
    chat_id: str | None
    block_id: str | None
    request_body: BatchDeleteChatAnnouncementBlockChildrenRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchDeleteChatAnnouncementBlockChildrenRequestBuilder: ...

class BatchDeleteChatAnnouncementBlockChildrenRequestBuilder:
    def __init__(self) -> None: ...
    def revision_id(self, revision_id: int) -> BatchDeleteChatAnnouncementBlockChildrenRequestBuilder: ...
    def client_token(self, client_token: str) -> BatchDeleteChatAnnouncementBlockChildrenRequestBuilder: ...
    def chat_id(self, chat_id: str) -> BatchDeleteChatAnnouncementBlockChildrenRequestBuilder: ...
    def block_id(self, block_id: str) -> BatchDeleteChatAnnouncementBlockChildrenRequestBuilder: ...
    def request_body(self, request_body: BatchDeleteChatAnnouncementBlockChildrenRequestBody) -> BatchDeleteChatAnnouncementBlockChildrenRequestBuilder: ...
    def build(self) -> BatchDeleteChatAnnouncementBlockChildrenRequest: ...
