from .batch_delete_document_block_children_request_body import BatchDeleteDocumentBlockChildrenRequestBody as BatchDeleteDocumentBlockChildrenRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchDeleteDocumentBlockChildrenRequest(BaseRequest):
    document_revision_id: int | None
    client_token: str | None
    document_id: str | None
    block_id: str | None
    request_body: BatchDeleteDocumentBlockChildrenRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchDeleteDocumentBlockChildrenRequestBuilder: ...

class BatchDeleteDocumentBlockChildrenRequestBuilder:
    def __init__(self) -> None: ...
    def document_revision_id(self, document_revision_id: int) -> BatchDeleteDocumentBlockChildrenRequestBuilder: ...
    def client_token(self, client_token: str) -> BatchDeleteDocumentBlockChildrenRequestBuilder: ...
    def document_id(self, document_id: str) -> BatchDeleteDocumentBlockChildrenRequestBuilder: ...
    def block_id(self, block_id: str) -> BatchDeleteDocumentBlockChildrenRequestBuilder: ...
    def request_body(self, request_body: BatchDeleteDocumentBlockChildrenRequestBody) -> BatchDeleteDocumentBlockChildrenRequestBuilder: ...
    def build(self) -> BatchDeleteDocumentBlockChildrenRequest: ...
