from .block import Block as Block
from lark_oapi.core.construct import init as init

class BatchUpdateDocumentBlockResponseBody:
    blocks: list[Block] | None
    document_revision_id: int | None
    client_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchUpdateDocumentBlockResponseBodyBuilder: ...

class BatchUpdateDocumentBlockResponseBodyBuilder:
    def __init__(self) -> None: ...
    def blocks(self, blocks: list[Block]) -> BatchUpdateDocumentBlockResponseBodyBuilder: ...
    def document_revision_id(self, document_revision_id: int) -> BatchUpdateDocumentBlockResponseBodyBuilder: ...
    def client_token(self, client_token: str) -> BatchUpdateDocumentBlockResponseBodyBuilder: ...
    def build(self) -> BatchUpdateDocumentBlockResponseBody: ...
