from .batch_update_chat_announcement_block_request_body import BatchUpdateChatAnnouncementBlockRequestBody as BatchUpdateChatAnnouncementBlockRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchUpdateChatAnnouncementBlockRequest(BaseRequest):
    revision_id: int | None
    client_token: str | None
    user_id_type: str | None
    chat_id: str | None
    request_body: BatchUpdateChatAnnouncementBlockRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchUpdateChatAnnouncementBlockRequestBuilder: ...

class BatchUpdateChatAnnouncementBlockRequestBuilder:
    def __init__(self) -> None: ...
    def revision_id(self, revision_id: int) -> BatchUpdateChatAnnouncementBlockRequestBuilder: ...
    def client_token(self, client_token: str) -> BatchUpdateChatAnnouncementBlockRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> BatchUpdateChatAnnouncementBlockRequestBuilder: ...
    def chat_id(self, chat_id: str) -> BatchUpdateChatAnnouncementBlockRequestBuilder: ...
    def request_body(self, request_body: BatchUpdateChatAnnouncementBlockRequestBody) -> BatchUpdateChatAnnouncementBlockRequestBuilder: ...
    def build(self) -> BatchUpdateChatAnnouncementBlockRequest: ...
