from lark_oapi.core.construct import init as init

class BlockIdToImageUrl:
    block_id: str | None
    image_url: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BlockIdToImageUrlBuilder: ...

class BlockIdToImageUrlBuilder:
    def __init__(self) -> None: ...
    def block_id(self, block_id: str) -> BlockIdToImageUrlBuilder: ...
    def image_url(self, image_url: str) -> BlockIdToImageUrlBuilder: ...
    def build(self) -> BlockIdToImageUrl: ...
