from lark_oapi.core.construct import init as init

class BlockIdRelation:
    temporary_block_id: str | None
    block_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BlockIdRelationBuilder: ...

class BlockIdRelationBuilder:
    def __init__(self) -> None: ...
    def temporary_block_id(self, temporary_block_id: str) -> BlockIdRelationBuilder: ...
    def block_id(self, block_id: str) -> BlockIdRelationBuilder: ...
    def build(self) -> BlockIdRelation: ...
