from lark_oapi.core.construct import init as init

class Callout:
    background_color: int | None
    border_color: int | None
    text_color: int | None
    emoji_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CalloutBuilder: ...

class CalloutBuilder:
    def __init__(self) -> None: ...
    def background_color(self, background_color: int) -> CalloutBuilder: ...
    def border_color(self, border_color: int) -> CalloutBuilder: ...
    def text_color(self, text_color: int) -> CalloutBuilder: ...
    def emoji_id(self, emoji_id: str) -> CalloutBuilder: ...
    def build(self) -> Callout: ...
