from .convert_document_request_body import ConvertDocumentRequestBody as ConvertDocumentRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ConvertDocumentRequest(BaseRequest):
    user_id_type: str | None
    request_body: ConvertDocumentRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ConvertDocumentRequestBuilder: ...

class ConvertDocumentRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> ConvertDocumentRequestBuilder: ...
    def request_body(self, request_body: ConvertDocumentRequestBody) -> ConvertDocumentRequestBuilder: ...
    def build(self) -> ConvertDocumentRequest: ...
