from .block import Block as Block
from .block_id_to_image_url import BlockIdToImageUrl as BlockIdToImageUrl
from lark_oapi.core.construct import init as init

class ConvertDocumentResponseBody:
    first_level_block_ids: list[str] | None
    blocks: list[Block] | None
    block_id_to_image_urls: list[BlockIdToImageUrl] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ConvertDocumentResponseBodyBuilder: ...

class ConvertDocumentResponseBodyBuilder:
    def __init__(self) -> None: ...
    def first_level_block_ids(self, first_level_block_ids: list[str]) -> ConvertDocumentResponseBodyBuilder: ...
    def blocks(self, blocks: list[Block]) -> ConvertDocumentResponseBodyBuilder: ...
    def block_id_to_image_urls(self, block_id_to_image_urls: list[BlockIdToImageUrl]) -> ConvertDocumentResponseBodyBuilder: ...
    def build(self) -> ConvertDocumentResponseBody: ...
