from .block import Block as Block
from lark_oapi.core.construct import init as init

class CreateDocumentBlockChildrenRequestBody:
    children: list[Block] | None
    index: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateDocumentBlockChildrenRequestBodyBuilder: ...

class CreateDocumentBlockChildrenRequestBodyBuilder:
    def __init__(self) -> None: ...
    def children(self, children: list[Block]) -> CreateDocumentBlockChildrenRequestBodyBuilder: ...
    def index(self, index: int) -> CreateDocumentBlockChildrenRequestBodyBuilder: ...
    def build(self) -> CreateDocumentBlockChildrenRequestBody: ...
