from .block import Block as Block
from lark_oapi.core.construct import init as init

class CreateChatAnnouncementBlockChildrenRequestBody:
    children: list[Block] | None
    index: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateChatAnnouncementBlockChildrenRequestBodyBuilder: ...

class CreateChatAnnouncementBlockChildrenRequestBodyBuilder:
    def __init__(self) -> None: ...
    def children(self, children: list[Block]) -> CreateChatAnnouncementBlockChildrenRequestBodyBuilder: ...
    def index(self, index: int) -> CreateChatAnnouncementBlockChildrenRequestBodyBuilder: ...
    def build(self) -> CreateChatAnnouncementBlockChildrenRequestBody: ...
