from lark_oapi.core.construct import init as init

class DeleteGridColumnRequest:
    column_index: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteGridColumnRequestBuilder: ...

class DeleteGridColumnRequestBuilder:
    def __init__(self) -> None: ...
    def column_index(self, column_index: int) -> DeleteGridColumnRequestBuilder: ...
    def build(self) -> DeleteGridColumnRequest: ...
