from lark_oapi.core.construct import init as init

class DeleteTableRowsRequest:
    row_start_index: int | None
    row_end_index: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteTableRowsRequestBuilder: ...

class DeleteTableRowsRequestBuilder:
    def __init__(self) -> None: ...
    def row_start_index(self, row_start_index: int) -> DeleteTableRowsRequestBuilder: ...
    def row_end_index(self, row_end_index: int) -> DeleteTableRowsRequestBuilder: ...
    def build(self) -> DeleteTableRowsRequest: ...
