from lark_oapi.core.construct import init as init

class DocumentCover:
    token: str | None
    offset_ratio_x: float | None
    offset_ratio_y: float | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DocumentCoverBuilder: ...

class DocumentCoverBuilder:
    def __init__(self) -> None: ...
    def token(self, token: str) -> DocumentCoverBuilder: ...
    def offset_ratio_x(self, offset_ratio_x: float) -> DocumentCoverBuilder: ...
    def offset_ratio_y(self, offset_ratio_y: float) -> DocumentCoverBuilder: ...
    def build(self) -> DocumentCover: ...
