from .document_cover import DocumentCover as DocumentCover
from .document_display_setting import DocumentDisplaySetting as DocumentDisplaySetting
from lark_oapi.core.construct import init as init

class Document:
    document_id: str | None
    revision_id: int | None
    title: str | None
    display_setting: DocumentDisplaySetting | None
    cover: DocumentCover | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DocumentBuilder: ...

class DocumentBuilder:
    def __init__(self) -> None: ...
    def document_id(self, document_id: str) -> DocumentBuilder: ...
    def revision_id(self, revision_id: int) -> DocumentBuilder: ...
    def title(self, title: str) -> DocumentBuilder: ...
    def display_setting(self, display_setting: DocumentDisplaySetting) -> DocumentBuilder: ...
    def cover(self, cover: DocumentCover) -> DocumentBuilder: ...
    def build(self) -> Document: ...
