from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetChatAnnouncementBlockChildrenRequest(BaseRequest):
    revision_id: int | None
    page_token: str | None
    page_size: int | None
    user_id_type: str | None
    chat_id: str | None
    block_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetChatAnnouncementBlockChildrenRequestBuilder: ...

class GetChatAnnouncementBlockChildrenRequestBuilder:
    def __init__(self) -> None: ...
    def revision_id(self, revision_id: int) -> GetChatAnnouncementBlockChildrenRequestBuilder: ...
    def page_token(self, page_token: str) -> GetChatAnnouncementBlockChildrenRequestBuilder: ...
    def page_size(self, page_size: int) -> GetChatAnnouncementBlockChildrenRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> GetChatAnnouncementBlockChildrenRequestBuilder: ...
    def chat_id(self, chat_id: str) -> GetChatAnnouncementBlockChildrenRequestBuilder: ...
    def block_id(self, block_id: str) -> GetChatAnnouncementBlockChildrenRequestBuilder: ...
    def build(self) -> GetChatAnnouncementBlockChildrenRequest: ...
