from lark_oapi.core.construct import init as init

class GetDocumentBlockRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetDocumentBlockRequestBodyBuilder: ...

class GetDocumentBlockRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetDocumentBlockRequestBody: ...
