from lark_oapi.core.construct import init as init

class GetChatAnnouncementBlockChildrenRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetChatAnnouncementBlockChildrenRequestBodyBuilder: ...

class GetChatAnnouncementBlockChildrenRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetChatAnnouncementBlockChildrenRequestBody: ...
