from .block import Block as Block
from lark_oapi.core.construct import init as init

class GetChatAnnouncementBlockResponseBody:
    block: Block | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetChatAnnouncementBlockResponseBodyBuilder: ...

class GetChatAnnouncementBlockResponseBodyBuilder:
    def __init__(self) -> None: ...
    def block(self, block: Block) -> GetChatAnnouncementBlockResponseBodyBuilder: ...
    def build(self) -> GetChatAnnouncementBlockResponseBody: ...
