from lark_oapi.core.construct import init as init

class GetDocumentBlockChildrenRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetDocumentBlockChildrenRequestBodyBuilder: ...

class GetDocumentBlockChildrenRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetDocumentBlockChildrenRequestBody: ...
