from lark_oapi.core.construct import init as init

class GridColumn:
    width_ratio: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GridColumnBuilder: ...

class GridColumnBuilder:
    def __init__(self) -> None: ...
    def width_ratio(self, width_ratio: int) -> GridColumnBuilder: ...
    def build(self) -> GridColumn: ...
