from .iframe_component import IframeComponent as IframeComponent
from lark_oapi.core.construct import init as init

class Iframe:
    component: IframeComponent | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> IframeBuilder: ...

class IframeBuilder:
    def __init__(self) -> None: ...
    def component(self, component: IframeComponent) -> IframeBuilder: ...
    def build(self) -> Iframe: ...
