from lark_oapi.core.construct import init as init

class IframeComponent:
    iframe_type: int | None
    url: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> IframeComponentBuilder: ...

class IframeComponentBuilder:
    def __init__(self) -> None: ...
    def iframe_type(self, iframe_type: int) -> IframeComponentBuilder: ...
    def url(self, url: str) -> IframeComponentBuilder: ...
    def build(self) -> IframeComponent: ...
