from .caption import Caption as Caption
from lark_oapi.core.construct import init as init

class Image:
    width: int | None
    height: int | None
    token: str | None
    align: int | None
    caption: Caption | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ImageBuilder: ...

class ImageBuilder:
    def __init__(self) -> None: ...
    def width(self, width: int) -> ImageBuilder: ...
    def height(self, height: int) -> ImageBuilder: ...
    def token(self, token: str) -> ImageBuilder: ...
    def align(self, align: int) -> ImageBuilder: ...
    def caption(self, caption: Caption) -> ImageBuilder: ...
    def build(self) -> Image: ...
