from .text_element_style import TextElementStyle as TextElementStyle
from lark_oapi.core.construct import init as init

class InlineFile:
    file_token: str | None
    source_block_id: str | None
    text_element_style: TextElementStyle | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InlineFileBuilder: ...

class InlineFileBuilder:
    def __init__(self) -> None: ...
    def file_token(self, file_token: str) -> InlineFileBuilder: ...
    def source_block_id(self, source_block_id: str) -> InlineFileBuilder: ...
    def text_element_style(self, text_element_style: TextElementStyle) -> InlineFileBuilder: ...
    def build(self) -> InlineFile: ...
