from lark_oapi.core.construct import init as init

class InsertTableRowRequest:
    row_index: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InsertTableRowRequestBuilder: ...

class InsertTableRowRequestBuilder:
    def __init__(self) -> None: ...
    def row_index(self, row_index: int) -> InsertTableRowRequestBuilder: ...
    def build(self) -> InsertTableRowRequest: ...
