from lark_oapi.core.construct import init as init

class JiraIssue:
    id: str | None
    key: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JiraIssueBuilder: ...

class JiraIssueBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> JiraIssueBuilder: ...
    def key(self, key: str) -> JiraIssueBuilder: ...
    def build(self) -> JiraIssue: ...
