from .block import Block as Block
from lark_oapi.core.construct import init as init

class ListDocumentBlockResponseBody:
    items: list[Block] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListDocumentBlockResponseBodyBuilder: ...

class ListDocumentBlockResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[Block]) -> ListDocumentBlockResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListDocumentBlockResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListDocumentBlockResponseBodyBuilder: ...
    def build(self) -> ListDocumentBlockResponseBody: ...
