from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListDocumentBlockRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    document_revision_id: int | None
    user_id_type: str | None
    document_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListDocumentBlockRequestBuilder: ...

class ListDocumentBlockRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> ListDocumentBlockRequestBuilder: ...
    def page_token(self, page_token: str) -> ListDocumentBlockRequestBuilder: ...
    def document_revision_id(self, document_revision_id: int) -> ListDocumentBlockRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> ListDocumentBlockRequestBuilder: ...
    def document_id(self, document_id: str) -> ListDocumentBlockRequestBuilder: ...
    def build(self) -> ListDocumentBlockRequest: ...
