from lark_oapi.core.construct import init as init

class ListChatAnnouncementBlockRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListChatAnnouncementBlockRequestBodyBuilder: ...

class ListChatAnnouncementBlockRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListChatAnnouncementBlockRequestBody: ...
