from .text_element_style import TextElementStyle as TextElementStyle
from lark_oapi.core.construct import init as init

class MentionUser:
    user_id: str | None
    text_element_style: TextElementStyle | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MentionUserBuilder: ...

class MentionUserBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: str) -> MentionUserBuilder: ...
    def text_element_style(self, text_element_style: TextElementStyle) -> MentionUserBuilder: ...
    def build(self) -> MentionUser: ...
