from .text_element_style import TextElementStyle as TextElementStyle
from lark_oapi.core.construct import init as init

class MentionDoc:
    token: str | None
    obj_type: int | None
    url: str | None
    title: str | None
    text_element_style: TextElementStyle | None
    fallback_type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MentionDocBuilder: ...

class MentionDocBuilder:
    def __init__(self) -> None: ...
    def token(self, token: str) -> MentionDocBuilder: ...
    def obj_type(self, obj_type: int) -> MentionDocBuilder: ...
    def url(self, url: str) -> MentionDocBuilder: ...
    def title(self, title: str) -> MentionDocBuilder: ...
    def text_element_style(self, text_element_style: TextElementStyle) -> MentionDocBuilder: ...
    def fallback_type(self, fallback_type: str) -> MentionDocBuilder: ...
    def build(self) -> MentionDoc: ...
