from lark_oapi.core.construct import init as init

class Mindnote:
    token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MindnoteBuilder: ...

class MindnoteBuilder:
    def __init__(self) -> None: ...
    def token(self, token: str) -> MindnoteBuilder: ...
    def build(self) -> Mindnote: ...
