from lark_oapi.core.construct import init as init

class ObjectiveIdWithKrId:
    objective_id: int | None
    kr_ids: list[int] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ObjectiveIdWithKrIdBuilder: ...

class ObjectiveIdWithKrIdBuilder:
    def __init__(self) -> None: ...
    def objective_id(self, objective_id: int) -> ObjectiveIdWithKrIdBuilder: ...
    def kr_ids(self, kr_ids: list[int]) -> ObjectiveIdWithKrIdBuilder: ...
    def build(self) -> ObjectiveIdWithKrId: ...
