from lark_oapi.core.construct import init as init

class OkrProgressRate:
    mode: str | None
    current: float | None
    percent: float | None
    progress_status: str | None
    start: float | None
    status_type: str | None
    target: float | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OkrProgressRateBuilder: ...

class OkrProgressRateBuilder:
    def __init__(self) -> None: ...
    def mode(self, mode: str) -> OkrProgressRateBuilder: ...
    def current(self, current: float) -> OkrProgressRateBuilder: ...
    def percent(self, percent: float) -> OkrProgressRateBuilder: ...
    def progress_status(self, progress_status: str) -> OkrProgressRateBuilder: ...
    def start(self, start: float) -> OkrProgressRateBuilder: ...
    def status_type(self, status_type: str) -> OkrProgressRateBuilder: ...
    def target(self, target: float) -> OkrProgressRateBuilder: ...
    def build(self) -> OkrProgressRate: ...
