from lark_oapi.core.construct import init as init

class OkrProgress:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OkrProgressBuilder: ...

class OkrProgressBuilder:
    def __init__(self) -> None: ...
    def build(self) -> OkrProgress: ...
