from lark_oapi.core.construct import init as init

class OkrVisibleSetting:
    progress_fill_area_visible: bool | None
    progress_status_visible: bool | None
    score_visible: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OkrVisibleSettingBuilder: ...

class OkrVisibleSettingBuilder:
    def __init__(self) -> None: ...
    def progress_fill_area_visible(self, progress_fill_area_visible: bool) -> OkrVisibleSettingBuilder: ...
    def progress_status_visible(self, progress_status_visible: bool) -> OkrVisibleSettingBuilder: ...
    def score_visible(self, score_visible: bool) -> OkrVisibleSettingBuilder: ...
    def build(self) -> OkrVisibleSetting: ...
