from lark_oapi.core.construct import init as init

class RawContentDocumentRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RawContentDocumentRequestBodyBuilder: ...

class RawContentDocumentRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> RawContentDocumentRequestBody: ...
