from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class RawContentDocumentRequest(BaseRequest):
    lang: int | None
    document_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> RawContentDocumentRequestBuilder: ...

class RawContentDocumentRequestBuilder:
    def __init__(self) -> None: ...
    def lang(self, lang: int) -> RawContentDocumentRequestBuilder: ...
    def document_id(self, document_id: str) -> RawContentDocumentRequestBuilder: ...
    def build(self) -> RawContentDocumentRequest: ...
