from .caption import Caption as Caption
from lark_oapi.core.construct import init as init

class ReplaceImageRequest:
    token: str | None
    width: int | None
    height: int | None
    align: int | None
    caption: Caption | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReplaceImageRequestBuilder: ...

class ReplaceImageRequestBuilder:
    def __init__(self) -> None: ...
    def token(self, token: str) -> ReplaceImageRequestBuilder: ...
    def width(self, width: int) -> ReplaceImageRequestBuilder: ...
    def height(self, height: int) -> ReplaceImageRequestBuilder: ...
    def align(self, align: int) -> ReplaceImageRequestBuilder: ...
    def caption(self, caption: Caption) -> ReplaceImageRequestBuilder: ...
    def build(self) -> ReplaceImageRequest: ...
