from .text_element import TextElement as TextElement
from lark_oapi.core.construct import init as init

class SourceSynced:
    elements: list[TextElement] | None
    align: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SourceSyncedBuilder: ...

class SourceSyncedBuilder:
    def __init__(self) -> None: ...
    def elements(self, elements: list[TextElement]) -> SourceSyncedBuilder: ...
    def align(self, align: int) -> SourceSyncedBuilder: ...
    def build(self) -> SourceSynced: ...
