from .table_merge_info import TableMergeInfo as TableMergeInfo
from lark_oapi.core.construct import init as init

class TableProperty:
    row_size: int | None
    column_size: int | None
    column_width: list[int] | None
    merge_info: list[TableMergeInfo] | None
    header_row: bool | None
    header_column: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TablePropertyBuilder: ...

class TablePropertyBuilder:
    def __init__(self) -> None: ...
    def row_size(self, row_size: int) -> TablePropertyBuilder: ...
    def column_size(self, column_size: int) -> TablePropertyBuilder: ...
    def column_width(self, column_width: list[int]) -> TablePropertyBuilder: ...
    def merge_info(self, merge_info: list[TableMergeInfo]) -> TablePropertyBuilder: ...
    def header_row(self, header_row: bool) -> TablePropertyBuilder: ...
    def header_column(self, header_column: bool) -> TablePropertyBuilder: ...
    def build(self) -> TableProperty: ...
