from lark_oapi.core.construct import init as init

class TableCell:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TableCellBuilder: ...

class TableCellBuilder:
    def __init__(self) -> None: ...
    def build(self) -> TableCell: ...
