from lark_oapi.core.construct import init as init

class TextStyle:
    align: int | None
    done: bool | None
    folded: bool | None
    language: int | None
    wrap: bool | None
    background_color: str | None
    indentation_level: str | None
    sequence: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TextStyleBuilder: ...

class TextStyleBuilder:
    def __init__(self) -> None: ...
    def align(self, align: int) -> TextStyleBuilder: ...
    def done(self, done: bool) -> TextStyleBuilder: ...
    def folded(self, folded: bool) -> TextStyleBuilder: ...
    def language(self, language: int) -> TextStyleBuilder: ...
    def wrap(self, wrap: bool) -> TextStyleBuilder: ...
    def background_color(self, background_color: str) -> TextStyleBuilder: ...
    def indentation_level(self, indentation_level: str) -> TextStyleBuilder: ...
    def sequence(self, sequence: str) -> TextStyleBuilder: ...
    def build(self) -> TextStyle: ...
