from .text_element import TextElement as TextElement
from .text_style import TextStyle as TextStyle
from lark_oapi.core.construct import init as init

class Text:
    style: TextStyle | None
    elements: list[TextElement] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TextBuilder: ...

class TextBuilder:
    def __init__(self) -> None: ...
    def style(self, style: TextStyle) -> TextBuilder: ...
    def elements(self, elements: list[TextElement]) -> TextBuilder: ...
    def build(self) -> Text: ...
