from .link import Link as Link
from lark_oapi.core.construct import init as init

class TextElementStyle:
    bold: bool | None
    italic: bool | None
    strikethrough: bool | None
    underline: bool | None
    inline_code: bool | None
    background_color: int | None
    text_color: int | None
    link: Link | None
    comment_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TextElementStyleBuilder: ...

class TextElementStyleBuilder:
    def __init__(self) -> None: ...
    def bold(self, bold: bool) -> TextElementStyleBuilder: ...
    def italic(self, italic: bool) -> TextElementStyleBuilder: ...
    def strikethrough(self, strikethrough: bool) -> TextElementStyleBuilder: ...
    def underline(self, underline: bool) -> TextElementStyleBuilder: ...
    def inline_code(self, inline_code: bool) -> TextElementStyleBuilder: ...
    def background_color(self, background_color: int) -> TextElementStyleBuilder: ...
    def text_color(self, text_color: int) -> TextElementStyleBuilder: ...
    def link(self, link: Link) -> TextElementStyleBuilder: ...
    def comment_ids(self, comment_ids: list[str]) -> TextElementStyleBuilder: ...
    def build(self) -> TextElementStyle: ...
