from lark_oapi.core.construct import init as init

class UpdateReferenceBaseRequest:
    token: str | None
    view_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateReferenceBaseRequestBuilder: ...

class UpdateReferenceBaseRequestBuilder:
    def __init__(self) -> None: ...
    def token(self, token: str) -> UpdateReferenceBaseRequestBuilder: ...
    def view_id(self, view_id: str) -> UpdateReferenceBaseRequestBuilder: ...
    def build(self) -> UpdateReferenceBaseRequest: ...
