from .text_element import TextElement as TextElement
from .text_style import TextStyle as TextStyle
from lark_oapi.core.construct import init as init

class UpdateTextRequest:
    elements: list[TextElement] | None
    style: TextStyle | None
    fields: list[int] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateTextRequestBuilder: ...

class UpdateTextRequestBuilder:
    def __init__(self) -> None: ...
    def elements(self, elements: list[TextElement]) -> UpdateTextRequestBuilder: ...
    def style(self, style: TextStyle) -> UpdateTextRequestBuilder: ...
    def fields(self, fields: list[int]) -> UpdateTextRequestBuilder: ...
    def build(self) -> UpdateTextRequest: ...
