from lark_oapi.core.construct import init as init

class ListOutboundIpResponseBody:
    ip_list: list[str] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListOutboundIpResponseBodyBuilder: ...

class ListOutboundIpResponseBodyBuilder:
    def __init__(self) -> None: ...
    def ip_list(self, ip_list: list[str]) -> ListOutboundIpResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListOutboundIpResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListOutboundIpResponseBodyBuilder: ...
    def build(self) -> ListOutboundIpResponseBody: ...
