from lark_oapi.core.construct import init as init

class AntiCheatConfig:
    intercept_suspected_cheat_punch: bool | None
    check_cheat_software_punch: bool | None
    check_buddy_punch: bool | None
    check_simulate_wifi_punch: bool | None
    check_change_device_punch: bool | None
    allow_change_device_num: int | None
    suspected_cheat_handle_method: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AntiCheatConfigBuilder: ...

class AntiCheatConfigBuilder:
    def __init__(self) -> None: ...
    def intercept_suspected_cheat_punch(self, intercept_suspected_cheat_punch: bool) -> AntiCheatConfigBuilder: ...
    def check_cheat_software_punch(self, check_cheat_software_punch: bool) -> AntiCheatConfigBuilder: ...
    def check_buddy_punch(self, check_buddy_punch: bool) -> AntiCheatConfigBuilder: ...
    def check_simulate_wifi_punch(self, check_simulate_wifi_punch: bool) -> AntiCheatConfigBuilder: ...
    def check_change_device_punch(self, check_change_device_punch: bool) -> AntiCheatConfigBuilder: ...
    def allow_change_device_num(self, allow_change_device_num: int) -> AntiCheatConfigBuilder: ...
    def suspected_cheat_handle_method(self, suspected_cheat_handle_method: int) -> AntiCheatConfigBuilder: ...
    def build(self) -> AntiCheatConfig: ...
