from .batch_create_temp_user_daily_shift_request_body import BatchCreateTempUserDailyShiftRequestBody as BatchCreateTempUserDailyShiftRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchCreateTempUserDailyShiftRequest(BaseRequest):
    employee_type: str | None
    request_body: BatchCreateTempUserDailyShiftRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchCreateTempUserDailyShiftRequestBuilder: ...

class BatchCreateTempUserDailyShiftRequestBuilder:
    def __init__(self) -> None: ...
    def employee_type(self, employee_type: str) -> BatchCreateTempUserDailyShiftRequestBuilder: ...
    def request_body(self, request_body: BatchCreateTempUserDailyShiftRequestBody) -> BatchCreateTempUserDailyShiftRequestBuilder: ...
    def build(self) -> BatchCreateTempUserDailyShiftRequest: ...
