from .batch_create_user_daily_shift_request_body import BatchCreateUserDailyShiftRequestBody as BatchCreateUserDailyShiftRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchCreateUserDailyShiftRequest(BaseRequest):
    employee_type: str | None
    request_body: BatchCreateUserDailyShiftRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchCreateUserDailyShiftRequestBuilder: ...

class BatchCreateUserDailyShiftRequestBuilder:
    def __init__(self) -> None: ...
    def employee_type(self, employee_type: str) -> BatchCreateUserDailyShiftRequestBuilder: ...
    def request_body(self, request_body: BatchCreateUserDailyShiftRequestBody) -> BatchCreateUserDailyShiftRequestBuilder: ...
    def build(self) -> BatchCreateUserDailyShiftRequest: ...
