from lark_oapi.core.construct import init as init

class BatchDelUserFlowRequestBody:
    record_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchDelUserFlowRequestBodyBuilder: ...

class BatchDelUserFlowRequestBodyBuilder:
    def __init__(self) -> None: ...
    def record_ids(self, record_ids: list[str]) -> BatchDelUserFlowRequestBodyBuilder: ...
    def build(self) -> BatchDelUserFlowRequestBody: ...
