from .batch_del_user_flow_request_body import BatchDelUserFlowRequestBody as BatchDelUserFlowRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchDelUserFlowRequest(BaseRequest):
    request_body: BatchDelUserFlowRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchDelUserFlowRequestBuilder: ...

class BatchDelUserFlowRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: BatchDelUserFlowRequestBody) -> BatchDelUserFlowRequestBuilder: ...
    def build(self) -> BatchDelUserFlowRequest: ...
