from lark_oapi.core.construct import init as init

class ChildItem:
    code: str | None
    value: str | None
    title: str | None
    column_type: int | None
    read_only: bool | None
    min_value: str | None
    max_value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ChildItemBuilder: ...

class ChildItemBuilder:
    def __init__(self) -> None: ...
    def code(self, code: str) -> ChildItemBuilder: ...
    def value(self, value: str) -> ChildItemBuilder: ...
    def title(self, title: str) -> ChildItemBuilder: ...
    def column_type(self, column_type: int) -> ChildItemBuilder: ...
    def read_only(self, read_only: bool) -> ChildItemBuilder: ...
    def min_value(self, min_value: str) -> ChildItemBuilder: ...
    def max_value(self, max_value: str) -> ChildItemBuilder: ...
    def build(self) -> ChildItem: ...
