from lark_oapi.core.construct import init as init

class Coordinate:
    longitude: float | None
    latitude: float | None
    accuracy: float | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CoordinateBuilder: ...

class CoordinateBuilder:
    def __init__(self) -> None: ...
    def longitude(self, longitude: float) -> CoordinateBuilder: ...
    def latitude(self, latitude: float) -> CoordinateBuilder: ...
    def accuracy(self, accuracy: float) -> CoordinateBuilder: ...
    def build(self) -> Coordinate: ...
