from .create_group_request_body import CreateGroupRequestBody as CreateGroupRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateGroupRequest(BaseRequest):
    employee_type: str | None
    dept_type: str | None
    request_body: CreateGroupRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateGroupRequestBuilder: ...

class CreateGroupRequestBuilder:
    def __init__(self) -> None: ...
    def employee_type(self, employee_type: str) -> CreateGroupRequestBuilder: ...
    def dept_type(self, dept_type: str) -> CreateGroupRequestBuilder: ...
    def request_body(self, request_body: CreateGroupRequestBody) -> CreateGroupRequestBuilder: ...
    def build(self) -> CreateGroupRequest: ...
