from .user_approval import UserApproval as UserApproval
from lark_oapi.core.construct import init as init

class CreateUserApprovalRequestBody:
    user_approval: UserApproval | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateUserApprovalRequestBodyBuilder: ...

class CreateUserApprovalRequestBodyBuilder:
    def __init__(self) -> None: ...
    def user_approval(self, user_approval: UserApproval) -> CreateUserApprovalRequestBodyBuilder: ...
    def build(self) -> CreateUserApprovalRequestBody: ...
