from .group import Group as Group
from lark_oapi.core.construct import init as init

class CreateGroupRequestBody:
    group: Group | None
    operator_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateGroupRequestBodyBuilder: ...

class CreateGroupRequestBodyBuilder:
    def __init__(self) -> None: ...
    def group(self, group: Group) -> CreateGroupRequestBodyBuilder: ...
    def operator_id(self, operator_id: str) -> CreateGroupRequestBodyBuilder: ...
    def build(self) -> CreateGroupRequestBody: ...
