from .shift import Shift as Shift
from lark_oapi.core.construct import init as init

class CreateShiftResponseBody:
    shift: Shift | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateShiftResponseBodyBuilder: ...

class CreateShiftResponseBodyBuilder:
    def __init__(self) -> None: ...
    def shift(self, shift: Shift) -> CreateShiftResponseBodyBuilder: ...
    def build(self) -> CreateShiftResponseBody: ...
