from .create_user_approval_request_body import CreateUserApprovalRequestBody as CreateUserApprovalRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateUserApprovalRequest(BaseRequest):
    employee_type: str | None
    request_body: CreateUserApprovalRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateUserApprovalRequestBuilder: ...

class CreateUserApprovalRequestBuilder:
    def __init__(self) -> None: ...
    def employee_type(self, employee_type: str) -> CreateUserApprovalRequestBuilder: ...
    def request_body(self, request_body: CreateUserApprovalRequestBody) -> CreateUserApprovalRequestBuilder: ...
    def build(self) -> CreateUserApprovalRequest: ...
