from lark_oapi.core.construct import init as init

class ExportArchiveUserRecordReq:
    start_date: str | None
    end_date: str | None
    user_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ExportArchiveUserRecordReqBuilder: ...

class ExportArchiveUserRecordReqBuilder:
    def __init__(self) -> None: ...
    def start_date(self, start_date: str) -> ExportArchiveUserRecordReqBuilder: ...
    def end_date(self, end_date: str) -> ExportArchiveUserRecordReqBuilder: ...
    def user_ids(self, user_ids: list[str]) -> ExportArchiveUserRecordReqBuilder: ...
    def build(self) -> ExportArchiveUserRecordReq: ...
