from lark_oapi.core.construct import init as init

class FilterItem:
    filter_type: str | None
    filter_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FilterItemBuilder: ...

class FilterItemBuilder:
    def __init__(self) -> None: ...
    def filter_type(self, filter_type: str) -> FilterItemBuilder: ...
    def filter_ids(self, filter_ids: list[str]) -> FilterItemBuilder: ...
    def build(self) -> FilterItem: ...
