from lark_oapi.core.construct import init as init

class FlexibleRule:
    flexible_early_minutes: int | None
    flexible_late_minutes: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FlexibleRuleBuilder: ...

class FlexibleRuleBuilder:
    def __init__(self) -> None: ...
    def flexible_early_minutes(self, flexible_early_minutes: int) -> FlexibleRuleBuilder: ...
    def flexible_late_minutes(self, flexible_late_minutes: int) -> FlexibleRuleBuilder: ...
    def build(self) -> FlexibleRule: ...
