from .leave_employ_expire_record import LeaveEmployExpireRecord as LeaveEmployExpireRecord
from lark_oapi.core.construct import init as init

class GetLeaveEmployExpireRecordResponseBody:
    records: list[LeaveEmployExpireRecord] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetLeaveEmployExpireRecordResponseBodyBuilder: ...

class GetLeaveEmployExpireRecordResponseBodyBuilder:
    def __init__(self) -> None: ...
    def records(self, records: list[LeaveEmployExpireRecord]) -> GetLeaveEmployExpireRecordResponseBodyBuilder: ...
    def build(self) -> GetLeaveEmployExpireRecordResponseBody: ...
