from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetGroupRequest(BaseRequest):
    employee_type: str | None
    dept_type: str | None
    group_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetGroupRequestBuilder: ...

class GetGroupRequestBuilder:
    def __init__(self) -> None: ...
    def employee_type(self, employee_type: str) -> GetGroupRequestBuilder: ...
    def dept_type(self, dept_type: str) -> GetGroupRequestBuilder: ...
    def group_id(self, group_id: str) -> GetGroupRequestBuilder: ...
    def build(self) -> GetGroupRequest: ...
