from lark_oapi.core.construct import init as init

class GetUserFlowResponseBody:
    user_id: str | None
    creator_id: str | None
    location_name: str | None
    check_time: str | None
    comment: str | None
    record_id: str | None
    longitude: float | None
    latitude: float | None
    ssid: str | None
    bssid: str | None
    is_field: bool | None
    is_wifi: bool | None
    type: int | None
    photo_urls: list[str] | None
    device_id: str | None
    check_result: str | None
    external_id: str | None
    idempotent_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetUserFlowResponseBodyBuilder: ...

class GetUserFlowResponseBodyBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: str) -> GetUserFlowResponseBodyBuilder: ...
    def creator_id(self, creator_id: str) -> GetUserFlowResponseBodyBuilder: ...
    def location_name(self, location_name: str) -> GetUserFlowResponseBodyBuilder: ...
    def check_time(self, check_time: str) -> GetUserFlowResponseBodyBuilder: ...
    def comment(self, comment: str) -> GetUserFlowResponseBodyBuilder: ...
    def record_id(self, record_id: str) -> GetUserFlowResponseBodyBuilder: ...
    def longitude(self, longitude: float) -> GetUserFlowResponseBodyBuilder: ...
    def latitude(self, latitude: float) -> GetUserFlowResponseBodyBuilder: ...
    def ssid(self, ssid: str) -> GetUserFlowResponseBodyBuilder: ...
    def bssid(self, bssid: str) -> GetUserFlowResponseBodyBuilder: ...
    def is_field(self, is_field: bool) -> GetUserFlowResponseBodyBuilder: ...
    def is_wifi(self, is_wifi: bool) -> GetUserFlowResponseBodyBuilder: ...
    def type(self, type: int) -> GetUserFlowResponseBodyBuilder: ...
    def photo_urls(self, photo_urls: list[str]) -> GetUserFlowResponseBodyBuilder: ...
    def device_id(self, device_id: str) -> GetUserFlowResponseBodyBuilder: ...
    def check_result(self, check_result: str) -> GetUserFlowResponseBodyBuilder: ...
    def external_id(self, external_id: str) -> GetUserFlowResponseBodyBuilder: ...
    def idempotent_id(self, idempotent_id: str) -> GetUserFlowResponseBodyBuilder: ...
    def build(self) -> GetUserFlowResponseBody: ...
