from lark_oapi.core.construct import init as init

class GetShiftRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetShiftRequestBodyBuilder: ...

class GetShiftRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetShiftRequestBody: ...
