from lark_oapi.core.construct import init as init

class GroupMeta:
    group_id: str | None
    group_name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GroupMetaBuilder: ...

class GroupMetaBuilder:
    def __init__(self) -> None: ...
    def group_id(self, group_id: str) -> GroupMetaBuilder: ...
    def group_name(self, group_name: str) -> GroupMetaBuilder: ...
    def build(self) -> GroupMeta: ...
