from .anti_cheat_config import AntiCheatConfig as AntiCheatConfig
from .clock_in_abnormal_settings import ClockInAbnormalSettings as ClockInAbnormalSettings
from .free_punch_cfg import FreePunchCfg as FreePunchCfg
from .leave_need_punch_cfg import LeaveNeedPunchCfg as LeaveNeedPunchCfg
from .location import Location as Location
from .machine import Machine as Machine
from .member_status_change import MemberStatusChange as MemberStatusChange
from .overtime_clock_cfg import OvertimeClockCfg as OvertimeClockCfg
from .punch_member import PunchMember as PunchMember
from .punch_special_date_shift import PunchSpecialDateShift as PunchSpecialDateShift
from lark_oapi.core.construct import init as init

class Group:
    group_id: str | None
    group_name: str | None
    time_zone: str | None
    bind_dept_ids: list[str] | None
    except_dept_ids: list[str] | None
    bind_user_ids: list[str] | None
    except_user_ids: list[str] | None
    group_leader_ids: list[str] | None
    sub_group_leader_ids: list[str] | None
    allow_out_punch: bool | None
    out_punch_need_approval: bool | None
    out_punch_need_post_approval: bool | None
    out_punch_need_remark: bool | None
    out_punch_need_photo: bool | None
    out_punch_allowed_hide_addr: bool | None
    out_punch_allowed_adjust_addr: bool | None
    adjust_range: int | None
    allow_pc_punch: bool | None
    allow_remedy: bool | None
    remedy_limit: bool | None
    remedy_limit_count: int | None
    remedy_date_limit: bool | None
    remedy_date_num: int | None
    allow_remedy_type_lack: bool | None
    allow_remedy_type_late: bool | None
    allow_remedy_type_early: bool | None
    allow_remedy_type_normal: bool | None
    show_cumulative_time: bool | None
    show_over_time: bool | None
    hide_staff_punch_time: bool | None
    hide_clock_in_rule: bool | None
    face_punch: bool | None
    face_punch_cfg: int | None
    face_live_need_action: bool | None
    face_downgrade: bool | None
    replace_basic_pic: bool | None
    anti_cheat_punch_config: AntiCheatConfig | None
    machines: list[Machine] | None
    gps_range: int | None
    locations: list[Location] | None
    group_type: int | None
    punch_day_shift_ids: list[str] | None
    free_punch_cfg: FreePunchCfg | None
    calendar_id: int | None
    need_punch_special_days: list[PunchSpecialDateShift] | None
    no_need_punch_special_days: list[PunchSpecialDateShift] | None
    work_day_no_punch_as_lack: bool | None
    effect_now: bool | None
    remedy_period_type: int | None
    remedy_period_custom_date: int | None
    punch_type: int | None
    effect_time: str | None
    fixshift_effect_time: str | None
    member_effect_time: str | None
    rest_clock_in_need_approval: bool | None
    clock_in_need_photo: bool | None
    member_status_change: MemberStatusChange | None
    leave_need_punch: bool | None
    leave_need_punch_cfg: LeaveNeedPunchCfg | None
    go_out_need_punch: int | None
    go_out_need_punch_cfg: LeaveNeedPunchCfg | None
    travel_need_punch: int | None
    travel_need_punch_cfg: LeaveNeedPunchCfg | None
    need_punch_members: list[PunchMember] | None
    no_need_punch_members: list[PunchMember] | None
    save_auto_changes: bool | None
    org_change_auto_adjust: bool | None
    bind_default_dept_ids: list[str] | None
    bind_default_user_ids: list[str] | None
    overtime_clock_cfg: OvertimeClockCfg | None
    new_calendar_id: str | None
    allow_apply_punch: bool | None
    clock_in_abnormal_settings: ClockInAbnormalSettings | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GroupBuilder: ...

class GroupBuilder:
    def __init__(self) -> None: ...
    def group_id(self, group_id: str) -> GroupBuilder: ...
    def group_name(self, group_name: str) -> GroupBuilder: ...
    def time_zone(self, time_zone: str) -> GroupBuilder: ...
    def bind_dept_ids(self, bind_dept_ids: list[str]) -> GroupBuilder: ...
    def except_dept_ids(self, except_dept_ids: list[str]) -> GroupBuilder: ...
    def bind_user_ids(self, bind_user_ids: list[str]) -> GroupBuilder: ...
    def except_user_ids(self, except_user_ids: list[str]) -> GroupBuilder: ...
    def group_leader_ids(self, group_leader_ids: list[str]) -> GroupBuilder: ...
    def sub_group_leader_ids(self, sub_group_leader_ids: list[str]) -> GroupBuilder: ...
    def allow_out_punch(self, allow_out_punch: bool) -> GroupBuilder: ...
    def out_punch_need_approval(self, out_punch_need_approval: bool) -> GroupBuilder: ...
    def out_punch_need_post_approval(self, out_punch_need_post_approval: bool) -> GroupBuilder: ...
    def out_punch_need_remark(self, out_punch_need_remark: bool) -> GroupBuilder: ...
    def out_punch_need_photo(self, out_punch_need_photo: bool) -> GroupBuilder: ...
    def out_punch_allowed_hide_addr(self, out_punch_allowed_hide_addr: bool) -> GroupBuilder: ...
    def out_punch_allowed_adjust_addr(self, out_punch_allowed_adjust_addr: bool) -> GroupBuilder: ...
    def adjust_range(self, adjust_range: int) -> GroupBuilder: ...
    def allow_pc_punch(self, allow_pc_punch: bool) -> GroupBuilder: ...
    def allow_remedy(self, allow_remedy: bool) -> GroupBuilder: ...
    def remedy_limit(self, remedy_limit: bool) -> GroupBuilder: ...
    def remedy_limit_count(self, remedy_limit_count: int) -> GroupBuilder: ...
    def remedy_date_limit(self, remedy_date_limit: bool) -> GroupBuilder: ...
    def remedy_date_num(self, remedy_date_num: int) -> GroupBuilder: ...
    def allow_remedy_type_lack(self, allow_remedy_type_lack: bool) -> GroupBuilder: ...
    def allow_remedy_type_late(self, allow_remedy_type_late: bool) -> GroupBuilder: ...
    def allow_remedy_type_early(self, allow_remedy_type_early: bool) -> GroupBuilder: ...
    def allow_remedy_type_normal(self, allow_remedy_type_normal: bool) -> GroupBuilder: ...
    def show_cumulative_time(self, show_cumulative_time: bool) -> GroupBuilder: ...
    def show_over_time(self, show_over_time: bool) -> GroupBuilder: ...
    def hide_staff_punch_time(self, hide_staff_punch_time: bool) -> GroupBuilder: ...
    def hide_clock_in_rule(self, hide_clock_in_rule: bool) -> GroupBuilder: ...
    def face_punch(self, face_punch: bool) -> GroupBuilder: ...
    def face_punch_cfg(self, face_punch_cfg: int) -> GroupBuilder: ...
    def face_live_need_action(self, face_live_need_action: bool) -> GroupBuilder: ...
    def face_downgrade(self, face_downgrade: bool) -> GroupBuilder: ...
    def replace_basic_pic(self, replace_basic_pic: bool) -> GroupBuilder: ...
    def anti_cheat_punch_config(self, anti_cheat_punch_config: AntiCheatConfig) -> GroupBuilder: ...
    def machines(self, machines: list[Machine]) -> GroupBuilder: ...
    def gps_range(self, gps_range: int) -> GroupBuilder: ...
    def locations(self, locations: list[Location]) -> GroupBuilder: ...
    def group_type(self, group_type: int) -> GroupBuilder: ...
    def punch_day_shift_ids(self, punch_day_shift_ids: list[str]) -> GroupBuilder: ...
    def free_punch_cfg(self, free_punch_cfg: FreePunchCfg) -> GroupBuilder: ...
    def calendar_id(self, calendar_id: int) -> GroupBuilder: ...
    def need_punch_special_days(self, need_punch_special_days: list[PunchSpecialDateShift]) -> GroupBuilder: ...
    def no_need_punch_special_days(self, no_need_punch_special_days: list[PunchSpecialDateShift]) -> GroupBuilder: ...
    def work_day_no_punch_as_lack(self, work_day_no_punch_as_lack: bool) -> GroupBuilder: ...
    def effect_now(self, effect_now: bool) -> GroupBuilder: ...
    def remedy_period_type(self, remedy_period_type: int) -> GroupBuilder: ...
    def remedy_period_custom_date(self, remedy_period_custom_date: int) -> GroupBuilder: ...
    def punch_type(self, punch_type: int) -> GroupBuilder: ...
    def effect_time(self, effect_time: str) -> GroupBuilder: ...
    def fixshift_effect_time(self, fixshift_effect_time: str) -> GroupBuilder: ...
    def member_effect_time(self, member_effect_time: str) -> GroupBuilder: ...
    def rest_clock_in_need_approval(self, rest_clock_in_need_approval: bool) -> GroupBuilder: ...
    def clock_in_need_photo(self, clock_in_need_photo: bool) -> GroupBuilder: ...
    def member_status_change(self, member_status_change: MemberStatusChange) -> GroupBuilder: ...
    def leave_need_punch(self, leave_need_punch: bool) -> GroupBuilder: ...
    def leave_need_punch_cfg(self, leave_need_punch_cfg: LeaveNeedPunchCfg) -> GroupBuilder: ...
    def go_out_need_punch(self, go_out_need_punch: int) -> GroupBuilder: ...
    def go_out_need_punch_cfg(self, go_out_need_punch_cfg: LeaveNeedPunchCfg) -> GroupBuilder: ...
    def travel_need_punch(self, travel_need_punch: int) -> GroupBuilder: ...
    def travel_need_punch_cfg(self, travel_need_punch_cfg: LeaveNeedPunchCfg) -> GroupBuilder: ...
    def need_punch_members(self, need_punch_members: list[PunchMember]) -> GroupBuilder: ...
    def no_need_punch_members(self, no_need_punch_members: list[PunchMember]) -> GroupBuilder: ...
    def save_auto_changes(self, save_auto_changes: bool) -> GroupBuilder: ...
    def org_change_auto_adjust(self, org_change_auto_adjust: bool) -> GroupBuilder: ...
    def bind_default_dept_ids(self, bind_default_dept_ids: list[str]) -> GroupBuilder: ...
    def bind_default_user_ids(self, bind_default_user_ids: list[str]) -> GroupBuilder: ...
    def overtime_clock_cfg(self, overtime_clock_cfg: OvertimeClockCfg) -> GroupBuilder: ...
    def new_calendar_id(self, new_calendar_id: str) -> GroupBuilder: ...
    def allow_apply_punch(self, allow_apply_punch: bool) -> GroupBuilder: ...
    def clock_in_abnormal_settings(self, clock_in_abnormal_settings: ClockInAbnormalSettings) -> GroupBuilder: ...
    def build(self) -> Group: ...
