from lark_oapi.core.construct import init as init

class LateOffLateOnRule:
    late_off_minutes: int | None
    late_on_minutes: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LateOffLateOnRuleBuilder: ...

class LateOffLateOnRuleBuilder:
    def __init__(self) -> None: ...
    def late_off_minutes(self, late_off_minutes: int) -> LateOffLateOnRuleBuilder: ...
    def late_on_minutes(self, late_on_minutes: int) -> LateOffLateOnRuleBuilder: ...
    def build(self) -> LateOffLateOnRule: ...
