from lark_oapi.core.construct import init as init

class LeaveNeedPunchCfg:
    late_minutes_as_late: int | None
    late_minutes_as_lack: int | None
    early_minutes_as_early: int | None
    early_minutes_as_lack: int | None
    not_during_shift: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LeaveNeedPunchCfgBuilder: ...

class LeaveNeedPunchCfgBuilder:
    def __init__(self) -> None: ...
    def late_minutes_as_late(self, late_minutes_as_late: int) -> LeaveNeedPunchCfgBuilder: ...
    def late_minutes_as_lack(self, late_minutes_as_lack: int) -> LeaveNeedPunchCfgBuilder: ...
    def early_minutes_as_early(self, early_minutes_as_early: int) -> LeaveNeedPunchCfgBuilder: ...
    def early_minutes_as_lack(self, early_minutes_as_lack: int) -> LeaveNeedPunchCfgBuilder: ...
    def not_during_shift(self, not_during_shift: bool) -> LeaveNeedPunchCfgBuilder: ...
    def build(self) -> LeaveNeedPunchCfg: ...
