from lark_oapi.core.construct import init as init

class ListUserGroupRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListUserGroupRequestBodyBuilder: ...

class ListUserGroupRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListUserGroupRequestBody: ...
