from lark_oapi.core.construct import init as init

class ListArchiveRuleRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListArchiveRuleRequestBodyBuilder: ...

class ListArchiveRuleRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListArchiveRuleRequestBody: ...
