from lark_oapi.core.construct import init as init

class ListShiftRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListShiftRequestBodyBuilder: ...

class ListShiftRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListShiftRequestBody: ...
