from .shift import Shift as Shift
from lark_oapi.core.construct import init as init

class ListShiftResponseBody:
    shift_list: list[Shift] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListShiftResponseBodyBuilder: ...

class ListShiftResponseBodyBuilder:
    def __init__(self) -> None: ...
    def shift_list(self, shift_list: list[Shift]) -> ListShiftResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListShiftResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListShiftResponseBodyBuilder: ...
    def build(self) -> ListShiftResponseBody: ...
