from .coordinate import Coordinate as Coordinate
from lark_oapi.core.construct import init as init

class LocationInfoEvent:
    coord: Coordinate | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LocationInfoEventBuilder: ...

class LocationInfoEventBuilder:
    def __init__(self) -> None: ...
    def coord(self, coord: Coordinate) -> LocationInfoEventBuilder: ...
    def build(self) -> LocationInfoEvent: ...
