from .area import Area as Area
from lark_oapi.core.construct import init as init

class LocationInfo:
    status: int | None
    geofences: list[Area] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LocationInfoBuilder: ...

class LocationInfoBuilder:
    def __init__(self) -> None: ...
    def status(self, status: int) -> LocationInfoBuilder: ...
    def geofences(self, geofences: list[Area]) -> LocationInfoBuilder: ...
    def build(self) -> LocationInfo: ...
