from lark_oapi.core.construct import init as init

class Machine:
    machine_sn: str | None
    machine_name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MachineBuilder: ...

class MachineBuilder:
    def __init__(self) -> None: ...
    def machine_sn(self, machine_sn: str) -> MachineBuilder: ...
    def machine_name(self, machine_name: str) -> MachineBuilder: ...
    def build(self) -> Machine: ...
