from lark_oapi.core.construct import init as init

class MemberStatusChange:
    onboarding_on_no_need_punch: bool | None
    onboarding_off_no_need_punch: bool | None
    offboarding_on_no_need_punch: bool | None
    offboarding_off_no_need_punch: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MemberStatusChangeBuilder: ...

class MemberStatusChangeBuilder:
    def __init__(self) -> None: ...
    def onboarding_on_no_need_punch(self, onboarding_on_no_need_punch: bool) -> MemberStatusChangeBuilder: ...
    def onboarding_off_no_need_punch(self, onboarding_off_no_need_punch: bool) -> MemberStatusChangeBuilder: ...
    def offboarding_on_no_need_punch(self, offboarding_on_no_need_punch: bool) -> MemberStatusChangeBuilder: ...
    def offboarding_off_no_need_punch(self, offboarding_off_no_need_punch: bool) -> MemberStatusChangeBuilder: ...
    def build(self) -> MemberStatusChange: ...
