from .user_setting import UserSetting as UserSetting
from lark_oapi.core.construct import init as init

class ModifyUserSettingResponseBody:
    user_setting: UserSetting | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ModifyUserSettingResponseBodyBuilder: ...

class ModifyUserSettingResponseBodyBuilder:
    def __init__(self) -> None: ...
    def user_setting(self, user_setting: UserSetting) -> ModifyUserSettingResponseBodyBuilder: ...
    def build(self) -> ModifyUserSettingResponseBody: ...
