from .modify_user_setting_request_body import ModifyUserSettingRequestBody as ModifyUserSettingRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ModifyUserSettingRequest(BaseRequest):
    employee_type: str | None
    request_body: ModifyUserSettingRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ModifyUserSettingRequestBuilder: ...

class ModifyUserSettingRequestBuilder:
    def __init__(self) -> None: ...
    def employee_type(self, employee_type: str) -> ModifyUserSettingRequestBuilder: ...
    def request_body(self, request_body: ModifyUserSettingRequestBody) -> ModifyUserSettingRequestBuilder: ...
    def build(self) -> ModifyUserSettingRequest: ...
