from .overtime_time_range import OvertimeTimeRange as OvertimeTimeRange
from lark_oapi.core.construct import init as init

class OpenApplyTimeRange:
    overtime_attribution_date: str | None
    time_range: OvertimeTimeRange | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OpenApplyTimeRangeBuilder: ...

class OpenApplyTimeRangeBuilder:
    def __init__(self) -> None: ...
    def overtime_attribution_date(self, overtime_attribution_date: str) -> OpenApplyTimeRangeBuilder: ...
    def time_range(self, time_range: OvertimeTimeRange) -> OpenApplyTimeRangeBuilder: ...
    def build(self) -> OpenApplyTimeRange: ...
