from lark_oapi.core.construct import init as init

class OvertimeRule:
    on_overtime: str | None
    off_overtime: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OvertimeRuleBuilder: ...

class OvertimeRuleBuilder:
    def __init__(self) -> None: ...
    def on_overtime(self, on_overtime: str) -> OvertimeRuleBuilder: ...
    def off_overtime(self, off_overtime: str) -> OvertimeRuleBuilder: ...
    def build(self) -> OvertimeRule: ...
