from lark_oapi.core.construct import init as init

class OvertimeTimeRange:
    start_time: str | None
    end_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OvertimeTimeRangeBuilder: ...

class OvertimeTimeRangeBuilder:
    def __init__(self) -> None: ...
    def start_time(self, start_time: str) -> OvertimeTimeRangeBuilder: ...
    def end_time(self, end_time: str) -> OvertimeTimeRangeBuilder: ...
    def build(self) -> OvertimeTimeRange: ...
