from .lang_text import LangText as LangText
from lark_oapi.core.construct import init as init

class PatchLeaveAccrualRecordRequestBody:
    leave_granting_record_id: str | None
    employment_id: str | None
    leave_type_id: str | None
    reason: list[LangText] | None
    time_offset: int | None
    expiration_date: str | None
    quantity: str | None
    section_type: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchLeaveAccrualRecordRequestBodyBuilder: ...

class PatchLeaveAccrualRecordRequestBodyBuilder:
    def __init__(self) -> None: ...
    def leave_granting_record_id(self, leave_granting_record_id: str) -> PatchLeaveAccrualRecordRequestBodyBuilder: ...
    def employment_id(self, employment_id: str) -> PatchLeaveAccrualRecordRequestBodyBuilder: ...
    def leave_type_id(self, leave_type_id: str) -> PatchLeaveAccrualRecordRequestBodyBuilder: ...
    def reason(self, reason: list[LangText]) -> PatchLeaveAccrualRecordRequestBodyBuilder: ...
    def time_offset(self, time_offset: int) -> PatchLeaveAccrualRecordRequestBodyBuilder: ...
    def expiration_date(self, expiration_date: str) -> PatchLeaveAccrualRecordRequestBodyBuilder: ...
    def quantity(self, quantity: str) -> PatchLeaveAccrualRecordRequestBodyBuilder: ...
    def section_type(self, section_type: int) -> PatchLeaveAccrualRecordRequestBodyBuilder: ...
    def build(self) -> PatchLeaveAccrualRecordRequestBody: ...
