from .leave_accrual_record import LeaveAccrualRecord as LeaveAccrualRecord
from lark_oapi.core.construct import init as init

class PatchLeaveAccrualRecordResponseBody:
    record: LeaveAccrualRecord | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchLeaveAccrualRecordResponseBodyBuilder: ...

class PatchLeaveAccrualRecordResponseBodyBuilder:
    def __init__(self) -> None: ...
    def record(self, record: LeaveAccrualRecord) -> PatchLeaveAccrualRecordResponseBodyBuilder: ...
    def build(self) -> PatchLeaveAccrualRecordResponseBody: ...
