from .scope_group import ScopeGroup as ScopeGroup
from lark_oapi.core.construct import init as init

class PunchMember:
    rule_scope_type: int | None
    scope_group_list: ScopeGroup | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PunchMemberBuilder: ...

class PunchMemberBuilder:
    def __init__(self) -> None: ...
    def rule_scope_type(self, rule_scope_type: int) -> PunchMemberBuilder: ...
    def scope_group_list(self, scope_group_list: ScopeGroup) -> PunchMemberBuilder: ...
    def build(self) -> PunchMember: ...
