from lark_oapi.core.construct import init as init

class QueryUserFlowRequestBody:
    user_ids: list[str] | None
    check_time_from: str | None
    check_time_to: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryUserFlowRequestBodyBuilder: ...

class QueryUserFlowRequestBodyBuilder:
    def __init__(self) -> None: ...
    def user_ids(self, user_ids: list[str]) -> QueryUserFlowRequestBodyBuilder: ...
    def check_time_from(self, check_time_from: str) -> QueryUserFlowRequestBodyBuilder: ...
    def check_time_to(self, check_time_to: str) -> QueryUserFlowRequestBodyBuilder: ...
    def build(self) -> QueryUserFlowRequestBody: ...
