from .query_user_flow_request_body import QueryUserFlowRequestBody as QueryUserFlowRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class QueryUserFlowRequest(BaseRequest):
    employee_type: str | None
    include_terminated_user: bool | None
    request_body: QueryUserFlowRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> QueryUserFlowRequestBuilder: ...

class QueryUserFlowRequestBuilder:
    def __init__(self) -> None: ...
    def employee_type(self, employee_type: str) -> QueryUserFlowRequestBuilder: ...
    def include_terminated_user(self, include_terminated_user: bool) -> QueryUserFlowRequestBuilder: ...
    def request_body(self, request_body: QueryUserFlowRequestBody) -> QueryUserFlowRequestBuilder: ...
    def build(self) -> QueryUserFlowRequest: ...
