from .user_flow import UserFlow as UserFlow
from lark_oapi.core.construct import init as init

class QueryUserFlowResponseBody:
    user_flow_results: list[UserFlow] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryUserFlowResponseBodyBuilder: ...

class QueryUserFlowResponseBodyBuilder:
    def __init__(self) -> None: ...
    def user_flow_results(self, user_flow_results: list[UserFlow]) -> QueryUserFlowResponseBodyBuilder: ...
    def build(self) -> QueryUserFlowResponseBody: ...
