from lark_oapi.core.construct import init as init

class QueryUserTaskRemedyRequestBody:
    user_ids: list[str] | None
    check_time_from: str | None
    check_time_to: str | None
    check_date_type: str | None
    status: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryUserTaskRemedyRequestBodyBuilder: ...

class QueryUserTaskRemedyRequestBodyBuilder:
    def __init__(self) -> None: ...
    def user_ids(self, user_ids: list[str]) -> QueryUserTaskRemedyRequestBodyBuilder: ...
    def check_time_from(self, check_time_from: str) -> QueryUserTaskRemedyRequestBodyBuilder: ...
    def check_time_to(self, check_time_to: str) -> QueryUserTaskRemedyRequestBodyBuilder: ...
    def check_date_type(self, check_date_type: str) -> QueryUserTaskRemedyRequestBodyBuilder: ...
    def status(self, status: int) -> QueryUserTaskRemedyRequestBodyBuilder: ...
    def build(self) -> QueryUserTaskRemedyRequestBody: ...
