from lark_oapi.core.construct import init as init

class QueryUserDailyShiftRequestBody:
    user_ids: list[str] | None
    check_date_from: int | None
    check_date_to: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryUserDailyShiftRequestBodyBuilder: ...

class QueryUserDailyShiftRequestBodyBuilder:
    def __init__(self) -> None: ...
    def user_ids(self, user_ids: list[str]) -> QueryUserDailyShiftRequestBodyBuilder: ...
    def check_date_from(self, check_date_from: int) -> QueryUserDailyShiftRequestBodyBuilder: ...
    def check_date_to(self, check_date_to: int) -> QueryUserDailyShiftRequestBodyBuilder: ...
    def build(self) -> QueryUserDailyShiftRequestBody: ...
