from .query_user_stats_view_request_body import QueryUserStatsViewRequestBody as QueryUserStatsViewRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class QueryUserStatsViewRequest(BaseRequest):
    employee_type: str | None
    request_body: QueryUserStatsViewRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> QueryUserStatsViewRequestBuilder: ...

class QueryUserStatsViewRequestBuilder:
    def __init__(self) -> None: ...
    def employee_type(self, employee_type: str) -> QueryUserStatsViewRequestBuilder: ...
    def request_body(self, request_body: QueryUserStatsViewRequestBody) -> QueryUserStatsViewRequestBuilder: ...
    def build(self) -> QueryUserStatsViewRequest: ...
