from .query_user_daily_shift_request_body import QueryUserDailyShiftRequestBody as QueryUserDailyShiftRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class QueryUserDailyShiftRequest(BaseRequest):
    employee_type: str | None
    request_body: QueryUserDailyShiftRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> QueryUserDailyShiftRequestBuilder: ...

class QueryUserDailyShiftRequestBuilder:
    def __init__(self) -> None: ...
    def employee_type(self, employee_type: str) -> QueryUserDailyShiftRequestBuilder: ...
    def request_body(self, request_body: QueryUserDailyShiftRequestBody) -> QueryUserDailyShiftRequestBuilder: ...
    def build(self) -> QueryUserDailyShiftRequest: ...
