from lark_oapi.core.construct import init as init

class QueryUserStatsDataRequestBody:
    locale: str | None
    stats_type: str | None
    start_date: int | None
    end_date: int | None
    user_ids: list[str] | None
    need_history: bool | None
    current_group_only: bool | None
    user_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryUserStatsDataRequestBodyBuilder: ...

class QueryUserStatsDataRequestBodyBuilder:
    def __init__(self) -> None: ...
    def locale(self, locale: str) -> QueryUserStatsDataRequestBodyBuilder: ...
    def stats_type(self, stats_type: str) -> QueryUserStatsDataRequestBodyBuilder: ...
    def start_date(self, start_date: int) -> QueryUserStatsDataRequestBodyBuilder: ...
    def end_date(self, end_date: int) -> QueryUserStatsDataRequestBodyBuilder: ...
    def user_ids(self, user_ids: list[str]) -> QueryUserStatsDataRequestBodyBuilder: ...
    def need_history(self, need_history: bool) -> QueryUserStatsDataRequestBodyBuilder: ...
    def current_group_only(self, current_group_only: bool) -> QueryUserStatsDataRequestBodyBuilder: ...
    def user_id(self, user_id: str) -> QueryUserStatsDataRequestBodyBuilder: ...
    def build(self) -> QueryUserStatsDataRequestBody: ...
