from .query_user_allowed_remedys_user_task_remedy_request_body import QueryUserAllowedRemedysUserTaskRemedyRequestBody as QueryUserAllowedRemedysUserTaskRemedyRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class QueryUserAllowedRemedysUserTaskRemedyRequest(BaseRequest):
    employee_type: str | None
    request_body: QueryUserAllowedRemedysUserTaskRemedyRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> QueryUserAllowedRemedysUserTaskRemedyRequestBuilder: ...

class QueryUserAllowedRemedysUserTaskRemedyRequestBuilder:
    def __init__(self) -> None: ...
    def employee_type(self, employee_type: str) -> QueryUserAllowedRemedysUserTaskRemedyRequestBuilder: ...
    def request_body(self, request_body: QueryUserAllowedRemedysUserTaskRemedyRequestBody) -> QueryUserAllowedRemedysUserTaskRemedyRequestBuilder: ...
    def build(self) -> QueryUserAllowedRemedysUserTaskRemedyRequest: ...
