from lark_oapi.core.construct import init as init

class ReportValue:
    value: str | None
    field_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReportValueBuilder: ...

class ReportValueBuilder:
    def __init__(self) -> None: ...
    def value(self, value: str) -> ReportValueBuilder: ...
    def field_id(self, field_id: str) -> ReportValueBuilder: ...
    def build(self) -> ReportValue: ...
