from lark_oapi.core.construct import init as init

class RestTimeFlexibleConfig:
    need_flexible: bool | None
    late_mins: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RestTimeFlexibleConfigBuilder: ...

class RestTimeFlexibleConfigBuilder:
    def __init__(self) -> None: ...
    def need_flexible(self, need_flexible: bool) -> RestTimeFlexibleConfigBuilder: ...
    def late_mins(self, late_mins: int) -> RestTimeFlexibleConfigBuilder: ...
    def build(self) -> RestTimeFlexibleConfig: ...
