from lark_oapi.core.construct import init as init

class RestRule:
    rest_begin_time: str | None
    rest_end_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RestRuleBuilder: ...

class RestRuleBuilder:
    def __init__(self) -> None: ...
    def rest_begin_time(self, rest_begin_time: str) -> RestRuleBuilder: ...
    def rest_end_time(self, rest_end_time: str) -> RestRuleBuilder: ...
    def build(self) -> RestRule: ...
