from .search_group_request_body import SearchGroupRequestBody as SearchGroupRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class SearchGroupRequest(BaseRequest):
    request_body: SearchGroupRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> SearchGroupRequestBuilder: ...

class SearchGroupRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: SearchGroupRequestBody) -> SearchGroupRequestBuilder: ...
    def build(self) -> SearchGroupRequest: ...
