from lark_oapi.core.construct import init as init

class ShiftGroupUser:
    shift_group_id: str | None
    user_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ShiftGroupUserBuilder: ...

class ShiftGroupUserBuilder:
    def __init__(self) -> None: ...
    def shift_group_id(self, shift_group_id: str) -> ShiftGroupUserBuilder: ...
    def user_id(self, user_id: str) -> ShiftGroupUserBuilder: ...
    def build(self) -> ShiftGroupUser: ...
