from .user_stats_view import UserStatsView as UserStatsView
from lark_oapi.core.construct import init as init

class UpdateUserStatsViewResponseBody:
    view: UserStatsView | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateUserStatsViewResponseBodyBuilder: ...

class UpdateUserStatsViewResponseBodyBuilder:
    def __init__(self) -> None: ...
    def view(self, view: UserStatsView) -> UpdateUserStatsViewResponseBodyBuilder: ...
    def build(self) -> UpdateUserStatsViewResponseBody: ...
