from .update_user_stats_view_request_body import UpdateUserStatsViewRequestBody as UpdateUserStatsViewRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UpdateUserStatsViewRequest(BaseRequest):
    employee_type: str | None
    user_stats_view_id: str | None
    request_body: UpdateUserStatsViewRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UpdateUserStatsViewRequestBuilder: ...

class UpdateUserStatsViewRequestBuilder:
    def __init__(self) -> None: ...
    def employee_type(self, employee_type: str) -> UpdateUserStatsViewRequestBuilder: ...
    def user_stats_view_id(self, user_stats_view_id: str) -> UpdateUserStatsViewRequestBuilder: ...
    def request_body(self, request_body: UpdateUserStatsViewRequestBody) -> UpdateUserStatsViewRequestBuilder: ...
    def build(self) -> UpdateUserStatsViewRequest: ...
