from .user_stats_view import UserStatsView as UserStatsView
from lark_oapi.core.construct import init as init

class UpdateUserStatsViewRequestBody:
    view: UserStatsView | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateUserStatsViewRequestBodyBuilder: ...

class UpdateUserStatsViewRequestBodyBuilder:
    def __init__(self) -> None: ...
    def view(self, view: UserStatsView) -> UpdateUserStatsViewRequestBodyBuilder: ...
    def build(self) -> UpdateUserStatsViewRequestBody: ...
