from lark_oapi.core.construct import init as init

class UploadReportArchiveRuleResponseBody:
    invalid_code: list[str] | None
    invalid_member_id: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UploadReportArchiveRuleResponseBodyBuilder: ...

class UploadReportArchiveRuleResponseBodyBuilder:
    def __init__(self) -> None: ...
    def invalid_code(self, invalid_code: list[str]) -> UploadReportArchiveRuleResponseBodyBuilder: ...
    def invalid_member_id(self, invalid_member_id: list[str]) -> UploadReportArchiveRuleResponseBodyBuilder: ...
    def build(self) -> UploadReportArchiveRuleResponseBody: ...
