from lark_oapi.core.construct import init as init
from typing import Any, IO

class UploadFileRequestBody:
    file: IO[Any] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UploadFileRequestBodyBuilder: ...

class UploadFileRequestBodyBuilder:
    def __init__(self) -> None: ...
    def file(self, file: IO[Any]) -> UploadFileRequestBodyBuilder: ...
    def build(self) -> UploadFileRequestBody: ...
