from .archive_report_data import ArchiveReportData as ArchiveReportData
from lark_oapi.core.construct import init as init

class UploadReportArchiveRuleRequestBody:
    month: str | None
    operator_id: str | None
    archive_report_datas: list[ArchiveReportData] | None
    archive_rule_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UploadReportArchiveRuleRequestBodyBuilder: ...

class UploadReportArchiveRuleRequestBodyBuilder:
    def __init__(self) -> None: ...
    def month(self, month: str) -> UploadReportArchiveRuleRequestBodyBuilder: ...
    def operator_id(self, operator_id: str) -> UploadReportArchiveRuleRequestBodyBuilder: ...
    def archive_report_datas(self, archive_report_datas: list[ArchiveReportData]) -> UploadReportArchiveRuleRequestBodyBuilder: ...
    def archive_rule_id(self, archive_rule_id: str) -> UploadReportArchiveRuleRequestBodyBuilder: ...
    def build(self) -> UploadReportArchiveRuleRequestBody: ...
