from .file import File as File
from lark_oapi.core.construct import init as init

class UploadFileResponseBody:
    file: File | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UploadFileResponseBodyBuilder: ...

class UploadFileResponseBodyBuilder:
    def __init__(self) -> None: ...
    def file(self, file: File) -> UploadFileResponseBodyBuilder: ...
    def build(self) -> UploadFileResponseBody: ...
