from lark_oapi.core.construct import init as init

class UserStatsDataFeature:
    key: str | None
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserStatsDataFeatureBuilder: ...

class UserStatsDataFeatureBuilder:
    def __init__(self) -> None: ...
    def key(self, key: str) -> UserStatsDataFeatureBuilder: ...
    def value(self, value: str) -> UserStatsDataFeatureBuilder: ...
    def build(self) -> UserStatsDataFeature: ...
