from lark_oapi.core.construct import init as init

class UserDailyShift:
    group_id: str | None
    shift_id: str | None
    month: int | None
    user_id: str | None
    day_no: int | None
    is_clear_schedule: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserDailyShiftBuilder: ...

class UserDailyShiftBuilder:
    def __init__(self) -> None: ...
    def group_id(self, group_id: str) -> UserDailyShiftBuilder: ...
    def shift_id(self, shift_id: str) -> UserDailyShiftBuilder: ...
    def month(self, month: int) -> UserDailyShiftBuilder: ...
    def user_id(self, user_id: str) -> UserDailyShiftBuilder: ...
    def day_no(self, day_no: int) -> UserDailyShiftBuilder: ...
    def is_clear_schedule(self, is_clear_schedule: bool) -> UserDailyShiftBuilder: ...
    def build(self) -> UserDailyShift: ...
