from lark_oapi.core.construct import init as init

class UserOvertimeWork:
    approval_id: str | None
    duration: float | None
    unit: int | None
    category: int | None
    type: int | None
    start_time: str | None
    end_time: str | None
    reason: str | None
    idempotent_id: str | None
    correct_process_id: list[str] | None
    cancel_process_id: list[str] | None
    process_id: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserOvertimeWorkBuilder: ...

class UserOvertimeWorkBuilder:
    def __init__(self) -> None: ...
    def approval_id(self, approval_id: str) -> UserOvertimeWorkBuilder: ...
    def duration(self, duration: float) -> UserOvertimeWorkBuilder: ...
    def unit(self, unit: int) -> UserOvertimeWorkBuilder: ...
    def category(self, category: int) -> UserOvertimeWorkBuilder: ...
    def type(self, type: int) -> UserOvertimeWorkBuilder: ...
    def start_time(self, start_time: str) -> UserOvertimeWorkBuilder: ...
    def end_time(self, end_time: str) -> UserOvertimeWorkBuilder: ...
    def reason(self, reason: str) -> UserOvertimeWorkBuilder: ...
    def idempotent_id(self, idempotent_id: str) -> UserOvertimeWorkBuilder: ...
    def correct_process_id(self, correct_process_id: list[str]) -> UserOvertimeWorkBuilder: ...
    def cancel_process_id(self, cancel_process_id: list[str]) -> UserOvertimeWorkBuilder: ...
    def process_id(self, process_id: list[str]) -> UserOvertimeWorkBuilder: ...
    def build(self) -> UserOvertimeWork: ...
