from lark_oapi.core.construct import init as init

class WifiInfo:
    status: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WifiInfoBuilder: ...

class WifiInfoBuilder:
    def __init__(self) -> None: ...
    def status(self, status: int) -> WifiInfoBuilder: ...
    def build(self) -> WifiInfo: ...
