from .body_entity import BodyEntity as BodyEntity
from lark_oapi.core.construct import init as init

class BodyInfo:
    body_type: str | None
    value: BodyEntity | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BodyInfoBuilder: ...

class BodyInfoBuilder:
    def __init__(self) -> None: ...
    def body_type(self, body_type: str) -> BodyInfoBuilder: ...
    def value(self, value: BodyEntity) -> BodyInfoBuilder: ...
    def build(self) -> BodyInfo: ...
