from lark_oapi.core.construct import init as init

class ChinesePassportEntity:
    type: str | None
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ChinesePassportEntityBuilder: ...

class ChinesePassportEntityBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> ChinesePassportEntityBuilder: ...
    def value(self, value: str) -> ChinesePassportEntityBuilder: ...
    def build(self) -> ChinesePassportEntity: ...
