from .chinese_passport_entity import ChinesePassportEntity as ChinesePassportEntity
from lark_oapi.core.construct import init as init

class ChinesePassport:
    entities: list[ChinesePassportEntity] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ChinesePassportBuilder: ...

class ChinesePassportBuilder:
    def __init__(self) -> None: ...
    def entities(self, entities: list[ChinesePassportEntity]) -> ChinesePassportBuilder: ...
    def build(self) -> ChinesePassport: ...
