from .doc_chunk_bbox_item import DocChunkBboxItem as DocChunkBboxItem
from lark_oapi.core.construct import init as init

class DocChunkPosition:
    page_numbers: list[int] | None
    bboxes: list[DocChunkBboxItem] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DocChunkPositionBuilder: ...

class DocChunkPositionBuilder:
    def __init__(self) -> None: ...
    def page_numbers(self, page_numbers: list[int]) -> DocChunkPositionBuilder: ...
    def bboxes(self, bboxes: list[DocChunkBboxItem]) -> DocChunkPositionBuilder: ...
    def build(self) -> DocChunkPosition: ...
