from lark_oapi.core.construct import init as init

class DocChunkTableCell:
    type: str | None
    text: str | None
    x0: str | None
    y0: str | None
    x1: str | None
    y1: str | None
    row_index: int | None
    col_index: int | None
    row_span: int | None
    col_span: int | None
    is_merge_cell: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DocChunkTableCellBuilder: ...

class DocChunkTableCellBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> DocChunkTableCellBuilder: ...
    def text(self, text: str) -> DocChunkTableCellBuilder: ...
    def x0(self, x0: str) -> DocChunkTableCellBuilder: ...
    def y0(self, y0: str) -> DocChunkTableCellBuilder: ...
    def x1(self, x1: str) -> DocChunkTableCellBuilder: ...
    def y1(self, y1: str) -> DocChunkTableCellBuilder: ...
    def row_index(self, row_index: int) -> DocChunkTableCellBuilder: ...
    def col_index(self, col_index: int) -> DocChunkTableCellBuilder: ...
    def row_span(self, row_span: int) -> DocChunkTableCellBuilder: ...
    def col_span(self, col_span: int) -> DocChunkTableCellBuilder: ...
    def is_merge_cell(self, is_merge_cell: bool) -> DocChunkTableCellBuilder: ...
    def build(self) -> DocChunkTableCell: ...
