from lark_oapi.core.construct import init as init

class DrivingEntity:
    type: str | None
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DrivingEntityBuilder: ...

class DrivingEntityBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> DrivingEntityBuilder: ...
    def value(self, value: str) -> DrivingEntityBuilder: ...
    def build(self) -> DrivingEntity: ...
