from lark_oapi.core.construct import init as init

class ExtractPrice:
    contract_price: float | None
    contract_price_original: str | None
    text: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ExtractPriceBuilder: ...

class ExtractPriceBuilder:
    def __init__(self) -> None: ...
    def contract_price(self, contract_price: float) -> ExtractPriceBuilder: ...
    def contract_price_original(self, contract_price_original: str) -> ExtractPriceBuilder: ...
    def text(self, text: str) -> ExtractPriceBuilder: ...
    def build(self) -> ExtractPrice: ...
