from lark_oapi.core.construct import init as init

class ExtractTerm:
    initial_time: str | None
    initial_unit: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ExtractTermBuilder: ...

class ExtractTermBuilder:
    def __init__(self) -> None: ...
    def initial_time(self, initial_time: str) -> ExtractTermBuilder: ...
    def initial_unit(self, initial_unit: str) -> ExtractTermBuilder: ...
    def build(self) -> ExtractTerm: ...
