from lark_oapi.core.construct import init as init

class ExtractCopy:
    copy_num: int | None
    original_copy: str | None
    key: str | None
    text: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ExtractCopyBuilder: ...

class ExtractCopyBuilder:
    def __init__(self) -> None: ...
    def copy_num(self, copy_num: int) -> ExtractCopyBuilder: ...
    def original_copy(self, original_copy: str) -> ExtractCopyBuilder: ...
    def key(self, key: str) -> ExtractCopyBuilder: ...
    def text(self, text: str) -> ExtractCopyBuilder: ...
    def build(self) -> ExtractCopy: ...
