from lark_oapi.core.construct import init as init

class ExtractCurrency:
    currency_name: str | None
    currency_text: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ExtractCurrencyBuilder: ...

class ExtractCurrencyBuilder:
    def __init__(self) -> None: ...
    def currency_name(self, currency_name: str) -> ExtractCurrencyBuilder: ...
    def currency_text(self, currency_text: str) -> ExtractCurrencyBuilder: ...
    def build(self) -> ExtractCurrency: ...
