from .field_extraction_contract_request_body import FieldExtractionContractRequestBody as FieldExtractionContractRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class FieldExtractionContractRequest(BaseRequest):
    request_body: FieldExtractionContractRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> FieldExtractionContractRequestBuilder: ...

class FieldExtractionContractRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: FieldExtractionContractRequestBody) -> FieldExtractionContractRequestBuilder: ...
    def build(self) -> FieldExtractionContractRequest: ...
