from lark_oapi.core.construct import init as init

class FieldExtraction:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FieldExtractionBuilder: ...

class FieldExtractionBuilder:
    def __init__(self) -> None: ...
    def build(self) -> FieldExtraction: ...
