from lark_oapi.core.construct import init as init

class FoodProduceEntity:
    type: str | None
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FoodProduceEntityBuilder: ...

class FoodProduceEntityBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> FoodProduceEntityBuilder: ...
    def value(self, value: str) -> FoodProduceEntityBuilder: ...
    def build(self) -> FoodProduceEntity: ...
