from lark_oapi.core.construct import init as init

class HkmMainlandTravelPermitEntity:
    type: str | None
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> HkmMainlandTravelPermitEntityBuilder: ...

class HkmMainlandTravelPermitEntityBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> HkmMainlandTravelPermitEntityBuilder: ...
    def value(self, value: str) -> HkmMainlandTravelPermitEntityBuilder: ...
    def build(self) -> HkmMainlandTravelPermitEntity: ...
