from lark_oapi.core.construct import init as init

class KvEntity:
    type: str | None
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> KvEntityBuilder: ...

class KvEntityBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> KvEntityBuilder: ...
    def value(self, value: str) -> KvEntityBuilder: ...
    def build(self) -> KvEntity: ...
