from .llm_usage import LlmUsage as LlmUsage
from lark_oapi.core.construct import init as init

class LlmDetail:
    query_id: int | None
    usage: LlmUsage | None
    finish_reason: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LlmDetailBuilder: ...

class LlmDetailBuilder:
    def __init__(self) -> None: ...
    def query_id(self, query_id: int) -> LlmDetailBuilder: ...
    def usage(self, usage: LlmUsage) -> LlmDetailBuilder: ...
    def finish_reason(self, finish_reason: str) -> LlmDetailBuilder: ...
    def build(self) -> LlmDetail: ...
