from .parse_resume_request_body import ParseResumeRequestBody as ParseResumeRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ParseResumeRequest(BaseRequest):
    request_body: ParseResumeRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ParseResumeRequestBuilder: ...

class ParseResumeRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: ParseResumeRequestBody) -> ParseResumeRequestBuilder: ...
    def build(self) -> ParseResumeRequest: ...
