from .vehicle_license import VehicleLicense as VehicleLicense
from lark_oapi.core.construct import init as init

class RecognizeVehicleLicenseResponseBody:
    vehicle_license: VehicleLicense | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RecognizeVehicleLicenseResponseBodyBuilder: ...

class RecognizeVehicleLicenseResponseBodyBuilder:
    def __init__(self) -> None: ...
    def vehicle_license(self, vehicle_license: VehicleLicense) -> RecognizeVehicleLicenseResponseBodyBuilder: ...
    def build(self) -> RecognizeVehicleLicenseResponseBody: ...
