from .recognize_food_manage_license_request_body import RecognizeFoodManageLicenseRequestBody as RecognizeFoodManageLicenseRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class RecognizeFoodManageLicenseRequest(BaseRequest):
    request_body: RecognizeFoodManageLicenseRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> RecognizeFoodManageLicenseRequestBuilder: ...

class RecognizeFoodManageLicenseRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: RecognizeFoodManageLicenseRequestBody) -> RecognizeFoodManageLicenseRequestBuilder: ...
    def build(self) -> RecognizeFoodManageLicenseRequest: ...
