from lark_oapi.core.construct import init as init
from typing import Any, IO

class RecognizeHealthCertificateRequestBody:
    file: IO[Any] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RecognizeHealthCertificateRequestBodyBuilder: ...

class RecognizeHealthCertificateRequestBodyBuilder:
    def __init__(self) -> None: ...
    def file(self, file: IO[Any]) -> RecognizeHealthCertificateRequestBodyBuilder: ...
    def build(self) -> RecognizeHealthCertificateRequestBody: ...
