from lark_oapi.core.construct import init as init
from typing import Any, IO

class RecognizeBusinessLicenseRequestBody:
    file: IO[Any] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RecognizeBusinessLicenseRequestBodyBuilder: ...

class RecognizeBusinessLicenseRequestBodyBuilder:
    def __init__(self) -> None: ...
    def file(self, file: IO[Any]) -> RecognizeBusinessLicenseRequestBodyBuilder: ...
    def build(self) -> RecognizeBusinessLicenseRequestBody: ...
