from .food_manage_license import FoodManageLicense as FoodManageLicense
from lark_oapi.core.construct import init as init

class RecognizeFoodManageLicenseResponseBody:
    food_manage_license: FoodManageLicense | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RecognizeFoodManageLicenseResponseBodyBuilder: ...

class RecognizeFoodManageLicenseResponseBodyBuilder:
    def __init__(self) -> None: ...
    def food_manage_license(self, food_manage_license: FoodManageLicense) -> RecognizeFoodManageLicenseResponseBodyBuilder: ...
    def build(self) -> RecognizeFoodManageLicenseResponseBody: ...
