from .id_card import IdCard as IdCard
from lark_oapi.core.construct import init as init

class RecognizeIdCardResponseBody:
    id_card: IdCard | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RecognizeIdCardResponseBodyBuilder: ...

class RecognizeIdCardResponseBodyBuilder:
    def __init__(self) -> None: ...
    def id_card(self, id_card: IdCard) -> RecognizeIdCardResponseBodyBuilder: ...
    def build(self) -> RecognizeIdCardResponseBody: ...
