from .recognize_vehicle_invoice_request_body import RecognizeVehicleInvoiceRequestBody as RecognizeVehicleInvoiceRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class RecognizeVehicleInvoiceRequest(BaseRequest):
    request_body: RecognizeVehicleInvoiceRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> RecognizeVehicleInvoiceRequestBuilder: ...

class RecognizeVehicleInvoiceRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: RecognizeVehicleInvoiceRequestBody) -> RecognizeVehicleInvoiceRequestBuilder: ...
    def build(self) -> RecognizeVehicleInvoiceRequest: ...
