from lark_oapi.core.construct import init as init

class RecognizedEntity:
    type: str | None
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RecognizedEntityBuilder: ...

class RecognizedEntityBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> RecognizedEntityBuilder: ...
    def value(self, value: str) -> RecognizedEntityBuilder: ...
    def build(self) -> RecognizedEntity: ...
