from .recognize_tw_mainland_travel_permit_request_body import RecognizeTwMainlandTravelPermitRequestBody as RecognizeTwMainlandTravelPermitRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class RecognizeTwMainlandTravelPermitRequest(BaseRequest):
    request_body: RecognizeTwMainlandTravelPermitRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> RecognizeTwMainlandTravelPermitRequestBuilder: ...

class RecognizeTwMainlandTravelPermitRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: RecognizeTwMainlandTravelPermitRequestBody) -> RecognizeTwMainlandTravelPermitRequestBuilder: ...
    def build(self) -> RecognizeTwMainlandTravelPermitRequest: ...
