from .recognize_business_license_request_body import RecognizeBusinessLicenseRequestBody as RecognizeBusinessLicenseRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class RecognizeBusinessLicenseRequest(BaseRequest):
    request_body: RecognizeBusinessLicenseRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> RecognizeBusinessLicenseRequestBuilder: ...

class RecognizeBusinessLicenseRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: RecognizeBusinessLicenseRequestBody) -> RecognizeBusinessLicenseRequestBuilder: ...
    def build(self) -> RecognizeBusinessLicenseRequest: ...
