from lark_oapi.core.construct import init as init
from typing import Any, IO

class RecognizeDrivingLicenseRequestBody:
    file: IO[Any] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RecognizeDrivingLicenseRequestBodyBuilder: ...

class RecognizeDrivingLicenseRequestBodyBuilder:
    def __init__(self) -> None: ...
    def file(self, file: IO[Any]) -> RecognizeDrivingLicenseRequestBodyBuilder: ...
    def build(self) -> RecognizeDrivingLicenseRequestBody: ...
