from lark_oapi.core.construct import init as init
from typing import Any, IO

class RecognizeTaxiInvoiceRequestBody:
    file: IO[Any] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RecognizeTaxiInvoiceRequestBodyBuilder: ...

class RecognizeTaxiInvoiceRequestBodyBuilder:
    def __init__(self) -> None: ...
    def file(self, file: IO[Any]) -> RecognizeTaxiInvoiceRequestBodyBuilder: ...
    def build(self) -> RecognizeTaxiInvoiceRequestBody: ...
