from .train_invoice import TrainInvoice as TrainInvoice
from lark_oapi.core.construct import init as init

class RecognizeTrainInvoiceResponseBody:
    train_invoices: list[TrainInvoice] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RecognizeTrainInvoiceResponseBodyBuilder: ...

class RecognizeTrainInvoiceResponseBodyBuilder:
    def __init__(self) -> None: ...
    def train_invoices(self, train_invoices: list[TrainInvoice]) -> RecognizeTrainInvoiceResponseBodyBuilder: ...
    def build(self) -> RecognizeTrainInvoiceResponseBody: ...
