from lark_oapi.core.construct import init as init
from typing import Any, IO

class RecognizeVatInvoiceRequestBody:
    file: IO[Any] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RecognizeVatInvoiceRequestBodyBuilder: ...

class RecognizeVatInvoiceRequestBodyBuilder:
    def __init__(self) -> None: ...
    def file(self, file: IO[Any]) -> RecognizeVatInvoiceRequestBodyBuilder: ...
    def build(self) -> RecognizeVatInvoiceRequestBody: ...
