from lark_oapi.core.construct import init as init
from typing import Any, IO

class RecognizeTrainInvoiceRequestBody:
    file: IO[Any] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RecognizeTrainInvoiceRequestBodyBuilder: ...

class RecognizeTrainInvoiceRequestBodyBuilder:
    def __init__(self) -> None: ...
    def file(self, file: IO[Any]) -> RecognizeTrainInvoiceRequestBodyBuilder: ...
    def build(self) -> RecognizeTrainInvoiceRequestBody: ...
