from .tw_mainland_travel_permit import TwMainlandTravelPermit as TwMainlandTravelPermit
from lark_oapi.core.construct import init as init

class RecognizeTwMainlandTravelPermitResponseBody:
    tw_mainland_travel_permit: TwMainlandTravelPermit | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RecognizeTwMainlandTravelPermitResponseBodyBuilder: ...

class RecognizeTwMainlandTravelPermitResponseBodyBuilder:
    def __init__(self) -> None: ...
    def tw_mainland_travel_permit(self, tw_mainland_travel_permit: TwMainlandTravelPermit) -> RecognizeTwMainlandTravelPermitResponseBodyBuilder: ...
    def build(self) -> RecognizeTwMainlandTravelPermitResponseBody: ...
