from lark_oapi.core.construct import init as init
from typing import Any, IO

class RecognizeFoodProduceLicenseRequestBody:
    file: IO[Any] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RecognizeFoodProduceLicenseRequestBodyBuilder: ...

class RecognizeFoodProduceLicenseRequestBodyBuilder:
    def __init__(self) -> None: ...
    def file(self, file: IO[Any]) -> RecognizeFoodProduceLicenseRequestBodyBuilder: ...
    def build(self) -> RecognizeFoodProduceLicenseRequestBody: ...
