from lark_oapi.core.construct import init as init
from typing import Any, IO

class RecognizeChinesePassportRequestBody:
    file: IO[Any] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RecognizeChinesePassportRequestBodyBuilder: ...

class RecognizeChinesePassportRequestBodyBuilder:
    def __init__(self) -> None: ...
    def file(self, file: IO[Any]) -> RecognizeChinesePassportRequestBodyBuilder: ...
    def build(self) -> RecognizeChinesePassportRequestBody: ...
