from lark_oapi.core.construct import init as init

class ResumeEducation:
    school: str | None
    start_date: str | None
    start_time: str | None
    end_date: str | None
    end_time: str | None
    major: str | None
    degree: str | None
    qualification: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ResumeEducationBuilder: ...

class ResumeEducationBuilder:
    def __init__(self) -> None: ...
    def school(self, school: str) -> ResumeEducationBuilder: ...
    def start_date(self, start_date: str) -> ResumeEducationBuilder: ...
    def start_time(self, start_time: str) -> ResumeEducationBuilder: ...
    def end_date(self, end_date: str) -> ResumeEducationBuilder: ...
    def end_time(self, end_time: str) -> ResumeEducationBuilder: ...
    def major(self, major: str) -> ResumeEducationBuilder: ...
    def degree(self, degree: str) -> ResumeEducationBuilder: ...
    def qualification(self, qualification: int) -> ResumeEducationBuilder: ...
    def build(self) -> ResumeEducation: ...
