from lark_oapi.core.construct import init as init

class ResumeCareer:
    company: str | None
    start_date: str | None
    start_time: str | None
    end_date: str | None
    end_time: str | None
    title: str | None
    type: int | None
    type_str: str | None
    job_description: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ResumeCareerBuilder: ...

class ResumeCareerBuilder:
    def __init__(self) -> None: ...
    def company(self, company: str) -> ResumeCareerBuilder: ...
    def start_date(self, start_date: str) -> ResumeCareerBuilder: ...
    def start_time(self, start_time: str) -> ResumeCareerBuilder: ...
    def end_date(self, end_date: str) -> ResumeCareerBuilder: ...
    def end_time(self, end_time: str) -> ResumeCareerBuilder: ...
    def title(self, title: str) -> ResumeCareerBuilder: ...
    def type(self, type: int) -> ResumeCareerBuilder: ...
    def type_str(self, type_str: str) -> ResumeCareerBuilder: ...
    def job_description(self, job_description: str) -> ResumeCareerBuilder: ...
    def build(self) -> ResumeCareer: ...
