from lark_oapi.core.construct import init as init

class ResumeAward:
    award: str | None
    date: str | None
    description: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ResumeAwardBuilder: ...

class ResumeAwardBuilder:
    def __init__(self) -> None: ...
    def award(self, award: str) -> ResumeAwardBuilder: ...
    def date(self, date: str) -> ResumeAwardBuilder: ...
    def description(self, description: str) -> ResumeAwardBuilder: ...
    def build(self) -> ResumeAward: ...
