from lark_oapi.core.construct import init as init

class TaxiEnitity:
    type: str | None
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TaxiEnitityBuilder: ...

class TaxiEnitityBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> TaxiEnitityBuilder: ...
    def value(self, value: str) -> TaxiEnitityBuilder: ...
    def build(self) -> TaxiEnitity: ...
