from .taxi_entity import TaxiEntity as TaxiEntity
from lark_oapi.core.construct import init as init

class TaxiInvoice:
    entities: list[TaxiEntity] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TaxiInvoiceBuilder: ...

class TaxiInvoiceBuilder:
    def __init__(self) -> None: ...
    def entities(self, entities: list[TaxiEntity]) -> TaxiInvoiceBuilder: ...
    def build(self) -> TaxiInvoice: ...
