from lark_oapi.core.construct import init as init

class TaxiEntity:
    type: str | None
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TaxiEntityBuilder: ...

class TaxiEntityBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> TaxiEntityBuilder: ...
    def value(self, value: str) -> TaxiEntityBuilder: ...
    def build(self) -> TaxiEntity: ...
