from .train_entity import TrainEntity as TrainEntity
from lark_oapi.core.construct import init as init

class TrainInvoice:
    entities: list[TrainEntity] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TrainInvoiceBuilder: ...

class TrainInvoiceBuilder:
    def __init__(self) -> None: ...
    def entities(self, entities: list[TrainEntity]) -> TrainInvoiceBuilder: ...
    def build(self) -> TrainInvoice: ...
