from lark_oapi.core.construct import init as init

class TrainEntity:
    type: str | None
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TrainEntityBuilder: ...

class TrainEntityBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> TrainEntityBuilder: ...
    def value(self, value: str) -> TrainEntityBuilder: ...
    def build(self) -> TrainEntity: ...
