from .tw_mainland_travel_permit_entity import TwMainlandTravelPermitEntity as TwMainlandTravelPermitEntity
from lark_oapi.core.construct import init as init

class TwMainlandTravelPermit:
    entities: list[TwMainlandTravelPermitEntity] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TwMainlandTravelPermitBuilder: ...

class TwMainlandTravelPermitBuilder:
    def __init__(self) -> None: ...
    def entities(self, entities: list[TwMainlandTravelPermitEntity]) -> TwMainlandTravelPermitBuilder: ...
    def build(self) -> TwMainlandTravelPermit: ...
