from .vat_entity import VatEntity as VatEntity
from lark_oapi.core.construct import init as init

class VatInvoice:
    entities: list[VatEntity] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> VatInvoiceBuilder: ...

class VatInvoiceBuilder:
    def __init__(self) -> None: ...
    def entities(self, entities: list[VatEntity]) -> VatInvoiceBuilder: ...
    def build(self) -> VatInvoice: ...
