from .vehicle_entity import VehicleEntity as VehicleEntity
from lark_oapi.core.construct import init as init

class VehicleLicense:
    entities: list[VehicleEntity] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> VehicleLicenseBuilder: ...

class VehicleLicenseBuilder:
    def __init__(self) -> None: ...
    def entities(self, entities: list[VehicleEntity]) -> VehicleLicenseBuilder: ...
    def build(self) -> VehicleLicense: ...
