from lark_oapi.core.construct import init as init

class VehicleEntity:
    type: str | None
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> VehicleEntityBuilder: ...

class VehicleEntityBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> VehicleEntityBuilder: ...
    def value(self, value: str) -> VehicleEntityBuilder: ...
    def build(self) -> VehicleEntity: ...
