from lark_oapi.core.construct import init as init

class VehicleInvoiceEntity:
    type: str | None
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> VehicleInvoiceEntityBuilder: ...

class VehicleInvoiceEntityBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> VehicleInvoiceEntityBuilder: ...
    def value(self, value: str) -> VehicleInvoiceEntityBuilder: ...
    def build(self) -> VehicleInvoiceEntity: ...
