from lark_oapi.ws.pb.google.protobuf.descriptor import FieldDescriptor as FieldDescriptor
from lark_oapi.ws.pb.google.protobuf.internal import type_checkers as type_checkers

class _ExtensionDict:
    def __init__(self, extended_message) -> None: ...
    def __getitem__(self, extension_handle): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __len__(self) -> int: ...
    def __hash__(self): ...
    def __setitem__(self, extension_handle, value) -> None: ...
    def __delitem__(self, extension_handle) -> None: ...
    def __iter__(self): ...
    def __contains__(self, extension_handle) -> bool: ...
