from ..model.batch_query_agency_request import BatchQueryAgencyRequest as BatchQueryAgencyRequest
from ..model.batch_query_agency_response import BatchQueryAgencyResponse as BatchQueryAgencyResponse
from ..model.get_agency_account_agency_request import GetAgencyAccountAgencyRequest as GetAgencyAccountAgencyRequest
from ..model.get_agency_account_agency_response import GetAgencyAccountAgencyResponse as GetAgencyAccountAgencyResponse
from ..model.get_agency_request import GetAgencyRequest as GetAgencyRequest
from ..model.get_agency_response import GetAgencyResponse as GetAgencyResponse
from ..model.operate_agency_account_agency_request import OperateAgencyAccountAgencyRequest as OperateAgencyAccountAgencyRequest
from ..model.operate_agency_account_agency_response import OperateAgencyAccountAgencyResponse as OperateAgencyAccountAgencyResponse
from ..model.protect_agency_request import ProtectAgencyRequest as ProtectAgencyRequest
from ..model.protect_agency_response import ProtectAgencyResponse as ProtectAgencyResponse
from ..model.protect_search_agency_request import ProtectSearchAgencyRequest as ProtectSearchAgencyRequest
from ..model.protect_search_agency_response import ProtectSearchAgencyResponse as ProtectSearchAgencyResponse
from ..model.query_agency_request import QueryAgencyRequest as QueryAgencyRequest
from ..model.query_agency_response import QueryAgencyResponse as QueryAgencyResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class Agency:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def batch_query(self, request: BatchQueryAgencyRequest, option: RequestOption | None = None) -> BatchQueryAgencyResponse: ...
    async def abatch_query(self, request: BatchQueryAgencyRequest, option: RequestOption | None = None) -> BatchQueryAgencyResponse: ...
    def get(self, request: GetAgencyRequest, option: RequestOption | None = None) -> GetAgencyResponse: ...
    async def aget(self, request: GetAgencyRequest, option: RequestOption | None = None) -> GetAgencyResponse: ...
    def get_agency_account(self, request: GetAgencyAccountAgencyRequest, option: RequestOption | None = None) -> GetAgencyAccountAgencyResponse: ...
    async def aget_agency_account(self, request: GetAgencyAccountAgencyRequest, option: RequestOption | None = None) -> GetAgencyAccountAgencyResponse: ...
    def operate_agency_account(self, request: OperateAgencyAccountAgencyRequest, option: RequestOption | None = None) -> OperateAgencyAccountAgencyResponse: ...
    async def aoperate_agency_account(self, request: OperateAgencyAccountAgencyRequest, option: RequestOption | None = None) -> OperateAgencyAccountAgencyResponse: ...
    def protect(self, request: ProtectAgencyRequest, option: RequestOption | None = None) -> ProtectAgencyResponse: ...
    async def aprotect(self, request: ProtectAgencyRequest, option: RequestOption | None = None) -> ProtectAgencyResponse: ...
    def protect_search(self, request: ProtectSearchAgencyRequest, option: RequestOption | None = None) -> ProtectSearchAgencyResponse: ...
    async def aprotect_search(self, request: ProtectSearchAgencyRequest, option: RequestOption | None = None) -> ProtectSearchAgencyResponse: ...
    def query(self, request: QueryAgencyRequest, option: RequestOption | None = None) -> QueryAgencyResponse: ...
    async def aquery(self, request: QueryAgencyRequest, option: RequestOption | None = None) -> QueryAgencyResponse: ...
