from lark_oapi.core.construct import init as init

class AccessData:
    pv: int | None
    uv: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AccessDataBuilder: ...

class AccessDataBuilder:
    def __init__(self) -> None: ...
    def pv(self, pv: int) -> AccessDataBuilder: ...
    def uv(self, uv: int) -> AccessDataBuilder: ...
    def build(self) -> AccessData: ...
