from .access_data import AccessData as AccessData
from lark_oapi.core.construct import init as init

class BlockAccessData:
    date: str | None
    block_id: str | None
    access_data: AccessData | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BlockAccessDataBuilder: ...

class BlockAccessDataBuilder:
    def __init__(self) -> None: ...
    def date(self, date: str) -> BlockAccessDataBuilder: ...
    def block_id(self, block_id: str) -> BlockAccessDataBuilder: ...
    def access_data(self, access_data: AccessData) -> BlockAccessDataBuilder: ...
    def build(self) -> BlockAccessData: ...
