from lark_oapi.core.construct import init as init

class SearchWorkplaceBlockAccessDataRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SearchWorkplaceBlockAccessDataRequestBodyBuilder: ...

class SearchWorkplaceBlockAccessDataRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> SearchWorkplaceBlockAccessDataRequestBody: ...
