from .custom_workplace_access_data import CustomWorkplaceAccessData as CustomWorkplaceAccessData
from lark_oapi.core.construct import init as init

class SearchCustomWorkplaceAccessDataResponseBody:
    items: list[CustomWorkplaceAccessData] | None
    has_more: bool | None
    page_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SearchCustomWorkplaceAccessDataResponseBodyBuilder: ...

class SearchCustomWorkplaceAccessDataResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[CustomWorkplaceAccessData]) -> SearchCustomWorkplaceAccessDataResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> SearchCustomWorkplaceAccessDataResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> SearchCustomWorkplaceAccessDataResponseBodyBuilder: ...
    def build(self) -> SearchCustomWorkplaceAccessDataResponseBody: ...
