from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class SearchCustomWorkplaceAccessDataRequest(BaseRequest):
    from_date: str | None
    to_date: str | None
    page_size: int | None
    page_token: str | None
    custom_workplace_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> SearchCustomWorkplaceAccessDataRequestBuilder: ...

class SearchCustomWorkplaceAccessDataRequestBuilder:
    def __init__(self) -> None: ...
    def from_date(self, from_date: str) -> SearchCustomWorkplaceAccessDataRequestBuilder: ...
    def to_date(self, to_date: str) -> SearchCustomWorkplaceAccessDataRequestBuilder: ...
    def page_size(self, page_size: int) -> SearchCustomWorkplaceAccessDataRequestBuilder: ...
    def page_token(self, page_token: str) -> SearchCustomWorkplaceAccessDataRequestBuilder: ...
    def custom_workplace_id(self, custom_workplace_id: str) -> SearchCustomWorkplaceAccessDataRequestBuilder: ...
    def build(self) -> SearchCustomWorkplaceAccessDataRequest: ...
