from .access_data import AccessData as AccessData
from lark_oapi.core.construct import init as init

class TemplateWorkplaceAccessData:
    tpl_id: str | None
    access_data: AccessData | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TemplateWorkplaceAccessDataBuilder: ...

class TemplateWorkplaceAccessDataBuilder:
    def __init__(self) -> None: ...
    def tpl_id(self, tpl_id: str) -> TemplateWorkplaceAccessDataBuilder: ...
    def access_data(self, access_data: AccessData) -> TemplateWorkplaceAccessDataBuilder: ...
    def build(self) -> TemplateWorkplaceAccessData: ...
