from .rule import Rule as Rule
from lark_oapi.core.construct import init as init

class WorkplaceTenantNotification:
    notification_id: str | None
    content: str | None
    expire_time: int | None
    rule: Rule | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WorkplaceTenantNotificationBuilder: ...

class WorkplaceTenantNotificationBuilder:
    def __init__(self) -> None: ...
    def notification_id(self, notification_id: str) -> WorkplaceTenantNotificationBuilder: ...
    def content(self, content: str) -> WorkplaceTenantNotificationBuilder: ...
    def expire_time(self, expire_time: int) -> WorkplaceTenantNotificationBuilder: ...
    def rule(self, rule: Rule) -> WorkplaceTenantNotificationBuilder: ...
    def build(self) -> WorkplaceTenantNotification: ...
