from ..model.create_entity_request import CreateEntityRequest as CreateEntityRequest
from ..model.create_entity_response import CreateEntityResponse as CreateEntityResponse
from ..model.delete_entity_request import DeleteEntityRequest as DeleteEntityRequest
from ..model.delete_entity_response import DeleteEntityResponse as DeleteEntityResponse
from ..model.get_entity_request import GetEntityRequest as GetEntityRequest
from ..model.get_entity_response import GetEntityResponse as GetEntityResponse
from ..model.highlight_entity_request import HighlightEntityRequest as HighlightEntityRequest
from ..model.highlight_entity_response import HighlightEntityResponse as HighlightEntityResponse
from ..model.list_entity_request import ListEntityRequest as ListEntityRequest
from ..model.list_entity_response import ListEntityResponse as ListEntityResponse
from ..model.match_entity_request import MatchEntityRequest as MatchEntityRequest
from ..model.match_entity_response import MatchEntityResponse as MatchEntityResponse
from ..model.search_entity_request import SearchEntityRequest as SearchEntityRequest
from ..model.search_entity_response import SearchEntityResponse as SearchEntityResponse
from ..model.update_entity_request import UpdateEntityRequest as UpdateEntityRequest
from ..model.update_entity_response import UpdateEntityResponse as UpdateEntityResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class Entity:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def create(self, request: CreateEntityRequest, option: RequestOption | None = None) -> CreateEntityResponse: ...
    async def acreate(self, request: CreateEntityRequest, option: RequestOption | None = None) -> CreateEntityResponse: ...
    def delete(self, request: DeleteEntityRequest, option: RequestOption | None = None) -> DeleteEntityResponse: ...
    async def adelete(self, request: DeleteEntityRequest, option: RequestOption | None = None) -> DeleteEntityResponse: ...
    def get(self, request: GetEntityRequest, option: RequestOption | None = None) -> GetEntityResponse: ...
    async def aget(self, request: GetEntityRequest, option: RequestOption | None = None) -> GetEntityResponse: ...
    def highlight(self, request: HighlightEntityRequest, option: RequestOption | None = None) -> HighlightEntityResponse: ...
    async def ahighlight(self, request: HighlightEntityRequest, option: RequestOption | None = None) -> HighlightEntityResponse: ...
    def list(self, request: ListEntityRequest, option: RequestOption | None = None) -> ListEntityResponse: ...
    async def alist(self, request: ListEntityRequest, option: RequestOption | None = None) -> ListEntityResponse: ...
    def match(self, request: MatchEntityRequest, option: RequestOption | None = None) -> MatchEntityResponse: ...
    async def amatch(self, request: MatchEntityRequest, option: RequestOption | None = None) -> MatchEntityResponse: ...
    def search(self, request: SearchEntityRequest, option: RequestOption | None = None) -> SearchEntityResponse: ...
    async def asearch(self, request: SearchEntityRequest, option: RequestOption | None = None) -> SearchEntityResponse: ...
    def update(self, request: UpdateEntityRequest, option: RequestOption | None = None) -> UpdateEntityResponse: ...
    async def aupdate(self, request: UpdateEntityRequest, option: RequestOption | None = None) -> UpdateEntityResponse: ...
