from .model.p2_meeting_room_meeting_room_created_v1 import P2MeetingRoomMeetingRoomCreatedV1 as P2MeetingRoomMeetingRoomCreatedV1
from .model.p2_meeting_room_meeting_room_deleted_v1 import P2MeetingRoomMeetingRoomDeletedV1 as P2MeetingRoomMeetingRoomDeletedV1
from .model.p2_meeting_room_meeting_room_status_changed_v1 import P2MeetingRoomMeetingRoomStatusChangedV1 as P2MeetingRoomMeetingRoomStatusChangedV1
from .model.p2_meeting_room_meeting_room_updated_v1 import P2MeetingRoomMeetingRoomUpdatedV1 as P2MeetingRoomMeetingRoomUpdatedV1
from _typeshed import Incomplete
from lark_oapi.event.processor import IEventProcessor as IEventProcessor
from typing import Callable

class P2MeetingRoomMeetingRoomCreatedV1Processor(IEventProcessor[P2MeetingRoomMeetingRoomCreatedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2MeetingRoomMeetingRoomCreatedV1], None]) -> None: ...
    def type(self) -> type[P2MeetingRoomMeetingRoomCreatedV1]: ...
    def do(self, data: P2MeetingRoomMeetingRoomCreatedV1) -> None: ...

class P2MeetingRoomMeetingRoomDeletedV1Processor(IEventProcessor[P2MeetingRoomMeetingRoomDeletedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2MeetingRoomMeetingRoomDeletedV1], None]) -> None: ...
    def type(self) -> type[P2MeetingRoomMeetingRoomDeletedV1]: ...
    def do(self, data: P2MeetingRoomMeetingRoomDeletedV1) -> None: ...

class P2MeetingRoomMeetingRoomStatusChangedV1Processor(IEventProcessor[P2MeetingRoomMeetingRoomStatusChangedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2MeetingRoomMeetingRoomStatusChangedV1], None]) -> None: ...
    def type(self) -> type[P2MeetingRoomMeetingRoomStatusChangedV1]: ...
    def do(self, data: P2MeetingRoomMeetingRoomStatusChangedV1) -> None: ...

class P2MeetingRoomMeetingRoomUpdatedV1Processor(IEventProcessor[P2MeetingRoomMeetingRoomUpdatedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2MeetingRoomMeetingRoomUpdatedV1], None]) -> None: ...
    def type(self) -> type[P2MeetingRoomMeetingRoomUpdatedV1]: ...
    def do(self, data: P2MeetingRoomMeetingRoomUpdatedV1) -> None: ...
