from lark_oapi.core.construct import init as init

class CustomFields:
    key: str | None
    label: str | None
    type: str | None
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CustomFieldsBuilder: ...

class CustomFieldsBuilder:
    def __init__(self) -> None: ...
    def key(self, key: str) -> CustomFieldsBuilder: ...
    def label(self, label: str) -> CustomFieldsBuilder: ...
    def type(self, type: str) -> CustomFieldsBuilder: ...
    def value(self, value: str) -> CustomFieldsBuilder: ...
    def build(self) -> CustomFields: ...
