from lark_oapi.core.construct import init as init

class Education:
    level: int | None
    school: str | None
    major: str | None
    degree: int | None
    start: str | None
    end: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EducationBuilder: ...

class EducationBuilder:
    def __init__(self) -> None: ...
    def level(self, level: int) -> EducationBuilder: ...
    def school(self, school: str) -> EducationBuilder: ...
    def major(self, major: str) -> EducationBuilder: ...
    def degree(self, degree: int) -> EducationBuilder: ...
    def start(self, start: str) -> EducationBuilder: ...
    def end(self, end: str) -> EducationBuilder: ...
    def build(self) -> Education: ...
