from lark_oapi.core.construct import init as init

class GetAttachmentResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetAttachmentResponseBodyBuilder: ...

class GetAttachmentResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetAttachmentResponseBody: ...
