from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetAttachmentRequest(BaseRequest):
    token: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetAttachmentRequestBuilder: ...

class GetAttachmentRequestBuilder:
    def __init__(self) -> None: ...
    def token(self, token: str) -> GetAttachmentRequestBuilder: ...
    def build(self) -> GetAttachmentRequest: ...
