from lark_oapi.core.construct import init as init

class Job:
    id: int | None
    name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobBuilder: ...

class JobBuilder:
    def __init__(self) -> None: ...
    def id(self, id: int) -> JobBuilder: ...
    def name(self, name: str) -> JobBuilder: ...
    def build(self) -> Job: ...
