from lark_oapi.core.construct import init as init

class JobLevel:
    id: int | None
    name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobLevelBuilder: ...

class JobLevelBuilder:
    def __init__(self) -> None: ...
    def id(self, id: int) -> JobLevelBuilder: ...
    def name(self, name: str) -> JobLevelBuilder: ...
    def build(self) -> JobLevel: ...
