from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListEmployeeRequest(BaseRequest):
    view: str | None
    status: list[int] | None
    type: list[int] | None
    start_time: int | None
    end_time: int | None
    user_id_type: str | None
    user_ids: list[str] | None
    page_token: str | None
    page_size: int | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListEmployeeRequestBuilder: ...

class ListEmployeeRequestBuilder:
    def __init__(self) -> None: ...
    def view(self, view: str) -> ListEmployeeRequestBuilder: ...
    def status(self, status: list[int]) -> ListEmployeeRequestBuilder: ...
    def type(self, type: list[int]) -> ListEmployeeRequestBuilder: ...
    def start_time(self, start_time: int) -> ListEmployeeRequestBuilder: ...
    def end_time(self, end_time: int) -> ListEmployeeRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> ListEmployeeRequestBuilder: ...
    def user_ids(self, user_ids: list[str]) -> ListEmployeeRequestBuilder: ...
    def page_token(self, page_token: str) -> ListEmployeeRequestBuilder: ...
    def page_size(self, page_size: int) -> ListEmployeeRequestBuilder: ...
    def build(self) -> ListEmployeeRequest: ...
