from lark_oapi.core.construct import init as init

class ListEmployeeRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListEmployeeRequestBodyBuilder: ...

class ListEmployeeRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListEmployeeRequestBody: ...
