from lark_oapi.core.construct import init as init

class Manager:
    user_id: str | None
    name: str | None
    en_name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ManagerBuilder: ...

class ManagerBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: str) -> ManagerBuilder: ...
    def name(self, name: str) -> ManagerBuilder: ...
    def en_name(self, en_name: str) -> ManagerBuilder: ...
    def build(self) -> Manager: ...
