from lark_oapi.core.construct import init as init

class NativeRegion:
    iso_code: str | None
    name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> NativeRegionBuilder: ...

class NativeRegionBuilder:
    def __init__(self) -> None: ...
    def iso_code(self, iso_code: str) -> NativeRegionBuilder: ...
    def name(self, name: str) -> NativeRegionBuilder: ...
    def build(self) -> NativeRegion: ...
