from lark_oapi.core.construct import init as init

class Currency:
    code: str | None
    currency_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CurrencyBuilder: ...

class CurrencyBuilder:
    def __init__(self) -> None: ...
    def code(self, code: str) -> CurrencyBuilder: ...
    def currency_id(self, currency_id: str) -> CurrencyBuilder: ...
    def build(self) -> Currency: ...
