from .formula_param import FormulaParam as FormulaParam
from lark_oapi.core.construct import init as init

class Formula:
    expr: str | None
    formula_params: list[FormulaParam] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FormulaBuilder: ...

class FormulaBuilder:
    def __init__(self) -> None: ...
    def expr(self, expr: str) -> FormulaBuilder: ...
    def formula_params(self, formula_params: list[FormulaParam]) -> FormulaBuilder: ...
    def build(self) -> Formula: ...
