from .standard_reference_object import StandardReferenceObject as StandardReferenceObject
from lark_oapi.core.construct import init as init

class GradeStandardValue:
    standard_value: str | None
    reference_object: StandardReferenceObject | None
    upper_limit: str | None
    lower_limit: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GradeStandardValueBuilder: ...

class GradeStandardValueBuilder:
    def __init__(self) -> None: ...
    def standard_value(self, standard_value: str) -> GradeStandardValueBuilder: ...
    def reference_object(self, reference_object: StandardReferenceObject) -> GradeStandardValueBuilder: ...
    def upper_limit(self, upper_limit: str) -> GradeStandardValueBuilder: ...
    def lower_limit(self, lower_limit: str) -> GradeStandardValueBuilder: ...
    def build(self) -> GradeStandardValue: ...
