from .i18n_content import I18nContent as I18nContent
from lark_oapi.core.construct import init as init

class Item:
    id: str | None
    name: str | None
    description: str | None
    category_id: str | None
    value_type: str | None
    pay_off_frequency_type: str | None
    decimal_places: int | None
    active_status: int | None
    i18n_names: list[I18nContent] | None
    i18n_descriptions: list[I18nContent] | None
    item_type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ItemBuilder: ...

class ItemBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> ItemBuilder: ...
    def name(self, name: str) -> ItemBuilder: ...
    def description(self, description: str) -> ItemBuilder: ...
    def category_id(self, category_id: str) -> ItemBuilder: ...
    def value_type(self, value_type: str) -> ItemBuilder: ...
    def pay_off_frequency_type(self, pay_off_frequency_type: str) -> ItemBuilder: ...
    def decimal_places(self, decimal_places: int) -> ItemBuilder: ...
    def active_status(self, active_status: int) -> ItemBuilder: ...
    def i18n_names(self, i18n_names: list[I18nContent]) -> ItemBuilder: ...
    def i18n_descriptions(self, i18n_descriptions: list[I18nContent]) -> ItemBuilder: ...
    def item_type(self, item_type: str) -> ItemBuilder: ...
    def build(self) -> Item: ...
