from .i18n_content import I18nContent as I18nContent
from lark_oapi.core.construct import init as init

class ItemCategory:
    id: str | None
    name: str | None
    i18n_names: list[I18nContent] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ItemCategoryBuilder: ...

class ItemCategoryBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> ItemCategoryBuilder: ...
    def name(self, name: str) -> ItemCategoryBuilder: ...
    def i18n_names(self, i18n_names: list[I18nContent]) -> ItemCategoryBuilder: ...
    def build(self) -> ItemCategory: ...
