from .plan_detail import PlanDetail as PlanDetail
from lark_oapi.core.construct import init as init

class ListPlanResponseBody:
    items: list[PlanDetail] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListPlanResponseBodyBuilder: ...

class ListPlanResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[PlanDetail]) -> ListPlanResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListPlanResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListPlanResponseBodyBuilder: ...
    def build(self) -> ListPlanResponseBody: ...
