from lark_oapi.core.construct import init as init

class ListIndicatorRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListIndicatorRequestBodyBuilder: ...

class ListIndicatorRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListIndicatorRequestBody: ...
