from lark_oapi.core.construct import init as init

class ListItemCategoryRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListItemCategoryRequestBodyBuilder: ...

class ListItemCategoryRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListItemCategoryRequestBody: ...
