from .lump_sum_payment_detail_for_update import LumpSumPaymentDetailForUpdate as LumpSumPaymentDetailForUpdate
from lark_oapi.core.construct import init as init

class LumpSumPaymentForUpdate:
    id: str | None
    total_amount: str | None
    binding_period: int | None
    currency_id: str | None
    issuance_frequency: int | None
    remark: str | None
    reference_period_start_date: str | None
    reference_period_end_date: str | None
    details: list[LumpSumPaymentDetailForUpdate] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LumpSumPaymentForUpdateBuilder: ...

class LumpSumPaymentForUpdateBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> LumpSumPaymentForUpdateBuilder: ...
    def total_amount(self, total_amount: str) -> LumpSumPaymentForUpdateBuilder: ...
    def binding_period(self, binding_period: int) -> LumpSumPaymentForUpdateBuilder: ...
    def currency_id(self, currency_id: str) -> LumpSumPaymentForUpdateBuilder: ...
    def issuance_frequency(self, issuance_frequency: int) -> LumpSumPaymentForUpdateBuilder: ...
    def remark(self, remark: str) -> LumpSumPaymentForUpdateBuilder: ...
    def reference_period_start_date(self, reference_period_start_date: str) -> LumpSumPaymentForUpdateBuilder: ...
    def reference_period_end_date(self, reference_period_end_date: str) -> LumpSumPaymentForUpdateBuilder: ...
    def details(self, details: list[LumpSumPaymentDetailForUpdate]) -> LumpSumPaymentForUpdateBuilder: ...
    def build(self) -> LumpSumPaymentForUpdate: ...
