from .archive_detail import ArchiveDetail as ArchiveDetail
from lark_oapi.core.construct import init as init

class QueryArchiveResponseBody:
    items: list[ArchiveDetail] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryArchiveResponseBodyBuilder: ...

class QueryArchiveResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[ArchiveDetail]) -> QueryArchiveResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> QueryArchiveResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> QueryArchiveResponseBodyBuilder: ...
    def build(self) -> QueryArchiveResponseBody: ...
