from lark_oapi.core.construct import init as init

class QueryArchiveRequestBody:
    user_id_list: list[str] | None
    tid_list: list[str] | None
    effective_start_date: str | None
    effective_end_date: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryArchiveRequestBodyBuilder: ...

class QueryArchiveRequestBodyBuilder:
    def __init__(self) -> None: ...
    def user_id_list(self, user_id_list: list[str]) -> QueryArchiveRequestBodyBuilder: ...
    def tid_list(self, tid_list: list[str]) -> QueryArchiveRequestBodyBuilder: ...
    def effective_start_date(self, effective_start_date: str) -> QueryArchiveRequestBodyBuilder: ...
    def effective_end_date(self, effective_end_date: str) -> QueryArchiveRequestBodyBuilder: ...
    def build(self) -> QueryArchiveRequestBody: ...
