from .query_archive_request_body import QueryArchiveRequestBody as QueryArchiveRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class QueryArchiveRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    user_id_type: str | None
    request_body: QueryArchiveRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> QueryArchiveRequestBuilder: ...

class QueryArchiveRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> QueryArchiveRequestBuilder: ...
    def page_token(self, page_token: str) -> QueryArchiveRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> QueryArchiveRequestBuilder: ...
    def request_body(self, request_body: QueryArchiveRequestBody) -> QueryArchiveRequestBuilder: ...
    def build(self) -> QueryArchiveRequest: ...
