from lark_oapi.core.construct import init as init

class RecurringPaymentForCreate:
    unique_id: str | None
    user_id: str | None
    item_id: str | None
    each_amount: str | None
    start_date: str | None
    end_date: str | None
    currency_id: str | None
    issuance_type: str | None
    issuance_period: str | None
    remark: str | None
    issuance_country_region_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RecurringPaymentForCreateBuilder: ...

class RecurringPaymentForCreateBuilder:
    def __init__(self) -> None: ...
    def unique_id(self, unique_id: str) -> RecurringPaymentForCreateBuilder: ...
    def user_id(self, user_id: str) -> RecurringPaymentForCreateBuilder: ...
    def item_id(self, item_id: str) -> RecurringPaymentForCreateBuilder: ...
    def each_amount(self, each_amount: str) -> RecurringPaymentForCreateBuilder: ...
    def start_date(self, start_date: str) -> RecurringPaymentForCreateBuilder: ...
    def end_date(self, end_date: str) -> RecurringPaymentForCreateBuilder: ...
    def currency_id(self, currency_id: str) -> RecurringPaymentForCreateBuilder: ...
    def issuance_type(self, issuance_type: str) -> RecurringPaymentForCreateBuilder: ...
    def issuance_period(self, issuance_period: str) -> RecurringPaymentForCreateBuilder: ...
    def remark(self, remark: str) -> RecurringPaymentForCreateBuilder: ...
    def issuance_country_region_id(self, issuance_country_region_id: str) -> RecurringPaymentForCreateBuilder: ...
    def build(self) -> RecurringPaymentForCreate: ...
