from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class SalaryGrade:
    id: str | None
    name: I18n | None
    status: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SalaryGradeBuilder: ...

class SalaryGradeBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> SalaryGradeBuilder: ...
    def name(self, name: I18n) -> SalaryGradeBuilder: ...
    def status(self, status: bool) -> SalaryGradeBuilder: ...
    def build(self) -> SalaryGrade: ...
