from .i18n import I18n as I18n
from .social_plan_item_setting import SocialPlanItemSetting as SocialPlanItemSetting
from lark_oapi.core.construct import init as init

class SocialArchiveItem:
    insurance_id: str | None
    insurance_name: I18n | None
    company_deduction: str | None
    company_setting: SocialPlanItemSetting | None
    personal_deduction: str | None
    personal_setting: SocialPlanItemSetting | None
    payment_frequency: str | None
    payment_months: list[int] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SocialArchiveItemBuilder: ...

class SocialArchiveItemBuilder:
    def __init__(self) -> None: ...
    def insurance_id(self, insurance_id: str) -> SocialArchiveItemBuilder: ...
    def insurance_name(self, insurance_name: I18n) -> SocialArchiveItemBuilder: ...
    def company_deduction(self, company_deduction: str) -> SocialArchiveItemBuilder: ...
    def company_setting(self, company_setting: SocialPlanItemSetting) -> SocialArchiveItemBuilder: ...
    def personal_deduction(self, personal_deduction: str) -> SocialArchiveItemBuilder: ...
    def personal_setting(self, personal_setting: SocialPlanItemSetting) -> SocialArchiveItemBuilder: ...
    def payment_frequency(self, payment_frequency: str) -> SocialArchiveItemBuilder: ...
    def payment_months(self, payment_months: list[int]) -> SocialArchiveItemBuilder: ...
    def build(self) -> SocialArchiveItem: ...
