from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class SocialInsurance:
    id: str | None
    name: I18n | None
    insurance_type: str | None
    active: bool | None
    is_system: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SocialInsuranceBuilder: ...

class SocialInsuranceBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> SocialInsuranceBuilder: ...
    def name(self, name: I18n) -> SocialInsuranceBuilder: ...
    def insurance_type(self, insurance_type: str) -> SocialInsuranceBuilder: ...
    def active(self, active: bool) -> SocialInsuranceBuilder: ...
    def is_system(self, is_system: bool) -> SocialInsuranceBuilder: ...
    def build(self) -> SocialInsurance: ...
