from .i18n import I18n as I18n
from .social_plan_item_detail import SocialPlanItemDetail as SocialPlanItemDetail
from .social_plan_scope import SocialPlanScope as SocialPlanScope
from lark_oapi.core.construct import init as init

class SocialPlan:
    plan_id: str | None
    plan_tid: str | None
    name: I18n | None
    effective_date: str | None
    active: bool | None
    insurance_type: str | None
    scope: SocialPlanScope | None
    item_detail: list[SocialPlanItemDetail] | None
    remark: I18n | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SocialPlanBuilder: ...

class SocialPlanBuilder:
    def __init__(self) -> None: ...
    def plan_id(self, plan_id: str) -> SocialPlanBuilder: ...
    def plan_tid(self, plan_tid: str) -> SocialPlanBuilder: ...
    def name(self, name: I18n) -> SocialPlanBuilder: ...
    def effective_date(self, effective_date: str) -> SocialPlanBuilder: ...
    def active(self, active: bool) -> SocialPlanBuilder: ...
    def insurance_type(self, insurance_type: str) -> SocialPlanBuilder: ...
    def scope(self, scope: SocialPlanScope) -> SocialPlanBuilder: ...
    def item_detail(self, item_detail: list[SocialPlanItemDetail]) -> SocialPlanBuilder: ...
    def remark(self, remark: I18n) -> SocialPlanBuilder: ...
    def build(self) -> SocialPlan: ...
