from lark_oapi.core.construct import init as init

class SocialPlanItemSetting:
    lower_limit: str | None
    upper_limit: str | None
    payment_ratio: str | None
    payment_rounding_rule: str | None
    payment_decimals: int | None
    fixed_payment: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SocialPlanItemSettingBuilder: ...

class SocialPlanItemSettingBuilder:
    def __init__(self) -> None: ...
    def lower_limit(self, lower_limit: str) -> SocialPlanItemSettingBuilder: ...
    def upper_limit(self, upper_limit: str) -> SocialPlanItemSettingBuilder: ...
    def payment_ratio(self, payment_ratio: str) -> SocialPlanItemSettingBuilder: ...
    def payment_rounding_rule(self, payment_rounding_rule: str) -> SocialPlanItemSettingBuilder: ...
    def payment_decimals(self, payment_decimals: int) -> SocialPlanItemSettingBuilder: ...
    def fixed_payment(self, fixed_payment: str) -> SocialPlanItemSettingBuilder: ...
    def build(self) -> SocialPlanItemSetting: ...
