from .social_archive_detail import SocialArchiveDetail as SocialArchiveDetail
from lark_oapi.core.construct import init as init

class SocialArchive:
    user_id: str | None
    details: list[SocialArchiveDetail] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SocialArchiveBuilder: ...

class SocialArchiveBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: str) -> SocialArchiveBuilder: ...
    def details(self, details: list[SocialArchiveDetail]) -> SocialArchiveBuilder: ...
    def build(self) -> SocialArchive: ...
