from lark_oapi.core.construct import init as init

class StandardReferenceObject:
    id: str | None
    api_name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> StandardReferenceObjectBuilder: ...

class StandardReferenceObjectBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> StandardReferenceObjectBuilder: ...
    def api_name(self, api_name: str) -> StandardReferenceObjectBuilder: ...
    def build(self) -> StandardReferenceObject: ...
