from .model.p2_im_chat_access_event_bot_p2p_chat_entered_v1 import P2ImChatAccessEventBotP2pChatEnteredV1 as P2ImChatAccessEventBotP2pChatEnteredV1
from .model.p2_im_chat_disbanded_v1 import P2ImChatDisbandedV1 as P2ImChatDisbandedV1
from .model.p2_im_chat_member_bot_added_v1 import P2ImChatMemberBotAddedV1 as P2ImChatMemberBotAddedV1
from .model.p2_im_chat_member_bot_deleted_v1 import P2ImChatMemberBotDeletedV1 as P2ImChatMemberBotDeletedV1
from .model.p2_im_chat_member_user_added_v1 import P2ImChatMemberUserAddedV1 as P2ImChatMemberUserAddedV1
from .model.p2_im_chat_member_user_deleted_v1 import P2ImChatMemberUserDeletedV1 as P2ImChatMemberUserDeletedV1
from .model.p2_im_chat_member_user_withdrawn_v1 import P2ImChatMemberUserWithdrawnV1 as P2ImChatMemberUserWithdrawnV1
from .model.p2_im_chat_updated_v1 import P2ImChatUpdatedV1 as P2ImChatUpdatedV1
from .model.p2_im_message_message_read_v1 import P2ImMessageMessageReadV1 as P2ImMessageMessageReadV1
from .model.p2_im_message_reaction_created_v1 import P2ImMessageReactionCreatedV1 as P2ImMessageReactionCreatedV1
from .model.p2_im_message_reaction_deleted_v1 import P2ImMessageReactionDeletedV1 as P2ImMessageReactionDeletedV1
from .model.p2_im_message_recalled_v1 import P2ImMessageRecalledV1 as P2ImMessageRecalledV1
from .model.p2_im_message_receive_v1 import P2ImMessageReceiveV1 as P2ImMessageReceiveV1
from _typeshed import Incomplete
from lark_oapi.event.processor import IEventProcessor as IEventProcessor
from typing import Callable

class P2ImChatDisbandedV1Processor(IEventProcessor[P2ImChatDisbandedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ImChatDisbandedV1], None]) -> None: ...
    def type(self) -> type[P2ImChatDisbandedV1]: ...
    def do(self, data: P2ImChatDisbandedV1) -> None: ...

class P2ImChatUpdatedV1Processor(IEventProcessor[P2ImChatUpdatedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ImChatUpdatedV1], None]) -> None: ...
    def type(self) -> type[P2ImChatUpdatedV1]: ...
    def do(self, data: P2ImChatUpdatedV1) -> None: ...

class P2ImChatAccessEventBotP2pChatEnteredV1Processor(IEventProcessor[P2ImChatAccessEventBotP2pChatEnteredV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ImChatAccessEventBotP2pChatEnteredV1], None]) -> None: ...
    def type(self) -> type[P2ImChatAccessEventBotP2pChatEnteredV1]: ...
    def do(self, data: P2ImChatAccessEventBotP2pChatEnteredV1) -> None: ...

class P2ImChatMemberBotAddedV1Processor(IEventProcessor[P2ImChatMemberBotAddedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ImChatMemberBotAddedV1], None]) -> None: ...
    def type(self) -> type[P2ImChatMemberBotAddedV1]: ...
    def do(self, data: P2ImChatMemberBotAddedV1) -> None: ...

class P2ImChatMemberBotDeletedV1Processor(IEventProcessor[P2ImChatMemberBotDeletedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ImChatMemberBotDeletedV1], None]) -> None: ...
    def type(self) -> type[P2ImChatMemberBotDeletedV1]: ...
    def do(self, data: P2ImChatMemberBotDeletedV1) -> None: ...

class P2ImChatMemberUserAddedV1Processor(IEventProcessor[P2ImChatMemberUserAddedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ImChatMemberUserAddedV1], None]) -> None: ...
    def type(self) -> type[P2ImChatMemberUserAddedV1]: ...
    def do(self, data: P2ImChatMemberUserAddedV1) -> None: ...

class P2ImChatMemberUserDeletedV1Processor(IEventProcessor[P2ImChatMemberUserDeletedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ImChatMemberUserDeletedV1], None]) -> None: ...
    def type(self) -> type[P2ImChatMemberUserDeletedV1]: ...
    def do(self, data: P2ImChatMemberUserDeletedV1) -> None: ...

class P2ImChatMemberUserWithdrawnV1Processor(IEventProcessor[P2ImChatMemberUserWithdrawnV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ImChatMemberUserWithdrawnV1], None]) -> None: ...
    def type(self) -> type[P2ImChatMemberUserWithdrawnV1]: ...
    def do(self, data: P2ImChatMemberUserWithdrawnV1) -> None: ...

class P2ImMessageMessageReadV1Processor(IEventProcessor[P2ImMessageMessageReadV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ImMessageMessageReadV1], None]) -> None: ...
    def type(self) -> type[P2ImMessageMessageReadV1]: ...
    def do(self, data: P2ImMessageMessageReadV1) -> None: ...

class P2ImMessageRecalledV1Processor(IEventProcessor[P2ImMessageRecalledV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ImMessageRecalledV1], None]) -> None: ...
    def type(self) -> type[P2ImMessageRecalledV1]: ...
    def do(self, data: P2ImMessageRecalledV1) -> None: ...

class P2ImMessageReceiveV1Processor(IEventProcessor[P2ImMessageReceiveV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ImMessageReceiveV1], None]) -> None: ...
    def type(self) -> type[P2ImMessageReceiveV1]: ...
    def do(self, data: P2ImMessageReceiveV1) -> None: ...

class P2ImMessageReactionCreatedV1Processor(IEventProcessor[P2ImMessageReactionCreatedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ImMessageReactionCreatedV1], None]) -> None: ...
    def type(self) -> type[P2ImMessageReactionCreatedV1]: ...
    def do(self, data: P2ImMessageReactionCreatedV1) -> None: ...

class P2ImMessageReactionDeletedV1Processor(IEventProcessor[P2ImMessageReactionDeletedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ImMessageReactionDeletedV1], None]) -> None: ...
    def type(self) -> type[P2ImMessageReactionDeletedV1]: ...
    def do(self, data: P2ImMessageReactionDeletedV1) -> None: ...
