from .role import Role as Role
from lark_oapi.core.construct import init as init

class CreateAppRoleResponseBody:
    role: Role | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateAppRoleResponseBodyBuilder: ...

class CreateAppRoleResponseBodyBuilder:
    def __init__(self) -> None: ...
    def role(self, role: Role) -> CreateAppRoleResponseBodyBuilder: ...
    def build(self) -> CreateAppRoleResponseBody: ...
