from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListAppRoleRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    app_token: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListAppRoleRequestBuilder: ...

class ListAppRoleRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> ListAppRoleRequestBuilder: ...
    def page_token(self, page_token: str) -> ListAppRoleRequestBuilder: ...
    def app_token(self, app_token: str) -> ListAppRoleRequestBuilder: ...
    def build(self) -> ListAppRoleRequest: ...
