from .rec_rule_condition import RecRuleCondition as RecRuleCondition
from lark_oapi.core.construct import init as init

class OtherRecRule:
    conditions: list[RecRuleCondition] | None
    conjunction: str | None
    perm: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OtherRecRuleBuilder: ...

class OtherRecRuleBuilder:
    def __init__(self) -> None: ...
    def conditions(self, conditions: list[RecRuleCondition]) -> OtherRecRuleBuilder: ...
    def conjunction(self, conjunction: str) -> OtherRecRuleBuilder: ...
    def perm(self, perm: int) -> OtherRecRuleBuilder: ...
    def build(self) -> OtherRecRule: ...
