from lark_oapi.core.construct import init as init

class RecRuleCondition:
    field_name: str | None
    operator: str | None
    value: list[str] | None
    field_type: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RecRuleConditionBuilder: ...

class RecRuleConditionBuilder:
    def __init__(self) -> None: ...
    def field_name(self, field_name: str) -> RecRuleConditionBuilder: ...
    def operator(self, operator: str) -> RecRuleConditionBuilder: ...
    def value(self, value: list[str]) -> RecRuleConditionBuilder: ...
    def field_type(self, field_type: int) -> RecRuleConditionBuilder: ...
    def build(self) -> RecRuleCondition: ...
