from lark_oapi.core.construct import init as init

class TemplateInfo:
    template_type: int | None
    publish_flag: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TemplateInfoBuilder: ...

class TemplateInfoBuilder:
    def __init__(self) -> None: ...
    def template_type(self, template_type: int) -> TemplateInfoBuilder: ...
    def publish_flag(self, publish_flag: int) -> TemplateInfoBuilder: ...
    def build(self) -> TemplateInfo: ...
