from .role import Role as Role
from lark_oapi.core.construct import init as init

class UpdateAppRoleResponseBody:
    role: Role | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateAppRoleResponseBodyBuilder: ...

class UpdateAppRoleResponseBodyBuilder:
    def __init__(self) -> None: ...
    def role(self, role: Role) -> UpdateAppRoleResponseBodyBuilder: ...
    def build(self) -> UpdateAppRoleResponseBody: ...
