from lark_oapi.core.construct import init as init

class CreateVisitorResponseBody:
    visitor_id: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateVisitorResponseBodyBuilder: ...

class CreateVisitorResponseBodyBuilder:
    def __init__(self) -> None: ...
    def visitor_id(self, visitor_id: int) -> CreateVisitorResponseBodyBuilder: ...
    def build(self) -> CreateVisitorResponseBody: ...
