from .rule import Rule as Rule
from lark_oapi.core.construct import init as init

class CreateRuleExternalRequestBody:
    rule: Rule | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateRuleExternalRequestBodyBuilder: ...

class CreateRuleExternalRequestBodyBuilder:
    def __init__(self) -> None: ...
    def rule(self, rule: Rule) -> CreateRuleExternalRequestBodyBuilder: ...
    def build(self) -> CreateRuleExternalRequestBody: ...
