from .user_external import UserExternal as UserExternal
from lark_oapi.core.construct import init as init

class CreateVisitorRequestBody:
    user: UserExternal | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateVisitorRequestBodyBuilder: ...

class CreateVisitorRequestBodyBuilder:
    def __init__(self) -> None: ...
    def user(self, user: UserExternal) -> CreateVisitorRequestBodyBuilder: ...
    def build(self) -> CreateVisitorRequestBody: ...
