from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteVisitorRequest(BaseRequest):
    user_id_type: str | None
    visitor_id: int | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteVisitorRequestBuilder: ...

class DeleteVisitorRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> DeleteVisitorRequestBuilder: ...
    def visitor_id(self, visitor_id: int) -> DeleteVisitorRequestBuilder: ...
    def build(self) -> DeleteVisitorRequest: ...
