from .device_bind_rule_external_request_body import DeviceBindRuleExternalRequestBody as DeviceBindRuleExternalRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeviceBindRuleExternalRequest(BaseRequest):
    request_body: DeviceBindRuleExternalRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeviceBindRuleExternalRequestBuilder: ...

class DeviceBindRuleExternalRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: DeviceBindRuleExternalRequestBody) -> DeviceBindRuleExternalRequestBuilder: ...
    def build(self) -> DeviceBindRuleExternalRequest: ...
