from lark_oapi.core.construct import init as init

class Feature:
    card: int | None
    face_uploaded: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FeatureBuilder: ...

class FeatureBuilder:
    def __init__(self) -> None: ...
    def card(self, card: int) -> FeatureBuilder: ...
    def face_uploaded(self, face_uploaded: bool) -> FeatureBuilder: ...
    def build(self) -> Feature: ...
