from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetUserFaceRequest(BaseRequest):
    is_cropped: bool | None
    user_id_type: str | None
    user_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetUserFaceRequestBuilder: ...

class GetUserFaceRequestBuilder:
    def __init__(self) -> None: ...
    def is_cropped(self, is_cropped: bool) -> GetUserFaceRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> GetUserFaceRequestBuilder: ...
    def user_id(self, user_id: str) -> GetUserFaceRequestBuilder: ...
    def build(self) -> GetUserFaceRequest: ...
