from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetAccessRecordAccessPhotoRequest(BaseRequest):
    access_record_id: int | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetAccessRecordAccessPhotoRequestBuilder: ...

class GetAccessRecordAccessPhotoRequestBuilder:
    def __init__(self) -> None: ...
    def access_record_id(self, access_record_id: int) -> GetAccessRecordAccessPhotoRequestBuilder: ...
    def build(self) -> GetAccessRecordAccessPhotoRequest: ...
