from lark_oapi.core.construct import init as init

class GetUserFaceResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetUserFaceResponseBodyBuilder: ...

class GetUserFaceResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetUserFaceResponseBody: ...
