from .opening_time_period_external import OpeningTimePeriodExternal as OpeningTimePeriodExternal
from .opening_time_valid_day_external import OpeningTimeValidDayExternal as OpeningTimeValidDayExternal
from lark_oapi.core.construct import init as init

class OpeningTimeExternal:
    valid_day: OpeningTimeValidDayExternal | None
    weekdays: list[int] | None
    day_times: list[OpeningTimePeriodExternal] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OpeningTimeExternalBuilder: ...

class OpeningTimeExternalBuilder:
    def __init__(self) -> None: ...
    def valid_day(self, valid_day: OpeningTimeValidDayExternal) -> OpeningTimeExternalBuilder: ...
    def weekdays(self, weekdays: list[int]) -> OpeningTimeExternalBuilder: ...
    def day_times(self, day_times: list[OpeningTimePeriodExternal]) -> OpeningTimeExternalBuilder: ...
    def build(self) -> OpeningTimeExternal: ...
