from lark_oapi.core.construct import init as init

class PatchUserResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchUserResponseBodyBuilder: ...

class PatchUserResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> PatchUserResponseBody: ...
