from lark_oapi.core.construct import init as init

class Property:
    version: str | None
    current_device_face_count: int | None
    max_face_capacity: int | None
    online_status: int | None
    device_name: str | None
    is_clock_in: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PropertyBuilder: ...

class PropertyBuilder:
    def __init__(self) -> None: ...
    def version(self, version: str) -> PropertyBuilder: ...
    def current_device_face_count(self, current_device_face_count: int) -> PropertyBuilder: ...
    def max_face_capacity(self, max_face_capacity: int) -> PropertyBuilder: ...
    def online_status(self, online_status: int) -> PropertyBuilder: ...
    def device_name(self, device_name: str) -> PropertyBuilder: ...
    def is_clock_in(self, is_clock_in: bool) -> PropertyBuilder: ...
    def build(self) -> Property: ...
