from .file import File as File
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UpdateUserFaceRequest(BaseRequest):
    user_id_type: str | None
    user_id: str | None
    request_body: File | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UpdateUserFaceRequestBuilder: ...

class UpdateUserFaceRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> UpdateUserFaceRequestBuilder: ...
    def user_id(self, user_id: str) -> UpdateUserFaceRequestBuilder: ...
    def request_body(self, request_body: File) -> UpdateUserFaceRequestBuilder: ...
    def build(self) -> UpdateUserFaceRequest: ...
