from .add_assignee_approval_task_request_body import AddAssigneeApprovalTaskRequestBody as AddAssigneeApprovalTaskRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class AddAssigneeApprovalTaskRequest(BaseRequest):
    approval_task_id: str | None
    request_body: AddAssigneeApprovalTaskRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> AddAssigneeApprovalTaskRequestBuilder: ...

class AddAssigneeApprovalTaskRequestBuilder:
    def __init__(self) -> None: ...
    def approval_task_id(self, approval_task_id: str) -> AddAssigneeApprovalTaskRequestBuilder: ...
    def request_body(self, request_body: AddAssigneeApprovalTaskRequestBody) -> AddAssigneeApprovalTaskRequestBuilder: ...
    def build(self) -> AddAssigneeApprovalTaskRequest: ...
