from lark_oapi.core.construct import init as init

class AddAssigneeApprovalTaskRequestBody:
    user_id: str | None
    approvers: list[int] | None
    add_assignee_type: str | None
    opinion: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AddAssigneeApprovalTaskRequestBodyBuilder: ...

class AddAssigneeApprovalTaskRequestBodyBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: str) -> AddAssigneeApprovalTaskRequestBodyBuilder: ...
    def approvers(self, approvers: list[int]) -> AddAssigneeApprovalTaskRequestBodyBuilder: ...
    def add_assignee_type(self, add_assignee_type: str) -> AddAssigneeApprovalTaskRequestBodyBuilder: ...
    def opinion(self, opinion: str) -> AddAssigneeApprovalTaskRequestBodyBuilder: ...
    def build(self) -> AddAssigneeApprovalTaskRequestBody: ...
