from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class AllowedRollbaclkTaskItemType:
    id: str | None
    activity_label: list[I18n] | None
    is_start: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AllowedRollbaclkTaskItemTypeBuilder: ...

class AllowedRollbaclkTaskItemTypeBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> AllowedRollbaclkTaskItemTypeBuilder: ...
    def activity_label(self, activity_label: list[I18n]) -> AllowedRollbaclkTaskItemTypeBuilder: ...
    def is_start(self, is_start: bool) -> AllowedRollbaclkTaskItemTypeBuilder: ...
    def build(self) -> AllowedRollbaclkTaskItemType: ...
