from lark_oapi.core.construct import init as init

class AppEnv:
    dev_id: str | None
    test_id: str | None
    prod_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppEnvBuilder: ...

class AppEnvBuilder:
    def __init__(self) -> None: ...
    def dev_id(self, dev_id: str) -> AppEnvBuilder: ...
    def test_id(self, test_id: str) -> AppEnvBuilder: ...
    def prod_id(self, prod_id: str) -> AppEnvBuilder: ...
    def build(self) -> AppEnv: ...
