from lark_oapi.core.construct import init as init

class ApprovalTask:
    id: str | None
    task_status: str | None
    task_start_time: str | None
    task_end_time: str | None
    form_data: str | None
    approval_logic: str | None
    approvers: list[str] | None
    assigners: list[str] | None
    task_url: str | None
    task_type: str | None
    free_cc_record: str | None
    add_assignee_record: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApprovalTaskBuilder: ...

class ApprovalTaskBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> ApprovalTaskBuilder: ...
    def task_status(self, task_status: str) -> ApprovalTaskBuilder: ...
    def task_start_time(self, task_start_time: str) -> ApprovalTaskBuilder: ...
    def task_end_time(self, task_end_time: str) -> ApprovalTaskBuilder: ...
    def form_data(self, form_data: str) -> ApprovalTaskBuilder: ...
    def approval_logic(self, approval_logic: str) -> ApprovalTaskBuilder: ...
    def approvers(self, approvers: list[str]) -> ApprovalTaskBuilder: ...
    def assigners(self, assigners: list[str]) -> ApprovalTaskBuilder: ...
    def task_url(self, task_url: str) -> ApprovalTaskBuilder: ...
    def task_type(self, task_type: str) -> ApprovalTaskBuilder: ...
    def free_cc_record(self, free_cc_record: str) -> ApprovalTaskBuilder: ...
    def add_assignee_record(self, add_assignee_record: str) -> ApprovalTaskBuilder: ...
    def build(self) -> ApprovalTask: ...
