from .audit_log_device_info import AuditLogDeviceInfo as AuditLogDeviceInfo
from .audit_log_login_info import AuditLogLoginInfo as AuditLogLoginInfo
from .audit_log_net_info import AuditLogNetInfo as AuditLogNetInfo
from .audit_log_op_info import AuditLogOpInfo as AuditLogOpInfo
from .basic_info import BasicInfo as BasicInfo
from lark_oapi.core.construct import init as init

class AuditLogDetail:
    log_id: str | None
    basic_info: BasicInfo | None
    op_info: AuditLogOpInfo | None
    login_info: AuditLogLoginInfo | None
    device_info: AuditLogDeviceInfo | None
    net_info: AuditLogNetInfo | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AuditLogDetailBuilder: ...

class AuditLogDetailBuilder:
    def __init__(self) -> None: ...
    def log_id(self, log_id: str) -> AuditLogDetailBuilder: ...
    def basic_info(self, basic_info: BasicInfo) -> AuditLogDetailBuilder: ...
    def op_info(self, op_info: AuditLogOpInfo) -> AuditLogDetailBuilder: ...
    def login_info(self, login_info: AuditLogLoginInfo) -> AuditLogDetailBuilder: ...
    def device_info(self, device_info: AuditLogDeviceInfo) -> AuditLogDetailBuilder: ...
    def net_info(self, net_info: AuditLogNetInfo) -> AuditLogDetailBuilder: ...
    def build(self) -> AuditLogDetail: ...
