from lark_oapi.core.construct import init as init

class AuditLogLoginInfo:
    login_type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AuditLogLoginInfoBuilder: ...

class AuditLogLoginInfoBuilder:
    def __init__(self) -> None: ...
    def login_type(self, login_type: str) -> AuditLogLoginInfoBuilder: ...
    def build(self) -> AuditLogLoginInfo: ...
