from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class Avatar:
    source: str | None
    color: str | None
    contents: list[I18n] | None
    color_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AvatarBuilder: ...

class AvatarBuilder:
    def __init__(self) -> None: ...
    def source(self, source: str) -> AvatarBuilder: ...
    def color(self, color: str) -> AvatarBuilder: ...
    def contents(self, contents: list[I18n]) -> AvatarBuilder: ...
    def color_id(self, color_id: str) -> AvatarBuilder: ...
    def build(self) -> Avatar: ...
