from .batch_query_application_object_record_request_body import BatchQueryApplicationObjectRecordRequestBody as BatchQueryApplicationObjectRecordRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchQueryApplicationObjectRecordRequest(BaseRequest):
    namespace: str | None
    object_api_name: str | None
    request_body: BatchQueryApplicationObjectRecordRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchQueryApplicationObjectRecordRequestBuilder: ...

class BatchQueryApplicationObjectRecordRequestBuilder:
    def __init__(self) -> None: ...
    def namespace(self, namespace: str) -> BatchQueryApplicationObjectRecordRequestBuilder: ...
    def object_api_name(self, object_api_name: str) -> BatchQueryApplicationObjectRecordRequestBuilder: ...
    def request_body(self, request_body: BatchQueryApplicationObjectRecordRequestBody) -> BatchQueryApplicationObjectRecordRequestBuilder: ...
    def build(self) -> BatchQueryApplicationObjectRecordRequest: ...
