from lark_oapi.core.construct import init as init

class BatchCreateAuthorizationApplicationRecordPermissionMemberRequestBody:
    user_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchCreateAuthorizationApplicationRecordPermissionMemberRequestBodyBuilder: ...

class BatchCreateAuthorizationApplicationRecordPermissionMemberRequestBodyBuilder:
    def __init__(self) -> None: ...
    def user_ids(self, user_ids: list[str]) -> BatchCreateAuthorizationApplicationRecordPermissionMemberRequestBodyBuilder: ...
    def build(self) -> BatchCreateAuthorizationApplicationRecordPermissionMemberRequestBody: ...
