from lark_oapi.core.construct import init as init

class BatchCreateApplicationObjectRecordRequestBody:
    records: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchCreateApplicationObjectRecordRequestBodyBuilder: ...

class BatchCreateApplicationObjectRecordRequestBodyBuilder:
    def __init__(self) -> None: ...
    def records(self, records: str) -> BatchCreateApplicationObjectRecordRequestBodyBuilder: ...
    def build(self) -> BatchCreateApplicationObjectRecordRequestBody: ...
