from .batch_create_authorization_application_record_permission_member_request_body import BatchCreateAuthorizationApplicationRecordPermissionMemberRequestBody as BatchCreateAuthorizationApplicationRecordPermissionMemberRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchCreateAuthorizationApplicationRecordPermissionMemberRequest(BaseRequest):
    namespace: str | None
    record_permission_api_name: str | None
    request_body: BatchCreateAuthorizationApplicationRecordPermissionMemberRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchCreateAuthorizationApplicationRecordPermissionMemberRequestBuilder: ...

class BatchCreateAuthorizationApplicationRecordPermissionMemberRequestBuilder:
    def __init__(self) -> None: ...
    def namespace(self, namespace: str) -> BatchCreateAuthorizationApplicationRecordPermissionMemberRequestBuilder: ...
    def record_permission_api_name(self, record_permission_api_name: str) -> BatchCreateAuthorizationApplicationRecordPermissionMemberRequestBuilder: ...
    def request_body(self, request_body: BatchCreateAuthorizationApplicationRecordPermissionMemberRequestBody) -> BatchCreateAuthorizationApplicationRecordPermissionMemberRequestBuilder: ...
    def build(self) -> BatchCreateAuthorizationApplicationRecordPermissionMemberRequest: ...
