from .batch_create_authorization_application_role_member_request_body import BatchCreateAuthorizationApplicationRoleMemberRequestBody as BatchCreateAuthorizationApplicationRoleMemberRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchCreateAuthorizationApplicationRoleMemberRequest(BaseRequest):
    namespace: str | None
    role_api_name: str | None
    request_body: BatchCreateAuthorizationApplicationRoleMemberRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchCreateAuthorizationApplicationRoleMemberRequestBuilder: ...

class BatchCreateAuthorizationApplicationRoleMemberRequestBuilder:
    def __init__(self) -> None: ...
    def namespace(self, namespace: str) -> BatchCreateAuthorizationApplicationRoleMemberRequestBuilder: ...
    def role_api_name(self, role_api_name: str) -> BatchCreateAuthorizationApplicationRoleMemberRequestBuilder: ...
    def request_body(self, request_body: BatchCreateAuthorizationApplicationRoleMemberRequestBody) -> BatchCreateAuthorizationApplicationRoleMemberRequestBuilder: ...
    def build(self) -> BatchCreateAuthorizationApplicationRoleMemberRequest: ...
