from .cancel_approval_instance_request_body import CancelApprovalInstanceRequestBody as CancelApprovalInstanceRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CancelApprovalInstanceRequest(BaseRequest):
    approval_instance_id: str | None
    request_body: CancelApprovalInstanceRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CancelApprovalInstanceRequestBuilder: ...

class CancelApprovalInstanceRequestBuilder:
    def __init__(self) -> None: ...
    def approval_instance_id(self, approval_instance_id: str) -> CancelApprovalInstanceRequestBuilder: ...
    def request_body(self, request_body: CancelApprovalInstanceRequestBody) -> CancelApprovalInstanceRequestBuilder: ...
    def build(self) -> CancelApprovalInstanceRequest: ...
