from lark_oapi.core.construct import init as init

class ConditionValue:
    type: str | None
    settings: str | None
    display_names: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ConditionValueBuilder: ...

class ConditionValueBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> ConditionValueBuilder: ...
    def settings(self, settings: str) -> ConditionValueBuilder: ...
    def display_names(self, display_names: list[str]) -> ConditionValueBuilder: ...
    def build(self) -> ConditionValue: ...
