from lark_oapi.core.construct import init as init

class CreateApplicationObjectRecordRequestBody:
    record: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateApplicationObjectRecordRequestBodyBuilder: ...

class CreateApplicationObjectRecordRequestBodyBuilder:
    def __init__(self) -> None: ...
    def record(self, record: str) -> CreateApplicationObjectRecordRequestBodyBuilder: ...
    def build(self) -> CreateApplicationObjectRecordRequestBody: ...
