from .create_application_object_record_request_body import CreateApplicationObjectRecordRequestBody as CreateApplicationObjectRecordRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateApplicationObjectRecordRequest(BaseRequest):
    namespace: str | None
    object_api_name: str | None
    request_body: CreateApplicationObjectRecordRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateApplicationObjectRecordRequestBuilder: ...

class CreateApplicationObjectRecordRequestBuilder:
    def __init__(self) -> None: ...
    def namespace(self, namespace: str) -> CreateApplicationObjectRecordRequestBuilder: ...
    def object_api_name(self, object_api_name: str) -> CreateApplicationObjectRecordRequestBuilder: ...
    def request_body(self, request_body: CreateApplicationObjectRecordRequestBody) -> CreateApplicationObjectRecordRequestBuilder: ...
    def build(self) -> CreateApplicationObjectRecordRequest: ...
