from .condition import Condition as Condition
from lark_oapi.core.construct import init as init

class Criterion:
    conditions: list[Condition] | None
    logic_expression: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CriterionBuilder: ...

class CriterionBuilder:
    def __init__(self) -> None: ...
    def conditions(self, conditions: list[Condition]) -> CriterionBuilder: ...
    def logic_expression(self, logic_expression: str) -> CriterionBuilder: ...
    def build(self) -> Criterion: ...
