from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DataChangeLogsListApplicationAuditLogRequest(BaseRequest):
    quick_query: str | None
    page_size: str | None
    offset: str | None
    from_: str | None
    to: str | None
    log_type: str | None
    filter: str | None
    columns: list[str] | None
    sort_by: str | None
    sort_order: str | None
    app_type: str | None
    namespace: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DataChangeLogsListApplicationAuditLogRequestBuilder: ...

class DataChangeLogsListApplicationAuditLogRequestBuilder:
    def __init__(self) -> None: ...
    def quick_query(self, quick_query: str) -> DataChangeLogsListApplicationAuditLogRequestBuilder: ...
    def page_size(self, page_size: str) -> DataChangeLogsListApplicationAuditLogRequestBuilder: ...
    def offset(self, offset: str) -> DataChangeLogsListApplicationAuditLogRequestBuilder: ...
    def from_(self, from_: str) -> DataChangeLogsListApplicationAuditLogRequestBuilder: ...
    def to(self, to: str) -> DataChangeLogsListApplicationAuditLogRequestBuilder: ...
    def log_type(self, log_type: str) -> DataChangeLogsListApplicationAuditLogRequestBuilder: ...
    def filter(self, filter: str) -> DataChangeLogsListApplicationAuditLogRequestBuilder: ...
    def columns(self, columns: list[str]) -> DataChangeLogsListApplicationAuditLogRequestBuilder: ...
    def sort_by(self, sort_by: str) -> DataChangeLogsListApplicationAuditLogRequestBuilder: ...
    def sort_order(self, sort_order: str) -> DataChangeLogsListApplicationAuditLogRequestBuilder: ...
    def app_type(self, app_type: str) -> DataChangeLogsListApplicationAuditLogRequestBuilder: ...
    def namespace(self, namespace: str) -> DataChangeLogsListApplicationAuditLogRequestBuilder: ...
    def build(self) -> DataChangeLogsListApplicationAuditLogRequest: ...
