from .lookup_with_avatar import LookupWithAvatar as LookupWithAvatar
from lark_oapi.core.construct import init as init

class EventSubscribeRule:
    namespace: str | None
    event_type: str | None
    creator: str | None
    create_time: str | None
    id: str | None
    created_by: LookupWithAvatar | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EventSubscribeRuleBuilder: ...

class EventSubscribeRuleBuilder:
    def __init__(self) -> None: ...
    def namespace(self, namespace: str) -> EventSubscribeRuleBuilder: ...
    def event_type(self, event_type: str) -> EventSubscribeRuleBuilder: ...
    def creator(self, creator: str) -> EventSubscribeRuleBuilder: ...
    def create_time(self, create_time: str) -> EventSubscribeRuleBuilder: ...
    def id(self, id: str) -> EventSubscribeRuleBuilder: ...
    def created_by(self, created_by: LookupWithAvatar) -> EventSubscribeRuleBuilder: ...
    def build(self) -> EventSubscribeRule: ...
