from .execute_application_flow_request_body import ExecuteApplicationFlowRequestBody as ExecuteApplicationFlowRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ExecuteApplicationFlowRequest(BaseRequest):
    namespace: str | None
    flow_id: str | None
    request_body: ExecuteApplicationFlowRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ExecuteApplicationFlowRequestBuilder: ...

class ExecuteApplicationFlowRequestBuilder:
    def __init__(self) -> None: ...
    def namespace(self, namespace: str) -> ExecuteApplicationFlowRequestBuilder: ...
    def flow_id(self, flow_id: str) -> ExecuteApplicationFlowRequestBuilder: ...
    def request_body(self, request_body: ExecuteApplicationFlowRequestBody) -> ExecuteApplicationFlowRequestBuilder: ...
    def build(self) -> ExecuteApplicationFlowRequest: ...
