from lark_oapi.core.construct import init as init

class ExpeditingUserTaskRequestBody:
    operator_user_id: str | None
    expediting_user_ids: list[str] | None
    opinion: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ExpeditingUserTaskRequestBodyBuilder: ...

class ExpeditingUserTaskRequestBodyBuilder:
    def __init__(self) -> None: ...
    def operator_user_id(self, operator_user_id: str) -> ExpeditingUserTaskRequestBodyBuilder: ...
    def expediting_user_ids(self, expediting_user_ids: list[str]) -> ExpeditingUserTaskRequestBodyBuilder: ...
    def opinion(self, opinion: str) -> ExpeditingUserTaskRequestBodyBuilder: ...
    def build(self) -> ExpeditingUserTaskRequestBody: ...
