from lark_oapi.core.construct import init as init
from typing import Any, IO

class File:
    name: str | None
    content: IO[Any] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FileBuilder: ...

class FileBuilder:
    def __init__(self) -> None: ...
    def name(self, name: str) -> FileBuilder: ...
    def content(self, content: IO[Any]) -> FileBuilder: ...
    def build(self) -> File: ...
