from lark_oapi.core.construct import init as init

class Flow:
    api_id: str | None
    api_name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FlowBuilder: ...

class FlowBuilder:
    def __init__(self) -> None: ...
    def api_id(self, api_id: str) -> FlowBuilder: ...
    def api_name(self, api_name: str) -> FlowBuilder: ...
    def build(self) -> Flow: ...
