from lark_oapi.core.construct import init as init

class Function:
    api_name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FunctionBuilder: ...

class FunctionBuilder:
    def __init__(self) -> None: ...
    def api_name(self, api_name: str) -> FunctionBuilder: ...
    def build(self) -> Function: ...
