from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetApplicationRoleMemberRequest(BaseRequest):
    need_display_name: bool | None
    use_api_id: bool | None
    namespace: str | None
    role_api_name: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetApplicationRoleMemberRequestBuilder: ...

class GetApplicationRoleMemberRequestBuilder:
    def __init__(self) -> None: ...
    def need_display_name(self, need_display_name: bool) -> GetApplicationRoleMemberRequestBuilder: ...
    def use_api_id(self, use_api_id: bool) -> GetApplicationRoleMemberRequestBuilder: ...
    def namespace(self, namespace: str) -> GetApplicationRoleMemberRequestBuilder: ...
    def role_api_name(self, role_api_name: str) -> GetApplicationRoleMemberRequestBuilder: ...
    def build(self) -> GetApplicationRoleMemberRequest: ...
