from lark_oapi.core.construct import init as init

class GlobalOptionFilter:
    quick_query: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GlobalOptionFilterBuilder: ...

class GlobalOptionFilterBuilder:
    def __init__(self) -> None: ...
    def quick_query(self, quick_query: str) -> GlobalOptionFilterBuilder: ...
    def build(self) -> GlobalOptionFilter: ...
