from lark_oapi.core.construct import init as init

class InvokeApplicationFunctionRequestBody:
    params: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InvokeApplicationFunctionRequestBodyBuilder: ...

class InvokeApplicationFunctionRequestBodyBuilder:
    def __init__(self) -> None: ...
    def params(self, params: str) -> InvokeApplicationFunctionRequestBodyBuilder: ...
    def build(self) -> InvokeApplicationFunctionRequestBody: ...
