from lark_oapi.core.construct import init as init

class LookupWithAvatar:
    id: str | None
    name: str | None
    tenant_id: str | None
    email: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LookupWithAvatarBuilder: ...

class LookupWithAvatarBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> LookupWithAvatarBuilder: ...
    def name(self, name: str) -> LookupWithAvatarBuilder: ...
    def tenant_id(self, tenant_id: str) -> LookupWithAvatarBuilder: ...
    def email(self, email: str) -> LookupWithAvatarBuilder: ...
    def build(self) -> LookupWithAvatar: ...
