from .label import Label as Label
from .object_fields_for_query import ObjectFieldsForQuery as ObjectFieldsForQuery
from .object_settings_for_query import ObjectSettingsForQuery as ObjectSettingsForQuery
from lark_oapi.core.construct import init as init

class ObjectForQuery:
    api_name: str | None
    label: Label | None
    type: str | None
    settings: ObjectSettingsForQuery | None
    fields: list[ObjectFieldsForQuery] | None
    created_at: int | None
    updated_at: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ObjectForQueryBuilder: ...

class ObjectForQueryBuilder:
    def __init__(self) -> None: ...
    def api_name(self, api_name: str) -> ObjectForQueryBuilder: ...
    def label(self, label: Label) -> ObjectForQueryBuilder: ...
    def type(self, type: str) -> ObjectForQueryBuilder: ...
    def settings(self, settings: ObjectSettingsForQuery) -> ObjectForQueryBuilder: ...
    def fields(self, fields: list[ObjectFieldsForQuery]) -> ObjectForQueryBuilder: ...
    def created_at(self, created_at: int) -> ObjectForQueryBuilder: ...
    def updated_at(self, updated_at: int) -> ObjectForQueryBuilder: ...
    def build(self) -> ObjectForQuery: ...
