from .label import Label as Label
from .object_field_type_for_query import ObjectFieldTypeForQuery as ObjectFieldTypeForQuery
from lark_oapi.core.construct import init as init

class ObjectFieldsForQuery:
    api_name: str | None
    label: Label | None
    type: ObjectFieldTypeForQuery | None
    created_at: int | None
    updated_at: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ObjectFieldsForQueryBuilder: ...

class ObjectFieldsForQueryBuilder:
    def __init__(self) -> None: ...
    def api_name(self, api_name: str) -> ObjectFieldsForQueryBuilder: ...
    def label(self, label: Label) -> ObjectFieldsForQueryBuilder: ...
    def type(self, type: ObjectFieldTypeForQuery) -> ObjectFieldsForQueryBuilder: ...
    def created_at(self, created_at: int) -> ObjectFieldsForQueryBuilder: ...
    def updated_at(self, updated_at: int) -> ObjectFieldsForQueryBuilder: ...
    def build(self) -> ObjectFieldsForQuery: ...
