from .object_search_layout import ObjectSearchLayout as ObjectSearchLayout
from lark_oapi.core.construct import init as init

class ObjectSettings:
    display_name: str | None
    allow_search_fields: list[str] | None
    search_layout: ObjectSearchLayout | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ObjectSettingsBuilder: ...

class ObjectSettingsBuilder:
    def __init__(self) -> None: ...
    def display_name(self, display_name: str) -> ObjectSettingsBuilder: ...
    def allow_search_fields(self, allow_search_fields: list[str]) -> ObjectSettingsBuilder: ...
    def search_layout(self, search_layout: ObjectSearchLayout) -> ObjectSettingsBuilder: ...
    def build(self) -> ObjectSettings: ...
