from lark_oapi.core.construct import init as init

class ObjectFilter:
    quick_query: str | None
    type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ObjectFilterBuilder: ...

class ObjectFilterBuilder:
    def __init__(self) -> None: ...
    def quick_query(self, quick_query: str) -> ObjectFilterBuilder: ...
    def type(self, type: str) -> ObjectFilterBuilder: ...
    def build(self) -> ObjectFilter: ...
