from lark_oapi.core.construct import init as init

class ObjectFieldTypeForQuery:
    name: str | None
    settings: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ObjectFieldTypeForQueryBuilder: ...

class ObjectFieldTypeForQueryBuilder:
    def __init__(self) -> None: ...
    def name(self, name: str) -> ObjectFieldTypeForQueryBuilder: ...
    def settings(self, settings: str) -> ObjectFieldTypeForQueryBuilder: ...
    def build(self) -> ObjectFieldTypeForQuery: ...
