from lark_oapi.core.construct import init as init

class OqlQueryApplicationObjectRequestBody:
    query: str | None
    args: str | None
    named_args: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OqlQueryApplicationObjectRequestBodyBuilder: ...

class OqlQueryApplicationObjectRequestBodyBuilder:
    def __init__(self) -> None: ...
    def query(self, query: str) -> OqlQueryApplicationObjectRequestBodyBuilder: ...
    def args(self, args: str) -> OqlQueryApplicationObjectRequestBodyBuilder: ...
    def named_args(self, named_args: str) -> OqlQueryApplicationObjectRequestBodyBuilder: ...
    def build(self) -> OqlQueryApplicationObjectRequestBody: ...
