from .query_application_environment_variable_request_body import QueryApplicationEnvironmentVariableRequestBody as QueryApplicationEnvironmentVariableRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class QueryApplicationEnvironmentVariableRequest(BaseRequest):
    namespace: str | None
    request_body: QueryApplicationEnvironmentVariableRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> QueryApplicationEnvironmentVariableRequestBuilder: ...

class QueryApplicationEnvironmentVariableRequestBuilder:
    def __init__(self) -> None: ...
    def namespace(self, namespace: str) -> QueryApplicationEnvironmentVariableRequestBuilder: ...
    def request_body(self, request_body: QueryApplicationEnvironmentVariableRequestBody) -> QueryApplicationEnvironmentVariableRequestBuilder: ...
    def build(self) -> QueryApplicationEnvironmentVariableRequest: ...
