from lark_oapi.core.construct import init as init

class QueryApplicationObjectRecordRequestBody:
    select: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryApplicationObjectRecordRequestBodyBuilder: ...

class QueryApplicationObjectRecordRequestBodyBuilder:
    def __init__(self) -> None: ...
    def select(self, select: list[str]) -> QueryApplicationObjectRecordRequestBodyBuilder: ...
    def build(self) -> QueryApplicationObjectRecordRequestBody: ...
