from .rollback_user_task_request_body import RollbackUserTaskRequestBody as RollbackUserTaskRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class RollbackUserTaskRequest(BaseRequest):
    task_id: str | None
    request_body: RollbackUserTaskRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> RollbackUserTaskRequestBuilder: ...

class RollbackUserTaskRequestBuilder:
    def __init__(self) -> None: ...
    def task_id(self, task_id: str) -> RollbackUserTaskRequestBuilder: ...
    def request_body(self, request_body: RollbackUserTaskRequestBody) -> RollbackUserTaskRequestBuilder: ...
    def build(self) -> RollbackUserTaskRequest: ...
