from lark_oapi.core.construct import init as init

class RollbackUserTaskRequestBody:
    operator_user_id: str | None
    to_task_id: str | None
    opinion: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RollbackUserTaskRequestBodyBuilder: ...

class RollbackUserTaskRequestBodyBuilder:
    def __init__(self) -> None: ...
    def operator_user_id(self, operator_user_id: str) -> RollbackUserTaskRequestBodyBuilder: ...
    def to_task_id(self, to_task_id: str) -> RollbackUserTaskRequestBodyBuilder: ...
    def opinion(self, opinion: str) -> RollbackUserTaskRequestBodyBuilder: ...
    def build(self) -> RollbackUserTaskRequestBody: ...
