from lark_oapi.core.construct import init as init

class RollbackPointsUserTaskRequestBody:
    operator_user_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RollbackPointsUserTaskRequestBodyBuilder: ...

class RollbackPointsUserTaskRequestBodyBuilder:
    def __init__(self) -> None: ...
    def operator_user_id(self, operator_user_id: str) -> RollbackPointsUserTaskRequestBodyBuilder: ...
    def build(self) -> RollbackPointsUserTaskRequestBody: ...
