from lark_oapi.core.construct import init as init

class SeatActivity:
    user_id: int | None
    namespace: str | None
    status: str | None
    active_time: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SeatActivityBuilder: ...

class SeatActivityBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: int) -> SeatActivityBuilder: ...
    def namespace(self, namespace: str) -> SeatActivityBuilder: ...
    def status(self, status: str) -> SeatActivityBuilder: ...
    def active_time(self, active_time: int) -> SeatActivityBuilder: ...
    def build(self) -> SeatActivity: ...
