from lark_oapi.core.construct import init as init

class SeatAssignment:
    user_id: int | None
    namespace: str | None
    status: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SeatAssignmentBuilder: ...

class SeatAssignmentBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: int) -> SeatAssignmentBuilder: ...
    def namespace(self, namespace: str) -> SeatAssignmentBuilder: ...
    def status(self, status: str) -> SeatAssignmentBuilder: ...
    def build(self) -> SeatAssignment: ...
