from .transfer_approval_task_request_body import TransferApprovalTaskRequestBody as TransferApprovalTaskRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class TransferApprovalTaskRequest(BaseRequest):
    approval_task_id: str | None
    request_body: TransferApprovalTaskRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> TransferApprovalTaskRequestBuilder: ...

class TransferApprovalTaskRequestBuilder:
    def __init__(self) -> None: ...
    def approval_task_id(self, approval_task_id: str) -> TransferApprovalTaskRequestBuilder: ...
    def request_body(self, request_body: TransferApprovalTaskRequestBody) -> TransferApprovalTaskRequestBuilder: ...
    def build(self) -> TransferApprovalTaskRequest: ...
