from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class UserTaskWfInstanceType:
    id: str | None
    label: list[I18n] | None
    status: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserTaskWfInstanceTypeBuilder: ...

class UserTaskWfInstanceTypeBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> UserTaskWfInstanceTypeBuilder: ...
    def label(self, label: list[I18n]) -> UserTaskWfInstanceTypeBuilder: ...
    def status(self, status: str) -> UserTaskWfInstanceTypeBuilder: ...
    def build(self) -> UserTaskWfInstanceType: ...
