from lark_oapi.core.construct import init as init

class User:
    user_id: str | None
    name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserBuilder: ...

class UserBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: str) -> UserBuilder: ...
    def name(self, name: str) -> UserBuilder: ...
    def build(self) -> User: ...
