from lark_oapi.core.construct import init as init

class UserTaskOpinion:
    content: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserTaskOpinionBuilder: ...

class UserTaskOpinionBuilder:
    def __init__(self) -> None: ...
    def content(self, content: str) -> UserTaskOpinionBuilder: ...
    def build(self) -> UserTaskOpinion: ...
