from .runtime_log import RuntimeLog as RuntimeLog
from lark_oapi.core.construct import init as init

class WorkflowInstanceLog:
    total: str | None
    logs: list[RuntimeLog] | None
    next_keyword_offset: str | None
    total_keyword: str | None
    has_read_auth: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WorkflowInstanceLogBuilder: ...

class WorkflowInstanceLogBuilder:
    def __init__(self) -> None: ...
    def total(self, total: str) -> WorkflowInstanceLogBuilder: ...
    def logs(self, logs: list[RuntimeLog]) -> WorkflowInstanceLogBuilder: ...
    def next_keyword_offset(self, next_keyword_offset: str) -> WorkflowInstanceLogBuilder: ...
    def total_keyword(self, total_keyword: str) -> WorkflowInstanceLogBuilder: ...
    def has_read_auth(self, has_read_auth: bool) -> WorkflowInstanceLogBuilder: ...
    def build(self) -> WorkflowInstanceLog: ...
