from lark_oapi.core.construct import init as init

class Acl:
    access: str | None
    value: str | None
    type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AclBuilder: ...

class AclBuilder:
    def __init__(self) -> None: ...
    def access(self, access: str) -> AclBuilder: ...
    def value(self, value: str) -> AclBuilder: ...
    def type(self, type: str) -> AclBuilder: ...
    def build(self) -> Acl: ...
