from lark_oapi.core.construct import init as init

class CreateAppRequestBody:
    query: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateAppRequestBodyBuilder: ...

class CreateAppRequestBodyBuilder:
    def __init__(self) -> None: ...
    def query(self, query: str) -> CreateAppRequestBodyBuilder: ...
    def build(self) -> CreateAppRequestBody: ...
