from .schema import Schema as Schema
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateSchemaRequest(BaseRequest):
    validate_only: bool | None
    request_body: Schema | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateSchemaRequestBuilder: ...

class CreateSchemaRequestBuilder:
    def __init__(self) -> None: ...
    def validate_only(self, validate_only: bool) -> CreateSchemaRequestBuilder: ...
    def request_body(self, request_body: Schema) -> CreateSchemaRequestBuilder: ...
    def build(self) -> CreateSchemaRequest: ...
