from .item import Item as Item
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateDataSourceItemRequest(BaseRequest):
    data_source_id: str | None
    request_body: Item | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateDataSourceItemRequestBuilder: ...

class CreateDataSourceItemRequestBuilder:
    def __init__(self) -> None: ...
    def data_source_id(self, data_source_id: str) -> CreateDataSourceItemRequestBuilder: ...
    def request_body(self, request_body: Item) -> CreateDataSourceItemRequestBuilder: ...
    def build(self) -> CreateDataSourceItemRequest: ...
