from lark_oapi.core.construct import init as init

class DeleteDataSourceRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteDataSourceRequestBodyBuilder: ...

class DeleteDataSourceRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteDataSourceRequestBody: ...
