from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteDataSourceRequest(BaseRequest):
    data_source_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteDataSourceRequestBuilder: ...

class DeleteDataSourceRequestBuilder:
    def __init__(self) -> None: ...
    def data_source_id(self, data_source_id: str) -> DeleteDataSourceRequestBuilder: ...
    def build(self) -> DeleteDataSourceRequest: ...
