from lark_oapi.core.construct import init as init

class DeleteSchemaResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteSchemaResponseBodyBuilder: ...

class DeleteSchemaResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteSchemaResponseBody: ...
