from .chunk import Chunk as Chunk
from lark_oapi.core.construct import init as init

class Doc:
    doc_id: str | None
    filter_data: str | None
    chunks: list[Chunk] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DocBuilder: ...

class DocBuilder:
    def __init__(self) -> None: ...
    def doc_id(self, doc_id: str) -> DocBuilder: ...
    def filter_data(self, filter_data: str) -> DocBuilder: ...
    def chunks(self, chunks: list[Chunk]) -> DocBuilder: ...
    def build(self) -> Doc: ...
