from .knowledge_source_space_filter import KnowledgeSourceSpaceFilter as KnowledgeSourceSpaceFilter
from .knowledge_source_space_reject import KnowledgeSourceSpaceReject as KnowledgeSourceSpaceReject
from lark_oapi.core.construct import init as init

class EnterpriseKnowledgeSourceSpaceParam:
    searchable: bool | None
    filter: KnowledgeSourceSpaceFilter | None
    reject: KnowledgeSourceSpaceReject | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EnterpriseKnowledgeSourceSpaceParamBuilder: ...

class EnterpriseKnowledgeSourceSpaceParamBuilder:
    def __init__(self) -> None: ...
    def searchable(self, searchable: bool) -> EnterpriseKnowledgeSourceSpaceParamBuilder: ...
    def filter(self, filter: KnowledgeSourceSpaceFilter) -> EnterpriseKnowledgeSourceSpaceParamBuilder: ...
    def reject(self, reject: KnowledgeSourceSpaceReject) -> EnterpriseKnowledgeSourceSpaceParamBuilder: ...
    def build(self) -> EnterpriseKnowledgeSourceSpaceParam: ...
