from .knowledge_source_helpdesk_filter import KnowledgeSourceHelpdeskFilter as KnowledgeSourceHelpdeskFilter
from lark_oapi.core.construct import init as init

class EnterpriseKnowledgeSourceHelpdeskParam:
    searchable: bool | None
    filter: KnowledgeSourceHelpdeskFilter | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EnterpriseKnowledgeSourceHelpdeskParamBuilder: ...

class EnterpriseKnowledgeSourceHelpdeskParamBuilder:
    def __init__(self) -> None: ...
    def searchable(self, searchable: bool) -> EnterpriseKnowledgeSourceHelpdeskParamBuilder: ...
    def filter(self, filter: KnowledgeSourceHelpdeskFilter) -> EnterpriseKnowledgeSourceHelpdeskParamBuilder: ...
    def build(self) -> EnterpriseKnowledgeSourceHelpdeskParam: ...
