from .schema import Schema as Schema
from lark_oapi.core.construct import init as init

class GetSchemaResponseBody:
    schema: Schema | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetSchemaResponseBodyBuilder: ...

class GetSchemaResponseBodyBuilder:
    def __init__(self) -> None: ...
    def schema(self, schema: Schema) -> GetSchemaResponseBodyBuilder: ...
    def build(self) -> GetSchemaResponseBody: ...
