from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetSchemaRequest(BaseRequest):
    schema_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetSchemaRequestBuilder: ...

class GetSchemaRequestBuilder:
    def __init__(self) -> None: ...
    def schema_id(self, schema_id: str) -> GetSchemaRequestBuilder: ...
    def build(self) -> GetSchemaRequest: ...
