from lark_oapi.core.construct import init as init

class GetSchemaRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetSchemaRequestBodyBuilder: ...

class GetSchemaRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetSchemaRequestBody: ...
