from .item import Item as Item
from lark_oapi.core.construct import init as init

class GetDataSourceItemResponseBody:
    item: Item | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetDataSourceItemResponseBodyBuilder: ...

class GetDataSourceItemResponseBodyBuilder:
    def __init__(self) -> None: ...
    def item(self, item: Item) -> GetDataSourceItemResponseBodyBuilder: ...
    def build(self) -> GetDataSourceItemResponseBody: ...
