from lark_oapi.core.construct import init as init

class HelpdeskPassageParam:
    searchable: bool | None
    helpdesk_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> HelpdeskPassageParamBuilder: ...

class HelpdeskPassageParamBuilder:
    def __init__(self) -> None: ...
    def searchable(self, searchable: bool) -> HelpdeskPassageParamBuilder: ...
    def helpdesk_ids(self, helpdesk_ids: list[str]) -> HelpdeskPassageParamBuilder: ...
    def build(self) -> HelpdeskPassageParam: ...
