from lark_oapi.core.construct import init as init

class ItemMetadata:
    title: str | None
    source_url: str | None
    create_time: int | None
    update_time: int | None
    source_url_mobile: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ItemMetadataBuilder: ...

class ItemMetadataBuilder:
    def __init__(self) -> None: ...
    def title(self, title: str) -> ItemMetadataBuilder: ...
    def source_url(self, source_url: str) -> ItemMetadataBuilder: ...
    def create_time(self, create_time: int) -> ItemMetadataBuilder: ...
    def update_time(self, update_time: int) -> ItemMetadataBuilder: ...
    def source_url_mobile(self, source_url_mobile: str) -> ItemMetadataBuilder: ...
    def build(self) -> ItemMetadata: ...
