from lark_oapi.core.construct import init as init

class ItemRecord:
    item_id: str | None
    data_source_id: str | None
    version: str | None
    created_at: str | None
    updated_at: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ItemRecordBuilder: ...

class ItemRecordBuilder:
    def __init__(self) -> None: ...
    def item_id(self, item_id: str) -> ItemRecordBuilder: ...
    def data_source_id(self, data_source_id: str) -> ItemRecordBuilder: ...
    def version(self, version: str) -> ItemRecordBuilder: ...
    def created_at(self, created_at: str) -> ItemRecordBuilder: ...
    def updated_at(self, updated_at: str) -> ItemRecordBuilder: ...
    def build(self) -> ItemRecord: ...
