from lark_oapi.core.construct import init as init

class KnowledgeSourceMessageRejectFilter:
    message_ids: list[str] | None
    chat_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> KnowledgeSourceMessageRejectFilterBuilder: ...

class KnowledgeSourceMessageRejectFilterBuilder:
    def __init__(self) -> None: ...
    def message_ids(self, message_ids: list[str]) -> KnowledgeSourceMessageRejectFilterBuilder: ...
    def chat_ids(self, chat_ids: list[str]) -> KnowledgeSourceMessageRejectFilterBuilder: ...
    def build(self) -> KnowledgeSourceMessageRejectFilter: ...
