from .time_range import TimeRange as TimeRange
from lark_oapi.core.construct import init as init

class KnowledgeSourceMessageFilter:
    chat_ids: list[str] | None
    time_range: TimeRange | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> KnowledgeSourceMessageFilterBuilder: ...

class KnowledgeSourceMessageFilterBuilder:
    def __init__(self) -> None: ...
    def chat_ids(self, chat_ids: list[str]) -> KnowledgeSourceMessageFilterBuilder: ...
    def time_range(self, time_range: TimeRange) -> KnowledgeSourceMessageFilterBuilder: ...
    def build(self) -> KnowledgeSourceMessageFilter: ...
