from .knowledge_qa_reference import KnowledgeQaReference as KnowledgeQaReference
from lark_oapi.core.construct import init as init

class KnowledgeQaAnswerResponse:
    answer: str | None
    reasoning_content: str | None
    status_code: int | None
    status_message: str | None
    references: KnowledgeQaReference | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> KnowledgeQaAnswerResponseBuilder: ...

class KnowledgeQaAnswerResponseBuilder:
    def __init__(self) -> None: ...
    def answer(self, answer: str) -> KnowledgeQaAnswerResponseBuilder: ...
    def reasoning_content(self, reasoning_content: str) -> KnowledgeQaAnswerResponseBuilder: ...
    def status_code(self, status_code: int) -> KnowledgeQaAnswerResponseBuilder: ...
    def status_message(self, status_message: str) -> KnowledgeQaAnswerResponseBuilder: ...
    def references(self, references: KnowledgeQaReference) -> KnowledgeQaAnswerResponseBuilder: ...
    def build(self) -> KnowledgeQaAnswerResponse: ...
