from lark_oapi.core.construct import init as init

class KnowledgeSourceSpaceFilter:
    doc_tokens: list[str] | None
    folder_tokens: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> KnowledgeSourceSpaceFilterBuilder: ...

class KnowledgeSourceSpaceFilterBuilder:
    def __init__(self) -> None: ...
    def doc_tokens(self, doc_tokens: list[str]) -> KnowledgeSourceSpaceFilterBuilder: ...
    def folder_tokens(self, folder_tokens: list[str]) -> KnowledgeSourceSpaceFilterBuilder: ...
    def build(self) -> KnowledgeSourceSpaceFilter: ...
