from .enterprise_knowledge_source_param import EnterpriseKnowledgeSourceParam as EnterpriseKnowledgeSourceParam
from lark_oapi.core.construct import init as init

class KnowledgeQaSearchRequest:
    query: str | None
    enterprise_knowledge_source: EnterpriseKnowledgeSourceParam | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> KnowledgeQaSearchRequestBuilder: ...

class KnowledgeQaSearchRequestBuilder:
    def __init__(self) -> None: ...
    def query(self, query: str) -> KnowledgeQaSearchRequestBuilder: ...
    def enterprise_knowledge_source(self, enterprise_knowledge_source: EnterpriseKnowledgeSourceParam) -> KnowledgeQaSearchRequestBuilder: ...
    def build(self) -> KnowledgeQaSearchRequest: ...
