from lark_oapi.core.construct import init as init

class KnowledgeSourceRequestExtra:
    locale: str | None
    timezone: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> KnowledgeSourceRequestExtraBuilder: ...

class KnowledgeSourceRequestExtraBuilder:
    def __init__(self) -> None: ...
    def locale(self, locale: str) -> KnowledgeSourceRequestExtraBuilder: ...
    def timezone(self, timezone: str) -> KnowledgeSourceRequestExtraBuilder: ...
    def build(self) -> KnowledgeSourceRequestExtra: ...
