from lark_oapi.core.construct import init as init

class KnowledgeSourceHelpdeskFilter:
    helpdesk_ids: list[int] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> KnowledgeSourceHelpdeskFilterBuilder: ...

class KnowledgeSourceHelpdeskFilterBuilder:
    def __init__(self) -> None: ...
    def helpdesk_ids(self, helpdesk_ids: list[int]) -> KnowledgeSourceHelpdeskFilterBuilder: ...
    def build(self) -> KnowledgeSourceHelpdeskFilter: ...
