from lark_oapi.core.construct import init as init

class KnowledgeSourceWikiReject:
    wiki_tokens: list[str] | None
    node_tokens: list[str] | None
    space_ids: list[int] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> KnowledgeSourceWikiRejectBuilder: ...

class KnowledgeSourceWikiRejectBuilder:
    def __init__(self) -> None: ...
    def wiki_tokens(self, wiki_tokens: list[str]) -> KnowledgeSourceWikiRejectBuilder: ...
    def node_tokens(self, node_tokens: list[str]) -> KnowledgeSourceWikiRejectBuilder: ...
    def space_ids(self, space_ids: list[int]) -> KnowledgeSourceWikiRejectBuilder: ...
    def build(self) -> KnowledgeSourceWikiReject: ...
