from lark_oapi.core.construct import init as init

class KnowledgeSourceSpaceReject:
    doc_tokens: list[str] | None
    folder_tokens: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> KnowledgeSourceSpaceRejectBuilder: ...

class KnowledgeSourceSpaceRejectBuilder:
    def __init__(self) -> None: ...
    def doc_tokens(self, doc_tokens: list[str]) -> KnowledgeSourceSpaceRejectBuilder: ...
    def folder_tokens(self, folder_tokens: list[str]) -> KnowledgeSourceSpaceRejectBuilder: ...
    def build(self) -> KnowledgeSourceSpaceReject: ...
