from lark_oapi.core.construct import init as init

class LingoPassageParam:
    searchable: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LingoPassageParamBuilder: ...

class LingoPassageParamBuilder:
    def __init__(self) -> None: ...
    def searchable(self, searchable: bool) -> LingoPassageParamBuilder: ...
    def build(self) -> LingoPassageParam: ...
