from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListDataSourceRequest(BaseRequest):
    view: int | None
    page_size: int | None
    page_token: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListDataSourceRequestBuilder: ...

class ListDataSourceRequestBuilder:
    def __init__(self) -> None: ...
    def view(self, view: int) -> ListDataSourceRequestBuilder: ...
    def page_size(self, page_size: int) -> ListDataSourceRequestBuilder: ...
    def page_token(self, page_token: str) -> ListDataSourceRequestBuilder: ...
    def build(self) -> ListDataSourceRequest: ...
