from lark_oapi.core.construct import init as init

class MessagePassageParam:
    searchable: bool | None
    chat_ids: list[str] | None
    excluded_passage_ids: list[str] | None
    excluded_chat_ids: list[str] | None
    excluded_message_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MessagePassageParamBuilder: ...

class MessagePassageParamBuilder:
    def __init__(self) -> None: ...
    def searchable(self, searchable: bool) -> MessagePassageParamBuilder: ...
    def chat_ids(self, chat_ids: list[str]) -> MessagePassageParamBuilder: ...
    def excluded_passage_ids(self, excluded_passage_ids: list[str]) -> MessagePassageParamBuilder: ...
    def excluded_chat_ids(self, excluded_chat_ids: list[str]) -> MessagePassageParamBuilder: ...
    def excluded_message_ids(self, excluded_message_ids: list[str]) -> MessagePassageParamBuilder: ...
    def build(self) -> MessagePassageParam: ...
