from lark_oapi.core.construct import init as init

class ModelParam:
    encoder_name: str | None
    ranker_name: str | None
    filter_name: str | None
    booster_name: str | None
    passage_language: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ModelParamBuilder: ...

class ModelParamBuilder:
    def __init__(self) -> None: ...
    def encoder_name(self, encoder_name: str) -> ModelParamBuilder: ...
    def ranker_name(self, ranker_name: str) -> ModelParamBuilder: ...
    def filter_name(self, filter_name: str) -> ModelParamBuilder: ...
    def booster_name(self, booster_name: str) -> ModelParamBuilder: ...
    def passage_language(self, passage_language: str) -> ModelParamBuilder: ...
    def build(self) -> ModelParam: ...
