from lark_oapi.core.construct import init as init

class Passage:
    passage_id: str | None
    passage_source: int | None
    content: str | None
    title: str | None
    url: str | None
    score: float | None
    extra: str | None
    content_for_llm: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PassageBuilder: ...

class PassageBuilder:
    def __init__(self) -> None: ...
    def passage_id(self, passage_id: str) -> PassageBuilder: ...
    def passage_source(self, passage_source: int) -> PassageBuilder: ...
    def content(self, content: str) -> PassageBuilder: ...
    def title(self, title: str) -> PassageBuilder: ...
    def url(self, url: str) -> PassageBuilder: ...
    def score(self, score: float) -> PassageBuilder: ...
    def extra(self, extra: str) -> PassageBuilder: ...
    def content_for_llm(self, content_for_llm: str) -> PassageBuilder: ...
    def build(self) -> Passage: ...
