from .data_source import DataSource as DataSource
from lark_oapi.core.construct import init as init

class PatchDataSourceResponseBody:
    data_source: DataSource | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchDataSourceResponseBodyBuilder: ...

class PatchDataSourceResponseBodyBuilder:
    def __init__(self) -> None: ...
    def data_source(self, data_source: DataSource) -> PatchDataSourceResponseBodyBuilder: ...
    def build(self) -> PatchDataSourceResponseBody: ...
