from .schema import Schema as Schema
from lark_oapi.core.construct import init as init

class PatchSchemaResponseBody:
    schema: Schema | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchSchemaResponseBodyBuilder: ...

class PatchSchemaResponseBodyBuilder:
    def __init__(self) -> None: ...
    def schema(self, schema: Schema) -> PatchSchemaResponseBodyBuilder: ...
    def build(self) -> PatchSchemaResponseBody: ...
