from .connector_param import ConnectorParam as ConnectorParam
from .i18n_meta import I18nMeta as I18nMeta
from lark_oapi.core.construct import init as init

class PatchDataSourceRequestBody:
    name: str | None
    state: int | None
    description: str | None
    icon_url: str | None
    i18n_name: I18nMeta | None
    i18n_description: I18nMeta | None
    connector_param: ConnectorParam | None
    enable_answer: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchDataSourceRequestBodyBuilder: ...

class PatchDataSourceRequestBodyBuilder:
    def __init__(self) -> None: ...
    def name(self, name: str) -> PatchDataSourceRequestBodyBuilder: ...
    def state(self, state: int) -> PatchDataSourceRequestBodyBuilder: ...
    def description(self, description: str) -> PatchDataSourceRequestBodyBuilder: ...
    def icon_url(self, icon_url: str) -> PatchDataSourceRequestBodyBuilder: ...
    def i18n_name(self, i18n_name: I18nMeta) -> PatchDataSourceRequestBodyBuilder: ...
    def i18n_description(self, i18n_description: I18nMeta) -> PatchDataSourceRequestBodyBuilder: ...
    def connector_param(self, connector_param: ConnectorParam) -> PatchDataSourceRequestBodyBuilder: ...
    def enable_answer(self, enable_answer: bool) -> PatchDataSourceRequestBodyBuilder: ...
    def build(self) -> PatchDataSourceRequestBody: ...
