from .template_card_variables import TemplateCardVariables as TemplateCardVariables
from lark_oapi.core.construct import init as init

class Present:
    type: str | None
    body: str | None
    operation_type: str | None
    interactable: bool | None
    operation_url: str | None
    callback_url: str | None
    callback_info: str | None
    card_template_id: str | None
    card_variables: TemplateCardVariables | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PresentBuilder: ...

class PresentBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> PresentBuilder: ...
    def body(self, body: str) -> PresentBuilder: ...
    def operation_type(self, operation_type: str) -> PresentBuilder: ...
    def interactable(self, interactable: bool) -> PresentBuilder: ...
    def operation_url(self, operation_url: str) -> PresentBuilder: ...
    def callback_url(self, callback_url: str) -> PresentBuilder: ...
    def callback_info(self, callback_info: str) -> PresentBuilder: ...
    def card_template_id(self, card_template_id: str) -> PresentBuilder: ...
    def card_variables(self, card_variables: TemplateCardVariables) -> PresentBuilder: ...
    def build(self) -> Present: ...
