from .status import Status as Status
from lark_oapi.core.construct import init as init

class PresentDataCallbackDialogRequest:
    message_id: str | None
    status: Status | None
    callback_info: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PresentDataCallbackDialogRequestBuilder: ...

class PresentDataCallbackDialogRequestBuilder:
    def __init__(self) -> None: ...
    def message_id(self, message_id: str) -> PresentDataCallbackDialogRequestBuilder: ...
    def status(self, status: Status) -> PresentDataCallbackDialogRequestBuilder: ...
    def callback_info(self, callback_info: str) -> PresentDataCallbackDialogRequestBuilder: ...
    def build(self) -> PresentDataCallbackDialogRequest: ...
