from lark_oapi.core.construct import init as init

class ScenarioContextExtra:
    grounding_id: str | None
    model_key: str | None
    specified_obj_ids: str | None
    suggest_query_id: str | None
    button_send_message_info: str | None
    button_regenerate_message: str | None
    enterprise_qa_channel_info: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ScenarioContextExtraBuilder: ...

class ScenarioContextExtraBuilder:
    def __init__(self) -> None: ...
    def grounding_id(self, grounding_id: str) -> ScenarioContextExtraBuilder: ...
    def model_key(self, model_key: str) -> ScenarioContextExtraBuilder: ...
    def specified_obj_ids(self, specified_obj_ids: str) -> ScenarioContextExtraBuilder: ...
    def suggest_query_id(self, suggest_query_id: str) -> ScenarioContextExtraBuilder: ...
    def button_send_message_info(self, button_send_message_info: str) -> ScenarioContextExtraBuilder: ...
    def button_regenerate_message(self, button_regenerate_message: str) -> ScenarioContextExtraBuilder: ...
    def enterprise_qa_channel_info(self, enterprise_qa_channel_info: str) -> ScenarioContextExtraBuilder: ...
    def build(self) -> ScenarioContextExtra: ...
