from .schema_display import SchemaDisplay as SchemaDisplay
from .schema_property import SchemaProperty as SchemaProperty
from lark_oapi.core.construct import init as init

class Schema:
    properties: list[SchemaProperty] | None
    display: SchemaDisplay | None
    schema_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SchemaBuilder: ...

class SchemaBuilder:
    def __init__(self) -> None: ...
    def properties(self, properties: list[SchemaProperty]) -> SchemaBuilder: ...
    def display(self, display: SchemaDisplay) -> SchemaBuilder: ...
    def schema_id(self, schema_id: str) -> SchemaBuilder: ...
    def build(self) -> Schema: ...
