from .schema_display_field_mapping import SchemaDisplayFieldMapping as SchemaDisplayFieldMapping
from lark_oapi.core.construct import init as init

class SchemaDisplay:
    card_key: str | None
    fields_mapping: list[SchemaDisplayFieldMapping] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SchemaDisplayBuilder: ...

class SchemaDisplayBuilder:
    def __init__(self) -> None: ...
    def card_key(self, card_key: str) -> SchemaDisplayBuilder: ...
    def fields_mapping(self, fields_mapping: list[SchemaDisplayFieldMapping]) -> SchemaDisplayBuilder: ...
    def build(self) -> SchemaDisplay: ...
