from typing import *
from lark_oapi.core.construct import init as init

class SchemaDisplayOption:
    display_label: Optional[str]
    display_type: Optional[str]
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SchemaDisplayOptionBuilder: ...

class SchemaDisplayOptionBuilder:
    def __init__(self) -> None: ...
    def display_label(self, display_label: str) -> SchemaDisplayOptionBuilder: ...
    def display_type(self, display_type: str) -> SchemaDisplayOptionBuilder: ...
    def build(self) -> SchemaDisplayOption: ...
