from .schema_tag_options import SchemaTagOptions as SchemaTagOptions
from .schema_user_ids_option import SchemaUserIdsOption as SchemaUserIdsOption
from lark_oapi.core.construct import init as init

class SchemaTypeDefinitions:
    tag: list[SchemaTagOptions] | None
    user_ids: SchemaUserIdsOption | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SchemaTypeDefinitionsBuilder: ...

class SchemaTypeDefinitionsBuilder:
    def __init__(self) -> None: ...
    def tag(self, tag: list[SchemaTagOptions]) -> SchemaTypeDefinitionsBuilder: ...
    def user_ids(self, user_ids: SchemaUserIdsOption) -> SchemaTypeDefinitionsBuilder: ...
    def build(self) -> SchemaTypeDefinitions: ...
