from lark_oapi.core.construct import init as init

class SchemaEnumOptions:
    possible_values: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SchemaEnumOptionsBuilder: ...

class SchemaEnumOptionsBuilder:
    def __init__(self) -> None: ...
    def possible_values(self, possible_values: list[str]) -> SchemaEnumOptionsBuilder: ...
    def build(self) -> SchemaEnumOptions: ...
