from lark_oapi.core.construct import init as init

class SchemaFieldAnswerOption:
    is_searchable: bool | None
    is_returnable: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SchemaFieldAnswerOptionBuilder: ...

class SchemaFieldAnswerOptionBuilder:
    def __init__(self) -> None: ...
    def is_searchable(self, is_searchable: bool) -> SchemaFieldAnswerOptionBuilder: ...
    def is_returnable(self, is_returnable: bool) -> SchemaFieldAnswerOptionBuilder: ...
    def build(self) -> SchemaFieldAnswerOption: ...
