from lark_oapi.core.construct import init as init

class SimpleGetRelatedUsersRequest:
    user_id: int | None
    top_k: int | None
    start_time_filter: int | None
    end_time_filter: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SimpleGetRelatedUsersRequestBuilder: ...

class SimpleGetRelatedUsersRequestBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: int) -> SimpleGetRelatedUsersRequestBuilder: ...
    def top_k(self, top_k: int) -> SimpleGetRelatedUsersRequestBuilder: ...
    def start_time_filter(self, start_time_filter: int) -> SimpleGetRelatedUsersRequestBuilder: ...
    def end_time_filter(self, end_time_filter: int) -> SimpleGetRelatedUsersRequestBuilder: ...
    def build(self) -> SimpleGetRelatedUsersRequest: ...
