from lark_oapi.core.construct import init as init

class Status:
    from_status: str | None
    to_status: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> StatusBuilder: ...

class StatusBuilder:
    def __init__(self) -> None: ...
    def from_status(self, from_status: str) -> StatusBuilder: ...
    def to_status(self, to_status: str) -> StatusBuilder: ...
    def build(self) -> Status: ...
