from lark_oapi.core.construct import init as init

class AilyMessageFilter:
    run_id: str | None
    with_partial_message: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AilyMessageFilterBuilder: ...

class AilyMessageFilterBuilder:
    def __init__(self) -> None: ...
    def run_id(self, run_id: str) -> AilyMessageFilterBuilder: ...
    def with_partial_message(self, with_partial_message: bool) -> AilyMessageFilterBuilder: ...
    def build(self) -> AilyMessageFilter: ...
