from .aily_knowledge_docs import AilyKnowledgeDocs as AilyKnowledgeDocs
from lark_oapi.core.construct import init as init

class AilyKnowledgeWikiSpace:
    title: str | None
    space_id: str | None
    sub_docs: list[AilyKnowledgeDocs] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AilyKnowledgeWikiSpaceBuilder: ...

class AilyKnowledgeWikiSpaceBuilder:
    def __init__(self) -> None: ...
    def title(self, title: str) -> AilyKnowledgeWikiSpaceBuilder: ...
    def space_id(self, space_id: str) -> AilyKnowledgeWikiSpaceBuilder: ...
    def sub_docs(self, sub_docs: list[AilyKnowledgeDocs]) -> AilyKnowledgeWikiSpaceBuilder: ...
    def build(self) -> AilyKnowledgeWikiSpace: ...
