from lark_oapi.core.construct import init as init

class AilyKnowledgeAskProcessData:
    chart_dsls: list[str] | None
    chunks: list[str] | None
    sql_data: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AilyKnowledgeAskProcessDataBuilder: ...

class AilyKnowledgeAskProcessDataBuilder:
    def __init__(self) -> None: ...
    def chart_dsls(self, chart_dsls: list[str]) -> AilyKnowledgeAskProcessDataBuilder: ...
    def chunks(self, chunks: list[str]) -> AilyKnowledgeAskProcessDataBuilder: ...
    def sql_data(self, sql_data: list[str]) -> AilyKnowledgeAskProcessDataBuilder: ...
    def build(self) -> AilyKnowledgeAskProcessData: ...
