from lark_oapi.core.construct import init as init

class AilyMessageFileFilter:
    with_preview_url: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AilyMessageFileFilterBuilder: ...

class AilyMessageFileFilterBuilder:
    def __init__(self) -> None: ...
    def with_preview_url(self, with_preview_url: bool) -> AilyMessageFileFilterBuilder: ...
    def build(self) -> AilyMessageFileFilter: ...
