from lark_oapi.core.construct import init as init

class App:
    id: str | None
    label: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppBuilder: ...

class AppBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> AppBuilder: ...
    def label(self, label: str) -> AppBuilder: ...
    def build(self) -> App: ...
