from .ask_app_knowledge_request_body import AskAppKnowledgeRequestBody as AskAppKnowledgeRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class AskAppKnowledgeRequest(BaseRequest):
    app_id: str | None
    request_body: AskAppKnowledgeRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> AskAppKnowledgeRequestBuilder: ...

class AskAppKnowledgeRequestBuilder:
    def __init__(self) -> None: ...
    def app_id(self, app_id: str) -> AskAppKnowledgeRequestBuilder: ...
    def request_body(self, request_body: AskAppKnowledgeRequestBody) -> AskAppKnowledgeRequestBuilder: ...
    def build(self) -> AskAppKnowledgeRequest: ...
