from lark_oapi.core.construct import init as init

class BuiltinAction:
    builtin_action_type: str | None
    enable: bool | None
    action_status: str | None
    extra: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BuiltinActionBuilder: ...

class BuiltinActionBuilder:
    def __init__(self) -> None: ...
    def builtin_action_type(self, builtin_action_type: str) -> BuiltinActionBuilder: ...
    def enable(self, enable: bool) -> BuiltinActionBuilder: ...
    def action_status(self, action_status: str) -> BuiltinActionBuilder: ...
    def extra(self, extra: str) -> BuiltinActionBuilder: ...
    def build(self) -> BuiltinAction: ...
