from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CancelAilySessionRunRequest(BaseRequest):
    aily_session_id: str | None
    run_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CancelAilySessionRunRequestBuilder: ...

class CancelAilySessionRunRequestBuilder:
    def __init__(self) -> None: ...
    def aily_session_id(self, aily_session_id: str) -> CancelAilySessionRunRequestBuilder: ...
    def run_id(self, run_id: str) -> CancelAilySessionRunRequestBuilder: ...
    def build(self) -> CancelAilySessionRunRequest: ...
