from .aily_mention import AilyMention as AilyMention
from lark_oapi.core.construct import init as init

class CreateAilySessionAilyMessageRequestBody:
    idempotent_id: str | None
    content_type: str | None
    content: str | None
    file_ids: list[str] | None
    quote_message_id: str | None
    mentions: list[AilyMention] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateAilySessionAilyMessageRequestBodyBuilder: ...

class CreateAilySessionAilyMessageRequestBodyBuilder:
    def __init__(self) -> None: ...
    def idempotent_id(self, idempotent_id: str) -> CreateAilySessionAilyMessageRequestBodyBuilder: ...
    def content_type(self, content_type: str) -> CreateAilySessionAilyMessageRequestBodyBuilder: ...
    def content(self, content: str) -> CreateAilySessionAilyMessageRequestBodyBuilder: ...
    def file_ids(self, file_ids: list[str]) -> CreateAilySessionAilyMessageRequestBodyBuilder: ...
    def quote_message_id(self, quote_message_id: str) -> CreateAilySessionAilyMessageRequestBodyBuilder: ...
    def mentions(self, mentions: list[AilyMention]) -> CreateAilySessionAilyMessageRequestBodyBuilder: ...
    def build(self) -> CreateAilySessionAilyMessageRequestBody: ...
