from .data_asset_import_knowledge_setting import DataAssetImportKnowledgeSetting as DataAssetImportKnowledgeSetting
from lark_oapi.core.construct import init as init

class CreateAppDataAssetRequestBody:
    connect_type: str | None
    source_type: str | None
    import_knowledge_setting: DataAssetImportKnowledgeSetting | None
    description: dict[str, str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateAppDataAssetRequestBodyBuilder: ...

class CreateAppDataAssetRequestBodyBuilder:
    def __init__(self) -> None: ...
    def connect_type(self, connect_type: str) -> CreateAppDataAssetRequestBodyBuilder: ...
    def source_type(self, source_type: str) -> CreateAppDataAssetRequestBodyBuilder: ...
    def import_knowledge_setting(self, import_knowledge_setting: DataAssetImportKnowledgeSetting) -> CreateAppDataAssetRequestBodyBuilder: ...
    def description(self, description: dict[str, str]) -> CreateAppDataAssetRequestBodyBuilder: ...
    def build(self) -> CreateAppDataAssetRequestBody: ...
