from .run import Run as Run
from lark_oapi.core.construct import init as init

class CreateAilySessionRunResponseBody:
    run: Run | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateAilySessionRunResponseBodyBuilder: ...

class CreateAilySessionRunResponseBodyBuilder:
    def __init__(self) -> None: ...
    def run(self, run: Run) -> CreateAilySessionRunResponseBodyBuilder: ...
    def build(self) -> CreateAilySessionRunResponseBody: ...
