from lark_oapi.core.construct import init as init

class DataAssetTag:
    data_asset_tag_id: str | None
    name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DataAssetTagBuilder: ...

class DataAssetTagBuilder:
    def __init__(self) -> None: ...
    def data_asset_tag_id(self, data_asset_tag_id: str) -> DataAssetTagBuilder: ...
    def name(self, name: str) -> DataAssetTagBuilder: ...
    def build(self) -> DataAssetTag: ...
