from lark_oapi.core.construct import init as init

class DataAssetChunkSourceInfo:
    title: str | None
    url: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DataAssetChunkSourceInfoBuilder: ...

class DataAssetChunkSourceInfoBuilder:
    def __init__(self) -> None: ...
    def title(self, title: str) -> DataAssetChunkSourceInfoBuilder: ...
    def url(self, url: str) -> DataAssetChunkSourceInfoBuilder: ...
    def build(self) -> DataAssetChunkSourceInfo: ...
