from lark_oapi.core.construct import init as init

class DataAssetFile:
    token: str | None
    mime_type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DataAssetFileBuilder: ...

class DataAssetFileBuilder:
    def __init__(self) -> None: ...
    def token(self, token: str) -> DataAssetFileBuilder: ...
    def mime_type(self, mime_type: str) -> DataAssetFileBuilder: ...
    def build(self) -> DataAssetFile: ...
