from .data_asset_import_knowledge_wiki_sub_doc import DataAssetImportKnowledgeWikiSubDoc as DataAssetImportKnowledgeWikiSubDoc
from lark_oapi.core.construct import init as init

class DataAssetImportKnowledgeWiki:
    space_id: str | None
    sub_docs: list[DataAssetImportKnowledgeWikiSubDoc] | None
    url: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DataAssetImportKnowledgeWikiBuilder: ...

class DataAssetImportKnowledgeWikiBuilder:
    def __init__(self) -> None: ...
    def space_id(self, space_id: str) -> DataAssetImportKnowledgeWikiBuilder: ...
    def sub_docs(self, sub_docs: list[DataAssetImportKnowledgeWikiSubDoc]) -> DataAssetImportKnowledgeWikiBuilder: ...
    def url(self, url: str) -> DataAssetImportKnowledgeWikiBuilder: ...
    def build(self) -> DataAssetImportKnowledgeWiki: ...
