from .data_asset_resource import DataAssetResource as DataAssetResource
from lark_oapi.core.construct import init as init

class DataAssetItem:
    data_asset_item_id: str | None
    api_name: str | None
    label: dict[str, str] | None
    description: dict[str, str] | None
    resources: list[DataAssetResource] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DataAssetItemBuilder: ...

class DataAssetItemBuilder:
    def __init__(self) -> None: ...
    def data_asset_item_id(self, data_asset_item_id: str) -> DataAssetItemBuilder: ...
    def api_name(self, api_name: str) -> DataAssetItemBuilder: ...
    def label(self, label: dict[str, str]) -> DataAssetItemBuilder: ...
    def description(self, description: dict[str, str]) -> DataAssetItemBuilder: ...
    def resources(self, resources: list[DataAssetResource]) -> DataAssetItemBuilder: ...
    def build(self) -> DataAssetItem: ...
