from lark_oapi.core.construct import init as init

class DataAssetImportKnowledgeFile:
    title: str | None
    token: str | None
    content: str | None
    mime_type: str | None
    url: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DataAssetImportKnowledgeFileBuilder: ...

class DataAssetImportKnowledgeFileBuilder:
    def __init__(self) -> None: ...
    def title(self, title: str) -> DataAssetImportKnowledgeFileBuilder: ...
    def token(self, token: str) -> DataAssetImportKnowledgeFileBuilder: ...
    def content(self, content: str) -> DataAssetImportKnowledgeFileBuilder: ...
    def mime_type(self, mime_type: str) -> DataAssetImportKnowledgeFileBuilder: ...
    def url(self, url: str) -> DataAssetImportKnowledgeFileBuilder: ...
    def build(self) -> DataAssetImportKnowledgeFile: ...
