from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteAilySessionRequest(BaseRequest):
    aily_session_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteAilySessionRequestBuilder: ...

class DeleteAilySessionRequestBuilder:
    def __init__(self) -> None: ...
    def aily_session_id(self, aily_session_id: str) -> DeleteAilySessionRequestBuilder: ...
    def build(self) -> DeleteAilySessionRequest: ...
