from .field_setting import FieldSetting as FieldSetting
from lark_oapi.core.construct import init as init

class Field:
    api_name: str | None
    label: dict[str, str] | None
    ai_description: str | None
    access_items: list[str] | None
    type_name: str | None
    field_setting: FieldSetting | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FieldBuilder: ...

class FieldBuilder:
    def __init__(self) -> None: ...
    def api_name(self, api_name: str) -> FieldBuilder: ...
    def label(self, label: dict[str, str]) -> FieldBuilder: ...
    def ai_description(self, ai_description: str) -> FieldBuilder: ...
    def access_items(self, access_items: list[str]) -> FieldBuilder: ...
    def type_name(self, type_name: str) -> FieldBuilder: ...
    def field_setting(self, field_setting: FieldSetting) -> FieldBuilder: ...
    def build(self) -> Field: ...
