from lark_oapi.core.construct import init as init

class FieldSetting:
    required: bool | None
    unique: bool | None
    case_sensitive: bool | None
    text_max_length: int | None
    multiple: bool | None
    lookup_object_api_name: str | None
    options: list[str] | None
    detail: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FieldSettingBuilder: ...

class FieldSettingBuilder:
    def __init__(self) -> None: ...
    def required(self, required: bool) -> FieldSettingBuilder: ...
    def unique(self, unique: bool) -> FieldSettingBuilder: ...
    def case_sensitive(self, case_sensitive: bool) -> FieldSettingBuilder: ...
    def text_max_length(self, text_max_length: int) -> FieldSettingBuilder: ...
    def multiple(self, multiple: bool) -> FieldSettingBuilder: ...
    def lookup_object_api_name(self, lookup_object_api_name: str) -> FieldSettingBuilder: ...
    def options(self, options: list[str]) -> FieldSettingBuilder: ...
    def detail(self, detail: str) -> FieldSettingBuilder: ...
    def build(self) -> FieldSetting: ...
