from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetAilySessionRequest(BaseRequest):
    aily_session_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetAilySessionRequestBuilder: ...

class GetAilySessionRequestBuilder:
    def __init__(self) -> None: ...
    def aily_session_id(self, aily_session_id: str) -> GetAilySessionRequestBuilder: ...
    def build(self) -> GetAilySessionRequest: ...
