from .aily_message import AilyMessage as AilyMessage
from lark_oapi.core.construct import init as init

class GetAilySessionAilyMessageResponseBody:
    message: AilyMessage | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetAilySessionAilyMessageResponseBodyBuilder: ...

class GetAilySessionAilyMessageResponseBodyBuilder:
    def __init__(self) -> None: ...
    def message(self, message: AilyMessage) -> GetAilySessionAilyMessageResponseBodyBuilder: ...
    def build(self) -> GetAilySessionAilyMessageResponseBody: ...
