from lark_oapi.core.construct import init as init

class GetAppSkillRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetAppSkillRequestBodyBuilder: ...

class GetAppSkillRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetAppSkillRequestBody: ...
