from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetAppSkillRequest(BaseRequest):
    app_id: str | None
    skill_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetAppSkillRequestBuilder: ...

class GetAppSkillRequestBuilder:
    def __init__(self) -> None: ...
    def app_id(self, app_id: str) -> GetAppSkillRequestBuilder: ...
    def skill_id(self, skill_id: str) -> GetAppSkillRequestBuilder: ...
    def build(self) -> GetAppSkillRequest: ...
