from lark_oapi.core.construct import init as init

class GetAilySessionRunRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetAilySessionRunRequestBodyBuilder: ...

class GetAilySessionRunRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetAilySessionRunRequestBody: ...
