from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetAilySessionAilyMessageRequest(BaseRequest):
    aily_session_id: str | None
    aily_message_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetAilySessionAilyMessageRequestBuilder: ...

class GetAilySessionAilyMessageRequestBuilder:
    def __init__(self) -> None: ...
    def aily_session_id(self, aily_session_id: str) -> GetAilySessionAilyMessageRequestBuilder: ...
    def aily_message_id(self, aily_message_id: str) -> GetAilySessionAilyMessageRequestBuilder: ...
    def build(self) -> GetAilySessionAilyMessageRequest: ...
