from .message_error import MessageError as MessageError
from lark_oapi.core.construct import init as init

class Intent:
    id: int | None
    created_at: int | None
    session_id: int | None
    status: str | None
    sub_status: str | None
    channel_type: str | None
    error: MessageError | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> IntentBuilder: ...

class IntentBuilder:
    def __init__(self) -> None: ...
    def id(self, id: int) -> IntentBuilder: ...
    def created_at(self, created_at: int) -> IntentBuilder: ...
    def session_id(self, session_id: int) -> IntentBuilder: ...
    def status(self, status: str) -> IntentBuilder: ...
    def sub_status(self, sub_status: str) -> IntentBuilder: ...
    def channel_type(self, channel_type: str) -> IntentBuilder: ...
    def error(self, error: MessageError) -> IntentBuilder: ...
    def build(self) -> Intent: ...
