from lark_oapi.core.construct import init as init

class ListAppSkillRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListAppSkillRequestBodyBuilder: ...

class ListAppSkillRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListAppSkillRequestBody: ...
