from .run import Run as Run
from lark_oapi.core.construct import init as init

class ListAilySessionRunResponseBody:
    runs: list[Run] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListAilySessionRunResponseBodyBuilder: ...

class ListAilySessionRunResponseBodyBuilder:
    def __init__(self) -> None: ...
    def runs(self, runs: list[Run]) -> ListAilySessionRunResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListAilySessionRunResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListAilySessionRunResponseBodyBuilder: ...
    def build(self) -> ListAilySessionRunResponseBody: ...
