from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListAilySessionRunRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    aily_session_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListAilySessionRunRequestBuilder: ...

class ListAilySessionRunRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> ListAilySessionRunRequestBuilder: ...
    def page_token(self, page_token: str) -> ListAilySessionRunRequestBuilder: ...
    def aily_session_id(self, aily_session_id: str) -> ListAilySessionRunRequestBuilder: ...
    def build(self) -> ListAilySessionRunRequest: ...
