from lark_oapi.core.construct import init as init

class ListAppDataAssetRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListAppDataAssetRequestBodyBuilder: ...

class ListAppDataAssetRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListAppDataAssetRequestBody: ...
