from .skill import Skill as Skill
from lark_oapi.core.construct import init as init

class ListAppSkillResponseBody:
    skills: list[Skill] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListAppSkillResponseBodyBuilder: ...

class ListAppSkillResponseBodyBuilder:
    def __init__(self) -> None: ...
    def skills(self, skills: list[Skill]) -> ListAppSkillResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListAppSkillResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListAppSkillResponseBodyBuilder: ...
    def build(self) -> ListAppSkillResponseBody: ...
