from .data_asset import DataAsset as DataAsset
from lark_oapi.core.construct import init as init

class ListAppDataAssetResponseBody:
    items: list[DataAsset] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListAppDataAssetResponseBodyBuilder: ...

class ListAppDataAssetResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[DataAsset]) -> ListAppDataAssetResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListAppDataAssetResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListAppDataAssetResponseBodyBuilder: ...
    def build(self) -> ListAppDataAssetResponseBody: ...
