from .progress_item import ProgressItem as ProgressItem
from lark_oapi.core.construct import init as init

class MessageProgress:
    progress_type: str | None
    progress_items: list[ProgressItem] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MessageProgressBuilder: ...

class MessageProgressBuilder:
    def __init__(self) -> None: ...
    def progress_type(self, progress_type: str) -> MessageProgressBuilder: ...
    def progress_items(self, progress_items: list[ProgressItem]) -> MessageProgressBuilder: ...
    def build(self) -> MessageProgress: ...
