from lark_oapi.core.construct import init as init

class MessageError:
    code: str | None
    message: str | None
    error_type: str | None
    log_id: str | None
    title: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MessageErrorBuilder: ...

class MessageErrorBuilder:
    def __init__(self) -> None: ...
    def code(self, code: str) -> MessageErrorBuilder: ...
    def message(self, message: str) -> MessageErrorBuilder: ...
    def error_type(self, error_type: str) -> MessageErrorBuilder: ...
    def log_id(self, log_id: str) -> MessageErrorBuilder: ...
    def title(self, title: str) -> MessageErrorBuilder: ...
    def build(self) -> MessageError: ...
