from lark_oapi.core.construct import init as init

class ObjectSetting:
    display_name: str | None
    field_orders: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ObjectSettingBuilder: ...

class ObjectSettingBuilder:
    def __init__(self) -> None: ...
    def display_name(self, display_name: str) -> ObjectSettingBuilder: ...
    def field_orders(self, field_orders: list[str]) -> ObjectSettingBuilder: ...
    def build(self) -> ObjectSetting: ...
