from lark_oapi.core.construct import init as init

class OrderCondition:
    field: str | None
    direction: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OrderConditionBuilder: ...

class OrderConditionBuilder:
    def __init__(self) -> None: ...
    def field(self, field: str) -> OrderConditionBuilder: ...
    def direction(self, direction: str) -> OrderConditionBuilder: ...
    def build(self) -> OrderCondition: ...
