from lark_oapi.core.construct import init as init

class ProgressItem:
    progress_item_state: str | None
    content: str | None
    skill_id: str | None
    node_id: str | None
    node_type: str | None
    input: str | None
    output: str | None
    usages: list[str] | None
    skill_strategy: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ProgressItemBuilder: ...

class ProgressItemBuilder:
    def __init__(self) -> None: ...
    def progress_item_state(self, progress_item_state: str) -> ProgressItemBuilder: ...
    def content(self, content: str) -> ProgressItemBuilder: ...
    def skill_id(self, skill_id: str) -> ProgressItemBuilder: ...
    def node_id(self, node_id: str) -> ProgressItemBuilder: ...
    def node_type(self, node_type: str) -> ProgressItemBuilder: ...
    def input(self, input: str) -> ProgressItemBuilder: ...
    def output(self, output: str) -> ProgressItemBuilder: ...
    def usages(self, usages: list[str]) -> ProgressItemBuilder: ...
    def skill_strategy(self, skill_strategy: str) -> ProgressItemBuilder: ...
    def build(self) -> ProgressItem: ...
