from lark_oapi.core.construct import init as init

class RecordQueryOption:
    stringify_number: bool | None
    normalize_column_name: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RecordQueryOptionBuilder: ...

class RecordQueryOptionBuilder:
    def __init__(self) -> None: ...
    def stringify_number(self, stringify_number: bool) -> RecordQueryOptionBuilder: ...
    def normalize_column_name(self, normalize_column_name: bool) -> RecordQueryOptionBuilder: ...
    def build(self) -> RecordQueryOption: ...
