from .run_error import RunError as RunError
from lark_oapi.core.construct import init as init

class Run:
    id: str | None
    created_at: int | None
    app_id: str | None
    session_id: str | None
    status: str | None
    started_at: int | None
    ended_at: int | None
    error: RunError | None
    metadata: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RunBuilder: ...

class RunBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> RunBuilder: ...
    def created_at(self, created_at: int) -> RunBuilder: ...
    def app_id(self, app_id: str) -> RunBuilder: ...
    def session_id(self, session_id: str) -> RunBuilder: ...
    def status(self, status: str) -> RunBuilder: ...
    def started_at(self, started_at: int) -> RunBuilder: ...
    def ended_at(self, ended_at: int) -> RunBuilder: ...
    def error(self, error: RunError) -> RunBuilder: ...
    def metadata(self, metadata: str) -> RunBuilder: ...
    def build(self) -> Run: ...
