from lark_oapi.core.construct import init as init

class Session:
    id: int | None
    created_at: int | None
    effected_at: int | None
    type: str | None
    status: str | None
    active_intent_id: int | None
    channel_type: str | None
    enable_debug: bool | None
    kvs: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SessionBuilder: ...

class SessionBuilder:
    def __init__(self) -> None: ...
    def id(self, id: int) -> SessionBuilder: ...
    def created_at(self, created_at: int) -> SessionBuilder: ...
    def effected_at(self, effected_at: int) -> SessionBuilder: ...
    def type(self, type: str) -> SessionBuilder: ...
    def status(self, status: str) -> SessionBuilder: ...
    def active_intent_id(self, active_intent_id: int) -> SessionBuilder: ...
    def channel_type(self, channel_type: str) -> SessionBuilder: ...
    def enable_debug(self, enable_debug: bool) -> SessionBuilder: ...
    def kvs(self, kvs: str) -> SessionBuilder: ...
    def build(self) -> Session: ...
