from lark_oapi.core.construct import init as init

class SkillCall:
    skill_call_id: str | None
    input: str | None
    waiting_type: str | None
    input_dsl: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SkillCallBuilder: ...

class SkillCallBuilder:
    def __init__(self) -> None: ...
    def skill_call_id(self, skill_call_id: str) -> SkillCallBuilder: ...
    def input(self, input: str) -> SkillCallBuilder: ...
    def waiting_type(self, waiting_type: str) -> SkillCallBuilder: ...
    def input_dsl(self, input_dsl: str) -> SkillCallBuilder: ...
    def build(self) -> SkillCall: ...
