from lark_oapi.core.construct import init as init

class StartAppSkillResponseBody:
    output: str | None
    status: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> StartAppSkillResponseBodyBuilder: ...

class StartAppSkillResponseBodyBuilder:
    def __init__(self) -> None: ...
    def output(self, output: str) -> StartAppSkillResponseBodyBuilder: ...
    def status(self, status: str) -> StartAppSkillResponseBodyBuilder: ...
    def build(self) -> StartAppSkillResponseBody: ...
