from lark_oapi.core.construct import init as init

class Suggestion:
    content: str | None
    skill_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SuggestionBuilder: ...

class SuggestionBuilder:
    def __init__(self) -> None: ...
    def content(self, content: str) -> SuggestionBuilder: ...
    def skill_id(self, skill_id: str) -> SuggestionBuilder: ...
    def build(self) -> Suggestion: ...
