from lark_oapi.core.construct import init as init

class UpdateAilySessionRequestBody:
    channel_context: str | None
    metadata: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateAilySessionRequestBodyBuilder: ...

class UpdateAilySessionRequestBodyBuilder:
    def __init__(self) -> None: ...
    def channel_context(self, channel_context: str) -> UpdateAilySessionRequestBodyBuilder: ...
    def metadata(self, metadata: str) -> UpdateAilySessionRequestBodyBuilder: ...
    def build(self) -> UpdateAilySessionRequestBody: ...
