from .aily_session import AilySession as AilySession
from lark_oapi.core.construct import init as init

class UpdateAilySessionResponseBody:
    session: AilySession | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateAilySessionResponseBodyBuilder: ...

class UpdateAilySessionResponseBodyBuilder:
    def __init__(self) -> None: ...
    def session(self, session: AilySession) -> UpdateAilySessionResponseBodyBuilder: ...
    def build(self) -> UpdateAilySessionResponseBody: ...
