from .update_aily_session_request_body import UpdateAilySessionRequestBody as UpdateAilySessionRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UpdateAilySessionRequest(BaseRequest):
    aily_session_id: str | None
    request_body: UpdateAilySessionRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UpdateAilySessionRequestBuilder: ...

class UpdateAilySessionRequestBuilder:
    def __init__(self) -> None: ...
    def aily_session_id(self, aily_session_id: str) -> UpdateAilySessionRequestBuilder: ...
    def request_body(self, request_body: UpdateAilySessionRequestBody) -> UpdateAilySessionRequestBuilder: ...
    def build(self) -> UpdateAilySessionRequest: ...
