from .data_asset_file import DataAssetFile as DataAssetFile
from lark_oapi.core.construct import init as init

class UploadFileAppDataAssetResponseBody:
    file_info: DataAssetFile | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UploadFileAppDataAssetResponseBodyBuilder: ...

class UploadFileAppDataAssetResponseBodyBuilder:
    def __init__(self) -> None: ...
    def file_info(self, file_info: DataAssetFile) -> UploadFileAppDataAssetResponseBodyBuilder: ...
    def build(self) -> UploadFileAppDataAssetResponseBody: ...
