from lark_oapi.core.construct import init as init

class FormField:
    name: str | None
    type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FormFieldBuilder: ...

class FormFieldBuilder:
    def __init__(self) -> None: ...
    def name(self, name: str) -> FormFieldBuilder: ...
    def type(self, type: str) -> FormFieldBuilder: ...
    def build(self) -> FormField: ...
