from .query_task_request_body import QueryTaskRequestBody as QueryTaskRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class QueryTaskRequest(BaseRequest):
    user_id_type: str | None
    request_body: QueryTaskRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> QueryTaskRequestBuilder: ...

class QueryTaskRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> QueryTaskRequestBuilder: ...
    def request_body(self, request_body: QueryTaskRequestBody) -> QueryTaskRequestBuilder: ...
    def build(self) -> QueryTaskRequest: ...
