from .rule import Rule as Rule
from lark_oapi.core.construct import init as init

class QueryRuleResponseBody:
    rules: list[Rule] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryRuleResponseBodyBuilder: ...

class QueryRuleResponseBodyBuilder:
    def __init__(self) -> None: ...
    def rules(self, rules: list[Rule]) -> QueryRuleResponseBodyBuilder: ...
    def build(self) -> QueryRuleResponseBody: ...
