from .remove_rule_view_request_body import RemoveRuleViewRequestBody as RemoveRuleViewRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class RemoveRuleViewRequest(BaseRequest):
    user_id_type: str | None
    rule_id: str | None
    request_body: RemoveRuleViewRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> RemoveRuleViewRequestBuilder: ...

class RemoveRuleViewRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> RemoveRuleViewRequestBuilder: ...
    def rule_id(self, rule_id: str) -> RemoveRuleViewRequestBuilder: ...
    def request_body(self, request_body: RemoveRuleViewRequestBody) -> RemoveRuleViewRequestBuilder: ...
    def build(self) -> RemoveRuleViewRequest: ...
