from ..model.batch_update_card_request import BatchUpdateCardRequest as BatchUpdateCardRequest
from ..model.batch_update_card_response import BatchUpdateCardResponse as BatchUpdateCardResponse
from ..model.create_card_request import CreateCardRequest as CreateCardRequest
from ..model.create_card_response import CreateCardResponse as CreateCardResponse
from ..model.id_convert_card_request import IdConvertCardRequest as IdConvertCardRequest
from ..model.id_convert_card_response import IdConvertCardResponse as IdConvertCardResponse
from ..model.settings_card_request import SettingsCardRequest as SettingsCardRequest
from ..model.settings_card_response import SettingsCardResponse as SettingsCardResponse
from ..model.update_card_request import UpdateCardRequest as UpdateCardRequest
from ..model.update_card_response import UpdateCardResponse as UpdateCardResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class Card:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def batch_update(self, request: BatchUpdateCardRequest, option: RequestOption | None = None) -> BatchUpdateCardResponse: ...
    async def abatch_update(self, request: BatchUpdateCardRequest, option: RequestOption | None = None) -> BatchUpdateCardResponse: ...
    def create(self, request: CreateCardRequest, option: RequestOption | None = None) -> CreateCardResponse: ...
    async def acreate(self, request: CreateCardRequest, option: RequestOption | None = None) -> CreateCardResponse: ...
    def id_convert(self, request: IdConvertCardRequest, option: RequestOption | None = None) -> IdConvertCardResponse: ...
    async def aid_convert(self, request: IdConvertCardRequest, option: RequestOption | None = None) -> IdConvertCardResponse: ...
    def settings(self, request: SettingsCardRequest, option: RequestOption | None = None) -> SettingsCardResponse: ...
    async def asettings(self, request: SettingsCardRequest, option: RequestOption | None = None) -> SettingsCardResponse: ...
    def update(self, request: UpdateCardRequest, option: RequestOption | None = None) -> UpdateCardResponse: ...
    async def aupdate(self, request: UpdateCardRequest, option: RequestOption | None = None) -> UpdateCardResponse: ...
