from ..model.add_members_tasklist_request import AddMembersTasklistRequest as AddMembersTasklistRequest
from ..model.add_members_tasklist_response import AddMembersTasklistResponse as AddMembersTasklistResponse
from ..model.create_tasklist_request import CreateTasklistRequest as CreateTasklistRequest
from ..model.create_tasklist_response import CreateTasklistResponse as CreateTasklistResponse
from ..model.delete_tasklist_request import DeleteTasklistRequest as DeleteTasklistRequest
from ..model.delete_tasklist_response import DeleteTasklistResponse as DeleteTasklistResponse
from ..model.get_tasklist_request import GetTasklistRequest as GetTasklistRequest
from ..model.get_tasklist_response import GetTasklistResponse as GetTasklistResponse
from ..model.list_tasklist_request import ListTasklistRequest as ListTasklistRequest
from ..model.list_tasklist_response import ListTasklistResponse as ListTasklistResponse
from ..model.patch_tasklist_request import PatchTasklistRequest as PatchTasklistRequest
from ..model.patch_tasklist_response import PatchTasklistResponse as PatchTasklistResponse
from ..model.remove_members_tasklist_request import RemoveMembersTasklistRequest as RemoveMembersTasklistRequest
from ..model.remove_members_tasklist_response import RemoveMembersTasklistResponse as RemoveMembersTasklistResponse
from ..model.tasks_tasklist_request import TasksTasklistRequest as TasksTasklistRequest
from ..model.tasks_tasklist_response import TasksTasklistResponse as TasksTasklistResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class Tasklist:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def add_members(self, request: AddMembersTasklistRequest, option: RequestOption | None = None) -> AddMembersTasklistResponse: ...
    async def aadd_members(self, request: AddMembersTasklistRequest, option: RequestOption | None = None) -> AddMembersTasklistResponse: ...
    def create(self, request: CreateTasklistRequest, option: RequestOption | None = None) -> CreateTasklistResponse: ...
    async def acreate(self, request: CreateTasklistRequest, option: RequestOption | None = None) -> CreateTasklistResponse: ...
    def delete(self, request: DeleteTasklistRequest, option: RequestOption | None = None) -> DeleteTasklistResponse: ...
    async def adelete(self, request: DeleteTasklistRequest, option: RequestOption | None = None) -> DeleteTasklistResponse: ...
    def get(self, request: GetTasklistRequest, option: RequestOption | None = None) -> GetTasklistResponse: ...
    async def aget(self, request: GetTasklistRequest, option: RequestOption | None = None) -> GetTasklistResponse: ...
    def list(self, request: ListTasklistRequest, option: RequestOption | None = None) -> ListTasklistResponse: ...
    async def alist(self, request: ListTasklistRequest, option: RequestOption | None = None) -> ListTasklistResponse: ...
    def patch(self, request: PatchTasklistRequest, option: RequestOption | None = None) -> PatchTasklistResponse: ...
    async def apatch(self, request: PatchTasklistRequest, option: RequestOption | None = None) -> PatchTasklistResponse: ...
    def remove_members(self, request: RemoveMembersTasklistRequest, option: RequestOption | None = None) -> RemoveMembersTasklistResponse: ...
    async def aremove_members(self, request: RemoveMembersTasklistRequest, option: RequestOption | None = None) -> RemoveMembersTasklistResponse: ...
    def tasks(self, request: TasksTasklistRequest, option: RequestOption | None = None) -> TasksTasklistResponse: ...
    async def atasks(self, request: TasksTasklistRequest, option: RequestOption | None = None) -> TasksTasklistResponse: ...
