from lark_oapi.core.construct import init as init

class CreateIdentityResponseBody:
    verify_uid: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateIdentityResponseBodyBuilder: ...

class CreateIdentityResponseBodyBuilder:
    def __init__(self) -> None: ...
    def verify_uid(self, verify_uid: str) -> CreateIdentityResponseBodyBuilder: ...
    def build(self) -> CreateIdentityResponseBody: ...
