from lark_oapi.core.construct import init as init

class Identity:
    identity_name: str | None
    identity_code: str | None
    mobile: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> IdentityBuilder: ...

class IdentityBuilder:
    def __init__(self) -> None: ...
    def identity_name(self, identity_name: str) -> IdentityBuilder: ...
    def identity_code(self, identity_code: str) -> IdentityBuilder: ...
    def mobile(self, mobile: str) -> IdentityBuilder: ...
    def build(self) -> Identity: ...
