from lark_oapi.core.construct import init as init

class Dislike:
    entity_type: int | None
    entity_id: str | None
    create_time: str | None
    user_id: str | None
    id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DislikeBuilder: ...

class DislikeBuilder:
    def __init__(self) -> None: ...
    def entity_type(self, entity_type: int) -> DislikeBuilder: ...
    def entity_id(self, entity_id: str) -> DislikeBuilder: ...
    def create_time(self, create_time: str) -> DislikeBuilder: ...
    def user_id(self, user_id: str) -> DislikeBuilder: ...
    def id(self, id: str) -> DislikeBuilder: ...
    def build(self) -> Dislike: ...
