from lark_oapi.core.construct import init as init

class GetPostRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetPostRequestBodyBuilder: ...

class GetPostRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetPostRequestBody: ...
