from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetPostRequest(BaseRequest):
    user_id_type: str | None
    post_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetPostRequestBuilder: ...

class GetPostRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> GetPostRequestBuilder: ...
    def post_id(self, post_id: str) -> GetPostRequestBuilder: ...
    def build(self) -> GetPostRequest: ...
