from .post import Post as Post
from lark_oapi.core.construct import init as init

class GetPostResponseBody:
    post: Post | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetPostResponseBodyBuilder: ...

class GetPostResponseBodyBuilder:
    def __init__(self) -> None: ...
    def post(self, post: Post) -> GetPostResponseBodyBuilder: ...
    def build(self) -> GetPostResponseBody: ...
