from lark_oapi.core.construct import init as init

class ReactionList:
    type: str | None
    count: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReactionListBuilder: ...

class ReactionListBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> ReactionListBuilder: ...
    def count(self, count: int) -> ReactionListBuilder: ...
    def build(self) -> ReactionList: ...
