from .model.p2_contact_custom_attr_event_updated_v3 import P2ContactCustomAttrEventUpdatedV3 as P2ContactCustomAttrEventUpdatedV3
from .model.p2_contact_department_created_v3 import P2ContactDepartmentCreatedV3 as P2ContactDepartmentCreatedV3
from .model.p2_contact_department_deleted_v3 import P2ContactDepartmentDeletedV3 as P2ContactDepartmentDeletedV3
from .model.p2_contact_department_updated_v3 import P2ContactDepartmentUpdatedV3 as P2ContactDepartmentUpdatedV3
from .model.p2_contact_employee_type_enum_actived_v3 import P2ContactEmployeeTypeEnumActivedV3 as P2ContactEmployeeTypeEnumActivedV3
from .model.p2_contact_employee_type_enum_created_v3 import P2ContactEmployeeTypeEnumCreatedV3 as P2ContactEmployeeTypeEnumCreatedV3
from .model.p2_contact_employee_type_enum_deactivated_v3 import P2ContactEmployeeTypeEnumDeactivatedV3 as P2ContactEmployeeTypeEnumDeactivatedV3
from .model.p2_contact_employee_type_enum_deleted_v3 import P2ContactEmployeeTypeEnumDeletedV3 as P2ContactEmployeeTypeEnumDeletedV3
from .model.p2_contact_employee_type_enum_updated_v3 import P2ContactEmployeeTypeEnumUpdatedV3 as P2ContactEmployeeTypeEnumUpdatedV3
from .model.p2_contact_scope_updated_v3 import P2ContactScopeUpdatedV3 as P2ContactScopeUpdatedV3
from .model.p2_contact_user_created_v3 import P2ContactUserCreatedV3 as P2ContactUserCreatedV3
from .model.p2_contact_user_deleted_v3 import P2ContactUserDeletedV3 as P2ContactUserDeletedV3
from .model.p2_contact_user_updated_v3 import P2ContactUserUpdatedV3 as P2ContactUserUpdatedV3
from _typeshed import Incomplete
from lark_oapi.event.processor import IEventProcessor as IEventProcessor
from typing import Callable

class P2ContactCustomAttrEventUpdatedV3Processor(IEventProcessor[P2ContactCustomAttrEventUpdatedV3]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ContactCustomAttrEventUpdatedV3], None]) -> None: ...
    def type(self) -> type[P2ContactCustomAttrEventUpdatedV3]: ...
    def do(self, data: P2ContactCustomAttrEventUpdatedV3) -> None: ...

class P2ContactDepartmentCreatedV3Processor(IEventProcessor[P2ContactDepartmentCreatedV3]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ContactDepartmentCreatedV3], None]) -> None: ...
    def type(self) -> type[P2ContactDepartmentCreatedV3]: ...
    def do(self, data: P2ContactDepartmentCreatedV3) -> None: ...

class P2ContactDepartmentDeletedV3Processor(IEventProcessor[P2ContactDepartmentDeletedV3]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ContactDepartmentDeletedV3], None]) -> None: ...
    def type(self) -> type[P2ContactDepartmentDeletedV3]: ...
    def do(self, data: P2ContactDepartmentDeletedV3) -> None: ...

class P2ContactDepartmentUpdatedV3Processor(IEventProcessor[P2ContactDepartmentUpdatedV3]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ContactDepartmentUpdatedV3], None]) -> None: ...
    def type(self) -> type[P2ContactDepartmentUpdatedV3]: ...
    def do(self, data: P2ContactDepartmentUpdatedV3) -> None: ...

class P2ContactEmployeeTypeEnumActivedV3Processor(IEventProcessor[P2ContactEmployeeTypeEnumActivedV3]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ContactEmployeeTypeEnumActivedV3], None]) -> None: ...
    def type(self) -> type[P2ContactEmployeeTypeEnumActivedV3]: ...
    def do(self, data: P2ContactEmployeeTypeEnumActivedV3) -> None: ...

class P2ContactEmployeeTypeEnumCreatedV3Processor(IEventProcessor[P2ContactEmployeeTypeEnumCreatedV3]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ContactEmployeeTypeEnumCreatedV3], None]) -> None: ...
    def type(self) -> type[P2ContactEmployeeTypeEnumCreatedV3]: ...
    def do(self, data: P2ContactEmployeeTypeEnumCreatedV3) -> None: ...

class P2ContactEmployeeTypeEnumDeactivatedV3Processor(IEventProcessor[P2ContactEmployeeTypeEnumDeactivatedV3]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ContactEmployeeTypeEnumDeactivatedV3], None]) -> None: ...
    def type(self) -> type[P2ContactEmployeeTypeEnumDeactivatedV3]: ...
    def do(self, data: P2ContactEmployeeTypeEnumDeactivatedV3) -> None: ...

class P2ContactEmployeeTypeEnumDeletedV3Processor(IEventProcessor[P2ContactEmployeeTypeEnumDeletedV3]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ContactEmployeeTypeEnumDeletedV3], None]) -> None: ...
    def type(self) -> type[P2ContactEmployeeTypeEnumDeletedV3]: ...
    def do(self, data: P2ContactEmployeeTypeEnumDeletedV3) -> None: ...

class P2ContactEmployeeTypeEnumUpdatedV3Processor(IEventProcessor[P2ContactEmployeeTypeEnumUpdatedV3]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ContactEmployeeTypeEnumUpdatedV3], None]) -> None: ...
    def type(self) -> type[P2ContactEmployeeTypeEnumUpdatedV3]: ...
    def do(self, data: P2ContactEmployeeTypeEnumUpdatedV3) -> None: ...

class P2ContactScopeUpdatedV3Processor(IEventProcessor[P2ContactScopeUpdatedV3]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ContactScopeUpdatedV3], None]) -> None: ...
    def type(self) -> type[P2ContactScopeUpdatedV3]: ...
    def do(self, data: P2ContactScopeUpdatedV3) -> None: ...

class P2ContactUserCreatedV3Processor(IEventProcessor[P2ContactUserCreatedV3]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ContactUserCreatedV3], None]) -> None: ...
    def type(self) -> type[P2ContactUserCreatedV3]: ...
    def do(self, data: P2ContactUserCreatedV3) -> None: ...

class P2ContactUserDeletedV3Processor(IEventProcessor[P2ContactUserDeletedV3]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ContactUserDeletedV3], None]) -> None: ...
    def type(self) -> type[P2ContactUserDeletedV3]: ...
    def do(self, data: P2ContactUserDeletedV3) -> None: ...

class P2ContactUserUpdatedV3Processor(IEventProcessor[P2ContactUserUpdatedV3]):
    f: Incomplete
    def __init__(self, f: Callable[[P2ContactUserUpdatedV3], None]) -> None: ...
    def type(self) -> type[P2ContactUserUpdatedV3]: ...
    def do(self, data: P2ContactUserUpdatedV3) -> None: ...
