from lark_oapi.core.construct import init as init

class ExportJob:
    file_extension: str | None
    token: str | None
    type: str | None
    file_name: str | None
    file_token: str | None
    job_error_msg: str | None
    job_status: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ExportJobBuilder: ...

class ExportJobBuilder:
    def __init__(self) -> None: ...
    def file_extension(self, file_extension: str) -> ExportJobBuilder: ...
    def token(self, token: str) -> ExportJobBuilder: ...
    def type(self, type: str) -> ExportJobBuilder: ...
    def file_name(self, file_name: str) -> ExportJobBuilder: ...
    def file_token(self, file_token: str) -> ExportJobBuilder: ...
    def job_error_msg(self, job_error_msg: str) -> ExportJobBuilder: ...
    def job_status(self, job_status: int) -> ExportJobBuilder: ...
    def build(self) -> ExportJob: ...
