from lark_oapi.core.construct import init as init

class FileLike:
    user_id: int | None
    last_liked_time: int | None
    user_name: str | None
    user_en_name: str | None
    user_avatar_url: str | None
    user_is_desensitized: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FileLikeBuilder: ...

class FileLikeBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: int) -> FileLikeBuilder: ...
    def last_liked_time(self, last_liked_time: int) -> FileLikeBuilder: ...
    def user_name(self, user_name: str) -> FileLikeBuilder: ...
    def user_en_name(self, user_en_name: str) -> FileLikeBuilder: ...
    def user_avatar_url(self, user_avatar_url: str) -> FileLikeBuilder: ...
    def user_is_desensitized(self, user_is_desensitized: bool) -> FileLikeBuilder: ...
    def build(self) -> FileLike: ...
