from lark_oapi.core.construct import init as init

class ImportJobMountPoint:
    mount_type: int | None
    mount_key: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ImportJobMountPointBuilder: ...

class ImportJobMountPointBuilder:
    def __init__(self) -> None: ...
    def mount_type(self, mount_type: int) -> ImportJobMountPointBuilder: ...
    def mount_key(self, mount_key: str) -> ImportJobMountPointBuilder: ...
    def build(self) -> ImportJobMountPoint: ...
