from .permission_public import PermissionPublic as PermissionPublic
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PatchPermissionPublicRequest(BaseRequest):
    type: str | None
    token: str | None
    request_body: PermissionPublic | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PatchPermissionPublicRequestBuilder: ...

class PatchPermissionPublicRequestBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> PatchPermissionPublicRequestBuilder: ...
    def token(self, token: str) -> PatchPermissionPublicRequestBuilder: ...
    def request_body(self, request_body: PermissionPublic) -> PatchPermissionPublicRequestBuilder: ...
    def build(self) -> PatchPermissionPublicRequest: ...
