from lark_oapi.core.construct import init as init

class SecureLabel:
    id: int | None
    name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SecureLabelBuilder: ...

class SecureLabelBuilder:
    def __init__(self) -> None: ...
    def id(self, id: int) -> SecureLabelBuilder: ...
    def name(self, name: str) -> SecureLabelBuilder: ...
    def build(self) -> SecureLabel: ...
