from lark_oapi.core.construct import init as init

class Accessibility:
    reason: str | None
    state: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AccessibilityBuilder: ...

class AccessibilityBuilder:
    def __init__(self) -> None: ...
    def reason(self, reason: str) -> AccessibilityBuilder: ...
    def state(self, state: str) -> AccessibilityBuilder: ...
    def build(self) -> Accessibility: ...
