from lark_oapi.core.construct import init as init

class AppScopes:
    high_level_scopes: list[str] | None
    low_level_scopes: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppScopesBuilder: ...

class AppScopesBuilder:
    def __init__(self) -> None: ...
    def high_level_scopes(self, high_level_scopes: list[str]) -> AppScopesBuilder: ...
    def low_level_scopes(self, low_level_scopes: list[str]) -> AppScopesBuilder: ...
    def build(self) -> AppScopes: ...
