from .app_visibility_event import AppVisibilityEvent as AppVisibilityEvent
from lark_oapi.core.construct import init as init

class AppVersionRemarkEvent:
    remark: str | None
    update_remark: str | None
    visibility: AppVisibilityEvent | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppVersionRemarkEventBuilder: ...

class AppVersionRemarkEventBuilder:
    def __init__(self) -> None: ...
    def remark(self, remark: str) -> AppVersionRemarkEventBuilder: ...
    def update_remark(self, update_remark: str) -> AppVersionRemarkEventBuilder: ...
    def visibility(self, visibility: AppVisibilityEvent) -> AppVersionRemarkEventBuilder: ...
    def build(self) -> AppVersionRemarkEvent: ...
