from lark_oapi.core.construct import init as init

class AppAdminUser:
    admin_type: list[str] | None
    user_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppAdminUserBuilder: ...

class AppAdminUserBuilder:
    def __init__(self) -> None: ...
    def admin_type(self, admin_type: list[str]) -> AppAdminUserBuilder: ...
    def user_id(self, user_id: str) -> AppAdminUserBuilder: ...
    def build(self) -> AppAdminUser: ...
