from lark_oapi.core.construct import init as init

class AppScope:
    scope: str | None
    description: str | None
    level: int | None
    token_types: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppScopeBuilder: ...

class AppScopeBuilder:
    def __init__(self) -> None: ...
    def scope(self, scope: str) -> AppScopeBuilder: ...
    def description(self, description: str) -> AppScopeBuilder: ...
    def level(self, level: int) -> AppScopeBuilder: ...
    def token_types(self, token_types: list[str]) -> AppScopeBuilder: ...
    def build(self) -> AppScope: ...
