from .app_contacts_range_id_list import AppContactsRangeIdList as AppContactsRangeIdList
from lark_oapi.core.construct import init as init

class AppConfigContactsRange:
    contacts_range_type: str | None
    visible_list: AppContactsRangeIdList | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppConfigContactsRangeBuilder: ...

class AppConfigContactsRangeBuilder:
    def __init__(self) -> None: ...
    def contacts_range_type(self, contacts_range_type: str) -> AppConfigContactsRangeBuilder: ...
    def visible_list(self, visible_list: AppContactsRangeIdList) -> AppConfigContactsRangeBuilder: ...
    def build(self) -> AppConfigContactsRange: ...
