from lark_oapi.core.construct import init as init

class AppRecommendRuleVisibilityInfo:
    is_all: bool | None
    department_ids: list[str] | None
    user_ids: list[str] | None
    group_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppRecommendRuleVisibilityInfoBuilder: ...

class AppRecommendRuleVisibilityInfoBuilder:
    def __init__(self) -> None: ...
    def is_all(self, is_all: bool) -> AppRecommendRuleVisibilityInfoBuilder: ...
    def department_ids(self, department_ids: list[str]) -> AppRecommendRuleVisibilityInfoBuilder: ...
    def user_ids(self, user_ids: list[str]) -> AppRecommendRuleVisibilityInfoBuilder: ...
    def group_ids(self, group_ids: list[str]) -> AppRecommendRuleVisibilityInfoBuilder: ...
    def build(self) -> AppRecommendRuleVisibilityInfo: ...
