from lark_oapi.core.construct import init as init

class AppVisibilityItem:
    user_id: str | None
    department_id: str | None
    group_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppVisibilityItemBuilder: ...

class AppVisibilityItemBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: str) -> AppVisibilityItemBuilder: ...
    def department_id(self, department_id: str) -> AppVisibilityItemBuilder: ...
    def group_id(self, group_id: str) -> AppVisibilityItemBuilder: ...
    def build(self) -> AppVisibilityItem: ...
