from .app_config_security_item import AppConfigSecurityItem as AppConfigSecurityItem
from lark_oapi.core.construct import init as init

class AppConfigSecurity:
    add: AppConfigSecurityItem | None
    remove: AppConfigSecurityItem | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppConfigSecurityBuilder: ...

class AppConfigSecurityBuilder:
    def __init__(self) -> None: ...
    def add(self, add: AppConfigSecurityItem) -> AppConfigSecurityBuilder: ...
    def remove(self, remove: AppConfigSecurityItem) -> AppConfigSecurityBuilder: ...
    def build(self) -> AppConfigSecurity: ...
