from lark_oapi.core.construct import init as init

class ApplyScopeResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApplyScopeResponseBodyBuilder: ...

class ApplyScopeResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ApplyScopeResponseBody: ...
