from .user_id import UserId as UserId
from lark_oapi.core.construct import init as init

class ApplicationEventOwner:
    type: int | None
    name: str | None
    help_desk: str | None
    email: str | None
    phone: str | None
    owner_id: UserId | None
    customer_service_account: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApplicationEventOwnerBuilder: ...

class ApplicationEventOwnerBuilder:
    def __init__(self) -> None: ...
    def type(self, type: int) -> ApplicationEventOwnerBuilder: ...
    def name(self, name: str) -> ApplicationEventOwnerBuilder: ...
    def help_desk(self, help_desk: str) -> ApplicationEventOwnerBuilder: ...
    def email(self, email: str) -> ApplicationEventOwnerBuilder: ...
    def phone(self, phone: str) -> ApplicationEventOwnerBuilder: ...
    def owner_id(self, owner_id: UserId) -> ApplicationEventOwnerBuilder: ...
    def customer_service_account(self, customer_service_account: str) -> ApplicationEventOwnerBuilder: ...
    def build(self) -> ApplicationEventOwner: ...
