from .application_app_usage import ApplicationAppUsage as ApplicationAppUsage
from lark_oapi.core.construct import init as init

class ApplicationDepartmentAppUsage:
    department_id: str | None
    app: list[ApplicationAppUsage] | None
    gadget: list[ApplicationAppUsage] | None
    webapp: list[ApplicationAppUsage] | None
    bot: list[ApplicationAppUsage] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApplicationDepartmentAppUsageBuilder: ...

class ApplicationDepartmentAppUsageBuilder:
    def __init__(self) -> None: ...
    def department_id(self, department_id: str) -> ApplicationDepartmentAppUsageBuilder: ...
    def app(self, app: list[ApplicationAppUsage]) -> ApplicationDepartmentAppUsageBuilder: ...
    def gadget(self, gadget: list[ApplicationAppUsage]) -> ApplicationDepartmentAppUsageBuilder: ...
    def webapp(self, webapp: list[ApplicationAppUsage]) -> ApplicationDepartmentAppUsageBuilder: ...
    def bot(self, bot: list[ApplicationAppUsage]) -> ApplicationDepartmentAppUsageBuilder: ...
    def build(self) -> ApplicationDepartmentAppUsage: ...
