from .app_ability import AppAbility as AppAbility
from .app_i18n_info import AppI18nInfo as AppI18nInfo
from .app_scope import AppScope as AppScope
from .app_version_remark_event import AppVersionRemarkEvent as AppVersionRemarkEvent
from lark_oapi.core.construct import init as init

class ApplicationAppVersionEvent:
    app_id: str | None
    version: str | None
    version_id: str | None
    app_name: str | None
    avatar_url: str | None
    description: str | None
    scopes: list[AppScope] | None
    back_home_url: str | None
    i18n: list[AppI18nInfo] | None
    common_categories: list[str] | None
    events: list[str] | None
    status: int | None
    create_time: int | None
    publish_time: int | None
    ability: AppAbility | None
    remark: AppVersionRemarkEvent | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApplicationAppVersionEventBuilder: ...

class ApplicationAppVersionEventBuilder:
    def __init__(self) -> None: ...
    def app_id(self, app_id: str) -> ApplicationAppVersionEventBuilder: ...
    def version(self, version: str) -> ApplicationAppVersionEventBuilder: ...
    def version_id(self, version_id: str) -> ApplicationAppVersionEventBuilder: ...
    def app_name(self, app_name: str) -> ApplicationAppVersionEventBuilder: ...
    def avatar_url(self, avatar_url: str) -> ApplicationAppVersionEventBuilder: ...
    def description(self, description: str) -> ApplicationAppVersionEventBuilder: ...
    def scopes(self, scopes: list[AppScope]) -> ApplicationAppVersionEventBuilder: ...
    def back_home_url(self, back_home_url: str) -> ApplicationAppVersionEventBuilder: ...
    def i18n(self, i18n: list[AppI18nInfo]) -> ApplicationAppVersionEventBuilder: ...
    def common_categories(self, common_categories: list[str]) -> ApplicationAppVersionEventBuilder: ...
    def events(self, events: list[str]) -> ApplicationAppVersionEventBuilder: ...
    def status(self, status: int) -> ApplicationAppVersionEventBuilder: ...
    def create_time(self, create_time: int) -> ApplicationAppVersionEventBuilder: ...
    def publish_time(self, publish_time: int) -> ApplicationAppVersionEventBuilder: ...
    def ability(self, ability: AppAbility) -> ApplicationAppVersionEventBuilder: ...
    def remark(self, remark: AppVersionRemarkEvent) -> ApplicationAppVersionEventBuilder: ...
    def build(self) -> ApplicationAppVersionEvent: ...
