from .block_i18n_info import BlockI18nInfo as BlockI18nInfo
from lark_oapi.core.construct import init as init

class Block:
    block_type_id: str | None
    version_id: str | None
    i18n: list[BlockI18nInfo] | None
    mobile_icon_url: str | None
    pc_icon_url: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BlockBuilder: ...

class BlockBuilder:
    def __init__(self) -> None: ...
    def block_type_id(self, block_type_id: str) -> BlockBuilder: ...
    def version_id(self, version_id: str) -> BlockBuilder: ...
    def i18n(self, i18n: list[BlockI18nInfo]) -> BlockBuilder: ...
    def mobile_icon_url(self, mobile_icon_url: str) -> BlockBuilder: ...
    def pc_icon_url(self, pc_icon_url: str) -> BlockBuilder: ...
    def build(self) -> Block: ...
