from lark_oapi.core.construct import init as init

class Bot:
    card_request_url: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BotBuilder: ...

class BotBuilder:
    def __init__(self) -> None: ...
    def card_request_url(self, card_request_url: str) -> BotBuilder: ...
    def build(self) -> Bot: ...
