from lark_oapi.core.construct import init as init

class Callback:
    callback_type: str | None
    request_url: str | None
    subscribed_callbacks: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CallbackBuilder: ...

class CallbackBuilder:
    def __init__(self) -> None: ...
    def callback_type(self, callback_type: str) -> CallbackBuilder: ...
    def request_url(self, request_url: str) -> CallbackBuilder: ...
    def subscribed_callbacks(self, subscribed_callbacks: list[str]) -> CallbackBuilder: ...
    def build(self) -> Callback: ...
