from .application_visibility_department_white_black_info import ApplicationVisibilityDepartmentWhiteBlackInfo as ApplicationVisibilityDepartmentWhiteBlackInfo
from .application_visibility_group_white_black_info import ApplicationVisibilityGroupWhiteBlackInfo as ApplicationVisibilityGroupWhiteBlackInfo
from .application_visibility_user_white_black_info import ApplicationVisibilityUserWhiteBlackInfo as ApplicationVisibilityUserWhiteBlackInfo
from lark_oapi.core.construct import init as init

class CheckWhiteBlackListApplicationVisibilityResponseBody:
    user_visibility_list: list[ApplicationVisibilityUserWhiteBlackInfo] | None
    department_visibility_list: list[ApplicationVisibilityDepartmentWhiteBlackInfo] | None
    group_visibility_list: list[ApplicationVisibilityGroupWhiteBlackInfo] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CheckWhiteBlackListApplicationVisibilityResponseBodyBuilder: ...

class CheckWhiteBlackListApplicationVisibilityResponseBodyBuilder:
    def __init__(self) -> None: ...
    def user_visibility_list(self, user_visibility_list: list[ApplicationVisibilityUserWhiteBlackInfo]) -> CheckWhiteBlackListApplicationVisibilityResponseBodyBuilder: ...
    def department_visibility_list(self, department_visibility_list: list[ApplicationVisibilityDepartmentWhiteBlackInfo]) -> CheckWhiteBlackListApplicationVisibilityResponseBodyBuilder: ...
    def group_visibility_list(self, group_visibility_list: list[ApplicationVisibilityGroupWhiteBlackInfo]) -> CheckWhiteBlackListApplicationVisibilityResponseBodyBuilder: ...
    def build(self) -> CheckWhiteBlackListApplicationVisibilityResponseBody: ...
