from lark_oapi.core.construct import init as init

class ClientBadgeNum:
    web_app: int | None
    gadget: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ClientBadgeNumBuilder: ...

class ClientBadgeNumBuilder:
    def __init__(self) -> None: ...
    def web_app(self, web_app: int) -> ClientBadgeNumBuilder: ...
    def gadget(self, gadget: int) -> ClientBadgeNumBuilder: ...
    def build(self) -> ClientBadgeNum: ...
