from .application_app_contacts_range import ApplicationAppContactsRange as ApplicationAppContactsRange
from lark_oapi.core.construct import init as init

class ContactsRangeSuggestApplicationAppVersionResponseBody:
    contacts_range: ApplicationAppContactsRange | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ContactsRangeSuggestApplicationAppVersionResponseBodyBuilder: ...

class ContactsRangeSuggestApplicationAppVersionResponseBodyBuilder:
    def __init__(self) -> None: ...
    def contacts_range(self, contacts_range: ApplicationAppContactsRange) -> ContactsRangeSuggestApplicationAppVersionResponseBodyBuilder: ...
    def build(self) -> ContactsRangeSuggestApplicationAppVersionResponseBody: ...
