from lark_oapi.core.construct import init as init

class EventAndCallbackEncryptStrategy:
    encryption_key: str | None
    verification_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EventAndCallbackEncryptStrategyBuilder: ...

class EventAndCallbackEncryptStrategyBuilder:
    def __init__(self) -> None: ...
    def encryption_key(self, encryption_key: str) -> EventAndCallbackEncryptStrategyBuilder: ...
    def verification_token(self, verification_token: str) -> EventAndCallbackEncryptStrategyBuilder: ...
    def build(self) -> EventAndCallbackEncryptStrategy: ...
