from lark_oapi.core.construct import init as init

class Event:
    event_type: str | None
    event_name: str | None
    event_description: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EventBuilder: ...

class EventBuilder:
    def __init__(self) -> None: ...
    def event_type(self, event_type: str) -> EventBuilder: ...
    def event_name(self, event_name: str) -> EventBuilder: ...
    def event_description(self, event_description: str) -> EventBuilder: ...
    def build(self) -> Event: ...
