from lark_oapi.core.construct import init as init

class GetApplicationCollaboratorsRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetApplicationCollaboratorsRequestBodyBuilder: ...

class GetApplicationCollaboratorsRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetApplicationCollaboratorsRequestBody: ...
