from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetApplicationCollaboratorsRequest(BaseRequest):
    user_id_type: str | None
    app_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetApplicationCollaboratorsRequestBuilder: ...

class GetApplicationCollaboratorsRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> GetApplicationCollaboratorsRequestBuilder: ...
    def app_id(self, app_id: str) -> GetApplicationCollaboratorsRequestBuilder: ...
    def build(self) -> GetApplicationCollaboratorsRequest: ...
