from .app_collaborator import AppCollaborator as AppCollaborator
from lark_oapi.core.construct import init as init

class GetApplicationCollaboratorsResponseBody:
    collaborators: list[AppCollaborator] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetApplicationCollaboratorsResponseBodyBuilder: ...

class GetApplicationCollaboratorsResponseBodyBuilder:
    def __init__(self) -> None: ...
    def collaborators(self, collaborators: list[AppCollaborator]) -> GetApplicationCollaboratorsResponseBodyBuilder: ...
    def build(self) -> GetApplicationCollaboratorsResponseBody: ...
