from .application_app_version import ApplicationAppVersion as ApplicationAppVersion
from lark_oapi.core.construct import init as init

class GetApplicationAppVersionResponseBody:
    app_version: ApplicationAppVersion | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetApplicationAppVersionResponseBodyBuilder: ...

class GetApplicationAppVersionResponseBodyBuilder:
    def __init__(self) -> None: ...
    def app_version(self, app_version: ApplicationAppVersion) -> GetApplicationAppVersionResponseBodyBuilder: ...
    def build(self) -> GetApplicationAppVersionResponseBody: ...
