from lark_oapi.core.construct import init as init

class ListAppRecommendRuleRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListAppRecommendRuleRequestBodyBuilder: ...

class ListAppRecommendRuleRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListAppRecommendRuleRequestBody: ...
