from .app_recommend_rule import AppRecommendRule as AppRecommendRule
from lark_oapi.core.construct import init as init

class ListAppRecommendRuleResponseBody:
    rules: list[AppRecommendRule] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListAppRecommendRuleResponseBodyBuilder: ...

class ListAppRecommendRuleResponseBodyBuilder:
    def __init__(self) -> None: ...
    def rules(self, rules: list[AppRecommendRule]) -> ListAppRecommendRuleResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListAppRecommendRuleResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListAppRecommendRuleResponseBodyBuilder: ...
    def build(self) -> ListAppRecommendRuleResponseBody: ...
