from lark_oapi.core.construct import init as init

class ListApplicationAppVersionRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListApplicationAppVersionRequestBodyBuilder: ...

class ListApplicationAppVersionRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListApplicationAppVersionRequestBody: ...
