from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListScopeRequest(BaseRequest):
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListScopeRequestBuilder: ...

class ListScopeRequestBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListScopeRequest: ...
