from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListApplicationRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    user_id_type: str | None
    lang: str | None
    status: int | None
    payment_type: int | None
    owner_type: int | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListApplicationRequestBuilder: ...

class ListApplicationRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> ListApplicationRequestBuilder: ...
    def page_token(self, page_token: str) -> ListApplicationRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> ListApplicationRequestBuilder: ...
    def lang(self, lang: str) -> ListApplicationRequestBuilder: ...
    def status(self, status: int) -> ListApplicationRequestBuilder: ...
    def payment_type(self, payment_type: int) -> ListApplicationRequestBuilder: ...
    def owner_type(self, owner_type: int) -> ListApplicationRequestBuilder: ...
    def build(self) -> ListApplicationRequest: ...
