from lark_oapi.core.construct import init as init

class Miniprogram:
    enable_pc_mode: int | None
    schema_urls: list[str] | None
    pc_use_mobile_pkg: bool | None
    pc_version_id: str | None
    mobile_version_id: str | None
    mobile_min_lark_version: str | None
    pc_min_lark_version: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MiniprogramBuilder: ...

class MiniprogramBuilder:
    def __init__(self) -> None: ...
    def enable_pc_mode(self, enable_pc_mode: int) -> MiniprogramBuilder: ...
    def schema_urls(self, schema_urls: list[str]) -> MiniprogramBuilder: ...
    def pc_use_mobile_pkg(self, pc_use_mobile_pkg: bool) -> MiniprogramBuilder: ...
    def pc_version_id(self, pc_version_id: str) -> MiniprogramBuilder: ...
    def mobile_version_id(self, mobile_version_id: str) -> MiniprogramBuilder: ...
    def mobile_min_lark_version(self, mobile_min_lark_version: str) -> MiniprogramBuilder: ...
    def pc_min_lark_version(self, pc_min_lark_version: str) -> MiniprogramBuilder: ...
    def build(self) -> Miniprogram: ...
