from .user_id import UserId as UserId
from lark_oapi.core.construct import init as init

class Operator:
    operator_name: str | None
    operator_id: UserId | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OperatorBuilder: ...

class OperatorBuilder:
    def __init__(self) -> None: ...
    def operator_name(self, operator_name: str) -> OperatorBuilder: ...
    def operator_id(self, operator_id: UserId) -> OperatorBuilder: ...
    def build(self) -> Operator: ...
