from lark_oapi.core.construct import init as init

class PatchApplicationContactsRangeResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchApplicationContactsRangeResponseBodyBuilder: ...

class PatchApplicationContactsRangeResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> PatchApplicationContactsRangeResponseBody: ...
