from lark_oapi.core.construct import init as init

class PatchApplicationAppVersionResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchApplicationAppVersionResponseBodyBuilder: ...

class PatchApplicationAppVersionResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> PatchApplicationAppVersionResponseBody: ...
