from .app_contacts_range_id_list import AppContactsRangeIdList as AppContactsRangeIdList
from lark_oapi.core.construct import init as init

class PatchApplicationContactsRangeRequestBody:
    contacts_range_type: str | None
    add_visible_list: AppContactsRangeIdList | None
    del_visible_list: AppContactsRangeIdList | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchApplicationContactsRangeRequestBodyBuilder: ...

class PatchApplicationContactsRangeRequestBodyBuilder:
    def __init__(self) -> None: ...
    def contacts_range_type(self, contacts_range_type: str) -> PatchApplicationContactsRangeRequestBodyBuilder: ...
    def add_visible_list(self, add_visible_list: AppContactsRangeIdList) -> PatchApplicationContactsRangeRequestBodyBuilder: ...
    def del_visible_list(self, del_visible_list: AppContactsRangeIdList) -> PatchApplicationContactsRangeRequestBodyBuilder: ...
    def build(self) -> PatchApplicationContactsRangeRequestBody: ...
