from .patch_application_visibility_request_body import PatchApplicationVisibilityRequestBody as PatchApplicationVisibilityRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PatchApplicationVisibilityRequest(BaseRequest):
    department_id_type: str | None
    user_id_type: str | None
    app_id: str | None
    request_body: PatchApplicationVisibilityRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PatchApplicationVisibilityRequestBuilder: ...

class PatchApplicationVisibilityRequestBuilder:
    def __init__(self) -> None: ...
    def department_id_type(self, department_id_type: str) -> PatchApplicationVisibilityRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> PatchApplicationVisibilityRequestBuilder: ...
    def app_id(self, app_id: str) -> PatchApplicationVisibilityRequestBuilder: ...
    def request_body(self, request_body: PatchApplicationVisibilityRequestBody) -> PatchApplicationVisibilityRequestBuilder: ...
    def build(self) -> PatchApplicationVisibilityRequest: ...
