from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UnderauditlistApplicationRequest(BaseRequest):
    lang: str | None
    page_token: str | None
    page_size: int | None
    user_id_type: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UnderauditlistApplicationRequestBuilder: ...

class UnderauditlistApplicationRequestBuilder:
    def __init__(self) -> None: ...
    def lang(self, lang: str) -> UnderauditlistApplicationRequestBuilder: ...
    def page_token(self, page_token: str) -> UnderauditlistApplicationRequestBuilder: ...
    def page_size(self, page_size: int) -> UnderauditlistApplicationRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> UnderauditlistApplicationRequestBuilder: ...
    def build(self) -> UnderauditlistApplicationRequest: ...
