from lark_oapi.core.construct import init as init

class UnderauditlistApplicationRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UnderauditlistApplicationRequestBodyBuilder: ...

class UnderauditlistApplicationRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> UnderauditlistApplicationRequestBody: ...
