from lark_oapi.core.construct import init as init

class UpdateApplicationManagementResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateApplicationManagementResponseBodyBuilder: ...

class UpdateApplicationManagementResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> UpdateApplicationManagementResponseBody: ...
