from lark_oapi.core.construct import init as init

class UsageOverviewItem:
    page_view: int | None
    unique_visitor: int | None
    department_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UsageOverviewItemBuilder: ...

class UsageOverviewItemBuilder:
    def __init__(self) -> None: ...
    def page_view(self, page_view: int) -> UsageOverviewItemBuilder: ...
    def unique_visitor(self, unique_visitor: int) -> UsageOverviewItemBuilder: ...
    def department_id(self, department_id: str) -> UsageOverviewItemBuilder: ...
    def build(self) -> UsageOverviewItem: ...
