from lark_oapi.core.construct import init as init

class WebApp:
    pc_url: str | None
    mobile_url: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WebAppBuilder: ...

class WebAppBuilder:
    def __init__(self) -> None: ...
    def pc_url(self, pc_url: str) -> WebAppBuilder: ...
    def mobile_url(self, mobile_url: str) -> WebAppBuilder: ...
    def build(self) -> WebApp: ...
