from lark_oapi.core.construct import init as init

class WorkplaceWidget:
    min_lark_version: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WorkplaceWidgetBuilder: ...

class WorkplaceWidgetBuilder:
    def __init__(self) -> None: ...
    def min_lark_version(self, min_lark_version: str) -> WorkplaceWidgetBuilder: ...
    def build(self) -> WorkplaceWidget: ...
