from lark_oapi.core.construct import init as init

class Attatchment:
    guid: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AttatchmentBuilder: ...

class AttatchmentBuilder:
    def __init__(self) -> None: ...
    def guid(self, guid: str) -> AttatchmentBuilder: ...
    def build(self) -> Attatchment: ...
