from lark_oapi.core.construct import init as init

class BatchDeleteFollowerTaskResponseBody:
    followers: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchDeleteFollowerTaskResponseBodyBuilder: ...

class BatchDeleteFollowerTaskResponseBodyBuilder:
    def __init__(self) -> None: ...
    def followers(self, followers: list[str]) -> BatchDeleteFollowerTaskResponseBodyBuilder: ...
    def build(self) -> BatchDeleteFollowerTaskResponseBody: ...
