from .follower import Follower as Follower
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchDeleteFollowerTaskRequest(BaseRequest):
    user_id_type: str | None
    task_id: str | None
    request_body: Follower | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchDeleteFollowerTaskRequestBuilder: ...

class BatchDeleteFollowerTaskRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> BatchDeleteFollowerTaskRequestBuilder: ...
    def task_id(self, task_id: str) -> BatchDeleteFollowerTaskRequestBuilder: ...
    def request_body(self, request_body: Follower) -> BatchDeleteFollowerTaskRequestBuilder: ...
    def build(self) -> BatchDeleteFollowerTaskRequest: ...
