from lark_oapi.core.construct import init as init

class Collaborator:
    id: str | None
    id_list: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CollaboratorBuilder: ...

class CollaboratorBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> CollaboratorBuilder: ...
    def id_list(self, id_list: list[str]) -> CollaboratorBuilder: ...
    def build(self) -> Collaborator: ...
