from lark_oapi.core.construct import init as init

class Comment:
    content: str | None
    parent_id: int | None
    id: int | None
    create_milli_time: int | None
    rich_content: str | None
    creator_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CommentBuilder: ...

class CommentBuilder:
    def __init__(self) -> None: ...
    def content(self, content: str) -> CommentBuilder: ...
    def parent_id(self, parent_id: int) -> CommentBuilder: ...
    def id(self, id: int) -> CommentBuilder: ...
    def create_milli_time(self, create_milli_time: int) -> CommentBuilder: ...
    def rich_content(self, rich_content: str) -> CommentBuilder: ...
    def creator_id(self, creator_id: str) -> CommentBuilder: ...
    def build(self) -> Comment: ...
