from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CompleteTaskRequest(BaseRequest):
    task_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CompleteTaskRequestBuilder: ...

class CompleteTaskRequestBuilder:
    def __init__(self) -> None: ...
    def task_id(self, task_id: str) -> CompleteTaskRequestBuilder: ...
    def build(self) -> CompleteTaskRequest: ...
