from .collaborator import Collaborator as Collaborator
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateTaskCollaboratorRequest(BaseRequest):
    user_id_type: str | None
    task_id: str | None
    request_body: Collaborator | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateTaskCollaboratorRequestBuilder: ...

class CreateTaskCollaboratorRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> CreateTaskCollaboratorRequestBuilder: ...
    def task_id(self, task_id: str) -> CreateTaskCollaboratorRequestBuilder: ...
    def request_body(self, request_body: Collaborator) -> CreateTaskCollaboratorRequestBuilder: ...
    def build(self) -> CreateTaskCollaboratorRequest: ...
