from .comment import Comment as Comment
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateTaskCommentRequest(BaseRequest):
    user_id_type: str | None
    task_id: str | None
    request_body: Comment | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateTaskCommentRequestBuilder: ...

class CreateTaskCommentRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> CreateTaskCommentRequestBuilder: ...
    def task_id(self, task_id: str) -> CreateTaskCommentRequestBuilder: ...
    def request_body(self, request_body: Comment) -> CreateTaskCommentRequestBuilder: ...
    def build(self) -> CreateTaskCommentRequest: ...
