from .follower import Follower as Follower
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateTaskFollowerRequest(BaseRequest):
    user_id_type: str | None
    task_id: str | None
    request_body: Follower | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateTaskFollowerRequestBuilder: ...

class CreateTaskFollowerRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> CreateTaskFollowerRequestBuilder: ...
    def task_id(self, task_id: str) -> CreateTaskFollowerRequestBuilder: ...
    def request_body(self, request_body: Follower) -> CreateTaskFollowerRequestBuilder: ...
    def build(self) -> CreateTaskFollowerRequest: ...
