from .reminder import Reminder as Reminder
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateTaskReminderRequest(BaseRequest):
    task_id: str | None
    request_body: Reminder | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateTaskReminderRequestBuilder: ...

class CreateTaskReminderRequestBuilder:
    def __init__(self) -> None: ...
    def task_id(self, task_id: str) -> CreateTaskReminderRequestBuilder: ...
    def request_body(self, request_body: Reminder) -> CreateTaskReminderRequestBuilder: ...
    def build(self) -> CreateTaskReminderRequest: ...
