from lark_oapi.core.construct import init as init

class DeleteTaskCommentRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteTaskCommentRequestBodyBuilder: ...

class DeleteTaskCommentRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteTaskCommentRequestBody: ...
