from lark_oapi.core.construct import init as init

class DeleteTaskRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteTaskRequestBodyBuilder: ...

class DeleteTaskRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteTaskRequestBody: ...
