from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetTaskCommentRequest(BaseRequest):
    user_id_type: str | None
    task_id: str | None
    comment_id: int | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetTaskCommentRequestBuilder: ...

class GetTaskCommentRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> GetTaskCommentRequestBuilder: ...
    def task_id(self, task_id: str) -> GetTaskCommentRequestBuilder: ...
    def comment_id(self, comment_id: int) -> GetTaskCommentRequestBuilder: ...
    def build(self) -> GetTaskCommentRequest: ...
