from .comment import Comment as Comment
from lark_oapi.core.construct import init as init

class GetTaskCommentResponseBody:
    comment: Comment | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetTaskCommentResponseBodyBuilder: ...

class GetTaskCommentResponseBodyBuilder:
    def __init__(self) -> None: ...
    def comment(self, comment: Comment) -> GetTaskCommentResponseBodyBuilder: ...
    def build(self) -> GetTaskCommentResponseBody: ...
