from .follower import Follower as Follower
from lark_oapi.core.construct import init as init

class ListTaskFollowerResponseBody:
    items: list[Follower] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListTaskFollowerResponseBodyBuilder: ...

class ListTaskFollowerResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[Follower]) -> ListTaskFollowerResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListTaskFollowerResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListTaskFollowerResponseBodyBuilder: ...
    def build(self) -> ListTaskFollowerResponseBody: ...
