from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListTaskFollowerRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    user_id_type: str | None
    task_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListTaskFollowerRequestBuilder: ...

class ListTaskFollowerRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> ListTaskFollowerRequestBuilder: ...
    def page_token(self, page_token: str) -> ListTaskFollowerRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> ListTaskFollowerRequestBuilder: ...
    def task_id(self, task_id: str) -> ListTaskFollowerRequestBuilder: ...
    def build(self) -> ListTaskFollowerRequest: ...
