from lark_oapi.core.construct import init as init

class ListTaskFollowerRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListTaskFollowerRequestBodyBuilder: ...

class ListTaskFollowerRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListTaskFollowerRequestBody: ...
