from .href import Href as Href
from lark_oapi.core.construct import init as init

class Origin:
    platform_i18n_name: str | None
    href: Href | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OriginBuilder: ...

class OriginBuilder:
    def __init__(self) -> None: ...
    def platform_i18n_name(self, platform_i18n_name: str) -> OriginBuilder: ...
    def href(self, href: Href) -> OriginBuilder: ...
    def build(self) -> Origin: ...
