from lark_oapi.core.construct import init as init

class Tasklist:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TasklistBuilder: ...

class TasklistBuilder:
    def __init__(self) -> None: ...
    def build(self) -> Tasklist: ...
