from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UncompleteTaskRequest(BaseRequest):
    task_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UncompleteTaskRequestBuilder: ...

class UncompleteTaskRequestBuilder:
    def __init__(self) -> None: ...
    def task_id(self, task_id: str) -> UncompleteTaskRequestBuilder: ...
    def build(self) -> UncompleteTaskRequest: ...
