from lark_oapi.core.construct import init as init

class UncompleteTaskResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UncompleteTaskResponseBodyBuilder: ...

class UncompleteTaskResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> UncompleteTaskResponseBody: ...
