from lark_oapi.core.construct import init as init

class AgentSkillRule:
    id: str | None
    selected_operator: int | None
    operator_options: list[int] | None
    operand: str | None
    category: int | None
    display_name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AgentSkillRuleBuilder: ...

class AgentSkillRuleBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> AgentSkillRuleBuilder: ...
    def selected_operator(self, selected_operator: int) -> AgentSkillRuleBuilder: ...
    def operator_options(self, operator_options: list[int]) -> AgentSkillRuleBuilder: ...
    def operand(self, operand: str) -> AgentSkillRuleBuilder: ...
    def category(self, category: int) -> AgentSkillRuleBuilder: ...
    def display_name(self, display_name: str) -> AgentSkillRuleBuilder: ...
    def build(self) -> AgentSkillRule: ...
