from lark_oapi.core.construct import init as init

class AgentEmailAgentRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AgentEmailAgentRequestBodyBuilder: ...

class AgentEmailAgentRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> AgentEmailAgentRequestBody: ...
