from .agent_skill_less_info import AgentSkillLessInfo as AgentSkillLessInfo
from .agent_user import AgentUser as AgentUser
from .weekday_schedule import WeekdaySchedule as WeekdaySchedule
from lark_oapi.core.construct import init as init

class AgentSchedules:
    status: int | None
    agent: AgentUser | None
    schedule: list[WeekdaySchedule] | None
    agent_skills: list[AgentSkillLessInfo] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AgentSchedulesBuilder: ...

class AgentSchedulesBuilder:
    def __init__(self) -> None: ...
    def status(self, status: int) -> AgentSchedulesBuilder: ...
    def agent(self, agent: AgentUser) -> AgentSchedulesBuilder: ...
    def schedule(self, schedule: list[WeekdaySchedule]) -> AgentSchedulesBuilder: ...
    def agent_skills(self, agent_skills: list[AgentSkillLessInfo]) -> AgentSchedulesBuilder: ...
    def build(self) -> AgentSchedules: ...
