from lark_oapi.core.construct import init as init

class BotMessage:
    msg_type: str | None
    content: str | None
    receiver_id: str | None
    receive_type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BotMessageBuilder: ...

class BotMessageBuilder:
    def __init__(self) -> None: ...
    def msg_type(self, msg_type: str) -> BotMessageBuilder: ...
    def content(self, content: str) -> BotMessageBuilder: ...
    def receiver_id(self, receiver_id: str) -> BotMessageBuilder: ...
    def receive_type(self, receive_type: str) -> BotMessageBuilder: ...
    def build(self) -> BotMessage: ...
