from lark_oapi.core.construct import init as init

class CancelSendNotificationRequestBody:
    is_recall: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CancelSendNotificationRequestBodyBuilder: ...

class CancelSendNotificationRequestBodyBuilder:
    def __init__(self) -> None: ...
    def is_recall(self, is_recall: bool) -> CancelSendNotificationRequestBodyBuilder: ...
    def build(self) -> CancelSendNotificationRequestBody: ...
