from lark_oapi.core.construct import init as init

class CancelSendNotificationResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CancelSendNotificationResponseBodyBuilder: ...

class CancelSendNotificationResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> CancelSendNotificationResponseBody: ...
