from lark_oapi.core.construct import init as init

class CancelApproveNotificationRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CancelApproveNotificationRequestBodyBuilder: ...

class CancelApproveNotificationRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> CancelApproveNotificationRequestBody: ...
