from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CancelApproveNotificationRequest(BaseRequest):
    notification_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CancelApproveNotificationRequestBuilder: ...

class CancelApproveNotificationRequestBuilder:
    def __init__(self) -> None: ...
    def notification_id(self, notification_id: str) -> CancelApproveNotificationRequestBuilder: ...
    def build(self) -> CancelApproveNotificationRequest: ...
