from .cancel_send_notification_request_body import CancelSendNotificationRequestBody as CancelSendNotificationRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CancelSendNotificationRequest(BaseRequest):
    notification_id: str | None
    request_body: CancelSendNotificationRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CancelSendNotificationRequestBuilder: ...

class CancelSendNotificationRequestBuilder:
    def __init__(self) -> None: ...
    def notification_id(self, notification_id: str) -> CancelSendNotificationRequestBuilder: ...
    def request_body(self, request_body: CancelSendNotificationRequestBody) -> CancelSendNotificationRequestBuilder: ...
    def build(self) -> CancelSendNotificationRequest: ...
