from lark_oapi.core.construct import init as init

class Category:
    category_id: str | None
    id: str | None
    name: str | None
    parent_id: str | None
    helpdesk_id: str | None
    language: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CategoryBuilder: ...

class CategoryBuilder:
    def __init__(self) -> None: ...
    def category_id(self, category_id: str) -> CategoryBuilder: ...
    def id(self, id: str) -> CategoryBuilder: ...
    def name(self, name: str) -> CategoryBuilder: ...
    def parent_id(self, parent_id: str) -> CategoryBuilder: ...
    def helpdesk_id(self, helpdesk_id: str) -> CategoryBuilder: ...
    def language(self, language: str) -> CategoryBuilder: ...
    def build(self) -> Category: ...
