from .create_faq_request_body import CreateFaqRequestBody as CreateFaqRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateFaqRequest(BaseRequest):
    request_body: CreateFaqRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateFaqRequestBuilder: ...

class CreateFaqRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: CreateFaqRequestBody) -> CreateFaqRequestBuilder: ...
    def build(self) -> CreateFaqRequest: ...
