from lark_oapi.core.construct import init as init

class CreateBotMessageResponseBody:
    message_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateBotMessageResponseBodyBuilder: ...

class CreateBotMessageResponseBodyBuilder:
    def __init__(self) -> None: ...
    def message_id(self, message_id: str) -> CreateBotMessageResponseBodyBuilder: ...
    def build(self) -> CreateBotMessageResponseBody: ...
