from lark_oapi.core.construct import init as init

class CreateTicketMessageResponseBody:
    message_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateTicketMessageResponseBodyBuilder: ...

class CreateTicketMessageResponseBodyBuilder:
    def __init__(self) -> None: ...
    def message_id(self, message_id: str) -> CreateTicketMessageResponseBodyBuilder: ...
    def build(self) -> CreateTicketMessageResponseBody: ...
