from .faq_create_info import FaqCreateInfo as FaqCreateInfo
from lark_oapi.core.construct import init as init

class CreateFaqRequestBody:
    faq: FaqCreateInfo | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateFaqRequestBodyBuilder: ...

class CreateFaqRequestBodyBuilder:
    def __init__(self) -> None: ...
    def faq(self, faq: FaqCreateInfo) -> CreateFaqRequestBodyBuilder: ...
    def build(self) -> CreateFaqRequestBody: ...
