from .faq import Faq as Faq
from lark_oapi.core.construct import init as init

class CreateFaqResponseBody:
    faq: Faq | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateFaqResponseBodyBuilder: ...

class CreateFaqResponseBodyBuilder:
    def __init__(self) -> None: ...
    def faq(self, faq: Faq) -> CreateFaqResponseBodyBuilder: ...
    def build(self) -> CreateFaqResponseBody: ...
