from lark_oapi.core.construct import init as init

class CreateAgentSkillResponseBody:
    agent_skill_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateAgentSkillResponseBodyBuilder: ...

class CreateAgentSkillResponseBodyBuilder:
    def __init__(self) -> None: ...
    def agent_skill_id(self, agent_skill_id: str) -> CreateAgentSkillResponseBodyBuilder: ...
    def build(self) -> CreateAgentSkillResponseBody: ...
