from .agent_skill_rule import AgentSkillRule as AgentSkillRule
from lark_oapi.core.construct import init as init

class CreateAgentSkillRequestBody:
    name: str | None
    rules: list[AgentSkillRule] | None
    agent_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateAgentSkillRequestBodyBuilder: ...

class CreateAgentSkillRequestBodyBuilder:
    def __init__(self) -> None: ...
    def name(self, name: str) -> CreateAgentSkillRequestBodyBuilder: ...
    def rules(self, rules: list[AgentSkillRule]) -> CreateAgentSkillRequestBodyBuilder: ...
    def agent_ids(self, agent_ids: list[str]) -> CreateAgentSkillRequestBodyBuilder: ...
    def build(self) -> CreateAgentSkillRequestBody: ...
