from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CustomizedFieldsTicketRequest(BaseRequest):
    visible_only: bool | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CustomizedFieldsTicketRequestBuilder: ...

class CustomizedFieldsTicketRequestBuilder:
    def __init__(self) -> None: ...
    def visible_only(self, visible_only: bool) -> CustomizedFieldsTicketRequestBuilder: ...
    def build(self) -> CustomizedFieldsTicketRequest: ...
