from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteAgentSkillRequest(BaseRequest):
    agent_skill_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteAgentSkillRequestBuilder: ...

class DeleteAgentSkillRequestBuilder:
    def __init__(self) -> None: ...
    def agent_skill_id(self, agent_skill_id: str) -> DeleteAgentSkillRequestBuilder: ...
    def build(self) -> DeleteAgentSkillRequest: ...
