from lark_oapi.core.construct import init as init

class DeleteTicketCustomizedFieldResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteTicketCustomizedFieldResponseBodyBuilder: ...

class DeleteTicketCustomizedFieldResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteTicketCustomizedFieldResponseBody: ...
