from lark_oapi.core.construct import init as init

class DeleteAgentSchedulesRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteAgentSchedulesRequestBodyBuilder: ...

class DeleteAgentSchedulesRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteAgentSchedulesRequestBody: ...
