from lark_oapi.core.construct import init as init

class DeleteAgentSkillRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteAgentSkillRequestBodyBuilder: ...

class DeleteAgentSkillRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteAgentSkillRequestBody: ...
