from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteFaqRequest(BaseRequest):
    id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteFaqRequestBuilder: ...

class DeleteFaqRequestBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> DeleteFaqRequestBuilder: ...
    def build(self) -> DeleteFaqRequest: ...
