from lark_oapi.core.construct import init as init

class DeleteAgentSchedulesResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteAgentSchedulesResponseBodyBuilder: ...

class DeleteAgentSchedulesResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteAgentSchedulesResponseBody: ...
