from lark_oapi.core.construct import init as init

class DeleteCategoryResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteCategoryResponseBodyBuilder: ...

class DeleteCategoryResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteCategoryResponseBody: ...
