from lark_oapi.core.construct import init as init

class DeleteCategoryRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteCategoryRequestBodyBuilder: ...

class DeleteCategoryRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteCategoryRequestBody: ...
