from lark_oapi.core.construct import init as init

class DeleteFaqRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteFaqRequestBodyBuilder: ...

class DeleteFaqRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteFaqRequestBody: ...
