from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteTicketCustomizedFieldRequest(BaseRequest):
    ticket_customized_field_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteTicketCustomizedFieldRequestBuilder: ...

class DeleteTicketCustomizedFieldRequestBuilder:
    def __init__(self) -> None: ...
    def ticket_customized_field_id(self, ticket_customized_field_id: str) -> DeleteTicketCustomizedFieldRequestBuilder: ...
    def build(self) -> DeleteTicketCustomizedFieldRequest: ...
