from lark_oapi.core.construct import init as init

class ExecuteSendNotificationResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ExecuteSendNotificationResponseBodyBuilder: ...

class ExecuteSendNotificationResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ExecuteSendNotificationResponseBody: ...
