from lark_oapi.core.construct import init as init

class FaqCreateInfo:
    category_id: str | None
    question: str | None
    answer: str | None
    answer_richtext: str | None
    tags: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FaqCreateInfoBuilder: ...

class FaqCreateInfoBuilder:
    def __init__(self) -> None: ...
    def category_id(self, category_id: str) -> FaqCreateInfoBuilder: ...
    def question(self, question: str) -> FaqCreateInfoBuilder: ...
    def answer(self, answer: str) -> FaqCreateInfoBuilder: ...
    def answer_richtext(self, answer_richtext: str) -> FaqCreateInfoBuilder: ...
    def tags(self, tags: list[str]) -> FaqCreateInfoBuilder: ...
    def build(self) -> FaqCreateInfo: ...
