from lark_oapi.core.construct import init as init

class FaqImageFaqRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FaqImageFaqRequestBodyBuilder: ...

class FaqImageFaqRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> FaqImageFaqRequestBody: ...
