from lark_oapi.core.construct import init as init

class GetAgentSchedulesRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetAgentSchedulesRequestBodyBuilder: ...

class GetAgentSchedulesRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetAgentSchedulesRequestBody: ...
