from lark_oapi.core.construct import init as init

class GetTicketRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetTicketRequestBodyBuilder: ...

class GetTicketRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetTicketRequestBody: ...
