from lark_oapi.core.construct import init as init

class GetCategoryRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetCategoryRequestBodyBuilder: ...

class GetCategoryRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetCategoryRequestBody: ...
