from .ticket_v2 import TicketV2 as TicketV2
from lark_oapi.core.construct import init as init

class ListTicketResponseBody:
    total: int | None
    tickets: list[TicketV2] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListTicketResponseBodyBuilder: ...

class ListTicketResponseBodyBuilder:
    def __init__(self) -> None: ...
    def total(self, total: int) -> ListTicketResponseBodyBuilder: ...
    def tickets(self, tickets: list[TicketV2]) -> ListTicketResponseBodyBuilder: ...
    def build(self) -> ListTicketResponseBody: ...
