from lark_oapi.core.construct import init as init

class ListAgentSkillRuleRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListAgentSkillRuleRequestBodyBuilder: ...

class ListAgentSkillRuleRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListAgentSkillRuleRequestBody: ...
