from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListTicketMessageRequest(BaseRequest):
    time_start: int | None
    time_end: int | None
    page: int | None
    page_size: int | None
    ticket_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListTicketMessageRequestBuilder: ...

class ListTicketMessageRequestBuilder:
    def __init__(self) -> None: ...
    def time_start(self, time_start: int) -> ListTicketMessageRequestBuilder: ...
    def time_end(self, time_end: int) -> ListTicketMessageRequestBuilder: ...
    def page(self, page: int) -> ListTicketMessageRequestBuilder: ...
    def page_size(self, page_size: int) -> ListTicketMessageRequestBuilder: ...
    def ticket_id(self, ticket_id: str) -> ListTicketMessageRequestBuilder: ...
    def build(self) -> ListTicketMessageRequest: ...
