from .agent_skill import AgentSkill as AgentSkill
from lark_oapi.core.construct import init as init

class ListAgentSkillResponseBody:
    agent_skills: list[AgentSkill] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListAgentSkillResponseBodyBuilder: ...

class ListAgentSkillResponseBodyBuilder:
    def __init__(self) -> None: ...
    def agent_skills(self, agent_skills: list[AgentSkill]) -> ListAgentSkillResponseBodyBuilder: ...
    def build(self) -> ListAgentSkillResponseBody: ...
