from lark_oapi.core.construct import init as init

class ListAgentScheduleRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListAgentScheduleRequestBodyBuilder: ...

class ListAgentScheduleRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListAgentScheduleRequestBody: ...
