from .agent_schedule import AgentSchedule as AgentSchedule
from lark_oapi.core.construct import init as init

class ListAgentScheduleResponseBody:
    agent_schedules: list[AgentSchedule] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListAgentScheduleResponseBodyBuilder: ...

class ListAgentScheduleResponseBodyBuilder:
    def __init__(self) -> None: ...
    def agent_schedules(self, agent_schedules: list[AgentSchedule]) -> ListAgentScheduleResponseBodyBuilder: ...
    def build(self) -> ListAgentScheduleResponseBody: ...
