from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListTicketRequest(BaseRequest):
    ticket_id: str | None
    agent_id: str | None
    closed_by_id: str | None
    type: int | None
    channel: int | None
    solved: int | None
    score: int | None
    status_list: list[int] | None
    guest_name: str | None
    guest_id: str | None
    tags: list[str] | None
    page: int | None
    page_size: int | None
    create_time_start: int | None
    create_time_end: int | None
    update_time_start: int | None
    update_time_end: int | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListTicketRequestBuilder: ...

class ListTicketRequestBuilder:
    def __init__(self) -> None: ...
    def ticket_id(self, ticket_id: str) -> ListTicketRequestBuilder: ...
    def agent_id(self, agent_id: str) -> ListTicketRequestBuilder: ...
    def closed_by_id(self, closed_by_id: str) -> ListTicketRequestBuilder: ...
    def type(self, type: int) -> ListTicketRequestBuilder: ...
    def channel(self, channel: int) -> ListTicketRequestBuilder: ...
    def solved(self, solved: int) -> ListTicketRequestBuilder: ...
    def score(self, score: int) -> ListTicketRequestBuilder: ...
    def status_list(self, status_list: list[int]) -> ListTicketRequestBuilder: ...
    def guest_name(self, guest_name: str) -> ListTicketRequestBuilder: ...
    def guest_id(self, guest_id: str) -> ListTicketRequestBuilder: ...
    def tags(self, tags: list[str]) -> ListTicketRequestBuilder: ...
    def page(self, page: int) -> ListTicketRequestBuilder: ...
    def page_size(self, page_size: int) -> ListTicketRequestBuilder: ...
    def create_time_start(self, create_time_start: int) -> ListTicketRequestBuilder: ...
    def create_time_end(self, create_time_end: int) -> ListTicketRequestBuilder: ...
    def update_time_start(self, update_time_start: int) -> ListTicketRequestBuilder: ...
    def update_time_end(self, update_time_end: int) -> ListTicketRequestBuilder: ...
    def build(self) -> ListTicketRequest: ...
