from .ticket_message import TicketMessage as TicketMessage
from lark_oapi.core.construct import init as init

class ListTicketMessageResponseBody:
    messages: list[TicketMessage] | None
    total: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListTicketMessageResponseBodyBuilder: ...

class ListTicketMessageResponseBodyBuilder:
    def __init__(self) -> None: ...
    def messages(self, messages: list[TicketMessage]) -> ListTicketMessageResponseBodyBuilder: ...
    def total(self, total: int) -> ListTicketMessageResponseBodyBuilder: ...
    def build(self) -> ListTicketMessageResponseBody: ...
