from lark_oapi.core.construct import init as init

class ListTicketCustomizedFieldRequestBody:
    visible: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListTicketCustomizedFieldRequestBodyBuilder: ...

class ListTicketCustomizedFieldRequestBodyBuilder:
    def __init__(self) -> None: ...
    def visible(self, visible: bool) -> ListTicketCustomizedFieldRequestBodyBuilder: ...
    def build(self) -> ListTicketCustomizedFieldRequestBody: ...
