from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListAgentScheduleRequest(BaseRequest):
    status: list[int] | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListAgentScheduleRequestBuilder: ...

class ListAgentScheduleRequestBuilder:
    def __init__(self) -> None: ...
    def status(self, status: list[int]) -> ListAgentScheduleRequestBuilder: ...
    def build(self) -> ListAgentScheduleRequest: ...
