from lark_oapi.core.construct import init as init

class ListTicketRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListTicketRequestBodyBuilder: ...

class ListTicketRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListTicketRequestBody: ...
