from lark_oapi.core.construct import init as init

class ListAgentSkillRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListAgentSkillRequestBodyBuilder: ...

class ListAgentSkillRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListAgentSkillRequestBody: ...
