from lark_oapi.core.construct import init as init

class MigrationTicketComment:
    user_id: int | None
    create_at_ms: str | None
    content: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MigrationTicketCommentBuilder: ...

class MigrationTicketCommentBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: int) -> MigrationTicketCommentBuilder: ...
    def create_at_ms(self, create_at_ms: str) -> MigrationTicketCommentBuilder: ...
    def content(self, content: str) -> MigrationTicketCommentBuilder: ...
    def build(self) -> MigrationTicketComment: ...
