from lark_oapi.core.construct import init as init

class NotificationChat:
    chat_id: str | None
    name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> NotificationChatBuilder: ...

class NotificationChatBuilder:
    def __init__(self) -> None: ...
    def chat_id(self, chat_id: str) -> NotificationChatBuilder: ...
    def name(self, name: str) -> NotificationChatBuilder: ...
    def build(self) -> NotificationChat: ...
