from lark_oapi.core.construct import init as init

class PatchAgentRequestBody:
    status: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchAgentRequestBodyBuilder: ...

class PatchAgentRequestBodyBuilder:
    def __init__(self) -> None: ...
    def status(self, status: int) -> PatchAgentRequestBodyBuilder: ...
    def build(self) -> PatchAgentRequestBody: ...
