from .patch_agent_request_body import PatchAgentRequestBody as PatchAgentRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PatchAgentRequest(BaseRequest):
    agent_id: str | None
    request_body: PatchAgentRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PatchAgentRequestBuilder: ...

class PatchAgentRequestBuilder:
    def __init__(self) -> None: ...
    def agent_id(self, agent_id: str) -> PatchAgentRequestBuilder: ...
    def request_body(self, request_body: PatchAgentRequestBody) -> PatchAgentRequestBuilder: ...
    def build(self) -> PatchAgentRequest: ...
