from .patch_agent_skill_request_body import PatchAgentSkillRequestBody as PatchAgentSkillRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PatchAgentSkillRequest(BaseRequest):
    agent_skill_id: str | None
    request_body: PatchAgentSkillRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PatchAgentSkillRequestBuilder: ...

class PatchAgentSkillRequestBuilder:
    def __init__(self) -> None: ...
    def agent_skill_id(self, agent_skill_id: str) -> PatchAgentSkillRequestBuilder: ...
    def request_body(self, request_body: PatchAgentSkillRequestBody) -> PatchAgentSkillRequestBuilder: ...
    def build(self) -> PatchAgentSkillRequest: ...
