from lark_oapi.core.construct import init as init

class PatchNotificationResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchNotificationResponseBodyBuilder: ...

class PatchNotificationResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> PatchNotificationResponseBody: ...
