from lark_oapi.core.construct import init as init

class PatchAgentResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchAgentResponseBodyBuilder: ...

class PatchAgentResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> PatchAgentResponseBody: ...
