from .patch_faq_request_body import PatchFaqRequestBody as PatchFaqRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PatchFaqRequest(BaseRequest):
    id: str | None
    request_body: PatchFaqRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PatchFaqRequestBuilder: ...

class PatchFaqRequestBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> PatchFaqRequestBuilder: ...
    def request_body(self, request_body: PatchFaqRequestBody) -> PatchFaqRequestBuilder: ...
    def build(self) -> PatchFaqRequest: ...
