from .category import Category as Category
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PatchCategoryRequest(BaseRequest):
    id: str | None
    request_body: Category | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PatchCategoryRequestBuilder: ...

class PatchCategoryRequestBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> PatchCategoryRequestBuilder: ...
    def request_body(self, request_body: Category) -> PatchCategoryRequestBuilder: ...
    def build(self) -> PatchCategoryRequest: ...
