from lark_oapi.core.construct import init as init

class PatchAgentSchedulesResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchAgentSchedulesResponseBodyBuilder: ...

class PatchAgentSchedulesResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> PatchAgentSchedulesResponseBody: ...
