from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PreviewNotificationRequest(BaseRequest):
    notification_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PreviewNotificationRequestBuilder: ...

class PreviewNotificationRequestBuilder:
    def __init__(self) -> None: ...
    def notification_id(self, notification_id: str) -> PreviewNotificationRequestBuilder: ...
    def build(self) -> PreviewNotificationRequest: ...
