from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class SearchFaqRequest(BaseRequest):
    query: str | None
    base64: str | None
    page_token: str | None
    page_size: int | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> SearchFaqRequestBuilder: ...

class SearchFaqRequestBuilder:
    def __init__(self) -> None: ...
    def query(self, query: str) -> SearchFaqRequestBuilder: ...
    def base64(self, base64: str) -> SearchFaqRequestBuilder: ...
    def page_token(self, page_token: str) -> SearchFaqRequestBuilder: ...
    def page_size(self, page_size: int) -> SearchFaqRequestBuilder: ...
    def build(self) -> SearchFaqRequest: ...
