from lark_oapi.core.construct import init as init

class SearchFaqRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SearchFaqRequestBodyBuilder: ...

class SearchFaqRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> SearchFaqRequestBody: ...
