from lark_oapi.core.construct import init as init

class StartServiceTicketResponseBody:
    chat_id: str | None
    ticket_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> StartServiceTicketResponseBodyBuilder: ...

class StartServiceTicketResponseBodyBuilder:
    def __init__(self) -> None: ...
    def chat_id(self, chat_id: str) -> StartServiceTicketResponseBodyBuilder: ...
    def ticket_id(self, ticket_id: str) -> StartServiceTicketResponseBodyBuilder: ...
    def build(self) -> StartServiceTicketResponseBody: ...
