from lark_oapi.core.construct import init as init

class SubscribeEventResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SubscribeEventResponseBodyBuilder: ...

class SubscribeEventResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> SubscribeEventResponseBody: ...
