from .subscribe_event_request_body import SubscribeEventRequestBody as SubscribeEventRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class SubscribeEventRequest(BaseRequest):
    request_body: SubscribeEventRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> SubscribeEventRequestBuilder: ...

class SubscribeEventRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: SubscribeEventRequestBody) -> SubscribeEventRequestBuilder: ...
    def build(self) -> SubscribeEventRequest: ...
