from lark_oapi.core.construct import init as init

class TicketImageTicketRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TicketImageTicketRequestBodyBuilder: ...

class TicketImageTicketRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> TicketImageTicketRequestBody: ...
