from lark_oapi.core.construct import init as init

class TicketImageTicketResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TicketImageTicketResponseBodyBuilder: ...

class TicketImageTicketResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> TicketImageTicketResponseBody: ...
