from lark_oapi.core.construct import init as init

class TicketMessageContent:
    content: str | None
    msg_type: str | None
    image_keys: list[str] | None
    image_key: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TicketMessageContentBuilder: ...

class TicketMessageContentBuilder:
    def __init__(self) -> None: ...
    def content(self, content: str) -> TicketMessageContentBuilder: ...
    def msg_type(self, msg_type: str) -> TicketMessageContentBuilder: ...
    def image_keys(self, image_keys: list[str]) -> TicketMessageContentBuilder: ...
    def image_key(self, image_key: str) -> TicketMessageContentBuilder: ...
    def build(self) -> TicketMessageContent: ...
