from lark_oapi.core.construct import init as init

class TicketEventUpdateInfo:
    stage: int | None
    status: int | None
    updated_at: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TicketEventUpdateInfoBuilder: ...

class TicketEventUpdateInfoBuilder:
    def __init__(self) -> None: ...
    def stage(self, stage: int) -> TicketEventUpdateInfoBuilder: ...
    def status(self, status: int) -> TicketEventUpdateInfoBuilder: ...
    def updated_at(self, updated_at: int) -> TicketEventUpdateInfoBuilder: ...
    def build(self) -> TicketEventUpdateInfo: ...
