from .export_ticket_message_content import ExportTicketMessageContent as ExportTicketMessageContent
from lark_oapi.core.construct import init as init

class TicketMessageExportEntity:
    id: str | None
    message_type: str | None
    created_at_ms: str | None
    user_id: int | None
    content: ExportTicketMessageContent | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TicketMessageExportEntityBuilder: ...

class TicketMessageExportEntityBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> TicketMessageExportEntityBuilder: ...
    def message_type(self, message_type: str) -> TicketMessageExportEntityBuilder: ...
    def created_at_ms(self, created_at_ms: str) -> TicketMessageExportEntityBuilder: ...
    def user_id(self, user_id: int) -> TicketMessageExportEntityBuilder: ...
    def content(self, content: ExportTicketMessageContent) -> TicketMessageExportEntityBuilder: ...
    def build(self) -> TicketMessageExportEntity: ...
