from .update_ticket_request_body import UpdateTicketRequestBody as UpdateTicketRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UpdateTicketRequest(BaseRequest):
    ticket_id: str | None
    request_body: UpdateTicketRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UpdateTicketRequestBuilder: ...

class UpdateTicketRequestBuilder:
    def __init__(self) -> None: ...
    def ticket_id(self, ticket_id: str) -> UpdateTicketRequestBuilder: ...
    def request_body(self, request_body: UpdateTicketRequestBody) -> UpdateTicketRequestBuilder: ...
    def build(self) -> UpdateTicketRequest: ...
