from lark_oapi.core.construct import init as init

class UserQueryFaqInfo:
    id: str | None
    score: float | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserQueryFaqInfoBuilder: ...

class UserQueryFaqInfoBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> UserQueryFaqInfoBuilder: ...
    def score(self, score: float) -> UserQueryFaqInfoBuilder: ...
    def build(self) -> UserQueryFaqInfo: ...
