from .create_token_request_body import CreateTokenRequestBody as CreateTokenRequestBody
from lark_oapi.core import HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateIsvAppTokenRequest(BaseRequest):
    request_body: CreateTokenRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateIsvAppTokenRequestBuilder: ...

class CreateIsvAppTokenRequestBuilder:
    def __init__(self, create_isv_app_token_request: CreateIsvAppTokenRequest = ...) -> None: ...
    def request_body(self, request_body: CreateTokenRequestBody) -> CreateIsvAppTokenRequestBuilder: ...
    def build(self) -> CreateIsvAppTokenRequest: ...
