from .create_token_request_body import CreateTokenRequestBody as CreateTokenRequestBody
from lark_oapi.core import HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateIsvTenantTokenRequest(BaseRequest):
    request_body: CreateTokenRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateIsvTenantTokenRequestBuilder: ...

class CreateIsvTenantTokenRequestBuilder:
    def __init__(self, create_isv_tenant_token_request: CreateIsvTenantTokenRequest = ...) -> None: ...
    def request_body(self, request_body: CreateTokenRequestBody) -> CreateIsvTenantTokenRequestBuilder: ...
    def build(self) -> CreateIsvTenantTokenRequest: ...
