from .moto import Moto as Moto
from lark_oapi.core.construct import init as init

class CreateMotoResponseBody:
    moto: Moto | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateMotoResponseBodyBuilder: ...

class CreateMotoResponseBodyBuilder:
    def __init__(self) -> None: ...
    def moto(self, moto: Moto) -> CreateMotoResponseBodyBuilder: ...
    def build(self) -> CreateMotoResponseBody: ...
