from .level import Level as Level
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateMotoRequest(BaseRequest):
    department_id_type: str | None
    user_id_type: str | None
    request_body: Level | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateMotoRequestBuilder: ...

class CreateMotoRequestBuilder:
    def __init__(self) -> None: ...
    def department_id_type(self, department_id_type: str) -> CreateMotoRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> CreateMotoRequestBuilder: ...
    def request_body(self, request_body: Level) -> CreateMotoRequestBuilder: ...
    def build(self) -> CreateMotoRequest: ...
