from lark_oapi.core.construct import init as init

class GetMotoRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetMotoRequestBodyBuilder: ...

class GetMotoRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetMotoRequestBody: ...
