from .moto import Moto as Moto
from lark_oapi.core.construct import init as init

class GetMotoResponseBody:
    moto: Moto | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetMotoResponseBodyBuilder: ...

class GetMotoResponseBodyBuilder:
    def __init__(self) -> None: ...
    def moto(self, moto: Moto) -> GetMotoResponseBodyBuilder: ...
    def build(self) -> GetMotoResponseBody: ...
