from lark_oapi.core.construct import init as init

class Moto:
    moto_id: str | None
    id: str | None
    user_name: str | None
    type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MotoBuilder: ...

class MotoBuilder:
    def __init__(self) -> None: ...
    def moto_id(self, moto_id: str) -> MotoBuilder: ...
    def id(self, id: str) -> MotoBuilder: ...
    def user_name(self, user_name: str) -> MotoBuilder: ...
    def type(self, type: str) -> MotoBuilder: ...
    def build(self) -> Moto: ...
