from .model.p2_drive_file_bitable_field_changed_v1 import P2DriveFileBitableFieldChangedV1 as P2DriveFileBitableFieldChangedV1
from .model.p2_drive_file_bitable_record_changed_v1 import P2DriveFileBitableRecordChangedV1 as P2DriveFileBitableRecordChangedV1
from .model.p2_drive_file_created_in_folder_v1 import P2DriveFileCreatedInFolderV1 as P2DriveFileCreatedInFolderV1
from .model.p2_drive_file_deleted_v1 import P2DriveFileDeletedV1 as P2DriveFileDeletedV1
from .model.p2_drive_file_edit_v1 import P2DriveFileEditV1 as P2DriveFileEditV1
from .model.p2_drive_file_permission_member_added_v1 import P2DriveFilePermissionMemberAddedV1 as P2DriveFilePermissionMemberAddedV1
from .model.p2_drive_file_permission_member_applied_v1 import P2DriveFilePermissionMemberAppliedV1 as P2DriveFilePermissionMemberAppliedV1
from .model.p2_drive_file_permission_member_removed_v1 import P2DriveFilePermissionMemberRemovedV1 as P2DriveFilePermissionMemberRemovedV1
from .model.p2_drive_file_read_v1 import P2DriveFileReadV1 as P2DriveFileReadV1
from .model.p2_drive_file_title_updated_v1 import P2DriveFileTitleUpdatedV1 as P2DriveFileTitleUpdatedV1
from .model.p2_drive_file_trashed_v1 import P2DriveFileTrashedV1 as P2DriveFileTrashedV1
from _typeshed import Incomplete
from lark_oapi.event.processor import IEventProcessor as IEventProcessor
from typing import Callable

class P2DriveFileBitableFieldChangedV1Processor(IEventProcessor[P2DriveFileBitableFieldChangedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2DriveFileBitableFieldChangedV1], None]) -> None: ...
    def type(self) -> type[P2DriveFileBitableFieldChangedV1]: ...
    def do(self, data: P2DriveFileBitableFieldChangedV1) -> None: ...

class P2DriveFileBitableRecordChangedV1Processor(IEventProcessor[P2DriveFileBitableRecordChangedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2DriveFileBitableRecordChangedV1], None]) -> None: ...
    def type(self) -> type[P2DriveFileBitableRecordChangedV1]: ...
    def do(self, data: P2DriveFileBitableRecordChangedV1) -> None: ...

class P2DriveFileCreatedInFolderV1Processor(IEventProcessor[P2DriveFileCreatedInFolderV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2DriveFileCreatedInFolderV1], None]) -> None: ...
    def type(self) -> type[P2DriveFileCreatedInFolderV1]: ...
    def do(self, data: P2DriveFileCreatedInFolderV1) -> None: ...

class P2DriveFileDeletedV1Processor(IEventProcessor[P2DriveFileDeletedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2DriveFileDeletedV1], None]) -> None: ...
    def type(self) -> type[P2DriveFileDeletedV1]: ...
    def do(self, data: P2DriveFileDeletedV1) -> None: ...

class P2DriveFileEditV1Processor(IEventProcessor[P2DriveFileEditV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2DriveFileEditV1], None]) -> None: ...
    def type(self) -> type[P2DriveFileEditV1]: ...
    def do(self, data: P2DriveFileEditV1) -> None: ...

class P2DriveFilePermissionMemberAddedV1Processor(IEventProcessor[P2DriveFilePermissionMemberAddedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2DriveFilePermissionMemberAddedV1], None]) -> None: ...
    def type(self) -> type[P2DriveFilePermissionMemberAddedV1]: ...
    def do(self, data: P2DriveFilePermissionMemberAddedV1) -> None: ...

class P2DriveFilePermissionMemberAppliedV1Processor(IEventProcessor[P2DriveFilePermissionMemberAppliedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2DriveFilePermissionMemberAppliedV1], None]) -> None: ...
    def type(self) -> type[P2DriveFilePermissionMemberAppliedV1]: ...
    def do(self, data: P2DriveFilePermissionMemberAppliedV1) -> None: ...

class P2DriveFilePermissionMemberRemovedV1Processor(IEventProcessor[P2DriveFilePermissionMemberRemovedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2DriveFilePermissionMemberRemovedV1], None]) -> None: ...
    def type(self) -> type[P2DriveFilePermissionMemberRemovedV1]: ...
    def do(self, data: P2DriveFilePermissionMemberRemovedV1) -> None: ...

class P2DriveFileReadV1Processor(IEventProcessor[P2DriveFileReadV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2DriveFileReadV1], None]) -> None: ...
    def type(self) -> type[P2DriveFileReadV1]: ...
    def do(self, data: P2DriveFileReadV1) -> None: ...

class P2DriveFileTitleUpdatedV1Processor(IEventProcessor[P2DriveFileTitleUpdatedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2DriveFileTitleUpdatedV1], None]) -> None: ...
    def type(self) -> type[P2DriveFileTitleUpdatedV1]: ...
    def do(self, data: P2DriveFileTitleUpdatedV1) -> None: ...

class P2DriveFileTrashedV1Processor(IEventProcessor[P2DriveFileTrashedV1]):
    f: Incomplete
    def __init__(self, f: Callable[[P2DriveFileTrashedV1], None]) -> None: ...
    def type(self) -> type[P2DriveFileTrashedV1]: ...
    def do(self, data: P2DriveFileTrashedV1) -> None: ...
