from ..model.create_badge_request import CreateBadgeRequest as CreateBadgeRequest
from ..model.create_badge_response import CreateBadgeResponse as CreateBadgeResponse
from ..model.get_badge_request import GetBadgeRequest as GetBadgeRequest
from ..model.get_badge_response import GetBadgeResponse as GetBadgeResponse
from ..model.list_badge_request import ListBadgeRequest as ListBadgeRequest
from ..model.list_badge_response import ListBadgeResponse as ListBadgeResponse
from ..model.update_badge_request import UpdateBadgeRequest as UpdateBadgeRequest
from ..model.update_badge_response import UpdateBadgeResponse as UpdateBadgeResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class Badge:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def create(self, request: CreateBadgeRequest, option: RequestOption | None = None) -> CreateBadgeResponse: ...
    async def acreate(self, request: CreateBadgeRequest, option: RequestOption | None = None) -> CreateBadgeResponse: ...
    def get(self, request: GetBadgeRequest, option: RequestOption | None = None) -> GetBadgeResponse: ...
    async def aget(self, request: GetBadgeRequest, option: RequestOption | None = None) -> GetBadgeResponse: ...
    def list(self, request: ListBadgeRequest, option: RequestOption | None = None) -> ListBadgeResponse: ...
    async def alist(self, request: ListBadgeRequest, option: RequestOption | None = None) -> ListBadgeResponse: ...
    def update(self, request: UpdateBadgeRequest, option: RequestOption | None = None) -> UpdateBadgeResponse: ...
    async def aupdate(self, request: UpdateBadgeRequest, option: RequestOption | None = None) -> UpdateBadgeResponse: ...
