from lark_oapi.core.construct import init as init

class Common:
    tenant_id: str | None
    languages: list[str] | None
    custom_executors: dict[str, str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CommonBuilder: ...

class CommonBuilder:
    def __init__(self) -> None: ...
    def tenant_id(self, tenant_id: str) -> CommonBuilder: ...
    def languages(self, languages: list[str]) -> CommonBuilder: ...
    def custom_executors(self, custom_executors: dict[str, str]) -> CommonBuilder: ...
    def build(self) -> Common: ...
