from .value import Value as Value
from lark_oapi.core.construct import init as init

class Expression:
    field: str | None
    operator: str | None
    value: Value | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ExpressionBuilder: ...

class ExpressionBuilder:
    def __init__(self) -> None: ...
    def field(self, field: str) -> ExpressionBuilder: ...
    def operator(self, operator: str) -> ExpressionBuilder: ...
    def value(self, value: Value) -> ExpressionBuilder: ...
    def build(self) -> Expression: ...
