from .common import Common as Common
from lark_oapi.core.construct import init as init

class GetBatchCountryRegionRequestBody:
    common: Common | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetBatchCountryRegionRequestBodyBuilder: ...

class GetBatchCountryRegionRequestBodyBuilder:
    def __init__(self) -> None: ...
    def common(self, common: Common) -> GetBatchCountryRegionRequestBodyBuilder: ...
    def build(self) -> GetBatchCountryRegionRequestBody: ...
