from .i18n_string import I18nString as I18nString
from lark_oapi.core.construct import init as init

class Language:
    id: str | None
    update_by: str | None
    create_by: str | None
    update_time: str | None
    create_time: str | None
    ietf_language_tag: str | None
    name: I18nString | None
    enable: bool | None
    mdm_code: str | None
    status: str | None
    system_status: str | None
    remark: str | None
    update_reason: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LanguageBuilder: ...

class LanguageBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> LanguageBuilder: ...
    def update_by(self, update_by: str) -> LanguageBuilder: ...
    def create_by(self, create_by: str) -> LanguageBuilder: ...
    def update_time(self, update_time: str) -> LanguageBuilder: ...
    def create_time(self, create_time: str) -> LanguageBuilder: ...
    def ietf_language_tag(self, ietf_language_tag: str) -> LanguageBuilder: ...
    def name(self, name: I18nString) -> LanguageBuilder: ...
    def enable(self, enable: bool) -> LanguageBuilder: ...
    def mdm_code(self, mdm_code: str) -> LanguageBuilder: ...
    def status(self, status: str) -> LanguageBuilder: ...
    def system_status(self, system_status: str) -> LanguageBuilder: ...
    def remark(self, remark: str) -> LanguageBuilder: ...
    def update_reason(self, update_reason: str) -> LanguageBuilder: ...
    def build(self) -> Language: ...
