from .common import Common as Common
from lark_oapi.core.construct import init as init

class TimeZone:
    update_by: str | None
    create_by: str | None
    update_time: str | None
    create_time: str | None
    time_zone_id: str | None
    name: Common | None
    utc_offset: str | None
    mdm_code: str | None
    remark: str | None
    update_reason: str | None
    status: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TimeZoneBuilder: ...

class TimeZoneBuilder:
    def __init__(self) -> None: ...
    def update_by(self, update_by: str) -> TimeZoneBuilder: ...
    def create_by(self, create_by: str) -> TimeZoneBuilder: ...
    def update_time(self, update_time: str) -> TimeZoneBuilder: ...
    def create_time(self, create_time: str) -> TimeZoneBuilder: ...
    def time_zone_id(self, time_zone_id: str) -> TimeZoneBuilder: ...
    def name(self, name: Common) -> TimeZoneBuilder: ...
    def utc_offset(self, utc_offset: str) -> TimeZoneBuilder: ...
    def mdm_code(self, mdm_code: str) -> TimeZoneBuilder: ...
    def remark(self, remark: str) -> TimeZoneBuilder: ...
    def update_reason(self, update_reason: str) -> TimeZoneBuilder: ...
    def status(self, status: str) -> TimeZoneBuilder: ...
    def build(self) -> TimeZone: ...
