from lark_oapi.core.construct import init as init

class Value:
    string_value: str | None
    bool_value: bool | None
    int_value: str | None
    string_list_value: list[str] | None
    int_list_value: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ValueBuilder: ...

class ValueBuilder:
    def __init__(self) -> None: ...
    def string_value(self, string_value: str) -> ValueBuilder: ...
    def bool_value(self, bool_value: bool) -> ValueBuilder: ...
    def int_value(self, int_value: str) -> ValueBuilder: ...
    def string_list_value(self, string_list_value: list[str]) -> ValueBuilder: ...
    def int_list_value(self, int_list_value: list[str]) -> ValueBuilder: ...
    def build(self) -> Value: ...
