from .batch_update_metric_source_table_item_request_body import BatchUpdateMetricSourceTableItemRequestBody as BatchUpdateMetricSourceTableItemRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchUpdateMetricSourceTableItemRequest(BaseRequest):
    user_id_type: str | None
    metric_source_id: str | None
    metric_table_id: str | None
    request_body: BatchUpdateMetricSourceTableItemRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchUpdateMetricSourceTableItemRequestBuilder: ...

class BatchUpdateMetricSourceTableItemRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> BatchUpdateMetricSourceTableItemRequestBuilder: ...
    def metric_source_id(self, metric_source_id: str) -> BatchUpdateMetricSourceTableItemRequestBuilder: ...
    def metric_table_id(self, metric_table_id: str) -> BatchUpdateMetricSourceTableItemRequestBuilder: ...
    def request_body(self, request_body: BatchUpdateMetricSourceTableItemRequestBody) -> BatchUpdateMetricSourceTableItemRequestBuilder: ...
    def build(self) -> BatchUpdateMetricSourceTableItemRequest: ...
