from .content_image_item import ContentImageItem as ContentImageItem
from lark_oapi.core.construct import init as init

class ContentGallery:
    image_list: list[ContentImageItem] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ContentGalleryBuilder: ...

class ContentGalleryBuilder:
    def __init__(self) -> None: ...
    def image_list(self, image_list: list[ContentImageItem]) -> ContentGalleryBuilder: ...
    def build(self) -> ContentGallery: ...
