from .content_text_style import ContentTextStyle as ContentTextStyle
from lark_oapi.core.construct import init as init

class ContentTextRun:
    text: str | None
    style: ContentTextStyle | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ContentTextRunBuilder: ...

class ContentTextRunBuilder:
    def __init__(self) -> None: ...
    def text(self, text: str) -> ContentTextRunBuilder: ...
    def style(self, style: ContentTextStyle) -> ContentTextRunBuilder: ...
    def build(self) -> ContentTextRun: ...
