from .content_list import ContentList as ContentList
from lark_oapi.core.construct import init as init

class ContentParagraphStyle:
    list: ContentList | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ContentParagraphStyleBuilder: ...

class ContentParagraphStyleBuilder:
    def __init__(self) -> None: ...
    def list(self, list: ContentList) -> ContentParagraphStyleBuilder: ...
    def build(self) -> ContentParagraphStyle: ...
