from lark_oapi.core.construct import init as init

class ContentImageItem:
    file_token: str | None
    src: str | None
    width: float | None
    height: float | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ContentImageItemBuilder: ...

class ContentImageItemBuilder:
    def __init__(self) -> None: ...
    def file_token(self, file_token: str) -> ContentImageItemBuilder: ...
    def src(self, src: str) -> ContentImageItemBuilder: ...
    def width(self, width: float) -> ContentImageItemBuilder: ...
    def height(self, height: float) -> ContentImageItemBuilder: ...
    def build(self) -> ContentImageItem: ...
