from .content_gallery import ContentGallery as ContentGallery
from .content_paragraph import ContentParagraph as ContentParagraph
from lark_oapi.core.construct import init as init

class ContentBlockElement:
    type: str | None
    paragraph: ContentParagraph | None
    gallery: ContentGallery | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ContentBlockElementBuilder: ...

class ContentBlockElementBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> ContentBlockElementBuilder: ...
    def paragraph(self, paragraph: ContentParagraph) -> ContentBlockElementBuilder: ...
    def gallery(self, gallery: ContentGallery) -> ContentBlockElementBuilder: ...
    def build(self) -> ContentBlockElement: ...
