from .content_docs_link import ContentDocsLink as ContentDocsLink
from .content_person import ContentPerson as ContentPerson
from .content_text_run import ContentTextRun as ContentTextRun
from lark_oapi.core.construct import init as init

class ContentParagraphElement:
    type: str | None
    text_run: ContentTextRun | None
    docs_link: ContentDocsLink | None
    person: ContentPerson | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ContentParagraphElementBuilder: ...

class ContentParagraphElementBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> ContentParagraphElementBuilder: ...
    def text_run(self, text_run: ContentTextRun) -> ContentParagraphElementBuilder: ...
    def docs_link(self, docs_link: ContentDocsLink) -> ContentParagraphElementBuilder: ...
    def person(self, person: ContentPerson) -> ContentParagraphElementBuilder: ...
    def build(self) -> ContentParagraphElement: ...
