from lark_oapi.core.construct import init as init

class ContentPerson:
    open_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ContentPersonBuilder: ...

class ContentPersonBuilder:
    def __init__(self) -> None: ...
    def open_id(self, open_id: str) -> ContentPersonBuilder: ...
    def build(self) -> ContentPerson: ...
