from .content_color import ContentColor as ContentColor
from .content_link import ContentLink as ContentLink
from lark_oapi.core.construct import init as init

class ContentTextStyle:
    bold: bool | None
    strike_through: bool | None
    back_color: ContentColor | None
    text_color: ContentColor | None
    link: ContentLink | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ContentTextStyleBuilder: ...

class ContentTextStyleBuilder:
    def __init__(self) -> None: ...
    def bold(self, bold: bool) -> ContentTextStyleBuilder: ...
    def strike_through(self, strike_through: bool) -> ContentTextStyleBuilder: ...
    def back_color(self, back_color: ContentColor) -> ContentTextStyleBuilder: ...
    def text_color(self, text_color: ContentColor) -> ContentTextStyleBuilder: ...
    def link(self, link: ContentLink) -> ContentTextStyleBuilder: ...
    def build(self) -> ContentTextStyle: ...
