from .content_block import ContentBlock as ContentBlock
from lark_oapi.core.construct import init as init

class CreateProgressRecordRequestBody:
    source_title: str | None
    source_url: str | None
    target_id: int | None
    target_type: int | None
    content: ContentBlock | None
    source_url_pc: str | None
    source_url_mobile: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateProgressRecordRequestBodyBuilder: ...

class CreateProgressRecordRequestBodyBuilder:
    def __init__(self) -> None: ...
    def source_title(self, source_title: str) -> CreateProgressRecordRequestBodyBuilder: ...
    def source_url(self, source_url: str) -> CreateProgressRecordRequestBodyBuilder: ...
    def target_id(self, target_id: int) -> CreateProgressRecordRequestBodyBuilder: ...
    def target_type(self, target_type: int) -> CreateProgressRecordRequestBodyBuilder: ...
    def content(self, content: ContentBlock) -> CreateProgressRecordRequestBodyBuilder: ...
    def source_url_pc(self, source_url_pc: str) -> CreateProgressRecordRequestBodyBuilder: ...
    def source_url_mobile(self, source_url_mobile: str) -> CreateProgressRecordRequestBodyBuilder: ...
    def build(self) -> CreateProgressRecordRequestBody: ...
