from .create_period_request_body import CreatePeriodRequestBody as CreatePeriodRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreatePeriodRequest(BaseRequest):
    request_body: CreatePeriodRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreatePeriodRequestBuilder: ...

class CreatePeriodRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: CreatePeriodRequestBody) -> CreatePeriodRequestBuilder: ...
    def build(self) -> CreatePeriodRequest: ...
