from .content_block import ContentBlock as ContentBlock
from lark_oapi.core.construct import init as init

class CreateProgressRecordResponseBody:
    progress_id: int | None
    modify_time: int | None
    content: ContentBlock | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateProgressRecordResponseBodyBuilder: ...

class CreateProgressRecordResponseBodyBuilder:
    def __init__(self) -> None: ...
    def progress_id(self, progress_id: int) -> CreateProgressRecordResponseBodyBuilder: ...
    def modify_time(self, modify_time: int) -> CreateProgressRecordResponseBodyBuilder: ...
    def content(self, content: ContentBlock) -> CreateProgressRecordResponseBodyBuilder: ...
    def build(self) -> CreateProgressRecordResponseBody: ...
