from lark_oapi.core.construct import init as init

class CurrentOkrSimple:
    okr_id: str | None
    period_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CurrentOkrSimpleBuilder: ...

class CurrentOkrSimpleBuilder:
    def __init__(self) -> None: ...
    def okr_id(self, okr_id: str) -> CurrentOkrSimpleBuilder: ...
    def period_id(self, period_id: str) -> CurrentOkrSimpleBuilder: ...
    def build(self) -> CurrentOkrSimple: ...
