from lark_oapi.core.construct import init as init

class DeleteProgressRecordRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteProgressRecordRequestBodyBuilder: ...

class DeleteProgressRecordRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteProgressRecordRequestBody: ...
