from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetProgressRecordRequest(BaseRequest):
    user_id_type: str | None
    progress_id: int | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetProgressRecordRequestBuilder: ...

class GetProgressRecordRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> GetProgressRecordRequestBuilder: ...
    def progress_id(self, progress_id: int) -> GetProgressRecordRequestBuilder: ...
    def build(self) -> GetProgressRecordRequest: ...
