from .okr_batch import OkrBatch as OkrBatch
from lark_oapi.core.construct import init as init

class ListUserOkrResponseBody:
    total: int | None
    okr_list: list[OkrBatch] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListUserOkrResponseBodyBuilder: ...

class ListUserOkrResponseBodyBuilder:
    def __init__(self) -> None: ...
    def total(self, total: int) -> ListUserOkrResponseBodyBuilder: ...
    def okr_list(self, okr_list: list[OkrBatch]) -> ListUserOkrResponseBodyBuilder: ...
    def build(self) -> ListUserOkrResponseBody: ...
