from lark_oapi.core.construct import init as init

class ListPeriodRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListPeriodRequestBodyBuilder: ...

class ListPeriodRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListPeriodRequestBody: ...
