from .period import Period as Period
from lark_oapi.core.construct import init as init

class ListPeriodResponseBody:
    page_token: str | None
    has_more: bool | None
    items: list[Period] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListPeriodResponseBodyBuilder: ...

class ListPeriodResponseBodyBuilder:
    def __init__(self) -> None: ...
    def page_token(self, page_token: str) -> ListPeriodResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListPeriodResponseBodyBuilder: ...
    def items(self, items: list[Period]) -> ListPeriodResponseBodyBuilder: ...
    def build(self) -> ListPeriodResponseBody: ...
