from .metric_source import MetricSource as MetricSource
from lark_oapi.core.construct import init as init

class ListMetricSourceResponseBody:
    total: int | None
    has_more: bool | None
    page_token: str | None
    items: list[MetricSource] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListMetricSourceResponseBodyBuilder: ...

class ListMetricSourceResponseBodyBuilder:
    def __init__(self) -> None: ...
    def total(self, total: int) -> ListMetricSourceResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListMetricSourceResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListMetricSourceResponseBodyBuilder: ...
    def items(self, items: list[MetricSource]) -> ListMetricSourceResponseBodyBuilder: ...
    def build(self) -> ListMetricSourceResponseBody: ...
