from .period_rule import PeriodRule as PeriodRule
from lark_oapi.core.construct import init as init

class ListPeriodRuleResponseBody:
    period_rules: list[PeriodRule] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListPeriodRuleResponseBodyBuilder: ...

class ListPeriodRuleResponseBodyBuilder:
    def __init__(self) -> None: ...
    def period_rules(self, period_rules: list[PeriodRule]) -> ListPeriodRuleResponseBodyBuilder: ...
    def build(self) -> ListPeriodRuleResponseBody: ...
