from lark_oapi.core.construct import init as init

class ListPeriodRuleRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListPeriodRuleRequestBodyBuilder: ...

class ListPeriodRuleRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListPeriodRuleRequestBody: ...
