from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListPeriodRequest(BaseRequest):
    page_token: str | None
    page_size: int | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListPeriodRequestBuilder: ...

class ListPeriodRequestBuilder:
    def __init__(self) -> None: ...
    def page_token(self, page_token: str) -> ListPeriodRequestBuilder: ...
    def page_size(self, page_size: int) -> ListPeriodRequestBuilder: ...
    def build(self) -> ListPeriodRequest: ...
