from .metric_unit import MetricUnit as MetricUnit
from lark_oapi.core.construct import init as init

class MetricSource:
    metric_source_id: str | None
    metric_source_name: str | None
    metric_name: str | None
    metric_unit: MetricUnit | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MetricSourceBuilder: ...

class MetricSourceBuilder:
    def __init__(self) -> None: ...
    def metric_source_id(self, metric_source_id: str) -> MetricSourceBuilder: ...
    def metric_source_name(self, metric_source_name: str) -> MetricSourceBuilder: ...
    def metric_name(self, metric_name: str) -> MetricSourceBuilder: ...
    def metric_unit(self, metric_unit: MetricUnit) -> MetricSourceBuilder: ...
    def build(self) -> MetricSource: ...
