from lark_oapi.core.construct import init as init

class MetricItemRequest:
    metric_item_id: str | None
    metric_initial_value: float | None
    metric_target_value: float | None
    metric_current_value: float | None
    supported_user_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MetricItemRequestBuilder: ...

class MetricItemRequestBuilder:
    def __init__(self) -> None: ...
    def metric_item_id(self, metric_item_id: str) -> MetricItemRequestBuilder: ...
    def metric_initial_value(self, metric_initial_value: float) -> MetricItemRequestBuilder: ...
    def metric_target_value(self, metric_target_value: float) -> MetricItemRequestBuilder: ...
    def metric_current_value(self, metric_current_value: float) -> MetricItemRequestBuilder: ...
    def supported_user_id(self, supported_user_id: str) -> MetricItemRequestBuilder: ...
    def build(self) -> MetricItemRequest: ...
