from lark_oapi.core.construct import init as init

class ObjectiveName:
    zh: str | None
    en: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ObjectiveNameBuilder: ...

class ObjectiveNameBuilder:
    def __init__(self) -> None: ...
    def zh(self, zh: str) -> ObjectiveNameBuilder: ...
    def en(self, en: str) -> ObjectiveNameBuilder: ...
    def build(self) -> ObjectiveName: ...
