from .okr_objective import OkrObjective as OkrObjective
from lark_oapi.core.construct import init as init

class OkrBatch:
    id: int | None
    permission: int | None
    period_id: int | None
    name: str | None
    objective_list: list[OkrObjective] | None
    confirm_status: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OkrBatchBuilder: ...

class OkrBatchBuilder:
    def __init__(self) -> None: ...
    def id(self, id: int) -> OkrBatchBuilder: ...
    def permission(self, permission: int) -> OkrBatchBuilder: ...
    def period_id(self, period_id: int) -> OkrBatchBuilder: ...
    def name(self, name: str) -> OkrBatchBuilder: ...
    def objective_list(self, objective_list: list[OkrObjective]) -> OkrBatchBuilder: ...
    def confirm_status(self, confirm_status: int) -> OkrBatchBuilder: ...
    def build(self) -> OkrBatch: ...
