from .okr_objective_aligned_objective_owner import OkrObjectiveAlignedObjectiveOwner as OkrObjectiveAlignedObjectiveOwner
from .okr_review_period import OkrReviewPeriod as OkrReviewPeriod
from lark_oapi.core.construct import init as init

class OkrReview:
    user_id: OkrObjectiveAlignedObjectiveOwner | None
    review_period_list: list[OkrReviewPeriod] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OkrReviewBuilder: ...

class OkrReviewBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: OkrObjectiveAlignedObjectiveOwner) -> OkrReviewBuilder: ...
    def review_period_list(self, review_period_list: list[OkrReviewPeriod]) -> OkrReviewBuilder: ...
    def build(self) -> OkrReview: ...
