from lark_oapi.core.construct import init as init

class OkrObjectiveAlignment:
    id: int | None
    to_id: int | None
    to_type: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OkrObjectiveAlignmentBuilder: ...

class OkrObjectiveAlignmentBuilder:
    def __init__(self) -> None: ...
    def id(self, id: int) -> OkrObjectiveAlignmentBuilder: ...
    def to_id(self, to_id: int) -> OkrObjectiveAlignmentBuilder: ...
    def to_type(self, to_type: int) -> OkrObjectiveAlignmentBuilder: ...
    def build(self) -> OkrObjectiveAlignment: ...
