from lark_oapi.core.construct import init as init

class OkrDetailObjectiveAlign:
    id: int | None
    okr_id: int | None
    user_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OkrDetailObjectiveAlignBuilder: ...

class OkrDetailObjectiveAlignBuilder:
    def __init__(self) -> None: ...
    def id(self, id: int) -> OkrDetailObjectiveAlignBuilder: ...
    def okr_id(self, okr_id: int) -> OkrDetailObjectiveAlignBuilder: ...
    def user_id(self, user_id: str) -> OkrDetailObjectiveAlignBuilder: ...
    def build(self) -> OkrDetailObjectiveAlign: ...
