from .okr_review_period_url import OkrReviewPeriodUrl as OkrReviewPeriodUrl
from lark_oapi.core.construct import init as init

class OkrReviewPeriod:
    period_id: int | None
    cycle_review_list: list[OkrReviewPeriodUrl] | None
    progress_report_list: list[OkrReviewPeriodUrl] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OkrReviewPeriodBuilder: ...

class OkrReviewPeriodBuilder:
    def __init__(self) -> None: ...
    def period_id(self, period_id: int) -> OkrReviewPeriodBuilder: ...
    def cycle_review_list(self, cycle_review_list: list[OkrReviewPeriodUrl]) -> OkrReviewPeriodBuilder: ...
    def progress_report_list(self, progress_report_list: list[OkrReviewPeriodUrl]) -> OkrReviewPeriodBuilder: ...
    def build(self) -> OkrReviewPeriod: ...
