from .okr_name import OkrName as OkrName
from lark_oapi.core.construct import init as init

class OkrSimple:
    name: OkrName | None
    okr_id: str | None
    period_id: str | None
    period_type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OkrSimpleBuilder: ...

class OkrSimpleBuilder:
    def __init__(self) -> None: ...
    def name(self, name: OkrName) -> OkrSimpleBuilder: ...
    def okr_id(self, okr_id: str) -> OkrSimpleBuilder: ...
    def period_id(self, period_id: str) -> OkrSimpleBuilder: ...
    def period_type(self, period_type: str) -> OkrSimpleBuilder: ...
    def build(self) -> OkrSimple: ...
