from .okr_detail_objective_align import OkrDetailObjectiveAlign as OkrDetailObjectiveAlign
from .okr_detail_objective_kr import OkrDetailObjectiveKr as OkrDetailObjectiveKr
from .okr_name import OkrName as OkrName
from lark_oapi.core.construct import init as init

class OkrDetailObjective:
    id: int | None
    okr_id: int | None
    user_id: str | None
    pos: int | None
    score: int | None
    name: OkrName | None
    progress: OkrName | None
    create_time: int | None
    modify_time: int | None
    kr_list: list[OkrDetailObjectiveKr] | None
    aligning_objective_list: list[OkrDetailObjectiveAlign] | None
    aligned_objective_list: list[OkrDetailObjectiveAlign] | None
    weight: float | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OkrDetailObjectiveBuilder: ...

class OkrDetailObjectiveBuilder:
    def __init__(self) -> None: ...
    def id(self, id: int) -> OkrDetailObjectiveBuilder: ...
    def okr_id(self, okr_id: int) -> OkrDetailObjectiveBuilder: ...
    def user_id(self, user_id: str) -> OkrDetailObjectiveBuilder: ...
    def pos(self, pos: int) -> OkrDetailObjectiveBuilder: ...
    def score(self, score: int) -> OkrDetailObjectiveBuilder: ...
    def name(self, name: OkrName) -> OkrDetailObjectiveBuilder: ...
    def progress(self, progress: OkrName) -> OkrDetailObjectiveBuilder: ...
    def create_time(self, create_time: int) -> OkrDetailObjectiveBuilder: ...
    def modify_time(self, modify_time: int) -> OkrDetailObjectiveBuilder: ...
    def kr_list(self, kr_list: list[OkrDetailObjectiveKr]) -> OkrDetailObjectiveBuilder: ...
    def aligning_objective_list(self, aligning_objective_list: list[OkrDetailObjectiveAlign]) -> OkrDetailObjectiveBuilder: ...
    def aligned_objective_list(self, aligned_objective_list: list[OkrDetailObjectiveAlign]) -> OkrDetailObjectiveBuilder: ...
    def weight(self, weight: float) -> OkrDetailObjectiveBuilder: ...
    def build(self) -> OkrDetailObjective: ...
