from .okr_objective_aligned_objective import OkrObjectiveAlignedObjective as OkrObjectiveAlignedObjective
from .okr_objective_aligned_objective_owner import OkrObjectiveAlignedObjectiveOwner as OkrObjectiveAlignedObjectiveOwner
from .okr_objective_kr import OkrObjectiveKr as OkrObjectiveKr
from .okr_objective_progress_rate import OkrObjectiveProgressRate as OkrObjectiveProgressRate
from .progress_record_simplify import ProgressRecordSimplify as ProgressRecordSimplify
from lark_oapi.core.construct import init as init

class OkrObjective:
    id: int | None
    permission: int | None
    content: str | None
    progress_report: str | None
    score: int | None
    weight: float | None
    progress_rate: OkrObjectiveProgressRate | None
    kr_list: list[OkrObjectiveKr] | None
    aligned_objective_list: list[OkrObjectiveAlignedObjective] | None
    aligning_objective_list: list[OkrObjectiveAlignedObjective] | None
    progress_record_list: list[ProgressRecordSimplify] | None
    progress_rate_percent_last_updated_time: int | None
    progress_rate_status_last_updated_time: int | None
    progress_record_last_updated_time: int | None
    progress_report_last_updated_time: int | None
    score_last_updated_time: int | None
    deadline: int | None
    mentioned_user_list: list[OkrObjectiveAlignedObjectiveOwner] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OkrObjectiveBuilder: ...

class OkrObjectiveBuilder:
    def __init__(self) -> None: ...
    def id(self, id: int) -> OkrObjectiveBuilder: ...
    def permission(self, permission: int) -> OkrObjectiveBuilder: ...
    def content(self, content: str) -> OkrObjectiveBuilder: ...
    def progress_report(self, progress_report: str) -> OkrObjectiveBuilder: ...
    def score(self, score: int) -> OkrObjectiveBuilder: ...
    def weight(self, weight: float) -> OkrObjectiveBuilder: ...
    def progress_rate(self, progress_rate: OkrObjectiveProgressRate) -> OkrObjectiveBuilder: ...
    def kr_list(self, kr_list: list[OkrObjectiveKr]) -> OkrObjectiveBuilder: ...
    def aligned_objective_list(self, aligned_objective_list: list[OkrObjectiveAlignedObjective]) -> OkrObjectiveBuilder: ...
    def aligning_objective_list(self, aligning_objective_list: list[OkrObjectiveAlignedObjective]) -> OkrObjectiveBuilder: ...
    def progress_record_list(self, progress_record_list: list[ProgressRecordSimplify]) -> OkrObjectiveBuilder: ...
    def progress_rate_percent_last_updated_time(self, progress_rate_percent_last_updated_time: int) -> OkrObjectiveBuilder: ...
    def progress_rate_status_last_updated_time(self, progress_rate_status_last_updated_time: int) -> OkrObjectiveBuilder: ...
    def progress_record_last_updated_time(self, progress_record_last_updated_time: int) -> OkrObjectiveBuilder: ...
    def progress_report_last_updated_time(self, progress_report_last_updated_time: int) -> OkrObjectiveBuilder: ...
    def score_last_updated_time(self, score_last_updated_time: int) -> OkrObjectiveBuilder: ...
    def deadline(self, deadline: int) -> OkrObjectiveBuilder: ...
    def mentioned_user_list(self, mentioned_user_list: list[OkrObjectiveAlignedObjectiveOwner]) -> OkrObjectiveBuilder: ...
    def build(self) -> OkrObjective: ...
