from .okr_name import OkrName as OkrName
from lark_oapi.core.construct import init as init

class OkrDetailObjectiveKr:
    id: int | None
    pos: int | None
    score: int | None
    weight: float | None
    content: OkrName | None
    create_time: int | None
    modify_time: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OkrDetailObjectiveKrBuilder: ...

class OkrDetailObjectiveKrBuilder:
    def __init__(self) -> None: ...
    def id(self, id: int) -> OkrDetailObjectiveKrBuilder: ...
    def pos(self, pos: int) -> OkrDetailObjectiveKrBuilder: ...
    def score(self, score: int) -> OkrDetailObjectiveKrBuilder: ...
    def weight(self, weight: float) -> OkrDetailObjectiveKrBuilder: ...
    def content(self, content: OkrName) -> OkrDetailObjectiveKrBuilder: ...
    def create_time(self, create_time: int) -> OkrDetailObjectiveKrBuilder: ...
    def modify_time(self, modify_time: int) -> OkrDetailObjectiveKrBuilder: ...
    def build(self) -> OkrDetailObjectiveKr: ...
