from .patch_period_request_body import PatchPeriodRequestBody as PatchPeriodRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PatchPeriodRequest(BaseRequest):
    period_id: str | None
    request_body: PatchPeriodRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PatchPeriodRequestBuilder: ...

class PatchPeriodRequestBuilder:
    def __init__(self) -> None: ...
    def period_id(self, period_id: str) -> PatchPeriodRequestBuilder: ...
    def request_body(self, request_body: PatchPeriodRequestBody) -> PatchPeriodRequestBuilder: ...
    def build(self) -> PatchPeriodRequest: ...
