from lark_oapi.core.construct import init as init

class PatchPeriodResponseBody:
    period_id: str | None
    status: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchPeriodResponseBodyBuilder: ...

class PatchPeriodResponseBodyBuilder:
    def __init__(self) -> None: ...
    def period_id(self, period_id: str) -> PatchPeriodResponseBodyBuilder: ...
    def status(self, status: int) -> PatchPeriodResponseBodyBuilder: ...
    def build(self) -> PatchPeriodResponseBody: ...
