from lark_oapi.core.construct import init as init

class PatchPeriodRequestBody:
    status: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchPeriodRequestBodyBuilder: ...

class PatchPeriodRequestBodyBuilder:
    def __init__(self) -> None: ...
    def status(self, status: int) -> PatchPeriodRequestBodyBuilder: ...
    def build(self) -> PatchPeriodRequestBody: ...
