from lark_oapi.core.construct import init as init

class PeriodRule:
    period_rule_id: str | None
    type: str | None
    length: int | None
    first_month: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PeriodRuleBuilder: ...

class PeriodRuleBuilder:
    def __init__(self) -> None: ...
    def period_rule_id(self, period_rule_id: str) -> PeriodRuleBuilder: ...
    def type(self, type: str) -> PeriodRuleBuilder: ...
    def length(self, length: int) -> PeriodRuleBuilder: ...
    def first_month(self, first_month: int) -> PeriodRuleBuilder: ...
    def build(self) -> PeriodRule: ...
