from lark_oapi.core.construct import init as init

class ProgressRecordSimplify:
    id: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ProgressRecordSimplifyBuilder: ...

class ProgressRecordSimplifyBuilder:
    def __init__(self) -> None: ...
    def id(self, id: int) -> ProgressRecordSimplifyBuilder: ...
    def build(self) -> ProgressRecordSimplify: ...
