from lark_oapi.core.construct import init as init

class QueryReviewRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryReviewRequestBodyBuilder: ...

class QueryReviewRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> QueryReviewRequestBody: ...
