from .okr_review import OkrReview as OkrReview
from lark_oapi.core.construct import init as init

class QueryReviewResponseBody:
    review_list: list[OkrReview] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryReviewResponseBodyBuilder: ...

class QueryReviewResponseBodyBuilder:
    def __init__(self) -> None: ...
    def review_list(self, review_list: list[OkrReview]) -> QueryReviewResponseBodyBuilder: ...
    def build(self) -> QueryReviewResponseBody: ...
