from .update_progress_record_request_body import UpdateProgressRecordRequestBody as UpdateProgressRecordRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UpdateProgressRecordRequest(BaseRequest):
    user_id_type: str | None
    progress_id: int | None
    request_body: UpdateProgressRecordRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UpdateProgressRecordRequestBuilder: ...

class UpdateProgressRecordRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> UpdateProgressRecordRequestBuilder: ...
    def progress_id(self, progress_id: int) -> UpdateProgressRecordRequestBuilder: ...
    def request_body(self, request_body: UpdateProgressRecordRequestBody) -> UpdateProgressRecordRequestBuilder: ...
    def build(self) -> UpdateProgressRecordRequest: ...
