from .content_block import ContentBlock as ContentBlock
from lark_oapi.core.construct import init as init

class UpdateProgressRecordRequestBody:
    content: ContentBlock | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateProgressRecordRequestBodyBuilder: ...

class UpdateProgressRecordRequestBodyBuilder:
    def __init__(self) -> None: ...
    def content(self, content: ContentBlock) -> UpdateProgressRecordRequestBodyBuilder: ...
    def build(self) -> UpdateProgressRecordRequestBody: ...
