from lark_oapi.core.construct import init as init
from typing import Any, IO

class UploadImageRequestBody:
    data: IO[Any] | None
    target_id: int | None
    target_type: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UploadImageRequestBodyBuilder: ...

class UploadImageRequestBodyBuilder:
    def __init__(self) -> None: ...
    def data(self, data: IO[Any]) -> UploadImageRequestBodyBuilder: ...
    def target_id(self, target_id: int) -> UploadImageRequestBodyBuilder: ...
    def target_type(self, target_type: int) -> UploadImageRequestBodyBuilder: ...
    def build(self) -> UploadImageRequestBody: ...
