from .upload_image_request_body import UploadImageRequestBody as UploadImageRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UploadImageRequest(BaseRequest):
    request_body: UploadImageRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UploadImageRequestBuilder: ...

class UploadImageRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: UploadImageRequestBody) -> UploadImageRequestBuilder: ...
    def build(self) -> UploadImageRequest: ...
