from .progress_item import ProgressItem as ProgressItem
from .progress_rate import ProgressRate as ProgressRate
from .upsert_objective_kr import UpsertObjectiveKr as UpsertObjectiveKr
from lark_oapi.core.construct import init as init

class UpsertObjective:
    content: str | None
    mention_list: list[str] | None
    kr_list: list[UpsertObjectiveKr] | None
    progress_rate: ProgressRate | None
    progress_list: list[ProgressItem] | None
    weight: float | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpsertObjectiveBuilder: ...

class UpsertObjectiveBuilder:
    def __init__(self) -> None: ...
    def content(self, content: str) -> UpsertObjectiveBuilder: ...
    def mention_list(self, mention_list: list[str]) -> UpsertObjectiveBuilder: ...
    def kr_list(self, kr_list: list[UpsertObjectiveKr]) -> UpsertObjectiveBuilder: ...
    def progress_rate(self, progress_rate: ProgressRate) -> UpsertObjectiveBuilder: ...
    def progress_list(self, progress_list: list[ProgressItem]) -> UpsertObjectiveBuilder: ...
    def weight(self, weight: float) -> UpsertObjectiveBuilder: ...
    def build(self) -> UpsertObjective: ...
