from .progress_item import ProgressItem as ProgressItem
from .progress_rate import ProgressRate as ProgressRate
from lark_oapi.core.construct import init as init

class UpsertObjectiveKr:
    content: str | None
    mention_list: list[str] | None
    score: int | None
    progress_rate: ProgressRate | None
    progress_list: list[ProgressItem] | None
    weight: float | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpsertObjectiveKrBuilder: ...

class UpsertObjectiveKrBuilder:
    def __init__(self) -> None: ...
    def content(self, content: str) -> UpsertObjectiveKrBuilder: ...
    def mention_list(self, mention_list: list[str]) -> UpsertObjectiveKrBuilder: ...
    def score(self, score: int) -> UpsertObjectiveKrBuilder: ...
    def progress_rate(self, progress_rate: ProgressRate) -> UpsertObjectiveKrBuilder: ...
    def progress_list(self, progress_list: list[ProgressItem]) -> UpsertObjectiveKrBuilder: ...
    def weight(self, weight: float) -> UpsertObjectiveKrBuilder: ...
    def build(self) -> UpsertObjectiveKr: ...
