from lark_oapi.core.construct import init as init

class UserOkrObjectiveProgressRate:
    percent: int | None
    status: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserOkrObjectiveProgressRateBuilder: ...

class UserOkrObjectiveProgressRateBuilder:
    def __init__(self) -> None: ...
    def percent(self, percent: int) -> UserOkrObjectiveProgressRateBuilder: ...
    def status(self, status: str) -> UserOkrObjectiveProgressRateBuilder: ...
    def build(self) -> UserOkrObjectiveProgressRate: ...
