from .create_tenant_access_token_request_body import CreateTenantAccessTokenRequestBody as CreateTenantAccessTokenRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateTenantAccessTokenRequest(BaseRequest):
    request_body: CreateTenantAccessTokenRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateTenantAccessTokenRequestBuilder: ...

class CreateTenantAccessTokenRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: CreateTenantAccessTokenRequestBody) -> CreateTenantAccessTokenRequestBuilder: ...
    def build(self) -> CreateTenantAccessTokenRequest: ...
