from lark_oapi.core.construct import init as init

class InternalTenantAccessTokenResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InternalTenantAccessTokenResponseBodyBuilder: ...

class InternalTenantAccessTokenResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> InternalTenantAccessTokenResponseBody: ...
