from .resend_app_ticket_request_body import ResendAppTicketRequestBody as ResendAppTicketRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ResendAppTicketRequest(BaseRequest):
    request_body: ResendAppTicketRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ResendAppTicketRequestBuilder: ...

class ResendAppTicketRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: ResendAppTicketRequestBody) -> ResendAppTicketRequestBuilder: ...
    def build(self) -> ResendAppTicketRequest: ...
