from ..model.create_location_request import CreateLocationRequest as CreateLocationRequest
from ..model.create_location_response import CreateLocationResponse as CreateLocationResponse
from ..model.delete_location_request import DeleteLocationRequest as DeleteLocationRequest
from ..model.delete_location_response import DeleteLocationResponse as DeleteLocationResponse
from ..model.get_location_request import GetLocationRequest as GetLocationRequest
from ..model.get_location_response import GetLocationResponse as GetLocationResponse
from ..model.list_location_request import ListLocationRequest as ListLocationRequest
from ..model.list_location_response import ListLocationResponse as ListLocationResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class Location:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def create(self, request: CreateLocationRequest, option: RequestOption | None = None) -> CreateLocationResponse: ...
    async def acreate(self, request: CreateLocationRequest, option: RequestOption | None = None) -> CreateLocationResponse: ...
    def delete(self, request: DeleteLocationRequest, option: RequestOption | None = None) -> DeleteLocationResponse: ...
    async def adelete(self, request: DeleteLocationRequest, option: RequestOption | None = None) -> DeleteLocationResponse: ...
    def get(self, request: GetLocationRequest, option: RequestOption | None = None) -> GetLocationResponse: ...
    async def aget(self, request: GetLocationRequest, option: RequestOption | None = None) -> GetLocationResponse: ...
    def list(self, request: ListLocationRequest, option: RequestOption | None = None) -> ListLocationResponse: ...
    async def alist(self, request: ListLocationRequest, option: RequestOption | None = None) -> ListLocationResponse: ...
