from .minute import Minute as Minute
from lark_oapi.core.construct import init as init

class GetMinuteResponseBody:
    minute: Minute | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetMinuteResponseBodyBuilder: ...

class GetMinuteResponseBodyBuilder:
    def __init__(self) -> None: ...
    def minute(self, minute: Minute) -> GetMinuteResponseBodyBuilder: ...
    def build(self) -> GetMinuteResponseBody: ...
