from lark_oapi.core.construct import init as init

class GetMinuteTranscriptRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetMinuteTranscriptRequestBodyBuilder: ...

class GetMinuteTranscriptRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetMinuteTranscriptRequestBody: ...
