from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetMinuteStatisticsRequest(BaseRequest):
    user_id_type: str | None
    minute_token: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetMinuteStatisticsRequestBuilder: ...

class GetMinuteStatisticsRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> GetMinuteStatisticsRequestBuilder: ...
    def minute_token(self, minute_token: str) -> GetMinuteStatisticsRequestBuilder: ...
    def build(self) -> GetMinuteStatisticsRequest: ...
