from lark_oapi.core.construct import init as init

class GetMinuteRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetMinuteRequestBodyBuilder: ...

class GetMinuteRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetMinuteRequestBody: ...
