from lark_oapi.core.construct import init as init

class UserViewDetail:
    user_id: str | None
    view_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserViewDetailBuilder: ...

class UserViewDetailBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: str) -> UserViewDetailBuilder: ...
    def view_time(self, view_time: str) -> UserViewDetailBuilder: ...
    def build(self) -> UserViewDetail: ...
