from ..model.create_faq_request import CreateFaqRequest as CreateFaqRequest
from ..model.create_faq_response import CreateFaqResponse as CreateFaqResponse
from ..model.delete_faq_request import DeleteFaqRequest as DeleteFaqRequest
from ..model.delete_faq_response import DeleteFaqResponse as DeleteFaqResponse
from ..model.faq_image_faq_request import FaqImageFaqRequest as FaqImageFaqRequest
from ..model.faq_image_faq_response import FaqImageFaqResponse as FaqImageFaqResponse
from ..model.get_faq_request import GetFaqRequest as GetFaqRequest
from ..model.get_faq_response import GetFaqResponse as GetFaqResponse
from ..model.list_faq_request import ListFaqRequest as ListFaqRequest
from ..model.list_faq_response import ListFaqResponse as ListFaqResponse
from ..model.patch_faq_request import PatchFaqRequest as PatchFaqRequest
from ..model.patch_faq_response import PatchFaqResponse as PatchFaqResponse
from ..model.search_faq_request import SearchFaqRequest as SearchFaqRequest
from ..model.search_faq_response import SearchFaqResponse as SearchFaqResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class Faq:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def create(self, request: CreateFaqRequest, option: RequestOption | None = None) -> CreateFaqResponse: ...
    async def acreate(self, request: CreateFaqRequest, option: RequestOption | None = None) -> CreateFaqResponse: ...
    def delete(self, request: DeleteFaqRequest, option: RequestOption | None = None) -> DeleteFaqResponse: ...
    async def adelete(self, request: DeleteFaqRequest, option: RequestOption | None = None) -> DeleteFaqResponse: ...
    def faq_image(self, request: FaqImageFaqRequest, option: RequestOption | None = None) -> FaqImageFaqResponse: ...
    async def afaq_image(self, request: FaqImageFaqRequest, option: RequestOption | None = None) -> FaqImageFaqResponse: ...
    def get(self, request: GetFaqRequest, option: RequestOption | None = None) -> GetFaqResponse: ...
    async def aget(self, request: GetFaqRequest, option: RequestOption | None = None) -> GetFaqResponse: ...
    def list(self, request: ListFaqRequest, option: RequestOption | None = None) -> ListFaqResponse: ...
    async def alist(self, request: ListFaqRequest, option: RequestOption | None = None) -> ListFaqResponse: ...
    def patch(self, request: PatchFaqRequest, option: RequestOption | None = None) -> PatchFaqResponse: ...
    async def apatch(self, request: PatchFaqRequest, option: RequestOption | None = None) -> PatchFaqResponse: ...
    def search(self, request: SearchFaqRequest, option: RequestOption | None = None) -> SearchFaqResponse: ...
    async def asearch(self, request: SearchFaqRequest, option: RequestOption | None = None) -> SearchFaqResponse: ...
