from _typeshed import Incomplete

class Error(Exception): ...
class DecodeError(Error): ...
class EncodeError(Error): ...

class Message:
    DESCRIPTOR: Incomplete
    def __deepcopy__(self, memo=None): ...
    def __eq__(self, other_msg): ...
    def __ne__(self, other_msg): ...
    def __hash__(self): ...
    def __unicode__(self) -> None: ...
    def MergeFrom(self, other_msg) -> None: ...
    def CopyFrom(self, other_msg) -> None: ...
    def Clear(self) -> None: ...
    def SetInParent(self) -> None: ...
    def IsInitialized(self) -> None: ...
    def MergeFromString(self, serialized) -> None: ...
    def ParseFromString(self, serialized): ...
    def SerializeToString(self, **kwargs) -> None: ...
    def SerializePartialToString(self, **kwargs) -> None: ...
    def ListFields(self) -> None: ...
    def HasField(self, field_name) -> None: ...
    def ClearField(self, field_name) -> None: ...
    def WhichOneof(self, oneof_group) -> None: ...
    def HasExtension(self, extension_handle) -> None: ...
    def ClearExtension(self, extension_handle) -> None: ...
    def UnknownFields(self) -> None: ...
    def DiscardUnknownFields(self) -> None: ...
    def ByteSize(self) -> None: ...
    @classmethod
    def FromString(cls, s) -> None: ...
    @staticmethod
    def RegisterExtension(extension_handle) -> None: ...
    def __reduce__(self): ...
