from _typeshed import Incomplete
from lark_oapi.ws.pb.google.protobuf import descriptor_pool as descriptor_pool, message as message
from lark_oapi.ws.pb.google.protobuf.internal import api_implementation as api_implementation

class MessageFactory:
    pool: Incomplete
    def __init__(self, pool=None) -> None: ...
    def GetPrototype(self, descriptor): ...
    def CreatePrototype(self, descriptor): ...
    def GetMessages(self, files): ...

def GetMessages(file_protos): ...
