from _typeshed import Incomplete

class GeneratedServiceType(type):
    def __init__(cls, name, bases, dictionary) -> None: ...

class GeneratedServiceStubType(GeneratedServiceType):
    def __init__(cls, name, bases, dictionary) -> None: ...

class _ServiceBuilder:
    descriptor: Incomplete
    def __init__(self, service_descriptor) -> None: ...
    def BuildService(builder, cls): ...

class _ServiceStubBuilder:
    descriptor: Incomplete
    def __init__(self, service_descriptor) -> None: ...
    cls: Incomplete
    def BuildServiceStub(self, cls) -> None: ...
