class RpcException(Exception): ...

class Service:
    def GetDescriptor() -> None: ...
    def CallMethod(self, method_descriptor, rpc_controller, request, done) -> None: ...
    def GetRequestClass(self, method_descriptor) -> None: ...
    def GetResponseClass(self, method_descriptor) -> None: ...

class RpcController:
    def Reset(self) -> None: ...
    def Failed(self) -> None: ...
    def ErrorText(self) -> None: ...
    def StartCancel(self) -> None: ...
    def SetFailed(self, reason) -> None: ...
    def IsCanceled(self) -> None: ...
    def NotifyOnCancel(self, callback) -> None: ...

class RpcChannel:
    def CallMethod(self, method_descriptor, rpc_controller, request, response_class, done) -> None: ...
