from .model.p2_card_action_trigger import P2CardActionTrigger as P2CardActionTrigger, P2CardActionTriggerResponse as P2CardActionTriggerResponse
from .model.p2_url_preview_get import P2URLPreviewGet as P2URLPreviewGet, P2URLPreviewGetResponse as P2URLPreviewGetResponse
from _typeshed import Incomplete
from lark_oapi.event.processor import ICallBackProcessor as ICallBackProcessor
from typing import Callable

class P2CardActionTriggerProcessor(ICallBackProcessor[P2CardActionTrigger]):
    f: Incomplete
    def __init__(self, f: Callable[[P2CardActionTrigger], P2CardActionTriggerResponse]) -> None: ...
    def type(self) -> type[P2CardActionTrigger]: ...
    def do(self, data: P2CardActionTrigger) -> P2CardActionTriggerResponse: ...

class P2URLPreviewGetProcessor(ICallBackProcessor[P2URLPreviewGet]):
    f: Incomplete
    def __init__(self, f: Callable[[P2URLPreviewGet], P2URLPreviewGetResponse]) -> None: ...
    def type(self) -> type[P2URLPreviewGet]: ...
    def do(self, data: P2URLPreviewGet) -> P2URLPreviewGetResponse: ...
