from lark_oapi.core.construct import init as init

class CreateRefreshAccessTokenResponseBody:
    access_token: str | None
    token_type: str | None
    expires_in: int | None
    name: str | None
    en_name: str | None
    avatar_url: str | None
    avatar_thumb: str | None
    avatar_middle: str | None
    avatar_big: str | None
    open_id: str | None
    union_id: str | None
    email: str | None
    enterprise_email: str | None
    user_id: str | None
    mobile: str | None
    tenant_key: str | None
    refresh_expires_in: int | None
    refresh_token: str | None
    sid: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateRefreshAccessTokenResponseBodyBuilder: ...

class CreateRefreshAccessTokenResponseBodyBuilder:
    def __init__(self) -> None: ...
    def access_token(self, access_token: str) -> CreateRefreshAccessTokenResponseBodyBuilder: ...
    def token_type(self, token_type: str) -> CreateRefreshAccessTokenResponseBodyBuilder: ...
    def expires_in(self, expires_in: int) -> CreateRefreshAccessTokenResponseBodyBuilder: ...
    def name(self, name: str) -> CreateRefreshAccessTokenResponseBodyBuilder: ...
    def en_name(self, en_name: str) -> CreateRefreshAccessTokenResponseBodyBuilder: ...
    def avatar_url(self, avatar_url: str) -> CreateRefreshAccessTokenResponseBodyBuilder: ...
    def avatar_thumb(self, avatar_thumb: str) -> CreateRefreshAccessTokenResponseBodyBuilder: ...
    def avatar_middle(self, avatar_middle: str) -> CreateRefreshAccessTokenResponseBodyBuilder: ...
    def avatar_big(self, avatar_big: str) -> CreateRefreshAccessTokenResponseBodyBuilder: ...
    def open_id(self, open_id: str) -> CreateRefreshAccessTokenResponseBodyBuilder: ...
    def union_id(self, union_id: str) -> CreateRefreshAccessTokenResponseBodyBuilder: ...
    def email(self, email: str) -> CreateRefreshAccessTokenResponseBodyBuilder: ...
    def enterprise_email(self, enterprise_email: str) -> CreateRefreshAccessTokenResponseBodyBuilder: ...
    def user_id(self, user_id: str) -> CreateRefreshAccessTokenResponseBodyBuilder: ...
    def mobile(self, mobile: str) -> CreateRefreshAccessTokenResponseBodyBuilder: ...
    def tenant_key(self, tenant_key: str) -> CreateRefreshAccessTokenResponseBodyBuilder: ...
    def refresh_expires_in(self, refresh_expires_in: int) -> CreateRefreshAccessTokenResponseBodyBuilder: ...
    def refresh_token(self, refresh_token: str) -> CreateRefreshAccessTokenResponseBodyBuilder: ...
    def sid(self, sid: str) -> CreateRefreshAccessTokenResponseBodyBuilder: ...
    def build(self) -> CreateRefreshAccessTokenResponseBody: ...
