from lark_oapi.core.construct import init as init

class CreateAccessTokenRequestBody:
    grant_type: str | None
    code: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateAccessTokenRequestBodyBuilder: ...

class CreateAccessTokenRequestBodyBuilder:
    def __init__(self) -> None: ...
    def grant_type(self, grant_type: str) -> CreateAccessTokenRequestBodyBuilder: ...
    def code(self, code: str) -> CreateAccessTokenRequestBodyBuilder: ...
    def build(self) -> CreateAccessTokenRequestBody: ...
