from lark_oapi.core.construct import init as init

class CreateOidcRefreshAccessTokenRequestBody:
    grant_type: str | None
    refresh_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateOidcRefreshAccessTokenRequestBodyBuilder: ...

class CreateOidcRefreshAccessTokenRequestBodyBuilder:
    def __init__(self) -> None: ...
    def grant_type(self, grant_type: str) -> CreateOidcRefreshAccessTokenRequestBodyBuilder: ...
    def refresh_token(self, refresh_token: str) -> CreateOidcRefreshAccessTokenRequestBodyBuilder: ...
    def build(self) -> CreateOidcRefreshAccessTokenRequestBody: ...
