from lark_oapi.core.construct import init as init

class CreateRefreshAccessTokenRequestBody:
    grant_type: str | None
    refresh_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateRefreshAccessTokenRequestBodyBuilder: ...

class CreateRefreshAccessTokenRequestBodyBuilder:
    def __init__(self) -> None: ...
    def grant_type(self, grant_type: str) -> CreateRefreshAccessTokenRequestBodyBuilder: ...
    def refresh_token(self, refresh_token: str) -> CreateRefreshAccessTokenRequestBodyBuilder: ...
    def build(self) -> CreateRefreshAccessTokenRequestBody: ...
