from .create_refresh_access_token_request_body import CreateRefreshAccessTokenRequestBody as CreateRefreshAccessTokenRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateRefreshAccessTokenRequest(BaseRequest):
    request_body: CreateRefreshAccessTokenRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateRefreshAccessTokenRequestBuilder: ...

class CreateRefreshAccessTokenRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: CreateRefreshAccessTokenRequestBody) -> CreateRefreshAccessTokenRequestBuilder: ...
    def build(self) -> CreateRefreshAccessTokenRequest: ...
