from lark_oapi.core.construct import init as init

class GetUserInfoRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetUserInfoRequestBodyBuilder: ...

class GetUserInfoRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetUserInfoRequestBody: ...
