from lark_oapi.core.enum import HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetAuthorizeRequest(BaseRequest):
    app_id: str | None
    redirect_uri: str | None
    scope: str | None
    state: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetAuthorizeRequestBuilder: ...

class GetAuthorizeRequestBuilder:
    def __init__(self) -> None: ...
    def app_id(self, app_id: str) -> GetAuthorizeRequestBuilder: ...
    def redirect_uri(self, redirect_uri: str) -> GetAuthorizeRequestBuilder: ...
    def scope(self, scope: str) -> GetAuthorizeRequestBuilder: ...
    def state(self, state: str) -> GetAuthorizeRequestBuilder: ...
    def build(self) -> GetAuthorizeRequest: ...
