from lark_oapi.core.construct import init as init

class GetUserInfoResponseBody:
    name: str | None
    en_name: str | None
    avatar_url: str | None
    avatar_thumb: str | None
    avatar_middle: str | None
    avatar_big: str | None
    open_id: str | None
    union_id: str | None
    email: str | None
    enterprise_email: str | None
    user_id: str | None
    mobile: str | None
    tenant_key: str | None
    employee_no: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetUserInfoResponseBodyBuilder: ...

class GetUserInfoResponseBodyBuilder:
    def __init__(self) -> None: ...
    def name(self, name: str) -> GetUserInfoResponseBodyBuilder: ...
    def en_name(self, en_name: str) -> GetUserInfoResponseBodyBuilder: ...
    def avatar_url(self, avatar_url: str) -> GetUserInfoResponseBodyBuilder: ...
    def avatar_thumb(self, avatar_thumb: str) -> GetUserInfoResponseBodyBuilder: ...
    def avatar_middle(self, avatar_middle: str) -> GetUserInfoResponseBodyBuilder: ...
    def avatar_big(self, avatar_big: str) -> GetUserInfoResponseBodyBuilder: ...
    def open_id(self, open_id: str) -> GetUserInfoResponseBodyBuilder: ...
    def union_id(self, union_id: str) -> GetUserInfoResponseBodyBuilder: ...
    def email(self, email: str) -> GetUserInfoResponseBodyBuilder: ...
    def enterprise_email(self, enterprise_email: str) -> GetUserInfoResponseBodyBuilder: ...
    def user_id(self, user_id: str) -> GetUserInfoResponseBodyBuilder: ...
    def mobile(self, mobile: str) -> GetUserInfoResponseBodyBuilder: ...
    def tenant_key(self, tenant_key: str) -> GetUserInfoResponseBodyBuilder: ...
    def employee_no(self, employee_no: str) -> GetUserInfoResponseBodyBuilder: ...
    def build(self) -> GetUserInfoResponseBody: ...
