from lark_oapi.core.construct import init as init

class TokenInfo:
    access_token: str | None
    refresh_token: str | None
    token_type: str | None
    expires_in: int | None
    refresh_expires_in: int | None
    scope: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TokenInfoBuilder: ...

class TokenInfoBuilder:
    def __init__(self) -> None: ...
    def access_token(self, access_token: str) -> TokenInfoBuilder: ...
    def refresh_token(self, refresh_token: str) -> TokenInfoBuilder: ...
    def token_type(self, token_type: str) -> TokenInfoBuilder: ...
    def expires_in(self, expires_in: int) -> TokenInfoBuilder: ...
    def refresh_expires_in(self, refresh_expires_in: int) -> TokenInfoBuilder: ...
    def scope(self, scope: str) -> TokenInfoBuilder: ...
    def build(self) -> TokenInfo: ...
