from lark_oapi.core.construct import init as init

class NodeChild:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> NodeChildBuilder: ...

class NodeChildBuilder:
    def __init__(self) -> None: ...
    def build(self) -> NodeChild: ...
