from lark_oapi.core.construct import init as init

class Node:
    node_id: str | None
    space_id: str | None
    parent_id: str | None
    obj_type: int | None
    title: str | None
    url: str | None
    icon: str | None
    area_id: str | None
    sort_id: float | None
    domain: str | None
    obj_token: str | None
    create_time: str | None
    update_time: str | None
    delete_time: str | None
    child_num: int | None
    version: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> NodeBuilder: ...

class NodeBuilder:
    def __init__(self) -> None: ...
    def node_id(self, node_id: str) -> NodeBuilder: ...
    def space_id(self, space_id: str) -> NodeBuilder: ...
    def parent_id(self, parent_id: str) -> NodeBuilder: ...
    def obj_type(self, obj_type: int) -> NodeBuilder: ...
    def title(self, title: str) -> NodeBuilder: ...
    def url(self, url: str) -> NodeBuilder: ...
    def icon(self, icon: str) -> NodeBuilder: ...
    def area_id(self, area_id: str) -> NodeBuilder: ...
    def sort_id(self, sort_id: float) -> NodeBuilder: ...
    def domain(self, domain: str) -> NodeBuilder: ...
    def obj_token(self, obj_token: str) -> NodeBuilder: ...
    def create_time(self, create_time: str) -> NodeBuilder: ...
    def update_time(self, update_time: str) -> NodeBuilder: ...
    def delete_time(self, delete_time: str) -> NodeBuilder: ...
    def child_num(self, child_num: int) -> NodeBuilder: ...
    def version(self, version: int) -> NodeBuilder: ...
    def build(self) -> Node: ...
