from lark_oapi.core.construct import init as init

class ArchivePaymentActivityRequestBody:
    activity_id: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ArchivePaymentActivityRequestBodyBuilder: ...

class ArchivePaymentActivityRequestBodyBuilder:
    def __init__(self) -> None: ...
    def activity_id(self, activity_id: int) -> ArchivePaymentActivityRequestBodyBuilder: ...
    def build(self) -> ArchivePaymentActivityRequestBody: ...
