from .calendar_period import CalendarPeriod as CalendarPeriod
from lark_oapi.core.construct import init as init

class CalendarSuccessItem:
    id: str | None
    periods: list[CalendarPeriod] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CalendarSuccessItemBuilder: ...

class CalendarSuccessItemBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> CalendarSuccessItemBuilder: ...
    def periods(self, periods: list[CalendarPeriod]) -> CalendarSuccessItemBuilder: ...
    def build(self) -> CalendarSuccessItem: ...
