from .i18n_content import I18nContent as I18nContent
from lark_oapi.core.construct import init as init

class Calendar:
    id: str | None
    names: list[I18nContent] | None
    region: str | None
    work_calendar: str | None
    time_zone: str | None
    payroll_cycle: int | None
    status: int | None
    creator_id: str | None
    create_time: str | None
    effective_date: str | None
    period_years: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CalendarBuilder: ...

class CalendarBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> CalendarBuilder: ...
    def names(self, names: list[I18nContent]) -> CalendarBuilder: ...
    def region(self, region: str) -> CalendarBuilder: ...
    def work_calendar(self, work_calendar: str) -> CalendarBuilder: ...
    def time_zone(self, time_zone: str) -> CalendarBuilder: ...
    def payroll_cycle(self, payroll_cycle: int) -> CalendarBuilder: ...
    def status(self, status: int) -> CalendarBuilder: ...
    def creator_id(self, creator_id: str) -> CalendarBuilder: ...
    def create_time(self, create_time: str) -> CalendarBuilder: ...
    def effective_date(self, effective_date: str) -> CalendarBuilder: ...
    def period_years(self, period_years: list[str]) -> CalendarBuilder: ...
    def build(self) -> Calendar: ...
