from .calendar_period import CalendarPeriod as CalendarPeriod
from .collection_employee_data import CollectionEmployeeData as CollectionEmployeeData
from .country_region import CountryRegion as CountryRegion
from lark_oapi.core.construct import init as init

class CollectionActivityDataWithDetails:
    activity_id: str | None
    template_id: str | None
    template_version_id: str | None
    calendar_period: CalendarPeriod | None
    calendar_effective_date: str | None
    country_regions: list[CountryRegion] | None
    collection_employee_datas: list[CollectionEmployeeData] | None
    activity_approval_pass_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CollectionActivityDataWithDetailsBuilder: ...

class CollectionActivityDataWithDetailsBuilder:
    def __init__(self) -> None: ...
    def activity_id(self, activity_id: str) -> CollectionActivityDataWithDetailsBuilder: ...
    def template_id(self, template_id: str) -> CollectionActivityDataWithDetailsBuilder: ...
    def template_version_id(self, template_version_id: str) -> CollectionActivityDataWithDetailsBuilder: ...
    def calendar_period(self, calendar_period: CalendarPeriod) -> CollectionActivityDataWithDetailsBuilder: ...
    def calendar_effective_date(self, calendar_effective_date: str) -> CollectionActivityDataWithDetailsBuilder: ...
    def country_regions(self, country_regions: list[CountryRegion]) -> CollectionActivityDataWithDetailsBuilder: ...
    def collection_employee_datas(self, collection_employee_datas: list[CollectionEmployeeData]) -> CollectionActivityDataWithDetailsBuilder: ...
    def activity_approval_pass_time(self, activity_approval_pass_time: str) -> CollectionActivityDataWithDetailsBuilder: ...
    def build(self) -> CollectionActivityDataWithDetails: ...
