from lark_oapi.core.construct import init as init

class CollectionItemValue:
    item_id: str | None
    value: str | None
    field_type: int | None
    currency_id: str | None
    currency_code: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CollectionItemValueBuilder: ...

class CollectionItemValueBuilder:
    def __init__(self) -> None: ...
    def item_id(self, item_id: str) -> CollectionItemValueBuilder: ...
    def value(self, value: str) -> CollectionItemValueBuilder: ...
    def field_type(self, field_type: int) -> CollectionItemValueBuilder: ...
    def currency_id(self, currency_id: str) -> CollectionItemValueBuilder: ...
    def currency_code(self, currency_code: str) -> CollectionItemValueBuilder: ...
    def build(self) -> CollectionItemValue: ...
