from .i18n_content import I18nContent as I18nContent
from lark_oapi.core.construct import init as init

class CompensationCost:
    compensation_cost_value: str | None
    i18n_names: list[I18nContent] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CompensationCostBuilder: ...

class CompensationCostBuilder:
    def __init__(self) -> None: ...
    def compensation_cost_value(self, compensation_cost_value: str) -> CompensationCostBuilder: ...
    def i18n_names(self, i18n_names: list[I18nContent]) -> CompensationCostBuilder: ...
    def build(self) -> CompensationCost: ...
