from .cost_item import CostItem as CostItem
from .dimension import Dimension as Dimension
from .i18n_content import I18nContent as I18nContent
from lark_oapi.core.construct import init as init

class CostAllocationPlan:
    id: int | None
    names: list[I18nContent] | None
    applicable_country_region: str | None
    dimensions: list[Dimension] | None
    cost_items: list[CostItem] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CostAllocationPlanBuilder: ...

class CostAllocationPlanBuilder:
    def __init__(self) -> None: ...
    def id(self, id: int) -> CostAllocationPlanBuilder: ...
    def names(self, names: list[I18nContent]) -> CostAllocationPlanBuilder: ...
    def applicable_country_region(self, applicable_country_region: str) -> CostAllocationPlanBuilder: ...
    def dimensions(self, dimensions: list[Dimension]) -> CostAllocationPlanBuilder: ...
    def cost_items(self, cost_items: list[CostItem]) -> CostAllocationPlanBuilder: ...
    def build(self) -> CostAllocationPlan: ...
