from lark_oapi.core.construct import init as init

class CostItemValue:
    id: str | None
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CostItemValueBuilder: ...

class CostItemValueBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> CostItemValueBuilder: ...
    def value(self, value: str) -> CostItemValueBuilder: ...
    def build(self) -> CostItemValue: ...
