from lark_oapi.core.construct import init as init

class CountryRegion:
    id: str | None
    alpha3_code: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CountryRegionBuilder: ...

class CountryRegionBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> CountryRegionBuilder: ...
    def alpha3_code(self, alpha3_code: str) -> CountryRegionBuilder: ...
    def build(self) -> CountryRegion: ...
