from .dimension_value_lookup_info import DimensionValueLookupInfo as DimensionValueLookupInfo
from .enum_object import EnumObject as EnumObject
from .i18n_content import I18nContent as I18nContent
from lark_oapi.core.construct import init as init

class DataSummaryDimension:
    dimension_level: int | None
    dimension_type: int | None
    dimension_value_id: str | None
    enum_dimension: EnumObject | None
    dimension_value_lookup_info: DimensionValueLookupInfo | None
    dimension_names: list[I18nContent] | None
    dimension_titles: list[I18nContent] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DataSummaryDimensionBuilder: ...

class DataSummaryDimensionBuilder:
    def __init__(self) -> None: ...
    def dimension_level(self, dimension_level: int) -> DataSummaryDimensionBuilder: ...
    def dimension_type(self, dimension_type: int) -> DataSummaryDimensionBuilder: ...
    def dimension_value_id(self, dimension_value_id: str) -> DataSummaryDimensionBuilder: ...
    def enum_dimension(self, enum_dimension: EnumObject) -> DataSummaryDimensionBuilder: ...
    def dimension_value_lookup_info(self, dimension_value_lookup_info: DimensionValueLookupInfo) -> DataSummaryDimensionBuilder: ...
    def dimension_names(self, dimension_names: list[I18nContent]) -> DataSummaryDimensionBuilder: ...
    def dimension_titles(self, dimension_titles: list[I18nContent]) -> DataSummaryDimensionBuilder: ...
    def build(self) -> DataSummaryDimension: ...
