from .datasource_record_field import DatasourceRecordField as DatasourceRecordField
from lark_oapi.core.construct import init as init

class DatasourceRecord:
    active_status: int | None
    field_values: list[DatasourceRecordField] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DatasourceRecordBuilder: ...

class DatasourceRecordBuilder:
    def __init__(self) -> None: ...
    def active_status(self, active_status: int) -> DatasourceRecordBuilder: ...
    def field_values(self, field_values: list[DatasourceRecordField]) -> DatasourceRecordBuilder: ...
    def build(self) -> DatasourceRecord: ...
