from lark_oapi.core.construct import init as init

class DatasourceRecordFieldFilter:
    field_code: str | None
    field_values: list[str] | None
    operator: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DatasourceRecordFieldFilterBuilder: ...

class DatasourceRecordFieldFilterBuilder:
    def __init__(self) -> None: ...
    def field_code(self, field_code: str) -> DatasourceRecordFieldFilterBuilder: ...
    def field_values(self, field_values: list[str]) -> DatasourceRecordFieldFilterBuilder: ...
    def operator(self, operator: int) -> DatasourceRecordFieldFilterBuilder: ...
    def build(self) -> DatasourceRecordFieldFilter: ...
