from lark_oapi.core.construct import init as init

class DimensionValueLookupInfo:
    type: str | None
    id: str | None
    code: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DimensionValueLookupInfoBuilder: ...

class DimensionValueLookupInfoBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> DimensionValueLookupInfoBuilder: ...
    def id(self, id: str) -> DimensionValueLookupInfoBuilder: ...
    def code(self, code: str) -> DimensionValueLookupInfoBuilder: ...
    def build(self) -> DimensionValueLookupInfo: ...
