from .dmp_timeline_field import DmpTimelineField as DmpTimelineField
from lark_oapi.core.construct import init as init

class DmpChangeEvent:
    employee_number: str | None
    old_version_data: list[DmpTimelineField] | None
    new_version_data: list[DmpTimelineField] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DmpChangeEventBuilder: ...

class DmpChangeEventBuilder:
    def __init__(self) -> None: ...
    def employee_number(self, employee_number: str) -> DmpChangeEventBuilder: ...
    def old_version_data(self, old_version_data: list[DmpTimelineField]) -> DmpChangeEventBuilder: ...
    def new_version_data(self, new_version_data: list[DmpTimelineField]) -> DmpChangeEventBuilder: ...
    def build(self) -> DmpChangeEvent: ...
