from lark_oapi.core.construct import init as init

class DonationsTaxData:
    employee_id: int | None
    legal_name: str | None
    identity_type: str | None
    identity_number: str | None
    issuing_company: str | None
    non_tax_residence: str | None
    total_donation_amount: str | None
    tax_free_donation_amount30: str | None
    tax_free_donation_amount100: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DonationsTaxDataBuilder: ...

class DonationsTaxDataBuilder:
    def __init__(self) -> None: ...
    def employee_id(self, employee_id: int) -> DonationsTaxDataBuilder: ...
    def legal_name(self, legal_name: str) -> DonationsTaxDataBuilder: ...
    def identity_type(self, identity_type: str) -> DonationsTaxDataBuilder: ...
    def identity_number(self, identity_number: str) -> DonationsTaxDataBuilder: ...
    def issuing_company(self, issuing_company: str) -> DonationsTaxDataBuilder: ...
    def non_tax_residence(self, non_tax_residence: str) -> DonationsTaxDataBuilder: ...
    def total_donation_amount(self, total_donation_amount: str) -> DonationsTaxDataBuilder: ...
    def tax_free_donation_amount30(self, tax_free_donation_amount30: str) -> DonationsTaxDataBuilder: ...
    def tax_free_donation_amount100(self, tax_free_donation_amount100: str) -> DonationsTaxDataBuilder: ...
    def build(self) -> DonationsTaxData: ...
