from lark_oapi.core.construct import init as init

class EnumObject:
    enum_value_id: str | None
    enum_key: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EnumObjectBuilder: ...

class EnumObjectBuilder:
    def __init__(self) -> None: ...
    def enum_value_id(self, enum_value_id: str) -> EnumObjectBuilder: ...
    def enum_key(self, enum_key: str) -> EnumObjectBuilder: ...
    def build(self) -> EnumObject: ...
