from lark_oapi.core.construct import init as init

class FailInfo:
    idx: int | None
    error_code: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FailInfoBuilder: ...

class FailInfoBuilder:
    def __init__(self) -> None: ...
    def idx(self, idx: int) -> FailInfoBuilder: ...
    def error_code(self, error_code: int) -> FailInfoBuilder: ...
    def build(self) -> FailInfo: ...
