from lark_oapi.core.construct import init as init

class IntRange:
    greate_than: int | None
    greate_equal_than: int | None
    less_than: int | None
    less_equal_than: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> IntRangeBuilder: ...

class IntRangeBuilder:
    def __init__(self) -> None: ...
    def greate_than(self, greate_than: int) -> IntRangeBuilder: ...
    def greate_equal_than(self, greate_equal_than: int) -> IntRangeBuilder: ...
    def less_than(self, less_than: int) -> IntRangeBuilder: ...
    def less_equal_than(self, less_equal_than: int) -> IntRangeBuilder: ...
    def build(self) -> IntRange: ...
