from .paygroup import Paygroup as Paygroup
from lark_oapi.core.construct import init as init

class ListPaygroupResponseBody:
    items: list[Paygroup] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListPaygroupResponseBodyBuilder: ...

class ListPaygroupResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[Paygroup]) -> ListPaygroupResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListPaygroupResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListPaygroupResponseBodyBuilder: ...
    def build(self) -> ListPaygroupResponseBody: ...
