from .datasource import Datasource as Datasource
from lark_oapi.core.construct import init as init

class ListDatasourceResponseBody:
    page_token: str | None
    has_more: bool | None
    datasources: list[Datasource] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListDatasourceResponseBodyBuilder: ...

class ListDatasourceResponseBodyBuilder:
    def __init__(self) -> None: ...
    def page_token(self, page_token: str) -> ListDatasourceResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListDatasourceResponseBodyBuilder: ...
    def datasources(self, datasources: list[Datasource]) -> ListDatasourceResponseBodyBuilder: ...
    def build(self) -> ListDatasourceResponseBody: ...
