from .cost_allocation_plan import CostAllocationPlan as CostAllocationPlan
from lark_oapi.core.construct import init as init

class ListCostAllocationPlanResponseBody:
    items: list[CostAllocationPlan] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListCostAllocationPlanResponseBodyBuilder: ...

class ListCostAllocationPlanResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[CostAllocationPlan]) -> ListCostAllocationPlanResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListCostAllocationPlanResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListCostAllocationPlanResponseBodyBuilder: ...
    def build(self) -> ListCostAllocationPlanResponseBody: ...
