from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListPaymentActivityRequest(BaseRequest):
    pay_period_start_date: str | None
    pay_period_end_date: str | None
    page_size: int | None
    page_token: str | None
    statuses: list[int] | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListPaymentActivityRequestBuilder: ...

class ListPaymentActivityRequestBuilder:
    def __init__(self) -> None: ...
    def pay_period_start_date(self, pay_period_start_date: str) -> ListPaymentActivityRequestBuilder: ...
    def pay_period_end_date(self, pay_period_end_date: str) -> ListPaymentActivityRequestBuilder: ...
    def page_size(self, page_size: int) -> ListPaymentActivityRequestBuilder: ...
    def page_token(self, page_token: str) -> ListPaymentActivityRequestBuilder: ...
    def statuses(self, statuses: list[int]) -> ListPaymentActivityRequestBuilder: ...
    def build(self) -> ListPaymentActivityRequest: ...
