from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListPaymentActivityDetailRequest(BaseRequest):
    page_index: int | None
    page_size: int | None
    activity_id: int | None
    include_segment_data: bool | None
    acct_item_ids: list[int] | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListPaymentActivityDetailRequestBuilder: ...

class ListPaymentActivityDetailRequestBuilder:
    def __init__(self) -> None: ...
    def page_index(self, page_index: int) -> ListPaymentActivityDetailRequestBuilder: ...
    def page_size(self, page_size: int) -> ListPaymentActivityDetailRequestBuilder: ...
    def activity_id(self, activity_id: int) -> ListPaymentActivityDetailRequestBuilder: ...
    def include_segment_data(self, include_segment_data: bool) -> ListPaymentActivityDetailRequestBuilder: ...
    def acct_item_ids(self, acct_item_ids: list[int]) -> ListPaymentActivityDetailRequestBuilder: ...
    def build(self) -> ListPaymentActivityDetailRequest: ...
