from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListCostAllocationReportRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    cost_allocation_plan_id: int | None
    pay_period: str | None
    report_type: int | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListCostAllocationReportRequestBuilder: ...

class ListCostAllocationReportRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> ListCostAllocationReportRequestBuilder: ...
    def page_token(self, page_token: str) -> ListCostAllocationReportRequestBuilder: ...
    def cost_allocation_plan_id(self, cost_allocation_plan_id: int) -> ListCostAllocationReportRequestBuilder: ...
    def pay_period(self, pay_period: str) -> ListCostAllocationReportRequestBuilder: ...
    def report_type(self, report_type: int) -> ListCostAllocationReportRequestBuilder: ...
    def build(self) -> ListCostAllocationReportRequest: ...
