from .country_region import CountryRegion as CountryRegion
from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class PayGroup:
    pay_group_id: str | None
    name: I18n | None
    code: str | None
    status: str | None
    country_region: CountryRegion | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PayGroupBuilder: ...

class PayGroupBuilder:
    def __init__(self) -> None: ...
    def pay_group_id(self, pay_group_id: str) -> PayGroupBuilder: ...
    def name(self, name: I18n) -> PayGroupBuilder: ...
    def code(self, code: str) -> PayGroupBuilder: ...
    def status(self, status: str) -> PayGroupBuilder: ...
    def country_region(self, country_region: CountryRegion) -> PayGroupBuilder: ...
    def build(self) -> PayGroup: ...
