from .accounting_item_value import AccountingItemValue as AccountingItemValue
from .i18n_content import I18nContent as I18nContent
from .segment_value import SegmentValue as SegmentValue
from lark_oapi.core.construct import init as init

class PaymentAccountingItem:
    id: str | None
    accounting_item_names: list[I18nContent] | None
    accounting_item_value: AccountingItemValue | None
    segment_values: list[SegmentValue] | None
    accounting_item_type: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PaymentAccountingItemBuilder: ...

class PaymentAccountingItemBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> PaymentAccountingItemBuilder: ...
    def accounting_item_names(self, accounting_item_names: list[I18nContent]) -> PaymentAccountingItemBuilder: ...
    def accounting_item_value(self, accounting_item_value: AccountingItemValue) -> PaymentAccountingItemBuilder: ...
    def segment_values(self, segment_values: list[SegmentValue]) -> PaymentAccountingItemBuilder: ...
    def accounting_item_type(self, accounting_item_type: int) -> PaymentAccountingItemBuilder: ...
    def build(self) -> PaymentAccountingItem: ...
