from .calculation_activity import CalculationActivity as CalculationActivity
from .i18n_content import I18nContent as I18nContent
from lark_oapi.core.construct import init as init

class PaymentActivity:
    activity_id: int | None
    activity_names: list[I18nContent] | None
    pay_date: str | None
    total_number_of_payroll: int | None
    number_of_calculation_activities: int | None
    calculation_activities: list[CalculationActivity] | None
    activity_status: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PaymentActivityBuilder: ...

class PaymentActivityBuilder:
    def __init__(self) -> None: ...
    def activity_id(self, activity_id: int) -> PaymentActivityBuilder: ...
    def activity_names(self, activity_names: list[I18nContent]) -> PaymentActivityBuilder: ...
    def pay_date(self, pay_date: str) -> PaymentActivityBuilder: ...
    def total_number_of_payroll(self, total_number_of_payroll: int) -> PaymentActivityBuilder: ...
    def number_of_calculation_activities(self, number_of_calculation_activities: int) -> PaymentActivityBuilder: ...
    def calculation_activities(self, calculation_activities: list[CalculationActivity]) -> PaymentActivityBuilder: ...
    def activity_status(self, activity_status: int) -> PaymentActivityBuilder: ...
    def build(self) -> PaymentActivity: ...
