from .query_payment_detail_request_body import QueryPaymentDetailRequestBody as QueryPaymentDetailRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class QueryPaymentDetailRequest(BaseRequest):
    request_body: QueryPaymentDetailRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> QueryPaymentDetailRequestBuilder: ...

class QueryPaymentDetailRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: QueryPaymentDetailRequestBody) -> QueryPaymentDetailRequestBuilder: ...
    def build(self) -> QueryPaymentDetailRequest: ...
