from .datasource_record import DatasourceRecord as DatasourceRecord
from lark_oapi.core.construct import init as init

class SaveDatasourceRecordRequestBody:
    source_code: str | None
    records: list[DatasourceRecord] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SaveDatasourceRecordRequestBodyBuilder: ...

class SaveDatasourceRecordRequestBodyBuilder:
    def __init__(self) -> None: ...
    def source_code(self, source_code: str) -> SaveDatasourceRecordRequestBodyBuilder: ...
    def records(self, records: list[DatasourceRecord]) -> SaveDatasourceRecordRequestBodyBuilder: ...
    def build(self) -> SaveDatasourceRecordRequestBody: ...
