from .save_datasource_record_request_body import SaveDatasourceRecordRequestBody as SaveDatasourceRecordRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class SaveDatasourceRecordRequest(BaseRequest):
    request_body: SaveDatasourceRecordRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> SaveDatasourceRecordRequestBuilder: ...

class SaveDatasourceRecordRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: SaveDatasourceRecordRequestBody) -> SaveDatasourceRecordRequestBuilder: ...
    def build(self) -> SaveDatasourceRecordRequest: ...
