from .id_with_name import IdWithName as IdWithName
from lark_oapi.core.construct import init as init

class VerifDatasourceItem:
    name: IdWithName | None
    field_id: str | None
    field_type: int | None
    object_api_name: str | None
    field_api_name: str | None
    decimal_places: int | None
    object_type: int | None
    source_type: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> VerifDatasourceItemBuilder: ...

class VerifDatasourceItemBuilder:
    def __init__(self) -> None: ...
    def name(self, name: IdWithName) -> VerifDatasourceItemBuilder: ...
    def field_id(self, field_id: str) -> VerifDatasourceItemBuilder: ...
    def field_type(self, field_type: int) -> VerifDatasourceItemBuilder: ...
    def object_api_name(self, object_api_name: str) -> VerifDatasourceItemBuilder: ...
    def field_api_name(self, field_api_name: str) -> VerifDatasourceItemBuilder: ...
    def decimal_places(self, decimal_places: int) -> VerifDatasourceItemBuilder: ...
    def object_type(self, object_type: int) -> VerifDatasourceItemBuilder: ...
    def source_type(self, source_type: int) -> VerifDatasourceItemBuilder: ...
    def build(self) -> VerifDatasourceItem: ...
