from .verif_field_source_config import VerifFieldSourceConfig as VerifFieldSourceConfig
from lark_oapi.core.construct import init as init

class VerifSourceConfig:
    formula_config: VerifFieldSourceConfig | None
    ref_source_config: VerifFieldSourceConfig | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> VerifSourceConfigBuilder: ...

class VerifSourceConfigBuilder:
    def __init__(self) -> None: ...
    def formula_config(self, formula_config: VerifFieldSourceConfig) -> VerifSourceConfigBuilder: ...
    def ref_source_config(self, ref_source_config: VerifFieldSourceConfig) -> VerifSourceConfigBuilder: ...
    def build(self) -> VerifSourceConfig: ...
