from .id_with_name import IdWithName as IdWithName
from lark_oapi.core.construct import init as init

class VerifFilterValue:
    api_name: str | None
    field_type: int | None
    value: str | None
    ref_id: str | None
    currency: IdWithName | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> VerifFilterValueBuilder: ...

class VerifFilterValueBuilder:
    def __init__(self) -> None: ...
    def api_name(self, api_name: str) -> VerifFilterValueBuilder: ...
    def field_type(self, field_type: int) -> VerifFilterValueBuilder: ...
    def value(self, value: str) -> VerifFilterValueBuilder: ...
    def ref_id(self, ref_id: str) -> VerifFilterValueBuilder: ...
    def currency(self, currency: IdWithName) -> VerifFilterValueBuilder: ...
    def build(self) -> VerifFilterValue: ...
