from ..const import UTF_8 as UTF_8
from _typeshed import Incomplete

class AESCipher:
    digest: Incomplete
    def __init__(self, key: str | bytes) -> None: ...
    def decrypt(self, enc: bytes) -> bytes: ...
    def decrypt_str(self, enc: str) -> str: ...
