from lark_oapi.core.construct import init as init

class Attachment:
    file_id: str | None
    file_name: str | None
    content_type: str | None
    file_size: int | None
    create_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AttachmentBuilder: ...

class AttachmentBuilder:
    def __init__(self) -> None: ...
    def file_id(self, file_id: str) -> AttachmentBuilder: ...
    def file_name(self, file_name: str) -> AttachmentBuilder: ...
    def content_type(self, content_type: str) -> AttachmentBuilder: ...
    def file_size(self, file_size: int) -> AttachmentBuilder: ...
    def create_time(self, create_time: str) -> AttachmentBuilder: ...
    def build(self) -> Attachment: ...
