from .i18n import I18n as I18n
from .talent_customized_data_child import TalentCustomizedDataChild as TalentCustomizedDataChild
from lark_oapi.core.construct import init as init

class CompositeTalentCustomizedData:
    module_id: str | None
    name: I18n | None
    object_type: int | None
    children: list[TalentCustomizedDataChild] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CompositeTalentCustomizedDataBuilder: ...

class CompositeTalentCustomizedDataBuilder:
    def __init__(self) -> None: ...
    def module_id(self, module_id: str) -> CompositeTalentCustomizedDataBuilder: ...
    def name(self, name: I18n) -> CompositeTalentCustomizedDataBuilder: ...
    def object_type(self, object_type: int) -> CompositeTalentCustomizedDataBuilder: ...
    def children(self, children: list[TalentCustomizedDataChild]) -> CompositeTalentCustomizedDataBuilder: ...
    def build(self) -> CompositeTalentCustomizedData: ...
