from .talent_customized_data_child import TalentCustomizedDataChild as TalentCustomizedDataChild
from lark_oapi.core.construct import init as init

class CompositeTalentAwardInfo:
    award_name: str | None
    award_time: str | None
    description: str | None
    customized_data_list: list[TalentCustomizedDataChild] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CompositeTalentAwardInfoBuilder: ...

class CompositeTalentAwardInfoBuilder:
    def __init__(self) -> None: ...
    def award_name(self, award_name: str) -> CompositeTalentAwardInfoBuilder: ...
    def award_time(self, award_time: str) -> CompositeTalentAwardInfoBuilder: ...
    def description(self, description: str) -> CompositeTalentAwardInfoBuilder: ...
    def customized_data_list(self, customized_data_list: list[TalentCustomizedDataChild]) -> CompositeTalentAwardInfoBuilder: ...
    def build(self) -> CompositeTalentAwardInfo: ...
