from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetInterviewRecordRequest(BaseRequest):
    user_id_type: str | None
    interview_record_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetInterviewRecordRequestBuilder: ...

class GetInterviewRecordRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> GetInterviewRecordRequestBuilder: ...
    def interview_record_id(self, interview_record_id: str) -> GetInterviewRecordRequestBuilder: ...
    def build(self) -> GetInterviewRecordRequest: ...
