from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetTalentRequest(BaseRequest):
    user_id_type: str | None
    talent_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetTalentRequestBuilder: ...

class GetTalentRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> GetTalentRequestBuilder: ...
    def talent_id(self, talent_id: str) -> GetTalentRequestBuilder: ...
    def build(self) -> GetTalentRequest: ...
