from lark_oapi.core.construct import init as init

class TalentFolder:
    name: str | None
    folder_id: str | None
    owner_id: str | None
    add_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TalentFolderBuilder: ...

class TalentFolderBuilder:
    def __init__(self) -> None: ...
    def name(self, name: str) -> TalentFolderBuilder: ...
    def folder_id(self, folder_id: str) -> TalentFolderBuilder: ...
    def owner_id(self, owner_id: str) -> TalentFolderBuilder: ...
    def add_time(self, add_time: str) -> TalentFolderBuilder: ...
    def build(self) -> TalentFolder: ...
