from lark_oapi.core.construct import init as init

class TalentNote:
    id: str | None
    talent_id: str | None
    application_id: str | None
    create_time: str | None
    update_time: str | None
    creator_id: str | None
    content: str | None
    privacy: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TalentNoteBuilder: ...

class TalentNoteBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> TalentNoteBuilder: ...
    def talent_id(self, talent_id: str) -> TalentNoteBuilder: ...
    def application_id(self, application_id: str) -> TalentNoteBuilder: ...
    def create_time(self, create_time: str) -> TalentNoteBuilder: ...
    def update_time(self, update_time: str) -> TalentNoteBuilder: ...
    def creator_id(self, creator_id: str) -> TalentNoteBuilder: ...
    def content(self, content: str) -> TalentNoteBuilder: ...
    def privacy(self, privacy: int) -> TalentNoteBuilder: ...
    def build(self) -> TalentNote: ...
