from lark_oapi.core.construct import init as init

class TalentResumeAttachment:
    id: str | None
    name: str | None
    mime: str | None
    create_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TalentResumeAttachmentBuilder: ...

class TalentResumeAttachmentBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> TalentResumeAttachmentBuilder: ...
    def name(self, name: str) -> TalentResumeAttachmentBuilder: ...
    def mime(self, mime: str) -> TalentResumeAttachmentBuilder: ...
    def create_time(self, create_time: str) -> TalentResumeAttachmentBuilder: ...
    def build(self) -> TalentResumeAttachment: ...
