from .i18n import I18n as I18n
from .talent_customized_value import TalentCustomizedValue as TalentCustomizedValue
from lark_oapi.core.construct import init as init

class TalentCustomizedDataChild:
    object_id: str | None
    name: I18n | None
    object_type: int | None
    value: TalentCustomizedValue | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TalentCustomizedDataChildBuilder: ...

class TalentCustomizedDataChildBuilder:
    def __init__(self) -> None: ...
    def object_id(self, object_id: str) -> TalentCustomizedDataChildBuilder: ...
    def name(self, name: I18n) -> TalentCustomizedDataChildBuilder: ...
    def object_type(self, object_type: int) -> TalentCustomizedDataChildBuilder: ...
    def value(self, value: TalentCustomizedValue) -> TalentCustomizedDataChildBuilder: ...
    def build(self) -> TalentCustomizedDataChild: ...
