from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class TalentTag:
    id: str | None
    name: I18n | None
    description: I18n | None
    type: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TalentTagBuilder: ...

class TalentTagBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> TalentTagBuilder: ...
    def name(self, name: I18n) -> TalentTagBuilder: ...
    def description(self, description: I18n) -> TalentTagBuilder: ...
    def type(self, type: int) -> TalentTagBuilder: ...
    def build(self) -> TalentTag: ...
