from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class TalentPool:
    id: str | None
    name: I18n | None
    description: I18n | None
    add_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TalentPoolBuilder: ...

class TalentPoolBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> TalentPoolBuilder: ...
    def name(self, name: I18n) -> TalentPoolBuilder: ...
    def description(self, description: I18n) -> TalentPoolBuilder: ...
    def add_time(self, add_time: str) -> TalentPoolBuilder: ...
    def build(self) -> TalentPool: ...
