from ..model.create_room_level_request import CreateRoomLevelRequest as CreateRoomLevelRequest
from ..model.create_room_level_response import CreateRoomLevelResponse as CreateRoomLevelResponse
from ..model.del_room_level_request import DelRoomLevelRequest as DelRoomLevelRequest
from ..model.del_room_level_response import DelRoomLevelResponse as DelRoomLevelResponse
from ..model.get_room_level_request import GetRoomLevelRequest as GetRoomLevelRequest
from ..model.get_room_level_response import GetRoomLevelResponse as GetRoomLevelResponse
from ..model.list_room_level_request import ListRoomLevelRequest as ListRoomLevelRequest
from ..model.list_room_level_response import ListRoomLevelResponse as ListRoomLevelResponse
from ..model.mget_room_level_request import MgetRoomLevelRequest as MgetRoomLevelRequest
from ..model.mget_room_level_response import MgetRoomLevelResponse as MgetRoomLevelResponse
from ..model.patch_room_level_request import PatchRoomLevelRequest as PatchRoomLevelRequest
from ..model.patch_room_level_response import PatchRoomLevelResponse as PatchRoomLevelResponse
from ..model.search_room_level_request import SearchRoomLevelRequest as SearchRoomLevelRequest
from ..model.search_room_level_response import SearchRoomLevelResponse as SearchRoomLevelResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class RoomLevel:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def create(self, request: CreateRoomLevelRequest, option: RequestOption | None = None) -> CreateRoomLevelResponse: ...
    async def acreate(self, request: CreateRoomLevelRequest, option: RequestOption | None = None) -> CreateRoomLevelResponse: ...
    def del_(self, request: DelRoomLevelRequest, option: RequestOption | None = None) -> DelRoomLevelResponse: ...
    async def adel_(self, request: DelRoomLevelRequest, option: RequestOption | None = None) -> DelRoomLevelResponse: ...
    def get(self, request: GetRoomLevelRequest, option: RequestOption | None = None) -> GetRoomLevelResponse: ...
    async def aget(self, request: GetRoomLevelRequest, option: RequestOption | None = None) -> GetRoomLevelResponse: ...
    def list(self, request: ListRoomLevelRequest, option: RequestOption | None = None) -> ListRoomLevelResponse: ...
    async def alist(self, request: ListRoomLevelRequest, option: RequestOption | None = None) -> ListRoomLevelResponse: ...
    def mget(self, request: MgetRoomLevelRequest, option: RequestOption | None = None) -> MgetRoomLevelResponse: ...
    async def amget(self, request: MgetRoomLevelRequest, option: RequestOption | None = None) -> MgetRoomLevelResponse: ...
    def patch(self, request: PatchRoomLevelRequest, option: RequestOption | None = None) -> PatchRoomLevelResponse: ...
    async def apatch(self, request: PatchRoomLevelRequest, option: RequestOption | None = None) -> PatchRoomLevelResponse: ...
    def search(self, request: SearchRoomLevelRequest, option: RequestOption | None = None) -> SearchRoomLevelResponse: ...
    async def asearch(self, request: SearchRoomLevelRequest, option: RequestOption | None = None) -> SearchRoomLevelResponse: ...
