from .member import Member as Member
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateSpaceMemberRequest(BaseRequest):
    need_notification: bool | None
    space_id: str | None
    request_body: Member | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateSpaceMemberRequestBuilder: ...

class CreateSpaceMemberRequestBuilder:
    def __init__(self) -> None: ...
    def need_notification(self, need_notification: bool) -> CreateSpaceMemberRequestBuilder: ...
    def space_id(self, space_id: str) -> CreateSpaceMemberRequestBuilder: ...
    def request_body(self, request_body: Member) -> CreateSpaceMemberRequestBuilder: ...
    def build(self) -> CreateSpaceMemberRequest: ...
