from .node import Node as Node
from lark_oapi.core.construct import init as init

class CreateSpaceNodeResponseBody:
    node: Node | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateSpaceNodeResponseBodyBuilder: ...

class CreateSpaceNodeResponseBodyBuilder:
    def __init__(self) -> None: ...
    def node(self, node: Node) -> CreateSpaceNodeResponseBodyBuilder: ...
    def build(self) -> CreateSpaceNodeResponseBody: ...
