from .member import Member as Member
from lark_oapi.core.construct import init as init

class CreateSpaceMemberResponseBody:
    member: Member | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateSpaceMemberResponseBodyBuilder: ...

class CreateSpaceMemberResponseBodyBuilder:
    def __init__(self) -> None: ...
    def member(self, member: Member) -> CreateSpaceMemberResponseBodyBuilder: ...
    def build(self) -> CreateSpaceMemberResponseBody: ...
