from .member import Member as Member
from lark_oapi.core.construct import init as init

class DeleteSpaceMemberResponseBody:
    member: Member | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteSpaceMemberResponseBodyBuilder: ...

class DeleteSpaceMemberResponseBodyBuilder:
    def __init__(self) -> None: ...
    def member(self, member: Member) -> DeleteSpaceMemberResponseBodyBuilder: ...
    def build(self) -> DeleteSpaceMemberResponseBody: ...
