from .space import Space as Space
from lark_oapi.core.construct import init as init

class GetSpaceResponseBody:
    space: Space | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetSpaceResponseBodyBuilder: ...

class GetSpaceResponseBodyBuilder:
    def __init__(self) -> None: ...
    def space(self, space: Space) -> GetSpaceResponseBodyBuilder: ...
    def build(self) -> GetSpaceResponseBody: ...
