from lark_oapi.core.construct import init as init

class ListSpaceRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListSpaceRequestBodyBuilder: ...

class ListSpaceRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListSpaceRequestBody: ...
