from .member import Member as Member
from lark_oapi.core.construct import init as init

class ListSpaceMemberResponseBody:
    members: list[Member] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListSpaceMemberResponseBodyBuilder: ...

class ListSpaceMemberResponseBodyBuilder:
    def __init__(self) -> None: ...
    def members(self, members: list[Member]) -> ListSpaceMemberResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListSpaceMemberResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListSpaceMemberResponseBodyBuilder: ...
    def build(self) -> ListSpaceMemberResponseBody: ...
