from lark_oapi.core.construct import init as init

class Member:
    member_type: str | None
    member_id: str | None
    member_role: str | None
    type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MemberBuilder: ...

class MemberBuilder:
    def __init__(self) -> None: ...
    def member_type(self, member_type: str) -> MemberBuilder: ...
    def member_id(self, member_id: str) -> MemberBuilder: ...
    def member_role(self, member_role: str) -> MemberBuilder: ...
    def type(self, type: str) -> MemberBuilder: ...
    def build(self) -> Member: ...
