from .move_space_node_request_body import MoveSpaceNodeRequestBody as MoveSpaceNodeRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class MoveSpaceNodeRequest(BaseRequest):
    space_id: str | None
    node_token: str | None
    request_body: MoveSpaceNodeRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> MoveSpaceNodeRequestBuilder: ...

class MoveSpaceNodeRequestBuilder:
    def __init__(self) -> None: ...
    def space_id(self, space_id: str) -> MoveSpaceNodeRequestBuilder: ...
    def node_token(self, node_token: str) -> MoveSpaceNodeRequestBuilder: ...
    def request_body(self, request_body: MoveSpaceNodeRequestBody) -> MoveSpaceNodeRequestBuilder: ...
    def build(self) -> MoveSpaceNodeRequest: ...
