from .node import Node as Node
from lark_oapi.core.construct import init as init

class MoveSpaceNodeResponseBody:
    node: Node | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MoveSpaceNodeResponseBodyBuilder: ...

class MoveSpaceNodeResponseBodyBuilder:
    def __init__(self) -> None: ...
    def node(self, node: Node) -> MoveSpaceNodeResponseBodyBuilder: ...
    def build(self) -> MoveSpaceNodeResponseBody: ...
