from lark_oapi.core.construct import init as init

class Space:
    name: str | None
    description: str | None
    space_id: str | None
    space_type: str | None
    visibility: str | None
    open_sharing: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SpaceBuilder: ...

class SpaceBuilder:
    def __init__(self) -> None: ...
    def name(self, name: str) -> SpaceBuilder: ...
    def description(self, description: str) -> SpaceBuilder: ...
    def space_id(self, space_id: str) -> SpaceBuilder: ...
    def space_type(self, space_type: str) -> SpaceBuilder: ...
    def visibility(self, visibility: str) -> SpaceBuilder: ...
    def open_sharing(self, open_sharing: str) -> SpaceBuilder: ...
    def build(self) -> Space: ...
