from lark_oapi.core.construct import init as init

class UpdateTitleSpaceNodeResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateTitleSpaceNodeResponseBodyBuilder: ...

class UpdateTitleSpaceNodeResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> UpdateTitleSpaceNodeResponseBody: ...
