from .setting import Setting as Setting
from lark_oapi.core.construct import init as init

class UpdateSpaceSettingResponseBody:
    setting: Setting | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateSpaceSettingResponseBodyBuilder: ...

class UpdateSpaceSettingResponseBodyBuilder:
    def __init__(self) -> None: ...
    def setting(self, setting: Setting) -> UpdateSpaceSettingResponseBodyBuilder: ...
    def build(self) -> UpdateSpaceSettingResponseBody: ...
