from lark_oapi.core.construct import init as init

class AddCustomFieldRequestBody:
    resource_type: str | None
    resource_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AddCustomFieldRequestBodyBuilder: ...

class AddCustomFieldRequestBodyBuilder:
    def __init__(self) -> None: ...
    def resource_type(self, resource_type: str) -> AddCustomFieldRequestBodyBuilder: ...
    def resource_id(self, resource_id: str) -> AddCustomFieldRequestBodyBuilder: ...
    def build(self) -> AddCustomFieldRequestBody: ...
