from .task import Task as Task
from lark_oapi.core.construct import init as init

class AddRemindersTaskResponseBody:
    task: Task | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AddRemindersTaskResponseBodyBuilder: ...

class AddRemindersTaskResponseBodyBuilder:
    def __init__(self) -> None: ...
    def task(self, task: Task) -> AddRemindersTaskResponseBodyBuilder: ...
    def build(self) -> AddRemindersTaskResponseBody: ...
