from .reminder import Reminder as Reminder
from lark_oapi.core.construct import init as init

class AddRemindersTaskRequestBody:
    reminders: list[Reminder] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AddRemindersTaskRequestBodyBuilder: ...

class AddRemindersTaskRequestBodyBuilder:
    def __init__(self) -> None: ...
    def reminders(self, reminders: list[Reminder]) -> AddRemindersTaskRequestBodyBuilder: ...
    def build(self) -> AddRemindersTaskRequestBody: ...
