from lark_oapi.core.construct import init as init

class AddCustomFieldResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AddCustomFieldResponseBodyBuilder: ...

class AddCustomFieldResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> AddCustomFieldResponseBody: ...
