from .add_members_tasklist_request_body import AddMembersTasklistRequestBody as AddMembersTasklistRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class AddMembersTasklistRequest(BaseRequest):
    user_id_type: str | None
    tasklist_guid: str | None
    request_body: AddMembersTasklistRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> AddMembersTasklistRequestBuilder: ...

class AddMembersTasklistRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> AddMembersTasklistRequestBuilder: ...
    def tasklist_guid(self, tasklist_guid: str) -> AddMembersTasklistRequestBuilder: ...
    def request_body(self, request_body: AddMembersTasklistRequestBody) -> AddMembersTasklistRequestBuilder: ...
    def build(self) -> AddMembersTasklistRequest: ...
