from .member import Member as Member
from lark_oapi.core.construct import init as init

class AddMembersTasklistRequestBody:
    members: list[Member] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AddMembersTasklistRequestBodyBuilder: ...

class AddMembersTasklistRequestBodyBuilder:
    def __init__(self) -> None: ...
    def members(self, members: list[Member]) -> AddMembersTasklistRequestBodyBuilder: ...
    def build(self) -> AddMembersTasklistRequestBody: ...
