from .task_dependency import TaskDependency as TaskDependency
from lark_oapi.core.construct import init as init

class AddDependenciesTaskRequestBody:
    dependencies: list[TaskDependency] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AddDependenciesTaskRequestBodyBuilder: ...

class AddDependenciesTaskRequestBodyBuilder:
    def __init__(self) -> None: ...
    def dependencies(self, dependencies: list[TaskDependency]) -> AddDependenciesTaskRequestBodyBuilder: ...
    def build(self) -> AddDependenciesTaskRequestBody: ...
