from .tasklist_activity_subscription import TasklistActivitySubscription as TasklistActivitySubscription
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateTasklistActivitySubscriptionRequest(BaseRequest):
    user_id_type: str | None
    tasklist_guid: str | None
    request_body: TasklistActivitySubscription | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateTasklistActivitySubscriptionRequestBuilder: ...

class CreateTasklistActivitySubscriptionRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> CreateTasklistActivitySubscriptionRequestBuilder: ...
    def tasklist_guid(self, tasklist_guid: str) -> CreateTasklistActivitySubscriptionRequestBuilder: ...
    def request_body(self, request_body: TasklistActivitySubscription) -> CreateTasklistActivitySubscriptionRequestBuilder: ...
    def build(self) -> CreateTasklistActivitySubscriptionRequest: ...
