from .input_option import InputOption as InputOption
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateCustomFieldOptionRequest(BaseRequest):
    custom_field_guid: str | None
    request_body: InputOption | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateCustomFieldOptionRequestBuilder: ...

class CreateCustomFieldOptionRequestBuilder:
    def __init__(self) -> None: ...
    def custom_field_guid(self, custom_field_guid: str) -> CreateCustomFieldOptionRequestBuilder: ...
    def request_body(self, request_body: InputOption) -> CreateCustomFieldOptionRequestBuilder: ...
    def build(self) -> CreateCustomFieldOptionRequest: ...
