from .input_task import InputTask as InputTask
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateTaskSubtaskRequest(BaseRequest):
    user_id_type: str | None
    task_guid: str | None
    request_body: InputTask | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateTaskSubtaskRequestBuilder: ...

class CreateTaskSubtaskRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> CreateTaskSubtaskRequestBuilder: ...
    def task_guid(self, task_guid: str) -> CreateTaskSubtaskRequestBuilder: ...
    def request_body(self, request_body: InputTask) -> CreateTaskSubtaskRequestBuilder: ...
    def build(self) -> CreateTaskSubtaskRequest: ...
