from .tasklist import Tasklist as Tasklist
from lark_oapi.core.construct import init as init

class CreateTasklistResponseBody:
    tasklist: Tasklist | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateTasklistResponseBodyBuilder: ...

class CreateTasklistResponseBodyBuilder:
    def __init__(self) -> None: ...
    def tasklist(self, tasklist: Tasklist) -> CreateTasklistResponseBodyBuilder: ...
    def build(self) -> CreateTasklistResponseBody: ...
