from .section import Section as Section
from lark_oapi.core.construct import init as init

class CreateSectionResponseBody:
    section: Section | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateSectionResponseBodyBuilder: ...

class CreateSectionResponseBodyBuilder:
    def __init__(self) -> None: ...
    def section(self, section: Section) -> CreateSectionResponseBodyBuilder: ...
    def build(self) -> CreateSectionResponseBody: ...
