from .input_custom_field import InputCustomField as InputCustomField
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateCustomFieldRequest(BaseRequest):
    user_id_type: str | None
    request_body: InputCustomField | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateCustomFieldRequestBuilder: ...

class CreateCustomFieldRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> CreateCustomFieldRequestBuilder: ...
    def request_body(self, request_body: InputCustomField) -> CreateCustomFieldRequestBuilder: ...
    def build(self) -> CreateCustomFieldRequest: ...
