from .input_tasklist import InputTasklist as InputTasklist
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateTasklistRequest(BaseRequest):
    user_id_type: str | None
    request_body: InputTasklist | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateTasklistRequestBuilder: ...

class CreateTasklistRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> CreateTasklistRequestBuilder: ...
    def request_body(self, request_body: InputTasklist) -> CreateTasklistRequestBuilder: ...
    def build(self) -> CreateTasklistRequest: ...
