from .custom_complete_item import CustomCompleteItem as CustomCompleteItem
from lark_oapi.core.construct import init as init

class CustomComplete:
    pc: CustomCompleteItem | None
    ios: CustomCompleteItem | None
    android: CustomCompleteItem | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CustomCompleteBuilder: ...

class CustomCompleteBuilder:
    def __init__(self) -> None: ...
    def pc(self, pc: CustomCompleteItem) -> CustomCompleteBuilder: ...
    def ios(self, ios: CustomCompleteItem) -> CustomCompleteBuilder: ...
    def android(self, android: CustomCompleteItem) -> CustomCompleteBuilder: ...
    def build(self) -> CustomComplete: ...
