from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteSectionRequest(BaseRequest):
    section_guid: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteSectionRequestBuilder: ...

class DeleteSectionRequestBuilder:
    def __init__(self) -> None: ...
    def section_guid(self, section_guid: str) -> DeleteSectionRequestBuilder: ...
    def build(self) -> DeleteSectionRequest: ...
