from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteTasklistRequest(BaseRequest):
    tasklist_guid: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteTasklistRequestBuilder: ...

class DeleteTasklistRequestBuilder:
    def __init__(self) -> None: ...
    def tasklist_guid(self, tasklist_guid: str) -> DeleteTasklistRequestBuilder: ...
    def build(self) -> DeleteTasklistRequest: ...
