from lark_oapi.core.construct import init as init

class DeleteTasklistActivitySubscriptionResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteTasklistActivitySubscriptionResponseBodyBuilder: ...

class DeleteTasklistActivitySubscriptionResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteTasklistActivitySubscriptionResponseBody: ...
