from .tasklist_activity_subscription import TasklistActivitySubscription as TasklistActivitySubscription
from lark_oapi.core.construct import init as init

class GetTasklistActivitySubscriptionResponseBody:
    activity_subscription: TasklistActivitySubscription | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetTasklistActivitySubscriptionResponseBodyBuilder: ...

class GetTasklistActivitySubscriptionResponseBodyBuilder:
    def __init__(self) -> None: ...
    def activity_subscription(self, activity_subscription: TasklistActivitySubscription) -> GetTasklistActivitySubscriptionResponseBodyBuilder: ...
    def build(self) -> GetTasklistActivitySubscriptionResponseBody: ...
