from lark_oapi.core.construct import init as init

class GetCustomFieldRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetCustomFieldRequestBodyBuilder: ...

class GetCustomFieldRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetCustomFieldRequestBody: ...
