from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetTaskRequest(BaseRequest):
    user_id_type: str | None
    task_guid: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetTaskRequestBuilder: ...

class GetTaskRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> GetTaskRequestBuilder: ...
    def task_guid(self, task_guid: str) -> GetTaskRequestBuilder: ...
    def build(self) -> GetTaskRequest: ...
