from lark_oapi.core.construct import init as init

class GetSectionRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetSectionRequestBodyBuilder: ...

class GetSectionRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetSectionRequestBody: ...
