from .task import Task as Task
from lark_oapi.core.construct import init as init

class GetTaskResponseBody:
    task: Task | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetTaskResponseBodyBuilder: ...

class GetTaskResponseBodyBuilder:
    def __init__(self) -> None: ...
    def task(self, task: Task) -> GetTaskResponseBodyBuilder: ...
    def build(self) -> GetTaskResponseBody: ...
