from lark_oapi.core.construct import init as init

class GetTasklistRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetTasklistRequestBodyBuilder: ...

class GetTasklistRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetTasklistRequestBody: ...
