from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetAttachmentRequest(BaseRequest):
    user_id_type: str | None
    attachment_guid: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetAttachmentRequestBuilder: ...

class GetAttachmentRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> GetAttachmentRequestBuilder: ...
    def attachment_guid(self, attachment_guid: str) -> GetAttachmentRequestBuilder: ...
    def build(self) -> GetAttachmentRequest: ...
