from .datetime_setting import DatetimeSetting as DatetimeSetting
from .member_setting import MemberSetting as MemberSetting
from .number_setting import NumberSetting as NumberSetting
from .select_setting import SelectSetting as SelectSetting
from .text_setting import TextSetting as TextSetting
from lark_oapi.core.construct import init as init

class InputCustomField:
    resource_type: str | None
    resource_id: str | None
    name: str | None
    type: str | None
    number_setting: NumberSetting | None
    member_setting: MemberSetting | None
    datetime_setting: DatetimeSetting | None
    single_select_setting: SelectSetting | None
    multi_select_setting: SelectSetting | None
    text_setting: TextSetting | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InputCustomFieldBuilder: ...

class InputCustomFieldBuilder:
    def __init__(self) -> None: ...
    def resource_type(self, resource_type: str) -> InputCustomFieldBuilder: ...
    def resource_id(self, resource_id: str) -> InputCustomFieldBuilder: ...
    def name(self, name: str) -> InputCustomFieldBuilder: ...
    def type(self, type: str) -> InputCustomFieldBuilder: ...
    def number_setting(self, number_setting: NumberSetting) -> InputCustomFieldBuilder: ...
    def member_setting(self, member_setting: MemberSetting) -> InputCustomFieldBuilder: ...
    def datetime_setting(self, datetime_setting: DatetimeSetting) -> InputCustomFieldBuilder: ...
    def single_select_setting(self, single_select_setting: SelectSetting) -> InputCustomFieldBuilder: ...
    def multi_select_setting(self, multi_select_setting: SelectSetting) -> InputCustomFieldBuilder: ...
    def text_setting(self, text_setting: TextSetting) -> InputCustomFieldBuilder: ...
    def build(self) -> InputCustomField: ...
