from .member import Member as Member
from lark_oapi.core.construct import init as init

class InputTasklist:
    name: str | None
    client_token: str | None
    members: list[Member] | None
    owner: Member | None
    archive_tasklist: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InputTasklistBuilder: ...

class InputTasklistBuilder:
    def __init__(self) -> None: ...
    def name(self, name: str) -> InputTasklistBuilder: ...
    def client_token(self, client_token: str) -> InputTasklistBuilder: ...
    def members(self, members: list[Member]) -> InputTasklistBuilder: ...
    def owner(self, owner: Member) -> InputTasklistBuilder: ...
    def archive_tasklist(self, archive_tasklist: bool) -> InputTasklistBuilder: ...
    def build(self) -> InputTasklist: ...
