from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListTasklistActivitySubscriptionRequest(BaseRequest):
    limit: int | None
    user_id_type: str | None
    tasklist_guid: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListTasklistActivitySubscriptionRequestBuilder: ...

class ListTasklistActivitySubscriptionRequestBuilder:
    def __init__(self) -> None: ...
    def limit(self, limit: int) -> ListTasklistActivitySubscriptionRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> ListTasklistActivitySubscriptionRequestBuilder: ...
    def tasklist_guid(self, tasklist_guid: str) -> ListTasklistActivitySubscriptionRequestBuilder: ...
    def build(self) -> ListTasklistActivitySubscriptionRequest: ...
