from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListSectionRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    resource_type: str | None
    resource_id: str | None
    user_id_type: str | None
    update_msec: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListSectionRequestBuilder: ...

class ListSectionRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> ListSectionRequestBuilder: ...
    def page_token(self, page_token: str) -> ListSectionRequestBuilder: ...
    def resource_type(self, resource_type: str) -> ListSectionRequestBuilder: ...
    def resource_id(self, resource_id: str) -> ListSectionRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> ListSectionRequestBuilder: ...
    def update_msec(self, update_msec: str) -> ListSectionRequestBuilder: ...
    def build(self) -> ListSectionRequest: ...
