from lark_oapi.core.construct import init as init

class ListTasklistActivitySubscriptionRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListTasklistActivitySubscriptionRequestBodyBuilder: ...

class ListTasklistActivitySubscriptionRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListTasklistActivitySubscriptionRequestBody: ...
