from .task import Task as Task
from lark_oapi.core.construct import init as init

class ListTaskSubtaskResponseBody:
    items: list[Task] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListTaskSubtaskResponseBodyBuilder: ...

class ListTaskSubtaskResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[Task]) -> ListTaskSubtaskResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListTaskSubtaskResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListTaskSubtaskResponseBodyBuilder: ...
    def build(self) -> ListTaskSubtaskResponseBody: ...
