from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListTaskSubtaskRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    user_id_type: str | None
    task_guid: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListTaskSubtaskRequestBuilder: ...

class ListTaskSubtaskRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> ListTaskSubtaskRequestBuilder: ...
    def page_token(self, page_token: str) -> ListTaskSubtaskRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> ListTaskSubtaskRequestBuilder: ...
    def task_guid(self, task_guid: str) -> ListTaskSubtaskRequestBuilder: ...
    def build(self) -> ListTaskSubtaskRequest: ...
