from lark_oapi.core.construct import init as init

class ListCustomFieldRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListCustomFieldRequestBodyBuilder: ...

class ListCustomFieldRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListCustomFieldRequestBody: ...
