from .section_summary import SectionSummary as SectionSummary
from lark_oapi.core.construct import init as init

class ListSectionResponseBody:
    items: list[SectionSummary] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListSectionResponseBodyBuilder: ...

class ListSectionResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[SectionSummary]) -> ListSectionResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListSectionResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListSectionResponseBodyBuilder: ...
    def build(self) -> ListSectionResponseBody: ...
