from .attachment import Attachment as Attachment
from lark_oapi.core.construct import init as init

class ListAttachmentResponseBody:
    items: list[Attachment] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListAttachmentResponseBodyBuilder: ...

class ListAttachmentResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[Attachment]) -> ListAttachmentResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListAttachmentResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListAttachmentResponseBodyBuilder: ...
    def build(self) -> ListAttachmentResponseBody: ...
