from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListTaskRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    completed: bool | None
    type: str | None
    user_id_type: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListTaskRequestBuilder: ...

class ListTaskRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> ListTaskRequestBuilder: ...
    def page_token(self, page_token: str) -> ListTaskRequestBuilder: ...
    def completed(self, completed: bool) -> ListTaskRequestBuilder: ...
    def type(self, type: str) -> ListTaskRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> ListTaskRequestBuilder: ...
    def build(self) -> ListTaskRequest: ...
