from lark_oapi.core.construct import init as init

class MemberSetting:
    multi: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MemberSettingBuilder: ...

class MemberSettingBuilder:
    def __init__(self) -> None: ...
    def multi(self, multi: bool) -> MemberSettingBuilder: ...
    def build(self) -> MemberSetting: ...
