from lark_oapi.core.construct import init as init

class Option:
    guid: str | None
    name: str | None
    color_index: int | None
    is_hidden: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OptionBuilder: ...

class OptionBuilder:
    def __init__(self) -> None: ...
    def guid(self, guid: str) -> OptionBuilder: ...
    def name(self, name: str) -> OptionBuilder: ...
    def color_index(self, color_index: int) -> OptionBuilder: ...
    def is_hidden(self, is_hidden: bool) -> OptionBuilder: ...
    def build(self) -> Option: ...
