from .tasklist_activity_subscription import TasklistActivitySubscription as TasklistActivitySubscription
from lark_oapi.core.construct import init as init

class PatchTasklistActivitySubscriptionRequestBody:
    activity_subscription: TasklistActivitySubscription | None
    update_fields: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchTasklistActivitySubscriptionRequestBodyBuilder: ...

class PatchTasklistActivitySubscriptionRequestBodyBuilder:
    def __init__(self) -> None: ...
    def activity_subscription(self, activity_subscription: TasklistActivitySubscription) -> PatchTasklistActivitySubscriptionRequestBodyBuilder: ...
    def update_fields(self, update_fields: list[str]) -> PatchTasklistActivitySubscriptionRequestBodyBuilder: ...
    def build(self) -> PatchTasklistActivitySubscriptionRequestBody: ...
