from .input_task import InputTask as InputTask
from lark_oapi.core.construct import init as init

class PatchTaskRequestBody:
    task: InputTask | None
    update_fields: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchTaskRequestBodyBuilder: ...

class PatchTaskRequestBodyBuilder:
    def __init__(self) -> None: ...
    def task(self, task: InputTask) -> PatchTaskRequestBodyBuilder: ...
    def update_fields(self, update_fields: list[str]) -> PatchTaskRequestBodyBuilder: ...
    def build(self) -> PatchTaskRequestBody: ...
