from .section import Section as Section
from lark_oapi.core.construct import init as init

class PatchSectionResponseBody:
    section: Section | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchSectionResponseBodyBuilder: ...

class PatchSectionResponseBodyBuilder:
    def __init__(self) -> None: ...
    def section(self, section: Section) -> PatchSectionResponseBodyBuilder: ...
    def build(self) -> PatchSectionResponseBody: ...
