from .tasklist import Tasklist as Tasklist
from lark_oapi.core.construct import init as init

class RemoveMembersTasklistResponseBody:
    tasklist: Tasklist | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RemoveMembersTasklistResponseBodyBuilder: ...

class RemoveMembersTasklistResponseBodyBuilder:
    def __init__(self) -> None: ...
    def tasklist(self, tasklist: Tasklist) -> RemoveMembersTasklistResponseBodyBuilder: ...
    def build(self) -> RemoveMembersTasklistResponseBody: ...
