from lark_oapi.core.construct import init as init

class RemoveCustomFieldRequestBody:
    resource_type: str | None
    resource_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RemoveCustomFieldRequestBodyBuilder: ...

class RemoveCustomFieldRequestBodyBuilder:
    def __init__(self) -> None: ...
    def resource_type(self, resource_type: str) -> RemoveCustomFieldRequestBodyBuilder: ...
    def resource_id(self, resource_id: str) -> RemoveCustomFieldRequestBodyBuilder: ...
    def build(self) -> RemoveCustomFieldRequestBody: ...
