from .remove_tasklist_task_request_body import RemoveTasklistTaskRequestBody as RemoveTasklistTaskRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class RemoveTasklistTaskRequest(BaseRequest):
    user_id_type: str | None
    task_guid: str | None
    request_body: RemoveTasklistTaskRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> RemoveTasklistTaskRequestBuilder: ...

class RemoveTasklistTaskRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> RemoveTasklistTaskRequestBuilder: ...
    def task_guid(self, task_guid: str) -> RemoveTasklistTaskRequestBuilder: ...
    def request_body(self, request_body: RemoveTasklistTaskRequestBody) -> RemoveTasklistTaskRequestBuilder: ...
    def build(self) -> RemoveTasklistTaskRequest: ...
