from .remove_custom_field_request_body import RemoveCustomFieldRequestBody as RemoveCustomFieldRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class RemoveCustomFieldRequest(BaseRequest):
    custom_field_guid: str | None
    request_body: RemoveCustomFieldRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> RemoveCustomFieldRequestBuilder: ...

class RemoveCustomFieldRequestBuilder:
    def __init__(self) -> None: ...
    def custom_field_guid(self, custom_field_guid: str) -> RemoveCustomFieldRequestBuilder: ...
    def request_body(self, request_body: RemoveCustomFieldRequestBody) -> RemoveCustomFieldRequestBuilder: ...
    def build(self) -> RemoveCustomFieldRequest: ...
