from lark_oapi.core.construct import init as init

class RemoveRemindersTaskRequestBody:
    reminder_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RemoveRemindersTaskRequestBodyBuilder: ...

class RemoveRemindersTaskRequestBodyBuilder:
    def __init__(self) -> None: ...
    def reminder_ids(self, reminder_ids: list[str]) -> RemoveRemindersTaskRequestBodyBuilder: ...
    def build(self) -> RemoveRemindersTaskRequestBody: ...
