from .member import Member as Member
from lark_oapi.core.construct import init as init

class RemoveMembersTasklistRequestBody:
    members: list[Member] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RemoveMembersTasklistRequestBodyBuilder: ...

class RemoveMembersTasklistRequestBodyBuilder:
    def __init__(self) -> None: ...
    def members(self, members: list[Member]) -> RemoveMembersTasklistRequestBodyBuilder: ...
    def build(self) -> RemoveMembersTasklistRequestBody: ...
