from .remove_members_tasklist_request_body import RemoveMembersTasklistRequestBody as RemoveMembersTasklistRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class RemoveMembersTasklistRequest(BaseRequest):
    user_id_type: str | None
    tasklist_guid: str | None
    request_body: RemoveMembersTasklistRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> RemoveMembersTasklistRequestBuilder: ...

class RemoveMembersTasklistRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> RemoveMembersTasklistRequestBuilder: ...
    def tasklist_guid(self, tasklist_guid: str) -> RemoveMembersTasklistRequestBuilder: ...
    def request_body(self, request_body: RemoveMembersTasklistRequestBody) -> RemoveMembersTasklistRequestBuilder: ...
    def build(self) -> RemoveMembersTasklistRequest: ...
