from .member import Member as Member
from .tasklist_summary import TasklistSummary as TasklistSummary
from lark_oapi.core.construct import init as init

class Section:
    guid: str | None
    name: str | None
    resource_type: str | None
    is_default: bool | None
    creator: Member | None
    tasklist: TasklistSummary | None
    created_at: int | None
    updated_at: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SectionBuilder: ...

class SectionBuilder:
    def __init__(self) -> None: ...
    def guid(self, guid: str) -> SectionBuilder: ...
    def name(self, name: str) -> SectionBuilder: ...
    def resource_type(self, resource_type: str) -> SectionBuilder: ...
    def is_default(self, is_default: bool) -> SectionBuilder: ...
    def creator(self, creator: Member) -> SectionBuilder: ...
    def tasklist(self, tasklist: TasklistSummary) -> SectionBuilder: ...
    def created_at(self, created_at: int) -> SectionBuilder: ...
    def updated_at(self, updated_at: int) -> SectionBuilder: ...
    def build(self) -> Section: ...
