from .option import Option as Option
from lark_oapi.core.construct import init as init

class SelectSetting:
    options: list[Option] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SelectSettingBuilder: ...

class SelectSettingBuilder:
    def __init__(self) -> None: ...
    def options(self, options: list[Option]) -> SelectSettingBuilder: ...
    def build(self) -> SelectSetting: ...
