from lark_oapi.core.construct import init as init

class TasksSectionRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TasksSectionRequestBodyBuilder: ...

class TasksSectionRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> TasksSectionRequestBody: ...
