from .member import Member as Member
from lark_oapi.core.construct import init as init

class TasklistActivitySubscription:
    guid: str | None
    name: str | None
    subscribers: list[Member] | None
    include_keys: list[int] | None
    disabled: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TasklistActivitySubscriptionBuilder: ...

class TasklistActivitySubscriptionBuilder:
    def __init__(self) -> None: ...
    def guid(self, guid: str) -> TasklistActivitySubscriptionBuilder: ...
    def name(self, name: str) -> TasklistActivitySubscriptionBuilder: ...
    def subscribers(self, subscribers: list[Member]) -> TasklistActivitySubscriptionBuilder: ...
    def include_keys(self, include_keys: list[int]) -> TasklistActivitySubscriptionBuilder: ...
    def disabled(self, disabled: bool) -> TasklistActivitySubscriptionBuilder: ...
    def build(self) -> TasklistActivitySubscription: ...
