from lark_oapi.core.construct import init as init

class TasksTasklistRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TasksTasklistRequestBodyBuilder: ...

class TasksTasklistRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> TasksTasklistRequestBody: ...
