from lark_oapi.core.construct import init as init

class TaskAssignee:
    id: str | None
    completed_at: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TaskAssigneeBuilder: ...

class TaskAssigneeBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> TaskAssigneeBuilder: ...
    def completed_at(self, completed_at: int) -> TaskAssigneeBuilder: ...
    def build(self) -> TaskAssignee: ...
