from lark_oapi.core.construct import init as init

class TaskStatistics:
    total_tasks_count: int | None
    total_completed_tasks_count: int | None
    total_uncompleted_tasks_count: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TaskStatisticsBuilder: ...

class TaskStatisticsBuilder:
    def __init__(self) -> None: ...
    def total_tasks_count(self, total_tasks_count: int) -> TaskStatisticsBuilder: ...
    def total_completed_tasks_count(self, total_completed_tasks_count: int) -> TaskStatisticsBuilder: ...
    def total_uncompleted_tasks_count(self, total_uncompleted_tasks_count: int) -> TaskStatisticsBuilder: ...
    def build(self) -> TaskStatistics: ...
