from .task_summary import TaskSummary as TaskSummary
from lark_oapi.core.construct import init as init

class TasksTasklistResponseBody:
    items: list[TaskSummary] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TasksTasklistResponseBodyBuilder: ...

class TasksTasklistResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[TaskSummary]) -> TasksTasklistResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> TasksTasklistResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> TasksTasklistResponseBodyBuilder: ...
    def build(self) -> TasksTasklistResponseBody: ...
