from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class TasksSectionRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    completed: bool | None
    created_from: int | None
    created_to: int | None
    user_id_type: str | None
    section_guid: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> TasksSectionRequestBuilder: ...

class TasksSectionRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> TasksSectionRequestBuilder: ...
    def page_token(self, page_token: str) -> TasksSectionRequestBuilder: ...
    def completed(self, completed: bool) -> TasksSectionRequestBuilder: ...
    def created_from(self, created_from: int) -> TasksSectionRequestBuilder: ...
    def created_to(self, created_to: int) -> TasksSectionRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> TasksSectionRequestBuilder: ...
    def section_guid(self, section_guid: str) -> TasksSectionRequestBuilder: ...
    def build(self) -> TasksSectionRequest: ...
