from .task_summary import TaskSummary as TaskSummary
from lark_oapi.core.construct import init as init

class TasksSectionResponseBody:
    items: list[TaskSummary] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TasksSectionResponseBodyBuilder: ...

class TasksSectionResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[TaskSummary]) -> TasksSectionResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> TasksSectionResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> TasksSectionResponseBodyBuilder: ...
    def build(self) -> TasksSectionResponseBody: ...
