from lark_oapi.core.construct import init as init

class AddManagersChatManagersRequestBody:
    manager_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AddManagersChatManagersRequestBodyBuilder: ...

class AddManagersChatManagersRequestBodyBuilder:
    def __init__(self) -> None: ...
    def manager_ids(self, manager_ids: list[str]) -> AddManagersChatManagersRequestBodyBuilder: ...
    def build(self) -> AddManagersChatManagersRequestBody: ...
