from .add_managers_chat_managers_request_body import AddManagersChatManagersRequestBody as AddManagersChatManagersRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class AddManagersChatManagersRequest(BaseRequest):
    member_id_type: str | None
    chat_id: str | None
    request_body: AddManagersChatManagersRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> AddManagersChatManagersRequestBuilder: ...

class AddManagersChatManagersRequestBuilder:
    def __init__(self) -> None: ...
    def member_id_type(self, member_id_type: str) -> AddManagersChatManagersRequestBuilder: ...
    def chat_id(self, chat_id: str) -> AddManagersChatManagersRequestBuilder: ...
    def request_body(self, request_body: AddManagersChatManagersRequestBody) -> AddManagersChatManagersRequestBuilder: ...
    def build(self) -> AddManagersChatManagersRequest: ...
