from lark_oapi.core.construct import init as init

class BatchMessageSendProgress:
    valid_user_ids_count: int | None
    success_user_ids_count: int | None
    read_user_ids_count: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchMessageSendProgressBuilder: ...

class BatchMessageSendProgressBuilder:
    def __init__(self) -> None: ...
    def valid_user_ids_count(self, valid_user_ids_count: int) -> BatchMessageSendProgressBuilder: ...
    def success_user_ids_count(self, success_user_ids_count: int) -> BatchMessageSendProgressBuilder: ...
    def read_user_ids_count(self, read_user_ids_count: int) -> BatchMessageSendProgressBuilder: ...
    def build(self) -> BatchMessageSendProgress: ...
