from .batch_recall_progress import BatchRecallProgress as BatchRecallProgress
from .batch_send_progress import BatchSendProgress as BatchSendProgress
from lark_oapi.core.construct import init as init

class BatchMessage:
    batch_message_id: str | None
    batch_send_progress: BatchSendProgress | None
    batch_recall_progress: BatchRecallProgress | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchMessageBuilder: ...

class BatchMessageBuilder:
    def __init__(self) -> None: ...
    def batch_message_id(self, batch_message_id: str) -> BatchMessageBuilder: ...
    def batch_send_progress(self, batch_send_progress: BatchSendProgress) -> BatchMessageBuilder: ...
    def batch_recall_progress(self, batch_recall_progress: BatchRecallProgress) -> BatchMessageBuilder: ...
    def build(self) -> BatchMessage: ...
