from lark_oapi.core.construct import init as init

class BatchMessageRecallProgress:
    recall: bool | None
    recall_count: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchMessageRecallProgressBuilder: ...

class BatchMessageRecallProgressBuilder:
    def __init__(self) -> None: ...
    def recall(self, recall: bool) -> BatchMessageRecallProgressBuilder: ...
    def recall_count(self, recall_count: int) -> BatchMessageRecallProgressBuilder: ...
    def build(self) -> BatchMessageRecallProgress: ...
