from .chat_menu_item import ChatMenuItem as ChatMenuItem
from .chat_menu_second_level import ChatMenuSecondLevel as ChatMenuSecondLevel
from lark_oapi.core.construct import init as init

class ChatMenuTopLevel:
    chat_menu_top_level_id: int | None
    chat_menu_item: ChatMenuItem | None
    children: list[ChatMenuSecondLevel] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ChatMenuTopLevelBuilder: ...

class ChatMenuTopLevelBuilder:
    def __init__(self) -> None: ...
    def chat_menu_top_level_id(self, chat_menu_top_level_id: int) -> ChatMenuTopLevelBuilder: ...
    def chat_menu_item(self, chat_menu_item: ChatMenuItem) -> ChatMenuTopLevelBuilder: ...
    def children(self, children: list[ChatMenuSecondLevel]) -> ChatMenuTopLevelBuilder: ...
    def build(self) -> ChatMenuTopLevel: ...
