from lark_oapi.core.construct import init as init

class ChatMember:
    user_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ChatMemberBuilder: ...

class ChatMemberBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: str) -> ChatMemberBuilder: ...
    def build(self) -> ChatMember: ...
