from lark_oapi.core.construct import init as init

class ChatMemberBot:
    bot_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ChatMemberBotBuilder: ...

class ChatMemberBotBuilder:
    def __init__(self) -> None: ...
    def bot_id(self, bot_id: str) -> ChatMemberBotBuilder: ...
    def build(self) -> ChatMemberBot: ...
