from .chat_menu_item import ChatMenuItem as ChatMenuItem
from lark_oapi.core.construct import init as init

class ChatMenuSecondLevel:
    chat_menu_second_level_id: int | None
    chat_menu_item: ChatMenuItem | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ChatMenuSecondLevelBuilder: ...

class ChatMenuSecondLevelBuilder:
    def __init__(self) -> None: ...
    def chat_menu_second_level_id(self, chat_menu_second_level_id: int) -> ChatMenuSecondLevelBuilder: ...
    def chat_menu_item(self, chat_menu_item: ChatMenuItem) -> ChatMenuSecondLevelBuilder: ...
    def build(self) -> ChatMenuSecondLevel: ...
