from lark_oapi.core.construct import init as init

class Crc32Item:
    part_id: str | None
    crc32: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> Crc32ItemBuilder: ...

class Crc32ItemBuilder:
    def __init__(self) -> None: ...
    def part_id(self, part_id: str) -> Crc32ItemBuilder: ...
    def crc32(self, crc32: str) -> Crc32ItemBuilder: ...
    def build(self) -> Crc32Item: ...
