from lark_oapi.core.construct import init as init

class CreateChatMembersRequestBody:
    id_list: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateChatMembersRequestBodyBuilder: ...

class CreateChatMembersRequestBodyBuilder:
    def __init__(self) -> None: ...
    def id_list(self, id_list: list[str]) -> CreateChatMembersRequestBodyBuilder: ...
    def build(self) -> CreateChatMembersRequestBody: ...
