from .create_pin_request_body import CreatePinRequestBody as CreatePinRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreatePinRequest(BaseRequest):
    request_body: CreatePinRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreatePinRequestBuilder: ...

class CreatePinRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: CreatePinRequestBody) -> CreatePinRequestBuilder: ...
    def build(self) -> CreatePinRequest: ...
