from .create_message_request_body import CreateMessageRequestBody as CreateMessageRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateMessageRequest(BaseRequest):
    receive_id_type: str | None
    request_body: CreateMessageRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateMessageRequestBuilder: ...

class CreateMessageRequestBuilder:
    def __init__(self) -> None: ...
    def receive_id_type(self, receive_id_type: str) -> CreateMessageRequestBuilder: ...
    def request_body(self, request_body: CreateMessageRequestBody) -> CreateMessageRequestBuilder: ...
    def build(self) -> CreateMessageRequest: ...
