from .create_file_request_body import CreateFileRequestBody as CreateFileRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateFileRequest(BaseRequest):
    request_body: CreateFileRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateFileRequestBuilder: ...

class CreateFileRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: CreateFileRequestBody) -> CreateFileRequestBuilder: ...
    def build(self) -> CreateFileRequest: ...
