from lark_oapi.core.construct import init as init

class CreatePinRequestBody:
    message_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreatePinRequestBodyBuilder: ...

class CreatePinRequestBodyBuilder:
    def __init__(self) -> None: ...
    def message_id(self, message_id: str) -> CreatePinRequestBodyBuilder: ...
    def build(self) -> CreatePinRequestBody: ...
