from lark_oapi.core.construct import init as init

class CreateMessageRequestBody:
    receive_id: str | None
    msg_type: str | None
    content: str | None
    uuid: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateMessageRequestBodyBuilder: ...

class CreateMessageRequestBodyBuilder:
    def __init__(self) -> None: ...
    def receive_id(self, receive_id: str) -> CreateMessageRequestBodyBuilder: ...
    def msg_type(self, msg_type: str) -> CreateMessageRequestBodyBuilder: ...
    def content(self, content: str) -> CreateMessageRequestBodyBuilder: ...
    def uuid(self, uuid: str) -> CreateMessageRequestBodyBuilder: ...
    def build(self) -> CreateMessageRequestBody: ...
