from .chat_menu_tree import ChatMenuTree as ChatMenuTree
from lark_oapi.core.construct import init as init

class CreateChatMenuTreeResponseBody:
    menu_tree: ChatMenuTree | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateChatMenuTreeResponseBodyBuilder: ...

class CreateChatMenuTreeResponseBodyBuilder:
    def __init__(self) -> None: ...
    def menu_tree(self, menu_tree: ChatMenuTree) -> CreateChatMenuTreeResponseBodyBuilder: ...
    def build(self) -> CreateChatMenuTreeResponseBody: ...
