from lark_oapi.core.construct import init as init

class DeleteChatResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteChatResponseBodyBuilder: ...

class DeleteChatResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteChatResponseBody: ...
