from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteChatRequest(BaseRequest):
    chat_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteChatRequestBuilder: ...

class DeleteChatRequestBuilder:
    def __init__(self) -> None: ...
    def chat_id(self, chat_id: str) -> DeleteChatRequestBuilder: ...
    def build(self) -> DeleteChatRequest: ...
