from .delete_chat_members_request_body import DeleteChatMembersRequestBody as DeleteChatMembersRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteChatMembersRequest(BaseRequest):
    member_id_type: str | None
    chat_id: str | None
    request_body: DeleteChatMembersRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteChatMembersRequestBuilder: ...

class DeleteChatMembersRequestBuilder:
    def __init__(self) -> None: ...
    def member_id_type(self, member_id_type: str) -> DeleteChatMembersRequestBuilder: ...
    def chat_id(self, chat_id: str) -> DeleteChatMembersRequestBuilder: ...
    def request_body(self, request_body: DeleteChatMembersRequestBody) -> DeleteChatMembersRequestBuilder: ...
    def build(self) -> DeleteChatMembersRequest: ...
