from lark_oapi.core.construct import init as init

class DeleteTopNoticeChatTopNoticeRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteTopNoticeChatTopNoticeRequestBodyBuilder: ...

class DeleteTopNoticeChatTopNoticeRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteTopNoticeChatTopNoticeRequestBody: ...
