from lark_oapi.core.construct import init as init

class DeleteTabsChatTabRequestBody:
    tab_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteTabsChatTabRequestBodyBuilder: ...

class DeleteTabsChatTabRequestBodyBuilder:
    def __init__(self) -> None: ...
    def tab_ids(self, tab_ids: list[str]) -> DeleteTabsChatTabRequestBodyBuilder: ...
    def build(self) -> DeleteTabsChatTabRequestBody: ...
