from .delete_managers_chat_managers_request_body import DeleteManagersChatManagersRequestBody as DeleteManagersChatManagersRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteManagersChatManagersRequest(BaseRequest):
    member_id_type: str | None
    chat_id: str | None
    request_body: DeleteManagersChatManagersRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteManagersChatManagersRequestBuilder: ...

class DeleteManagersChatManagersRequestBuilder:
    def __init__(self) -> None: ...
    def member_id_type(self, member_id_type: str) -> DeleteManagersChatManagersRequestBuilder: ...
    def chat_id(self, chat_id: str) -> DeleteManagersChatManagersRequestBuilder: ...
    def request_body(self, request_body: DeleteManagersChatManagersRequestBody) -> DeleteManagersChatManagersRequestBuilder: ...
    def build(self) -> DeleteManagersChatManagersRequest: ...
