from lark_oapi.core.construct import init as init

class DeleteMessageRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteMessageRequestBodyBuilder: ...

class DeleteMessageRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteMessageRequestBody: ...
