from lark_oapi.core.construct import init as init

class DeleteMessageResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteMessageResponseBodyBuilder: ...

class DeleteMessageResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteMessageResponseBody: ...
