from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteMessageRequest(BaseRequest):
    message_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteMessageRequestBuilder: ...

class DeleteMessageRequestBuilder:
    def __init__(self) -> None: ...
    def message_id(self, message_id: str) -> DeleteMessageRequestBuilder: ...
    def build(self) -> DeleteMessageRequest: ...
