from lark_oapi.core.construct import init as init

class DeleteChatMenuTreeRequestBody:
    chat_menu_top_level_ids: list[int] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteChatMenuTreeRequestBodyBuilder: ...

class DeleteChatMenuTreeRequestBodyBuilder:
    def __init__(self) -> None: ...
    def chat_menu_top_level_ids(self, chat_menu_top_level_ids: list[int]) -> DeleteChatMenuTreeRequestBodyBuilder: ...
    def build(self) -> DeleteChatMenuTreeRequestBody: ...
