from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteTopNoticeChatTopNoticeRequest(BaseRequest):
    chat_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteTopNoticeChatTopNoticeRequestBuilder: ...

class DeleteTopNoticeChatTopNoticeRequestBuilder:
    def __init__(self) -> None: ...
    def chat_id(self, chat_id: str) -> DeleteTopNoticeChatTopNoticeRequestBuilder: ...
    def build(self) -> DeleteTopNoticeChatTopNoticeRequest: ...
