from .delete_chat_menu_tree_request_body import DeleteChatMenuTreeRequestBody as DeleteChatMenuTreeRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteChatMenuTreeRequest(BaseRequest):
    chat_id: str | None
    request_body: DeleteChatMenuTreeRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteChatMenuTreeRequestBuilder: ...

class DeleteChatMenuTreeRequestBuilder:
    def __init__(self) -> None: ...
    def chat_id(self, chat_id: str) -> DeleteChatMenuTreeRequestBuilder: ...
    def request_body(self, request_body: DeleteChatMenuTreeRequestBody) -> DeleteChatMenuTreeRequestBuilder: ...
    def build(self) -> DeleteChatMenuTreeRequest: ...
