from .user_id import UserId as UserId
from lark_oapi.core.construct import init as init

class EventMessageReader:
    reader_id: UserId | None
    read_time: str | None
    tenant_key: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EventMessageReaderBuilder: ...

class EventMessageReaderBuilder:
    def __init__(self) -> None: ...
    def reader_id(self, reader_id: UserId) -> EventMessageReaderBuilder: ...
    def read_time(self, read_time: str) -> EventMessageReaderBuilder: ...
    def tenant_key(self, tenant_key: str) -> EventMessageReaderBuilder: ...
    def build(self) -> EventMessageReader: ...
