from .forward_thread_request_body import ForwardThreadRequestBody as ForwardThreadRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ForwardThreadRequest(BaseRequest):
    receive_id_type: str | None
    uuid: str | None
    thread_id: str | None
    request_body: ForwardThreadRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ForwardThreadRequestBuilder: ...

class ForwardThreadRequestBuilder:
    def __init__(self) -> None: ...
    def receive_id_type(self, receive_id_type: str) -> ForwardThreadRequestBuilder: ...
    def uuid(self, uuid: str) -> ForwardThreadRequestBuilder: ...
    def thread_id(self, thread_id: str) -> ForwardThreadRequestBuilder: ...
    def request_body(self, request_body: ForwardThreadRequestBody) -> ForwardThreadRequestBuilder: ...
    def build(self) -> ForwardThreadRequest: ...
