from lark_oapi.core.construct import init as init

class ForwardMessageRequestBody:
    receive_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ForwardMessageRequestBodyBuilder: ...

class ForwardMessageRequestBodyBuilder:
    def __init__(self) -> None: ...
    def receive_id(self, receive_id: str) -> ForwardMessageRequestBodyBuilder: ...
    def build(self) -> ForwardMessageRequestBody: ...
