from .mention import Mention as Mention
from .message_body import MessageBody as MessageBody
from .sender import Sender as Sender
from lark_oapi.core.construct import init as init

class ForwardMessageResponseBody:
    message_id: str | None
    root_id: str | None
    parent_id: str | None
    thread_id: str | None
    msg_type: str | None
    create_time: int | None
    update_time: int | None
    deleted: bool | None
    updated: bool | None
    chat_id: str | None
    sender: Sender | None
    body: MessageBody | None
    mentions: list[Mention] | None
    upper_message_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ForwardMessageResponseBodyBuilder: ...

class ForwardMessageResponseBodyBuilder:
    def __init__(self) -> None: ...
    def message_id(self, message_id: str) -> ForwardMessageResponseBodyBuilder: ...
    def root_id(self, root_id: str) -> ForwardMessageResponseBodyBuilder: ...
    def parent_id(self, parent_id: str) -> ForwardMessageResponseBodyBuilder: ...
    def thread_id(self, thread_id: str) -> ForwardMessageResponseBodyBuilder: ...
    def msg_type(self, msg_type: str) -> ForwardMessageResponseBodyBuilder: ...
    def create_time(self, create_time: int) -> ForwardMessageResponseBodyBuilder: ...
    def update_time(self, update_time: int) -> ForwardMessageResponseBodyBuilder: ...
    def deleted(self, deleted: bool) -> ForwardMessageResponseBodyBuilder: ...
    def updated(self, updated: bool) -> ForwardMessageResponseBodyBuilder: ...
    def chat_id(self, chat_id: str) -> ForwardMessageResponseBodyBuilder: ...
    def sender(self, sender: Sender) -> ForwardMessageResponseBodyBuilder: ...
    def body(self, body: MessageBody) -> ForwardMessageResponseBodyBuilder: ...
    def mentions(self, mentions: list[Mention]) -> ForwardMessageResponseBodyBuilder: ...
    def upper_message_id(self, upper_message_id: str) -> ForwardMessageResponseBodyBuilder: ...
    def build(self) -> ForwardMessageResponseBody: ...
