from .forward_message_request_body import ForwardMessageRequestBody as ForwardMessageRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ForwardMessageRequest(BaseRequest):
    receive_id_type: str | None
    uuid: str | None
    message_id: str | None
    request_body: ForwardMessageRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ForwardMessageRequestBuilder: ...

class ForwardMessageRequestBuilder:
    def __init__(self) -> None: ...
    def receive_id_type(self, receive_id_type: str) -> ForwardMessageRequestBuilder: ...
    def uuid(self, uuid: str) -> ForwardMessageRequestBuilder: ...
    def message_id(self, message_id: str) -> ForwardMessageRequestBuilder: ...
    def request_body(self, request_body: ForwardMessageRequestBody) -> ForwardMessageRequestBuilder: ...
    def build(self) -> ForwardMessageRequest: ...
