from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetChatRequest(BaseRequest):
    user_id_type: str | None
    chat_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetChatRequestBuilder: ...

class GetChatRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> GetChatRequestBuilder: ...
    def chat_id(self, chat_id: str) -> GetChatRequestBuilder: ...
    def build(self) -> GetChatRequest: ...
