from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetChatMenuTreeRequest(BaseRequest):
    chat_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetChatMenuTreeRequestBuilder: ...

class GetChatMenuTreeRequestBuilder:
    def __init__(self) -> None: ...
    def chat_id(self, chat_id: str) -> GetChatMenuTreeRequestBuilder: ...
    def build(self) -> GetChatMenuTreeRequest: ...
