from .list_moderator import ListModerator as ListModerator
from lark_oapi.core.construct import init as init

class GetChatModerationResponseBody:
    moderation_setting: str | None
    page_token: str | None
    has_more: bool | None
    items: list[ListModerator] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetChatModerationResponseBodyBuilder: ...

class GetChatModerationResponseBodyBuilder:
    def __init__(self) -> None: ...
    def moderation_setting(self, moderation_setting: str) -> GetChatModerationResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> GetChatModerationResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> GetChatModerationResponseBodyBuilder: ...
    def items(self, items: list[ListModerator]) -> GetChatModerationResponseBodyBuilder: ...
    def build(self) -> GetChatModerationResponseBody: ...
