from .batch_message_recall_progress import BatchMessageRecallProgress as BatchMessageRecallProgress
from .batch_message_send_progress import BatchMessageSendProgress as BatchMessageSendProgress
from lark_oapi.core.construct import init as init

class GetProgressBatchMessageResponseBody:
    batch_message_send_progress: BatchMessageSendProgress | None
    batch_message_recall_progress: BatchMessageRecallProgress | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetProgressBatchMessageResponseBodyBuilder: ...

class GetProgressBatchMessageResponseBodyBuilder:
    def __init__(self) -> None: ...
    def batch_message_send_progress(self, batch_message_send_progress: BatchMessageSendProgress) -> GetProgressBatchMessageResponseBodyBuilder: ...
    def batch_message_recall_progress(self, batch_message_recall_progress: BatchMessageRecallProgress) -> GetProgressBatchMessageResponseBodyBuilder: ...
    def build(self) -> GetProgressBatchMessageResponseBody: ...
