from lark_oapi.core.construct import init as init

class GetImageResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetImageResponseBodyBuilder: ...

class GetImageResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetImageResponseBody: ...
