from .message import Message as Message
from lark_oapi.core.construct import init as init

class GetMessageResponseBody:
    items: list[Message] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetMessageResponseBodyBuilder: ...

class GetMessageResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[Message]) -> GetMessageResponseBodyBuilder: ...
    def build(self) -> GetMessageResponseBody: ...
