from lark_oapi.core.construct import init as init

class GetMessageResourceRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetMessageResourceRequestBodyBuilder: ...

class GetMessageResourceRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetMessageResourceRequestBody: ...
