from lark_oapi.core.construct import init as init

class GetChatAnnouncementRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetChatAnnouncementRequestBodyBuilder: ...

class GetChatAnnouncementRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetChatAnnouncementRequestBody: ...
