from lark_oapi.core.construct import init as init

class GetChatAnnouncementResponseBody:
    content: str | None
    revision: str | None
    create_time: str | None
    update_time: str | None
    owner_id_type: str | None
    owner_id: str | None
    modifier_id_type: str | None
    modifier_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetChatAnnouncementResponseBodyBuilder: ...

class GetChatAnnouncementResponseBodyBuilder:
    def __init__(self) -> None: ...
    def content(self, content: str) -> GetChatAnnouncementResponseBodyBuilder: ...
    def revision(self, revision: str) -> GetChatAnnouncementResponseBodyBuilder: ...
    def create_time(self, create_time: str) -> GetChatAnnouncementResponseBodyBuilder: ...
    def update_time(self, update_time: str) -> GetChatAnnouncementResponseBodyBuilder: ...
    def owner_id_type(self, owner_id_type: str) -> GetChatAnnouncementResponseBodyBuilder: ...
    def owner_id(self, owner_id: str) -> GetChatAnnouncementResponseBodyBuilder: ...
    def modifier_id_type(self, modifier_id_type: str) -> GetChatAnnouncementResponseBodyBuilder: ...
    def modifier_id(self, modifier_id: str) -> GetChatAnnouncementResponseBodyBuilder: ...
    def build(self) -> GetChatAnnouncementResponseBody: ...
