from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetMessageRequest(BaseRequest):
    user_id_type: str | None
    message_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetMessageRequestBuilder: ...

class GetMessageRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> GetMessageRequestBuilder: ...
    def message_id(self, message_id: str) -> GetMessageRequestBuilder: ...
    def build(self) -> GetMessageRequest: ...
