from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetChatModerationRequest(BaseRequest):
    user_id_type: str | None
    page_size: int | None
    page_token: str | None
    chat_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetChatModerationRequestBuilder: ...

class GetChatModerationRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> GetChatModerationRequestBuilder: ...
    def page_size(self, page_size: int) -> GetChatModerationRequestBuilder: ...
    def page_token(self, page_token: str) -> GetChatModerationRequestBuilder: ...
    def chat_id(self, chat_id: str) -> GetChatModerationRequestBuilder: ...
    def build(self) -> GetChatModerationRequest: ...
