from lark_oapi.core.construct import init as init

class LinkChatRequestBody:
    validity_period: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LinkChatRequestBodyBuilder: ...

class LinkChatRequestBodyBuilder:
    def __init__(self) -> None: ...
    def validity_period(self, validity_period: str) -> LinkChatRequestBodyBuilder: ...
    def build(self) -> LinkChatRequestBody: ...
