from .link_chat_request_body import LinkChatRequestBody as LinkChatRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class LinkChatRequest(BaseRequest):
    chat_id: str | None
    request_body: LinkChatRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> LinkChatRequestBuilder: ...

class LinkChatRequestBuilder:
    def __init__(self) -> None: ...
    def chat_id(self, chat_id: str) -> LinkChatRequestBuilder: ...
    def request_body(self, request_body: LinkChatRequestBody) -> LinkChatRequestBuilder: ...
    def build(self) -> LinkChatRequest: ...
