from lark_oapi.core.construct import init as init

class ListChatRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListChatRequestBodyBuilder: ...

class ListChatRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListChatRequestBody: ...
