from .message_reaction import MessageReaction as MessageReaction
from lark_oapi.core.construct import init as init

class ListMessageReactionResponseBody:
    items: list[MessageReaction] | None
    has_more: bool | None
    page_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListMessageReactionResponseBodyBuilder: ...

class ListMessageReactionResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[MessageReaction]) -> ListMessageReactionResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListMessageReactionResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListMessageReactionResponseBodyBuilder: ...
    def build(self) -> ListMessageReactionResponseBody: ...
