from lark_oapi.core.construct import init as init

class ListMessageRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListMessageRequestBodyBuilder: ...

class ListMessageRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListMessageRequestBody: ...
