from .chat_tab import ChatTab as ChatTab
from lark_oapi.core.construct import init as init

class ListTabsChatTabResponseBody:
    chat_tabs: list[ChatTab] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListTabsChatTabResponseBodyBuilder: ...

class ListTabsChatTabResponseBodyBuilder:
    def __init__(self) -> None: ...
    def chat_tabs(self, chat_tabs: list[ChatTab]) -> ListTabsChatTabResponseBodyBuilder: ...
    def build(self) -> ListTabsChatTabResponseBody: ...
