from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListMessageRequest(BaseRequest):
    container_id_type: str | None
    container_id: str | None
    start_time: str | None
    end_time: str | None
    sort_type: str | None
    page_size: int | None
    page_token: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListMessageRequestBuilder: ...

class ListMessageRequestBuilder:
    def __init__(self) -> None: ...
    def container_id_type(self, container_id_type: str) -> ListMessageRequestBuilder: ...
    def container_id(self, container_id: str) -> ListMessageRequestBuilder: ...
    def start_time(self, start_time: str) -> ListMessageRequestBuilder: ...
    def end_time(self, end_time: str) -> ListMessageRequestBuilder: ...
    def sort_type(self, sort_type: str) -> ListMessageRequestBuilder: ...
    def page_size(self, page_size: int) -> ListMessageRequestBuilder: ...
    def page_token(self, page_token: str) -> ListMessageRequestBuilder: ...
    def build(self) -> ListMessageRequest: ...
