from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListPinRequest(BaseRequest):
    chat_id: str | None
    start_time: str | None
    end_time: str | None
    page_size: int | None
    page_token: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListPinRequestBuilder: ...

class ListPinRequestBuilder:
    def __init__(self) -> None: ...
    def chat_id(self, chat_id: str) -> ListPinRequestBuilder: ...
    def start_time(self, start_time: str) -> ListPinRequestBuilder: ...
    def end_time(self, end_time: str) -> ListPinRequestBuilder: ...
    def page_size(self, page_size: int) -> ListPinRequestBuilder: ...
    def page_token(self, page_token: str) -> ListPinRequestBuilder: ...
    def build(self) -> ListPinRequest: ...
