from typing import *
from .special_focus import SpecialFocus as SpecialFocus
from lark_oapi.core.construct import init as init

class ListSpecialFocusResponseBody:
    items: Optional[List[SpecialFocus]]
    page_token: Optional[str]
    has_more: Optional[bool]
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListSpecialFocusResponseBodyBuilder: ...

class ListSpecialFocusResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: List[SpecialFocus]) -> ListSpecialFocusResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListSpecialFocusResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListSpecialFocusResponseBodyBuilder: ...
    def build(self) -> ListSpecialFocusResponseBody: ...
