from lark_oapi.core.construct import init as init

class MeJoinChatMembersResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MeJoinChatMembersResponseBodyBuilder: ...

class MeJoinChatMembersResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> MeJoinChatMembersResponseBody: ...
