from lark_oapi.core.construct import init as init

class MeJoinChatMembersRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MeJoinChatMembersRequestBodyBuilder: ...

class MeJoinChatMembersRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> MeJoinChatMembersRequestBody: ...
