from .merge_forward_message_request_body import MergeForwardMessageRequestBody as MergeForwardMessageRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class MergeForwardMessageRequest(BaseRequest):
    receive_id_type: str | None
    uuid: str | None
    request_body: MergeForwardMessageRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> MergeForwardMessageRequestBuilder: ...

class MergeForwardMessageRequestBuilder:
    def __init__(self) -> None: ...
    def receive_id_type(self, receive_id_type: str) -> MergeForwardMessageRequestBuilder: ...
    def uuid(self, uuid: str) -> MergeForwardMessageRequestBuilder: ...
    def request_body(self, request_body: MergeForwardMessageRequestBody) -> MergeForwardMessageRequestBuilder: ...
    def build(self) -> MergeForwardMessageRequest: ...
