from lark_oapi.core.construct import init as init

class MergeForwardMessageRequestBody:
    receive_id: str | None
    message_id_list: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MergeForwardMessageRequestBodyBuilder: ...

class MergeForwardMessageRequestBodyBuilder:
    def __init__(self) -> None: ...
    def receive_id(self, receive_id: str) -> MergeForwardMessageRequestBodyBuilder: ...
    def message_id_list(self, message_id_list: list[str]) -> MergeForwardMessageRequestBodyBuilder: ...
    def build(self) -> MergeForwardMessageRequestBody: ...
