from .emoji import Emoji as Emoji
from .operator import Operator as Operator
from lark_oapi.core.construct import init as init

class MessageReaction:
    reaction_id: str | None
    operator: Operator | None
    action_time: int | None
    reaction_type: Emoji | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MessageReactionBuilder: ...

class MessageReactionBuilder:
    def __init__(self) -> None: ...
    def reaction_id(self, reaction_id: str) -> MessageReactionBuilder: ...
    def operator(self, operator: Operator) -> MessageReactionBuilder: ...
    def action_time(self, action_time: int) -> MessageReactionBuilder: ...
    def reaction_type(self, reaction_type: Emoji) -> MessageReactionBuilder: ...
    def build(self) -> MessageReaction: ...
