from lark_oapi.core.construct import init as init

class MessageBody:
    content: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MessageBodyBuilder: ...

class MessageBodyBuilder:
    def __init__(self) -> None: ...
    def content(self, content: str) -> MessageBodyBuilder: ...
    def build(self) -> MessageBody: ...
