from .patch_message_request_body import PatchMessageRequestBody as PatchMessageRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PatchMessageRequest(BaseRequest):
    message_id: str | None
    request_body: PatchMessageRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PatchMessageRequestBuilder: ...

class PatchMessageRequestBuilder:
    def __init__(self) -> None: ...
    def message_id(self, message_id: str) -> PatchMessageRequestBuilder: ...
    def request_body(self, request_body: PatchMessageRequestBody) -> PatchMessageRequestBuilder: ...
    def build(self) -> PatchMessageRequest: ...
