from .patch_chat_menu_item_request_body import PatchChatMenuItemRequestBody as PatchChatMenuItemRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PatchChatMenuItemRequest(BaseRequest):
    chat_id: str | None
    menu_item_id: int | None
    request_body: PatchChatMenuItemRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PatchChatMenuItemRequestBuilder: ...

class PatchChatMenuItemRequestBuilder:
    def __init__(self) -> None: ...
    def chat_id(self, chat_id: str) -> PatchChatMenuItemRequestBuilder: ...
    def menu_item_id(self, menu_item_id: int) -> PatchChatMenuItemRequestBuilder: ...
    def request_body(self, request_body: PatchChatMenuItemRequestBody) -> PatchChatMenuItemRequestBuilder: ...
    def build(self) -> PatchChatMenuItemRequest: ...
