from .patch_chat_announcement_request_body import PatchChatAnnouncementRequestBody as PatchChatAnnouncementRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PatchChatAnnouncementRequest(BaseRequest):
    chat_id: str | None
    request_body: PatchChatAnnouncementRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PatchChatAnnouncementRequestBuilder: ...

class PatchChatAnnouncementRequestBuilder:
    def __init__(self) -> None: ...
    def chat_id(self, chat_id: str) -> PatchChatAnnouncementRequestBuilder: ...
    def request_body(self, request_body: PatchChatAnnouncementRequestBody) -> PatchChatAnnouncementRequestBuilder: ...
    def build(self) -> PatchChatAnnouncementRequest: ...
