from .chat_menu_item import ChatMenuItem as ChatMenuItem
from lark_oapi.core.construct import init as init

class PatchChatMenuItemResponseBody:
    chat_menu_item: ChatMenuItem | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchChatMenuItemResponseBodyBuilder: ...

class PatchChatMenuItemResponseBodyBuilder:
    def __init__(self) -> None: ...
    def chat_menu_item(self, chat_menu_item: ChatMenuItem) -> PatchChatMenuItemResponseBodyBuilder: ...
    def build(self) -> PatchChatMenuItemResponseBody: ...
