from lark_oapi.core.construct import init as init

class PatchMessageRequestBody:
    content: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchMessageRequestBodyBuilder: ...

class PatchMessageRequestBodyBuilder:
    def __init__(self) -> None: ...
    def content(self, content: str) -> PatchMessageRequestBodyBuilder: ...
    def build(self) -> PatchMessageRequestBody: ...
