from lark_oapi.core.construct import init as init

class PatchChatAnnouncementRequestBody:
    revision: str | None
    requests: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchChatAnnouncementRequestBodyBuilder: ...

class PatchChatAnnouncementRequestBodyBuilder:
    def __init__(self) -> None: ...
    def revision(self, revision: str) -> PatchChatAnnouncementRequestBodyBuilder: ...
    def requests(self, requests: list[str]) -> PatchChatAnnouncementRequestBodyBuilder: ...
    def build(self) -> PatchChatAnnouncementRequestBody: ...
