from lark_oapi.core.construct import init as init

class Pin:
    message_id: str | None
    chat_id: str | None
    operator_id: str | None
    operator_id_type: str | None
    create_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PinBuilder: ...

class PinBuilder:
    def __init__(self) -> None: ...
    def message_id(self, message_id: str) -> PinBuilder: ...
    def chat_id(self, chat_id: str) -> PinBuilder: ...
    def operator_id(self, operator_id: str) -> PinBuilder: ...
    def operator_id_type(self, operator_id_type: str) -> PinBuilder: ...
    def create_time(self, create_time: str) -> PinBuilder: ...
    def build(self) -> Pin: ...
