from .chat_top_notice import ChatTopNotice as ChatTopNotice
from lark_oapi.core.construct import init as init

class PutTopNoticeChatTopNoticeRequestBody:
    chat_top_notice: list[ChatTopNotice] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PutTopNoticeChatTopNoticeRequestBodyBuilder: ...

class PutTopNoticeChatTopNoticeRequestBodyBuilder:
    def __init__(self) -> None: ...
    def chat_top_notice(self, chat_top_notice: list[ChatTopNotice]) -> PutTopNoticeChatTopNoticeRequestBodyBuilder: ...
    def build(self) -> PutTopNoticeChatTopNoticeRequestBody: ...
