from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ReadUsersMessageRequest(BaseRequest):
    user_id_type: str | None
    page_size: int | None
    page_token: str | None
    message_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ReadUsersMessageRequestBuilder: ...

class ReadUsersMessageRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> ReadUsersMessageRequestBuilder: ...
    def page_size(self, page_size: int) -> ReadUsersMessageRequestBuilder: ...
    def page_token(self, page_token: str) -> ReadUsersMessageRequestBuilder: ...
    def message_id(self, message_id: str) -> ReadUsersMessageRequestBuilder: ...
    def build(self) -> ReadUsersMessageRequest: ...
