from lark_oapi.core.construct import init as init

class ReadUser:
    user_id_type: str | None
    user_id: str | None
    timestamp: str | None
    tenant_key: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReadUserBuilder: ...

class ReadUserBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> ReadUserBuilder: ...
    def user_id(self, user_id: str) -> ReadUserBuilder: ...
    def timestamp(self, timestamp: str) -> ReadUserBuilder: ...
    def tenant_key(self, tenant_key: str) -> ReadUserBuilder: ...
    def build(self) -> ReadUser: ...
