from lark_oapi.core.construct import init as init

class ReplyMessageRequestBody:
    content: str | None
    msg_type: str | None
    reply_in_thread: bool | None
    uuid: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReplyMessageRequestBodyBuilder: ...

class ReplyMessageRequestBodyBuilder:
    def __init__(self) -> None: ...
    def content(self, content: str) -> ReplyMessageRequestBodyBuilder: ...
    def msg_type(self, msg_type: str) -> ReplyMessageRequestBodyBuilder: ...
    def reply_in_thread(self, reply_in_thread: bool) -> ReplyMessageRequestBodyBuilder: ...
    def uuid(self, uuid: str) -> ReplyMessageRequestBodyBuilder: ...
    def build(self) -> ReplyMessageRequestBody: ...
