from .reply_message_request_body import ReplyMessageRequestBody as ReplyMessageRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ReplyMessageRequest(BaseRequest):
    message_id: str | None
    request_body: ReplyMessageRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ReplyMessageRequestBuilder: ...

class ReplyMessageRequestBuilder:
    def __init__(self) -> None: ...
    def message_id(self, message_id: str) -> ReplyMessageRequestBuilder: ...
    def request_body(self, request_body: ReplyMessageRequestBody) -> ReplyMessageRequestBuilder: ...
    def build(self) -> ReplyMessageRequest: ...
