from .sort_chat_menu_tree_request_body import SortChatMenuTreeRequestBody as SortChatMenuTreeRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class SortChatMenuTreeRequest(BaseRequest):
    chat_id: str | None
    request_body: SortChatMenuTreeRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> SortChatMenuTreeRequestBuilder: ...

class SortChatMenuTreeRequestBuilder:
    def __init__(self) -> None: ...
    def chat_id(self, chat_id: str) -> SortChatMenuTreeRequestBuilder: ...
    def request_body(self, request_body: SortChatMenuTreeRequestBody) -> SortChatMenuTreeRequestBuilder: ...
    def build(self) -> SortChatMenuTreeRequest: ...
