from .chat_tab import ChatTab as ChatTab
from lark_oapi.core.construct import init as init

class SortTabsChatTabResponseBody:
    chat_tabs: list[ChatTab] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SortTabsChatTabResponseBodyBuilder: ...

class SortTabsChatTabResponseBodyBuilder:
    def __init__(self) -> None: ...
    def chat_tabs(self, chat_tabs: list[ChatTab]) -> SortTabsChatTabResponseBodyBuilder: ...
    def build(self) -> SortTabsChatTabResponseBody: ...
