from lark_oapi.core.construct import init as init

class Thread:
    thread_id: str | None
    chat_id: str | None
    update_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ThreadBuilder: ...

class ThreadBuilder:
    def __init__(self) -> None: ...
    def thread_id(self, thread_id: str) -> ThreadBuilder: ...
    def chat_id(self, chat_id: str) -> ThreadBuilder: ...
    def update_time(self, update_time: str) -> ThreadBuilder: ...
    def build(self) -> Thread: ...
