from .i18n_names import I18nNames as I18nNames
from .toolkit_callback import ToolkitCallback as ToolkitCallback
from .toolkit_redirect_link import ToolkitRedirectLink as ToolkitRedirectLink
from lark_oapi.core.construct import init as init

class Toolkit:
    toolkit_id: int | None
    image_key: str | None
    toolkit_name: str | None
    i18n_name: I18nNames | None
    toolkit_type: str | None
    redirect_link: ToolkitRedirectLink | None
    callback: ToolkitCallback | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ToolkitBuilder: ...

class ToolkitBuilder:
    def __init__(self) -> None: ...
    def toolkit_id(self, toolkit_id: int) -> ToolkitBuilder: ...
    def image_key(self, image_key: str) -> ToolkitBuilder: ...
    def toolkit_name(self, toolkit_name: str) -> ToolkitBuilder: ...
    def i18n_name(self, i18n_name: I18nNames) -> ToolkitBuilder: ...
    def toolkit_type(self, toolkit_type: str) -> ToolkitBuilder: ...
    def redirect_link(self, redirect_link: ToolkitRedirectLink) -> ToolkitBuilder: ...
    def callback(self, callback: ToolkitCallback) -> ToolkitBuilder: ...
    def build(self) -> Toolkit: ...
