from lark_oapi.core.construct import init as init

class ToolkitRedirectLink:
    url: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ToolkitRedirectLinkBuilder: ...

class ToolkitRedirectLinkBuilder:
    def __init__(self) -> None: ...
    def url(self, url: str) -> ToolkitRedirectLinkBuilder: ...
    def build(self) -> ToolkitRedirectLink: ...
