from typing import *
from .unread_special_focus_request_body import UnreadSpecialFocusRequestBody as UnreadSpecialFocusRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UnreadSpecialFocusRequest(BaseRequest):
    member_id_type: Optional[str]
    request_body: Optional[UnreadSpecialFocusRequestBody]
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UnreadSpecialFocusRequestBuilder: ...

class UnreadSpecialFocusRequestBuilder:
    def __init__(self) -> None: ...
    def member_id_type(self, member_id_type: str) -> UnreadSpecialFocusRequestBuilder: ...
    def request_body(self, request_body: UnreadSpecialFocusRequestBody) -> UnreadSpecialFocusRequestBuilder: ...
    def build(self) -> UnreadSpecialFocusRequest: ...
