from lark_oapi.core.construct import init as init

class UpdateMessageRequestBody:
    msg_type: str | None
    content: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateMessageRequestBodyBuilder: ...

class UpdateMessageRequestBodyBuilder:
    def __init__(self) -> None: ...
    def msg_type(self, msg_type: str) -> UpdateMessageRequestBodyBuilder: ...
    def content(self, content: str) -> UpdateMessageRequestBodyBuilder: ...
    def build(self) -> UpdateMessageRequestBody: ...
