from .update_message_request_body import UpdateMessageRequestBody as UpdateMessageRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UpdateMessageRequest(BaseRequest):
    message_id: str | None
    request_body: UpdateMessageRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UpdateMessageRequestBuilder: ...

class UpdateMessageRequestBuilder:
    def __init__(self) -> None: ...
    def message_id(self, message_id: str) -> UpdateMessageRequestBuilder: ...
    def request_body(self, request_body: UpdateMessageRequestBody) -> UpdateMessageRequestBuilder: ...
    def build(self) -> UpdateMessageRequest: ...
