from .i18n_names import I18nNames as I18nNames
from .restricted_mode_setting import RestrictedModeSetting as RestrictedModeSetting
from lark_oapi.core.construct import init as init

class UpdateChatRequestBody:
    avatar: str | None
    name: str | None
    description: str | None
    i18n_names: I18nNames | None
    add_member_permission: str | None
    share_card_permission: str | None
    at_all_permission: str | None
    edit_permission: str | None
    owner_id: str | None
    join_message_visibility: str | None
    leave_message_visibility: str | None
    membership_approval: str | None
    labels: list[str] | None
    toolkit_ids: list[int] | None
    restricted_mode_setting: RestrictedModeSetting | None
    chat_type: str | None
    group_message_type: str | None
    urgent_setting: str | None
    video_conference_setting: str | None
    pin_manage_setting: str | None
    hide_member_count_setting: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateChatRequestBodyBuilder: ...

class UpdateChatRequestBodyBuilder:
    def __init__(self) -> None: ...
    def avatar(self, avatar: str) -> UpdateChatRequestBodyBuilder: ...
    def name(self, name: str) -> UpdateChatRequestBodyBuilder: ...
    def description(self, description: str) -> UpdateChatRequestBodyBuilder: ...
    def i18n_names(self, i18n_names: I18nNames) -> UpdateChatRequestBodyBuilder: ...
    def add_member_permission(self, add_member_permission: str) -> UpdateChatRequestBodyBuilder: ...
    def share_card_permission(self, share_card_permission: str) -> UpdateChatRequestBodyBuilder: ...
    def at_all_permission(self, at_all_permission: str) -> UpdateChatRequestBodyBuilder: ...
    def edit_permission(self, edit_permission: str) -> UpdateChatRequestBodyBuilder: ...
    def owner_id(self, owner_id: str) -> UpdateChatRequestBodyBuilder: ...
    def join_message_visibility(self, join_message_visibility: str) -> UpdateChatRequestBodyBuilder: ...
    def leave_message_visibility(self, leave_message_visibility: str) -> UpdateChatRequestBodyBuilder: ...
    def membership_approval(self, membership_approval: str) -> UpdateChatRequestBodyBuilder: ...
    def labels(self, labels: list[str]) -> UpdateChatRequestBodyBuilder: ...
    def toolkit_ids(self, toolkit_ids: list[int]) -> UpdateChatRequestBodyBuilder: ...
    def restricted_mode_setting(self, restricted_mode_setting: RestrictedModeSetting) -> UpdateChatRequestBodyBuilder: ...
    def chat_type(self, chat_type: str) -> UpdateChatRequestBodyBuilder: ...
    def group_message_type(self, group_message_type: str) -> UpdateChatRequestBodyBuilder: ...
    def urgent_setting(self, urgent_setting: str) -> UpdateChatRequestBodyBuilder: ...
    def video_conference_setting(self, video_conference_setting: str) -> UpdateChatRequestBodyBuilder: ...
    def pin_manage_setting(self, pin_manage_setting: str) -> UpdateChatRequestBodyBuilder: ...
    def hide_member_count_setting(self, hide_member_count_setting: str) -> UpdateChatRequestBodyBuilder: ...
    def build(self) -> UpdateChatRequestBody: ...
