from lark_oapi.core.construct import init as init

class UrgentReceivers:
    user_id_list: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UrgentReceiversBuilder: ...

class UrgentReceiversBuilder:
    def __init__(self) -> None: ...
    def user_id_list(self, user_id_list: list[str]) -> UrgentReceiversBuilder: ...
    def build(self) -> UrgentReceivers: ...
