from lark_oapi.core.construct import init as init

class WidgetUrl:
    url: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WidgetUrlBuilder: ...

class WidgetUrlBuilder:
    def __init__(self) -> None: ...
    def url(self, url: str) -> WidgetUrlBuilder: ...
    def build(self) -> WidgetUrl: ...
