from .mailgroup_manager import MailgroupManager as MailgroupManager
from lark_oapi.core.construct import init as init

class BatchCreateMailgroupManagerRequestBody:
    mailgroup_manager_list: list[MailgroupManager] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchCreateMailgroupManagerRequestBodyBuilder: ...

class BatchCreateMailgroupManagerRequestBodyBuilder:
    def __init__(self) -> None: ...
    def mailgroup_manager_list(self, mailgroup_manager_list: list[MailgroupManager]) -> BatchCreateMailgroupManagerRequestBodyBuilder: ...
    def build(self) -> BatchCreateMailgroupManagerRequestBody: ...
