from .batch_delete_mailgroup_permission_member_request_body import BatchDeleteMailgroupPermissionMemberRequestBody as BatchDeleteMailgroupPermissionMemberRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchDeleteMailgroupPermissionMemberRequest(BaseRequest):
    mailgroup_id: str | None
    request_body: BatchDeleteMailgroupPermissionMemberRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchDeleteMailgroupPermissionMemberRequestBuilder: ...

class BatchDeleteMailgroupPermissionMemberRequestBuilder:
    def __init__(self) -> None: ...
    def mailgroup_id(self, mailgroup_id: str) -> BatchDeleteMailgroupPermissionMemberRequestBuilder: ...
    def request_body(self, request_body: BatchDeleteMailgroupPermissionMemberRequestBody) -> BatchDeleteMailgroupPermissionMemberRequestBuilder: ...
    def build(self) -> BatchDeleteMailgroupPermissionMemberRequest: ...
