from .mailgroup_member import MailgroupMember as MailgroupMember
from lark_oapi.core.construct import init as init

class BatchCreateMailgroupMemberResponseBody:
    items: list[MailgroupMember] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchCreateMailgroupMemberResponseBodyBuilder: ...

class BatchCreateMailgroupMemberResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[MailgroupMember]) -> BatchCreateMailgroupMemberResponseBodyBuilder: ...
    def build(self) -> BatchCreateMailgroupMemberResponseBody: ...
