from lark_oapi.core.construct import init as init

class BatchDeleteMailgroupMemberResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchDeleteMailgroupMemberResponseBodyBuilder: ...

class BatchDeleteMailgroupMemberResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> BatchDeleteMailgroupMemberResponseBody: ...
