from .batch_delete_mailgroup_manager_request_body import BatchDeleteMailgroupManagerRequestBody as BatchDeleteMailgroupManagerRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchDeleteMailgroupManagerRequest(BaseRequest):
    user_id_type: str | None
    mailgroup_id: str | None
    request_body: BatchDeleteMailgroupManagerRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchDeleteMailgroupManagerRequestBuilder: ...

class BatchDeleteMailgroupManagerRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> BatchDeleteMailgroupManagerRequestBuilder: ...
    def mailgroup_id(self, mailgroup_id: str) -> BatchDeleteMailgroupManagerRequestBuilder: ...
    def request_body(self, request_body: BatchDeleteMailgroupManagerRequestBody) -> BatchDeleteMailgroupManagerRequestBuilder: ...
    def build(self) -> BatchDeleteMailgroupManagerRequest: ...
