from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ClearPublicMailboxMemberRequest(BaseRequest):
    public_mailbox_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ClearPublicMailboxMemberRequestBuilder: ...

class ClearPublicMailboxMemberRequestBuilder:
    def __init__(self) -> None: ...
    def public_mailbox_id(self, public_mailbox_id: str) -> ClearPublicMailboxMemberRequestBuilder: ...
    def build(self) -> ClearPublicMailboxMemberRequest: ...
