from lark_oapi.core.construct import init as init

class ClearPublicMailboxMemberRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ClearPublicMailboxMemberRequestBodyBuilder: ...

class ClearPublicMailboxMemberRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ClearPublicMailboxMemberRequestBody: ...
