from lark_oapi.core.construct import init as init

class ClearPublicMailboxMemberResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ClearPublicMailboxMemberResponseBodyBuilder: ...

class ClearPublicMailboxMemberResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ClearPublicMailboxMemberResponseBody: ...
