from lark_oapi.core.construct import init as init

class CreateMailgroupMemberResponseBody:
    member_id: str | None
    email: str | None
    user_id: str | None
    department_id: str | None
    type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateMailgroupMemberResponseBodyBuilder: ...

class CreateMailgroupMemberResponseBodyBuilder:
    def __init__(self) -> None: ...
    def member_id(self, member_id: str) -> CreateMailgroupMemberResponseBodyBuilder: ...
    def email(self, email: str) -> CreateMailgroupMemberResponseBodyBuilder: ...
    def user_id(self, user_id: str) -> CreateMailgroupMemberResponseBodyBuilder: ...
    def department_id(self, department_id: str) -> CreateMailgroupMemberResponseBodyBuilder: ...
    def type(self, type: str) -> CreateMailgroupMemberResponseBodyBuilder: ...
    def build(self) -> CreateMailgroupMemberResponseBody: ...
