from lark_oapi.core.construct import init as init

class CreatePublicMailboxResponseBody:
    public_mailbox_id: str | None
    email: str | None
    name: str | None
    geo: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreatePublicMailboxResponseBodyBuilder: ...

class CreatePublicMailboxResponseBodyBuilder:
    def __init__(self) -> None: ...
    def public_mailbox_id(self, public_mailbox_id: str) -> CreatePublicMailboxResponseBodyBuilder: ...
    def email(self, email: str) -> CreatePublicMailboxResponseBodyBuilder: ...
    def name(self, name: str) -> CreatePublicMailboxResponseBodyBuilder: ...
    def geo(self, geo: str) -> CreatePublicMailboxResponseBodyBuilder: ...
    def build(self) -> CreatePublicMailboxResponseBody: ...
