from .rule import Rule as Rule
from lark_oapi.core.construct import init as init

class CreateUserMailboxRuleResponseBody:
    rule: Rule | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateUserMailboxRuleResponseBodyBuilder: ...

class CreateUserMailboxRuleResponseBodyBuilder:
    def __init__(self) -> None: ...
    def rule(self, rule: Rule) -> CreateUserMailboxRuleResponseBodyBuilder: ...
    def build(self) -> CreateUserMailboxRuleResponseBody: ...
