from lark_oapi.core.construct import init as init

class CreateMailgroupResponseBody:
    mailgroup_id: str | None
    email: str | None
    name: str | None
    description: str | None
    direct_members_count: str | None
    include_external_member: bool | None
    include_all_company_member: bool | None
    who_can_send_mail: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateMailgroupResponseBodyBuilder: ...

class CreateMailgroupResponseBodyBuilder:
    def __init__(self) -> None: ...
    def mailgroup_id(self, mailgroup_id: str) -> CreateMailgroupResponseBodyBuilder: ...
    def email(self, email: str) -> CreateMailgroupResponseBodyBuilder: ...
    def name(self, name: str) -> CreateMailgroupResponseBodyBuilder: ...
    def description(self, description: str) -> CreateMailgroupResponseBodyBuilder: ...
    def direct_members_count(self, direct_members_count: str) -> CreateMailgroupResponseBodyBuilder: ...
    def include_external_member(self, include_external_member: bool) -> CreateMailgroupResponseBodyBuilder: ...
    def include_all_company_member(self, include_all_company_member: bool) -> CreateMailgroupResponseBodyBuilder: ...
    def who_can_send_mail(self, who_can_send_mail: str) -> CreateMailgroupResponseBodyBuilder: ...
    def build(self) -> CreateMailgroupResponseBody: ...
