from .mail_contact import MailContact as MailContact
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateUserMailboxMailContactRequest(BaseRequest):
    user_mailbox_id: str | None
    request_body: MailContact | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateUserMailboxMailContactRequestBuilder: ...

class CreateUserMailboxMailContactRequestBuilder:
    def __init__(self) -> None: ...
    def user_mailbox_id(self, user_mailbox_id: str) -> CreateUserMailboxMailContactRequestBuilder: ...
    def request_body(self, request_body: MailContact) -> CreateUserMailboxMailContactRequestBuilder: ...
    def build(self) -> CreateUserMailboxMailContactRequest: ...
