from .public_mailbox_member import PublicMailboxMember as PublicMailboxMember
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreatePublicMailboxMemberRequest(BaseRequest):
    user_id_type: str | None
    public_mailbox_id: str | None
    request_body: PublicMailboxMember | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreatePublicMailboxMemberRequestBuilder: ...

class CreatePublicMailboxMemberRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> CreatePublicMailboxMemberRequestBuilder: ...
    def public_mailbox_id(self, public_mailbox_id: str) -> CreatePublicMailboxMemberRequestBuilder: ...
    def request_body(self, request_body: PublicMailboxMember) -> CreatePublicMailboxMemberRequestBuilder: ...
    def build(self) -> CreatePublicMailboxMemberRequest: ...
