from lark_oapi.core.construct import init as init

class DeletePublicMailboxAliasRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeletePublicMailboxAliasRequestBodyBuilder: ...

class DeletePublicMailboxAliasRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeletePublicMailboxAliasRequestBody: ...
