from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteMailgroupAliasRequest(BaseRequest):
    mailgroup_id: str | None
    alias_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteMailgroupAliasRequestBuilder: ...

class DeleteMailgroupAliasRequestBuilder:
    def __init__(self) -> None: ...
    def mailgroup_id(self, mailgroup_id: str) -> DeleteMailgroupAliasRequestBuilder: ...
    def alias_id(self, alias_id: str) -> DeleteMailgroupAliasRequestBuilder: ...
    def build(self) -> DeleteMailgroupAliasRequest: ...
