from lark_oapi.core.construct import init as init

class DeleteUserMailboxRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteUserMailboxRequestBodyBuilder: ...

class DeleteUserMailboxRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteUserMailboxRequestBody: ...
