from lark_oapi.core.construct import init as init

class DeleteUserMailboxAliasResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteUserMailboxAliasResponseBodyBuilder: ...

class DeleteUserMailboxAliasResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteUserMailboxAliasResponseBody: ...
