from lark_oapi.core.construct import init as init

class DeleteMailgroupRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteMailgroupRequestBodyBuilder: ...

class DeleteMailgroupRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteMailgroupRequestBody: ...
