from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeletePublicMailboxMemberRequest(BaseRequest):
    public_mailbox_id: str | None
    member_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeletePublicMailboxMemberRequestBuilder: ...

class DeletePublicMailboxMemberRequestBuilder:
    def __init__(self) -> None: ...
    def public_mailbox_id(self, public_mailbox_id: str) -> DeletePublicMailboxMemberRequestBuilder: ...
    def member_id(self, member_id: str) -> DeletePublicMailboxMemberRequestBuilder: ...
    def build(self) -> DeletePublicMailboxMemberRequest: ...
