from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeletePublicMailboxAliasRequest(BaseRequest):
    public_mailbox_id: str | None
    alias_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeletePublicMailboxAliasRequestBuilder: ...

class DeletePublicMailboxAliasRequestBuilder:
    def __init__(self) -> None: ...
    def public_mailbox_id(self, public_mailbox_id: str) -> DeletePublicMailboxAliasRequestBuilder: ...
    def alias_id(self, alias_id: str) -> DeletePublicMailboxAliasRequestBuilder: ...
    def build(self) -> DeletePublicMailboxAliasRequest: ...
