from lark_oapi.core.construct import init as init

class DeletePublicMailboxMemberRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeletePublicMailboxMemberRequestBodyBuilder: ...

class DeletePublicMailboxMemberRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeletePublicMailboxMemberRequestBody: ...
