from .attachment_download_url_item import AttachmentDownloadUrlItem as AttachmentDownloadUrlItem
from lark_oapi.core.construct import init as init

class DownloadUrlUserMailboxMessageAttachmentResponseBody:
    download_urls: list[AttachmentDownloadUrlItem] | None
    failed_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DownloadUrlUserMailboxMessageAttachmentResponseBodyBuilder: ...

class DownloadUrlUserMailboxMessageAttachmentResponseBodyBuilder:
    def __init__(self) -> None: ...
    def download_urls(self, download_urls: list[AttachmentDownloadUrlItem]) -> DownloadUrlUserMailboxMessageAttachmentResponseBodyBuilder: ...
    def failed_ids(self, failed_ids: list[str]) -> DownloadUrlUserMailboxMessageAttachmentResponseBodyBuilder: ...
    def build(self) -> DownloadUrlUserMailboxMessageAttachmentResponseBody: ...
