from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DownloadUrlUserMailboxMessageAttachmentRequest(BaseRequest):
    attachment_ids: list[str] | None
    user_mailbox_id: str | None
    message_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DownloadUrlUserMailboxMessageAttachmentRequestBuilder: ...

class DownloadUrlUserMailboxMessageAttachmentRequestBuilder:
    def __init__(self) -> None: ...
    def attachment_ids(self, attachment_ids: list[str]) -> DownloadUrlUserMailboxMessageAttachmentRequestBuilder: ...
    def user_mailbox_id(self, user_mailbox_id: str) -> DownloadUrlUserMailboxMessageAttachmentRequestBuilder: ...
    def message_id(self, message_id: str) -> DownloadUrlUserMailboxMessageAttachmentRequestBuilder: ...
    def build(self) -> DownloadUrlUserMailboxMessageAttachmentRequest: ...
