from lark_oapi.core.construct import init as init

class FileMetaInfo:
    id: str | None
    filename_hash: str | None
    size: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FileMetaInfoBuilder: ...

class FileMetaInfoBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> FileMetaInfoBuilder: ...
    def filename_hash(self, filename_hash: str) -> FileMetaInfoBuilder: ...
    def size(self, size: int) -> FileMetaInfoBuilder: ...
    def build(self) -> FileMetaInfo: ...
