from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetMailgroupPermissionMemberRequest(BaseRequest):
    user_id_type: str | None
    department_id_type: str | None
    mailgroup_id: str | None
    permission_member_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetMailgroupPermissionMemberRequestBuilder: ...

class GetMailgroupPermissionMemberRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> GetMailgroupPermissionMemberRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> GetMailgroupPermissionMemberRequestBuilder: ...
    def mailgroup_id(self, mailgroup_id: str) -> GetMailgroupPermissionMemberRequestBuilder: ...
    def permission_member_id(self, permission_member_id: str) -> GetMailgroupPermissionMemberRequestBuilder: ...
    def build(self) -> GetMailgroupPermissionMemberRequest: ...
