from lark_oapi.core.construct import init as init

class GetMailgroupRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetMailgroupRequestBodyBuilder: ...

class GetMailgroupRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetMailgroupRequestBody: ...
