from lark_oapi.core.construct import init as init

class GetPublicMailboxRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetPublicMailboxRequestBodyBuilder: ...

class GetPublicMailboxRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetPublicMailboxRequestBody: ...
