from lark_oapi.core.construct import init as init

class GetPublicMailboxMemberRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetPublicMailboxMemberRequestBodyBuilder: ...

class GetPublicMailboxMemberRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetPublicMailboxMemberRequestBody: ...
