from lark_oapi.core.construct import init as init

class GetMailgroupPermissionMemberResponseBody:
    permission_member_id: str | None
    user_id: str | None
    department_id: str | None
    email: str | None
    type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetMailgroupPermissionMemberResponseBodyBuilder: ...

class GetMailgroupPermissionMemberResponseBodyBuilder:
    def __init__(self) -> None: ...
    def permission_member_id(self, permission_member_id: str) -> GetMailgroupPermissionMemberResponseBodyBuilder: ...
    def user_id(self, user_id: str) -> GetMailgroupPermissionMemberResponseBodyBuilder: ...
    def department_id(self, department_id: str) -> GetMailgroupPermissionMemberResponseBodyBuilder: ...
    def email(self, email: str) -> GetMailgroupPermissionMemberResponseBodyBuilder: ...
    def type(self, type: str) -> GetMailgroupPermissionMemberResponseBodyBuilder: ...
    def build(self) -> GetMailgroupPermissionMemberResponseBody: ...
