from lark_oapi.core.construct import init as init

class ListPublicMailboxRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListPublicMailboxRequestBodyBuilder: ...

class ListPublicMailboxRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListPublicMailboxRequestBody: ...
