from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListMailgroupManagerRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    user_id_type: str | None
    mailgroup_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListMailgroupManagerRequestBuilder: ...

class ListMailgroupManagerRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> ListMailgroupManagerRequestBuilder: ...
    def page_token(self, page_token: str) -> ListMailgroupManagerRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> ListMailgroupManagerRequestBuilder: ...
    def mailgroup_id(self, mailgroup_id: str) -> ListMailgroupManagerRequestBuilder: ...
    def build(self) -> ListMailgroupManagerRequest: ...
