from .email_alias import EmailAlias as EmailAlias
from lark_oapi.core.construct import init as init

class ListUserMailboxAliasResponseBody:
    items: list[EmailAlias] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListUserMailboxAliasResponseBodyBuilder: ...

class ListUserMailboxAliasResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[EmailAlias]) -> ListUserMailboxAliasResponseBodyBuilder: ...
    def build(self) -> ListUserMailboxAliasResponseBody: ...
