from .rule import Rule as Rule
from lark_oapi.core.construct import init as init

class ListUserMailboxRuleResponseBody:
    items: list[Rule] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListUserMailboxRuleResponseBodyBuilder: ...

class ListUserMailboxRuleResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[Rule]) -> ListUserMailboxRuleResponseBodyBuilder: ...
    def build(self) -> ListUserMailboxRuleResponseBody: ...
