from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListMailgroupAliasRequest(BaseRequest):
    mailgroup_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListMailgroupAliasRequestBuilder: ...

class ListMailgroupAliasRequestBuilder:
    def __init__(self) -> None: ...
    def mailgroup_id(self, mailgroup_id: str) -> ListMailgroupAliasRequestBuilder: ...
    def build(self) -> ListMailgroupAliasRequest: ...
