from lark_oapi.core.construct import init as init

class ListMailgroupRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListMailgroupRequestBodyBuilder: ...

class ListMailgroupRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListMailgroupRequestBody: ...
