from .mailgroup import Mailgroup as Mailgroup
from lark_oapi.core.construct import init as init

class ListMailgroupResponseBody:
    has_more: bool | None
    page_token: str | None
    items: list[Mailgroup] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListMailgroupResponseBodyBuilder: ...

class ListMailgroupResponseBodyBuilder:
    def __init__(self) -> None: ...
    def has_more(self, has_more: bool) -> ListMailgroupResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListMailgroupResponseBodyBuilder: ...
    def items(self, items: list[Mailgroup]) -> ListMailgroupResponseBodyBuilder: ...
    def build(self) -> ListMailgroupResponseBody: ...
