from .mailgroup_permission_member import MailgroupPermissionMember as MailgroupPermissionMember
from lark_oapi.core.construct import init as init

class ListMailgroupPermissionMemberResponseBody:
    has_more: bool | None
    page_token: str | None
    items: list[MailgroupPermissionMember] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListMailgroupPermissionMemberResponseBodyBuilder: ...

class ListMailgroupPermissionMemberResponseBodyBuilder:
    def __init__(self) -> None: ...
    def has_more(self, has_more: bool) -> ListMailgroupPermissionMemberResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListMailgroupPermissionMemberResponseBodyBuilder: ...
    def items(self, items: list[MailgroupPermissionMember]) -> ListMailgroupPermissionMemberResponseBodyBuilder: ...
    def build(self) -> ListMailgroupPermissionMemberResponseBody: ...
