from lark_oapi.core.construct import init as init

class ListUserMailboxAliasRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListUserMailboxAliasRequestBodyBuilder: ...

class ListUserMailboxAliasRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListUserMailboxAliasRequestBody: ...
