from lark_oapi.core.construct import init as init

class MailgroupMember:
    member_id: str | None
    email: str | None
    user_id: str | None
    department_id: str | None
    type: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MailgroupMemberBuilder: ...

class MailgroupMemberBuilder:
    def __init__(self) -> None: ...
    def member_id(self, member_id: str) -> MailgroupMemberBuilder: ...
    def email(self, email: str) -> MailgroupMemberBuilder: ...
    def user_id(self, user_id: str) -> MailgroupMemberBuilder: ...
    def department_id(self, department_id: str) -> MailgroupMemberBuilder: ...
    def type(self, type: str) -> MailgroupMemberBuilder: ...
    def build(self) -> MailgroupMember: ...
