from lark_oapi.core.construct import init as init

class MailContact:
    id: str | None
    name: str | None
    company: str | None
    phone: str | None
    mail_address: str | None
    tag: str | None
    remark: str | None
    avatar: str | None
    position: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MailContactBuilder: ...

class MailContactBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> MailContactBuilder: ...
    def name(self, name: str) -> MailContactBuilder: ...
    def company(self, company: str) -> MailContactBuilder: ...
    def phone(self, phone: str) -> MailContactBuilder: ...
    def mail_address(self, mail_address: str) -> MailContactBuilder: ...
    def tag(self, tag: str) -> MailContactBuilder: ...
    def remark(self, remark: str) -> MailContactBuilder: ...
    def avatar(self, avatar: str) -> MailContactBuilder: ...
    def position(self, position: str) -> MailContactBuilder: ...
    def build(self) -> MailContact: ...
