from lark_oapi.core.construct import init as init

class MailAddress:
    mail_address: str | None
    name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MailAddressBuilder: ...

class MailAddressBuilder:
    def __init__(self) -> None: ...
    def mail_address(self, mail_address: str) -> MailAddressBuilder: ...
    def name(self, name: str) -> MailAddressBuilder: ...
    def build(self) -> MailAddress: ...
