from lark_oapi.core.construct import init as init

class PatchPublicMailboxResponseBody:
    public_mailbox_id: str | None
    email: str | None
    name: str | None
    geo: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchPublicMailboxResponseBodyBuilder: ...

class PatchPublicMailboxResponseBodyBuilder:
    def __init__(self) -> None: ...
    def public_mailbox_id(self, public_mailbox_id: str) -> PatchPublicMailboxResponseBodyBuilder: ...
    def email(self, email: str) -> PatchPublicMailboxResponseBodyBuilder: ...
    def name(self, name: str) -> PatchPublicMailboxResponseBodyBuilder: ...
    def geo(self, geo: str) -> PatchPublicMailboxResponseBodyBuilder: ...
    def build(self) -> PatchPublicMailboxResponseBody: ...
