from lark_oapi.core.construct import init as init

class PublicMailbox:
    public_mailbox_id: str | None
    email: str | None
    name: str | None
    geo: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PublicMailboxBuilder: ...

class PublicMailboxBuilder:
    def __init__(self) -> None: ...
    def public_mailbox_id(self, public_mailbox_id: str) -> PublicMailboxBuilder: ...
    def email(self, email: str) -> PublicMailboxBuilder: ...
    def name(self, name: str) -> PublicMailboxBuilder: ...
    def geo(self, geo: str) -> PublicMailboxBuilder: ...
    def build(self) -> PublicMailbox: ...
