from .query_user_request_body import QueryUserRequestBody as QueryUserRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class QueryUserRequest(BaseRequest):
    request_body: QueryUserRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> QueryUserRequestBuilder: ...

class QueryUserRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: QueryUserRequestBody) -> QueryUserRequestBuilder: ...
    def build(self) -> QueryUserRequest: ...
