from .reorder_user_mailbox_rule_request_body import ReorderUserMailboxRuleRequestBody as ReorderUserMailboxRuleRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ReorderUserMailboxRuleRequest(BaseRequest):
    user_mailbox_id: str | None
    request_body: ReorderUserMailboxRuleRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ReorderUserMailboxRuleRequestBuilder: ...

class ReorderUserMailboxRuleRequestBuilder:
    def __init__(self) -> None: ...
    def user_mailbox_id(self, user_mailbox_id: str) -> ReorderUserMailboxRuleRequestBuilder: ...
    def request_body(self, request_body: ReorderUserMailboxRuleRequestBody) -> ReorderUserMailboxRuleRequestBuilder: ...
    def build(self) -> ReorderUserMailboxRuleRequest: ...
