from .rule_condition_item import RuleConditionItem as RuleConditionItem
from lark_oapi.core.construct import init as init

class RuleCondition:
    match_type: int | None
    items: list[RuleConditionItem] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RuleConditionBuilder: ...

class RuleConditionBuilder:
    def __init__(self) -> None: ...
    def match_type(self, match_type: int) -> RuleConditionBuilder: ...
    def items(self, items: list[RuleConditionItem]) -> RuleConditionBuilder: ...
    def build(self) -> RuleCondition: ...
