from lark_oapi.core.construct import init as init

class SendUserMailboxMessageResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SendUserMailboxMessageResponseBodyBuilder: ...

class SendUserMailboxMessageResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> SendUserMailboxMessageResponseBody: ...
