from lark_oapi.core.construct import init as init

class SubscriptionUserMailboxEventResponseBody:
    event_types: list[int] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SubscriptionUserMailboxEventResponseBodyBuilder: ...

class SubscriptionUserMailboxEventResponseBodyBuilder:
    def __init__(self) -> None: ...
    def event_types(self, event_types: list[int]) -> SubscriptionUserMailboxEventResponseBodyBuilder: ...
    def build(self) -> SubscriptionUserMailboxEventResponseBody: ...
