from lark_oapi.core.construct import init as init

class UnsubscribeUserMailboxEventRequestBody:
    event_type: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UnsubscribeUserMailboxEventRequestBodyBuilder: ...

class UnsubscribeUserMailboxEventRequestBodyBuilder:
    def __init__(self) -> None: ...
    def event_type(self, event_type: int) -> UnsubscribeUserMailboxEventRequestBodyBuilder: ...
    def build(self) -> UnsubscribeUserMailboxEventRequestBody: ...
