from .rule import Rule as Rule
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UpdateUserMailboxRuleRequest(BaseRequest):
    user_mailbox_id: str | None
    rule_id: int | None
    request_body: Rule | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UpdateUserMailboxRuleRequestBuilder: ...

class UpdateUserMailboxRuleRequestBuilder:
    def __init__(self) -> None: ...
    def user_mailbox_id(self, user_mailbox_id: str) -> UpdateUserMailboxRuleRequestBuilder: ...
    def rule_id(self, rule_id: int) -> UpdateUserMailboxRuleRequestBuilder: ...
    def request_body(self, request_body: Rule) -> UpdateUserMailboxRuleRequestBuilder: ...
    def build(self) -> UpdateUserMailboxRuleRequest: ...
