from lark_oapi.core.construct import init as init

class UserInfo:
    type: str | None
    owner_user_id: str | None
    public_mailbox_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserInfoBuilder: ...

class UserInfoBuilder:
    def __init__(self) -> None: ...
    def type(self, type: str) -> UserInfoBuilder: ...
    def owner_user_id(self, owner_user_id: str) -> UserInfoBuilder: ...
    def public_mailbox_id(self, public_mailbox_id: str) -> UserInfoBuilder: ...
    def build(self) -> UserInfo: ...
