from lark_oapi.core.construct import init as init

class UserId:
    user_id: str | None
    open_id: str | None
    union_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserIdBuilder: ...

class UserIdBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: str) -> UserIdBuilder: ...
    def open_id(self, open_id: str) -> UserIdBuilder: ...
    def union_id(self, union_id: str) -> UserIdBuilder: ...
    def build(self) -> UserId: ...
