from .add_role_assign_authorization_request_body import AddRoleAssignAuthorizationRequestBody as AddRoleAssignAuthorizationRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class AddRoleAssignAuthorizationRequest(BaseRequest):
    employment_id: str | None
    user_id_type: str | None
    role_id: str | None
    request_body: AddRoleAssignAuthorizationRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> AddRoleAssignAuthorizationRequestBuilder: ...

class AddRoleAssignAuthorizationRequestBuilder:
    def __init__(self) -> None: ...
    def employment_id(self, employment_id: str) -> AddRoleAssignAuthorizationRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> AddRoleAssignAuthorizationRequestBuilder: ...
    def role_id(self, role_id: str) -> AddRoleAssignAuthorizationRequestBuilder: ...
    def request_body(self, request_body: AddRoleAssignAuthorizationRequestBody) -> AddRoleAssignAuthorizationRequestBuilder: ...
    def build(self) -> AddRoleAssignAuthorizationRequest: ...
