from .assigned_organization_with_code import AssignedOrganizationWithCode as AssignedOrganizationWithCode
from lark_oapi.core.construct import init as init

class AddRoleAssignAuthorizationRequestBody:
    assigned_organization_items: list[list] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AddRoleAssignAuthorizationRequestBodyBuilder: ...

class AddRoleAssignAuthorizationRequestBodyBuilder:
    def __init__(self) -> None: ...
    def assigned_organization_items(self, assigned_organization_items: list[list]) -> AddRoleAssignAuthorizationRequestBodyBuilder: ...
    def build(self) -> AddRoleAssignAuthorizationRequestBody: ...
