from lark_oapi.core.construct import init as init

class ApplicationInfo:
    apply_initiator_id: str | None
    apply_initiating_time: str | None
    apply_finish_time: str | None
    process_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApplicationInfoBuilder: ...

class ApplicationInfoBuilder:
    def __init__(self) -> None: ...
    def apply_initiator_id(self, apply_initiator_id: str) -> ApplicationInfoBuilder: ...
    def apply_initiating_time(self, apply_initiating_time: str) -> ApplicationInfoBuilder: ...
    def apply_finish_time(self, apply_finish_time: str) -> ApplicationInfoBuilder: ...
    def process_id(self, process_id: str) -> ApplicationInfoBuilder: ...
    def build(self) -> ApplicationInfo: ...
