from .background_check_report_object import BackgroundCheckReportObject as BackgroundCheckReportObject
from lark_oapi.core.construct import init as init

class BackgroundCheck:
    id: str | None
    package: int | None
    status: int | None
    created_time: str | None
    modified_time: str | None
    target_id: str | None
    outcome: int | None
    report: BackgroundCheckReportObject | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BackgroundCheckBuilder: ...

class BackgroundCheckBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> BackgroundCheckBuilder: ...
    def package(self, package: int) -> BackgroundCheckBuilder: ...
    def status(self, status: int) -> BackgroundCheckBuilder: ...
    def created_time(self, created_time: str) -> BackgroundCheckBuilder: ...
    def modified_time(self, modified_time: str) -> BackgroundCheckBuilder: ...
    def target_id(self, target_id: str) -> BackgroundCheckBuilder: ...
    def outcome(self, outcome: int) -> BackgroundCheckBuilder: ...
    def report(self, report: BackgroundCheckReportObject) -> BackgroundCheckBuilder: ...
    def build(self) -> BackgroundCheck: ...
