from .background_check_city import BackgroundCheckCity as BackgroundCheckCity
from .background_check_country import BackgroundCheckCountry as BackgroundCheckCountry
from lark_oapi.core.construct import init as init

class BackgroundCheckTarget:
    id: str | None
    first_name: str | None
    last_name: str | None
    email: str | None
    work_country: BackgroundCheckCountry | None
    work_city: BackgroundCheckCity | None
    job_title: str | None
    offer_hr_email: str | None
    biz_unit: str | None
    offer_hr_department_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BackgroundCheckTargetBuilder: ...

class BackgroundCheckTargetBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> BackgroundCheckTargetBuilder: ...
    def first_name(self, first_name: str) -> BackgroundCheckTargetBuilder: ...
    def last_name(self, last_name: str) -> BackgroundCheckTargetBuilder: ...
    def email(self, email: str) -> BackgroundCheckTargetBuilder: ...
    def work_country(self, work_country: BackgroundCheckCountry) -> BackgroundCheckTargetBuilder: ...
    def work_city(self, work_city: BackgroundCheckCity) -> BackgroundCheckTargetBuilder: ...
    def job_title(self, job_title: str) -> BackgroundCheckTargetBuilder: ...
    def offer_hr_email(self, offer_hr_email: str) -> BackgroundCheckTargetBuilder: ...
    def biz_unit(self, biz_unit: str) -> BackgroundCheckTargetBuilder: ...
    def offer_hr_department_id(self, offer_hr_department_id: str) -> BackgroundCheckTargetBuilder: ...
    def build(self) -> BackgroundCheckTarget: ...
