from lark_oapi.core.construct import init as init

class BpmFormErrorMessage:
    code: int | None
    message: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BpmFormErrorMessageBuilder: ...

class BpmFormErrorMessageBuilder:
    def __init__(self) -> None: ...
    def code(self, code: int) -> BpmFormErrorMessageBuilder: ...
    def message(self, message: str) -> BpmFormErrorMessageBuilder: ...
    def build(self) -> BpmFormErrorMessage: ...
