from .name import Name as Name
from lark_oapi.core.construct import init as init

class CommonSchemaOption:
    api_name: str | None
    name: Name | None
    description: Name | None
    is_open: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CommonSchemaOptionBuilder: ...

class CommonSchemaOptionBuilder:
    def __init__(self) -> None: ...
    def api_name(self, api_name: str) -> CommonSchemaOptionBuilder: ...
    def name(self, name: Name) -> CommonSchemaOptionBuilder: ...
    def description(self, description: Name) -> CommonSchemaOptionBuilder: ...
    def is_open(self, is_open: bool) -> CommonSchemaOptionBuilder: ...
    def build(self) -> CommonSchemaOption: ...
