from .convert_common_data_id_request_body import ConvertCommonDataIdRequestBody as ConvertCommonDataIdRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ConvertCommonDataIdRequest(BaseRequest):
    id_transform_type: int | None
    id_type: str | None
    feishu_user_id_type: str | None
    feishu_department_id_type: str | None
    request_body: ConvertCommonDataIdRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ConvertCommonDataIdRequestBuilder: ...

class ConvertCommonDataIdRequestBuilder:
    def __init__(self) -> None: ...
    def id_transform_type(self, id_transform_type: int) -> ConvertCommonDataIdRequestBuilder: ...
    def id_type(self, id_type: str) -> ConvertCommonDataIdRequestBuilder: ...
    def feishu_user_id_type(self, feishu_user_id_type: str) -> ConvertCommonDataIdRequestBuilder: ...
    def feishu_department_id_type(self, feishu_department_id_type: str) -> ConvertCommonDataIdRequestBuilder: ...
    def request_body(self, request_body: ConvertCommonDataIdRequestBody) -> ConvertCommonDataIdRequestBuilder: ...
    def build(self) -> ConvertCommonDataIdRequest: ...
