from lark_oapi.core.construct import init as init

class ConvertCommonDataIdRequestBody:
    ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ConvertCommonDataIdRequestBodyBuilder: ...

class ConvertCommonDataIdRequestBodyBuilder:
    def __init__(self) -> None: ...
    def ids(self, ids: list[str]) -> ConvertCommonDataIdRequestBodyBuilder: ...
    def build(self) -> ConvertCommonDataIdRequestBody: ...
