from .i18n import I18n as I18n
from .object_field_data import ObjectFieldData as ObjectFieldData
from .support_cost_center_item import SupportCostCenterItem as SupportCostCenterItem
from lark_oapi.core.construct import init as init

class CostCenter:
    is_autogenerate: bool | None
    id: str | None
    name: list[I18n] | None
    active: bool | None
    code: str | None
    description: list[I18n] | None
    effective_time: str | None
    expiration_time: str | None
    managers: list[str] | None
    parent: str | None
    custom_fields: list[ObjectFieldData] | None
    employment_id: str | None
    rate: int | None
    support_cost_center: list[SupportCostCenterItem] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CostCenterBuilder: ...

class CostCenterBuilder:
    def __init__(self) -> None: ...
    def is_autogenerate(self, is_autogenerate: bool) -> CostCenterBuilder: ...
    def id(self, id: str) -> CostCenterBuilder: ...
    def name(self, name: list[I18n]) -> CostCenterBuilder: ...
    def active(self, active: bool) -> CostCenterBuilder: ...
    def code(self, code: str) -> CostCenterBuilder: ...
    def description(self, description: list[I18n]) -> CostCenterBuilder: ...
    def effective_time(self, effective_time: str) -> CostCenterBuilder: ...
    def expiration_time(self, expiration_time: str) -> CostCenterBuilder: ...
    def managers(self, managers: list[str]) -> CostCenterBuilder: ...
    def parent(self, parent: str) -> CostCenterBuilder: ...
    def custom_fields(self, custom_fields: list[ObjectFieldData]) -> CostCenterBuilder: ...
    def employment_id(self, employment_id: str) -> CostCenterBuilder: ...
    def rate(self, rate: int) -> CostCenterBuilder: ...
    def support_cost_center(self, support_cost_center: list[SupportCostCenterItem]) -> CostCenterBuilder: ...
    def build(self) -> CostCenter: ...
