from .cpst_band_width import CpstBandWidth as CpstBandWidth
from .cpst_standard_type import CpstStandardType as CpstStandardType
from .reference_object import ReferenceObject as ReferenceObject
from lark_oapi.core.construct import init as init

class CpstGradeStandardValue:
    reference_object: ReferenceObject | None
    standard_type: CpstStandardType | None
    band_width: CpstBandWidth | None
    standard_value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CpstGradeStandardValueBuilder: ...

class CpstGradeStandardValueBuilder:
    def __init__(self) -> None: ...
    def reference_object(self, reference_object: ReferenceObject) -> CpstGradeStandardValueBuilder: ...
    def standard_type(self, standard_type: CpstStandardType) -> CpstGradeStandardValueBuilder: ...
    def band_width(self, band_width: CpstBandWidth) -> CpstGradeStandardValueBuilder: ...
    def standard_value(self, standard_value: str) -> CpstGradeStandardValueBuilder: ...
    def build(self) -> CpstGradeStandardValue: ...
