from .cpst_i18n import CpstI18n as CpstI18n
from lark_oapi.core.construct import init as init

class CpstCurrency:
    currency_id: str | None
    code: str | None
    name: CpstI18n | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CpstCurrencyBuilder: ...

class CpstCurrencyBuilder:
    def __init__(self) -> None: ...
    def currency_id(self, currency_id: str) -> CpstCurrencyBuilder: ...
    def code(self, code: str) -> CpstCurrencyBuilder: ...
    def name(self, name: CpstI18n) -> CpstCurrencyBuilder: ...
    def build(self) -> CpstCurrency: ...
