from .cpst_currency import CpstCurrency as CpstCurrency
from .cpst_grade_standard_value import CpstGradeStandardValue as CpstGradeStandardValue
from .cpst_i18n import CpstI18n as CpstI18n
from lark_oapi.core.construct import init as init

class CpstGrade:
    grade_id: str | None
    grade_tid: str | None
    grade_standard_value: CpstGradeStandardValue | None
    currency: CpstCurrency | None
    description: CpstI18n | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CpstGradeBuilder: ...

class CpstGradeBuilder:
    def __init__(self) -> None: ...
    def grade_id(self, grade_id: str) -> CpstGradeBuilder: ...
    def grade_tid(self, grade_tid: str) -> CpstGradeBuilder: ...
    def grade_standard_value(self, grade_standard_value: CpstGradeStandardValue) -> CpstGradeBuilder: ...
    def currency(self, currency: CpstCurrency) -> CpstGradeBuilder: ...
    def description(self, description: CpstI18n) -> CpstGradeBuilder: ...
    def build(self) -> CpstGrade: ...
