from .working_hours_type import WorkingHoursType as WorkingHoursType
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateWorkingHoursTypeRequest(BaseRequest):
    client_token: str | None
    request_body: WorkingHoursType | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateWorkingHoursTypeRequestBuilder: ...

class CreateWorkingHoursTypeRequestBuilder:
    def __init__(self) -> None: ...
    def client_token(self, client_token: str) -> CreateWorkingHoursTypeRequestBuilder: ...
    def request_body(self, request_body: WorkingHoursType) -> CreateWorkingHoursTypeRequestBuilder: ...
    def build(self) -> CreateWorkingHoursTypeRequest: ...
