from .employment_create import EmploymentCreate as EmploymentCreate
from lark_oapi.core.construct import init as init

class CreateEmploymentResponseBody:
    employment: EmploymentCreate | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateEmploymentResponseBodyBuilder: ...

class CreateEmploymentResponseBodyBuilder:
    def __init__(self) -> None: ...
    def employment(self, employment: EmploymentCreate) -> CreateEmploymentResponseBodyBuilder: ...
    def build(self) -> CreateEmploymentResponseBody: ...
