from .job_family import JobFamily as JobFamily
from lark_oapi.core.construct import init as init

class CreateJobFamilyResponseBody:
    job_family: JobFamily | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateJobFamilyResponseBodyBuilder: ...

class CreateJobFamilyResponseBodyBuilder:
    def __init__(self) -> None: ...
    def job_family(self, job_family: JobFamily) -> CreateJobFamilyResponseBodyBuilder: ...
    def build(self) -> CreateJobFamilyResponseBody: ...
