from .employee_type import EmployeeType as EmployeeType
from lark_oapi.core.construct import init as init

class CreateEmployeeTypeResponseBody:
    employee_type: EmployeeType | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateEmployeeTypeResponseBodyBuilder: ...

class CreateEmployeeTypeResponseBodyBuilder:
    def __init__(self) -> None: ...
    def employee_type(self, employee_type: EmployeeType) -> CreateEmployeeTypeResponseBodyBuilder: ...
    def build(self) -> CreateEmployeeTypeResponseBody: ...
