from .job import Job as Job
from lark_oapi.core.construct import init as init

class CreateJobResponseBody:
    job: Job | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateJobResponseBodyBuilder: ...

class CreateJobResponseBodyBuilder:
    def __init__(self) -> None: ...
    def job(self, job: Job) -> CreateJobResponseBodyBuilder: ...
    def build(self) -> CreateJobResponseBody: ...
