from .job_level import JobLevel as JobLevel
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateJobLevelRequest(BaseRequest):
    client_token: str | None
    request_body: JobLevel | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateJobLevelRequestBuilder: ...

class CreateJobLevelRequestBuilder:
    def __init__(self) -> None: ...
    def client_token(self, client_token: str) -> CreateJobLevelRequestBuilder: ...
    def request_body(self, request_body: JobLevel) -> CreateJobLevelRequestBuilder: ...
    def build(self) -> CreateJobLevelRequest: ...
