from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class CreateLeaveGrantingRecordRequestBody:
    leave_type_id: str | None
    employment_id: str | None
    granting_quantity: str | None
    granting_unit: int | None
    effective_date: str | None
    expiration_date: str | None
    section_type: int | None
    reason: list[I18n] | None
    external_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateLeaveGrantingRecordRequestBodyBuilder: ...

class CreateLeaveGrantingRecordRequestBodyBuilder:
    def __init__(self) -> None: ...
    def leave_type_id(self, leave_type_id: str) -> CreateLeaveGrantingRecordRequestBodyBuilder: ...
    def employment_id(self, employment_id: str) -> CreateLeaveGrantingRecordRequestBodyBuilder: ...
    def granting_quantity(self, granting_quantity: str) -> CreateLeaveGrantingRecordRequestBodyBuilder: ...
    def granting_unit(self, granting_unit: int) -> CreateLeaveGrantingRecordRequestBodyBuilder: ...
    def effective_date(self, effective_date: str) -> CreateLeaveGrantingRecordRequestBodyBuilder: ...
    def expiration_date(self, expiration_date: str) -> CreateLeaveGrantingRecordRequestBodyBuilder: ...
    def section_type(self, section_type: int) -> CreateLeaveGrantingRecordRequestBodyBuilder: ...
    def reason(self, reason: list[I18n]) -> CreateLeaveGrantingRecordRequestBodyBuilder: ...
    def external_id(self, external_id: str) -> CreateLeaveGrantingRecordRequestBodyBuilder: ...
    def build(self) -> CreateLeaveGrantingRecordRequestBody: ...
