from .custom_name import CustomName as CustomName
from lark_oapi.core.construct import init as init

class CustomFieldData:
    custom_api_name: str | None
    name: CustomName | None
    type: int | None
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CustomFieldDataBuilder: ...

class CustomFieldDataBuilder:
    def __init__(self) -> None: ...
    def custom_api_name(self, custom_api_name: str) -> CustomFieldDataBuilder: ...
    def name(self, name: CustomName) -> CustomFieldDataBuilder: ...
    def type(self, type: int) -> CustomFieldDataBuilder: ...
    def value(self, value: str) -> CustomFieldDataBuilder: ...
    def build(self) -> CustomFieldData: ...
