from lark_oapi.core.construct import init as init

class DeleteLocationResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteLocationResponseBodyBuilder: ...

class DeleteLocationResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteLocationResponseBody: ...
