from lark_oapi.core.construct import init as init

class DeleteJobResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteJobResponseBodyBuilder: ...

class DeleteJobResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteJobResponseBody: ...
