from lark_oapi.core.construct import init as init

class DeleteJobLevelRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteJobLevelRequestBodyBuilder: ...

class DeleteJobLevelRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteJobLevelRequestBody: ...
