from lark_oapi.core.construct import init as init

class DeleteJobDataResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteJobDataResponseBodyBuilder: ...

class DeleteJobDataResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteJobDataResponseBody: ...
