from lark_oapi.core.construct import init as init

class DeleteEmploymentResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteEmploymentResponseBodyBuilder: ...

class DeleteEmploymentResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteEmploymentResponseBody: ...
