from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeletePersonRequest(BaseRequest):
    person_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeletePersonRequestBuilder: ...

class DeletePersonRequestBuilder:
    def __init__(self) -> None: ...
    def person_id(self, person_id: str) -> DeletePersonRequestBuilder: ...
    def build(self) -> DeletePersonRequest: ...
