from lark_oapi.core.construct import init as init

class DeleteContractRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteContractRequestBodyBuilder: ...

class DeleteContractRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteContractRequestBody: ...
