from lark_oapi.core.construct import init as init

class DeleteEmployeeTypeRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteEmployeeTypeRequestBodyBuilder: ...

class DeleteEmployeeTypeRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteEmployeeTypeRequestBody: ...
