from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteJobRequest(BaseRequest):
    job_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteJobRequestBuilder: ...

class DeleteJobRequestBuilder:
    def __init__(self) -> None: ...
    def job_id(self, job_id: str) -> DeleteJobRequestBuilder: ...
    def build(self) -> DeleteJobRequest: ...
