from lark_oapi.core.construct import init as init

class DeletePreHireResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeletePreHireResponseBodyBuilder: ...

class DeletePreHireResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeletePreHireResponseBody: ...
