from lark_oapi.core.construct import init as init

class DeleteEmploymentRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteEmploymentRequestBodyBuilder: ...

class DeleteEmploymentRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteEmploymentRequestBody: ...
