from lark_oapi.core.construct import init as init

class DimensionValue:
    api_name: str | None
    value_list: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DimensionValueBuilder: ...

class DimensionValueBuilder:
    def __init__(self) -> None: ...
    def api_name(self, api_name: str) -> DimensionValueBuilder: ...
    def value_list(self, value_list: list[str]) -> DimensionValueBuilder: ...
    def build(self) -> DimensionValue: ...
