from .enum import Enum as Enum
from .object_field_data import ObjectFieldData as ObjectFieldData
from lark_oapi.core.construct import init as init

class Email:
    email: str | None
    is_primary: bool | None
    is_public: bool | None
    email_usage: Enum | None
    custom_fields: list[ObjectFieldData] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EmailBuilder: ...

class EmailBuilder:
    def __init__(self) -> None: ...
    def email(self, email: str) -> EmailBuilder: ...
    def is_primary(self, is_primary: bool) -> EmailBuilder: ...
    def is_public(self, is_public: bool) -> EmailBuilder: ...
    def email_usage(self, email_usage: Enum) -> EmailBuilder: ...
    def custom_fields(self, custom_fields: list[ObjectFieldData]) -> EmailBuilder: ...
    def build(self) -> Email: ...
