from .cost_center import CostCenter as CostCenter
from lark_oapi.core.construct import init as init

class EmploymentCostCenter:
    employment_id: str | None
    cost_center: list[CostCenter] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EmploymentCostCenterBuilder: ...

class EmploymentCostCenterBuilder:
    def __init__(self) -> None: ...
    def employment_id(self, employment_id: str) -> EmploymentCostCenterBuilder: ...
    def cost_center(self, cost_center: list[CostCenter]) -> EmploymentCostCenterBuilder: ...
    def build(self) -> EmploymentCostCenter: ...
