from .bpm_dataengine_i18n import BpmDataengineI18n as BpmDataengineI18n
from .form_variable_value_info import FormVariableValueInfo as FormVariableValueInfo
from lark_oapi.core.construct import init as init

class FormFieldVariable:
    variable_api_name: str | None
    variable_name: BpmDataengineI18n | None
    variable_value: FormVariableValueInfo | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FormFieldVariableBuilder: ...

class FormFieldVariableBuilder:
    def __init__(self) -> None: ...
    def variable_api_name(self, variable_api_name: str) -> FormFieldVariableBuilder: ...
    def variable_name(self, variable_name: BpmDataengineI18n) -> FormFieldVariableBuilder: ...
    def variable_value(self, variable_value: FormVariableValueInfo) -> FormFieldVariableBuilder: ...
    def build(self) -> FormFieldVariable: ...
