from lark_oapi.core.construct import init as init

class FormFieldVariableTextValue:
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FormFieldVariableTextValueBuilder: ...

class FormFieldVariableTextValueBuilder:
    def __init__(self) -> None: ...
    def value(self, value: str) -> FormFieldVariableTextValueBuilder: ...
    def build(self) -> FormFieldVariableTextValue: ...
