from lark_oapi.core.construct import init as init

class FormFieldVariableDateValue:
    value: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> FormFieldVariableDateValueBuilder: ...

class FormFieldVariableDateValueBuilder:
    def __init__(self) -> None: ...
    def value(self, value: int) -> FormFieldVariableDateValueBuilder: ...
    def build(self) -> FormFieldVariableDateValue: ...
