from lark_oapi.core.construct import init as init

class GetWorkingHoursTypeRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetWorkingHoursTypeRequestBodyBuilder: ...

class GetWorkingHoursTypeRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetWorkingHoursTypeRequestBody: ...
