from .role_authorization import RoleAuthorization as RoleAuthorization
from lark_oapi.core.construct import init as init

class GetByParamAuthorizationResponseBody:
    role_authorization: RoleAuthorization | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetByParamAuthorizationResponseBodyBuilder: ...

class GetByParamAuthorizationResponseBodyBuilder:
    def __init__(self) -> None: ...
    def role_authorization(self, role_authorization: RoleAuthorization) -> GetByParamAuthorizationResponseBodyBuilder: ...
    def build(self) -> GetByParamAuthorizationResponseBody: ...
