from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetNationalIdTypeRequest(BaseRequest):
    national_id_type_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetNationalIdTypeRequestBuilder: ...

class GetNationalIdTypeRequestBuilder:
    def __init__(self) -> None: ...
    def national_id_type_id(self, national_id_type_id: str) -> GetNationalIdTypeRequestBuilder: ...
    def build(self) -> GetNationalIdTypeRequest: ...
