from .contract import Contract as Contract
from lark_oapi.core.construct import init as init

class GetContractResponseBody:
    contract: Contract | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetContractResponseBodyBuilder: ...

class GetContractResponseBodyBuilder:
    def __init__(self) -> None: ...
    def contract(self, contract: Contract) -> GetContractResponseBodyBuilder: ...
    def build(self) -> GetContractResponseBody: ...
