from .subregion import Subregion as Subregion
from lark_oapi.core.construct import init as init

class GetSubregionResponseBody:
    subregion: Subregion | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetSubregionResponseBodyBuilder: ...

class GetSubregionResponseBodyBuilder:
    def __init__(self) -> None: ...
    def subregion(self, subregion: Subregion) -> GetSubregionResponseBodyBuilder: ...
    def build(self) -> GetSubregionResponseBody: ...
