from lark_oapi.core.construct import init as init

class GetFileResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetFileResponseBodyBuilder: ...

class GetFileResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetFileResponseBody: ...
