from lark_oapi.core.construct import init as init

class GetSubdivisionRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetSubdivisionRequestBodyBuilder: ...

class GetSubdivisionRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetSubdivisionRequestBody: ...
