from lark_oapi.core.construct import init as init

class GetCompanyRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetCompanyRequestBodyBuilder: ...

class GetCompanyRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetCompanyRequestBody: ...
