from .working_hours_type import WorkingHoursType as WorkingHoursType
from lark_oapi.core.construct import init as init

class GetWorkingHoursTypeResponseBody:
    working_hours_type: WorkingHoursType | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetWorkingHoursTypeResponseBodyBuilder: ...

class GetWorkingHoursTypeResponseBodyBuilder:
    def __init__(self) -> None: ...
    def working_hours_type(self, working_hours_type: WorkingHoursType) -> GetWorkingHoursTypeResponseBodyBuilder: ...
    def build(self) -> GetWorkingHoursTypeResponseBody: ...
