from .country_region import CountryRegion as CountryRegion
from lark_oapi.core.construct import init as init

class GetCountryRegionResponseBody:
    country_region: CountryRegion | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetCountryRegionResponseBodyBuilder: ...

class GetCountryRegionResponseBodyBuilder:
    def __init__(self) -> None: ...
    def country_region(self, country_region: CountryRegion) -> GetCountryRegionResponseBodyBuilder: ...
    def build(self) -> GetCountryRegionResponseBody: ...
