from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetByParamCustomFieldRequest(BaseRequest):
    object_api_name: str | None
    custom_api_name: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetByParamCustomFieldRequestBuilder: ...

class GetByParamCustomFieldRequestBuilder:
    def __init__(self) -> None: ...
    def object_api_name(self, object_api_name: str) -> GetByParamCustomFieldRequestBuilder: ...
    def custom_api_name(self, custom_api_name: str) -> GetByParamCustomFieldRequestBuilder: ...
    def build(self) -> GetByParamCustomFieldRequest: ...
