from lark_oapi.core.construct import init as init

class GetEmployeeTypeRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetEmployeeTypeRequestBodyBuilder: ...

class GetEmployeeTypeRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetEmployeeTypeRequestBody: ...
