from .currency import Currency as Currency
from lark_oapi.core.construct import init as init

class GetCurrencyResponseBody:
    currency: Currency | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetCurrencyResponseBodyBuilder: ...

class GetCurrencyResponseBodyBuilder:
    def __init__(self) -> None: ...
    def currency(self, currency: Currency) -> GetCurrencyResponseBodyBuilder: ...
    def build(self) -> GetCurrencyResponseBody: ...
