from .location import Location as Location
from lark_oapi.core.construct import init as init

class GetLocationResponseBody:
    location: Location | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetLocationResponseBodyBuilder: ...

class GetLocationResponseBodyBuilder:
    def __init__(self) -> None: ...
    def location(self, location: Location) -> GetLocationResponseBodyBuilder: ...
    def build(self) -> GetLocationResponseBody: ...
