from lark_oapi.core.construct import init as init

class GetByParamAuthorizationRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetByParamAuthorizationRequestBodyBuilder: ...

class GetByParamAuthorizationRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetByParamAuthorizationRequestBody: ...
