from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetCountryRegionRequest(BaseRequest):
    country_region_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetCountryRegionRequestBuilder: ...

class GetCountryRegionRequestBuilder:
    def __init__(self) -> None: ...
    def country_region_id(self, country_region_id: str) -> GetCountryRegionRequestBuilder: ...
    def build(self) -> GetCountryRegionRequest: ...
