from lark_oapi.core.construct import init as init

class GetNationalIdTypeRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetNationalIdTypeRequestBodyBuilder: ...

class GetNationalIdTypeRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetNationalIdTypeRequestBody: ...
