from lark_oapi.core.construct import init as init

class GetSubregionRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetSubregionRequestBodyBuilder: ...

class GetSubregionRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetSubregionRequestBody: ...
