from lark_oapi.core.construct import init as init

class GetCurrencyRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetCurrencyRequestBodyBuilder: ...

class GetCurrencyRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetCurrencyRequestBody: ...
