from lark_oapi.core.construct import init as init

class GetJobFamilyRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetJobFamilyRequestBodyBuilder: ...

class GetJobFamilyRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetJobFamilyRequestBody: ...
