from .enum import Enum as Enum
from .object_field_data import ObjectFieldData as ObjectFieldData
from .support_cost_center_item import SupportCostCenterItem as SupportCostCenterItem
from lark_oapi.core.construct import init as init

class JobData:
    id: str | None
    version_id: str | None
    job_level_id: str | None
    job_grade_id: str | None
    employee_type_id: str | None
    working_hours_type_id: str | None
    work_location_id: str | None
    department_id: str | None
    job_id: str | None
    probation_start_date: str | None
    probation_end_date: str | None
    primary_job_data: bool | None
    employment_id: str | None
    effective_time: str | None
    expiration_time: str | None
    job_family_id: str | None
    assignment_start_reason: Enum | None
    probation_expected_end_date: str | None
    probation_outcome: Enum | None
    weekly_working_hours: int | None
    direct_manager_id: str | None
    dotted_line_manager_id_list: list[str] | None
    second_direct_manager_id: str | None
    cost_center_rate: list[SupportCostCenterItem] | None
    custom_fields: list[ObjectFieldData] | None
    weekly_working_hours_v2: float | None
    work_shift: Enum | None
    compensation_type: Enum | None
    service_company: str | None
    employee_subtype_id: str | None
    position_id: str | None
    pathway_id: str | None
    job_data_reason: Enum | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobDataBuilder: ...

class JobDataBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> JobDataBuilder: ...
    def version_id(self, version_id: str) -> JobDataBuilder: ...
    def job_level_id(self, job_level_id: str) -> JobDataBuilder: ...
    def job_grade_id(self, job_grade_id: str) -> JobDataBuilder: ...
    def employee_type_id(self, employee_type_id: str) -> JobDataBuilder: ...
    def working_hours_type_id(self, working_hours_type_id: str) -> JobDataBuilder: ...
    def work_location_id(self, work_location_id: str) -> JobDataBuilder: ...
    def department_id(self, department_id: str) -> JobDataBuilder: ...
    def job_id(self, job_id: str) -> JobDataBuilder: ...
    def probation_start_date(self, probation_start_date: str) -> JobDataBuilder: ...
    def probation_end_date(self, probation_end_date: str) -> JobDataBuilder: ...
    def primary_job_data(self, primary_job_data: bool) -> JobDataBuilder: ...
    def employment_id(self, employment_id: str) -> JobDataBuilder: ...
    def effective_time(self, effective_time: str) -> JobDataBuilder: ...
    def expiration_time(self, expiration_time: str) -> JobDataBuilder: ...
    def job_family_id(self, job_family_id: str) -> JobDataBuilder: ...
    def assignment_start_reason(self, assignment_start_reason: Enum) -> JobDataBuilder: ...
    def probation_expected_end_date(self, probation_expected_end_date: str) -> JobDataBuilder: ...
    def probation_outcome(self, probation_outcome: Enum) -> JobDataBuilder: ...
    def weekly_working_hours(self, weekly_working_hours: int) -> JobDataBuilder: ...
    def direct_manager_id(self, direct_manager_id: str) -> JobDataBuilder: ...
    def dotted_line_manager_id_list(self, dotted_line_manager_id_list: list[str]) -> JobDataBuilder: ...
    def second_direct_manager_id(self, second_direct_manager_id: str) -> JobDataBuilder: ...
    def cost_center_rate(self, cost_center_rate: list[SupportCostCenterItem]) -> JobDataBuilder: ...
    def custom_fields(self, custom_fields: list[ObjectFieldData]) -> JobDataBuilder: ...
    def weekly_working_hours_v2(self, weekly_working_hours_v2: float) -> JobDataBuilder: ...
    def work_shift(self, work_shift: Enum) -> JobDataBuilder: ...
    def compensation_type(self, compensation_type: Enum) -> JobDataBuilder: ...
    def service_company(self, service_company: str) -> JobDataBuilder: ...
    def employee_subtype_id(self, employee_subtype_id: str) -> JobDataBuilder: ...
    def position_id(self, position_id: str) -> JobDataBuilder: ...
    def pathway_id(self, pathway_id: str) -> JobDataBuilder: ...
    def job_data_reason(self, job_data_reason: Enum) -> JobDataBuilder: ...
    def build(self) -> JobData: ...
