from lark_oapi.core.construct import init as init

class JobCategory:
    id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobCategoryBuilder: ...

class JobCategoryBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> JobCategoryBuilder: ...
    def build(self) -> JobCategory: ...
