from .i18n import I18n as I18n
from .object_field_data import ObjectFieldData as ObjectFieldData
from lark_oapi.core.construct import init as init

class JobFamily:
    id: str | None
    name: list[I18n] | None
    active: bool | None
    selectable: bool | None
    parent_id: str | None
    pathway_ids: list[str] | None
    effective_time: str | None
    expiration_time: str | None
    code: str | None
    description: list[I18n] | None
    custom_fields: list[ObjectFieldData] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobFamilyBuilder: ...

class JobFamilyBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> JobFamilyBuilder: ...
    def name(self, name: list[I18n]) -> JobFamilyBuilder: ...
    def active(self, active: bool) -> JobFamilyBuilder: ...
    def selectable(self, selectable: bool) -> JobFamilyBuilder: ...
    def parent_id(self, parent_id: str) -> JobFamilyBuilder: ...
    def pathway_ids(self, pathway_ids: list[str]) -> JobFamilyBuilder: ...
    def effective_time(self, effective_time: str) -> JobFamilyBuilder: ...
    def expiration_time(self, expiration_time: str) -> JobFamilyBuilder: ...
    def code(self, code: str) -> JobFamilyBuilder: ...
    def description(self, description: list[I18n]) -> JobFamilyBuilder: ...
    def custom_fields(self, custom_fields: list[ObjectFieldData]) -> JobFamilyBuilder: ...
    def build(self) -> JobFamily: ...
