from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class LeaveTypesLeaveRequest(BaseRequest):
    page_token: str | None
    page_size: str | None
    status: str | None
    user_id_type: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> LeaveTypesLeaveRequestBuilder: ...

class LeaveTypesLeaveRequestBuilder:
    def __init__(self) -> None: ...
    def page_token(self, page_token: str) -> LeaveTypesLeaveRequestBuilder: ...
    def page_size(self, page_size: str) -> LeaveTypesLeaveRequestBuilder: ...
    def status(self, status: str) -> LeaveTypesLeaveRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> LeaveTypesLeaveRequestBuilder: ...
    def build(self) -> LeaveTypesLeaveRequest: ...
