from lark_oapi.core.construct import init as init

class LeaveDuration:
    duration: str | None
    unit: str | None
    duration_per_day: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LeaveDurationBuilder: ...

class LeaveDurationBuilder:
    def __init__(self) -> None: ...
    def duration(self, duration: str) -> LeaveDurationBuilder: ...
    def unit(self, unit: str) -> LeaveDurationBuilder: ...
    def duration_per_day(self, duration_per_day: str) -> LeaveDurationBuilder: ...
    def build(self) -> LeaveDuration: ...
