from .leave_type import LeaveType as LeaveType
from lark_oapi.core.construct import init as init

class LeaveTypesLeaveResponseBody:
    leave_type_list: list[LeaveType] | None
    has_more: bool | None
    page_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LeaveTypesLeaveResponseBodyBuilder: ...

class LeaveTypesLeaveResponseBodyBuilder:
    def __init__(self) -> None: ...
    def leave_type_list(self, leave_type_list: list[LeaveType]) -> LeaveTypesLeaveResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> LeaveTypesLeaveResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> LeaveTypesLeaveResponseBodyBuilder: ...
    def build(self) -> LeaveTypesLeaveResponseBody: ...
