from lark_oapi.core.construct import init as init

class LeaveTime:
    date: str | None
    time: str | None
    half_day: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LeaveTimeBuilder: ...

class LeaveTimeBuilder:
    def __init__(self) -> None: ...
    def date(self, date: str) -> LeaveTimeBuilder: ...
    def time(self, time: str) -> LeaveTimeBuilder: ...
    def half_day(self, half_day: str) -> LeaveTimeBuilder: ...
    def build(self) -> LeaveTime: ...
