from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class LeaveRequestHistoryLeaveRequest(BaseRequest):
    page_token: str | None
    page_size: str | None
    employment_id_list: list[str] | None
    initiator_id_list: list[str] | None
    leave_request_status: list[str] | None
    leave_type_id_list: list[str] | None
    leave_start_date_min: str | None
    leave_start_date_max: str | None
    leave_end_date_min: str | None
    leave_end_date_max: str | None
    leave_submit_date_min: str | None
    leave_submit_date_max: str | None
    user_id_type: str | None
    leave_update_time_min: str | None
    leave_update_time_max: str | None
    return_detail: bool | None
    leave_term_type: int | None
    time_zone: str | None
    data_source: int | None
    db_update_time_min: str | None
    db_update_time_max: str | None
    wd_need_amount_zero_records: bool | None
    wd_need_denied_and_canceled_record: bool | None
    wd_paid_type: int | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> LeaveRequestHistoryLeaveRequestBuilder: ...

class LeaveRequestHistoryLeaveRequestBuilder:
    def __init__(self) -> None: ...
    def page_token(self, page_token: str) -> LeaveRequestHistoryLeaveRequestBuilder: ...
    def page_size(self, page_size: str) -> LeaveRequestHistoryLeaveRequestBuilder: ...
    def employment_id_list(self, employment_id_list: list[str]) -> LeaveRequestHistoryLeaveRequestBuilder: ...
    def initiator_id_list(self, initiator_id_list: list[str]) -> LeaveRequestHistoryLeaveRequestBuilder: ...
    def leave_request_status(self, leave_request_status: list[str]) -> LeaveRequestHistoryLeaveRequestBuilder: ...
    def leave_type_id_list(self, leave_type_id_list: list[str]) -> LeaveRequestHistoryLeaveRequestBuilder: ...
    def leave_start_date_min(self, leave_start_date_min: str) -> LeaveRequestHistoryLeaveRequestBuilder: ...
    def leave_start_date_max(self, leave_start_date_max: str) -> LeaveRequestHistoryLeaveRequestBuilder: ...
    def leave_end_date_min(self, leave_end_date_min: str) -> LeaveRequestHistoryLeaveRequestBuilder: ...
    def leave_end_date_max(self, leave_end_date_max: str) -> LeaveRequestHistoryLeaveRequestBuilder: ...
    def leave_submit_date_min(self, leave_submit_date_min: str) -> LeaveRequestHistoryLeaveRequestBuilder: ...
    def leave_submit_date_max(self, leave_submit_date_max: str) -> LeaveRequestHistoryLeaveRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> LeaveRequestHistoryLeaveRequestBuilder: ...
    def leave_update_time_min(self, leave_update_time_min: str) -> LeaveRequestHistoryLeaveRequestBuilder: ...
    def leave_update_time_max(self, leave_update_time_max: str) -> LeaveRequestHistoryLeaveRequestBuilder: ...
    def return_detail(self, return_detail: bool) -> LeaveRequestHistoryLeaveRequestBuilder: ...
    def leave_term_type(self, leave_term_type: int) -> LeaveRequestHistoryLeaveRequestBuilder: ...
    def time_zone(self, time_zone: str) -> LeaveRequestHistoryLeaveRequestBuilder: ...
    def data_source(self, data_source: int) -> LeaveRequestHistoryLeaveRequestBuilder: ...
    def db_update_time_min(self, db_update_time_min: str) -> LeaveRequestHistoryLeaveRequestBuilder: ...
    def db_update_time_max(self, db_update_time_max: str) -> LeaveRequestHistoryLeaveRequestBuilder: ...
    def wd_need_amount_zero_records(self, wd_need_amount_zero_records: bool) -> LeaveRequestHistoryLeaveRequestBuilder: ...
    def wd_need_denied_and_canceled_record(self, wd_need_denied_and_canceled_record: bool) -> LeaveRequestHistoryLeaveRequestBuilder: ...
    def wd_paid_type(self, wd_paid_type: int) -> LeaveRequestHistoryLeaveRequestBuilder: ...
    def build(self) -> LeaveRequestHistoryLeaveRequest: ...
