from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class LeaveSubtype:
    leave_type_id: str | None
    leave_type_name: list[I18n] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LeaveSubtypeBuilder: ...

class LeaveSubtypeBuilder:
    def __init__(self) -> None: ...
    def leave_type_id(self, leave_type_id: str) -> LeaveSubtypeBuilder: ...
    def leave_type_name(self, leave_type_name: list[I18n]) -> LeaveSubtypeBuilder: ...
    def build(self) -> LeaveSubtype: ...
