from .security_group import SecurityGroup as SecurityGroup
from lark_oapi.core.construct import init as init

class ListSecurityGroupResponseBody:
    items: list[SecurityGroup] | None
    has_more: bool | None
    page_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListSecurityGroupResponseBodyBuilder: ...

class ListSecurityGroupResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[SecurityGroup]) -> ListSecurityGroupResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListSecurityGroupResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListSecurityGroupResponseBodyBuilder: ...
    def build(self) -> ListSecurityGroupResponseBody: ...
