from .job_level import JobLevel as JobLevel
from lark_oapi.core.construct import init as init

class ListJobLevelResponseBody:
    items: list[JobLevel] | None
    has_more: bool | None
    page_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListJobLevelResponseBodyBuilder: ...

class ListJobLevelResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[JobLevel]) -> ListJobLevelResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListJobLevelResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListJobLevelResponseBodyBuilder: ...
    def build(self) -> ListJobLevelResponseBody: ...
