from lark_oapi.core.construct import init as init

class ListCurrencyRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListCurrencyRequestBodyBuilder: ...

class ListCurrencyRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListCurrencyRequestBody: ...
