from lark_oapi.core.construct import init as init

class ListSubregionRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListSubregionRequestBodyBuilder: ...

class ListSubregionRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListSubregionRequestBody: ...
