from lark_oapi.core.construct import init as init

class ListNationalIdTypeRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListNationalIdTypeRequestBodyBuilder: ...

class ListNationalIdTypeRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListNationalIdTypeRequestBody: ...
