from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListSubregionRequest(BaseRequest):
    page_token: str | None
    page_size: str | None
    subdivision_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListSubregionRequestBuilder: ...

class ListSubregionRequestBuilder:
    def __init__(self) -> None: ...
    def page_token(self, page_token: str) -> ListSubregionRequestBuilder: ...
    def page_size(self, page_size: str) -> ListSubregionRequestBuilder: ...
    def subdivision_id(self, subdivision_id: str) -> ListSubregionRequestBuilder: ...
    def build(self) -> ListSubregionRequest: ...
