from lark_oapi.core.construct import init as init

class ListWorkingHoursTypeRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListWorkingHoursTypeRequestBodyBuilder: ...

class ListWorkingHoursTypeRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListWorkingHoursTypeRequestBody: ...
