from .department import Department as Department
from lark_oapi.core.construct import init as init

class ListDepartmentResponseBody:
    items: list[Department] | None
    has_more: bool | None
    page_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListDepartmentResponseBodyBuilder: ...

class ListDepartmentResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[Department]) -> ListDepartmentResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListDepartmentResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListDepartmentResponseBodyBuilder: ...
    def build(self) -> ListDepartmentResponseBody: ...
