from lark_oapi.core.construct import init as init

class ListEmployeeTypeRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListEmployeeTypeRequestBodyBuilder: ...

class ListEmployeeTypeRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListEmployeeTypeRequestBody: ...
