from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListPreHireRequest(BaseRequest):
    page_token: str | None
    page_size: str | None
    pre_hire_ids: list[str] | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListPreHireRequestBuilder: ...

class ListPreHireRequestBuilder:
    def __init__(self) -> None: ...
    def page_token(self, page_token: str) -> ListPreHireRequestBuilder: ...
    def page_size(self, page_size: str) -> ListPreHireRequestBuilder: ...
    def pre_hire_ids(self, pre_hire_ids: list[str]) -> ListPreHireRequestBuilder: ...
    def build(self) -> ListPreHireRequest: ...
