from .employee_type import EmployeeType as EmployeeType
from lark_oapi.core.construct import init as init

class ListEmployeeTypeResponseBody:
    items: list[EmployeeType] | None
    has_more: bool | None
    page_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListEmployeeTypeResponseBodyBuilder: ...

class ListEmployeeTypeResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[EmployeeType]) -> ListEmployeeTypeResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListEmployeeTypeResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListEmployeeTypeResponseBodyBuilder: ...
    def build(self) -> ListEmployeeTypeResponseBody: ...
