from lark_oapi.core.construct import init as init

class ListCountryRegionRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListCountryRegionRequestBodyBuilder: ...

class ListCountryRegionRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListCountryRegionRequestBody: ...
