from lark_oapi.core.construct import init as init

class LookupFieldSetting:
    lookup_obj_api_name: str | None
    is_multiple: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LookupFieldSettingBuilder: ...

class LookupFieldSettingBuilder:
    def __init__(self) -> None: ...
    def lookup_obj_api_name(self, lookup_obj_api_name: str) -> LookupFieldSettingBuilder: ...
    def is_multiple(self, is_multiple: bool) -> LookupFieldSettingBuilder: ...
    def build(self) -> LookupFieldSetting: ...
