from .cpst_grade import CpstGrade as CpstGrade
from lark_oapi.core.construct import init as init

class MatchCompensationStandardResponseBody:
    standard_id: str | None
    grade: CpstGrade | None
    effective_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MatchCompensationStandardResponseBodyBuilder: ...

class MatchCompensationStandardResponseBodyBuilder:
    def __init__(self) -> None: ...
    def standard_id(self, standard_id: str) -> MatchCompensationStandardResponseBodyBuilder: ...
    def grade(self, grade: CpstGrade) -> MatchCompensationStandardResponseBodyBuilder: ...
    def effective_time(self, effective_time: str) -> MatchCompensationStandardResponseBodyBuilder: ...
    def build(self) -> MatchCompensationStandardResponseBody: ...
