from lark_oapi.core.construct import init as init

class MatchCompensationStandardRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MatchCompensationStandardRequestBodyBuilder: ...

class MatchCompensationStandardRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> MatchCompensationStandardRequestBody: ...
