from lark_oapi.core.construct import init as init

class Name:
    zh_cn: str | None
    en_us: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> NameBuilder: ...

class NameBuilder:
    def __init__(self) -> None: ...
    def zh_cn(self, zh_cn: str) -> NameBuilder: ...
    def en_us(self, en_us: str) -> NameBuilder: ...
    def build(self) -> Name: ...
