from .name import Name as Name
from lark_oapi.core.construct import init as init

class Object:
    object_api_name: str | None
    name: Name | None
    is_open: bool | None
    create_time: str | None
    update_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ObjectBuilder: ...

class ObjectBuilder:
    def __init__(self) -> None: ...
    def object_api_name(self, object_api_name: str) -> ObjectBuilder: ...
    def name(self, name: Name) -> ObjectBuilder: ...
    def is_open(self, is_open: bool) -> ObjectBuilder: ...
    def create_time(self, create_time: str) -> ObjectBuilder: ...
    def update_time(self, update_time: str) -> ObjectBuilder: ...
    def build(self) -> Object: ...
