from lark_oapi.core.construct import init as init

class OffboardingChecklist:
    checklist_status: str | None
    checklist_start_time: str | None
    checklist_finish_time: str | None
    checklist_process_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OffboardingChecklistBuilder: ...

class OffboardingChecklistBuilder:
    def __init__(self) -> None: ...
    def checklist_status(self, checklist_status: str) -> OffboardingChecklistBuilder: ...
    def checklist_start_time(self, checklist_start_time: str) -> OffboardingChecklistBuilder: ...
    def checklist_finish_time(self, checklist_finish_time: str) -> OffboardingChecklistBuilder: ...
    def checklist_process_id(self, checklist_process_id: str) -> OffboardingChecklistBuilder: ...
    def build(self) -> OffboardingChecklist: ...
