from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class OffboardingReason:
    offboarding_reason_unique_identifier: str | None
    name: list[I18n] | None
    active: bool | None
    parent_offboarding_reason_unique_identifier: str | None
    created_time: str | None
    updated_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OffboardingReasonBuilder: ...

class OffboardingReasonBuilder:
    def __init__(self) -> None: ...
    def offboarding_reason_unique_identifier(self, offboarding_reason_unique_identifier: str) -> OffboardingReasonBuilder: ...
    def name(self, name: list[I18n]) -> OffboardingReasonBuilder: ...
    def active(self, active: bool) -> OffboardingReasonBuilder: ...
    def parent_offboarding_reason_unique_identifier(self, parent_offboarding_reason_unique_identifier: str) -> OffboardingReasonBuilder: ...
    def created_time(self, created_time: str) -> OffboardingReasonBuilder: ...
    def updated_time(self, updated_time: str) -> OffboardingReasonBuilder: ...
    def build(self) -> OffboardingReason: ...
