from lark_oapi.core.construct import init as init

class OrgTruncation:
    org_key: str | None
    type: int | None
    depth: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OrgTruncationBuilder: ...

class OrgTruncationBuilder:
    def __init__(self) -> None: ...
    def org_key(self, org_key: str) -> OrgTruncationBuilder: ...
    def type(self, type: int) -> OrgTruncationBuilder: ...
    def depth(self, depth: int) -> OrgTruncationBuilder: ...
    def build(self) -> OrgTruncation: ...
