from .working_hours_type import WorkingHoursType as WorkingHoursType
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PatchWorkingHoursTypeRequest(BaseRequest):
    client_token: str | None
    working_hours_type_id: str | None
    request_body: WorkingHoursType | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PatchWorkingHoursTypeRequestBuilder: ...

class PatchWorkingHoursTypeRequestBuilder:
    def __init__(self) -> None: ...
    def client_token(self, client_token: str) -> PatchWorkingHoursTypeRequestBuilder: ...
    def working_hours_type_id(self, working_hours_type_id: str) -> PatchWorkingHoursTypeRequestBuilder: ...
    def request_body(self, request_body: WorkingHoursType) -> PatchWorkingHoursTypeRequestBuilder: ...
    def build(self) -> PatchWorkingHoursTypeRequest: ...
