from .job import Job as Job
from lark_oapi.core.construct import init as init

class PatchJobResponseBody:
    job: Job | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchJobResponseBodyBuilder: ...

class PatchJobResponseBodyBuilder:
    def __init__(self) -> None: ...
    def job(self, job: Job) -> PatchJobResponseBodyBuilder: ...
    def build(self) -> PatchJobResponseBody: ...
