from .employment import Employment as Employment
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PatchEmploymentRequest(BaseRequest):
    client_token: str | None
    user_id_type: str | None
    department_id_type: str | None
    employment_id: str | None
    request_body: Employment | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PatchEmploymentRequestBuilder: ...

class PatchEmploymentRequestBuilder:
    def __init__(self) -> None: ...
    def client_token(self, client_token: str) -> PatchEmploymentRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> PatchEmploymentRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> PatchEmploymentRequestBuilder: ...
    def employment_id(self, employment_id: str) -> PatchEmploymentRequestBuilder: ...
    def request_body(self, request_body: Employment) -> PatchEmploymentRequestBuilder: ...
    def build(self) -> PatchEmploymentRequest: ...
