from .national_id_type import NationalIdType as NationalIdType
from lark_oapi.core.construct import init as init

class PatchNationalIdTypeResponseBody:
    national_id_type: NationalIdType | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchNationalIdTypeResponseBodyBuilder: ...

class PatchNationalIdTypeResponseBodyBuilder:
    def __init__(self) -> None: ...
    def national_id_type(self, national_id_type: NationalIdType) -> PatchNationalIdTypeResponseBodyBuilder: ...
    def build(self) -> PatchNationalIdTypeResponseBody: ...
