from .job import Job as Job
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PatchJobRequest(BaseRequest):
    client_token: str | None
    job_id: str | None
    request_body: Job | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PatchJobRequestBuilder: ...

class PatchJobRequestBuilder:
    def __init__(self) -> None: ...
    def client_token(self, client_token: str) -> PatchJobRequestBuilder: ...
    def job_id(self, job_id: str) -> PatchJobRequestBuilder: ...
    def request_body(self, request_body: Job) -> PatchJobRequestBuilder: ...
    def build(self) -> PatchJobRequest: ...
