from .company import Company as Company
from lark_oapi.core.construct import init as init

class PatchCompanyResponseBody:
    company: Company | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchCompanyResponseBodyBuilder: ...

class PatchCompanyResponseBodyBuilder:
    def __init__(self) -> None: ...
    def company(self, company: Company) -> PatchCompanyResponseBodyBuilder: ...
    def build(self) -> PatchCompanyResponseBody: ...
