from .employment import Employment as Employment
from lark_oapi.core.construct import init as init

class PatchEmploymentResponseBody:
    employment: Employment | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchEmploymentResponseBodyBuilder: ...

class PatchEmploymentResponseBodyBuilder:
    def __init__(self) -> None: ...
    def employment(self, employment: Employment) -> PatchEmploymentResponseBodyBuilder: ...
    def build(self) -> PatchEmploymentResponseBody: ...
