from .enum import Enum as Enum
from .object_field_data import ObjectFieldData as ObjectFieldData
from lark_oapi.core.construct import init as init

class PersonInfoChn:
    id: str | None
    native_region: str | None
    political_affiliation_list: list[Enum] | None
    hukou_type: Enum | None
    hukou_location: str | None
    person_id: str | None
    custom_fields: list[ObjectFieldData] | None
    working_years: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PersonInfoChnBuilder: ...

class PersonInfoChnBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> PersonInfoChnBuilder: ...
    def native_region(self, native_region: str) -> PersonInfoChnBuilder: ...
    def political_affiliation_list(self, political_affiliation_list: list[Enum]) -> PersonInfoChnBuilder: ...
    def hukou_type(self, hukou_type: Enum) -> PersonInfoChnBuilder: ...
    def hukou_location(self, hukou_location: str) -> PersonInfoChnBuilder: ...
    def person_id(self, person_id: str) -> PersonInfoChnBuilder: ...
    def custom_fields(self, custom_fields: list[ObjectFieldData]) -> PersonInfoChnBuilder: ...
    def working_years(self, working_years: int) -> PersonInfoChnBuilder: ...
    def build(self) -> PersonInfoChn: ...
