from .object_field_data import ObjectFieldData as ObjectFieldData
from lark_oapi.core.construct import init as init

class PreviousEmployer:
    id: str | None
    employer_name: str | None
    employer_reference_number: str | None
    employment_order: int | None
    custom_fields: list[ObjectFieldData] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PreviousEmployerBuilder: ...

class PreviousEmployerBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> PreviousEmployerBuilder: ...
    def employer_name(self, employer_name: str) -> PreviousEmployerBuilder: ...
    def employer_reference_number(self, employer_reference_number: str) -> PreviousEmployerBuilder: ...
    def employment_order(self, employment_order: int) -> PreviousEmployerBuilder: ...
    def custom_fields(self, custom_fields: list[ObjectFieldData]) -> PreviousEmployerBuilder: ...
    def build(self) -> PreviousEmployer: ...
