from .hrbp import Hrbp as Hrbp
from lark_oapi.core.construct import init as init

class QuerySecurityGroupResponseBody:
    hrbp_list: list[Hrbp] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QuerySecurityGroupResponseBodyBuilder: ...

class QuerySecurityGroupResponseBodyBuilder:
    def __init__(self) -> None: ...
    def hrbp_list(self, hrbp_list: list[Hrbp]) -> QuerySecurityGroupResponseBodyBuilder: ...
    def build(self) -> QuerySecurityGroupResponseBody: ...
