from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class QueryTransferReasonRequest(BaseRequest):
    active: bool | None
    transfer_reason_unique_identifier: list[str] | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> QueryTransferReasonRequestBuilder: ...

class QueryTransferReasonRequestBuilder:
    def __init__(self) -> None: ...
    def active(self, active: bool) -> QueryTransferReasonRequestBuilder: ...
    def transfer_reason_unique_identifier(self, transfer_reason_unique_identifier: list[str]) -> QueryTransferReasonRequestBuilder: ...
    def build(self) -> QueryTransferReasonRequest: ...
