from .transfer_type import TransferType as TransferType
from lark_oapi.core.construct import init as init

class QueryTransferTypeResponseBody:
    items: list[TransferType] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryTransferTypeResponseBodyBuilder: ...

class QueryTransferTypeResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[TransferType]) -> QueryTransferTypeResponseBodyBuilder: ...
    def build(self) -> QueryTransferTypeResponseBody: ...
