from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class QueryTransferTypeRequest(BaseRequest):
    active: bool | None
    transfer_type_unique_identifier: list[str] | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> QueryTransferTypeRequestBuilder: ...

class QueryTransferTypeRequestBuilder:
    def __init__(self) -> None: ...
    def active(self, active: bool) -> QueryTransferTypeRequestBuilder: ...
    def transfer_type_unique_identifier(self, transfer_type_unique_identifier: list[str]) -> QueryTransferTypeRequestBuilder: ...
    def build(self) -> QueryTransferTypeRequest: ...
