from lark_oapi.core.construct import init as init

class QueryCustomFieldRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryCustomFieldRequestBodyBuilder: ...

class QueryCustomFieldRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> QueryCustomFieldRequestBody: ...
