from .bp_role_organization import BpRoleOrganization as BpRoleOrganization
from lark_oapi.core.construct import init as init

class QuerySecurityGroupRequestBody:
    item_list: list[BpRoleOrganization] | None
    updated_at_gte: str | None
    updated_at_lte: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QuerySecurityGroupRequestBodyBuilder: ...

class QuerySecurityGroupRequestBodyBuilder:
    def __init__(self) -> None: ...
    def item_list(self, item_list: list[BpRoleOrganization]) -> QuerySecurityGroupRequestBodyBuilder: ...
    def updated_at_gte(self, updated_at_gte: str) -> QuerySecurityGroupRequestBodyBuilder: ...
    def updated_at_lte(self, updated_at_lte: str) -> QuerySecurityGroupRequestBodyBuilder: ...
    def build(self) -> QuerySecurityGroupRequestBody: ...
