from lark_oapi.core.construct import init as init

class QueryOffboardingRequestBody:
    active: bool | None
    offboarding_reason_unique_identifier: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryOffboardingRequestBodyBuilder: ...

class QueryOffboardingRequestBodyBuilder:
    def __init__(self) -> None: ...
    def active(self, active: bool) -> QueryOffboardingRequestBodyBuilder: ...
    def offboarding_reason_unique_identifier(self, offboarding_reason_unique_identifier: list[str]) -> QueryOffboardingRequestBodyBuilder: ...
    def build(self) -> QueryOffboardingRequestBody: ...
