from .query_offboarding_request_body import QueryOffboardingRequestBody as QueryOffboardingRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class QueryOffboardingRequest(BaseRequest):
    request_body: QueryOffboardingRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> QueryOffboardingRequestBuilder: ...

class QueryOffboardingRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: QueryOffboardingRequestBody) -> QueryOffboardingRequestBuilder: ...
    def build(self) -> QueryOffboardingRequest: ...
