from lark_oapi.core.construct import init as init

class RemoveRoleAssignAuthorizationRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RemoveRoleAssignAuthorizationRequestBodyBuilder: ...

class RemoveRoleAssignAuthorizationRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> RemoveRoleAssignAuthorizationRequestBody: ...
