from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class RemoveRoleAssignAuthorizationRequest(BaseRequest):
    employment_id: str | None
    user_id_type: str | None
    role_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> RemoveRoleAssignAuthorizationRequestBuilder: ...

class RemoveRoleAssignAuthorizationRequestBuilder:
    def __init__(self) -> None: ...
    def employment_id(self, employment_id: str) -> RemoveRoleAssignAuthorizationRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> RemoveRoleAssignAuthorizationRequestBuilder: ...
    def role_id(self, role_id: str) -> RemoveRoleAssignAuthorizationRequestBuilder: ...
    def build(self) -> RemoveRoleAssignAuthorizationRequest: ...
