from .management_scope import ManagementScope as ManagementScope
from .permission_detail import PermissionDetail as PermissionDetail
from lark_oapi.core.construct import init as init

class RoleAuthorization:
    employment_id: str | None
    permission_detail_list: list[PermissionDetail] | None
    management_scope_list: list[ManagementScope] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RoleAuthorizationBuilder: ...

class RoleAuthorizationBuilder:
    def __init__(self) -> None: ...
    def employment_id(self, employment_id: str) -> RoleAuthorizationBuilder: ...
    def permission_detail_list(self, permission_detail_list: list[PermissionDetail]) -> RoleAuthorizationBuilder: ...
    def management_scope_list(self, management_scope_list: list[ManagementScope]) -> RoleAuthorizationBuilder: ...
    def build(self) -> RoleAuthorization: ...
