from .management_scope import ManagementScope as ManagementScope
from lark_oapi.core.construct import init as init

class SearchAssignedUserRequestBody:
    role_id: str | None
    management_scope_list: list[ManagementScope] | None
    search_method: str | None
    page_token: str | None
    page_size: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SearchAssignedUserRequestBodyBuilder: ...

class SearchAssignedUserRequestBodyBuilder:
    def __init__(self) -> None: ...
    def role_id(self, role_id: str) -> SearchAssignedUserRequestBodyBuilder: ...
    def management_scope_list(self, management_scope_list: list[ManagementScope]) -> SearchAssignedUserRequestBodyBuilder: ...
    def search_method(self, search_method: str) -> SearchAssignedUserRequestBodyBuilder: ...
    def page_token(self, page_token: str) -> SearchAssignedUserRequestBodyBuilder: ...
    def page_size(self, page_size: str) -> SearchAssignedUserRequestBodyBuilder: ...
    def build(self) -> SearchAssignedUserRequestBody: ...
