from .search_assigned_user_request_body import SearchAssignedUserRequestBody as SearchAssignedUserRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class SearchAssignedUserRequest(BaseRequest):
    user_id_type: str | None
    request_body: SearchAssignedUserRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> SearchAssignedUserRequestBuilder: ...

class SearchAssignedUserRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> SearchAssignedUserRequestBuilder: ...
    def request_body(self, request_body: SearchAssignedUserRequestBody) -> SearchAssignedUserRequestBuilder: ...
    def build(self) -> SearchAssignedUserRequest: ...
