from .search_offboarding_request_body import SearchOffboardingRequestBody as SearchOffboardingRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class SearchOffboardingRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    user_id_type: str | None
    request_body: SearchOffboardingRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> SearchOffboardingRequestBuilder: ...

class SearchOffboardingRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> SearchOffboardingRequestBuilder: ...
    def page_token(self, page_token: str) -> SearchOffboardingRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> SearchOffboardingRequestBuilder: ...
    def request_body(self, request_body: SearchOffboardingRequestBody) -> SearchOffboardingRequestBuilder: ...
    def build(self) -> SearchOffboardingRequest: ...
