from lark_oapi.core.construct import init as init

class SortOption:
    sort_field: str | None
    sort_order: int | None
    sort_i18n: int | None
    sort_by_strand_length: bool | None
    sort_by_pinyin: bool | None
    sort_by_enum_value_order: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SortOptionBuilder: ...

class SortOptionBuilder:
    def __init__(self) -> None: ...
    def sort_field(self, sort_field: str) -> SortOptionBuilder: ...
    def sort_order(self, sort_order: int) -> SortOptionBuilder: ...
    def sort_i18n(self, sort_i18n: int) -> SortOptionBuilder: ...
    def sort_by_strand_length(self, sort_by_strand_length: bool) -> SortOptionBuilder: ...
    def sort_by_pinyin(self, sort_by_pinyin: bool) -> SortOptionBuilder: ...
    def sort_by_enum_value_order(self, sort_by_enum_value_order: bool) -> SortOptionBuilder: ...
    def build(self) -> SortOption: ...
