from .enum import Enum as Enum
from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class Subdivision:
    id: str | None
    name: list[I18n] | None
    country_region_id: str | None
    subdivision_type: Enum | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SubdivisionBuilder: ...

class SubdivisionBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> SubdivisionBuilder: ...
    def name(self, name: list[I18n]) -> SubdivisionBuilder: ...
    def country_region_id(self, country_region_id: str) -> SubdivisionBuilder: ...
    def subdivision_type(self, subdivision_type: Enum) -> SubdivisionBuilder: ...
    def build(self) -> Subdivision: ...
