from .submit_offboarding_request_body import SubmitOffboardingRequestBody as SubmitOffboardingRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class SubmitOffboardingRequest(BaseRequest):
    user_id_type: str | None
    request_body: SubmitOffboardingRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> SubmitOffboardingRequestBuilder: ...

class SubmitOffboardingRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> SubmitOffboardingRequestBuilder: ...
    def request_body(self, request_body: SubmitOffboardingRequestBody) -> SubmitOffboardingRequestBuilder: ...
    def build(self) -> SubmitOffboardingRequest: ...
