from .object_field_data import ObjectFieldData as ObjectFieldData
from lark_oapi.core.construct import init as init

class SubmitOffboardingRequestBody:
    offboarding_mode: int | None
    employment_id: str | None
    offboarding_date: str | None
    offboarding_reason_unique_identifier: str | None
    offboarding_reason_explanation: str | None
    initiator_id: str | None
    add_block_list: bool | None
    block_reason: str | None
    block_reason_explanation: str | None
    custom_fields: list[ObjectFieldData] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SubmitOffboardingRequestBodyBuilder: ...

class SubmitOffboardingRequestBodyBuilder:
    def __init__(self) -> None: ...
    def offboarding_mode(self, offboarding_mode: int) -> SubmitOffboardingRequestBodyBuilder: ...
    def employment_id(self, employment_id: str) -> SubmitOffboardingRequestBodyBuilder: ...
    def offboarding_date(self, offboarding_date: str) -> SubmitOffboardingRequestBodyBuilder: ...
    def offboarding_reason_unique_identifier(self, offboarding_reason_unique_identifier: str) -> SubmitOffboardingRequestBodyBuilder: ...
    def offboarding_reason_explanation(self, offboarding_reason_explanation: str) -> SubmitOffboardingRequestBodyBuilder: ...
    def initiator_id(self, initiator_id: str) -> SubmitOffboardingRequestBodyBuilder: ...
    def add_block_list(self, add_block_list: bool) -> SubmitOffboardingRequestBodyBuilder: ...
    def block_reason(self, block_reason: str) -> SubmitOffboardingRequestBodyBuilder: ...
    def block_reason_explanation(self, block_reason_explanation: str) -> SubmitOffboardingRequestBodyBuilder: ...
    def custom_fields(self, custom_fields: list[ObjectFieldData]) -> SubmitOffboardingRequestBodyBuilder: ...
    def build(self) -> SubmitOffboardingRequestBody: ...
