from lark_oapi.core.construct import init as init

class SupportCostCenterItem:
    cost_center_id: str | None
    rate: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SupportCostCenterItemBuilder: ...

class SupportCostCenterItemBuilder:
    def __init__(self) -> None: ...
    def cost_center_id(self, cost_center_id: str) -> SupportCostCenterItemBuilder: ...
    def rate(self, rate: int) -> SupportCostCenterItemBuilder: ...
    def build(self) -> SupportCostCenterItem: ...
