from lark_oapi.core.construct import init as init

class Temp:
    id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TempBuilder: ...

class TempBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> TempBuilder: ...
    def build(self) -> Temp: ...
