from lark_oapi.core.construct import init as init

class UpdateRoleAssignAuthorizationResponseBody:
    assign_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateRoleAssignAuthorizationResponseBodyBuilder: ...

class UpdateRoleAssignAuthorizationResponseBodyBuilder:
    def __init__(self) -> None: ...
    def assign_id(self, assign_id: str) -> UpdateRoleAssignAuthorizationResponseBodyBuilder: ...
    def build(self) -> UpdateRoleAssignAuthorizationResponseBody: ...
