from .update_role_assign_authorization_request_body import UpdateRoleAssignAuthorizationRequestBody as UpdateRoleAssignAuthorizationRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UpdateRoleAssignAuthorizationRequest(BaseRequest):
    employment_id: str | None
    user_id_type: str | None
    role_id: str | None
    request_body: UpdateRoleAssignAuthorizationRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UpdateRoleAssignAuthorizationRequestBuilder: ...

class UpdateRoleAssignAuthorizationRequestBuilder:
    def __init__(self) -> None: ...
    def employment_id(self, employment_id: str) -> UpdateRoleAssignAuthorizationRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> UpdateRoleAssignAuthorizationRequestBuilder: ...
    def role_id(self, role_id: str) -> UpdateRoleAssignAuthorizationRequestBuilder: ...
    def request_body(self, request_body: UpdateRoleAssignAuthorizationRequestBody) -> UpdateRoleAssignAuthorizationRequestBuilder: ...
    def build(self) -> UpdateRoleAssignAuthorizationRequest: ...
