from lark_oapi.core.construct import init as init

class WkCalendarDate:
    calendar_id: str | None
    date: str | None
    date_type: str | None
    id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WkCalendarDateBuilder: ...

class WkCalendarDateBuilder:
    def __init__(self) -> None: ...
    def calendar_id(self, calendar_id: str) -> WkCalendarDateBuilder: ...
    def date(self, date: str) -> WkCalendarDateBuilder: ...
    def date_type(self, date_type: str) -> WkCalendarDateBuilder: ...
    def id(self, id: str) -> WkCalendarDateBuilder: ...
    def build(self) -> WkCalendarDate: ...
