from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class AccountReferrer:
    id: str | None
    name: I18n | None
    email: str | None
    mobile: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AccountReferrerBuilder: ...

class AccountReferrerBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> AccountReferrerBuilder: ...
    def name(self, name: I18n) -> AccountReferrerBuilder: ...
    def email(self, email: str) -> AccountReferrerBuilder: ...
    def mobile(self, mobile: str) -> AccountReferrerBuilder: ...
    def build(self) -> AccountReferrer: ...
