from .add_to_folder_talent_request_body import AddToFolderTalentRequestBody as AddToFolderTalentRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class AddToFolderTalentRequest(BaseRequest):
    request_body: AddToFolderTalentRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> AddToFolderTalentRequestBuilder: ...

class AddToFolderTalentRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: AddToFolderTalentRequestBody) -> AddToFolderTalentRequestBuilder: ...
    def build(self) -> AddToFolderTalentRequest: ...
