from lark_oapi.core.construct import init as init

class AddToFolderTalentRequestBody:
    talent_id_list: list[str] | None
    folder_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AddToFolderTalentRequestBodyBuilder: ...

class AddToFolderTalentRequestBodyBuilder:
    def __init__(self) -> None: ...
    def talent_id_list(self, talent_id_list: list[str]) -> AddToFolderTalentRequestBodyBuilder: ...
    def folder_id(self, folder_id: str) -> AddToFolderTalentRequestBodyBuilder: ...
    def build(self) -> AddToFolderTalentRequestBody: ...
