from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class AgencySupplierAdmin:
    user_id: str | None
    name: I18n | None
    email: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AgencySupplierAdminBuilder: ...

class AgencySupplierAdminBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: str) -> AgencySupplierAdminBuilder: ...
    def name(self, name: I18n) -> AgencySupplierAdminBuilder: ...
    def email(self, email: str) -> AgencySupplierAdminBuilder: ...
    def build(self) -> AgencySupplierAdmin: ...
