from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class AgencyBasicInfo:
    hunter_user_name: I18n | None
    hunter_company_name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AgencyBasicInfoBuilder: ...

class AgencyBasicInfoBuilder:
    def __init__(self) -> None: ...
    def hunter_user_name(self, hunter_user_name: I18n) -> AgencyBasicInfoBuilder: ...
    def hunter_company_name(self, hunter_company_name: str) -> AgencyBasicInfoBuilder: ...
    def build(self) -> AgencyBasicInfo: ...
