from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class AgencySupplierLabel:
    id: str | None
    name: I18n | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AgencySupplierLabelBuilder: ...

class AgencySupplierLabelBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> AgencySupplierLabelBuilder: ...
    def name(self, name: I18n) -> AgencySupplierLabelBuilder: ...
    def build(self) -> AgencySupplierLabel: ...
