from .appli_offer_onboard_profile import AppliOfferOnboardProfile as AppliOfferOnboardProfile
from .application_offer_attachment import ApplicationOfferAttachment as ApplicationOfferAttachment
from .application_prehire_offer_basic import ApplicationPrehireOfferBasic as ApplicationPrehireOfferBasic
from lark_oapi.core.construct import init as init

class ApplicationPrehireOffer:
    basic_info: ApplicationPrehireOfferBasic | None
    offer_onboard_profile: AppliOfferOnboardProfile | None
    attachment_list: list[ApplicationOfferAttachment] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApplicationPrehireOfferBuilder: ...

class ApplicationPrehireOfferBuilder:
    def __init__(self) -> None: ...
    def basic_info(self, basic_info: ApplicationPrehireOfferBasic) -> ApplicationPrehireOfferBuilder: ...
    def offer_onboard_profile(self, offer_onboard_profile: AppliOfferOnboardProfile) -> ApplicationPrehireOfferBuilder: ...
    def attachment_list(self, attachment_list: list[ApplicationOfferAttachment]) -> ApplicationPrehireOfferBuilder: ...
    def build(self) -> ApplicationPrehireOffer: ...
