from .application_offer_basic_info_user import ApplicationOfferBasicInfoUser as ApplicationOfferBasicInfoUser
from .application_offer_onboard_profile_address import ApplicationOfferOnboardProfileAddress as ApplicationOfferOnboardProfileAddress
from .department import Department as Department
from .level import Level as Level
from .recruitment_type import RecruitmentType as RecruitmentType
from .sequence import Sequence as Sequence
from lark_oapi.core.construct import init as init

class ApplicationOfferOnboardProfile:
    offer_id: str | None
    department: Department | None
    recruitment_type: RecruitmentType | None
    sequence: Sequence | None
    level: Level | None
    onboard_address: ApplicationOfferOnboardProfileAddress | None
    work_address: ApplicationOfferOnboardProfileAddress | None
    leader: ApplicationOfferBasicInfoUser | None
    is_work_address_same_to_onboard: bool | None
    probation_month: int | None
    contract_year: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApplicationOfferOnboardProfileBuilder: ...

class ApplicationOfferOnboardProfileBuilder:
    def __init__(self) -> None: ...
    def offer_id(self, offer_id: str) -> ApplicationOfferOnboardProfileBuilder: ...
    def department(self, department: Department) -> ApplicationOfferOnboardProfileBuilder: ...
    def recruitment_type(self, recruitment_type: RecruitmentType) -> ApplicationOfferOnboardProfileBuilder: ...
    def sequence(self, sequence: Sequence) -> ApplicationOfferOnboardProfileBuilder: ...
    def level(self, level: Level) -> ApplicationOfferOnboardProfileBuilder: ...
    def onboard_address(self, onboard_address: ApplicationOfferOnboardProfileAddress) -> ApplicationOfferOnboardProfileBuilder: ...
    def work_address(self, work_address: ApplicationOfferOnboardProfileAddress) -> ApplicationOfferOnboardProfileBuilder: ...
    def leader(self, leader: ApplicationOfferBasicInfoUser) -> ApplicationOfferOnboardProfileBuilder: ...
    def is_work_address_same_to_onboard(self, is_work_address_same_to_onboard: bool) -> ApplicationOfferOnboardProfileBuilder: ...
    def probation_month(self, probation_month: int) -> ApplicationOfferOnboardProfileBuilder: ...
    def contract_year(self, contract_year: int) -> ApplicationOfferOnboardProfileBuilder: ...
    def build(self) -> ApplicationOfferOnboardProfile: ...
