from lark_oapi.core.construct import init as init

class AppliTalentEducationInfo:
    id: str | None
    degree: int | None
    school: str | None
    field_of_study: str | None
    start_time: str | None
    end_time: str | None
    education_type: int | None
    academic_ranking: int | None
    tag_list: list[int] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppliTalentEducationInfoBuilder: ...

class AppliTalentEducationInfoBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> AppliTalentEducationInfoBuilder: ...
    def degree(self, degree: int) -> AppliTalentEducationInfoBuilder: ...
    def school(self, school: str) -> AppliTalentEducationInfoBuilder: ...
    def field_of_study(self, field_of_study: str) -> AppliTalentEducationInfoBuilder: ...
    def start_time(self, start_time: str) -> AppliTalentEducationInfoBuilder: ...
    def end_time(self, end_time: str) -> AppliTalentEducationInfoBuilder: ...
    def education_type(self, education_type: int) -> AppliTalentEducationInfoBuilder: ...
    def academic_ranking(self, academic_ranking: int) -> AppliTalentEducationInfoBuilder: ...
    def tag_list(self, tag_list: list[int]) -> AppliTalentEducationInfoBuilder: ...
    def build(self) -> AppliTalentEducationInfo: ...
