from lark_oapi.core.construct import init as init

class ApplicationOfferSalaryPlanSalaryTemplate:
    template_key: str | None
    total_amount: str | None
    currency: str | None
    salary_content: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApplicationOfferSalaryPlanSalaryTemplateBuilder: ...

class ApplicationOfferSalaryPlanSalaryTemplateBuilder:
    def __init__(self) -> None: ...
    def template_key(self, template_key: str) -> ApplicationOfferSalaryPlanSalaryTemplateBuilder: ...
    def total_amount(self, total_amount: str) -> ApplicationOfferSalaryPlanSalaryTemplateBuilder: ...
    def currency(self, currency: str) -> ApplicationOfferSalaryPlanSalaryTemplateBuilder: ...
    def salary_content(self, salary_content: str) -> ApplicationOfferSalaryPlanSalaryTemplateBuilder: ...
    def build(self) -> ApplicationOfferSalaryPlanSalaryTemplate: ...
