from .appli_offer_basic_cust_obj_op_v import AppliOfferBasicCustObjOpV as AppliOfferBasicCustObjOpV
from .offer_schema_name import OfferSchemaName as OfferSchemaName
from lark_oapi.core.construct import init as init

class AppliOfferBasicCustObj:
    id: str | None
    name: OfferSchemaName | None
    type: str | None
    value: str | None
    option_value_list: list[AppliOfferBasicCustObjOpV] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppliOfferBasicCustObjBuilder: ...

class AppliOfferBasicCustObjBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> AppliOfferBasicCustObjBuilder: ...
    def name(self, name: OfferSchemaName) -> AppliOfferBasicCustObjBuilder: ...
    def type(self, type: str) -> AppliOfferBasicCustObjBuilder: ...
    def value(self, value: str) -> AppliOfferBasicCustObjBuilder: ...
    def option_value_list(self, option_value_list: list[AppliOfferBasicCustObjOpV]) -> AppliOfferBasicCustObjBuilder: ...
    def build(self) -> AppliOfferBasicCustObj: ...
