from lark_oapi.core.construct import init as init

class ApplicationStageInfo:
    id: str | None
    zh_name: str | None
    en_name: str | None
    type: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApplicationStageInfoBuilder: ...

class ApplicationStageInfoBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> ApplicationStageInfoBuilder: ...
    def zh_name(self, zh_name: str) -> ApplicationStageInfoBuilder: ...
    def en_name(self, en_name: str) -> ApplicationStageInfoBuilder: ...
    def type(self, type: int) -> ApplicationStageInfoBuilder: ...
    def build(self) -> ApplicationStageInfo: ...
