from lark_oapi.core.construct import init as init

class AppliTalentAttachResumeInfo:
    id: str | None
    name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AppliTalentAttachResumeInfoBuilder: ...

class AppliTalentAttachResumeInfoBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> AppliTalentAttachResumeInfoBuilder: ...
    def name(self, name: str) -> AppliTalentAttachResumeInfoBuilder: ...
    def build(self) -> AppliTalentAttachResumeInfo: ...
