from .application_resume_source import ApplicationResumeSource as ApplicationResumeSource
from .application_stage_info import ApplicationStageInfo as ApplicationStageInfo
from .application_stage_time import ApplicationStageTime as ApplicationStageTime
from .application_website_resume_source import ApplicationWebsiteResumeSource as ApplicationWebsiteResumeSource
from .code_name_object import CodeNameObject as CodeNameObject
from lark_oapi.core.construct import init as init

class Application:
    id: str | None
    job_id: str | None
    talent_id: str | None
    resume_source_id: str | None
    stage: ApplicationStageInfo | None
    active_status: int | None
    delivery_type: int | None
    resume_source_info: ApplicationResumeSource | None
    website_resume_source: ApplicationWebsiteResumeSource | None
    talent_attachment_resume_id: str | None
    create_time: str | None
    modify_time: str | None
    stage_time_list: list[ApplicationStageTime] | None
    termination_type: int | None
    termination_reason_list: list[str] | None
    termination_reason_note: str | None
    application_preferred_city_list: list[CodeNameObject] | None
    creator_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApplicationBuilder: ...

class ApplicationBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> ApplicationBuilder: ...
    def job_id(self, job_id: str) -> ApplicationBuilder: ...
    def talent_id(self, talent_id: str) -> ApplicationBuilder: ...
    def resume_source_id(self, resume_source_id: str) -> ApplicationBuilder: ...
    def stage(self, stage: ApplicationStageInfo) -> ApplicationBuilder: ...
    def active_status(self, active_status: int) -> ApplicationBuilder: ...
    def delivery_type(self, delivery_type: int) -> ApplicationBuilder: ...
    def resume_source_info(self, resume_source_info: ApplicationResumeSource) -> ApplicationBuilder: ...
    def website_resume_source(self, website_resume_source: ApplicationWebsiteResumeSource) -> ApplicationBuilder: ...
    def talent_attachment_resume_id(self, talent_attachment_resume_id: str) -> ApplicationBuilder: ...
    def create_time(self, create_time: str) -> ApplicationBuilder: ...
    def modify_time(self, modify_time: str) -> ApplicationBuilder: ...
    def stage_time_list(self, stage_time_list: list[ApplicationStageTime]) -> ApplicationBuilder: ...
    def termination_type(self, termination_type: int) -> ApplicationBuilder: ...
    def termination_reason_list(self, termination_reason_list: list[str]) -> ApplicationBuilder: ...
    def termination_reason_note(self, termination_reason_note: str) -> ApplicationBuilder: ...
    def application_preferred_city_list(self, application_preferred_city_list: list[CodeNameObject]) -> ApplicationBuilder: ...
    def creator_id(self, creator_id: str) -> ApplicationBuilder: ...
    def build(self) -> Application: ...
