from lark_oapi.core.construct import init as init

class ApplicationOfferAttachment:
    attachment_id: str | None
    name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApplicationOfferAttachmentBuilder: ...

class ApplicationOfferAttachmentBuilder:
    def __init__(self) -> None: ...
    def attachment_id(self, attachment_id: str) -> ApplicationOfferAttachmentBuilder: ...
    def name(self, name: str) -> ApplicationOfferAttachmentBuilder: ...
    def build(self) -> ApplicationOfferAttachment: ...
