from lark_oapi.core.construct import init as init

class ApplicationOfferOnboardProfileCity:
    code: str | None
    name: str | None
    en_name: str | None
    location_type: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApplicationOfferOnboardProfileCityBuilder: ...

class ApplicationOfferOnboardProfileCityBuilder:
    def __init__(self) -> None: ...
    def code(self, code: str) -> ApplicationOfferOnboardProfileCityBuilder: ...
    def name(self, name: str) -> ApplicationOfferOnboardProfileCityBuilder: ...
    def en_name(self, en_name: str) -> ApplicationOfferOnboardProfileCityBuilder: ...
    def location_type(self, location_type: int) -> ApplicationOfferOnboardProfileCityBuilder: ...
    def build(self) -> ApplicationOfferOnboardProfileCity: ...
