from .application_offer_custom_value import ApplicationOfferCustomValue as ApplicationOfferCustomValue
from lark_oapi.core.construct import init as init

class ApplicationOfferCustomModule:
    i_d: str | None
    object_list: list[ApplicationOfferCustomValue] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApplicationOfferCustomModuleBuilder: ...

class ApplicationOfferCustomModuleBuilder:
    def __init__(self) -> None: ...
    def i_d(self, i_d: str) -> ApplicationOfferCustomModuleBuilder: ...
    def object_list(self, object_list: list[ApplicationOfferCustomValue]) -> ApplicationOfferCustomModuleBuilder: ...
    def build(self) -> ApplicationOfferCustomModule: ...
