from .application_resume_source import ApplicationResumeSource as ApplicationResumeSource
from .application_stage_info import ApplicationStageInfo as ApplicationStageInfo
from .application_stage_time import ApplicationStageTime as ApplicationStageTime
from .application_website_resume_source import ApplicationWebsiteResumeSource as ApplicationWebsiteResumeSource
from .code_name_object import CodeNameObject as CodeNameObject
from .termination_reason_info import TerminationReasonInfo as TerminationReasonInfo
from lark_oapi.core.construct import init as init

class ApplicationDetailBasicInfo:
    id: str | None
    job_id: str | None
    talent_id: str | None
    stage: ApplicationStageInfo | None
    active_status: int | None
    delivery_type: int | None
    resume_source_info: ApplicationResumeSource | None
    website_resume_source: ApplicationWebsiteResumeSource | None
    talent_attachment_resume_id: str | None
    stage_time_list: list[ApplicationStageTime] | None
    onboard_status: int | None
    application_preferred_city_list: list[CodeNameObject] | None
    termination_reason: TerminationReasonInfo | None
    creator_id: str | None
    owner_id: str | None
    terminator_id: str | None
    create_time: str | None
    modify_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApplicationDetailBasicInfoBuilder: ...

class ApplicationDetailBasicInfoBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> ApplicationDetailBasicInfoBuilder: ...
    def job_id(self, job_id: str) -> ApplicationDetailBasicInfoBuilder: ...
    def talent_id(self, talent_id: str) -> ApplicationDetailBasicInfoBuilder: ...
    def stage(self, stage: ApplicationStageInfo) -> ApplicationDetailBasicInfoBuilder: ...
    def active_status(self, active_status: int) -> ApplicationDetailBasicInfoBuilder: ...
    def delivery_type(self, delivery_type: int) -> ApplicationDetailBasicInfoBuilder: ...
    def resume_source_info(self, resume_source_info: ApplicationResumeSource) -> ApplicationDetailBasicInfoBuilder: ...
    def website_resume_source(self, website_resume_source: ApplicationWebsiteResumeSource) -> ApplicationDetailBasicInfoBuilder: ...
    def talent_attachment_resume_id(self, talent_attachment_resume_id: str) -> ApplicationDetailBasicInfoBuilder: ...
    def stage_time_list(self, stage_time_list: list[ApplicationStageTime]) -> ApplicationDetailBasicInfoBuilder: ...
    def onboard_status(self, onboard_status: int) -> ApplicationDetailBasicInfoBuilder: ...
    def application_preferred_city_list(self, application_preferred_city_list: list[CodeNameObject]) -> ApplicationDetailBasicInfoBuilder: ...
    def termination_reason(self, termination_reason: TerminationReasonInfo) -> ApplicationDetailBasicInfoBuilder: ...
    def creator_id(self, creator_id: str) -> ApplicationDetailBasicInfoBuilder: ...
    def owner_id(self, owner_id: str) -> ApplicationDetailBasicInfoBuilder: ...
    def terminator_id(self, terminator_id: str) -> ApplicationDetailBasicInfoBuilder: ...
    def create_time(self, create_time: str) -> ApplicationDetailBasicInfoBuilder: ...
    def modify_time(self, modify_time: str) -> ApplicationDetailBasicInfoBuilder: ...
    def build(self) -> ApplicationDetailBasicInfo: ...
