from .campus_volumnteer_info import CampusVolumnteerInfo as CampusVolumnteerInfo
from lark_oapi.core.construct import init as init

class ApplicationDetailPortalInfo:
    campus_volunteer_info: CampusVolumnteerInfo | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApplicationDetailPortalInfoBuilder: ...

class ApplicationDetailPortalInfoBuilder:
    def __init__(self) -> None: ...
    def campus_volunteer_info(self, campus_volunteer_info: CampusVolumnteerInfo) -> ApplicationDetailPortalInfoBuilder: ...
    def build(self) -> ApplicationDetailPortalInfo: ...
