from .application_offer_onboard_profile_city import ApplicationOfferOnboardProfileCity as ApplicationOfferOnboardProfileCity
from lark_oapi.core.construct import init as init

class ApplicationOfferOnboardProfileAddress:
    id: str | None
    name: str | None
    en_name: str | None
    district: ApplicationOfferOnboardProfileCity | None
    city: ApplicationOfferOnboardProfileCity | None
    state: ApplicationOfferOnboardProfileCity | None
    country: ApplicationOfferOnboardProfileCity | None
    usage_id_list: list[str] | None
    active_status: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApplicationOfferOnboardProfileAddressBuilder: ...

class ApplicationOfferOnboardProfileAddressBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> ApplicationOfferOnboardProfileAddressBuilder: ...
    def name(self, name: str) -> ApplicationOfferOnboardProfileAddressBuilder: ...
    def en_name(self, en_name: str) -> ApplicationOfferOnboardProfileAddressBuilder: ...
    def district(self, district: ApplicationOfferOnboardProfileCity) -> ApplicationOfferOnboardProfileAddressBuilder: ...
    def city(self, city: ApplicationOfferOnboardProfileCity) -> ApplicationOfferOnboardProfileAddressBuilder: ...
    def state(self, state: ApplicationOfferOnboardProfileCity) -> ApplicationOfferOnboardProfileAddressBuilder: ...
    def country(self, country: ApplicationOfferOnboardProfileCity) -> ApplicationOfferOnboardProfileAddressBuilder: ...
    def usage_id_list(self, usage_id_list: list[str]) -> ApplicationOfferOnboardProfileAddressBuilder: ...
    def active_status(self, active_status: int) -> ApplicationOfferOnboardProfileAddressBuilder: ...
    def build(self) -> ApplicationOfferOnboardProfileAddress: ...
