from .appli_offer_basic_info_user import AppliOfferBasicInfoUser as AppliOfferBasicInfoUser
from lark_oapi.core.construct import init as init

class ApplicationPrehireOfferBasic:
    offer_id: str | None
    application_id: str | None
    talent_id: str | None
    job_id: str | None
    remark: str | None
    expire_time: int | None
    onboard_time: int | None
    time_zone: str | None
    offer_type: int | None
    offer_status: int | None
    owner: AppliOfferBasicInfoUser | None
    offer_job_title: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApplicationPrehireOfferBasicBuilder: ...

class ApplicationPrehireOfferBasicBuilder:
    def __init__(self) -> None: ...
    def offer_id(self, offer_id: str) -> ApplicationPrehireOfferBasicBuilder: ...
    def application_id(self, application_id: str) -> ApplicationPrehireOfferBasicBuilder: ...
    def talent_id(self, talent_id: str) -> ApplicationPrehireOfferBasicBuilder: ...
    def job_id(self, job_id: str) -> ApplicationPrehireOfferBasicBuilder: ...
    def remark(self, remark: str) -> ApplicationPrehireOfferBasicBuilder: ...
    def expire_time(self, expire_time: int) -> ApplicationPrehireOfferBasicBuilder: ...
    def onboard_time(self, onboard_time: int) -> ApplicationPrehireOfferBasicBuilder: ...
    def time_zone(self, time_zone: str) -> ApplicationPrehireOfferBasicBuilder: ...
    def offer_type(self, offer_type: int) -> ApplicationPrehireOfferBasicBuilder: ...
    def offer_status(self, offer_status: int) -> ApplicationPrehireOfferBasicBuilder: ...
    def owner(self, owner: AppliOfferBasicInfoUser) -> ApplicationPrehireOfferBasicBuilder: ...
    def offer_job_title(self, offer_job_title: str) -> ApplicationPrehireOfferBasicBuilder: ...
    def build(self) -> ApplicationPrehireOfferBasic: ...
