from lark_oapi.core.construct import init as init

class ApplicationTalentSnsInfo:
    id: str | None
    sns_type: int | None
    link: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ApplicationTalentSnsInfoBuilder: ...

class ApplicationTalentSnsInfoBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> ApplicationTalentSnsInfoBuilder: ...
    def sns_type(self, sns_type: int) -> ApplicationTalentSnsInfoBuilder: ...
    def link(self, link: str) -> ApplicationTalentSnsInfoBuilder: ...
    def build(self) -> ApplicationTalentSnsInfo: ...
