from lark_oapi.core.construct import init as init

class AssessInterviewOption:
    ignore_minutes: bool | None
    ignore_coding_question: bool | None
    ignore_interview_question: bool | None
    ignore_image: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AssessInterviewOptionBuilder: ...

class AssessInterviewOptionBuilder:
    def __init__(self) -> None: ...
    def ignore_minutes(self, ignore_minutes: bool) -> AssessInterviewOptionBuilder: ...
    def ignore_coding_question(self, ignore_coding_question: bool) -> AssessInterviewOptionBuilder: ...
    def ignore_interview_question(self, ignore_interview_question: bool) -> AssessInterviewOptionBuilder: ...
    def ignore_image(self, ignore_image: bool) -> AssessInterviewOptionBuilder: ...
    def build(self) -> AssessInterviewOption: ...
