from .bonus_amount import BonusAmount as BonusAmount
from lark_oapi.core.construct import init as init

class Assets:
    confirmed_bonus: BonusAmount | None
    paid_bonus: BonusAmount | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AssetsBuilder: ...

class AssetsBuilder:
    def __init__(self) -> None: ...
    def confirmed_bonus(self, confirmed_bonus: BonusAmount) -> AssetsBuilder: ...
    def paid_bonus(self, paid_bonus: BonusAmount) -> AssetsBuilder: ...
    def build(self) -> Assets: ...
