from lark_oapi.core.construct import init as init

class AttachmentV2:
    id: str | None
    url: str | None
    name: str | None
    mime: str | None
    create_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AttachmentV2Builder: ...

class AttachmentV2Builder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> AttachmentV2Builder: ...
    def url(self, url: str) -> AttachmentV2Builder: ...
    def name(self, name: str) -> AttachmentV2Builder: ...
    def mime(self, mime: str) -> AttachmentV2Builder: ...
    def create_time(self, create_time: str) -> AttachmentV2Builder: ...
    def build(self) -> AttachmentV2: ...
