from lark_oapi.core.construct import init as init

class Attachment:
    id: str | None
    url: str | None
    name: str | None
    mime: str | None
    create_time: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AttachmentBuilder: ...

class AttachmentBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> AttachmentBuilder: ...
    def url(self, url: str) -> AttachmentBuilder: ...
    def name(self, name: str) -> AttachmentBuilder: ...
    def mime(self, mime: str) -> AttachmentBuilder: ...
    def create_time(self, create_time: int) -> AttachmentBuilder: ...
    def build(self) -> Attachment: ...
