from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class Auth:
    id: str | None
    name: I18n | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> AuthBuilder: ...

class AuthBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> AuthBuilder: ...
    def name(self, name: I18n) -> AuthBuilder: ...
    def build(self) -> Auth: ...
