from lark_oapi.core.construct import init as init

class BackgroundCheckOrderProcessInfo:
    process: str | None
    update_time: str | None
    en_process: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BackgroundCheckOrderProcessInfoBuilder: ...

class BackgroundCheckOrderProcessInfoBuilder:
    def __init__(self) -> None: ...
    def process(self, process: str) -> BackgroundCheckOrderProcessInfoBuilder: ...
    def update_time(self, update_time: str) -> BackgroundCheckOrderProcessInfoBuilder: ...
    def en_process(self, en_process: str) -> BackgroundCheckOrderProcessInfoBuilder: ...
    def build(self) -> BackgroundCheckOrderProcessInfo: ...
