from lark_oapi.core.construct import init as init

class BackgroundCheckCustomFieldDataValue:
    key: str | None
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BackgroundCheckCustomFieldDataValueBuilder: ...

class BackgroundCheckCustomFieldDataValueBuilder:
    def __init__(self) -> None: ...
    def key(self, key: str) -> BackgroundCheckCustomFieldDataValueBuilder: ...
    def value(self, value: str) -> BackgroundCheckCustomFieldDataValueBuilder: ...
    def build(self) -> BackgroundCheckCustomFieldDataValue: ...
