from .base_location import BaseLocation as BaseLocation
from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class BaseAddressV2:
    id: str | None
    name: I18n | None
    district: BaseLocation | None
    city: BaseLocation | None
    state: BaseLocation | None
    country: BaseLocation | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BaseAddressV2Builder: ...

class BaseAddressV2Builder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> BaseAddressV2Builder: ...
    def name(self, name: I18n) -> BaseAddressV2Builder: ...
    def district(self, district: BaseLocation) -> BaseAddressV2Builder: ...
    def city(self, city: BaseLocation) -> BaseAddressV2Builder: ...
    def state(self, state: BaseLocation) -> BaseAddressV2Builder: ...
    def country(self, country: BaseLocation) -> BaseAddressV2Builder: ...
    def build(self) -> BaseAddressV2: ...
