from .base_city import BaseCity as BaseCity
from .base_country import BaseCountry as BaseCountry
from .base_district import BaseDistrict as BaseDistrict
from lark_oapi.core.construct import init as init

class BaseAddress:
    id: str | None
    zh_name: str | None
    en_name: str | None
    district: BaseDistrict | None
    city: BaseCity | None
    state: BaseCity | None
    country: BaseCountry | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BaseAddressBuilder: ...

class BaseAddressBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> BaseAddressBuilder: ...
    def zh_name(self, zh_name: str) -> BaseAddressBuilder: ...
    def en_name(self, en_name: str) -> BaseAddressBuilder: ...
    def district(self, district: BaseDistrict) -> BaseAddressBuilder: ...
    def city(self, city: BaseCity) -> BaseAddressBuilder: ...
    def state(self, state: BaseCity) -> BaseAddressBuilder: ...
    def country(self, country: BaseCountry) -> BaseAddressBuilder: ...
    def build(self) -> BaseAddress: ...
