from lark_oapi.core.construct import init as init

class BaseResp:
    status_message: str | None
    status_code: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BaseRespBuilder: ...

class BaseRespBuilder:
    def __init__(self) -> None: ...
    def status_message(self, status_message: str) -> BaseRespBuilder: ...
    def status_code(self, status_code: int) -> BaseRespBuilder: ...
    def build(self) -> BaseResp: ...
