from lark_oapi.core.construct import init as init

class BatchChangeTalentPoolTalentPoolResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchChangeTalentPoolTalentPoolResponseBodyBuilder: ...

class BatchChangeTalentPoolTalentPoolResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> BatchChangeTalentPoolTalentPoolResponseBody: ...
