from lark_oapi.core.construct import init as init

class BatchUpdateEcoBackgroundCheckCustomFieldResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchUpdateEcoBackgroundCheckCustomFieldResponseBodyBuilder: ...

class BatchUpdateEcoBackgroundCheckCustomFieldResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> BatchUpdateEcoBackgroundCheckCustomFieldResponseBody: ...
