from .eco_background_check_custom_field import EcoBackgroundCheckCustomField as EcoBackgroundCheckCustomField
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchUpdateEcoBackgroundCheckCustomFieldRequest(BaseRequest):
    request_body: EcoBackgroundCheckCustomField | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchUpdateEcoBackgroundCheckCustomFieldRequestBuilder: ...

class BatchUpdateEcoBackgroundCheckCustomFieldRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: EcoBackgroundCheckCustomField) -> BatchUpdateEcoBackgroundCheckCustomFieldRequestBuilder: ...
    def build(self) -> BatchUpdateEcoBackgroundCheckCustomFieldRequest: ...
