from .batch_delete_eco_account_custom_field_request_body import BatchDeleteEcoAccountCustomFieldRequestBody as BatchDeleteEcoAccountCustomFieldRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchDeleteEcoAccountCustomFieldRequest(BaseRequest):
    request_body: BatchDeleteEcoAccountCustomFieldRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchDeleteEcoAccountCustomFieldRequestBuilder: ...

class BatchDeleteEcoAccountCustomFieldRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: BatchDeleteEcoAccountCustomFieldRequestBody) -> BatchDeleteEcoAccountCustomFieldRequestBuilder: ...
    def build(self) -> BatchDeleteEcoAccountCustomFieldRequest: ...
