from lark_oapi.core.construct import init as init

class BatchDeleteEcoAccountCustomFieldResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchDeleteEcoAccountCustomFieldResponseBodyBuilder: ...

class BatchDeleteEcoAccountCustomFieldResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> BatchDeleteEcoAccountCustomFieldResponseBody: ...
