from .agency_supplier import AgencySupplier as AgencySupplier
from lark_oapi.core.construct import init as init

class BatchQueryAgencyResponseBody:
    has_more: bool | None
    page_token: str | None
    items: list[AgencySupplier] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchQueryAgencyResponseBodyBuilder: ...

class BatchQueryAgencyResponseBodyBuilder:
    def __init__(self) -> None: ...
    def has_more(self, has_more: bool) -> BatchQueryAgencyResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> BatchQueryAgencyResponseBodyBuilder: ...
    def items(self, items: list[AgencySupplier]) -> BatchQueryAgencyResponseBodyBuilder: ...
    def build(self) -> BatchQueryAgencyResponseBody: ...
