from lark_oapi.core.construct import init as init

class BatchChangeTalentPoolTalentPoolRequestBody:
    talent_id_list: list[str] | None
    option_type: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchChangeTalentPoolTalentPoolRequestBodyBuilder: ...

class BatchChangeTalentPoolTalentPoolRequestBodyBuilder:
    def __init__(self) -> None: ...
    def talent_id_list(self, talent_id_list: list[str]) -> BatchChangeTalentPoolTalentPoolRequestBodyBuilder: ...
    def option_type(self, option_type: int) -> BatchChangeTalentPoolTalentPoolRequestBodyBuilder: ...
    def build(self) -> BatchChangeTalentPoolTalentPoolRequestBody: ...
