from .common_filter import CommonFilter as CommonFilter
from lark_oapi.core.construct import init as init

class BatchQueryAgencyRequestBody:
    agency_supplier_id_list: list[str] | None
    keyword: str | None
    filter_list: list[CommonFilter] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchQueryAgencyRequestBodyBuilder: ...

class BatchQueryAgencyRequestBodyBuilder:
    def __init__(self) -> None: ...
    def agency_supplier_id_list(self, agency_supplier_id_list: list[str]) -> BatchQueryAgencyRequestBodyBuilder: ...
    def keyword(self, keyword: str) -> BatchQueryAgencyRequestBodyBuilder: ...
    def filter_list(self, filter_list: list[CommonFilter]) -> BatchQueryAgencyRequestBodyBuilder: ...
    def build(self) -> BatchQueryAgencyRequestBody: ...
