from lark_oapi.core.construct import init as init

class BatchUpdateEcoAccountCustomFieldResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchUpdateEcoAccountCustomFieldResponseBodyBuilder: ...

class BatchUpdateEcoAccountCustomFieldResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> BatchUpdateEcoAccountCustomFieldResponseBody: ...
