from lark_oapi.core.construct import init as init

class BatchGetIdTalentRequestBody:
    mobile_code: str | None
    mobile_number_list: list[str] | None
    email_list: list[str] | None
    identification_type: int | None
    identification_number_list: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchGetIdTalentRequestBodyBuilder: ...

class BatchGetIdTalentRequestBodyBuilder:
    def __init__(self) -> None: ...
    def mobile_code(self, mobile_code: str) -> BatchGetIdTalentRequestBodyBuilder: ...
    def mobile_number_list(self, mobile_number_list: list[str]) -> BatchGetIdTalentRequestBodyBuilder: ...
    def email_list(self, email_list: list[str]) -> BatchGetIdTalentRequestBodyBuilder: ...
    def identification_type(self, identification_type: int) -> BatchGetIdTalentRequestBodyBuilder: ...
    def identification_number_list(self, identification_number_list: list[str]) -> BatchGetIdTalentRequestBodyBuilder: ...
    def build(self) -> BatchGetIdTalentRequestBody: ...
