from .batch_query_external_offer_request_body import BatchQueryExternalOfferRequestBody as BatchQueryExternalOfferRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchQueryExternalOfferRequest(BaseRequest):
    external_application_id: str | None
    page_size: int | None
    page_token: str | None
    request_body: BatchQueryExternalOfferRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchQueryExternalOfferRequestBuilder: ...

class BatchQueryExternalOfferRequestBuilder:
    def __init__(self) -> None: ...
    def external_application_id(self, external_application_id: str) -> BatchQueryExternalOfferRequestBuilder: ...
    def page_size(self, page_size: int) -> BatchQueryExternalOfferRequestBuilder: ...
    def page_token(self, page_token: str) -> BatchQueryExternalOfferRequestBuilder: ...
    def request_body(self, request_body: BatchQueryExternalOfferRequestBody) -> BatchQueryExternalOfferRequestBuilder: ...
    def build(self) -> BatchQueryExternalOfferRequest: ...
