from .batch_get_id_talent_request_body import BatchGetIdTalentRequestBody as BatchGetIdTalentRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchGetIdTalentRequest(BaseRequest):
    request_body: BatchGetIdTalentRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchGetIdTalentRequestBuilder: ...

class BatchGetIdTalentRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: BatchGetIdTalentRequestBody) -> BatchGetIdTalentRequestBuilder: ...
    def build(self) -> BatchGetIdTalentRequest: ...
