from .batch_delete_eco_exam_paper_request_body import BatchDeleteEcoExamPaperRequestBody as BatchDeleteEcoExamPaperRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class BatchDeleteEcoExamPaperRequest(BaseRequest):
    request_body: BatchDeleteEcoExamPaperRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> BatchDeleteEcoExamPaperRequestBuilder: ...

class BatchDeleteEcoExamPaperRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: BatchDeleteEcoExamPaperRequestBody) -> BatchDeleteEcoExamPaperRequestBuilder: ...
    def build(self) -> BatchDeleteEcoExamPaperRequest: ...
