from lark_oapi.core.construct import init as init

class BatchDeleteEcoExamPaperResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> BatchDeleteEcoExamPaperResponseBodyBuilder: ...

class BatchDeleteEcoExamPaperResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> BatchDeleteEcoExamPaperResponseBody: ...
