from lark_oapi.core.construct import init as init

class CancelOnboardApplicationResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CancelOnboardApplicationResponseBodyBuilder: ...

class CancelOnboardApplicationResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> CancelOnboardApplicationResponseBody: ...
