from lark_oapi.core.construct import init as init

class CandidateTagFilter:
    match_type: int | None
    candidate_tag_id: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CandidateTagFilterBuilder: ...

class CandidateTagFilterBuilder:
    def __init__(self) -> None: ...
    def match_type(self, match_type: int) -> CandidateTagFilterBuilder: ...
    def candidate_tag_id(self, candidate_tag_id: list[str]) -> CandidateTagFilterBuilder: ...
    def build(self) -> CandidateTagFilter: ...
