from lark_oapi.core.construct import init as init

class CareerInfo:
    career_type: int | None
    company: str | None
    desc: str | None
    end_time: int | None
    start_time: int | None
    title: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CareerInfoBuilder: ...

class CareerInfoBuilder:
    def __init__(self) -> None: ...
    def career_type(self, career_type: int) -> CareerInfoBuilder: ...
    def company(self, company: str) -> CareerInfoBuilder: ...
    def desc(self, desc: str) -> CareerInfoBuilder: ...
    def end_time(self, end_time: int) -> CareerInfoBuilder: ...
    def start_time(self, start_time: int) -> CareerInfoBuilder: ...
    def title(self, title: str) -> CareerInfoBuilder: ...
    def build(self) -> CareerInfo: ...
