from lark_oapi.core.construct import init as init

class CertificateInfo:
    desc: str | None
    name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CertificateInfoBuilder: ...

class CertificateInfoBuilder:
    def __init__(self) -> None: ...
    def desc(self, desc: str) -> CertificateInfoBuilder: ...
    def name(self, name: str) -> CertificateInfoBuilder: ...
    def build(self) -> CertificateInfo: ...
