from .change_talent_block_talent_blocklist_request_body import ChangeTalentBlockTalentBlocklistRequestBody as ChangeTalentBlockTalentBlocklistRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ChangeTalentBlockTalentBlocklistRequest(BaseRequest):
    request_body: ChangeTalentBlockTalentBlocklistRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ChangeTalentBlockTalentBlocklistRequestBuilder: ...

class ChangeTalentBlockTalentBlocklistRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: ChangeTalentBlockTalentBlocklistRequestBody) -> ChangeTalentBlockTalentBlocklistRequestBuilder: ...
    def build(self) -> ChangeTalentBlockTalentBlocklistRequest: ...
