from lark_oapi.core.construct import init as init

class CloseJobResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CloseJobResponseBodyBuilder: ...

class CloseJobResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> CloseJobResponseBody: ...
