from .combined_create_talent_request_body import CombinedCreateTalentRequestBody as CombinedCreateTalentRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CombinedCreateTalentRequest(BaseRequest):
    user_id_type: str | None
    request_body: CombinedCreateTalentRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CombinedCreateTalentRequestBuilder: ...

class CombinedCreateTalentRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> CombinedCreateTalentRequestBuilder: ...
    def request_body(self, request_body: CombinedCreateTalentRequestBody) -> CombinedCreateTalentRequestBuilder: ...
    def build(self) -> CombinedCreateTalentRequest: ...
