from .talent_combined_award_info import TalentCombinedAwardInfo as TalentCombinedAwardInfo
from .talent_combined_basic_info import TalentCombinedBasicInfo as TalentCombinedBasicInfo
from .talent_combined_career_info import TalentCombinedCareerInfo as TalentCombinedCareerInfo
from .talent_combined_education_info import TalentCombinedEducationInfo as TalentCombinedEducationInfo
from .talent_combined_language_info import TalentCombinedLanguageInfo as TalentCombinedLanguageInfo
from .talent_combined_project_info import TalentCombinedProjectInfo as TalentCombinedProjectInfo
from .talent_combined_sns_info import TalentCombinedSnsInfo as TalentCombinedSnsInfo
from .talent_combined_work_info import TalentCombinedWorkInfo as TalentCombinedWorkInfo
from .talent_customized_data_object_value import TalentCustomizedDataObjectValue as TalentCustomizedDataObjectValue
from .talent_self_evaluation import TalentSelfEvaluation as TalentSelfEvaluation
from lark_oapi.core.construct import init as init

class CombinedUpdateTalentRequestBody:
    talent_id: str | None
    init_source_id: str | None
    folder_id_list: list[str] | None
    operator_id: str | None
    operator_account_type: int | None
    resume_attachment_id: str | None
    basic_info: TalentCombinedBasicInfo | None
    education_list: list[TalentCombinedEducationInfo] | None
    career_list: list[TalentCombinedCareerInfo] | None
    project_list: list[TalentCombinedProjectInfo] | None
    works_list: list[TalentCombinedWorkInfo] | None
    award_list: list[TalentCombinedAwardInfo] | None
    language_list: list[TalentCombinedLanguageInfo] | None
    sns_list: list[TalentCombinedSnsInfo] | None
    preferred_city_code_list: list[str] | None
    self_evaluation: TalentSelfEvaluation | None
    customized_data: list[TalentCustomizedDataObjectValue] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CombinedUpdateTalentRequestBodyBuilder: ...

class CombinedUpdateTalentRequestBodyBuilder:
    def __init__(self) -> None: ...
    def talent_id(self, talent_id: str) -> CombinedUpdateTalentRequestBodyBuilder: ...
    def init_source_id(self, init_source_id: str) -> CombinedUpdateTalentRequestBodyBuilder: ...
    def folder_id_list(self, folder_id_list: list[str]) -> CombinedUpdateTalentRequestBodyBuilder: ...
    def operator_id(self, operator_id: str) -> CombinedUpdateTalentRequestBodyBuilder: ...
    def operator_account_type(self, operator_account_type: int) -> CombinedUpdateTalentRequestBodyBuilder: ...
    def resume_attachment_id(self, resume_attachment_id: str) -> CombinedUpdateTalentRequestBodyBuilder: ...
    def basic_info(self, basic_info: TalentCombinedBasicInfo) -> CombinedUpdateTalentRequestBodyBuilder: ...
    def education_list(self, education_list: list[TalentCombinedEducationInfo]) -> CombinedUpdateTalentRequestBodyBuilder: ...
    def career_list(self, career_list: list[TalentCombinedCareerInfo]) -> CombinedUpdateTalentRequestBodyBuilder: ...
    def project_list(self, project_list: list[TalentCombinedProjectInfo]) -> CombinedUpdateTalentRequestBodyBuilder: ...
    def works_list(self, works_list: list[TalentCombinedWorkInfo]) -> CombinedUpdateTalentRequestBodyBuilder: ...
    def award_list(self, award_list: list[TalentCombinedAwardInfo]) -> CombinedUpdateTalentRequestBodyBuilder: ...
    def language_list(self, language_list: list[TalentCombinedLanguageInfo]) -> CombinedUpdateTalentRequestBodyBuilder: ...
    def sns_list(self, sns_list: list[TalentCombinedSnsInfo]) -> CombinedUpdateTalentRequestBodyBuilder: ...
    def preferred_city_code_list(self, preferred_city_code_list: list[str]) -> CombinedUpdateTalentRequestBodyBuilder: ...
    def self_evaluation(self, self_evaluation: TalentSelfEvaluation) -> CombinedUpdateTalentRequestBodyBuilder: ...
    def customized_data(self, customized_data: list[TalentCustomizedDataObjectValue]) -> CombinedUpdateTalentRequestBodyBuilder: ...
    def build(self) -> CombinedUpdateTalentRequestBody: ...
