from .common_schema_option import CommonSchemaOption as CommonSchemaOption
from lark_oapi.core.construct import init as init

class CommonSchemaConfig:
    options: list[CommonSchemaOption] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CommonSchemaConfigBuilder: ...

class CommonSchemaConfigBuilder:
    def __init__(self) -> None: ...
    def options(self, options: list[CommonSchemaOption]) -> CommonSchemaConfigBuilder: ...
    def build(self) -> CommonSchemaConfig: ...
