from .common_schema_config import CommonSchemaConfig as CommonSchemaConfig
from lark_oapi.core.construct import init as init

class CommonSchemaSetting:
    object_type: int | None
    config: CommonSchemaConfig | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CommonSchemaSettingBuilder: ...

class CommonSchemaSettingBuilder:
    def __init__(self) -> None: ...
    def object_type(self, object_type: int) -> CommonSchemaSettingBuilder: ...
    def config(self, config: CommonSchemaConfig) -> CommonSchemaSettingBuilder: ...
    def build(self) -> CommonSchemaSetting: ...
