from .range_filter import RangeFilter as RangeFilter
from lark_oapi.core.construct import init as init

class CommonFilter:
    key: str | None
    value_type: int | None
    value_list: list[str] | None
    range_filter: RangeFilter | None
    user_id_list: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CommonFilterBuilder: ...

class CommonFilterBuilder:
    def __init__(self) -> None: ...
    def key(self, key: str) -> CommonFilterBuilder: ...
    def value_type(self, value_type: int) -> CommonFilterBuilder: ...
    def value_list(self, value_list: list[str]) -> CommonFilterBuilder: ...
    def range_filter(self, range_filter: RangeFilter) -> CommonFilterBuilder: ...
    def user_id_list(self, user_id_list: list[str]) -> CommonFilterBuilder: ...
    def build(self) -> CommonFilter: ...
