from .common_schema_child import CommonSchemaChild as CommonSchemaChild
from .common_schema_setting import CommonSchemaSetting as CommonSchemaSetting
from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class CommonSchema:
    id: str | None
    name: I18n | None
    description: I18n | None
    setting: CommonSchemaSetting | None
    is_customized: bool | None
    is_required: bool | None
    is_visible: bool | None
    active_status: int | None
    children_list: list[CommonSchemaChild] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CommonSchemaBuilder: ...

class CommonSchemaBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> CommonSchemaBuilder: ...
    def name(self, name: I18n) -> CommonSchemaBuilder: ...
    def description(self, description: I18n) -> CommonSchemaBuilder: ...
    def setting(self, setting: CommonSchemaSetting) -> CommonSchemaBuilder: ...
    def is_customized(self, is_customized: bool) -> CommonSchemaBuilder: ...
    def is_required(self, is_required: bool) -> CommonSchemaBuilder: ...
    def is_visible(self, is_visible: bool) -> CommonSchemaBuilder: ...
    def active_status(self, active_status: int) -> CommonSchemaBuilder: ...
    def children_list(self, children_list: list[CommonSchemaChild]) -> CommonSchemaBuilder: ...
    def build(self) -> CommonSchema: ...
