from .common_schema_setting import CommonSchemaSetting as CommonSchemaSetting
from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class CommonSchemaChild:
    id: str | None
    name: I18n | None
    description: I18n | None
    setting: CommonSchemaSetting | None
    parent_id: str | None
    is_customized: bool | None
    is_required: bool | None
    is_visible: bool | None
    active_status: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CommonSchemaChildBuilder: ...

class CommonSchemaChildBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> CommonSchemaChildBuilder: ...
    def name(self, name: I18n) -> CommonSchemaChildBuilder: ...
    def description(self, description: I18n) -> CommonSchemaChildBuilder: ...
    def setting(self, setting: CommonSchemaSetting) -> CommonSchemaChildBuilder: ...
    def parent_id(self, parent_id: str) -> CommonSchemaChildBuilder: ...
    def is_customized(self, is_customized: bool) -> CommonSchemaChildBuilder: ...
    def is_required(self, is_required: bool) -> CommonSchemaChildBuilder: ...
    def is_visible(self, is_visible: bool) -> CommonSchemaChildBuilder: ...
    def active_status(self, active_status: int) -> CommonSchemaChildBuilder: ...
    def build(self) -> CommonSchemaChild: ...
