from lark_oapi.core.construct import init as init

class ConfigJobRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ConfigJobRequestBodyBuilder: ...

class ConfigJobRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ConfigJobRequestBody: ...
