from lark_oapi.core.construct import init as init

class ContractPeriodInfo:
    period_type: int | None
    period: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ContractPeriodInfoBuilder: ...

class ContractPeriodInfoBuilder:
    def __init__(self) -> None: ...
    def period_type(self, period_type: int) -> ContractPeriodInfoBuilder: ...
    def period(self, period: int) -> ContractPeriodInfoBuilder: ...
    def build(self) -> ContractPeriodInfo: ...
