from lark_oapi.core.construct import init as init

class CreateAttachmentResponseBody:
    id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateAttachmentResponseBodyBuilder: ...

class CreateAttachmentResponseBodyBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> CreateAttachmentResponseBodyBuilder: ...
    def build(self) -> CreateAttachmentResponseBody: ...
