from lark_oapi.core.construct import init as init

class CreateTripartiteAgreementResponseBody:
    id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateTripartiteAgreementResponseBodyBuilder: ...

class CreateTripartiteAgreementResponseBodyBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> CreateTripartiteAgreementResponseBodyBuilder: ...
    def build(self) -> CreateTripartiteAgreementResponseBody: ...
