from lark_oapi.core.construct import init as init

class CreateApplicationResponseBody:
    id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateApplicationResponseBodyBuilder: ...

class CreateApplicationResponseBodyBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> CreateApplicationResponseBodyBuilder: ...
    def build(self) -> CreateApplicationResponseBody: ...
