from lark_oapi.core.construct import init as init

class CreateEcoAccountCustomFieldResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateEcoAccountCustomFieldResponseBodyBuilder: ...

class CreateEcoAccountCustomFieldResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> CreateEcoAccountCustomFieldResponseBody: ...
