from .eco_account_custom_field import EcoAccountCustomField as EcoAccountCustomField
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateEcoAccountCustomFieldRequest(BaseRequest):
    request_body: EcoAccountCustomField | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateEcoAccountCustomFieldRequestBuilder: ...

class CreateEcoAccountCustomFieldRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: EcoAccountCustomField) -> CreateEcoAccountCustomFieldRequestBuilder: ...
    def build(self) -> CreateEcoAccountCustomFieldRequest: ...
