from .create_talent_external_info_request_body import CreateTalentExternalInfoRequestBody as CreateTalentExternalInfoRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateTalentExternalInfoRequest(BaseRequest):
    talent_id: str | None
    request_body: CreateTalentExternalInfoRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateTalentExternalInfoRequestBuilder: ...

class CreateTalentExternalInfoRequestBuilder:
    def __init__(self) -> None: ...
    def talent_id(self, talent_id: str) -> CreateTalentExternalInfoRequestBuilder: ...
    def request_body(self, request_body: CreateTalentExternalInfoRequestBody) -> CreateTalentExternalInfoRequestBuilder: ...
    def build(self) -> CreateTalentExternalInfoRequest: ...
