from lark_oapi.core.construct import init as init

class CreateExamResponseBody:
    exam_id: str | None
    application_id: str | None
    exam_resource_name: str | None
    score: float | None
    uuid: str | None
    operator_id: str | None
    operate_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateExamResponseBodyBuilder: ...

class CreateExamResponseBodyBuilder:
    def __init__(self) -> None: ...
    def exam_id(self, exam_id: str) -> CreateExamResponseBodyBuilder: ...
    def application_id(self, application_id: str) -> CreateExamResponseBodyBuilder: ...
    def exam_resource_name(self, exam_resource_name: str) -> CreateExamResponseBodyBuilder: ...
    def score(self, score: float) -> CreateExamResponseBodyBuilder: ...
    def uuid(self, uuid: str) -> CreateExamResponseBodyBuilder: ...
    def operator_id(self, operator_id: str) -> CreateExamResponseBodyBuilder: ...
    def operate_time(self, operate_time: str) -> CreateExamResponseBodyBuilder: ...
    def build(self) -> CreateExamResponseBody: ...
