from .external_offer import ExternalOffer as ExternalOffer
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateExternalOfferRequest(BaseRequest):
    request_body: ExternalOffer | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateExternalOfferRequestBuilder: ...

class CreateExternalOfferRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: ExternalOffer) -> CreateExternalOfferRequestBuilder: ...
    def build(self) -> CreateExternalOfferRequest: ...
