from .external_application import ExternalApplication as ExternalApplication
from lark_oapi.core.construct import init as init

class CreateExternalApplicationResponseBody:
    external_application: ExternalApplication | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateExternalApplicationResponseBodyBuilder: ...

class CreateExternalApplicationResponseBodyBuilder:
    def __init__(self) -> None: ...
    def external_application(self, external_application: ExternalApplication) -> CreateExternalApplicationResponseBodyBuilder: ...
    def build(self) -> CreateExternalApplicationResponseBody: ...
