from .job_requirement_dto import JobRequirementDto as JobRequirementDto
from lark_oapi.core.construct import init as init

class CreateJobRequirementResponseBody:
    job_requirement: JobRequirementDto | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateJobRequirementResponseBodyBuilder: ...

class CreateJobRequirementResponseBodyBuilder:
    def __init__(self) -> None: ...
    def job_requirement(self, job_requirement: JobRequirementDto) -> CreateJobRequirementResponseBodyBuilder: ...
    def build(self) -> CreateJobRequirementResponseBody: ...
