from .eco_background_check_package import EcoBackgroundCheckPackage as EcoBackgroundCheckPackage
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateEcoBackgroundCheckPackageRequest(BaseRequest):
    request_body: EcoBackgroundCheckPackage | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateEcoBackgroundCheckPackageRequestBuilder: ...

class CreateEcoBackgroundCheckPackageRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: EcoBackgroundCheckPackage) -> CreateEcoBackgroundCheckPackageRequestBuilder: ...
    def build(self) -> CreateEcoBackgroundCheckPackageRequest: ...
