from lark_oapi.core.construct import init as init

class CreateWebsiteChannelResponseBody:
    id: str | None
    name: str | None
    link: str | None
    code: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateWebsiteChannelResponseBodyBuilder: ...

class CreateWebsiteChannelResponseBodyBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> CreateWebsiteChannelResponseBodyBuilder: ...
    def name(self, name: str) -> CreateWebsiteChannelResponseBodyBuilder: ...
    def link(self, link: str) -> CreateWebsiteChannelResponseBodyBuilder: ...
    def code(self, code: str) -> CreateWebsiteChannelResponseBodyBuilder: ...
    def build(self) -> CreateWebsiteChannelResponseBody: ...
