from .external_interview import ExternalInterview as ExternalInterview
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class CreateExternalInterviewRequest(BaseRequest):
    request_body: ExternalInterview | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> CreateExternalInterviewRequestBuilder: ...

class CreateExternalInterviewRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: ExternalInterview) -> CreateExternalInterviewRequestBuilder: ...
    def build(self) -> CreateExternalInterviewRequest: ...
