from .mobile import Mobile as Mobile
from lark_oapi.core.construct import init as init

class CreateReferralAccountRequestBody:
    mobile: Mobile | None
    email: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateReferralAccountRequestBodyBuilder: ...

class CreateReferralAccountRequestBodyBuilder:
    def __init__(self) -> None: ...
    def mobile(self, mobile: Mobile) -> CreateReferralAccountRequestBodyBuilder: ...
    def email(self, email: str) -> CreateReferralAccountRequestBodyBuilder: ...
    def build(self) -> CreateReferralAccountRequestBody: ...
