from .website_user import WebsiteUser as WebsiteUser
from lark_oapi.core.construct import init as init

class CreateWebsiteSiteUserResponseBody:
    site_user: WebsiteUser | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateWebsiteSiteUserResponseBodyBuilder: ...

class CreateWebsiteSiteUserResponseBodyBuilder:
    def __init__(self) -> None: ...
    def site_user(self, site_user: WebsiteUser) -> CreateWebsiteSiteUserResponseBodyBuilder: ...
    def build(self) -> CreateWebsiteSiteUserResponseBody: ...
