from lark_oapi.core.construct import init as init

class CreateExternalReferralRewardResponseBody:
    id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateExternalReferralRewardResponseBodyBuilder: ...

class CreateExternalReferralRewardResponseBodyBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> CreateExternalReferralRewardResponseBodyBuilder: ...
    def build(self) -> CreateExternalReferralRewardResponseBody: ...
