from lark_oapi.core.construct import init as init

class CreateApplicationRequestBody:
    talent_id: str | None
    job_id: str | None
    user_id: str | None
    resume_source_id: str | None
    application_preferred_city_code_list: list[str] | None
    delivery_type: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> CreateApplicationRequestBodyBuilder: ...

class CreateApplicationRequestBodyBuilder:
    def __init__(self) -> None: ...
    def talent_id(self, talent_id: str) -> CreateApplicationRequestBodyBuilder: ...
    def job_id(self, job_id: str) -> CreateApplicationRequestBodyBuilder: ...
    def user_id(self, user_id: str) -> CreateApplicationRequestBodyBuilder: ...
    def resume_source_id(self, resume_source_id: str) -> CreateApplicationRequestBodyBuilder: ...
    def application_preferred_city_code_list(self, application_preferred_city_code_list: list[str]) -> CreateApplicationRequestBodyBuilder: ...
    def delivery_type(self, delivery_type: int) -> CreateApplicationRequestBodyBuilder: ...
    def build(self) -> CreateApplicationRequestBody: ...
