from lark_oapi.core.construct import init as init

class DeactivateReferralAccountRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeactivateReferralAccountRequestBodyBuilder: ...

class DeactivateReferralAccountRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeactivateReferralAccountRequestBody: ...
