from lark_oapi.core.construct import init as init

class DeleteNoteResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteNoteResponseBodyBuilder: ...

class DeleteNoteResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteNoteResponseBody: ...
