from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteJobRequirementRequest(BaseRequest):
    job_requirement_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteJobRequirementRequestBuilder: ...

class DeleteJobRequirementRequestBuilder:
    def __init__(self) -> None: ...
    def job_requirement_id(self, job_requirement_id: str) -> DeleteJobRequirementRequestBuilder: ...
    def build(self) -> DeleteJobRequirementRequest: ...
