from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteNoteRequest(BaseRequest):
    note_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteNoteRequestBuilder: ...

class DeleteNoteRequestBuilder:
    def __init__(self) -> None: ...
    def note_id(self, note_id: str) -> DeleteNoteRequestBuilder: ...
    def build(self) -> DeleteNoteRequest: ...
