from lark_oapi.core.construct import init as init

class DeleteTripartiteAgreementRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteTripartiteAgreementRequestBodyBuilder: ...

class DeleteTripartiteAgreementRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteTripartiteAgreementRequestBody: ...
