from lark_oapi.core.construct import init as init

class DeleteJobRequirementResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteJobRequirementResponseBodyBuilder: ...

class DeleteJobRequirementResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteJobRequirementResponseBody: ...
