from lark_oapi.core.construct import init as init

class DeleteNoteRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteNoteRequestBodyBuilder: ...

class DeleteNoteRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteNoteRequestBody: ...
