from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteExternalApplicationRequest(BaseRequest):
    talent_id: str | None
    external_application_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteExternalApplicationRequestBuilder: ...

class DeleteExternalApplicationRequestBuilder:
    def __init__(self) -> None: ...
    def talent_id(self, talent_id: str) -> DeleteExternalApplicationRequestBuilder: ...
    def external_application_id(self, external_application_id: str) -> DeleteExternalApplicationRequestBuilder: ...
    def build(self) -> DeleteExternalApplicationRequest: ...
