from lark_oapi.core.construct import init as init

class DeleteExternalReferralRewardRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteExternalReferralRewardRequestBodyBuilder: ...

class DeleteExternalReferralRewardRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteExternalReferralRewardRequestBody: ...
