from lark_oapi.core.construct import init as init

class DeleteExternalReferralRewardResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteExternalReferralRewardResponseBodyBuilder: ...

class DeleteExternalReferralRewardResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteExternalReferralRewardResponseBody: ...
