from lark_oapi.core.construct import init as init

class DeleteExternalOfferRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteExternalOfferRequestBodyBuilder: ...

class DeleteExternalOfferRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteExternalOfferRequestBody: ...
