from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class DeleteExternalBackgroundCheckRequest(BaseRequest):
    external_background_check_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> DeleteExternalBackgroundCheckRequestBuilder: ...

class DeleteExternalBackgroundCheckRequestBuilder:
    def __init__(self) -> None: ...
    def external_background_check_id(self, external_background_check_id: str) -> DeleteExternalBackgroundCheckRequestBuilder: ...
    def build(self) -> DeleteExternalBackgroundCheckRequest: ...
