from lark_oapi.core.construct import init as init

class DeleteExternalBackgroundCheckRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DeleteExternalBackgroundCheckRequestBodyBuilder: ...

class DeleteExternalBackgroundCheckRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> DeleteExternalBackgroundCheckRequestBody: ...
