from .di_data import DiData as DiData
from lark_oapi.core.construct import init as init

class DiInfo:
    id: str | None
    application_id: str | None
    talent_id: str | None
    source_type: int | None
    create_time: str | None
    update_time: str | None
    di_data: list[DiData] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DiInfoBuilder: ...

class DiInfoBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> DiInfoBuilder: ...
    def application_id(self, application_id: str) -> DiInfoBuilder: ...
    def talent_id(self, talent_id: str) -> DiInfoBuilder: ...
    def source_type(self, source_type: int) -> DiInfoBuilder: ...
    def create_time(self, create_time: str) -> DiInfoBuilder: ...
    def update_time(self, update_time: str) -> DiInfoBuilder: ...
    def di_data(self, di_data: list[DiData]) -> DiInfoBuilder: ...
    def build(self) -> DiInfo: ...
