from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class DimensionOption:
    id: str | None
    name: I18n | None
    score_val: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DimensionOptionBuilder: ...

class DimensionOptionBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> DimensionOptionBuilder: ...
    def name(self, name: I18n) -> DimensionOptionBuilder: ...
    def score_val(self, score_val: int) -> DimensionOptionBuilder: ...
    def build(self) -> DimensionOption: ...
