from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class DimensionAbility:
    id: str | None
    name: I18n | None
    description: I18n | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> DimensionAbilityBuilder: ...

class DimensionAbilityBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> DimensionAbilityBuilder: ...
    def name(self, name: I18n) -> DimensionAbilityBuilder: ...
    def description(self, description: I18n) -> DimensionAbilityBuilder: ...
    def build(self) -> DimensionAbility: ...
