from lark_oapi.core.construct import init as init

class EcoBackgroundCheckReportFile:
    report_name: str | None
    report_url: str | None
    report_url_type: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EcoBackgroundCheckReportFileBuilder: ...

class EcoBackgroundCheckReportFileBuilder:
    def __init__(self) -> None: ...
    def report_name(self, report_name: str) -> EcoBackgroundCheckReportFileBuilder: ...
    def report_url(self, report_url: str) -> EcoBackgroundCheckReportFileBuilder: ...
    def report_url_type(self, report_url_type: int) -> EcoBackgroundCheckReportFileBuilder: ...
    def build(self) -> EcoBackgroundCheckReportFile: ...
