from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class EcoAccountCustomFieldData:
    key: str | None
    name: I18n | None
    is_required: bool | None
    description: I18n | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EcoAccountCustomFieldDataBuilder: ...

class EcoAccountCustomFieldDataBuilder:
    def __init__(self) -> None: ...
    def key(self, key: str) -> EcoAccountCustomFieldDataBuilder: ...
    def name(self, name: I18n) -> EcoAccountCustomFieldDataBuilder: ...
    def is_required(self, is_required: bool) -> EcoAccountCustomFieldDataBuilder: ...
    def description(self, description: I18n) -> EcoAccountCustomFieldDataBuilder: ...
    def build(self) -> EcoAccountCustomFieldData: ...
