from lark_oapi.core.construct import init as init

class EcoExamLoginInfo:
    exam_url: str | None
    username: str | None
    password: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EcoExamLoginInfoBuilder: ...

class EcoExamLoginInfoBuilder:
    def __init__(self) -> None: ...
    def exam_url(self, exam_url: str) -> EcoExamLoginInfoBuilder: ...
    def username(self, username: str) -> EcoExamLoginInfoBuilder: ...
    def password(self, password: str) -> EcoExamLoginInfoBuilder: ...
    def build(self) -> EcoExamLoginInfo: ...
