from .eco_background_check_package_additional_item import EcoBackgroundCheckPackageAdditionalItem as EcoBackgroundCheckPackageAdditionalItem
from .eco_background_check_package_data import EcoBackgroundCheckPackageData as EcoBackgroundCheckPackageData
from lark_oapi.core.construct import init as init

class EcoBackgroundCheckPackage:
    account_id: str | None
    package_list: list[EcoBackgroundCheckPackageData] | None
    additional_item_list: list[EcoBackgroundCheckPackageAdditionalItem] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EcoBackgroundCheckPackageBuilder: ...

class EcoBackgroundCheckPackageBuilder:
    def __init__(self) -> None: ...
    def account_id(self, account_id: str) -> EcoBackgroundCheckPackageBuilder: ...
    def package_list(self, package_list: list[EcoBackgroundCheckPackageData]) -> EcoBackgroundCheckPackageBuilder: ...
    def additional_item_list(self, additional_item_list: list[EcoBackgroundCheckPackageAdditionalItem]) -> EcoBackgroundCheckPackageBuilder: ...
    def build(self) -> EcoBackgroundCheckPackage: ...
