from lark_oapi.core.construct import init as init

class EcoBackgroundCheckPackageAdditionalItem:
    id: str | None
    name: str | None
    description: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EcoBackgroundCheckPackageAdditionalItemBuilder: ...

class EcoBackgroundCheckPackageAdditionalItemBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> EcoBackgroundCheckPackageAdditionalItemBuilder: ...
    def name(self, name: str) -> EcoBackgroundCheckPackageAdditionalItemBuilder: ...
    def description(self, description: str) -> EcoBackgroundCheckPackageAdditionalItemBuilder: ...
    def build(self) -> EcoBackgroundCheckPackageAdditionalItem: ...
