from lark_oapi.core.construct import init as init

class EcoAccountCustomFieldEventData:
    key: str | None
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EcoAccountCustomFieldEventDataBuilder: ...

class EcoAccountCustomFieldEventDataBuilder:
    def __init__(self) -> None: ...
    def key(self, key: str) -> EcoAccountCustomFieldEventDataBuilder: ...
    def value(self, value: str) -> EcoAccountCustomFieldEventDataBuilder: ...
    def build(self) -> EcoAccountCustomFieldEventData: ...
