from .eco_background_check_custom_field_data import EcoBackgroundCheckCustomFieldData as EcoBackgroundCheckCustomFieldData
from lark_oapi.core.construct import init as init

class EcoBackgroundCheckCustomField:
    account_id: str | None
    custom_field_list: list[EcoBackgroundCheckCustomFieldData] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EcoBackgroundCheckCustomFieldBuilder: ...

class EcoBackgroundCheckCustomFieldBuilder:
    def __init__(self) -> None: ...
    def account_id(self, account_id: str) -> EcoBackgroundCheckCustomFieldBuilder: ...
    def custom_field_list(self, custom_field_list: list[EcoBackgroundCheckCustomFieldData]) -> EcoBackgroundCheckCustomFieldBuilder: ...
    def build(self) -> EcoBackgroundCheckCustomField: ...
