from lark_oapi.core.construct import init as init

class EducationInfo:
    degree: int | None
    end_time: int | None
    field_of_study: str | None
    school: str | None
    start_time: int | None
    education_type: int | None
    academic_ranking: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EducationInfoBuilder: ...

class EducationInfoBuilder:
    def __init__(self) -> None: ...
    def degree(self, degree: int) -> EducationInfoBuilder: ...
    def end_time(self, end_time: int) -> EducationInfoBuilder: ...
    def field_of_study(self, field_of_study: str) -> EducationInfoBuilder: ...
    def school(self, school: str) -> EducationInfoBuilder: ...
    def start_time(self, start_time: int) -> EducationInfoBuilder: ...
    def education_type(self, education_type: int) -> EducationInfoBuilder: ...
    def academic_ranking(self, academic_ranking: int) -> EducationInfoBuilder: ...
    def build(self) -> EducationInfo: ...
