from lark_oapi.core.construct import init as init

class EmployeeOverboardInfo:
    actual_overboard_time: int | None
    overboard_note: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EmployeeOverboardInfoBuilder: ...

class EmployeeOverboardInfoBuilder:
    def __init__(self) -> None: ...
    def actual_overboard_time(self, actual_overboard_time: int) -> EmployeeOverboardInfoBuilder: ...
    def overboard_note(self, overboard_note: str) -> EmployeeOverboardInfoBuilder: ...
    def build(self) -> EmployeeOverboardInfo: ...
