from lark_oapi.core.construct import init as init

class EmployeeConversionInfo:
    actual_conversion_time: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EmployeeConversionInfoBuilder: ...

class EmployeeConversionInfoBuilder:
    def __init__(self) -> None: ...
    def actual_conversion_time(self, actual_conversion_time: int) -> EmployeeConversionInfoBuilder: ...
    def build(self) -> EmployeeConversionInfo: ...
