from .enable_referral_account_request_body import EnableReferralAccountRequestBody as EnableReferralAccountRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class EnableReferralAccountRequest(BaseRequest):
    user_id_type: str | None
    request_body: EnableReferralAccountRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> EnableReferralAccountRequestBuilder: ...

class EnableReferralAccountRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> EnableReferralAccountRequestBuilder: ...
    def request_body(self, request_body: EnableReferralAccountRequestBody) -> EnableReferralAccountRequestBuilder: ...
    def build(self) -> EnableReferralAccountRequest: ...
