from .account import Account as Account
from lark_oapi.core.construct import init as init

class EnableReferralAccountResponseBody:
    account: Account | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EnableReferralAccountResponseBodyBuilder: ...

class EnableReferralAccountResponseBodyBuilder:
    def __init__(self) -> None: ...
    def account(self, account: Account) -> EnableReferralAccountResponseBodyBuilder: ...
    def build(self) -> EnableReferralAccountResponseBody: ...
