from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class EntityInfo:
    code: str | None
    name: I18n | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> EntityInfoBuilder: ...

class EntityInfoBuilder:
    def __init__(self) -> None: ...
    def code(self, code: str) -> EntityInfoBuilder: ...
    def name(self, name: I18n) -> EntityInfoBuilder: ...
    def build(self) -> EntityInfo: ...
