from lark_oapi.core.construct import init as init

class ExternalCommonAttachment:
    id: str | None
    name: str | None
    size: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ExternalCommonAttachmentBuilder: ...

class ExternalCommonAttachmentBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> ExternalCommonAttachmentBuilder: ...
    def name(self, name: str) -> ExternalCommonAttachmentBuilder: ...
    def size(self, size: int) -> ExternalCommonAttachmentBuilder: ...
    def build(self) -> ExternalCommonAttachment: ...
