from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetDetailJobRequest(BaseRequest):
    user_id_type: str | None
    department_id_type: str | None
    job_level_id_type: str | None
    job_family_id_type: str | None
    job_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetDetailJobRequestBuilder: ...

class GetDetailJobRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> GetDetailJobRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> GetDetailJobRequestBuilder: ...
    def job_level_id_type(self, job_level_id_type: str) -> GetDetailJobRequestBuilder: ...
    def job_family_id_type(self, job_family_id_type: str) -> GetDetailJobRequestBuilder: ...
    def job_id(self, job_id: str) -> GetDetailJobRequestBuilder: ...
    def build(self) -> GetDetailJobRequest: ...
