from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetByApplicationEmployeeRequest(BaseRequest):
    application_id: str | None
    user_id_type: str | None
    department_id_type: str | None
    job_level_id_type: str | None
    job_family_id_type: str | None
    employee_type_id_type: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetByApplicationEmployeeRequestBuilder: ...

class GetByApplicationEmployeeRequestBuilder:
    def __init__(self) -> None: ...
    def application_id(self, application_id: str) -> GetByApplicationEmployeeRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> GetByApplicationEmployeeRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> GetByApplicationEmployeeRequestBuilder: ...
    def job_level_id_type(self, job_level_id_type: str) -> GetByApplicationEmployeeRequestBuilder: ...
    def job_family_id_type(self, job_family_id_type: str) -> GetByApplicationEmployeeRequestBuilder: ...
    def employee_type_id_type(self, employee_type_id_type: str) -> GetByApplicationEmployeeRequestBuilder: ...
    def build(self) -> GetByApplicationEmployeeRequest: ...
