from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetReferralWebsiteJobPostRequest(BaseRequest):
    user_id_type: str | None
    department_id_type: str | None
    job_level_id_type: str | None
    job_post_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetReferralWebsiteJobPostRequestBuilder: ...

class GetReferralWebsiteJobPostRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> GetReferralWebsiteJobPostRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> GetReferralWebsiteJobPostRequestBuilder: ...
    def job_level_id_type(self, job_level_id_type: str) -> GetReferralWebsiteJobPostRequestBuilder: ...
    def job_post_id(self, job_post_id: str) -> GetReferralWebsiteJobPostRequestBuilder: ...
    def build(self) -> GetReferralWebsiteJobPostRequest: ...
