from lark_oapi.core.construct import init as init

class GetNoteRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetNoteRequestBodyBuilder: ...

class GetNoteRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetNoteRequestBody: ...
