from lark_oapi.core.construct import init as init

class GetAgencyRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetAgencyRequestBodyBuilder: ...

class GetAgencyRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetAgencyRequestBody: ...
