from lark_oapi.core.construct import init as init

class GetDetailApplicationRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetDetailApplicationRequestBodyBuilder: ...

class GetDetailApplicationRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetDetailApplicationRequestBody: ...
