from lark_oapi.core.construct import init as init

class GetWebsiteJobPostRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetWebsiteJobPostRequestBodyBuilder: ...

class GetWebsiteJobPostRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetWebsiteJobPostRequestBody: ...
