from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetAccountAssetsReferralAccountRequest(BaseRequest):
    referral_account_id: str | None
    user_id_type: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetAccountAssetsReferralAccountRequestBuilder: ...

class GetAccountAssetsReferralAccountRequestBuilder:
    def __init__(self) -> None: ...
    def referral_account_id(self, referral_account_id: str) -> GetAccountAssetsReferralAccountRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> GetAccountAssetsReferralAccountRequestBuilder: ...
    def build(self) -> GetAccountAssetsReferralAccountRequest: ...
