from .job_detail import JobDetail as JobDetail
from lark_oapi.core.construct import init as init

class GetDetailJobResponseBody:
    job_detail: JobDetail | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetDetailJobResponseBodyBuilder: ...

class GetDetailJobResponseBodyBuilder:
    def __init__(self) -> None: ...
    def job_detail(self, job_detail: JobDetail) -> GetDetailJobResponseBodyBuilder: ...
    def build(self) -> GetDetailJobResponseBody: ...
