from .referral import Referral as Referral
from lark_oapi.core.construct import init as init

class GetByApplicationReferralResponseBody:
    referral: Referral | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetByApplicationReferralResponseBodyBuilder: ...

class GetByApplicationReferralResponseBodyBuilder:
    def __init__(self) -> None: ...
    def referral(self, referral: Referral) -> GetByApplicationReferralResponseBodyBuilder: ...
    def build(self) -> GetByApplicationReferralResponseBody: ...
