from .employee import Employee as Employee
from lark_oapi.core.construct import init as init

class GetEmployeeResponseBody:
    employee: Employee | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetEmployeeResponseBodyBuilder: ...

class GetEmployeeResponseBodyBuilder:
    def __init__(self) -> None: ...
    def employee(self, employee: Employee) -> GetEmployeeResponseBodyBuilder: ...
    def build(self) -> GetEmployeeResponseBody: ...
