from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetNoteRequest(BaseRequest):
    user_id_type: str | None
    note_id: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetNoteRequestBuilder: ...

class GetNoteRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> GetNoteRequestBuilder: ...
    def note_id(self, note_id: str) -> GetNoteRequestBuilder: ...
    def build(self) -> GetNoteRequest: ...
