from .website_job_post import WebsiteJobPost as WebsiteJobPost
from lark_oapi.core.construct import init as init

class GetWebsiteJobPostResponseBody:
    job_post: WebsiteJobPost | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetWebsiteJobPostResponseBodyBuilder: ...

class GetWebsiteJobPostResponseBodyBuilder:
    def __init__(self) -> None: ...
    def job_post(self, job_post: WebsiteJobPost) -> GetWebsiteJobPostResponseBodyBuilder: ...
    def build(self) -> GetWebsiteJobPostResponseBody: ...
