from lark_oapi.core.construct import init as init

class GetTalentRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetTalentRequestBodyBuilder: ...

class GetTalentRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetTalentRequestBody: ...
