from lark_oapi.core.construct import init as init

class GetOfferSchemaRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetOfferSchemaRequestBodyBuilder: ...

class GetOfferSchemaRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetOfferSchemaRequestBody: ...
