from .talent_interview import TalentInterview as TalentInterview
from lark_oapi.core.construct import init as init

class GetByTalentInterviewResponseBody:
    items: list[TalentInterview] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetByTalentInterviewResponseBodyBuilder: ...

class GetByTalentInterviewResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[TalentInterview]) -> GetByTalentInterviewResponseBodyBuilder: ...
    def build(self) -> GetByTalentInterviewResponseBody: ...
