from lark_oapi.core.construct import init as init

class GetInterviewRecordRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetInterviewRecordRequestBodyBuilder: ...

class GetInterviewRecordRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetInterviewRecordRequestBody: ...
