from .attachment import Attachment as Attachment
from lark_oapi.core.construct import init as init

class GetAttachmentResponseBody:
    attachment: Attachment | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetAttachmentResponseBodyBuilder: ...

class GetAttachmentResponseBodyBuilder:
    def __init__(self) -> None: ...
    def attachment(self, attachment: Attachment) -> GetAttachmentResponseBodyBuilder: ...
    def build(self) -> GetAttachmentResponseBody: ...
