from lark_oapi.core.construct import init as init

class GetByApplicationReferralRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> GetByApplicationReferralRequestBodyBuilder: ...

class GetByApplicationReferralRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> GetByApplicationReferralRequestBody: ...
