from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class GetByTalentInterviewRequest(BaseRequest):
    talent_id: str | None
    user_id_type: str | None
    job_level_id_type: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> GetByTalentInterviewRequestBuilder: ...

class GetByTalentInterviewRequestBuilder:
    def __init__(self) -> None: ...
    def talent_id(self, talent_id: str) -> GetByTalentInterviewRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> GetByTalentInterviewRequestBuilder: ...
    def job_level_id_type(self, job_level_id_type: str) -> GetByTalentInterviewRequestBuilder: ...
    def build(self) -> GetByTalentInterviewRequest: ...
