from .interview_extend_v2 import InterviewExtendV2 as InterviewExtendV2
from lark_oapi.core.construct import init as init

class InterviewAggregation:
    interviews: list[InterviewExtendV2] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InterviewAggregationBuilder: ...

class InterviewAggregationBuilder:
    def __init__(self) -> None: ...
    def interviews(self, interviews: list[InterviewExtendV2]) -> InterviewAggregationBuilder: ...
    def build(self) -> InterviewAggregation: ...
