from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class InterviewRoundTypeAssessmentTemplate:
    id: str | None
    biz_id: str | None
    name: I18n | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InterviewRoundTypeAssessmentTemplateBuilder: ...

class InterviewRoundTypeAssessmentTemplateBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> InterviewRoundTypeAssessmentTemplateBuilder: ...
    def biz_id(self, biz_id: str) -> InterviewRoundTypeAssessmentTemplateBuilder: ...
    def name(self, name: I18n) -> InterviewRoundTypeAssessmentTemplateBuilder: ...
    def build(self) -> InterviewRoundTypeAssessmentTemplate: ...
