from .intern_offer_offboarding_info import InternOfferOffboardingInfo as InternOfferOffboardingInfo
from .intern_offer_onboarding_info import InternOfferOnboardingInfo as InternOfferOnboardingInfo
from lark_oapi.core.construct import init as init

class InternOfferStatus:
    offer_id: str | None
    operation: str | None
    onboarding_info: InternOfferOnboardingInfo | None
    offboarding_info: InternOfferOffboardingInfo | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InternOfferStatusBuilder: ...

class InternOfferStatusBuilder:
    def __init__(self) -> None: ...
    def offer_id(self, offer_id: str) -> InternOfferStatusBuilder: ...
    def operation(self, operation: str) -> InternOfferStatusBuilder: ...
    def onboarding_info(self, onboarding_info: InternOfferOnboardingInfo) -> InternOfferStatusBuilder: ...
    def offboarding_info(self, offboarding_info: InternOfferOffboardingInfo) -> InternOfferStatusBuilder: ...
    def build(self) -> InternOfferStatus: ...
