from .i18n import I18n as I18n
from .interview_feedback_form_dimension import InterviewFeedbackFormDimension as InterviewFeedbackFormDimension
from lark_oapi.core.construct import init as init

class InterviewFeedbackFormModule:
    id: str | None
    name: I18n | None
    description: I18n | None
    type: int | None
    sequence: int | None
    weight: float | None
    dimensions: list[InterviewFeedbackFormDimension] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InterviewFeedbackFormModuleBuilder: ...

class InterviewFeedbackFormModuleBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> InterviewFeedbackFormModuleBuilder: ...
    def name(self, name: I18n) -> InterviewFeedbackFormModuleBuilder: ...
    def description(self, description: I18n) -> InterviewFeedbackFormModuleBuilder: ...
    def type(self, type: int) -> InterviewFeedbackFormModuleBuilder: ...
    def sequence(self, sequence: int) -> InterviewFeedbackFormModuleBuilder: ...
    def weight(self, weight: float) -> InterviewFeedbackFormModuleBuilder: ...
    def dimensions(self, dimensions: list[InterviewFeedbackFormDimension]) -> InterviewFeedbackFormModuleBuilder: ...
    def build(self) -> InterviewFeedbackFormModule: ...
