from lark_oapi.core.construct import init as init

class Interviewer:
    user_id: str | None
    verify_status: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InterviewerBuilder: ...

class InterviewerBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: str) -> InterviewerBuilder: ...
    def verify_status(self, verify_status: int) -> InterviewerBuilder: ...
    def build(self) -> Interviewer: ...
