from .i18n import I18n as I18n
from .interview_feedback_form_module import InterviewFeedbackFormModule as InterviewFeedbackFormModule
from .score_calculation_config import ScoreCalculationConfig as ScoreCalculationConfig
from lark_oapi.core.construct import init as init

class InterviewFeedbackForm:
    id: str | None
    version: int | None
    name: I18n | None
    type: int | None
    score_calculation_config: ScoreCalculationConfig | None
    modules: list[InterviewFeedbackFormModule] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InterviewFeedbackFormBuilder: ...

class InterviewFeedbackFormBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> InterviewFeedbackFormBuilder: ...
    def version(self, version: int) -> InterviewFeedbackFormBuilder: ...
    def name(self, name: I18n) -> InterviewFeedbackFormBuilder: ...
    def type(self, type: int) -> InterviewFeedbackFormBuilder: ...
    def score_calculation_config(self, score_calculation_config: ScoreCalculationConfig) -> InterviewFeedbackFormBuilder: ...
    def modules(self, modules: list[InterviewFeedbackFormModule]) -> InterviewFeedbackFormBuilder: ...
    def build(self) -> InterviewFeedbackForm: ...
