from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class InterviewerTag:
    id: str | None
    name: I18n | None
    active_status: int | None
    creator_id: str | None
    updater_id: str | None
    create_time: str | None
    update_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InterviewerTagBuilder: ...

class InterviewerTagBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> InterviewerTagBuilder: ...
    def name(self, name: I18n) -> InterviewerTagBuilder: ...
    def active_status(self, active_status: int) -> InterviewerTagBuilder: ...
    def creator_id(self, creator_id: str) -> InterviewerTagBuilder: ...
    def updater_id(self, updater_id: str) -> InterviewerTagBuilder: ...
    def create_time(self, create_time: str) -> InterviewerTagBuilder: ...
    def update_time(self, update_time: str) -> InterviewerTagBuilder: ...
    def build(self) -> InterviewerTag: ...
