from lark_oapi.core.construct import init as init

class InterviewScore:
    id: str | None
    level: int | None
    zh_name: str | None
    zh_description: str | None
    en_name: str | None
    en_description: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InterviewScoreBuilder: ...

class InterviewScoreBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> InterviewScoreBuilder: ...
    def level(self, level: int) -> InterviewScoreBuilder: ...
    def zh_name(self, zh_name: str) -> InterviewScoreBuilder: ...
    def zh_description(self, zh_description: str) -> InterviewScoreBuilder: ...
    def en_name(self, en_name: str) -> InterviewScoreBuilder: ...
    def en_description(self, en_description: str) -> InterviewScoreBuilder: ...
    def build(self) -> InterviewScore: ...
