from lark_oapi.core.construct import init as init

class InternOfferOffboardingInfo:
    actual_offboarding_date: str | None
    notes: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InternOfferOffboardingInfoBuilder: ...

class InternOfferOffboardingInfoBuilder:
    def __init__(self) -> None: ...
    def actual_offboarding_date(self, actual_offboarding_date: str) -> InternOfferOffboardingInfoBuilder: ...
    def notes(self, notes: str) -> InternOfferOffboardingInfoBuilder: ...
    def build(self) -> InternOfferOffboardingInfo: ...
