from .basic_user_info import BasicUserInfo as BasicUserInfo
from .interview_attachment import InterviewAttachment as InterviewAttachment
from .module_assessment import ModuleAssessment as ModuleAssessment
from .record_score import RecordScore as RecordScore
from lark_oapi.core.construct import init as init

class InterviewRecordV2:
    id: str | None
    feedback_form_id: str | None
    commit_status: int | None
    submit_time: str | None
    record_score: RecordScore | None
    interviewer: BasicUserInfo | None
    attachments: list[InterviewAttachment] | None
    module_assessments: list[ModuleAssessment] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InterviewRecordV2Builder: ...

class InterviewRecordV2Builder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> InterviewRecordV2Builder: ...
    def feedback_form_id(self, feedback_form_id: str) -> InterviewRecordV2Builder: ...
    def commit_status(self, commit_status: int) -> InterviewRecordV2Builder: ...
    def submit_time(self, submit_time: str) -> InterviewRecordV2Builder: ...
    def record_score(self, record_score: RecordScore) -> InterviewRecordV2Builder: ...
    def interviewer(self, interviewer: BasicUserInfo) -> InterviewRecordV2Builder: ...
    def attachments(self, attachments: list[InterviewAttachment]) -> InterviewRecordV2Builder: ...
    def module_assessments(self, module_assessments: list[ModuleAssessment]) -> InterviewRecordV2Builder: ...
    def build(self) -> InterviewRecordV2: ...
