from lark_oapi.core.construct import init as init

class InterviewMeetingRoom:
    room_id: str | None
    room_name: str | None
    building_name: str | None
    reserved_status: int | None
    floor_name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InterviewMeetingRoomBuilder: ...

class InterviewMeetingRoomBuilder:
    def __init__(self) -> None: ...
    def room_id(self, room_id: str) -> InterviewMeetingRoomBuilder: ...
    def room_name(self, room_name: str) -> InterviewMeetingRoomBuilder: ...
    def building_name(self, building_name: str) -> InterviewMeetingRoomBuilder: ...
    def reserved_status(self, reserved_status: int) -> InterviewMeetingRoomBuilder: ...
    def floor_name(self, floor_name: str) -> InterviewMeetingRoomBuilder: ...
    def build(self) -> InterviewMeetingRoom: ...
