from .interview_assessment_dimension import InterviewAssessmentDimension as InterviewAssessmentDimension
from lark_oapi.core.construct import init as init

class InterviewAssessmentTemplateArgs:
    conclusion_dimension: InterviewAssessmentDimension | None
    score_dimension: InterviewAssessmentDimension | None
    content_dimension: InterviewAssessmentDimension | None
    custom_dimension_list: list[InterviewAssessmentDimension] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InterviewAssessmentTemplateArgsBuilder: ...

class InterviewAssessmentTemplateArgsBuilder:
    def __init__(self) -> None: ...
    def conclusion_dimension(self, conclusion_dimension: InterviewAssessmentDimension) -> InterviewAssessmentTemplateArgsBuilder: ...
    def score_dimension(self, score_dimension: InterviewAssessmentDimension) -> InterviewAssessmentTemplateArgsBuilder: ...
    def content_dimension(self, content_dimension: InterviewAssessmentDimension) -> InterviewAssessmentTemplateArgsBuilder: ...
    def custom_dimension_list(self, custom_dimension_list: list[InterviewAssessmentDimension]) -> InterviewAssessmentTemplateArgsBuilder: ...
    def build(self) -> InterviewAssessmentTemplateArgs: ...
