from .interview_record import InterviewRecord as InterviewRecord
from lark_oapi.core.construct import init as init

class Interview:
    id: str | None
    begin_time: int | None
    end_time: int | None
    round: int | None
    stage_id: str | None
    interview_record_list: list[InterviewRecord] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> InterviewBuilder: ...

class InterviewBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> InterviewBuilder: ...
    def begin_time(self, begin_time: int) -> InterviewBuilder: ...
    def end_time(self, end_time: int) -> InterviewBuilder: ...
    def round(self, round: int) -> InterviewBuilder: ...
    def stage_id(self, stage_id: str) -> InterviewBuilder: ...
    def interview_record_list(self, interview_record_list: list[InterviewRecord]) -> InterviewBuilder: ...
    def build(self) -> Interview: ...
