from lark_oapi.core.construct import init as init

class JobCategory:
    id: str | None
    zh_name: str | None
    en_name: str | None
    active_status: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobCategoryBuilder: ...

class JobCategoryBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> JobCategoryBuilder: ...
    def zh_name(self, zh_name: str) -> JobCategoryBuilder: ...
    def en_name(self, en_name: str) -> JobCategoryBuilder: ...
    def active_status(self, active_status: int) -> JobCategoryBuilder: ...
    def build(self) -> JobCategory: ...
