from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class JobRequirementCustomizedOption:
    key: str | None
    name: I18n | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobRequirementCustomizedOptionBuilder: ...

class JobRequirementCustomizedOptionBuilder:
    def __init__(self) -> None: ...
    def key(self, key: str) -> JobRequirementCustomizedOptionBuilder: ...
    def name(self, name: I18n) -> JobRequirementCustomizedOptionBuilder: ...
    def build(self) -> JobRequirementCustomizedOption: ...
