from lark_oapi.core.construct import init as init

class JobCity:
    city_code: str | None
    zh_name: str | None
    en_name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobCityBuilder: ...

class JobCityBuilder:
    def __init__(self) -> None: ...
    def city_code(self, city_code: str) -> JobCityBuilder: ...
    def zh_name(self, zh_name: str) -> JobCityBuilder: ...
    def en_name(self, en_name: str) -> JobCityBuilder: ...
    def build(self) -> JobCity: ...
