from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class JobDetailTargetMajorInfo:
    id: str | None
    name: I18n | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobDetailTargetMajorInfoBuilder: ...

class JobDetailTargetMajorInfoBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> JobDetailTargetMajorInfoBuilder: ...
    def name(self, name: I18n) -> JobDetailTargetMajorInfoBuilder: ...
    def build(self) -> JobDetailTargetMajorInfo: ...
