from lark_oapi.core.construct import init as init

class JobCustomizedTimeRange:
    start_time: str | None
    end_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobCustomizedTimeRangeBuilder: ...

class JobCustomizedTimeRangeBuilder:
    def __init__(self) -> None: ...
    def start_time(self, start_time: str) -> JobCustomizedTimeRangeBuilder: ...
    def end_time(self, end_time: str) -> JobCustomizedTimeRangeBuilder: ...
    def build(self) -> JobCustomizedTimeRange: ...
