from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class JobFunction:
    id: str | None
    name: I18n | None
    active_status: int | None
    parent_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobFunctionBuilder: ...

class JobFunctionBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> JobFunctionBuilder: ...
    def name(self, name: I18n) -> JobFunctionBuilder: ...
    def active_status(self, active_status: int) -> JobFunctionBuilder: ...
    def parent_id(self, parent_id: str) -> JobFunctionBuilder: ...
    def build(self) -> JobFunction: ...
