from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class JobTypeInfo:
    id: str | None
    name: I18n | None
    parent_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobTypeInfoBuilder: ...

class JobTypeInfoBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> JobTypeInfoBuilder: ...
    def name(self, name: I18n) -> JobTypeInfoBuilder: ...
    def parent_id(self, parent_id: str) -> JobTypeInfoBuilder: ...
    def build(self) -> JobTypeInfo: ...
