from lark_oapi.core.construct import init as init

class JobRequirementCustomizedData:
    object_id: str | None
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobRequirementCustomizedDataBuilder: ...

class JobRequirementCustomizedDataBuilder:
    def __init__(self) -> None: ...
    def object_id(self, object_id: str) -> JobRequirementCustomizedDataBuilder: ...
    def value(self, value: str) -> JobRequirementCustomizedDataBuilder: ...
    def build(self) -> JobRequirementCustomizedData: ...
