from lark_oapi.core.construct import init as init

class JobRequirementCustomizedTimeRange:
    start_time: str | None
    end_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobRequirementCustomizedTimeRangeBuilder: ...

class JobRequirementCustomizedTimeRangeBuilder:
    def __init__(self) -> None: ...
    def start_time(self, start_time: str) -> JobRequirementCustomizedTimeRangeBuilder: ...
    def end_time(self, end_time: str) -> JobRequirementCustomizedTimeRangeBuilder: ...
    def build(self) -> JobRequirementCustomizedTimeRange: ...
