from .common_schema import CommonSchema as CommonSchema
from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class JobRequirementSchema:
    id: str | None
    name: I18n | None
    object_list: list[CommonSchema] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobRequirementSchemaBuilder: ...

class JobRequirementSchemaBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> JobRequirementSchemaBuilder: ...
    def name(self, name: I18n) -> JobRequirementSchemaBuilder: ...
    def object_list(self, object_list: list[CommonSchema]) -> JobRequirementSchemaBuilder: ...
    def build(self) -> JobRequirementSchema: ...
