from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class JobDetailTag:
    id: str | None
    name: I18n | None
    order: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobDetailTagBuilder: ...

class JobDetailTagBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> JobDetailTagBuilder: ...
    def name(self, name: I18n) -> JobDetailTagBuilder: ...
    def order(self, order: int) -> JobDetailTagBuilder: ...
    def build(self) -> JobDetailTag: ...
