from lark_oapi.core.construct import init as init

class JobBasicInfo:
    id: str | None
    name: str | None
    code: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobBasicInfoBuilder: ...

class JobBasicInfoBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> JobBasicInfoBuilder: ...
    def name(self, name: str) -> JobBasicInfoBuilder: ...
    def code(self, code: str) -> JobBasicInfoBuilder: ...
    def build(self) -> JobBasicInfo: ...
