from lark_oapi.core.construct import init as init

class JobLevel:
    id: str | None
    zh_name: str | None
    en_name: str | None
    active_status: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobLevelBuilder: ...

class JobLevelBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> JobLevelBuilder: ...
    def zh_name(self, zh_name: str) -> JobLevelBuilder: ...
    def en_name(self, en_name: str) -> JobLevelBuilder: ...
    def active_status(self, active_status: int) -> JobLevelBuilder: ...
    def build(self) -> JobLevel: ...
