from lark_oapi.core.construct import init as init

class JobRecruiter2:
    id: str | None
    recruiter_id: str | None
    hiring_manager_id_list: list[str] | None
    assistant_id_list: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobRecruiter2Builder: ...

class JobRecruiter2Builder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> JobRecruiter2Builder: ...
    def recruiter_id(self, recruiter_id: str) -> JobRecruiter2Builder: ...
    def hiring_manager_id_list(self, hiring_manager_id_list: list[str]) -> JobRecruiter2Builder: ...
    def assistant_id_list(self, assistant_id_list: list[str]) -> JobRecruiter2Builder: ...
    def build(self) -> JobRecruiter2: ...
