from lark_oapi.core.construct import init as init

class JobDepartment:
    id: str | None
    zh_name: str | None
    en_name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobDepartmentBuilder: ...

class JobDepartmentBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> JobDepartmentBuilder: ...
    def zh_name(self, zh_name: str) -> JobDepartmentBuilder: ...
    def en_name(self, en_name: str) -> JobDepartmentBuilder: ...
    def build(self) -> JobDepartment: ...
