from lark_oapi.core.construct import init as init

class JobProcessesStage:
    id: str | None
    zh_name: str | None
    en_name: str | None
    type: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobProcessesStageBuilder: ...

class JobProcessesStageBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> JobProcessesStageBuilder: ...
    def zh_name(self, zh_name: str) -> JobProcessesStageBuilder: ...
    def en_name(self, en_name: str) -> JobProcessesStageBuilder: ...
    def type(self, type: int) -> JobProcessesStageBuilder: ...
    def build(self) -> JobProcessesStage: ...
