from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class JobCustomizedOption:
    key: str | None
    name: I18n | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> JobCustomizedOptionBuilder: ...

class JobCustomizedOptionBuilder:
    def __init__(self) -> None: ...
    def key(self, key: str) -> JobCustomizedOptionBuilder: ...
    def name(self, name: I18n) -> JobCustomizedOptionBuilder: ...
    def build(self) -> JobCustomizedOption: ...
