from lark_oapi.core.construct import init as init

class ListUserRoleRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListUserRoleRequestBodyBuilder: ...

class ListUserRoleRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListUserRoleRequestBody: ...
