from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListTerminationReasonRequest(BaseRequest):
    page_token: str | None
    page_size: int | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListTerminationReasonRequestBuilder: ...

class ListTerminationReasonRequestBuilder:
    def __init__(self) -> None: ...
    def page_token(self, page_token: str) -> ListTerminationReasonRequestBuilder: ...
    def page_size(self, page_size: int) -> ListTerminationReasonRequestBuilder: ...
    def build(self) -> ListTerminationReasonRequest: ...
