from .questionnaire import Questionnaire as Questionnaire
from lark_oapi.core.construct import init as init

class ListQuestionnaireResponseBody:
    has_more: bool | None
    page_token: str | None
    items: list[Questionnaire] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListQuestionnaireResponseBodyBuilder: ...

class ListQuestionnaireResponseBodyBuilder:
    def __init__(self) -> None: ...
    def has_more(self, has_more: bool) -> ListQuestionnaireResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListQuestionnaireResponseBodyBuilder: ...
    def items(self, items: list[Questionnaire]) -> ListQuestionnaireResponseBodyBuilder: ...
    def build(self) -> ListQuestionnaireResponseBody: ...
