from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListBackgroundCheckOrderRequest(BaseRequest):
    user_id_type: str | None
    page_token: str | None
    page_size: int | None
    application_id: str | None
    update_start_time: str | None
    update_end_time: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListBackgroundCheckOrderRequestBuilder: ...

class ListBackgroundCheckOrderRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> ListBackgroundCheckOrderRequestBuilder: ...
    def page_token(self, page_token: str) -> ListBackgroundCheckOrderRequestBuilder: ...
    def page_size(self, page_size: int) -> ListBackgroundCheckOrderRequestBuilder: ...
    def application_id(self, application_id: str) -> ListBackgroundCheckOrderRequestBuilder: ...
    def update_start_time(self, update_start_time: str) -> ListBackgroundCheckOrderRequestBuilder: ...
    def update_end_time(self, update_end_time: str) -> ListBackgroundCheckOrderRequestBuilder: ...
    def build(self) -> ListBackgroundCheckOrderRequest: ...
