from .interview_round_type import InterviewRoundType as InterviewRoundType
from lark_oapi.core.construct import init as init

class ListInterviewRoundTypeResponseBody:
    active_status: int | None
    items: list[InterviewRoundType] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListInterviewRoundTypeResponseBodyBuilder: ...

class ListInterviewRoundTypeResponseBodyBuilder:
    def __init__(self) -> None: ...
    def active_status(self, active_status: int) -> ListInterviewRoundTypeResponseBodyBuilder: ...
    def items(self, items: list[InterviewRoundType]) -> ListInterviewRoundTypeResponseBodyBuilder: ...
    def build(self) -> ListInterviewRoundTypeResponseBody: ...
