from lark_oapi.core.construct import init as init

class ListApplicationInterviewRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListApplicationInterviewRequestBodyBuilder: ...

class ListApplicationInterviewRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListApplicationInterviewRequestBody: ...
