from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListJobTypeRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListJobTypeRequestBuilder: ...

class ListJobTypeRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> ListJobTypeRequestBuilder: ...
    def page_token(self, page_token: str) -> ListJobTypeRequestBuilder: ...
    def build(self) -> ListJobTypeRequest: ...
