from .tripartite_agreement_info import TripartiteAgreementInfo as TripartiteAgreementInfo
from lark_oapi.core.construct import init as init

class ListTripartiteAgreementResponseBody:
    items: list[TripartiteAgreementInfo] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListTripartiteAgreementResponseBodyBuilder: ...

class ListTripartiteAgreementResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[TripartiteAgreementInfo]) -> ListTripartiteAgreementResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListTripartiteAgreementResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListTripartiteAgreementResponseBodyBuilder: ...
    def build(self) -> ListTripartiteAgreementResponseBody: ...
