from lark_oapi.core.construct import init as init

class ListInterviewRoundTypeRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListInterviewRoundTypeRequestBodyBuilder: ...

class ListInterviewRoundTypeRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListInterviewRoundTypeRequestBody: ...
