from lark_oapi.core.construct import init as init

class ListNoteRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListNoteRequestBodyBuilder: ...

class ListNoteRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListNoteRequestBody: ...
