from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListInterviewRecordRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    ids: list[str] | None
    user_id_type: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListInterviewRecordRequestBuilder: ...

class ListInterviewRecordRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> ListInterviewRecordRequestBuilder: ...
    def page_token(self, page_token: str) -> ListInterviewRecordRequestBuilder: ...
    def ids(self, ids: list[str]) -> ListInterviewRecordRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> ListInterviewRecordRequestBuilder: ...
    def build(self) -> ListInterviewRecordRequest: ...
