from .job_requirement_dto import JobRequirementDto as JobRequirementDto
from lark_oapi.core.construct import init as init

class ListByIdJobRequirementResponseBody:
    items: list[JobRequirementDto] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListByIdJobRequirementResponseBodyBuilder: ...

class ListByIdJobRequirementResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[JobRequirementDto]) -> ListByIdJobRequirementResponseBodyBuilder: ...
    def build(self) -> ListByIdJobRequirementResponseBody: ...
