from lark_oapi.core.construct import init as init

class ListRoleRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListRoleRequestBodyBuilder: ...

class ListRoleRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListRoleRequestBody: ...
