from .interviewer import Interviewer as Interviewer
from lark_oapi.core.construct import init as init

class ListInterviewerResponseBody:
    items: list[Interviewer] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListInterviewerResponseBodyBuilder: ...

class ListInterviewerResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[Interviewer]) -> ListInterviewerResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListInterviewerResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListInterviewerResponseBodyBuilder: ...
    def build(self) -> ListInterviewerResponseBody: ...
