from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListNoteRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    talent_id: str | None
    user_id_type: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListNoteRequestBuilder: ...

class ListNoteRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> ListNoteRequestBuilder: ...
    def page_token(self, page_token: str) -> ListNoteRequestBuilder: ...
    def talent_id(self, talent_id: str) -> ListNoteRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> ListNoteRequestBuilder: ...
    def build(self) -> ListNoteRequest: ...
