from .job_requirement_dto import JobRequirementDto as JobRequirementDto
from lark_oapi.core.construct import init as init

class ListJobRequirementResponseBody:
    has_more: bool | None
    page_token: str | None
    items: list[JobRequirementDto] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListJobRequirementResponseBodyBuilder: ...

class ListJobRequirementResponseBodyBuilder:
    def __init__(self) -> None: ...
    def has_more(self, has_more: bool) -> ListJobRequirementResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListJobRequirementResponseBodyBuilder: ...
    def items(self, items: list[JobRequirementDto]) -> ListJobRequirementResponseBodyBuilder: ...
    def build(self) -> ListJobRequirementResponseBody: ...
