from lark_oapi.core.construct import init as init

class ListJobRequirementRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListJobRequirementRequestBodyBuilder: ...

class ListJobRequirementRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListJobRequirementRequestBody: ...
