from lark_oapi.core.construct import init as init

class ListOfferApplicationFormRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListOfferApplicationFormRequestBodyBuilder: ...

class ListOfferApplicationFormRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListOfferApplicationFormRequestBody: ...
