from lark_oapi.core.construct import init as init

class ListInterviewFeedbackFormRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListInterviewFeedbackFormRequestBodyBuilder: ...

class ListInterviewFeedbackFormRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListInterviewFeedbackFormRequestBody: ...
