from lark_oapi.core.construct import init as init

class ListJobRequirementSchemaRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListJobRequirementSchemaRequestBodyBuilder: ...

class ListJobRequirementSchemaRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListJobRequirementSchemaRequestBody: ...
