from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListUserRoleRequest(BaseRequest):
    page_token: str | None
    page_size: int | None
    user_id: str | None
    role_id: str | None
    update_start_time: int | None
    update_end_time: int | None
    user_id_type: str | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListUserRoleRequestBuilder: ...

class ListUserRoleRequestBuilder:
    def __init__(self) -> None: ...
    def page_token(self, page_token: str) -> ListUserRoleRequestBuilder: ...
    def page_size(self, page_size: int) -> ListUserRoleRequestBuilder: ...
    def user_id(self, user_id: str) -> ListUserRoleRequestBuilder: ...
    def role_id(self, role_id: str) -> ListUserRoleRequestBuilder: ...
    def update_start_time(self, update_start_time: int) -> ListUserRoleRequestBuilder: ...
    def update_end_time(self, update_end_time: int) -> ListUserRoleRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> ListUserRoleRequestBuilder: ...
    def build(self) -> ListUserRoleRequest: ...
