from .job_requirement_schema import JobRequirementSchema as JobRequirementSchema
from lark_oapi.core.construct import init as init

class ListJobRequirementSchemaResponseBody:
    items: list[JobRequirementSchema] | None
    has_more: bool | None
    page_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListJobRequirementSchemaResponseBodyBuilder: ...

class ListJobRequirementSchemaResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[JobRequirementSchema]) -> ListJobRequirementSchemaResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListJobRequirementSchemaResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListJobRequirementSchemaResponseBodyBuilder: ...
    def build(self) -> ListJobRequirementSchemaResponseBody: ...
