from .list_by_id_job_requirement_request_body import ListByIdJobRequirementRequestBody as ListByIdJobRequirementRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListByIdJobRequirementRequest(BaseRequest):
    user_id_type: str | None
    department_id_type: str | None
    job_level_id_type: str | None
    job_family_id_type: str | None
    employee_type_id_type: str | None
    request_body: ListByIdJobRequirementRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListByIdJobRequirementRequestBuilder: ...

class ListByIdJobRequirementRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> ListByIdJobRequirementRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> ListByIdJobRequirementRequestBuilder: ...
    def job_level_id_type(self, job_level_id_type: str) -> ListByIdJobRequirementRequestBuilder: ...
    def job_family_id_type(self, job_family_id_type: str) -> ListByIdJobRequirementRequestBuilder: ...
    def employee_type_id_type(self, employee_type_id_type: str) -> ListByIdJobRequirementRequestBuilder: ...
    def request_body(self, request_body: ListByIdJobRequirementRequestBody) -> ListByIdJobRequirementRequestBuilder: ...
    def build(self) -> ListByIdJobRequirementRequest: ...
