from .termination_reason import TerminationReason as TerminationReason
from lark_oapi.core.construct import init as init

class ListTerminationReasonResponseBody:
    items: list[TerminationReason] | None
    has_more: bool | None
    page_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListTerminationReasonResponseBodyBuilder: ...

class ListTerminationReasonResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[TerminationReason]) -> ListTerminationReasonResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListTerminationReasonResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListTerminationReasonResponseBodyBuilder: ...
    def build(self) -> ListTerminationReasonResponseBody: ...
