from lark_oapi.core.construct import init as init

class ListQuestionnaireRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListQuestionnaireRequestBodyBuilder: ...

class ListQuestionnaireRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListQuestionnaireRequestBody: ...
