from .role import Role as Role
from lark_oapi.core.construct import init as init

class ListRoleResponseBody:
    items: list[Role] | None
    has_more: bool | None
    page_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListRoleResponseBodyBuilder: ...

class ListRoleResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[Role]) -> ListRoleResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListRoleResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListRoleResponseBodyBuilder: ...
    def build(self) -> ListRoleResponseBody: ...
