from .interview_task import InterviewTask as InterviewTask
from lark_oapi.core.construct import init as init

class ListInterviewTaskResponseBody:
    has_more: bool | None
    page_token: str | None
    items: list[InterviewTask] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListInterviewTaskResponseBodyBuilder: ...

class ListInterviewTaskResponseBodyBuilder:
    def __init__(self) -> None: ...
    def has_more(self, has_more: bool) -> ListInterviewTaskResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListInterviewTaskResponseBodyBuilder: ...
    def items(self, items: list[InterviewTask]) -> ListInterviewTaskResponseBodyBuilder: ...
    def build(self) -> ListInterviewTaskResponseBody: ...
