from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListInterviewRoundTypeRequest(BaseRequest):
    process_type: int | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListInterviewRoundTypeRequestBuilder: ...

class ListInterviewRoundTypeRequestBuilder:
    def __init__(self) -> None: ...
    def process_type(self, process_type: int) -> ListInterviewRoundTypeRequestBuilder: ...
    def build(self) -> ListInterviewRoundTypeRequest: ...
