from .resume_source import ResumeSource as ResumeSource
from lark_oapi.core.construct import init as init

class ListResumeSourceResponseBody:
    items: list[ResumeSource] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListResumeSourceResponseBodyBuilder: ...

class ListResumeSourceResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[ResumeSource]) -> ListResumeSourceResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListResumeSourceResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListResumeSourceResponseBodyBuilder: ...
    def build(self) -> ListResumeSourceResponseBody: ...
