from lark_oapi.core.construct import init as init

class ListRegistrationSchemaRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListRegistrationSchemaRequestBodyBuilder: ...

class ListRegistrationSchemaRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListRegistrationSchemaRequestBody: ...
