from lark_oapi.core.construct import init as init

class ListApplicationRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListApplicationRequestBodyBuilder: ...

class ListApplicationRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListApplicationRequestBody: ...
