from .interview_feedback_form import InterviewFeedbackForm as InterviewFeedbackForm
from lark_oapi.core.construct import init as init

class ListInterviewFeedbackFormResponseBody:
    items: list[InterviewFeedbackForm] | None
    page_token: str | None
    has_more: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListInterviewFeedbackFormResponseBodyBuilder: ...

class ListInterviewFeedbackFormResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[InterviewFeedbackForm]) -> ListInterviewFeedbackFormResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListInterviewFeedbackFormResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListInterviewFeedbackFormResponseBodyBuilder: ...
    def build(self) -> ListInterviewFeedbackFormResponseBody: ...
