from lark_oapi.core.construct import init as init

class ListBackgroundCheckOrderRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListBackgroundCheckOrderRequestBodyBuilder: ...

class ListBackgroundCheckOrderRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListBackgroundCheckOrderRequestBody: ...
