from lark_oapi.core.construct import init as init

class ListWebsiteJobPostRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListWebsiteJobPostRequestBodyBuilder: ...

class ListWebsiteJobPostRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListWebsiteJobPostRequestBody: ...
