from lark_oapi.core.construct import init as init

class ListExternalApplicationRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListExternalApplicationRequestBodyBuilder: ...

class ListExternalApplicationRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListExternalApplicationRequestBody: ...
