from .external_application import ExternalApplication as ExternalApplication
from lark_oapi.core.construct import init as init

class ListExternalApplicationResponseBody:
    items: list[ExternalApplication] | None
    has_more: bool | None
    page_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListExternalApplicationResponseBodyBuilder: ...

class ListExternalApplicationResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[ExternalApplication]) -> ListExternalApplicationResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListExternalApplicationResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListExternalApplicationResponseBodyBuilder: ...
    def build(self) -> ListExternalApplicationResponseBody: ...
