from .subject import Subject as Subject
from lark_oapi.core.construct import init as init

class ListSubjectResponseBody:
    has_more: bool | None
    page_token: str | None
    items: list[Subject] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListSubjectResponseBodyBuilder: ...

class ListSubjectResponseBodyBuilder:
    def __init__(self) -> None: ...
    def has_more(self, has_more: bool) -> ListSubjectResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListSubjectResponseBodyBuilder: ...
    def items(self, items: list[Subject]) -> ListSubjectResponseBodyBuilder: ...
    def build(self) -> ListSubjectResponseBody: ...
