from lark_oapi.core.construct import init as init

class ListExamMarkingTaskRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListExamMarkingTaskRequestBodyBuilder: ...

class ListExamMarkingTaskRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ListExamMarkingTaskRequestBody: ...
