from .website_channel_info import WebsiteChannelInfo as WebsiteChannelInfo
from lark_oapi.core.construct import init as init

class ListWebsiteChannelResponseBody:
    has_more: bool | None
    page_token: str | None
    website_channel_list: list[WebsiteChannelInfo] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListWebsiteChannelResponseBodyBuilder: ...

class ListWebsiteChannelResponseBodyBuilder:
    def __init__(self) -> None: ...
    def has_more(self, has_more: bool) -> ListWebsiteChannelResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListWebsiteChannelResponseBodyBuilder: ...
    def website_channel_list(self, website_channel_list: list[WebsiteChannelInfo]) -> ListWebsiteChannelResponseBodyBuilder: ...
    def build(self) -> ListWebsiteChannelResponseBody: ...
