from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ListJobSchemaRequest(BaseRequest):
    page_token: str | None
    page_size: int | None
    scenario: int | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ListJobSchemaRequestBuilder: ...

class ListJobSchemaRequestBuilder:
    def __init__(self) -> None: ...
    def page_token(self, page_token: str) -> ListJobSchemaRequestBuilder: ...
    def page_size(self, page_size: int) -> ListJobSchemaRequestBuilder: ...
    def scenario(self, scenario: int) -> ListJobSchemaRequestBuilder: ...
    def build(self) -> ListJobSchemaRequest: ...
