from .job_schema import JobSchema as JobSchema
from lark_oapi.core.construct import init as init

class ListJobSchemaResponseBody:
    items: list[JobSchema] | None
    has_more: bool | None
    page_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ListJobSchemaResponseBodyBuilder: ...

class ListJobSchemaResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[JobSchema]) -> ListJobSchemaResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> ListJobSchemaResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> ListJobSchemaResponseBodyBuilder: ...
    def build(self) -> ListJobSchemaResponseBody: ...
