from .location_name_info import LocationNameInfo as LocationNameInfo
from lark_oapi.core.construct import init as init

class LocationState:
    state_code: str | None
    country_code: str | None
    state_name_info: LocationNameInfo | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LocationStateBuilder: ...

class LocationStateBuilder:
    def __init__(self) -> None: ...
    def state_code(self, state_code: str) -> LocationStateBuilder: ...
    def country_code(self, country_code: str) -> LocationStateBuilder: ...
    def state_name_info(self, state_name_info: LocationNameInfo) -> LocationStateBuilder: ...
    def build(self) -> LocationState: ...
