from lark_oapi.core.construct import init as init

class LocationBaseInfo:
    code: str | None
    name: str | None
    en_name: str | None
    location_type: int | None
    i18n_name: str | None
    py_name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LocationBaseInfoBuilder: ...

class LocationBaseInfoBuilder:
    def __init__(self) -> None: ...
    def code(self, code: str) -> LocationBaseInfoBuilder: ...
    def name(self, name: str) -> LocationBaseInfoBuilder: ...
    def en_name(self, en_name: str) -> LocationBaseInfoBuilder: ...
    def location_type(self, location_type: int) -> LocationBaseInfoBuilder: ...
    def i18n_name(self, i18n_name: str) -> LocationBaseInfoBuilder: ...
    def py_name(self, py_name: str) -> LocationBaseInfoBuilder: ...
    def build(self) -> LocationBaseInfo: ...
