from .location_name_info import LocationNameInfo as LocationNameInfo
from lark_oapi.core.construct import init as init

class LocationCity:
    city_code: str | None
    state_code: str | None
    country_code: str | None
    city_name_info: LocationNameInfo | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LocationCityBuilder: ...

class LocationCityBuilder:
    def __init__(self) -> None: ...
    def city_code(self, city_code: str) -> LocationCityBuilder: ...
    def state_code(self, state_code: str) -> LocationCityBuilder: ...
    def country_code(self, country_code: str) -> LocationCityBuilder: ...
    def city_name_info(self, city_name_info: LocationNameInfo) -> LocationCityBuilder: ...
    def build(self) -> LocationCity: ...
