from .location_name_info import LocationNameInfo as LocationNameInfo
from lark_oapi.core.construct import init as init

class LocationDistrict:
    district_code: str | None
    city_code: str | None
    state_code: str | None
    country_code: str | None
    district_name_info: LocationNameInfo | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> LocationDistrictBuilder: ...

class LocationDistrictBuilder:
    def __init__(self) -> None: ...
    def district_code(self, district_code: str) -> LocationDistrictBuilder: ...
    def city_code(self, city_code: str) -> LocationDistrictBuilder: ...
    def state_code(self, state_code: str) -> LocationDistrictBuilder: ...
    def country_code(self, country_code: str) -> LocationDistrictBuilder: ...
    def district_name_info(self, district_name_info: LocationNameInfo) -> LocationDistrictBuilder: ...
    def build(self) -> LocationDistrict: ...
