from lark_oapi.core.construct import init as init

class MentionEntity:
    offset: int | None
    user_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> MentionEntityBuilder: ...

class MentionEntityBuilder:
    def __init__(self) -> None: ...
    def offset(self, offset: int) -> MentionEntityBuilder: ...
    def user_id(self, user_id: str) -> MentionEntityBuilder: ...
    def build(self) -> MentionEntity: ...
