from .move_talent_talent_pool_request_body import MoveTalentTalentPoolRequestBody as MoveTalentTalentPoolRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class MoveTalentTalentPoolRequest(BaseRequest):
    talent_pool_id: str | None
    request_body: MoveTalentTalentPoolRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> MoveTalentTalentPoolRequestBuilder: ...

class MoveTalentTalentPoolRequestBuilder:
    def __init__(self) -> None: ...
    def talent_pool_id(self, talent_pool_id: str) -> MoveTalentTalentPoolRequestBuilder: ...
    def request_body(self, request_body: MoveTalentTalentPoolRequestBody) -> MoveTalentTalentPoolRequestBuilder: ...
    def build(self) -> MoveTalentTalentPoolRequest: ...
