from lark_oapi.core.construct import init as init

class Nationality:
    nationality_code: str | None
    name: str | None
    en_name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> NationalityBuilder: ...

class NationalityBuilder:
    def __init__(self) -> None: ...
    def nationality_code(self, nationality_code: str) -> NationalityBuilder: ...
    def name(self, name: str) -> NationalityBuilder: ...
    def en_name(self, en_name: str) -> NationalityBuilder: ...
    def build(self) -> Nationality: ...
