from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class ObjectAttribute:
    title: I18n | None
    description: I18n | None
    data_type: int | None
    tags: list[int] | None
    is_fcf_data: bool | None
    is_di_data: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ObjectAttributeBuilder: ...

class ObjectAttributeBuilder:
    def __init__(self) -> None: ...
    def title(self, title: I18n) -> ObjectAttributeBuilder: ...
    def description(self, description: I18n) -> ObjectAttributeBuilder: ...
    def data_type(self, data_type: int) -> ObjectAttributeBuilder: ...
    def tags(self, tags: list[int]) -> ObjectAttributeBuilder: ...
    def is_fcf_data(self, is_fcf_data: bool) -> ObjectAttributeBuilder: ...
    def is_di_data(self, is_di_data: bool) -> ObjectAttributeBuilder: ...
    def build(self) -> ObjectAttribute: ...
