from .i18n import I18n as I18n
from .offer_apply_form_object_info import OfferApplyFormObjectInfo as OfferApplyFormObjectInfo
from lark_oapi.core.construct import init as init

class OfferApplyFormModuleInfo:
    id: str | None
    name: I18n | None
    is_customized: bool | None
    active_status: int | None
    hint: I18n | None
    object_list: list[OfferApplyFormObjectInfo] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OfferApplyFormModuleInfoBuilder: ...

class OfferApplyFormModuleInfoBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> OfferApplyFormModuleInfoBuilder: ...
    def name(self, name: I18n) -> OfferApplyFormModuleInfoBuilder: ...
    def is_customized(self, is_customized: bool) -> OfferApplyFormModuleInfoBuilder: ...
    def active_status(self, active_status: int) -> OfferApplyFormModuleInfoBuilder: ...
    def hint(self, hint: I18n) -> OfferApplyFormModuleInfoBuilder: ...
    def object_list(self, object_list: list[OfferApplyFormObjectInfo]) -> OfferApplyFormModuleInfoBuilder: ...
    def build(self) -> OfferApplyFormModuleInfo: ...
