from .offer_custom_field_config_option import OfferCustomFieldConfigOption as OfferCustomFieldConfigOption
from lark_oapi.core.construct import init as init

class OfferCustomFieldConfig:
    options: list[OfferCustomFieldConfigOption] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OfferCustomFieldConfigBuilder: ...

class OfferCustomFieldConfigBuilder:
    def __init__(self) -> None: ...
    def options(self, options: list[OfferCustomFieldConfigOption]) -> OfferCustomFieldConfigBuilder: ...
    def build(self) -> OfferCustomFieldConfig: ...
