from lark_oapi.core.construct import init as init

class OfferStatusOfferRequestBody:
    offer_status: int | None
    expiration_date: str | None
    termination_reason_id_list: list[str] | None
    termination_reason_note: str | None
    cancel_offer_termination_type: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OfferStatusOfferRequestBodyBuilder: ...

class OfferStatusOfferRequestBodyBuilder:
    def __init__(self) -> None: ...
    def offer_status(self, offer_status: int) -> OfferStatusOfferRequestBodyBuilder: ...
    def expiration_date(self, expiration_date: str) -> OfferStatusOfferRequestBodyBuilder: ...
    def termination_reason_id_list(self, termination_reason_id_list: list[str]) -> OfferStatusOfferRequestBodyBuilder: ...
    def termination_reason_note(self, termination_reason_note: str) -> OfferStatusOfferRequestBodyBuilder: ...
    def cancel_offer_termination_type(self, cancel_offer_termination_type: int) -> OfferStatusOfferRequestBodyBuilder: ...
    def build(self) -> OfferStatusOfferRequestBody: ...
