from .base_bilingual_with_id import BaseBilingualWithId as BaseBilingualWithId
from .offer_job_info import OfferJobInfo as OfferJobInfo
from lark_oapi.core.construct import init as init

class OfferListInfo:
    id: str | None
    job_info: OfferJobInfo | None
    create_time: int | None
    offer_status: int | None
    offer_type: int | None
    employee_type: BaseBilingualWithId | None
    application_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OfferListInfoBuilder: ...

class OfferListInfoBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> OfferListInfoBuilder: ...
    def job_info(self, job_info: OfferJobInfo) -> OfferListInfoBuilder: ...
    def create_time(self, create_time: int) -> OfferListInfoBuilder: ...
    def offer_status(self, offer_status: int) -> OfferListInfoBuilder: ...
    def offer_type(self, offer_type: int) -> OfferListInfoBuilder: ...
    def employee_type(self, employee_type: BaseBilingualWithId) -> OfferListInfoBuilder: ...
    def application_id(self, application_id: str) -> OfferListInfoBuilder: ...
    def build(self) -> OfferListInfo: ...
