from .offer_apply_form_pre_object_config_info import OfferApplyFormPreObjectConfigInfo as OfferApplyFormPreObjectConfigInfo
from lark_oapi.core.construct import init as init

class OfferApplyFormObjectDisplayConfigInfo:
    display_condition: int | None
    pre_object_config_list: list[OfferApplyFormPreObjectConfigInfo] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OfferApplyFormObjectDisplayConfigInfoBuilder: ...

class OfferApplyFormObjectDisplayConfigInfoBuilder:
    def __init__(self) -> None: ...
    def display_condition(self, display_condition: int) -> OfferApplyFormObjectDisplayConfigInfoBuilder: ...
    def pre_object_config_list(self, pre_object_config_list: list[OfferApplyFormPreObjectConfigInfo]) -> OfferApplyFormObjectDisplayConfigInfoBuilder: ...
    def build(self) -> OfferApplyFormObjectDisplayConfigInfo: ...
