from lark_oapi.core.construct import init as init

class OfferCustomizedInfo:
    id: str | None
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OfferCustomizedInfoBuilder: ...

class OfferCustomizedInfoBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> OfferCustomizedInfoBuilder: ...
    def value(self, value: str) -> OfferCustomizedInfoBuilder: ...
    def build(self) -> OfferCustomizedInfo: ...
