from .offer_apply_form_config_formula_info import OfferApplyFormConfigFormulaInfo as OfferApplyFormConfigFormulaInfo
from .offer_apply_form_config_option_info import OfferApplyFormConfigOptionInfo as OfferApplyFormConfigOptionInfo
from .offer_apply_form_object_display_config_info import OfferApplyFormObjectDisplayConfigInfo as OfferApplyFormObjectDisplayConfigInfo
from lark_oapi.core.construct import init as init

class OfferApplyFormObjectConfigInfo:
    options: list[OfferApplyFormConfigOptionInfo] | None
    formula: OfferApplyFormConfigFormulaInfo | None
    object_display_config: OfferApplyFormObjectDisplayConfigInfo | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OfferApplyFormObjectConfigInfoBuilder: ...

class OfferApplyFormObjectConfigInfoBuilder:
    def __init__(self) -> None: ...
    def options(self, options: list[OfferApplyFormConfigOptionInfo]) -> OfferApplyFormObjectConfigInfoBuilder: ...
    def formula(self, formula: OfferApplyFormConfigFormulaInfo) -> OfferApplyFormObjectConfigInfoBuilder: ...
    def object_display_config(self, object_display_config: OfferApplyFormObjectDisplayConfigInfo) -> OfferApplyFormObjectConfigInfoBuilder: ...
    def build(self) -> OfferApplyFormObjectConfigInfo: ...
