from .offer_schema_detail_option import OfferSchemaDetailOption as OfferSchemaDetailOption
from lark_oapi.core.construct import init as init

class OfferSelectionObject:
    schema_version: int | None
    option_list: list[OfferSchemaDetailOption] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OfferSelectionObjectBuilder: ...

class OfferSelectionObjectBuilder:
    def __init__(self) -> None: ...
    def schema_version(self, schema_version: int) -> OfferSelectionObjectBuilder: ...
    def option_list(self, option_list: list[OfferSchemaDetailOption]) -> OfferSelectionObjectBuilder: ...
    def build(self) -> OfferSelectionObject: ...
