from .offer_schema_detail import OfferSchemaDetail as OfferSchemaDetail
from lark_oapi.core.construct import init as init

class OfferSchemaChild:
    id: str | None
    scenario: int | None
    version: int | None
    object_list: list[OfferSchemaDetail] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OfferSchemaChildBuilder: ...

class OfferSchemaChildBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> OfferSchemaChildBuilder: ...
    def scenario(self, scenario: int) -> OfferSchemaChildBuilder: ...
    def version(self, version: int) -> OfferSchemaChildBuilder: ...
    def object_list(self, object_list: list[OfferSchemaDetail]) -> OfferSchemaChildBuilder: ...
    def build(self) -> OfferSchemaChild: ...
