from lark_oapi.core.construct import init as init

class OfferJobInfo:
    job_id: str | None
    job_name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OfferJobInfoBuilder: ...

class OfferJobInfoBuilder:
    def __init__(self) -> None: ...
    def job_id(self, job_id: str) -> OfferJobInfoBuilder: ...
    def job_name(self, job_name: str) -> OfferJobInfoBuilder: ...
    def build(self) -> OfferJobInfo: ...
