from .offer_schema_name import OfferSchemaName as OfferSchemaName
from lark_oapi.core.construct import init as init

class OfferSchemaDetailOption:
    name: OfferSchemaName | None
    index: int | None
    active_status: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OfferSchemaDetailOptionBuilder: ...

class OfferSchemaDetailOptionBuilder:
    def __init__(self) -> None: ...
    def name(self, name: OfferSchemaName) -> OfferSchemaDetailOptionBuilder: ...
    def index(self, index: int) -> OfferSchemaDetailOptionBuilder: ...
    def active_status(self, active_status: int) -> OfferSchemaDetailOptionBuilder: ...
    def build(self) -> OfferSchemaDetailOption: ...
