from .offer_basic_info import OfferBasicInfo as OfferBasicInfo
from .offer_customized_info import OfferCustomizedInfo as OfferCustomizedInfo
from .offer_salary_info import OfferSalaryInfo as OfferSalaryInfo
from lark_oapi.core.construct import init as init

class OfferInfo:
    offer_id: str | None
    application_id: str | None
    schema_id: str | None
    offer_type: int | None
    basic_info: OfferBasicInfo | None
    salary_info: OfferSalaryInfo | None
    customized_info_list: list[OfferCustomizedInfo] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OfferInfoBuilder: ...

class OfferInfoBuilder:
    def __init__(self) -> None: ...
    def offer_id(self, offer_id: str) -> OfferInfoBuilder: ...
    def application_id(self, application_id: str) -> OfferInfoBuilder: ...
    def schema_id(self, schema_id: str) -> OfferInfoBuilder: ...
    def offer_type(self, offer_type: int) -> OfferInfoBuilder: ...
    def basic_info(self, basic_info: OfferBasicInfo) -> OfferInfoBuilder: ...
    def salary_info(self, salary_info: OfferSalaryInfo) -> OfferInfoBuilder: ...
    def customized_info_list(self, customized_info_list: list[OfferCustomizedInfo]) -> OfferInfoBuilder: ...
    def build(self) -> OfferInfo: ...
