from .application_offer_custom_value import ApplicationOfferCustomValue as ApplicationOfferCustomValue
from .base_address_v2 import BaseAddressV2 as BaseAddressV2
from .basic_department_info import BasicDepartmentInfo as BasicDepartmentInfo
from .basic_user_info import BasicUserInfo as BasicUserInfo
from .contract_period_info import ContractPeriodInfo as ContractPeriodInfo
from .id_name_object import IdNameObject as IdNameObject
from .offer_attachment_info import OfferAttachmentInfo as OfferAttachmentInfo
from lark_oapi.core.construct import init as init

class OfferBasicInfoV2:
    id: str | None
    offer_type: int | None
    offer_status: int | None
    leader: BasicUserInfo | None
    employee_type: IdNameObject | None
    department: BasicDepartmentInfo | None
    sequence: IdNameObject | None
    level: IdNameObject | None
    company_main_body: IdNameObject | None
    job_requirement_id: str | None
    probation_month: int | None
    contract_period: ContractPeriodInfo | None
    onboard_date: str | None
    owner: BasicUserInfo | None
    onboard_address: BaseAddressV2 | None
    work_address: BaseAddressV2 | None
    remark: str | None
    attachment_list: list[OfferAttachmentInfo] | None
    customize_info_list: list[ApplicationOfferCustomValue] | None
    create_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OfferBasicInfoV2Builder: ...

class OfferBasicInfoV2Builder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> OfferBasicInfoV2Builder: ...
    def offer_type(self, offer_type: int) -> OfferBasicInfoV2Builder: ...
    def offer_status(self, offer_status: int) -> OfferBasicInfoV2Builder: ...
    def leader(self, leader: BasicUserInfo) -> OfferBasicInfoV2Builder: ...
    def employee_type(self, employee_type: IdNameObject) -> OfferBasicInfoV2Builder: ...
    def department(self, department: BasicDepartmentInfo) -> OfferBasicInfoV2Builder: ...
    def sequence(self, sequence: IdNameObject) -> OfferBasicInfoV2Builder: ...
    def level(self, level: IdNameObject) -> OfferBasicInfoV2Builder: ...
    def company_main_body(self, company_main_body: IdNameObject) -> OfferBasicInfoV2Builder: ...
    def job_requirement_id(self, job_requirement_id: str) -> OfferBasicInfoV2Builder: ...
    def probation_month(self, probation_month: int) -> OfferBasicInfoV2Builder: ...
    def contract_period(self, contract_period: ContractPeriodInfo) -> OfferBasicInfoV2Builder: ...
    def onboard_date(self, onboard_date: str) -> OfferBasicInfoV2Builder: ...
    def owner(self, owner: BasicUserInfo) -> OfferBasicInfoV2Builder: ...
    def onboard_address(self, onboard_address: BaseAddressV2) -> OfferBasicInfoV2Builder: ...
    def work_address(self, work_address: BaseAddressV2) -> OfferBasicInfoV2Builder: ...
    def remark(self, remark: str) -> OfferBasicInfoV2Builder: ...
    def attachment_list(self, attachment_list: list[OfferAttachmentInfo]) -> OfferBasicInfoV2Builder: ...
    def customize_info_list(self, customize_info_list: list[ApplicationOfferCustomValue]) -> OfferBasicInfoV2Builder: ...
    def create_time(self, create_time: str) -> OfferBasicInfoV2Builder: ...
    def build(self) -> OfferBasicInfoV2: ...
