from .i18n import I18n as I18n
from .offer_apply_form_object_config_info import OfferApplyFormObjectConfigInfo as OfferApplyFormObjectConfigInfo
from lark_oapi.core.construct import init as init

class OfferApplyFormObjectInfo:
    id: str | None
    name: I18n | None
    description: I18n | None
    module_id: str | None
    is_customized: bool | None
    is_required: bool | None
    active_status: int | None
    need_approve: bool | None
    is_sensitive: bool | None
    object_type: int | None
    object_type_v2: int | None
    config: OfferApplyFormObjectConfigInfo | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OfferApplyFormObjectInfoBuilder: ...

class OfferApplyFormObjectInfoBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> OfferApplyFormObjectInfoBuilder: ...
    def name(self, name: I18n) -> OfferApplyFormObjectInfoBuilder: ...
    def description(self, description: I18n) -> OfferApplyFormObjectInfoBuilder: ...
    def module_id(self, module_id: str) -> OfferApplyFormObjectInfoBuilder: ...
    def is_customized(self, is_customized: bool) -> OfferApplyFormObjectInfoBuilder: ...
    def is_required(self, is_required: bool) -> OfferApplyFormObjectInfoBuilder: ...
    def active_status(self, active_status: int) -> OfferApplyFormObjectInfoBuilder: ...
    def need_approve(self, need_approve: bool) -> OfferApplyFormObjectInfoBuilder: ...
    def is_sensitive(self, is_sensitive: bool) -> OfferApplyFormObjectInfoBuilder: ...
    def object_type(self, object_type: int) -> OfferApplyFormObjectInfoBuilder: ...
    def object_type_v2(self, object_type_v2: int) -> OfferApplyFormObjectInfoBuilder: ...
    def config(self, config: OfferApplyFormObjectConfigInfo) -> OfferApplyFormObjectInfoBuilder: ...
    def build(self) -> OfferApplyFormObjectInfo: ...
