from lark_oapi.core.construct import init as init

class OfferSchemaName:
    zh_cn: str | None
    en_us: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OfferSchemaNameBuilder: ...

class OfferSchemaNameBuilder:
    def __init__(self) -> None: ...
    def zh_cn(self, zh_cn: str) -> OfferSchemaNameBuilder: ...
    def en_us(self, en_us: str) -> OfferSchemaNameBuilder: ...
    def build(self) -> OfferSchemaName: ...
