from .offer_schema_child import OfferSchemaChild as OfferSchemaChild
from lark_oapi.core.construct import init as init

class OfferSchemaListInfo:
    schema_list: list[OfferSchemaChild] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OfferSchemaListInfoBuilder: ...

class OfferSchemaListInfoBuilder:
    def __init__(self) -> None: ...
    def schema_list(self, schema_list: list[OfferSchemaChild]) -> OfferSchemaListInfoBuilder: ...
    def build(self) -> OfferSchemaListInfo: ...
