from lark_oapi.core.construct import init as init

class OpenJobRequestBody:
    expiry_time: int | None
    is_never_expired: bool | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OpenJobRequestBodyBuilder: ...

class OpenJobRequestBodyBuilder:
    def __init__(self) -> None: ...
    def expiry_time(self, expiry_time: int) -> OpenJobRequestBodyBuilder: ...
    def is_never_expired(self, is_never_expired: bool) -> OpenJobRequestBodyBuilder: ...
    def build(self) -> OpenJobRequestBody: ...
