from .open_job_request_body import OpenJobRequestBody as OpenJobRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class OpenJobRequest(BaseRequest):
    job_id: str | None
    request_body: OpenJobRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> OpenJobRequestBuilder: ...

class OpenJobRequestBuilder:
    def __init__(self) -> None: ...
    def job_id(self, job_id: str) -> OpenJobRequestBuilder: ...
    def request_body(self, request_body: OpenJobRequestBody) -> OpenJobRequestBuilder: ...
    def build(self) -> OpenJobRequest: ...
