from .operate_agency_account_agency_request_body import OperateAgencyAccountAgencyRequestBody as OperateAgencyAccountAgencyRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class OperateAgencyAccountAgencyRequest(BaseRequest):
    request_body: OperateAgencyAccountAgencyRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> OperateAgencyAccountAgencyRequestBuilder: ...

class OperateAgencyAccountAgencyRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: OperateAgencyAccountAgencyRequestBody) -> OperateAgencyAccountAgencyRequestBuilder: ...
    def build(self) -> OperateAgencyAccountAgencyRequest: ...
