from lark_oapi.core.construct import init as init

class OperateAgencyAccountAgencyRequestBody:
    option: int | None
    id: str | None
    reason: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OperateAgencyAccountAgencyRequestBodyBuilder: ...

class OperateAgencyAccountAgencyRequestBodyBuilder:
    def __init__(self) -> None: ...
    def option(self, option: int) -> OperateAgencyAccountAgencyRequestBodyBuilder: ...
    def id(self, id: str) -> OperateAgencyAccountAgencyRequestBodyBuilder: ...
    def reason(self, reason: str) -> OperateAgencyAccountAgencyRequestBodyBuilder: ...
    def build(self) -> OperateAgencyAccountAgencyRequestBody: ...
