from lark_oapi.core.construct import init as init

class OperateAgencyAccountAgencyResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> OperateAgencyAccountAgencyResponseBodyBuilder: ...

class OperateAgencyAccountAgencyResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> OperateAgencyAccountAgencyResponseBody: ...
