from .external_interview_assessment import ExternalInterviewAssessment as ExternalInterviewAssessment
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PatchExternalInterviewAssessmentRequest(BaseRequest):
    external_interview_assessment_id: str | None
    request_body: ExternalInterviewAssessment | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PatchExternalInterviewAssessmentRequestBuilder: ...

class PatchExternalInterviewAssessmentRequestBuilder:
    def __init__(self) -> None: ...
    def external_interview_assessment_id(self, external_interview_assessment_id: str) -> PatchExternalInterviewAssessmentRequestBuilder: ...
    def request_body(self, request_body: ExternalInterviewAssessment) -> PatchExternalInterviewAssessmentRequestBuilder: ...
    def build(self) -> PatchExternalInterviewAssessmentRequest: ...
