from .employee import Employee as Employee
from lark_oapi.core.construct import init as init

class PatchEmployeeResponseBody:
    employee: Employee | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchEmployeeResponseBodyBuilder: ...

class PatchEmployeeResponseBodyBuilder:
    def __init__(self) -> None: ...
    def employee(self, employee: Employee) -> PatchEmployeeResponseBodyBuilder: ...
    def build(self) -> PatchEmployeeResponseBody: ...
