from .patch_interviewer_request_body import PatchInterviewerRequestBody as PatchInterviewerRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PatchInterviewerRequest(BaseRequest):
    user_id_type: str | None
    interviewer_id: str | None
    request_body: PatchInterviewerRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PatchInterviewerRequestBuilder: ...

class PatchInterviewerRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> PatchInterviewerRequestBuilder: ...
    def interviewer_id(self, interviewer_id: str) -> PatchInterviewerRequestBuilder: ...
    def request_body(self, request_body: PatchInterviewerRequestBody) -> PatchInterviewerRequestBuilder: ...
    def build(self) -> PatchInterviewerRequest: ...
