from .ehr_import_task import EhrImportTask as EhrImportTask
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PatchEhrImportTaskRequest(BaseRequest):
    ehr_import_task_id: str | None
    request_body: EhrImportTask | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PatchEhrImportTaskRequestBuilder: ...

class PatchEhrImportTaskRequestBuilder:
    def __init__(self) -> None: ...
    def ehr_import_task_id(self, ehr_import_task_id: str) -> PatchEhrImportTaskRequestBuilder: ...
    def request_body(self, request_body: EhrImportTask) -> PatchEhrImportTaskRequestBuilder: ...
    def build(self) -> PatchEhrImportTaskRequest: ...
