from .note import Note as Note
from lark_oapi.core.construct import init as init

class PatchNoteResponseBody:
    note: Note | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PatchNoteResponseBodyBuilder: ...

class PatchNoteResponseBodyBuilder:
    def __init__(self) -> None: ...
    def note(self, note: Note) -> PatchNoteResponseBodyBuilder: ...
    def build(self) -> PatchNoteResponseBody: ...
