from .patch_note_request_body import PatchNoteRequestBody as PatchNoteRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class PatchNoteRequest(BaseRequest):
    user_id_type: str | None
    note_id: str | None
    request_body: PatchNoteRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> PatchNoteRequestBuilder: ...

class PatchNoteRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> PatchNoteRequestBuilder: ...
    def note_id(self, note_id: str) -> PatchNoteRequestBuilder: ...
    def request_body(self, request_body: PatchNoteRequestBody) -> PatchNoteRequestBuilder: ...
    def build(self) -> PatchNoteRequest: ...
