from .permission_scope_rule import PermissionScopeRule as PermissionScopeRule
from lark_oapi.core.construct import init as init

class PermissionGroupInfo:
    permission_ids: list[str] | None
    scope_rule: PermissionScopeRule | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PermissionGroupInfoBuilder: ...

class PermissionGroupInfoBuilder:
    def __init__(self) -> None: ...
    def permission_ids(self, permission_ids: list[str]) -> PermissionGroupInfoBuilder: ...
    def scope_rule(self, scope_rule: PermissionScopeRule) -> PermissionGroupInfoBuilder: ...
    def build(self) -> PermissionGroupInfo: ...
