from lark_oapi.core.construct import init as init

class ProjectInfo:
    desc: str | None
    end_time: int | None
    link: str | None
    name: str | None
    role: str | None
    start_time: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ProjectInfoBuilder: ...

class ProjectInfoBuilder:
    def __init__(self) -> None: ...
    def desc(self, desc: str) -> ProjectInfoBuilder: ...
    def end_time(self, end_time: int) -> ProjectInfoBuilder: ...
    def link(self, link: str) -> ProjectInfoBuilder: ...
    def name(self, name: str) -> ProjectInfoBuilder: ...
    def role(self, role: str) -> ProjectInfoBuilder: ...
    def start_time(self, start_time: int) -> ProjectInfoBuilder: ...
    def build(self) -> ProjectInfo: ...
