from lark_oapi.core.construct import init as init

class ProtectAgencyResponseBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ProtectAgencyResponseBodyBuilder: ...

class ProtectAgencyResponseBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> ProtectAgencyResponseBody: ...
