from lark_oapi.core.construct import init as init

class ProtectSearchAgencyRequestBody:
    talent_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ProtectSearchAgencyRequestBodyBuilder: ...

class ProtectSearchAgencyRequestBodyBuilder:
    def __init__(self) -> None: ...
    def talent_id(self, talent_id: str) -> ProtectSearchAgencyRequestBodyBuilder: ...
    def build(self) -> ProtectSearchAgencyRequestBody: ...
