from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class ProviderIdNameObject:
    provider_id: str | None
    provider_name: I18n | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ProviderIdNameObjectBuilder: ...

class ProviderIdNameObjectBuilder:
    def __init__(self) -> None: ...
    def provider_id(self, provider_id: str) -> ProviderIdNameObjectBuilder: ...
    def provider_name(self, provider_name: I18n) -> ProviderIdNameObjectBuilder: ...
    def build(self) -> ProviderIdNameObject: ...
