from lark_oapi.core.construct import init as init

class PushStage:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> PushStageBuilder: ...

class PushStageBuilder:
    def __init__(self) -> None: ...
    def build(self) -> PushStage: ...
