from lark_oapi.core.construct import init as init

class QueryTalentObjectRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryTalentObjectRequestBodyBuilder: ...

class QueryTalentObjectRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> QueryTalentObjectRequestBody: ...
