from lark_oapi.core.construct import init as init

class QueryLocationRequestBody:
    code_list: list[str] | None
    location_type: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> QueryLocationRequestBodyBuilder: ...

class QueryLocationRequestBodyBuilder:
    def __init__(self) -> None: ...
    def code_list(self, code_list: list[str]) -> QueryLocationRequestBodyBuilder: ...
    def location_type(self, location_type: int) -> QueryLocationRequestBodyBuilder: ...
    def build(self) -> QueryLocationRequestBody: ...
