from .reconciliation_referral_account_request_body import ReconciliationReferralAccountRequestBody as ReconciliationReferralAccountRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class ReconciliationReferralAccountRequest(BaseRequest):
    request_body: ReconciliationReferralAccountRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> ReconciliationReferralAccountRequestBuilder: ...

class ReconciliationReferralAccountRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: ReconciliationReferralAccountRequestBody) -> ReconciliationReferralAccountRequestBuilder: ...
    def build(self) -> ReconciliationReferralAccountRequest: ...
