from .check_failed_account_info import CheckFailedAccountInfo as CheckFailedAccountInfo
from lark_oapi.core.construct import init as init

class ReconciliationReferralAccountResponseBody:
    check_failed_list: list[CheckFailedAccountInfo] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReconciliationReferralAccountResponseBodyBuilder: ...

class ReconciliationReferralAccountResponseBodyBuilder:
    def __init__(self) -> None: ...
    def check_failed_list(self, check_failed_list: list[CheckFailedAccountInfo]) -> ReconciliationReferralAccountResponseBodyBuilder: ...
    def build(self) -> ReconciliationReferralAccountResponseBody: ...
