from lark_oapi.core.construct import init as init

class RecoverApplicationRequestBody:
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RecoverApplicationRequestBodyBuilder: ...

class RecoverApplicationRequestBodyBuilder:
    def __init__(self) -> None: ...
    def build(self) -> RecoverApplicationRequestBody: ...
