from .basic_user_info import BasicUserInfo as BasicUserInfo
from lark_oapi.core.construct import init as init

class ReferralBasicInfo:
    id: str | None
    application_id: str | None
    referral_type: int | None
    user_info: BasicUserInfo | None
    create_time: str | None
    referral_method: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReferralBasicInfoBuilder: ...

class ReferralBasicInfoBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> ReferralBasicInfoBuilder: ...
    def application_id(self, application_id: str) -> ReferralBasicInfoBuilder: ...
    def referral_type(self, referral_type: int) -> ReferralBasicInfoBuilder: ...
    def user_info(self, user_info: BasicUserInfo) -> ReferralBasicInfoBuilder: ...
    def create_time(self, create_time: str) -> ReferralBasicInfoBuilder: ...
    def referral_method(self, referral_method: int) -> ReferralBasicInfoBuilder: ...
    def build(self) -> ReferralBasicInfo: ...
