from .id_name_object import IdNameObject as IdNameObject
from lark_oapi.core.construct import init as init

class Referral:
    id: str | None
    application_id: str | None
    create_time: int | None
    referral_user_id: str | None
    referral_user: IdNameObject | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReferralBuilder: ...

class ReferralBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> ReferralBuilder: ...
    def application_id(self, application_id: str) -> ReferralBuilder: ...
    def create_time(self, create_time: int) -> ReferralBuilder: ...
    def referral_user_id(self, referral_user_id: str) -> ReferralBuilder: ...
    def referral_user(self, referral_user: IdNameObject) -> ReferralBuilder: ...
    def build(self) -> Referral: ...
