from .specific_relationship import SpecificRelationship as SpecificRelationship
from lark_oapi.core.construct import init as init

class ReferralRecommendInfo:
    relationship: int | None
    familiarity: int | None
    comment: str | None
    specific_relationship: SpecificRelationship | None
    work_ability_familiarity: int | None
    match_degree: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ReferralRecommendInfoBuilder: ...

class ReferralRecommendInfoBuilder:
    def __init__(self) -> None: ...
    def relationship(self, relationship: int) -> ReferralRecommendInfoBuilder: ...
    def familiarity(self, familiarity: int) -> ReferralRecommendInfoBuilder: ...
    def comment(self, comment: str) -> ReferralRecommendInfoBuilder: ...
    def specific_relationship(self, specific_relationship: SpecificRelationship) -> ReferralRecommendInfoBuilder: ...
    def work_ability_familiarity(self, work_ability_familiarity: int) -> ReferralRecommendInfoBuilder: ...
    def match_degree(self, match_degree: int) -> ReferralRecommendInfoBuilder: ...
    def build(self) -> ReferralRecommendInfo: ...
