from lark_oapi.core.construct import init as init

class RegistrationInfo:
    schema_id: str | None
    name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RegistrationInfoBuilder: ...

class RegistrationInfoBuilder:
    def __init__(self) -> None: ...
    def schema_id(self, schema_id: str) -> RegistrationInfoBuilder: ...
    def name(self, name: str) -> RegistrationInfoBuilder: ...
    def build(self) -> RegistrationInfo: ...
