from .common_schema import CommonSchema as CommonSchema
from lark_oapi.core.construct import init as init

class RegistrationSchema:
    id: str | None
    name: str | None
    scenarios: list[int] | None
    objects: list[CommonSchema] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RegistrationSchemaBuilder: ...

class RegistrationSchemaBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> RegistrationSchemaBuilder: ...
    def name(self, name: str) -> RegistrationSchemaBuilder: ...
    def scenarios(self, scenarios: list[int]) -> RegistrationSchemaBuilder: ...
    def objects(self, objects: list[CommonSchema]) -> RegistrationSchemaBuilder: ...
    def build(self) -> RegistrationSchema: ...
