from lark_oapi.core.construct import init as init

class RemoveToFolderTalentRequestBody:
    talent_id_list: list[str] | None
    folder_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> RemoveToFolderTalentRequestBodyBuilder: ...

class RemoveToFolderTalentRequestBodyBuilder:
    def __init__(self) -> None: ...
    def talent_id_list(self, talent_id_list: list[str]) -> RemoveToFolderTalentRequestBodyBuilder: ...
    def folder_id(self, folder_id: str) -> RemoveToFolderTalentRequestBodyBuilder: ...
    def build(self) -> RemoveToFolderTalentRequestBody: ...
