from .remove_to_folder_talent_request_body import RemoveToFolderTalentRequestBody as RemoveToFolderTalentRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class RemoveToFolderTalentRequest(BaseRequest):
    request_body: RemoveToFolderTalentRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> RemoveToFolderTalentRequestBuilder: ...

class RemoveToFolderTalentRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: RemoveToFolderTalentRequestBody) -> RemoveToFolderTalentRequestBuilder: ...
    def build(self) -> RemoveToFolderTalentRequest: ...
