from lark_oapi.core.construct import init as init

class ScoreCalculationConfig:
    enabled: bool | None
    calculation_mode: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> ScoreCalculationConfigBuilder: ...

class ScoreCalculationConfigBuilder:
    def __init__(self) -> None: ...
    def enabled(self, enabled: bool) -> ScoreCalculationConfigBuilder: ...
    def calculation_mode(self, calculation_mode: int) -> ScoreCalculationConfigBuilder: ...
    def build(self) -> ScoreCalculationConfig: ...
