from lark_oapi.core.construct import init as init

class SearchTalentOperationLogRequestBody:
    job_id_list: list[str] | None
    operator_id_list: list[str] | None
    operation_list: list[int] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SearchTalentOperationLogRequestBodyBuilder: ...

class SearchTalentOperationLogRequestBodyBuilder:
    def __init__(self) -> None: ...
    def job_id_list(self, job_id_list: list[str]) -> SearchTalentOperationLogRequestBodyBuilder: ...
    def operator_id_list(self, operator_id_list: list[str]) -> SearchTalentOperationLogRequestBodyBuilder: ...
    def operation_list(self, operation_list: list[int]) -> SearchTalentOperationLogRequestBodyBuilder: ...
    def build(self) -> SearchTalentOperationLogRequestBody: ...
