from .website_job_post import WebsiteJobPost as WebsiteJobPost
from lark_oapi.core.construct import init as init

class SearchJobPublishRecordResponseBody:
    items: list[WebsiteJobPost] | None
    has_more: bool | None
    page_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SearchJobPublishRecordResponseBodyBuilder: ...

class SearchJobPublishRecordResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[WebsiteJobPost]) -> SearchJobPublishRecordResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> SearchJobPublishRecordResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> SearchJobPublishRecordResponseBodyBuilder: ...
    def build(self) -> SearchJobPublishRecordResponseBody: ...
