from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class SearchTalentPoolRequest(BaseRequest):
    page_size: int | None
    page_token: str | None
    id_list: list[str] | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> SearchTalentPoolRequestBuilder: ...

class SearchTalentPoolRequestBuilder:
    def __init__(self) -> None: ...
    def page_size(self, page_size: int) -> SearchTalentPoolRequestBuilder: ...
    def page_token(self, page_token: str) -> SearchTalentPoolRequestBuilder: ...
    def id_list(self, id_list: list[str]) -> SearchTalentPoolRequestBuilder: ...
    def build(self) -> SearchTalentPoolRequest: ...
