from .di_info import DiInfo as DiInfo
from lark_oapi.core.construct import init as init

class SearchDiversityInclusionResponseBody:
    items: list[DiInfo] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SearchDiversityInclusionResponseBodyBuilder: ...

class SearchDiversityInclusionResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[DiInfo]) -> SearchDiversityInclusionResponseBodyBuilder: ...
    def build(self) -> SearchDiversityInclusionResponseBody: ...
