from lark_oapi.core.construct import init as init

class SearchDiversityInclusionRequestBody:
    talent_ids: list[str] | None
    application_ids: list[str] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SearchDiversityInclusionRequestBodyBuilder: ...

class SearchDiversityInclusionRequestBodyBuilder:
    def __init__(self) -> None: ...
    def talent_ids(self, talent_ids: list[str]) -> SearchDiversityInclusionRequestBodyBuilder: ...
    def application_ids(self, application_ids: list[str]) -> SearchDiversityInclusionRequestBodyBuilder: ...
    def build(self) -> SearchDiversityInclusionRequestBody: ...
