from .search_diversity_inclusion_request_body import SearchDiversityInclusionRequestBody as SearchDiversityInclusionRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class SearchDiversityInclusionRequest(BaseRequest):
    request_body: SearchDiversityInclusionRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> SearchDiversityInclusionRequestBuilder: ...

class SearchDiversityInclusionRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: SearchDiversityInclusionRequestBody) -> SearchDiversityInclusionRequestBuilder: ...
    def build(self) -> SearchDiversityInclusionRequest: ...
