from .search_referral_request_body import SearchReferralRequestBody as SearchReferralRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class SearchReferralRequest(BaseRequest):
    user_id_type: str | None
    request_body: SearchReferralRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> SearchReferralRequestBuilder: ...

class SearchReferralRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> SearchReferralRequestBuilder: ...
    def request_body(self, request_body: SearchReferralRequestBody) -> SearchReferralRequestBuilder: ...
    def build(self) -> SearchReferralRequest: ...
