from .search_test_request_body import SearchTestRequestBody as SearchTestRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class SearchTestRequest(BaseRequest):
    page_token: str | None
    page_size: int | None
    user_id_type: str | None
    request_body: SearchTestRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> SearchTestRequestBuilder: ...

class SearchTestRequestBuilder:
    def __init__(self) -> None: ...
    def page_token(self, page_token: str) -> SearchTestRequestBuilder: ...
    def page_size(self, page_size: int) -> SearchTestRequestBuilder: ...
    def user_id_type(self, user_id_type: str) -> SearchTestRequestBuilder: ...
    def request_body(self, request_body: SearchTestRequestBody) -> SearchTestRequestBuilder: ...
    def build(self) -> SearchTestRequest: ...
