from .website_job_post import WebsiteJobPost as WebsiteJobPost
from lark_oapi.core.construct import init as init

class SearchWebsiteJobPostResponseBody:
    items: list[WebsiteJobPost] | None
    has_more: bool | None
    page_token: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SearchWebsiteJobPostResponseBodyBuilder: ...

class SearchWebsiteJobPostResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[WebsiteJobPost]) -> SearchWebsiteJobPostResponseBodyBuilder: ...
    def has_more(self, has_more: bool) -> SearchWebsiteJobPostResponseBodyBuilder: ...
    def page_token(self, page_token: str) -> SearchWebsiteJobPostResponseBodyBuilder: ...
    def build(self) -> SearchWebsiteJobPostResponseBody: ...
