from .referral_info import ReferralInfo as ReferralInfo
from lark_oapi.core.construct import init as init

class SearchReferralResponseBody:
    items: list[ReferralInfo] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SearchReferralResponseBodyBuilder: ...

class SearchReferralResponseBodyBuilder:
    def __init__(self) -> None: ...
    def items(self, items: list[ReferralInfo]) -> SearchReferralResponseBodyBuilder: ...
    def build(self) -> SearchReferralResponseBody: ...
