from lark_oapi.core.construct import init as init

class SiteResumeLanguageSkill:
    language: str | None
    proficiency: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SiteResumeLanguageSkillBuilder: ...

class SiteResumeLanguageSkillBuilder:
    def __init__(self) -> None: ...
    def language(self, language: str) -> SiteResumeLanguageSkillBuilder: ...
    def proficiency(self, proficiency: str) -> SiteResumeLanguageSkillBuilder: ...
    def build(self) -> SiteResumeLanguageSkill: ...
