from lark_oapi.core.construct import init as init

class SiteName:
    zh_cn: str | None
    en_us: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SiteNameBuilder: ...

class SiteNameBuilder:
    def __init__(self) -> None: ...
    def zh_cn(self, zh_cn: str) -> SiteNameBuilder: ...
    def en_us(self, en_us: str) -> SiteNameBuilder: ...
    def build(self) -> SiteName: ...
