from lark_oapi.core.construct import init as init

class SiteResumeAward:
    title: str | None
    award_time: str | None
    description: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SiteResumeAwardBuilder: ...

class SiteResumeAwardBuilder:
    def __init__(self) -> None: ...
    def title(self, title: str) -> SiteResumeAwardBuilder: ...
    def award_time(self, award_time: str) -> SiteResumeAwardBuilder: ...
    def description(self, description: str) -> SiteResumeAwardBuilder: ...
    def build(self) -> SiteResumeAward: ...
