from lark_oapi.core.construct import init as init

class SiteResumeCareer:
    company: str | None
    title: str | None
    career_type: str | None
    description: str | None
    start_time: str | None
    end_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SiteResumeCareerBuilder: ...

class SiteResumeCareerBuilder:
    def __init__(self) -> None: ...
    def company(self, company: str) -> SiteResumeCareerBuilder: ...
    def title(self, title: str) -> SiteResumeCareerBuilder: ...
    def career_type(self, career_type: str) -> SiteResumeCareerBuilder: ...
    def description(self, description: str) -> SiteResumeCareerBuilder: ...
    def start_time(self, start_time: str) -> SiteResumeCareerBuilder: ...
    def end_time(self, end_time: str) -> SiteResumeCareerBuilder: ...
    def build(self) -> SiteResumeCareer: ...
