from .site_name import SiteName as SiteName
from lark_oapi.core.construct import init as init

class SiteJobRecruitmentType:
    id: str | None
    name: SiteName | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SiteJobRecruitmentTypeBuilder: ...

class SiteJobRecruitmentTypeBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> SiteJobRecruitmentTypeBuilder: ...
    def name(self, name: SiteName) -> SiteJobRecruitmentTypeBuilder: ...
    def build(self) -> SiteJobRecruitmentType: ...
