from .site_resume_award import SiteResumeAward as SiteResumeAward
from .site_resume_career import SiteResumeCareer as SiteResumeCareer
from .site_resume_certificate import SiteResumeCertificate as SiteResumeCertificate
from .site_resume_competition import SiteResumeCompetition as SiteResumeCompetition
from .site_resume_education import SiteResumeEducation as SiteResumeEducation
from .site_resume_identification import SiteResumeIdentification as SiteResumeIdentification
from .site_resume_internship import SiteResumeInternship as SiteResumeInternship
from .site_resume_language_skill import SiteResumeLanguageSkill as SiteResumeLanguageSkill
from .site_resume_project import SiteResumeProject as SiteResumeProject
from .site_resume_sns import SiteResumeSns as SiteResumeSns
from .site_resume_work import SiteResumeWork as SiteResumeWork
from lark_oapi.core.construct import init as init

class SiteApplicationResume:
    name: str | None
    mobile_number: str | None
    moblie_code: str | None
    email: str | None
    site_attachment_id: str | None
    self_evaluation: str | None
    age: str | None
    working_year: str | None
    education_list: list[SiteResumeEducation] | None
    career_list: list[SiteResumeCareer] | None
    project_list: list[SiteResumeProject] | None
    internship_list: list[SiteResumeInternship] | None
    work_list: list[SiteResumeWork] | None
    award_list: list[SiteResumeAward] | None
    language_skill_list: list[SiteResumeLanguageSkill] | None
    sns_list: list[SiteResumeSns] | None
    identification: SiteResumeIdentification | None
    competition_list: list[SiteResumeCompetition] | None
    certificate_list: list[SiteResumeCertificate] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SiteApplicationResumeBuilder: ...

class SiteApplicationResumeBuilder:
    def __init__(self) -> None: ...
    def name(self, name: str) -> SiteApplicationResumeBuilder: ...
    def mobile_number(self, mobile_number: str) -> SiteApplicationResumeBuilder: ...
    def moblie_code(self, moblie_code: str) -> SiteApplicationResumeBuilder: ...
    def email(self, email: str) -> SiteApplicationResumeBuilder: ...
    def site_attachment_id(self, site_attachment_id: str) -> SiteApplicationResumeBuilder: ...
    def self_evaluation(self, self_evaluation: str) -> SiteApplicationResumeBuilder: ...
    def age(self, age: str) -> SiteApplicationResumeBuilder: ...
    def working_year(self, working_year: str) -> SiteApplicationResumeBuilder: ...
    def education_list(self, education_list: list[SiteResumeEducation]) -> SiteApplicationResumeBuilder: ...
    def career_list(self, career_list: list[SiteResumeCareer]) -> SiteApplicationResumeBuilder: ...
    def project_list(self, project_list: list[SiteResumeProject]) -> SiteApplicationResumeBuilder: ...
    def internship_list(self, internship_list: list[SiteResumeInternship]) -> SiteApplicationResumeBuilder: ...
    def work_list(self, work_list: list[SiteResumeWork]) -> SiteApplicationResumeBuilder: ...
    def award_list(self, award_list: list[SiteResumeAward]) -> SiteApplicationResumeBuilder: ...
    def language_skill_list(self, language_skill_list: list[SiteResumeLanguageSkill]) -> SiteApplicationResumeBuilder: ...
    def sns_list(self, sns_list: list[SiteResumeSns]) -> SiteApplicationResumeBuilder: ...
    def identification(self, identification: SiteResumeIdentification) -> SiteApplicationResumeBuilder: ...
    def competition_list(self, competition_list: list[SiteResumeCompetition]) -> SiteApplicationResumeBuilder: ...
    def certificate_list(self, certificate_list: list[SiteResumeCertificate]) -> SiteApplicationResumeBuilder: ...
    def build(self) -> SiteApplicationResume: ...
