from .site_name import SiteName as SiteName
from lark_oapi.core.construct import init as init

class SiteJobType:
    id: str | None
    name: SiteName | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SiteJobTypeBuilder: ...

class SiteJobTypeBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> SiteJobTypeBuilder: ...
    def name(self, name: SiteName) -> SiteJobTypeBuilder: ...
    def build(self) -> SiteJobType: ...
