from lark_oapi.core.construct import init as init

class SiteJobPostSearchRequest:
    keyword: str | None
    offset: int | None
    limit: int | None
    job_type_id_list: list[str] | None
    city_code_list: list[str] | None
    site_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> SiteJobPostSearchRequestBuilder: ...

class SiteJobPostSearchRequestBuilder:
    def __init__(self) -> None: ...
    def keyword(self, keyword: str) -> SiteJobPostSearchRequestBuilder: ...
    def offset(self, offset: int) -> SiteJobPostSearchRequestBuilder: ...
    def limit(self, limit: int) -> SiteJobPostSearchRequestBuilder: ...
    def job_type_id_list(self, job_type_id_list: list[str]) -> SiteJobPostSearchRequestBuilder: ...
    def city_code_list(self, city_code_list: list[str]) -> SiteJobPostSearchRequestBuilder: ...
    def site_id(self, site_id: str) -> SiteJobPostSearchRequestBuilder: ...
    def build(self) -> SiteJobPostSearchRequest: ...
