from .talent_customized_data_object_value_child import TalentCustomizedDataObjectValueChild as TalentCustomizedDataObjectValueChild
from lark_oapi.core.construct import init as init

class TalentCustomizedDataObjectValue:
    object_id: str | None
    value: str | None
    children: list[TalentCustomizedDataObjectValueChild] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TalentCustomizedDataObjectValueBuilder: ...

class TalentCustomizedDataObjectValueBuilder:
    def __init__(self) -> None: ...
    def object_id(self, object_id: str) -> TalentCustomizedDataObjectValueBuilder: ...
    def value(self, value: str) -> TalentCustomizedDataObjectValueBuilder: ...
    def children(self, children: list[TalentCustomizedDataObjectValueChild]) -> TalentCustomizedDataObjectValueBuilder: ...
    def build(self) -> TalentCustomizedDataObjectValue: ...
