from lark_oapi.core.construct import init as init

class TalentCityInfo:
    city_code: str | None
    zh_name: str | None
    en_name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TalentCityInfoBuilder: ...

class TalentCityInfoBuilder:
    def __init__(self) -> None: ...
    def city_code(self, city_code: str) -> TalentCityInfoBuilder: ...
    def zh_name(self, zh_name: str) -> TalentCityInfoBuilder: ...
    def en_name(self, en_name: str) -> TalentCityInfoBuilder: ...
    def build(self) -> TalentCityInfo: ...
