from .talent_city_info import TalentCityInfo as TalentCityInfo
from .talent_customized_data_child import TalentCustomizedDataChild as TalentCustomizedDataChild
from .talent_identification_info import TalentIdentificationInfo as TalentIdentificationInfo
from .talent_nationality import TalentNationality as TalentNationality
from lark_oapi.core.construct import init as init

class TalentBasicInfo:
    name: str | None
    mobile: str | None
    mobile_code: str | None
    mobile_country_code: str | None
    email: str | None
    experience_years: int | None
    age: int | None
    nationality: TalentNationality | None
    gender: int | None
    current_city: TalentCityInfo | None
    hometown_city: TalentCityInfo | None
    preferred_city_list: list[TalentCityInfo] | None
    identification_type: int | None
    identification_number: str | None
    identification: TalentIdentificationInfo | None
    birthday: int | None
    creator_id: str | None
    marital_status: int | None
    current_home_address: str | None
    customized_data_list: list[TalentCustomizedDataChild] | None
    modify_time: str | None
    hukou_location_code: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TalentBasicInfoBuilder: ...

class TalentBasicInfoBuilder:
    def __init__(self) -> None: ...
    def name(self, name: str) -> TalentBasicInfoBuilder: ...
    def mobile(self, mobile: str) -> TalentBasicInfoBuilder: ...
    def mobile_code(self, mobile_code: str) -> TalentBasicInfoBuilder: ...
    def mobile_country_code(self, mobile_country_code: str) -> TalentBasicInfoBuilder: ...
    def email(self, email: str) -> TalentBasicInfoBuilder: ...
    def experience_years(self, experience_years: int) -> TalentBasicInfoBuilder: ...
    def age(self, age: int) -> TalentBasicInfoBuilder: ...
    def nationality(self, nationality: TalentNationality) -> TalentBasicInfoBuilder: ...
    def gender(self, gender: int) -> TalentBasicInfoBuilder: ...
    def current_city(self, current_city: TalentCityInfo) -> TalentBasicInfoBuilder: ...
    def hometown_city(self, hometown_city: TalentCityInfo) -> TalentBasicInfoBuilder: ...
    def preferred_city_list(self, preferred_city_list: list[TalentCityInfo]) -> TalentBasicInfoBuilder: ...
    def identification_type(self, identification_type: int) -> TalentBasicInfoBuilder: ...
    def identification_number(self, identification_number: str) -> TalentBasicInfoBuilder: ...
    def identification(self, identification: TalentIdentificationInfo) -> TalentBasicInfoBuilder: ...
    def birthday(self, birthday: int) -> TalentBasicInfoBuilder: ...
    def creator_id(self, creator_id: str) -> TalentBasicInfoBuilder: ...
    def marital_status(self, marital_status: int) -> TalentBasicInfoBuilder: ...
    def current_home_address(self, current_home_address: str) -> TalentBasicInfoBuilder: ...
    def customized_data_list(self, customized_data_list: list[TalentCustomizedDataChild]) -> TalentBasicInfoBuilder: ...
    def modify_time(self, modify_time: str) -> TalentBasicInfoBuilder: ...
    def hukou_location_code(self, hukou_location_code: str) -> TalentBasicInfoBuilder: ...
    def build(self) -> TalentBasicInfo: ...
