from lark_oapi.core.construct import init as init

class TalentIdentificationInfo:
    identification_type: int | None
    identification_number: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TalentIdentificationInfoBuilder: ...

class TalentIdentificationInfoBuilder:
    def __init__(self) -> None: ...
    def identification_type(self, identification_type: int) -> TalentIdentificationInfoBuilder: ...
    def identification_number(self, identification_number: str) -> TalentIdentificationInfoBuilder: ...
    def build(self) -> TalentIdentificationInfo: ...
