from .talent_customized_data_child import TalentCustomizedDataChild as TalentCustomizedDataChild
from lark_oapi.core.construct import init as init

class TalentCertificateInfo:
    id: str | None
    name: str | None
    desc: str | None
    customized_data_list: list[TalentCustomizedDataChild] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TalentCertificateInfoBuilder: ...

class TalentCertificateInfoBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> TalentCertificateInfoBuilder: ...
    def name(self, name: str) -> TalentCertificateInfoBuilder: ...
    def desc(self, desc: str) -> TalentCertificateInfoBuilder: ...
    def customized_data_list(self, customized_data_list: list[TalentCustomizedDataChild]) -> TalentCertificateInfoBuilder: ...
    def build(self) -> TalentCertificateInfo: ...
