from .id_name_object import IdNameObject as IdNameObject
from lark_oapi.core.construct import init as init

class TalentOperationLog:
    application_id: str | None
    talent_id: str | None
    operator: IdNameObject | None
    operation_type: int | None
    operation_time: str | None
    operator_type: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TalentOperationLogBuilder: ...

class TalentOperationLogBuilder:
    def __init__(self) -> None: ...
    def application_id(self, application_id: str) -> TalentOperationLogBuilder: ...
    def talent_id(self, talent_id: str) -> TalentOperationLogBuilder: ...
    def operator(self, operator: IdNameObject) -> TalentOperationLogBuilder: ...
    def operation_type(self, operation_type: int) -> TalentOperationLogBuilder: ...
    def operation_time(self, operation_time: str) -> TalentOperationLogBuilder: ...
    def operator_type(self, operator_type: int) -> TalentOperationLogBuilder: ...
    def build(self) -> TalentOperationLog: ...
