from lark_oapi.core.construct import init as init

class TalentCustomizedTimeRange:
    start_time: str | None
    end_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TalentCustomizedTimeRangeBuilder: ...

class TalentCustomizedTimeRangeBuilder:
    def __init__(self) -> None: ...
    def start_time(self, start_time: str) -> TalentCustomizedTimeRangeBuilder: ...
    def end_time(self, end_time: str) -> TalentCustomizedTimeRangeBuilder: ...
    def build(self) -> TalentCustomizedTimeRange: ...
