from .i18n import I18n as I18n
from .talent_customized_data_child import TalentCustomizedDataChild as TalentCustomizedDataChild
from lark_oapi.core.construct import init as init

class TalentCustomizedData:
    object_id: str | None
    name: I18n | None
    object_type: int | None
    children: list[TalentCustomizedDataChild] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TalentCustomizedDataBuilder: ...

class TalentCustomizedDataBuilder:
    def __init__(self) -> None: ...
    def object_id(self, object_id: str) -> TalentCustomizedDataBuilder: ...
    def name(self, name: I18n) -> TalentCustomizedDataBuilder: ...
    def object_type(self, object_type: int) -> TalentCustomizedDataBuilder: ...
    def children(self, children: list[TalentCustomizedDataChild]) -> TalentCustomizedDataBuilder: ...
    def build(self) -> TalentCustomizedData: ...
