from lark_oapi.core.construct import init as init

class TalentNationality:
    nationality_code: str | None
    zh_name: str | None
    en_name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TalentNationalityBuilder: ...

class TalentNationalityBuilder:
    def __init__(self) -> None: ...
    def nationality_code(self, nationality_code: str) -> TalentNationalityBuilder: ...
    def zh_name(self, zh_name: str) -> TalentNationalityBuilder: ...
    def en_name(self, en_name: str) -> TalentNationalityBuilder: ...
    def build(self) -> TalentNationality: ...
