from lark_oapi.core.construct import init as init

class TalentExternalInfo:
    talent_id: str | None
    external_create_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TalentExternalInfoBuilder: ...

class TalentExternalInfoBuilder:
    def __init__(self) -> None: ...
    def talent_id(self, talent_id: str) -> TalentExternalInfoBuilder: ...
    def external_create_time(self, external_create_time: str) -> TalentExternalInfoBuilder: ...
    def build(self) -> TalentExternalInfo: ...
