from .i18n import I18n as I18n
from .talent_schema_child_object import TalentSchemaChildObject as TalentSchemaChildObject
from .talent_schema_option import TalentSchemaOption as TalentSchemaOption
from lark_oapi.core.construct import init as init

class TalentSchemaObject:
    id: str | None
    active_status: int | None
    is_customized: bool | None
    name: I18n | None
    option_list: list[TalentSchemaOption] | None
    children: list[TalentSchemaChildObject] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TalentSchemaObjectBuilder: ...

class TalentSchemaObjectBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> TalentSchemaObjectBuilder: ...
    def active_status(self, active_status: int) -> TalentSchemaObjectBuilder: ...
    def is_customized(self, is_customized: bool) -> TalentSchemaObjectBuilder: ...
    def name(self, name: I18n) -> TalentSchemaObjectBuilder: ...
    def option_list(self, option_list: list[TalentSchemaOption]) -> TalentSchemaObjectBuilder: ...
    def children(self, children: list[TalentSchemaChildObject]) -> TalentSchemaObjectBuilder: ...
    def build(self) -> TalentSchemaObject: ...
