from .i18n import I18n as I18n
from lark_oapi.core.construct import init as init

class TalentPool:
    id: str | None
    i18n_name: I18n | None
    i18n_description: I18n | None
    parent_id: str | None
    is_private: int | None
    create_time: str | None
    modify_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TalentPoolBuilder: ...

class TalentPoolBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> TalentPoolBuilder: ...
    def i18n_name(self, i18n_name: I18n) -> TalentPoolBuilder: ...
    def i18n_description(self, i18n_description: I18n) -> TalentPoolBuilder: ...
    def parent_id(self, parent_id: str) -> TalentPoolBuilder: ...
    def is_private(self, is_private: int) -> TalentPoolBuilder: ...
    def create_time(self, create_time: str) -> TalentPoolBuilder: ...
    def modify_time(self, modify_time: str) -> TalentPoolBuilder: ...
    def build(self) -> TalentPool: ...
