from .terminate_application_request_body import TerminateApplicationRequestBody as TerminateApplicationRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class TerminateApplicationRequest(BaseRequest):
    application_id: str | None
    request_body: TerminateApplicationRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> TerminateApplicationRequestBuilder: ...

class TerminateApplicationRequestBuilder:
    def __init__(self) -> None: ...
    def application_id(self, application_id: str) -> TerminateApplicationRequestBuilder: ...
    def request_body(self, request_body: TerminateApplicationRequestBody) -> TerminateApplicationRequestBuilder: ...
    def build(self) -> TerminateApplicationRequest: ...
