from .i18n import I18n as I18n
from .termination_reason_child_info import TerminationReasonChildInfo as TerminationReasonChildInfo
from lark_oapi.core.construct import init as init

class TerminationReasonInfo:
    id: str | None
    name: I18n | None
    children: list[TerminationReasonChildInfo] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TerminationReasonInfoBuilder: ...

class TerminationReasonInfoBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> TerminationReasonInfoBuilder: ...
    def name(self, name: I18n) -> TerminationReasonInfoBuilder: ...
    def children(self, children: list[TerminationReasonChildInfo]) -> TerminationReasonInfoBuilder: ...
    def build(self) -> TerminationReasonInfo: ...
