from .todo_common import TodoCommon as TodoCommon
from lark_oapi.core.construct import init as init

class Todo:
    evaluation: TodoCommon | None
    offer: TodoCommon | None
    exam: TodoCommon | None
    interview: TodoCommon | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TodoBuilder: ...

class TodoBuilder:
    def __init__(self) -> None: ...
    def evaluation(self, evaluation: TodoCommon) -> TodoBuilder: ...
    def offer(self, offer: TodoCommon) -> TodoBuilder: ...
    def exam(self, exam: TodoCommon) -> TodoBuilder: ...
    def interview(self, interview: TodoCommon) -> TodoBuilder: ...
    def build(self) -> Todo: ...
