from .bonus_amount import BonusAmount as BonusAmount
from lark_oapi.core.construct import init as init

class TradeDetail:
    account_id: str | None
    total_recharge_reward_info: BonusAmount | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TradeDetailBuilder: ...

class TradeDetailBuilder:
    def __init__(self) -> None: ...
    def account_id(self, account_id: str) -> TradeDetailBuilder: ...
    def total_recharge_reward_info(self, total_recharge_reward_info: BonusAmount) -> TradeDetailBuilder: ...
    def build(self) -> TradeDetail: ...
