from .employee import Employee as Employee
from lark_oapi.core.construct import init as init

class TransferOnboardApplicationResponseBody:
    employee: Employee | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TransferOnboardApplicationResponseBodyBuilder: ...

class TransferOnboardApplicationResponseBodyBuilder:
    def __init__(self) -> None: ...
    def employee(self, employee: Employee) -> TransferOnboardApplicationResponseBodyBuilder: ...
    def build(self) -> TransferOnboardApplicationResponseBody: ...
