from lark_oapi.core.construct import init as init

class TransferStageApplicationRequestBody:
    stage_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TransferStageApplicationRequestBodyBuilder: ...

class TransferStageApplicationRequestBodyBuilder:
    def __init__(self) -> None: ...
    def stage_id(self, stage_id: str) -> TransferStageApplicationRequestBodyBuilder: ...
    def build(self) -> TransferStageApplicationRequestBody: ...
