from .transfer_stage_application_request_body import TransferStageApplicationRequestBody as TransferStageApplicationRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class TransferStageApplicationRequest(BaseRequest):
    application_id: str | None
    request_body: TransferStageApplicationRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> TransferStageApplicationRequestBuilder: ...

class TransferStageApplicationRequestBuilder:
    def __init__(self) -> None: ...
    def application_id(self, application_id: str) -> TransferStageApplicationRequestBuilder: ...
    def request_body(self, request_body: TransferStageApplicationRequestBody) -> TransferStageApplicationRequestBuilder: ...
    def build(self) -> TransferStageApplicationRequest: ...
