from lark_oapi.core.construct import init as init

class TripartiteAgreementInfo:
    id: str | None
    application_id: str | None
    state: int | None
    create_time: str | None
    modify_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> TripartiteAgreementInfoBuilder: ...

class TripartiteAgreementInfoBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> TripartiteAgreementInfoBuilder: ...
    def application_id(self, application_id: str) -> TripartiteAgreementInfoBuilder: ...
    def state(self, state: int) -> TripartiteAgreementInfoBuilder: ...
    def create_time(self, create_time: str) -> TripartiteAgreementInfoBuilder: ...
    def modify_time(self, modify_time: str) -> TripartiteAgreementInfoBuilder: ...
    def build(self) -> TripartiteAgreementInfo: ...
