from .offer_custom_field import OfferCustomField as OfferCustomField
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UpdateOfferCustomFieldRequest(BaseRequest):
    offer_custom_field_id: str | None
    request_body: OfferCustomField | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UpdateOfferCustomFieldRequestBuilder: ...

class UpdateOfferCustomFieldRequestBuilder:
    def __init__(self) -> None: ...
    def offer_custom_field_id(self, offer_custom_field_id: str) -> UpdateOfferCustomFieldRequestBuilder: ...
    def request_body(self, request_body: OfferCustomField) -> UpdateOfferCustomFieldRequestBuilder: ...
    def build(self) -> UpdateOfferCustomFieldRequest: ...
