from .talent_external_info import TalentExternalInfo as TalentExternalInfo
from lark_oapi.core.construct import init as init

class UpdateTalentExternalInfoResponseBody:
    external_info: TalentExternalInfo | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateTalentExternalInfoResponseBodyBuilder: ...

class UpdateTalentExternalInfoResponseBodyBuilder:
    def __init__(self) -> None: ...
    def external_info(self, external_info: TalentExternalInfo) -> UpdateTalentExternalInfoResponseBodyBuilder: ...
    def build(self) -> UpdateTalentExternalInfoResponseBody: ...
