from lark_oapi.core.construct import init as init

class UpdateWebsiteChannelResponseBody:
    id: str | None
    name: str | None
    link: str | None
    code: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateWebsiteChannelResponseBodyBuilder: ...

class UpdateWebsiteChannelResponseBodyBuilder:
    def __init__(self) -> None: ...
    def id(self, id: str) -> UpdateWebsiteChannelResponseBodyBuilder: ...
    def name(self, name: str) -> UpdateWebsiteChannelResponseBodyBuilder: ...
    def link(self, link: str) -> UpdateWebsiteChannelResponseBodyBuilder: ...
    def code(self, code: str) -> UpdateWebsiteChannelResponseBodyBuilder: ...
    def build(self) -> UpdateWebsiteChannelResponseBody: ...
