from .eco_background_check_report_file import EcoBackgroundCheckReportFile as EcoBackgroundCheckReportFile
from lark_oapi.core.construct import init as init

class UpdateProgressEcoBackgroundCheckRequestBody:
    background_check_id: str | None
    stage_id: str | None
    stage_en_name: str | None
    stage_name: str | None
    stage_time: str | None
    result: str | None
    operator_role: int | None
    report_file_list: list[EcoBackgroundCheckReportFile] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateProgressEcoBackgroundCheckRequestBodyBuilder: ...

class UpdateProgressEcoBackgroundCheckRequestBodyBuilder:
    def __init__(self) -> None: ...
    def background_check_id(self, background_check_id: str) -> UpdateProgressEcoBackgroundCheckRequestBodyBuilder: ...
    def stage_id(self, stage_id: str) -> UpdateProgressEcoBackgroundCheckRequestBodyBuilder: ...
    def stage_en_name(self, stage_en_name: str) -> UpdateProgressEcoBackgroundCheckRequestBodyBuilder: ...
    def stage_name(self, stage_name: str) -> UpdateProgressEcoBackgroundCheckRequestBodyBuilder: ...
    def stage_time(self, stage_time: str) -> UpdateProgressEcoBackgroundCheckRequestBodyBuilder: ...
    def result(self, result: str) -> UpdateProgressEcoBackgroundCheckRequestBodyBuilder: ...
    def operator_role(self, operator_role: int) -> UpdateProgressEcoBackgroundCheckRequestBodyBuilder: ...
    def report_file_list(self, report_file_list: list[EcoBackgroundCheckReportFile]) -> UpdateProgressEcoBackgroundCheckRequestBodyBuilder: ...
    def build(self) -> UpdateProgressEcoBackgroundCheckRequestBody: ...
