from .external_background_check import ExternalBackgroundCheck as ExternalBackgroundCheck
from lark_oapi.core.construct import init as init

class UpdateExternalBackgroundCheckResponseBody:
    external_background_check: ExternalBackgroundCheck | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateExternalBackgroundCheckResponseBodyBuilder: ...

class UpdateExternalBackgroundCheckResponseBodyBuilder:
    def __init__(self) -> None: ...
    def external_background_check(self, external_background_check: ExternalBackgroundCheck) -> UpdateExternalBackgroundCheckResponseBodyBuilder: ...
    def build(self) -> UpdateExternalBackgroundCheckResponseBody: ...
