from .external_offer import ExternalOffer as ExternalOffer
from lark_oapi.core.construct import init as init

class UpdateExternalOfferResponseBody:
    external_offer: ExternalOffer | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateExternalOfferResponseBodyBuilder: ...

class UpdateExternalOfferResponseBodyBuilder:
    def __init__(self) -> None: ...
    def external_offer(self, external_offer: ExternalOffer) -> UpdateExternalOfferResponseBodyBuilder: ...
    def build(self) -> UpdateExternalOfferResponseBody: ...
