from .update_progress_eco_background_check_request_body import UpdateProgressEcoBackgroundCheckRequestBody as UpdateProgressEcoBackgroundCheckRequestBody
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UpdateProgressEcoBackgroundCheckRequest(BaseRequest):
    request_body: UpdateProgressEcoBackgroundCheckRequestBody | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UpdateProgressEcoBackgroundCheckRequestBuilder: ...

class UpdateProgressEcoBackgroundCheckRequestBuilder:
    def __init__(self) -> None: ...
    def request_body(self, request_body: UpdateProgressEcoBackgroundCheckRequestBody) -> UpdateProgressEcoBackgroundCheckRequestBuilder: ...
    def build(self) -> UpdateProgressEcoBackgroundCheckRequest: ...
