from lark_oapi.core.construct import init as init

class UpdateTalentExternalInfoRequestBody:
    external_create_time: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UpdateTalentExternalInfoRequestBodyBuilder: ...

class UpdateTalentExternalInfoRequestBodyBuilder:
    def __init__(self) -> None: ...
    def external_create_time(self, external_create_time: str) -> UpdateTalentExternalInfoRequestBodyBuilder: ...
    def build(self) -> UpdateTalentExternalInfoRequestBody: ...
