from .offer_info import OfferInfo as OfferInfo
from lark_oapi.core.enum import AccessTokenType as AccessTokenType, HttpMethod as HttpMethod
from lark_oapi.core.model import BaseRequest as BaseRequest

class UpdateOfferRequest(BaseRequest):
    user_id_type: str | None
    department_id_type: str | None
    job_level_id_type: str | None
    job_family_id_type: str | None
    employee_type_id_type: str | None
    offer_id: str | None
    request_body: OfferInfo | None
    def __init__(self) -> None: ...
    @staticmethod
    def builder() -> UpdateOfferRequestBuilder: ...

class UpdateOfferRequestBuilder:
    def __init__(self) -> None: ...
    def user_id_type(self, user_id_type: str) -> UpdateOfferRequestBuilder: ...
    def department_id_type(self, department_id_type: str) -> UpdateOfferRequestBuilder: ...
    def job_level_id_type(self, job_level_id_type: str) -> UpdateOfferRequestBuilder: ...
    def job_family_id_type(self, job_family_id_type: str) -> UpdateOfferRequestBuilder: ...
    def employee_type_id_type(self, employee_type_id_type: str) -> UpdateOfferRequestBuilder: ...
    def offer_id(self, offer_id: str) -> UpdateOfferRequestBuilder: ...
    def request_body(self, request_body: OfferInfo) -> UpdateOfferRequestBuilder: ...
    def build(self) -> UpdateOfferRequest: ...
