from .i18n import I18n as I18n
from .user_business_management_scope import UserBusinessManagementScope as UserBusinessManagementScope
from lark_oapi.core.construct import init as init

class UserRole:
    user_id: str | None
    role_id: str | None
    modify_time: str | None
    role_name: I18n | None
    role_description: I18n | None
    business_management_scopes: list[UserBusinessManagementScope] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserRoleBuilder: ...

class UserRoleBuilder:
    def __init__(self) -> None: ...
    def user_id(self, user_id: str) -> UserRoleBuilder: ...
    def role_id(self, role_id: str) -> UserRoleBuilder: ...
    def modify_time(self, modify_time: str) -> UserRoleBuilder: ...
    def role_name(self, role_name: I18n) -> UserRoleBuilder: ...
    def role_description(self, role_description: I18n) -> UserRoleBuilder: ...
    def business_management_scopes(self, business_management_scopes: list[UserBusinessManagementScope]) -> UserRoleBuilder: ...
    def build(self) -> UserRole: ...
