from .entity_info import EntityInfo as EntityInfo
from .permission_scope_rule import PermissionScopeRule as PermissionScopeRule
from lark_oapi.core.construct import init as init

class UserBusinessManagementScope:
    entity: EntityInfo | None
    scope_rule: PermissionScopeRule | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> UserBusinessManagementScopeBuilder: ...

class UserBusinessManagementScopeBuilder:
    def __init__(self) -> None: ...
    def entity(self, entity: EntityInfo) -> UserBusinessManagementScopeBuilder: ...
    def scope_rule(self, scope_rule: PermissionScopeRule) -> UserBusinessManagementScopeBuilder: ...
    def build(self) -> UserBusinessManagementScope: ...
