from .website_delivery_customized_data import WebsiteDeliveryCustomizedData as WebsiteDeliveryCustomizedData
from lark_oapi.core.construct import init as init

class WebsiteDeliveryProject:
    customized_data: list[WebsiteDeliveryCustomizedData] | None
    desc: str | None
    end_time: int | None
    link: str | None
    name: str | None
    role: str | None
    start_time: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WebsiteDeliveryProjectBuilder: ...

class WebsiteDeliveryProjectBuilder:
    def __init__(self) -> None: ...
    def customized_data(self, customized_data: list[WebsiteDeliveryCustomizedData]) -> WebsiteDeliveryProjectBuilder: ...
    def desc(self, desc: str) -> WebsiteDeliveryProjectBuilder: ...
    def end_time(self, end_time: int) -> WebsiteDeliveryProjectBuilder: ...
    def link(self, link: str) -> WebsiteDeliveryProjectBuilder: ...
    def name(self, name: str) -> WebsiteDeliveryProjectBuilder: ...
    def role(self, role: str) -> WebsiteDeliveryProjectBuilder: ...
    def start_time(self, start_time: int) -> WebsiteDeliveryProjectBuilder: ...
    def build(self) -> WebsiteDeliveryProject: ...
