from .website_delivery_customized_data import WebsiteDeliveryCustomizedData as WebsiteDeliveryCustomizedData
from lark_oapi.core.construct import init as init

class WebsiteDeliveryInternship:
    desc: str | None
    end_time: int | None
    start_time: int | None
    title: str | None
    company: str | None
    customized_data: list[WebsiteDeliveryCustomizedData] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WebsiteDeliveryInternshipBuilder: ...

class WebsiteDeliveryInternshipBuilder:
    def __init__(self) -> None: ...
    def desc(self, desc: str) -> WebsiteDeliveryInternshipBuilder: ...
    def end_time(self, end_time: int) -> WebsiteDeliveryInternshipBuilder: ...
    def start_time(self, start_time: int) -> WebsiteDeliveryInternshipBuilder: ...
    def title(self, title: str) -> WebsiteDeliveryInternshipBuilder: ...
    def company(self, company: str) -> WebsiteDeliveryInternshipBuilder: ...
    def customized_data(self, customized_data: list[WebsiteDeliveryCustomizedData]) -> WebsiteDeliveryInternshipBuilder: ...
    def build(self) -> WebsiteDeliveryInternship: ...
