from .website_delivery_customized_data import WebsiteDeliveryCustomizedData as WebsiteDeliveryCustomizedData
from .website_delivery_identification import WebsiteDeliveryIdentification as WebsiteDeliveryIdentification
from lark_oapi.core.construct import init as init

class WebsiteDeliveryBasicInfo:
    nationality_id: str | None
    start_work_time: int | None
    current_home_address: str | None
    hometown_city_code: str | None
    mobile_country_code: str | None
    identification: WebsiteDeliveryIdentification | None
    marital_status: int | None
    mobile: str | None
    current_city_code: str | None
    experience_years: int | None
    gender: int | None
    birthday: int | None
    name: str | None
    preferred_city_code_list: list[str] | None
    resume_source_id: str | None
    age: int | None
    customized_data: list[WebsiteDeliveryCustomizedData] | None
    email: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WebsiteDeliveryBasicInfoBuilder: ...

class WebsiteDeliveryBasicInfoBuilder:
    def __init__(self) -> None: ...
    def nationality_id(self, nationality_id: str) -> WebsiteDeliveryBasicInfoBuilder: ...
    def start_work_time(self, start_work_time: int) -> WebsiteDeliveryBasicInfoBuilder: ...
    def current_home_address(self, current_home_address: str) -> WebsiteDeliveryBasicInfoBuilder: ...
    def hometown_city_code(self, hometown_city_code: str) -> WebsiteDeliveryBasicInfoBuilder: ...
    def mobile_country_code(self, mobile_country_code: str) -> WebsiteDeliveryBasicInfoBuilder: ...
    def identification(self, identification: WebsiteDeliveryIdentification) -> WebsiteDeliveryBasicInfoBuilder: ...
    def marital_status(self, marital_status: int) -> WebsiteDeliveryBasicInfoBuilder: ...
    def mobile(self, mobile: str) -> WebsiteDeliveryBasicInfoBuilder: ...
    def current_city_code(self, current_city_code: str) -> WebsiteDeliveryBasicInfoBuilder: ...
    def experience_years(self, experience_years: int) -> WebsiteDeliveryBasicInfoBuilder: ...
    def gender(self, gender: int) -> WebsiteDeliveryBasicInfoBuilder: ...
    def birthday(self, birthday: int) -> WebsiteDeliveryBasicInfoBuilder: ...
    def name(self, name: str) -> WebsiteDeliveryBasicInfoBuilder: ...
    def preferred_city_code_list(self, preferred_city_code_list: list[str]) -> WebsiteDeliveryBasicInfoBuilder: ...
    def resume_source_id(self, resume_source_id: str) -> WebsiteDeliveryBasicInfoBuilder: ...
    def age(self, age: int) -> WebsiteDeliveryBasicInfoBuilder: ...
    def customized_data(self, customized_data: list[WebsiteDeliveryCustomizedData]) -> WebsiteDeliveryBasicInfoBuilder: ...
    def email(self, email: str) -> WebsiteDeliveryBasicInfoBuilder: ...
    def build(self) -> WebsiteDeliveryBasicInfo: ...
