from .website_delivery_customized_data import WebsiteDeliveryCustomizedData as WebsiteDeliveryCustomizedData
from lark_oapi.core.construct import init as init

class WebsiteDeliveryCompetition:
    customized_data: list[WebsiteDeliveryCustomizedData] | None
    desc: str | None
    name: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WebsiteDeliveryCompetitionBuilder: ...

class WebsiteDeliveryCompetitionBuilder:
    def __init__(self) -> None: ...
    def customized_data(self, customized_data: list[WebsiteDeliveryCustomizedData]) -> WebsiteDeliveryCompetitionBuilder: ...
    def desc(self, desc: str) -> WebsiteDeliveryCompetitionBuilder: ...
    def name(self, name: str) -> WebsiteDeliveryCompetitionBuilder: ...
    def build(self) -> WebsiteDeliveryCompetition: ...
