from lark_oapi.core.construct import init as init

class WebsiteDeliveryAttachmentIndentification:
    identification_type: int | None
    identification_number: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WebsiteDeliveryAttachmentIndentificationBuilder: ...

class WebsiteDeliveryAttachmentIndentificationBuilder:
    def __init__(self) -> None: ...
    def identification_type(self, identification_type: int) -> WebsiteDeliveryAttachmentIndentificationBuilder: ...
    def identification_number(self, identification_number: str) -> WebsiteDeliveryAttachmentIndentificationBuilder: ...
    def build(self) -> WebsiteDeliveryAttachmentIndentification: ...
