from .website_delivery_award import WebsiteDeliveryAward as WebsiteDeliveryAward
from .website_delivery_basic_info import WebsiteDeliveryBasicInfo as WebsiteDeliveryBasicInfo
from .website_delivery_career import WebsiteDeliveryCareer as WebsiteDeliveryCareer
from .website_delivery_customized_data_parent import WebsiteDeliveryCustomizedDataParent as WebsiteDeliveryCustomizedDataParent
from .website_delivery_education import WebsiteDeliveryEducation as WebsiteDeliveryEducation
from .website_delivery_internship import WebsiteDeliveryInternship as WebsiteDeliveryInternship
from .website_delivery_language import WebsiteDeliveryLanguage as WebsiteDeliveryLanguage
from .website_delivery_project import WebsiteDeliveryProject as WebsiteDeliveryProject
from .website_delivery_self_evaluation import WebsiteDeliverySelfEvaluation as WebsiteDeliverySelfEvaluation
from .website_delivery_sns import WebsiteDeliverySns as WebsiteDeliverySns
from .website_delivery_works import WebsiteDeliveryWorks as WebsiteDeliveryWorks
from lark_oapi.core.construct import init as init

class WebsiteDeliveryResume:
    internship_list: list[WebsiteDeliveryInternship] | None
    basic_info: WebsiteDeliveryBasicInfo | None
    education_list: list[WebsiteDeliveryEducation] | None
    self_evaluation: WebsiteDeliverySelfEvaluation | None
    career_list: list[WebsiteDeliveryCareer] | None
    customized_data: list[WebsiteDeliveryCustomizedDataParent] | None
    resume_attachment_id: str | None
    sns_list: list[WebsiteDeliverySns] | None
    works_list: list[WebsiteDeliveryWorks] | None
    award_list: list[WebsiteDeliveryAward] | None
    project_list: list[WebsiteDeliveryProject] | None
    language_list: list[WebsiteDeliveryLanguage] | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WebsiteDeliveryResumeBuilder: ...

class WebsiteDeliveryResumeBuilder:
    def __init__(self) -> None: ...
    def internship_list(self, internship_list: list[WebsiteDeliveryInternship]) -> WebsiteDeliveryResumeBuilder: ...
    def basic_info(self, basic_info: WebsiteDeliveryBasicInfo) -> WebsiteDeliveryResumeBuilder: ...
    def education_list(self, education_list: list[WebsiteDeliveryEducation]) -> WebsiteDeliveryResumeBuilder: ...
    def self_evaluation(self, self_evaluation: WebsiteDeliverySelfEvaluation) -> WebsiteDeliveryResumeBuilder: ...
    def career_list(self, career_list: list[WebsiteDeliveryCareer]) -> WebsiteDeliveryResumeBuilder: ...
    def customized_data(self, customized_data: list[WebsiteDeliveryCustomizedDataParent]) -> WebsiteDeliveryResumeBuilder: ...
    def resume_attachment_id(self, resume_attachment_id: str) -> WebsiteDeliveryResumeBuilder: ...
    def sns_list(self, sns_list: list[WebsiteDeliverySns]) -> WebsiteDeliveryResumeBuilder: ...
    def works_list(self, works_list: list[WebsiteDeliveryWorks]) -> WebsiteDeliveryResumeBuilder: ...
    def award_list(self, award_list: list[WebsiteDeliveryAward]) -> WebsiteDeliveryResumeBuilder: ...
    def project_list(self, project_list: list[WebsiteDeliveryProject]) -> WebsiteDeliveryResumeBuilder: ...
    def language_list(self, language_list: list[WebsiteDeliveryLanguage]) -> WebsiteDeliveryResumeBuilder: ...
    def build(self) -> WebsiteDeliveryResume: ...
