from .website_job_post_customized_option import WebsiteJobPostCustomizedOption as WebsiteJobPostCustomizedOption
from .website_job_post_customized_time_range import WebsiteJobPostCustomizedTimeRange as WebsiteJobPostCustomizedTimeRange
from lark_oapi.core.construct import init as init

class WebsiteJobPostCustomizedValue:
    content: str | None
    option: WebsiteJobPostCustomizedOption | None
    option_list: list[WebsiteJobPostCustomizedOption] | None
    time_range: WebsiteJobPostCustomizedTimeRange | None
    time: str | None
    number: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WebsiteJobPostCustomizedValueBuilder: ...

class WebsiteJobPostCustomizedValueBuilder:
    def __init__(self) -> None: ...
    def content(self, content: str) -> WebsiteJobPostCustomizedValueBuilder: ...
    def option(self, option: WebsiteJobPostCustomizedOption) -> WebsiteJobPostCustomizedValueBuilder: ...
    def option_list(self, option_list: list[WebsiteJobPostCustomizedOption]) -> WebsiteJobPostCustomizedValueBuilder: ...
    def time_range(self, time_range: WebsiteJobPostCustomizedTimeRange) -> WebsiteJobPostCustomizedValueBuilder: ...
    def time(self, time: str) -> WebsiteJobPostCustomizedValueBuilder: ...
    def number(self, number: str) -> WebsiteJobPostCustomizedValueBuilder: ...
    def build(self) -> WebsiteJobPostCustomizedValue: ...
