from .website_delivery_customized_data import WebsiteDeliveryCustomizedData as WebsiteDeliveryCustomizedData
from lark_oapi.core.construct import init as init

class WebsiteDeliveryLanguage:
    customized_data: list[WebsiteDeliveryCustomizedData] | None
    language: int | None
    proficiency: int | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WebsiteDeliveryLanguageBuilder: ...

class WebsiteDeliveryLanguageBuilder:
    def __init__(self) -> None: ...
    def customized_data(self, customized_data: list[WebsiteDeliveryCustomizedData]) -> WebsiteDeliveryLanguageBuilder: ...
    def language(self, language: int) -> WebsiteDeliveryLanguageBuilder: ...
    def proficiency(self, proficiency: int) -> WebsiteDeliveryLanguageBuilder: ...
    def build(self) -> WebsiteDeliveryLanguage: ...
