from .i18n import I18n as I18n
from .website_job_post_customized_value import WebsiteJobPostCustomizedValue as WebsiteJobPostCustomizedValue
from lark_oapi.core.construct import init as init

class WebsiteJobPostCustomizedData:
    object_id: str | None
    name: I18n | None
    object_type: int | None
    value: WebsiteJobPostCustomizedValue | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WebsiteJobPostCustomizedDataBuilder: ...

class WebsiteJobPostCustomizedDataBuilder:
    def __init__(self) -> None: ...
    def object_id(self, object_id: str) -> WebsiteJobPostCustomizedDataBuilder: ...
    def name(self, name: I18n) -> WebsiteJobPostCustomizedDataBuilder: ...
    def object_type(self, object_type: int) -> WebsiteJobPostCustomizedDataBuilder: ...
    def value(self, value: WebsiteJobPostCustomizedValue) -> WebsiteJobPostCustomizedDataBuilder: ...
    def build(self) -> WebsiteJobPostCustomizedData: ...
