from lark_oapi.core.construct import init as init

class WebsiteDeliveryCustomizedData:
    object_id: str | None
    value: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WebsiteDeliveryCustomizedDataBuilder: ...

class WebsiteDeliveryCustomizedDataBuilder:
    def __init__(self) -> None: ...
    def object_id(self, object_id: str) -> WebsiteDeliveryCustomizedDataBuilder: ...
    def value(self, value: str) -> WebsiteDeliveryCustomizedDataBuilder: ...
    def build(self) -> WebsiteDeliveryCustomizedData: ...
