from lark_oapi.core.construct import init as init

class WebsiteDeliveryWorksAttachment:
    file_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WebsiteDeliveryWorksAttachmentBuilder: ...

class WebsiteDeliveryWorksAttachmentBuilder:
    def __init__(self) -> None: ...
    def file_id(self, file_id: str) -> WebsiteDeliveryWorksAttachmentBuilder: ...
    def build(self) -> WebsiteDeliveryWorksAttachment: ...
