from lark_oapi.core.construct import init as init

class WithdrawReferralAccountRequestBody:
    withdraw_bonus_type: list[int] | None
    external_order_id: str | None
    def __init__(self, d=None) -> None: ...
    @staticmethod
    def builder() -> WithdrawReferralAccountRequestBodyBuilder: ...

class WithdrawReferralAccountRequestBodyBuilder:
    def __init__(self) -> None: ...
    def withdraw_bonus_type(self, withdraw_bonus_type: list[int]) -> WithdrawReferralAccountRequestBodyBuilder: ...
    def external_order_id(self, external_order_id: str) -> WithdrawReferralAccountRequestBodyBuilder: ...
    def build(self) -> WithdrawReferralAccountRequestBody: ...
