from ..model.create_spreadsheet_sheet_filter_view_condition_request import CreateSpreadsheetSheetFilterViewConditionRequest as CreateSpreadsheetSheetFilterViewConditionRequest
from ..model.create_spreadsheet_sheet_filter_view_condition_response import CreateSpreadsheetSheetFilterViewConditionResponse as CreateSpreadsheetSheetFilterViewConditionResponse
from ..model.delete_spreadsheet_sheet_filter_view_condition_request import DeleteSpreadsheetSheetFilterViewConditionRequest as DeleteSpreadsheetSheetFilterViewConditionRequest
from ..model.delete_spreadsheet_sheet_filter_view_condition_response import DeleteSpreadsheetSheetFilterViewConditionResponse as DeleteSpreadsheetSheetFilterViewConditionResponse
from ..model.get_spreadsheet_sheet_filter_view_condition_request import GetSpreadsheetSheetFilterViewConditionRequest as GetSpreadsheetSheetFilterViewConditionRequest
from ..model.get_spreadsheet_sheet_filter_view_condition_response import GetSpreadsheetSheetFilterViewConditionResponse as GetSpreadsheetSheetFilterViewConditionResponse
from ..model.query_spreadsheet_sheet_filter_view_condition_request import QuerySpreadsheetSheetFilterViewConditionRequest as QuerySpreadsheetSheetFilterViewConditionRequest
from ..model.query_spreadsheet_sheet_filter_view_condition_response import QuerySpreadsheetSheetFilterViewConditionResponse as QuerySpreadsheetSheetFilterViewConditionResponse
from ..model.update_spreadsheet_sheet_filter_view_condition_request import UpdateSpreadsheetSheetFilterViewConditionRequest as UpdateSpreadsheetSheetFilterViewConditionRequest
from ..model.update_spreadsheet_sheet_filter_view_condition_response import UpdateSpreadsheetSheetFilterViewConditionResponse as UpdateSpreadsheetSheetFilterViewConditionResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class SpreadsheetSheetFilterViewCondition:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def create(self, request: CreateSpreadsheetSheetFilterViewConditionRequest, option: RequestOption | None = None) -> CreateSpreadsheetSheetFilterViewConditionResponse: ...
    async def acreate(self, request: CreateSpreadsheetSheetFilterViewConditionRequest, option: RequestOption | None = None) -> CreateSpreadsheetSheetFilterViewConditionResponse: ...
    def delete(self, request: DeleteSpreadsheetSheetFilterViewConditionRequest, option: RequestOption | None = None) -> DeleteSpreadsheetSheetFilterViewConditionResponse: ...
    async def adelete(self, request: DeleteSpreadsheetSheetFilterViewConditionRequest, option: RequestOption | None = None) -> DeleteSpreadsheetSheetFilterViewConditionResponse: ...
    def get(self, request: GetSpreadsheetSheetFilterViewConditionRequest, option: RequestOption | None = None) -> GetSpreadsheetSheetFilterViewConditionResponse: ...
    async def aget(self, request: GetSpreadsheetSheetFilterViewConditionRequest, option: RequestOption | None = None) -> GetSpreadsheetSheetFilterViewConditionResponse: ...
    def query(self, request: QuerySpreadsheetSheetFilterViewConditionRequest, option: RequestOption | None = None) -> QuerySpreadsheetSheetFilterViewConditionResponse: ...
    async def aquery(self, request: QuerySpreadsheetSheetFilterViewConditionRequest, option: RequestOption | None = None) -> QuerySpreadsheetSheetFilterViewConditionResponse: ...
    def update(self, request: UpdateSpreadsheetSheetFilterViewConditionRequest, option: RequestOption | None = None) -> UpdateSpreadsheetSheetFilterViewConditionResponse: ...
    async def aupdate(self, request: UpdateSpreadsheetSheetFilterViewConditionRequest, option: RequestOption | None = None) -> UpdateSpreadsheetSheetFilterViewConditionResponse: ...
