from ..model.find_spreadsheet_sheet_request import FindSpreadsheetSheetRequest as FindSpreadsheetSheetRequest
from ..model.find_spreadsheet_sheet_response import FindSpreadsheetSheetResponse as FindSpreadsheetSheetResponse
from ..model.get_spreadsheet_sheet_request import GetSpreadsheetSheetRequest as GetSpreadsheetSheetRequest
from ..model.get_spreadsheet_sheet_response import GetSpreadsheetSheetResponse as GetSpreadsheetSheetResponse
from ..model.move_dimension_spreadsheet_sheet_request import MoveDimensionSpreadsheetSheetRequest as MoveDimensionSpreadsheetSheetRequest
from ..model.move_dimension_spreadsheet_sheet_response import MoveDimensionSpreadsheetSheetResponse as MoveDimensionSpreadsheetSheetResponse
from ..model.query_spreadsheet_sheet_request import QuerySpreadsheetSheetRequest as QuerySpreadsheetSheetRequest
from ..model.query_spreadsheet_sheet_response import QuerySpreadsheetSheetResponse as QuerySpreadsheetSheetResponse
from ..model.replace_spreadsheet_sheet_request import ReplaceSpreadsheetSheetRequest as ReplaceSpreadsheetSheetRequest
from ..model.replace_spreadsheet_sheet_response import ReplaceSpreadsheetSheetResponse as ReplaceSpreadsheetSheetResponse
from lark_oapi.core import JSON as JSON
from lark_oapi.core.const import APPLICATION_JSON as APPLICATION_JSON, CONTENT_TYPE as CONTENT_TYPE, UTF_8 as UTF_8
from lark_oapi.core.http import Transport as Transport
from lark_oapi.core.model import Config as Config, RawResponse as RawResponse, RequestOption as RequestOption
from lark_oapi.core.token import verify as verify
from lark_oapi.core.utils import Files as Files
from requests_toolbelt import MultipartEncoder as MultipartEncoder

class SpreadsheetSheet:
    config: Config
    def __init__(self, config: Config) -> None: ...
    def find(self, request: FindSpreadsheetSheetRequest, option: RequestOption | None = None) -> FindSpreadsheetSheetResponse: ...
    async def afind(self, request: FindSpreadsheetSheetRequest, option: RequestOption | None = None) -> FindSpreadsheetSheetResponse: ...
    def get(self, request: GetSpreadsheetSheetRequest, option: RequestOption | None = None) -> GetSpreadsheetSheetResponse: ...
    async def aget(self, request: GetSpreadsheetSheetRequest, option: RequestOption | None = None) -> GetSpreadsheetSheetResponse: ...
    def move_dimension(self, request: MoveDimensionSpreadsheetSheetRequest, option: RequestOption | None = None) -> MoveDimensionSpreadsheetSheetResponse: ...
    async def amove_dimension(self, request: MoveDimensionSpreadsheetSheetRequest, option: RequestOption | None = None) -> MoveDimensionSpreadsheetSheetResponse: ...
    def query(self, request: QuerySpreadsheetSheetRequest, option: RequestOption | None = None) -> QuerySpreadsheetSheetResponse: ...
    async def aquery(self, request: QuerySpreadsheetSheetRequest, option: RequestOption | None = None) -> QuerySpreadsheetSheetResponse: ...
    def replace(self, request: ReplaceSpreadsheetSheetRequest, option: RequestOption | None = None) -> ReplaceSpreadsheetSheetResponse: ...
    async def areplace(self, request: ReplaceSpreadsheetSheetRequest, option: RequestOption | None = None) -> ReplaceSpreadsheetSheetResponse: ...
